### ISSUE TITLE
How to identify proper reason of MSALErrorUserCanceled

### ISSUE THREAD

**Issue by pavelreva1998** [AzureAD/microsoft-authentication-library-for-objc#1012]
Hi,
We are using iOS and MSAL library for authorization, I've identified that in the list of errors we have MSALErrorUserCanceled, this one can be triggered(at least) for signIn&up flow, when the user cancels the flow actively by profession the button "Cancel" or when "forgot password" button was clicked or when the user clicks cancel on sign up page.

The difference in the errors is in the code, which we have in the description, like this:

AADB2C90118 - forgot password
AADB2C90091 - cancel sign up

So, can we make error handling, which is based on these codes, e.g. we got MSALErrorUserCanceled with code AADB2C90118, can we be sure for 100%, that we need to run forgot password flow in this case?

Thanks for your response!

**Comment by jasoncoolmax** [comment]
Hi @pavelreva1998 , user could have different ways to cancel the flow. If you don't see `MSALErrorDescriptionKey` in error's `userInfo`, it means user clicks the cancel button on the webview navigation bar. If you see `MSALErrorDescriptionKey` in error's `userInfo`, it means user clicks something in the web page to cancel the flow. Detailed reason needs to be found from the `MSALErrorDescriptionKey` value in error's `userInfo`.

Hope the above info can help.

**Comment by pavelreva1998** [comment]
Thanks for your answer, @jasoncoolmax, I know it. My question was about codes on `userInfo`. Can I identify the reason via the codes, like AADB2C90118 for forgot password or it would be wrong way?

**Comment by pavelreva1998** [comment]
The reason why I need it, the string in `userInfo` is not localized and user-friendly, so when I catch the error, I need to do something(like start forgot password flow) or show the user what was wrong(localized, user-friendly message)

**Comment by jasoncoolmax** [comment]
Hi @pavelreva1998 , yes, you can identify the reason via the codes. Please refer the following documentation regarding B2C error codes: https://docs.microsoft.com/en-us/azure/active-directory-b2c/error-codes

**Comment by pavelreva1998** [comment]
Breathtaking, thanks a lot, that's exactly what I need
