### ISSUE TITLE
The user can close the webview and cannot login after that

### ISSUE THREAD

**Issue by odarynakorolevych** [AzureAD/microsoft-authentication-library-for-objc#1023]
Hi everyone,
We noticed in the release of MSAL (1.1.2) the issue, that user is able to swipe down the webView (we are using ASWebAuthenticationSession). If he/she wants to login again 'Only one interactive session is allowed at a time' error is received. So first issue is that we don't receive any callback with error from you, when the user swiped down webView. Second issue (more major) is that login after that is not possible.

As far as I remember in earlier versions the user was not able to swipe down the webView and everything worked in that case correctly.

**Comment by hieunguyenmsft** [comment]
Hi @odarynakorolevych, thanks for reporting this bug. I verify that I can reproduce the bug in both 1.1.2 and 1.1.7.
I will look into that and update you on the result.

**Comment by hieunguyenmsft** [comment]
A bug was filed with Apple as we can't control the swipe down event in ASWebAuthenticationSession and Apple didn't trigger the callback at that moment. We will update when have a response from Apple.
