### ISSUE TITLE
How can i Customize the authenticate name？

### ISSUE THREAD

**Issue by ws752958369** [AzureAD/microsoft-authentication-library-for-objc#1028]
Phenomenon:
When I use MSAL to trigger single sign-on, the App will pop up an alert box asking "xxx" to visit "microsoftonline.com".
Question:
1.How is The "xxx"  defined by the MSAL SDK ?
2.How can i rename the "xxx" ?
Attached is the screenshot part，please help me . Thank you.
![ACFCF690-ACCB-4062-8387-A000784585D0](https://user-images.githubusercontent.com/15607355/89042555-ae7aac00-d379-11ea-90ae-e8febe3a8c60.png)

**Comment by oldalton** [comment]
MSAL uses ASWebAuthenticationSession. This alert is shown by iOS and name is determined based on your application's Info.plist.

**Comment by ws752958369** [comment]
@oldalton  Thank you so much.,i have solved this problem.
