### ISSUE TITLE
Authenticator App not able to register the Device for workplace Join to AAD.

### ISSUE THREAD

**Issue by rahulcode** [AzureAD/microsoft-authentication-library-for-objc#1044]
Microsoft Authenticator Production App.

Setup :
ADFS user

Scenario : 
Registering the device from the Microsoft Authenticator App.

Behavior Noticed :

1) ADFS user login works properly from Safari. ( Safari prompts 1 time on device to accept the risk and continue.) 
The user is able to login and access the resource like outlook.

**Issue**
If we try to register the device using Microsoft authenticator, the Page Opens up for Authentication and closes with a error.

Expected :
Redirection should have happened to the ADFS authentication page and user could have continued with the authentication.

**Error Image**

![IMG_0334](https://user-images.githubusercontent.com/19573187/89531755-5b3baa00-d80e-11ea-9d43-342c35374909.PNG)

**Attached Logs** **Microsoft Authenticator App logs**
[Microsoft Authenticator Issue for Invalid Certificate But Safari works.txt](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/5034763/Microsoft.Authenticator.Issue.for.Invalid.Certificate.But.Safari.works.txt)

**Comment by rohitnarula7176** [comment]
@rahulcode Can you try the same flow after disabling your vpn. There might be a proxy causing network issues.

**Comment by rahulcode** [comment]
Hi @rohitnarula7176 

For our setup to connect to our ADFS authentication Page we need VPN on our device.

From Safari, the same login workflow works absolutely fine and loads the ADFS login page after redirection.
Authentication also succeeds.

But trying the same with Authenticator App suddenly gives the issue.

`), NSErrorFailingURLStringKey=https://adfsf21.forest21.fiberlinkqa.local/adfs/ls/?login_hint=test1%40forest37.redroverlife.com&client-request-id=eacb9a42-fa9f-4ebf-8fa1-9e19be3387ae&username=test1%40forest37.redroverlife.com&wa=wsignin1.0&wtrealm=urn%3afederation%3aMicrosoftOnline&wctx=estsredirect%3d2%26estsrequest%3drQIIAZVSv2_TUBDOi5OQWhSiwlAmPDAgKv-uG2MJiSStQkIcQxqakAW9OM_Ji2K_9PmFhExMwEbFhCoEgoGhEgghBoQETCxh6Vh1Zqg6MSImHP6DSqfvdN_p-3S6Oz6pSqpkLAH1CqdJinVp1VR13dSgaHowK65qBhJhO2uIegQ6hG0dttt0ic_kd38ev_r7vfr09csL3_TH7_eA7IdwxHqSS3zJxy4lIfGYBKcjiuY8Chh2ISPUkuV5LX8GYB-AZ_GLDIVMve4RGmU9K1HUoeQ-ogPsobnZfhwcxs86uUijzYFQPEW7nFLr3zVq9d66Pc0xe9p9YBcUpXqnmq9EnFO32e3-VtGpb6i2Us076662x4kjGlh-KHZoaEXjIDqkOEQUdXHIKGSYBNIYBx0yDqUAsY_cIqFdGODp_1Y44-on0stSB3lwNGACGaIAd4QhJR4eIIF43gAH6B50XRSGBxzYSYD9BDhOCGmQActJIXY5o8StdHoxk1qOCbFyOs1F_IIQ-5MAb5LR8rOPfhz08dvS10-_Xjx8J8RmSXmtdaPbM1DdLQzlPt02PLXbMpDZbK6UKqTl2tV8f6PBGqSYc69plnqUBDupKM7NUml7M1eRsLP5OwWenIp9WZBOdsjnPNjjV8alyWi7oNaK5ZxZ7m6W_UbeMX0yUW5q4hZxVrFYyE_HTWNyy_3Ag0P-vKZoiqiYorImqJqlXLV0o3V4-gy_0IOh26PER9FT_gM1#, NSUnderlyingError=0x281893ae0 \\\{Error Domain=kCFErrorDomainCFNetwork Code=-1202 "(null)" UserInfo=\\\{_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9807, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9807\\\}\\\}, NSErrorClientCertificateStateKey=0, NSErrorFailingURLKey=https://adfsf21.forest21.fiberlinkqa.local/adfs/ls/?login_hint=test1%40forest37.redroverlife.com&client-request-id=eacb9a42-fa9f-4ebf-8fa1-9e19be3387ae&username=test1%40forest37.redroverlife.com&wa=wsignin1.0&wtrealm=urn%3afederation%3aMicrosoftOnline&wctx=estsredirect%3d2%26estsrequest%3drQIIAZVSv2_TUBDOi5OQWhSiwlAmPDAgKv-uG2MJiSStQkIcQxqakAW9OM_Ji2K_9PmFhExMwEbFhCoEgoGhEgghBoQETCxh6Vh1Zqg6MSImHP6DSqfvdN_p-3S6Oz6pSqpkLAH1CqdJinVp1VR13dSgaHowK65qBhJhO2uIegQ6hG0dttt0ic_kd38ev_r7vfr09csL3_TH7_eA7IdwxHqSS3zJxy4lIfGYBKcjiuY8Chh2ISPUkuV5LX8GYB-AZ_GLDIVMve4RGmU9K1HUoeQ-ogPsobnZfhwcxs86uUijzYFQPEW7nFLr3zVq9d66Pc0xe9p9YBcUpXqnmq9EnFO32e3-VtGpb6i2Us076662x4kjGlh-KHZoaEXjIDqkOEQUdXHIKGSYBNIYBx0yDqUAsY_cIqFdGODp_1Y44-on0stSB3lwNGACGaIAd4QhJR4eIIF43gAH6B50XRSGBxzYSYD9BDhOCGmQActJIXY5o8StdHoxk1qOCbFyOs1F_IIQ-5MAb5LR8rOPfhz08dvS10-_Xjx8J8RmSXmtdaPbM1DdLQzlPt02PLXbMpDZbK6UKqTl2tV8f6PBGqSYc69plnqUBDupKM7NUml7M1eRsLP5OwWenIp9WZBOdsjnPNjjV8alyWi7oNaK5ZxZ7m6W_UbeMX0yUW5q4hZxVrFYyE_HTWNyy_3Ag0P-vKZoiqiYorImqJqlXLV0o3V4-gy_0IOh26PER9FT_gM1#, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask [2BDDE1A2-4A0E-46E0-B5BD-7E39DA827DE4].[19], NSURLErrorFailingURLPeerTrustErrorKey=[SecTrustRef: 0x282412d90], NSLocalizedDescription=The certificate for this server is invalid. You might be connecting to a server that is pretending to be \\'93adfsf21.forest21.fiberlinkqa.local\\'94 which could put your confidential information at risk.\\\}\\\
`

**App is able to resolve the domian but after that the server certificate case fails.**
But on Safari  if the certificate is invalid it prompts the usdr to accept the risk and continue to ADFS page, which is not the case in MA.

![ADFS_Error](https://user-images.githubusercontent.com/19573187/90025320-95f08700-dcd3-11ea-96e7-681134945131.gif)

LOGS : https://gist.github.com/rahulcode/a9c02ec496d81250e17fead0d8c35799

**Authenticator logs show :**

**Comment by mipetriu** [comment]
@rahulcode Unfortunately invalid certificates are not supported by Authenticator, so you will not be able to accept the risk and continue.

**Comment by smudireddy** [comment]
Issue resolved with  1.1.8.
