### ISSUE TITLE
MSAL on iOS 9.3 ?

### ISSUE THREAD

**Issue by RegisStGelais** [AzureAD/microsoft-authentication-library-for-objc#1050]
I need to keep the compatibility of my app to as low as iOS 9.3

Is it possible to to use MSAL on iOS 9.3 ?

**Comment by RegisStGelais** [comment]
I would not mind to only enable MSAL if running on iOS 10 and +
I want to use the graph APIs to add OneDrive access to my app but it would be ok to not have OneDrive access if the user device is running iOS less than iOS 10.
Is that possible ?

**Comment by oldalton** [comment]
We support iOS 11+ at this moment.

**Comment by RegisStGelais** [comment]
Is it possible to build an app that will support MSAL if on the proper version of iOS but still run on older iOS versions without the MSAL capabilities?

When I try to install an app with the MSAL library included, I get a dyld error even if my code calls nothing from the library.

**Comment by rohitnarula7176** [comment]
@RegisStGelais You would get compile time errors if MSAL uses api's that are targeted for iOS 11+ even if you don't call any of its functions. Is that what you are seeing or are you experiencing linking errors.
