### ISSUE TITLE
Issue with signout 

### ISSUE THREAD

**Issue by sharjeelahmed** [AzureAD/microsoft-authentication-library-for-objc#1053]
my app has a loginController from which user can login through MSAL . its working fine and if i perform logout on same controller i.e loginController the signout works perfectly(no webview form is presented) and on just a button click user is successfully sign out from MSAL . 
but in my case i have to do sign out from other controller i.e homeController i put the same code for sign out on home controller  . when i m trying to sign out from Home controller first the popup appear (same popup appears in sign in) . _"my app" want to use "microsoftonline.com" to sign in , this allows the app and website to share information about you"_
and when i click on continue then webview form appears which says _"You signed out from your account"_ . and when i cliked on cancel button of that form then i logout successfully from home controller. 
basically i want to logout the user same as loginController where no webview form is appears . i just clicked on sign out and done

**code for sign out in HomeVC**
```
`@IBAction func signOutLogin(_ sender: UIButton) {
	guard let applicationContext = self.applicationContext else { return }
	self.loadCurrentAccount { (msalaccount) in
		  guard let account = msalaccount else { return }
			  
			  do {
				  
				  /**
				   Removes all tokens from the cache for this application for the provided account
				   
				   - account:    The account to remove from the cache
				   */
				  
				//self.webViewParameters?.parentViewController = self.navigationController

				  let signoutParameters = MSALSignoutParameters(webviewParameters: self.webViewParameters!)
				  signoutParameters.signoutFromBrowser = false // set this to true if you also want to signout from browser or webview
				  
				applicationContext.signout(with:account , signoutParameters: signoutParameters, completionBlock: {(success, error) in
					  
					  if let error = error {
						  //self.updateLogging(text: "Couldn't sign out account with error: \(error)")
						  return
					  }
					  
					 
				  })
				  
			  }
		  }
	}`

```
**Code for sign out in LoginVc** 

	@IBAction func signOut(_ sender: UIButton) {
        
		
        guard let applicationContext = self.applicationContext else { return }
		self.loadCurrentAccount { (msalaccount) in
			  guard let account = msalaccount else { return }
				  
				  do {
					  let signoutParameters = MSALSignoutParameters(webviewParameters: self.webViewParameters!)
					  signoutParameters.signoutFromBrowser = false
					  
					applicationContext.signout(with:account , signoutParameters: signoutParameters, completionBlock: {(success, error) in
				if success == true{
					print("Successfully Logout")
					return
				}
						  if let error = error {
                                                   print("Logout failed")
							  return
						  }
					  })
					  
				  }
			  }
		}

**Comment by sharjeelahmed** [comment]
any idea what i m doing wrong ?

**Comment by oldalton** [comment]
Could you try with the latest MSAL version. We've introduced a few changes to signout behavior that might help with this scenario.
