### ISSUE TITLE
Crashes on didReceiveAuthenticationChallenge callback

### ISSUE THREAD

**Issue by eltonjhony** [AzureAD/microsoft-authentication-library-for-objc#1061]
Hi guys,

I hope you are doing well!

We're using MSAL to login our users on Azure B2C and just after we deploy the code to production we start seeing a lot of crashes (1.715) on Crashlytics that apparently happens inside the MSAL lib. Take a look at the stacktrace:

`Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x1f60f3180 __exceptionPreprocess
1  libobjc.A.dylib                0x1f52cb9f8 objc_exception_throw
2  CoreFoundation                 0x1f600f9bc -[NSOrderedSet initWithSet:copyItems:]
3  CoreFoundation                 0x1f60f89c8 ___forwarding___
4  CoreFoundation                 0x1f60fa65c _CF_forwarding_prep_0
5  WebKit                         0x205757508 WebKit::NavigationState::NavigationClient::didReceiveAuthenticationChallenge(WebKit::WebPageProxy&, WebKit::AuthenticationChallengeProxy&)
6  WebKit                         0x205880b40 WebKit::NetworkProcessProxy::didReceiveAuthenticationChallenge(unsigned long long, unsigned long long, WebCore::AuthenticationChallenge&&, unsigned long long)
7  WebKit                         0x205633154 void IPC::handleMessage<Messages::NetworkProcessProxy::DidReceiveAuthenticationChallenge, WebKit::NetworkProcessProxy, void (WebKit::NetworkProcessProxy::*)(unsigned long long, unsigned long long, WebCore::AuthenticationChallenge&&, unsigned long long)>(IPC::Decoder&, WebKit::NetworkProcessProxy*, void (WebKit::NetworkProcessProxy::*)(unsigned long long, unsigned long long, WebCore::AuthenticationChallenge&&, unsigned long long))
8  WebKit                         0x20560f9a8 IPC::Connection::dispatchMessage(std::__1::unique_ptr<IPC::Decoder, std::__1::default_delete<IPC::Decoder> >)
9  WebKit                         0x205613004 IPC::Connection::dispatchOneIncomingMessage()
10 JavaScriptCore                 0x1fd2c5688 WTF::RunLoop::performWork()
11 JavaScriptCore                 0x1fd2c5908 WTF::RunLoop::performWork(void*)
12 CoreFoundation                 0x1f6084f1c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
13 CoreFoundation                 0x1f6084e9c __CFRunLoopDoSource0
14 CoreFoundation                 0x1f6084784 __CFRunLoopDoSources0
15 CoreFoundation                 0x1f607f6c0 __CFRunLoopRun
16 CoreFoundation                 0x1f607efb4 CFRunLoopRunSpecific
17 GraphicsServices               0x1f828079c GSEventRunModal
18 UIKitCore                      0x2228e0c38 UIApplicationMain
19 Parceiro_Ambev                 0x1005923d0 main + 15 (main.m:15)
20 libdyld.dylib                  0x1f5b428e0 start`

Seems like the error starts on the `didReceiveAuthenticationChallenge` callback. 

Are you guys familiar with this issue? May you help us understand what's happening inside the lib that is causing the crashes?

Let me know if you need more details about the issue. 

Best regards

**Comment by wilmerlm11** [comment]
Hi @oldalton @jasoncoolmax !
Is that something you could help us to address please?
We have many crash reports coming from our customers (and Crashlytics) and it's harshly affecting our business.
Thanks!

**Comment by kaisong1990** [comment]
@eltonjhony @wilmerlm11 Thanks for reporting this issue, is there a way to repro this issue or if we can get some clients' logs (MSAL logs) would be helpful.

Here is the [link](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging?tabs=dotnet#logging-in-msal-for-ios-and-macos) for collecting logs

**Comment by eltonjhony** [comment]
Hi @kaisong1990 

Thanks for your response!

We are currently investigating another possible cause related to the interaction of the NewRelic agent with our WebViews. 
Let's put this issue on hold until we get the confirmation that the issue is on NewRelic.

I'll get back to you as soon we finish this investigation. 
Thanks!

**Comment by eltonjhony** [comment]
Hi @kaisong1990 

Thanks for your help! 
The fix that we made on NewRelic solved the issue! We don't have crashes anymore! 

We can close this issue. 

Best regards

**Comment by nathan-batista** [comment]
Hello @eltonjhony 
I'm facing the same issue, could you please tell me which change you made to NewRelic?
I'm also using NewRelic.
