### ISSUE TITLE
Problem to open telephone in a journey

### ISSUE THREAD

**Issue by ralexandre-ciandt** [AzureAD/microsoft-authentication-library-for-objc#1066]
Hello!

We have a journey with a "support telephone" number in it. It's a link and we are trying to make it open the dialer in the device when clicked by the user. It does work if we open the journey on Chrome, but is there a way we could achieve it in the app that is implementing MSAL? 

Currently, we are getting this error from MSAL:

`Could not acquire token: Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=The server has redirected to a non-https url., MSALInternalErrorCodeKey=-42602, MSALCorrelationIDKey=CA862475-78D4-4E84-8683-FEC9A381D165}`

Thanks!

**Comment by kaisong1990** [comment]
@ralexandre-ciandt Thanks for your question.

Could you try to use the system webView instead of embedded webView in MSAL?

To make the change, please use ```MSALWebviewTypeDefault``` instead of ```MSALWebviewTypeWKWebView``` when assigning ```webviewType``` in ```MSALInteractiveTokenParameters```.

Meanwhile, we will investigate if it will bring any security concern to support phone schema in embedded webView.

**Comment by ralexandre-ciandt** [comment]
Hi!
Changing it to TypeDefault I got the following error when trying to initialize the journey:

`Error Domain=com.apple.AuthenticationServices.WebAuthenticationSession Code=2 "Cannot start ASWebAuthenticationSession without providing presentation context. Set presentationContextProvider before calling -start." UserInfo={NSDebugDescription=Cannot start ASWebAuthenticationSession without providing presentation context. Set presentationContextProvider before calling -start., MSALCorrelationIDKey=CB8AD1BA-D12C-4E4F-A61A-FB4A63A21063}
`

**Comment by kaisong1990** [comment]
When creating ```MSALWebviewParameters```, can you try to set ```parentViewController``` to be a viewController so that the system knows where to present. For example if ```self``` is a viewController, you can do:

webviewParameters.parentViewController = self;

**Comment by ralexandre-ciandt** [comment]
Hi!
Even with this flag we couldn't get the desired behavior, the journey even opens differently like a popup =/
For now, we made the journey return an error so we opened the dialer natively and then refreshed the journey

**Comment by antrix1989** [comment]
Since you found the workaround, I will close this issue. Please let us know if you have other questions.
