### ISSUE TITLE
Cannot consent to different API's with single acquireToken interactive call

### ISSUE THREAD

**Issue by ianloubser** [AzureAD/microsoft-authentication-library-for-objc#1092]
I keep getting the following error when I try to `acquireToken` for multiple API scopes simultaneously.
```
AADSTS650052: The app needs access to a service ("api://4db21fb4-9469-4cc4-89c6-cc7bc8dea8df") that your
organization "....onmicrosoft.com" has not subscribed to or enabled. Contact your IT Admin to review the configuration of 
your service subscriptions
``` 

Is it possible to get consent for multiple API's (MS Graph and own App on Azure) with a single acquireToken interactive call ?

So for instance we want to call acquireToken Interactively with the following 2 scopes:
`api://4db21fb4-9469-4cc4-89c6-cc7bc8dea8df/user_impersonate`
`https://graph.microsoft.com/User.Read`

Here is a snippet of the code we use in our iOS app:
```
        let webviewParams = MSALWebviewParameters(parentViewController: parentView)
        let urlParams = MSALInteractiveTokenParameters(scopes: [ "https://graph.microsoft.com/User.Read" ], webviewParameters: webviewParams)
        urlParams.promptType = .selectAccount
        
        urlParams.extraScopesToConsent = [ "api://4db21fb4-9469-4cc4-89c6-cc7bc8dea8df/user_impersonate" ]

        client?.acquireToken(with: urlParams, completionBlock: {
            (result: MSALResult?, error: Error?) in

             ....
```

I've tried solutions as suggested in this issue (setting default client type to public etc): https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/858 but to no avail ... :(

EDIT: To clarify, we have 2 multi-tenant apps (API & Mobile App) registered on Azure, one for the app and the other which exposes the `user_impersonate` scope. The mobile app has been added as an Authorized Client Application for the `user_impersonate` scope, and the API app has been added as a `knownApplication` in the manifest.

**Comment by ianloubser** [comment]
Also, if I remove the MS graph scope, and only request for our exposed API scope, then the consent screen correctly gets shown. But then I only get to consent to our API and cannot get an access token for MS graph. Would really like to avoid having an interactive request for consenting to both API's 🙂

**Comment by antrix1989** [comment]
Hi @ianloubser, could you provide us correlation id of the error?

**Comment by ianloubser** [comment]
Correlation ID : 1464c183-8b18-461e-85d4-534b14262c92

Thanks @antrix1989  🙂

**Comment by antrix1989** [comment]
Hi @ianloubser, thanks for the correlation id! Could you please run 2 more tests:
- remove graph scope and make a request for 2nd scope only (please capture a correlation ID as well as timestamp)
- add graph scope back and make a new request for both scopes (please capture a correlation ID as well as timestamp)
