### ISSUE TITLE
Intune Data removal Policy

### ISSUE THREAD

**Issue by ShilpaGavade** [AzureAD/microsoft-authentication-library-for-objc#1095]
I am facing issue with organisation data removal policy, as mentioned above I have used both MSAL as well as Intune app protection policy in the app, when I try to login with another user using MSAL, it asks for organisation data removal for first user, when I say yes, it removes data (looks like this) but after that I restart app and try to login another user, getting MSAL error, "(Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=Multiple accounts found in cache., MSALInternalErrorCodeKey=-42102})'", it means it is not clearing cookies or something like that, should we handle this manually?

**Comment by antrix1989** [comment]
Seems you are using [SingleAccount mode](https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/dev/README.md#single-account-mode). If you app support multiple accounts, you shouldn't use this API. Please check out out our [Readme](https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/dev/README.md) file for sample code.

If you app support Single Account only, you will need to delete 1st user by calling this API:
```
- (BOOL)removeAccount:(nonnull MSALAccount *)account
                error:(NSError * _Nullable __autoreleasing * _Nullable)error;
```

**Comment by ShilpaGavade** [comment]
@antrix1989 : Thanks for your response but from where should I call this method as 'organisation data removal' is handled by intune policy then intune library should remove previous user account, right? I went through readme file link mentioned above but did not get proper solution. is there any call back when data removal actually happens, so that, we can handle account removal.

**Comment by ShilpaGavade** [comment]
@ShruthiAchutha : Any update on this?

**Comment by ShruthiAchutha** [comment]
on my team is currently investigating this and will update you on progress.

**Comment by ShilpaGavade** [comment]
@ShruthiAchutha : Thank you for info

**Comment by darosal** [comment]
Hi @ShilpaGavade,

We call the `wipeDataForAccount` delegate in IntuneMAMPolicyDelegate.h when an account is removed. This would be the best place to do any additional cleanup. In order to not get the MSAL error when running on Single Account mode, the `removeAccount` MSAL API should be called here.

Please do note that this delegate requires a `BOOL` return value. If **all** account data is also removed manually as part of implementing the delegate, return `TRUE`. If not return `FALSE`, letting the Intune SDK will continue to do it.

**Comment by ShilpaGavade** [comment]
Hi @darosal , thanks for the answer, just confirming whatever I understood from above comment is, if we return 'False' in wipe data delegate then intune handle all the things itself. If we return 'True' in wipe data delegate then we have to handle account removal manually.
Will try setting 'false' in delegate for now

**Comment by ShilpaGavade** [comment]
@darosal : Your answer will be helpful for us as our devices stopped working for this particular application as not able to sign in again with any other user nor with previous user.

**Comment by darosal** [comment]
@ShilpaGavade, that is correct.

It is worth noting that even if you return `FALSE`, the SDK will not remove the MSAL account data. That needs to be done manually within the delegate.

**Comment by ShilpaGavade** [comment]
@darosal, ok but not getting specific method for remove account in iOS for single account mode, so, just setting currentAccount = nil.
If you have any other solution then please suggest

**Comment by darosal** [comment]
@ShilpaGavade, according to the earlier discussion, I believe the following should be used for removing the account in single account mode.
```
- (BOOL)removeAccount:(nonnull MSALAccount *)account
                error:(NSError * _Nullable __autoreleasing * _Nullable)error;
```

This should be called within the `wipeDataForAccount` delegate. This will completely remove the account, allowing for a future sign in with a different account.

@antrix1989, please correct me if I'm wrong about the MSAL method to use.

**Comment by ShilpaGavade** [comment]
@darosal : I have called MSALPublicClientApplication.remove(account) in wipeData method of IntuneMAMPolicyDelegate, but do we have to assign delegate for IntuneMAMPolicyDelegate?
I have implemented wipeData method of IntuneMAMPolicyDelegate only.

Sorry for troubling but still I am getting the same error.

**Comment by darosal** [comment]
@ShilpaGavade, I see. The delegate needs to be set by the time the application's `UIApplicationDelegate`
`application:willFinishLaunchingWithOptions` method returns. This can be done by calling `[[IntuneMAMPolicyManager instance] setDelegate:...]` there.

**Comment by ShilpaGavade** [comment]
@darosal : i tried setting MAM delegate in willFinishLaunching method like,

func application(_ application: UIApplication, willFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
        IntuneMAMPolicyManager().delegate = self as? IntuneMAMPolicyDelegate
        return true
    }

But not getting any luck as it is throwing multiple account error, is there any way to remove these accounts? we tried uninstalling app but no luck

**Comment by ShilpaGavade** [comment]
I am asking this because our devices are blocked now...

**Comment by darosal** [comment]
@ShilpaGavade Can you confirm that the code within the wipeDelegate is being called by using a breakpoint? I'm trying to see if the issue is that the delegate is never called or that the account data is not being removed when it is called.

**Comment by ShilpaGavade** [comment]
ok, will confirm and update you accordingly.

**Comment by ShilpaGavade** [comment]
@darosal : I am trying on the simulator where already multiple account exist error is coming, so, it is not allowing to navigate on microsoft page for login. 
_Below method is giving error_: 
"**applicationContext.getCurrentAccount(with: msalParameters, completionBlock: { (currentAccount, previousAccount, error) in**",
_error is_:
Optional(Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=Multiple accounts found in cache., MSALInternalErrorCodeKey=-42102})

so, may be, first need to handle remove account method here.

**Comment by ShilpaGavade** [comment]
but again, not able to get account using 'getCurrentAccount' method as it is giving error so, not able to remove specific account.
so, how can we handle this.. I am trying to search in docs but very limited information is available in docs.

**Comment by ShilpaGavade** [comment]
@darosal, please let me know if need any other information from our side, this is causing lots of issues in our ongoing project.

**Comment by ShruthiAchutha** [comment]
@oldalton or @antrix1989 could you help with the MSAL question Shilpa had above?

**Comment by oldalton** [comment]
@ShilpaGavade, you'll need to query account by the identifier since you have multiple accounts in cache. We have a sample code here: https://github.com/AzureAD/microsoft-authentication-library-for-objc#silently-acquiring-an-updated-token

**Comment by ShilpaGavade** [comment]
Hi @oldalton, I managed to remove previous all accounts using applicationContext.allAccounts() but as @darosal mentioned above, at the time of organisation data removal, we should remove account manually but it is not happening because, I checked using breakpoint but it is not reaching to wipeData method

**Comment by darosal** [comment]
@ShilpaGavade, then the delegate might not have been set correctly. I'm not the most familiar with the swift syntax for setting the delegate. But I believe it should be
```
IntuneMAMPolicyManager.instance().delegate = self as? IntuneMAMPolicyDelegate
```
rather than 
```
IntuneMAMPolicyManager().delegate = self as? IntuneMAMPolicyDelegate
```

Is there a reason the second was done instead? Does changing that cause the wipeData delegate to run?

If not, it could be that the wipeData delegate isn't being called even if the IntuneMAMPolicyManager delegate was set correctly. What method is being called to unenroll the user? From earlier in this conversation, it looks like a wipe **is** being called but I want to double check on that end.

**Comment by ShilpaGavade** [comment]
Hi @darosal, Tried assigning IntuneMAMPolicyManager delegate in the way you suggested

`IntuneMAMPolicyManager.instance().delegate = self as? IntuneMAMPolicyDelegate`

but still control not reaching to wipe data method which is written in appDelegate file.
It is not removing previous account details after organisation data removal, sometimes it asks for password for previous account only. 
Very weird behaviour there on organisation data removal

**Comment by darosal** [comment]
@ShilpaGavade, how are you triggering the signout/unenrollment? What actions prompt the organization data removal?

**Comment by ShilpaGavade** [comment]
![image](https://user-images.githubusercontent.com/65016832/96604930-45b92500-1313-11eb-8db1-992fc0325d36.png)
I am getting this pop up with two account options

**Comment by ShilpaGavade** [comment]
After selecting any one of account, getting another popup saying 
**"Your organisation has removed its data associated with this app....To reconnect....."**
After this, all account should get removed

**Comment by ShilpaGavade** [comment]
I am not sure why this issue is marked as 'stale', I think I have provided all the required information still no response from team, if need any other info then please let me know

**Comment by darosal** [comment]
@ShilpaGavade, what is being called that triggers this removal? Is it an additional sign-in?

Also, what is the exact flow of prompts now and when do you see the original MSAL error? I'm trying to see where the MSAL error is happening.

If it is feasible, could you also add code (temporarily) to [call our diagnostic tool](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#how-can-i-troubleshoot-my-app) and then provide the logs it generates? I believe that the wipe prompt you sent an image of should be handling removing the account and triggering the wipe delegate. It's possible that this is not happening because of some state issue. The logs would help determine a reason why.
