### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by guidedways** [AzureAD/microsoft-authentication-library-for-objc#1098]
I'm seeing random crashes reported in App Center from the MSAL.framework on macOS 10.15.6. This wasn't the case earlier.

```
libobjc.A.dylib
objc_release
MSAL
0x1086b9000 + 89851
MSAL
0x1086b9000 + 57874
```

**Comment by antrix1989** [comment]
Could you please provide symbolicated trace and MSAL log?

**Comment by oldalton** [comment]
@guidedways, just following up if you could upload symbolicated crash logs and MSAL logs to continue investigating this issue. Thanks.

**Comment by guidedways** [comment]
@oldalton apologies! I don't know why but I think since we were using Carthage, no symbols were available. We had issues with the latest framework update as macOS 10.11 wasn't supported so had to downgrade anyway. The random crashing stopped. I was unable to reproduce this myself or would have given it a try. I essentially saw AppCenter report numerous crashes on macOS 10.15 (which is officially supported by MSAL) but like I said, we had to go back to a previous version for macOS 10.11 support.

**Comment by oldalton** [comment]
Thanks, please do upload logs if you get any in the future. That will help us a lot.
