### ISSUE TITLE
Login pop up does not show

### ISSUE THREAD

**Issue by genesisemmloh** [AzureAD/microsoft-authentication-library-for-objc#1105]
**i have a reactnative app and i registerd on B2C
my app simple wont get the Login dialog and  i get an error**

i have followed the instructions and add a KeychainSharing, edited de info.plist 
what i see its to different documentations, i have tried with both ways and i get same error.
**Note: for Android the redirect format that worked was, msal<client-id>**
first i read this one;
[https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-ios](url)
but i have also tried with different URlScheme 
like mentioned here:
[https://docs.microsoft.com/en-us/samples/azure-samples/active-directory-b2c-ios-swift-native-msal/microsoft-authentication-library-b2c-ios/](url)

which seams to be unknown.
<img width="1388" alt="ios Error" src="https://user-images.githubusercontent.com/53597236/94133225-b11ced80-fe60-11ea-9ad6-4b8ec1d4ba18.png">

could you help me figuring out whats missing? is this an 404?
@oldalton , thanks girl.

**Comment by oldalton** [comment]
Looks like MSAL is trying to load a network request, but domain is not found.
Could you double check the authority that you're providing MSAL with?

**Comment by genesisemmloh** [comment]
Hi , it's a react native project and In the android version works... I would assume i don't need to change the values for the ios version. But I will give it a try.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by oldalton** [comment]
Thanks. Library configuration might be different between iOS and Android due to platform differences. 
If you could show us your configuration code, and [MSAL log](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging?tabs=android), this would be helpful. Thanks.

**Comment by oldalton** [comment]
@genesisemmloh, did you get it working?

**Comment by genesisemmloh** [comment]
@oldalton hi, good morning, yes it did.
i have changed pretty much all. 

the Authority URL im using now the url with the **tfp** format.
https://<TENANT_NAME>.b2clogin.com/tfp/<TENANT_NAME>.onmicrosoft.com/<POLICY_NAME>

now i use the  RedirectUri format for IOS. and android different,
android:msal[ClientId]://auth
IOS:msauth.[BundleId]://auth

, But definitely what i think change, was the Library im using on my React Native Project, after the update 3.0.1, so make me think something was wrong in there.
[https://github.com/stashenergy/react-native-msal](url)

**Comment by oldalton** [comment]
Great, thanks for confirming. Closing the issue.
