### ISSUE TITLE
AADSTS500031: Cannot find signing certificate configured

### ISSUE THREAD

**Issue by smudireddy** [AzureAD/microsoft-authentication-library-for-objc#1111]
MSAL SDK : 1.1.5

Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=AADSTS500031: Cannot find signing certificate configured.

MSAL-Auth: Internal Error -
{ MSALCorrelationIDKey = "AEB669E6-7FDB-4BAF-B005-237246B5D298"; MSALErrorDescriptionKey = "AADSTS500031: Cannot find signing certificate configured. \nTrace ID: 2ee1cf52-44ed-477e-9906-008f809ba200 \nCorrelation ID: aeb669e6-7fdb-4baf-b005-237246b5d298 \nTimestamp: 2020-09-17 21:00:07Z"; MSALInternalErrorCodeKey = "-42002"; MSALOAuthErrorKey = "invalid_request"; }

**Comment by aherciya** [comment]
Hi @smudireddy can you provide the steps you took while running into this issue such that we can reproduce it? Thanks.

**Comment by smudireddy** [comment]
@aherciya ,
With an ADFS setup, MSAL SDK initialized in our app and user made an interactive login request. 
Authenticator app not used in this workflow. Auth request is inline of the App.

**Comment by smudireddy** [comment]
21/09/2020 15:49:39:397|[548462]|78<Info>: TID=548339 MSAL 1.1.5 iOS 14.0 [2020-09-21 20:49:39 - 274449BD-6832-4C3E-AAE6-B611307BA25D] [MSAL] Beginning interactive flow.
21/09/2020 15:49:39:397|[548462]|78<Info>: TID=548339 MSAL 1.1.5 iOS 14.0 [2020-09-21 20:49:39 - 274449BD-6832-4C3E-AAE6-B611307BA25D] [MSAL] Resolving authority: Masked(not-null), upn: auth.placeholder-92346b7e@orrm.com
21/09/2020 15:49:39:397|[548358]|78<Info>: TID=548356 MSAL 1.1.5 iOS 14.0 [2020-09-21 20:49:39 - 274449BD-6832-4C3E-AAE6-B611307BA25D] [MSAL] No cached preferred_network for authority
21/09/2020 15:49:39:398|[548462]|78<Info>: TID=548356 MSAL 1.1.5 iOS 14.0 [2020-09-21 20:49:39 - 274449BD-6832-4C3E-AAE6-B611307BA25D] [MSAL] Caching AAD Environements
21/09/2020 15:49:39:398|[548462]|78<Info>: TID=548356 MSAL 1.1.5 iOS 14.0 [2020-09-21 20:49:39 - 274449BD-6832-4C3E-AAE6-B611307BA25D] [MSAL] networkHost: login.microsoftonline.com, cacheHost: login.windows.net, aliases: login.microsoftonline.com, login.windows.net, login.microsoft.com, sts.windows.net
21/09/2020 15:49:39:398|[548462]|78<Info>: TID=548356 MSAL 1.1.5 iOS 14.0 [2020-09-21 20:49:39 - 274449BD-6832-4C3E-AAE6-B611307BA25D] [MSAL] networkHost: login.partner.microsoftonline.cn, cacheHost: login.partner.microsoftonline.cn, aliases: login.partner.microsoftonline.cn, login.chinacloudapi.cn
21/09/2020 15:49:39:399|[548462]|78<Info>: TID=548356 MSAL 1.1.5 iOS 14.0 [2020-09-21 20:49:39 - 274449BD-6832-4C3E-AAE6-B611307BA25D] [MSAL] networkHost: login.microsoftonline.de, cacheHost: login.microsoftonline.de, aliases: login.microsoftonline.de
21/09/2020 15:49:39:399|[548462]|78<Info>: TID=548356 MSAL 1.1.5 iOS 14.0 [2020-09-21 20:49:39 - 274449BD-6832-4C3E-AAE6-B611307BA25D] [MSAL] networkHost: login.microsoftonline.us, cacheHost: login.microsoftonline.us, aliases: login.microsoftonline.us, login.usgovcloudapi.net
21/09/2020 15:49:39:399|[548462]|78<Info>: TID=548356 MSAL 1.1.5 iOS 14.0 [2020-09-21 20:49:39 - 274449BD-6832-4C3E-AAE6-B611307BA25D] [MSAL] networkHost: login-us.microsoftonline.com, cacheHost: login-us.microsoftonline.com, aliases: login-us.microsoftonline.com
21/09/2020 15:49:39:399|[548462]|78<Info>: TID=548356 MSAL 1.1.5 iOS 14.0 [2020-09-21 20:49:39 - 274449BD-6832-4C3E-AAE6-B611307BA25D] [MSAL] Resolved authority, validated: YES, error: 0
21/09/2020 15:49:39:420|[548356]|78<Info>: TID=548339 MSAL 1.1.5 iOS 14.0 [2020-09-21 20:49:39] Start background app task with type 0
21/09/2020 15:50:16:597|[548339]|245<Info>: Clearning the Application's azure context cache
21/09/2020 15:50:32:234|FLMCMaaSAzureService|onNotification:[548339]|196<Info>: MSAL auth event MSALWebAuthDidCompleteNotification
21/09/2020 15:50:32:234|[548462]|78<Info>: TID=548339 MSAL 1.1.5 iOS 14.0 [2020-09-21 20:50:32] Stop background task with type 0
21/09/2020 15:50:32:263|[548462]|78<Info>: TID=548339 MSAL 1.1.5 iOS 14.0 [2020-09-21 20:50:32 - 274449BD-6832-4C3E-AAE6-B611307BA25D] [MSAL] Enrollment id read from intune cache : (null).
21/09/2020 15:50:32:708|[548926]|78<Info>: TID=548632 MSAL 1.1.5 iOS 14.0 [2020-09-21 20:50:32] Id token was set to nil in token response!
21/09/2020 15:50:32:708|[548926]|78<Info>: TID=548632 MSAL 1.1.5 iOS 14.0 [2020-09-21 20:50:32 - 274449BD-6832-4C3E-AAE6-B611307BA25D] [MSAL] Validate and save token response...
21/09/2020 15:50:32:708|[548462]|82<Error>: TID=548632 MSAL 1.1.5 iOS 14.0 [2020-09-21 20:50:32 - 274449BD-6832-4C3E-AAE6-B611307BA25D] Processing an AAD error with error code -51410, error invalid_request, suberror (null), description Masked(not-null)
21/09/2020 15:50:32:709|[548462]|78<Info>: TID=548632 MSAL 1.1.5 iOS 14.0 [2020-09-21 20:50:32 - 274449BD-6832-4C3E-AAE6-B611307BA25D] Unsuccessful token response, error MaskedError(MSIDOAuthErrorDomain, -51410)
21/09/2020 15:50:32:711|[548643]|78<Info>: TID=548632 MSAL 1.1.5 iOS 14.0 [2020-09-21 20:50:32 - 274449BD-6832-4C3E-AAE6-B611307BA25D] [MSAL] Interactive flow finished. Result (null), error: -51410 error domain: MSIDOAuthErrorDomain
21/09/2020 15:50:32:711|[548643]|82<Error>: TID=548632 MSAL 1.1.5 iOS 14.0 [2020-09-21 20:50:32 - 274449BD-6832-4C3E-AAE6-B611307BA25D] [MSAL] acquireToken returning with error: (MSALErrorDomain, -50000) Masked(not-null)
21/09/2020 15:50:32:711|FLMSALClient|fetchMSALAzureServiceProviderClientWithCompletionHandler:progressHandler:forceAuthentication:[548339]|973<Info>: MSAL-Auth: loaded client [Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=AADSTS500031: Cannot find signing certificate configured.
Trace ID: 27b23423-8378-4d04-823e-9eee9c5c4100
Correlation ID: 274449bd-6832-4c3e-aae6-b611307ba25d
Timestamp: 2020-09-21 20:50:32Z, MSALOAuthErrorKey=invalid_request, MSALCorrelationIDKey=274449BD-6832-4C3E-AAE6-B611307BA25D, MSALInternalErrorCodeKey=-42002}]
21/09/2020 15:50:32:711|FLMSALClient|handleAuthenticationError:[548339]|1005<Error>: MSAL-Auth: Error: Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=AADSTS500031: Cannot find signing certificate configured.
Trace ID: 27b23423-8378-4d04-823e-9eee9c5c4100
Correlation ID: 274449bd-6832-4c3e-aae6-b611307ba25d
Timestamp: 2020-09-21 20:50:32Z, MSALOAuthErrorKey=invalid_request, MSALCorrelationIDKey=274449BD-6832-4C3E-AAE6-B611307BA25D, MSALInternalErrorCodeKey=-42002}
21/09/2020 15:50:32:714|FLMSALClient|handleAuthenticationError:[548339]|1010<Error>: MSAL-Auth: Authentication Error {
    MSALCorrelationIDKey = "274449BD-6832-4C3E-AAE6-B611307BA25D";
    MSALErrorDescriptionKey = "AADSTS500031: Cannot find signing certificate configured.
\nTrace ID: 27b23423-8378-4d04-823e-9eee9c5c4100
\nCorrelation ID: 274449bd-6832-4c3e-aae6-b611307ba25d
\nTimestamp: 2020-09-21 20:50:32Z";
    MSALInternalErrorCodeKey = "-42002";
    MSALOAuthErrorKey = "invalid_request";
}
21/09/2020 15:50:32:714|FLMSALClient|handleAuthenticationError:[548339]|1026<Error>: MSAL-Auth: Error Details {
    MSALCorrelationIDKey = "274449BD-6832-4C3E-AAE6-B611307BA25D";
    MSALErrorDescriptionKey = "AADSTS500031: Cannot find signing certificate configured.
\nTrace ID: 27b23423-8378-4d04-823e-9eee9c5c4100
\nCorrelation ID: 274449bd-6832-4c3e-aae6-b611307ba25d
\nTimestamp: 2020-09-21 20:50:32Z";
    MSALInternalErrorCodeKey = "-42002";
    MSALOAuthErrorKey = "invalid_request";
}

**Comment by aherciya** [comment]
Hi @smudireddy can you confirm that your [application certificates](https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/application-sign-in-problem-federated-sso-non-gallery#certificate-or-key-not-configured) are configured correctly? It might be the case they they somehow became corrupt and so deleting the old one and creating a new certificate might be all you need. Let us know if this doesn't address your issue.
