### ISSUE TITLE
 Azure AD Device registration.  ( Works only in specific workflow )

### ISSUE THREAD

**Issue by rahulcode** [AzureAD/microsoft-authentication-library-for-objc#1112]
Summary: Device registration not working when directly asking for a token with claim request in certificate-based authentication flow. 

Device Registration Issues with Certificate Based Authentications.
Used MSAL Sample Application for trying out all combinations.
Certificated installed in the keychain Manually.

**Scenarios and Issues**
(Authenticator App has no active sessions, no registrations and user is not there in added accounts )
Direct Registrations --> .login                    : Registration doesn't work.

Sample claim request :
`let claimRequest = MSALClaimsRequest();
        
        let individualClaimRequest =  MSALIndividualClaimRequest(name: "deviceid")
        individualClaimRequest.additionalInfo = MSALIndividualClaimRequestAdditionalInfo()
        individualClaimRequest.additionalInfo?.essential = NSNumber(integerLiteral: 1)
                
        parameters.claimsRequest = claimRequest
       
        do {
            try claimRequest.requestClaim(individualClaimRequest, for: .accessToken)
        } catch let error as NSError {
            print(error.description)
        }`

Steps:
Directly asking for a token with Claim request. ( Login )
VIDEO : (https://ibm.box.com/s/8sj4ra0vstphclo76n8hhp5el5vmj8po)

Directly asking for a token with Claim request. ( SelectAccount )
Direct Registrations --> .SelectAccount   : Registration doesn't work.
VIDEO : (https://ibm.box.com/s/2d777pbr1l3almrd46nta1khv8h96hbh)

The above cases, Authentication is Successful, but on tapping Register, We directly get an error.

<img width="571" alt="Error_MA" src="https://user-images.githubusercontent.com/19573187/94575340-c2fff580-0291-11eb-8eeb-354b314e8086.png">

MA logs Attached :
[Direct_Registration_Logs_Certificate_setup.txt](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/5299772/Direct_Registration_Logs_Certificate_setup.txt)

-------------- COMBINATION SCENARIO ( First without a claim and then with the claim request )
**Not working scenario ( login )**
1) Fetching token without Claim request first with Login
2) and then next requesting claims.(deviceid)
3) Register is Shown and on Register --> After Tapping Register, it keeps on loading, no change, hence registration doesn't work.
Logs::
[Register_Stuck_in_login Case.txt](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/5299781/Register_Stuck_in_login.Case.txt)

Video: https://ibm.box.com/s/y9qfi6pmvdnb2vuynykngrg1ej77e0y5
--------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------

**ONLY working scenario ( SelectAccount )**

1) Only order which works is Fetching token without Claim request first with selectAccount
2) and then next requesting claims.
3) Register is Shown and on Register works properly. Registration of the device is completed.
Video: https://ibm.box.com/s/kkt9xhkwl1xk2n7ee769ezhjd2f3mtaj

Logs : 
[Working_Case_logs.txt](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/5299894/Working_Case_logs.txt)

-----

Queries :

Why Registration doesn't work with claim requests in the first call to Microsoft Authenticator?
Will .login be not supported completely with Certificate-based authentication?

**Comment by oldalton** [comment]
Certificate based authentication with device registration only works using a "converged_broker_enabled" feature flag right now, so this is by design at this moment.

**Comment by smudireddy** [comment]
Thanks @oldalton  for confirmation  about the need of "converged_broker_enabled" configuration.
 App able to register the device if user already authenticated for any other workflow without the "converged_broker_enabled" configuration. It is the case not working is post Authenticator app installed and first request is "Register" the device with an additional claim of some resource auth.

**Comment by oldalton** [comment]
Yes, passing deviceId claim is equivalent to device being not registered and won't work when certificate based authentication is involved.

**Comment by smudireddy** [comment]
Thanks @oldalton .

With provided documentation, "converged_broker_enabled" can be configured only on devices managed by MDM solution.
What about the device not managed by MDM solution case ?. How to configure this required flag for Authenticator app to work with Certificate based user authentication ?. 

Note: User can also add a certificate by importing from webpage or can add from Files App ..etc to use it in authentication

**Comment by rahulcode** [comment]
Hi @oldalton 

Just to confirm, Is this the expected (supported) scenario in which registration works without any SSO extension (converged_broker_enabled) in certificate-based authentication?
`
ONLY working scenario ( SelectAccount )

Only order which works is Fetching token without Claim request first with selectAccount
and then next requesting claims.
Register is Shown and on Register works properly. Registration of the device is completed.`

Video: https://ibm.box.com/s/kkt9xhkwl1xk2n7ee769ezhjd2f3mtaj
Logs :
Working_Case_logs.txt

**Comment by oldalton** [comment]
Here's the current state:

1. With converged_broker_enabled flag:
- Registration should work with certificate based auth in most cases (the only exception is on-prem MFA. But we haven't seen cases where both on-prem MFA and CBA for authentication are used). 

2. Without converged_broker_enabled flag:
- Microsoft Authenticator settings: registration should work. On-prem MFA won't work for subsequent token requests (see note above)
- App calling Microsoft Authenticator: new registration won't work. If device is already registered, auth will only work if prompt is NOT login, and if app is not requesting deviceId claim.

Let me know if you have additional questions.

**Comment by smudireddy** [comment]
Thanks @oldalton .

With provided documentation, "converged_broker_enabled" can be configured only on devices managed by MDM solution.
What about the devices not managed by a MDM solution?. How to configure this required flag for Authenticator app to work for Certificate based user authentication in those devices ?.

Note: User can also add a certificate by importing from webpage / Files / Notes/ Mail App ..etc to use it in authentication

**Comment by oldalton** [comment]
@smudireddy, yes, this is not supported for non-MDM devices at this moment. "converged_broker_enabled" is a preview feature, and we only have a mechanism to enable preview features through MDM channel at this time.

**Comment by smudireddy** [comment]
@oldalton ,
Any plan to provide the support for non MDM devices through the integrated MSAL SDK in our App to Authenticator request ?
I mean sending the "converged_broker_enabled" value through the request to Authenticator app from App integrated with MSAL SDK.
