### ISSUE TITLE
Proper way to handle the case when MS Authenticator is not installed

### ISSUE THREAD

**Issue by locksleyu** [AzureAD/microsoft-authentication-library-for-objc#1118]
I am writing an app that uses MSAL to help with AAD Device Compliance use cases. The problem I have is how to smoothly handle the case where MS Authenticator is not installed.

If I try to get a token and MSA is not installed, it will show a dialog saying its installation is required, and if I click on the button it will flip to the app store, where I can install MSA. 

The problem is that if I go to MSA and log in, it never flips back to my app.

On the other hand, if the user returns to my app it will fail (whether that was before MSA run, or after), saying there was no response from MSA app.

I can modify my app to handle this case by calling the MSAL token API again, in which case it will flip to MSA and then eventually back, and this seems like it will work.

However, the problem is that I can't arbitrary retry this logic again, I need a way to gate it in order to handle other error cases.

The best I can think of is to check the installation state of MSA when I leave my app, and when I come back, and if it went from uninstalled->installed I retry the MSAL token call. Otherwise I fail for some other error.

However, this relies on canOpenURL and the Bundle ID of MSA, and generally seems fragile. At minimum, it would be nice if MSAL gave me some information that it was flipping away to the app store, or if there was an API to say whether MSA was installed or not. But I couldn't find one.

If anyone has any suggestions please let me know.

Thanks!

**Comment by oldalton** [comment]
Thanks for the question. There're multiple scenarios where Authenticator app is required. To better identify your scenario, could you provide a screenshot or a video of the webpage that asks to install the Microsoft Authenticator app? Thanks.

**Comment by locksleyu** [comment]
Thanks for the response. That API looks helpful.

I attached a screenshot. Username has been whited out for privacy reasons, but I can provide offline if needed.

![MSA_required](https://user-images.githubusercontent.com/10435419/94975990-4f93f900-04c8-11eb-9524-81c52ab69f59.PNG)

**Comment by jasoncoolmax** [comment]
Hi @locksleyu , thank you for providing the screenshot.

Currently we are relying on pasteboard to pass the request from MSAL app to Authenticator. Once Authenticator is installed, it will pick up the request in pasteboard and continue with the unfinished authentication flow.

However, pasteboard can only be shared among apps signed by the same cert/same publisher. Therefore, your app is not able to pass the request to Authenticator. 

We have had such a task in our backlog, although we are still not clear how that could be solved yet. Currently the work around is, user/app needs to reinitialize the auth request after Authenticator is installed.
