### ISSUE TITLE
Question: Correct way to handle journeys inside the app

### ISSUE THREAD

**Issue by ralexandre-ciandt** [AzureAD/microsoft-authentication-library-for-objc#1124]
Hello!

We have a few journeys to update the user's information (name, email, etc) inside the app.

The problem is: we have to handle the webview's cookies before opening the journey, otherwise it will request the login before.

We save the cookies after an interactive journey and before opening the "update user's information" journey we have to load the cookies to the webview in order to show the other journey.

What is the correct approach to this case? Or any other ideas other clients are using.

I ask this because sometimes the webview doesn't save the cookies correctly and intermittently the cookies are not enough and the login screen is shown.

Thanks!

**Comment by oldalton** [comment]
Can you clarify if you're trying to develop a B2C app? MSAL doesn't directly handle cookies, and we recommend using ASWebAuthenticationSession which should preserve cookies across sessions automatically. Are you seeing a different behavior?

**Comment by ralexandre-ciandt** [comment]
Hi!
Yes, we have a B2C app developed

For now, basically we have to save the cookies for 2 purposes: 1- autologin when closing the app and reopening; and 2- we open B2C journeys inside the app while logged in, in order to perform user account updates like name, email, etc. 

We saw the need for saving cookies in order to correctly open the update user information journeys, otherwise, it was showing the login journey, and after logging in again, it was showing the requested journey

**Comment by ameyapat** [comment]
@ralexandre-ciandt Which iOS version are you using? Is it iOS 14?

**Comment by ralexandre-ciandt** [comment]
Our app supports iOS 11 and above

**Comment by ameyapat** [comment]
@ralexandre-ciandt ASWebAuthenticationSession can be used and it should handle cookies. Here is some documentation regarding choice of browser : https://docs.microsoft.com/en-us/azure/active-directory/develop/customize-webviews#cookie-sharing-and-single-sign-on-sso-implications  

There is also a B2C custom policy : https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-policy-keep-me-signed-in that might be helpful according to your case

**Comment by ralexandre-ciandt** [comment]
Thanks, @ameyapat !
We will take a look at these documentations!

Thanks!

**Comment by ralexandre-ciandt** [comment]
Hi @ameyapat !

Just a feedback about our implementation.

We updated the MSAL library to the latest version and removed our cache mechanism. MSAL and the browser are handling the cookies by themselves in the latest version. I changed the signout method to hit the /logout endpoint and sign out the user from B2C following the documentation and the sign out starts working. But when we login again and try to execute another journey we get redirected to the login screen, but after logging in again it's not shown anymore until a new logout.

Is there something wrong we could possibly be doing?

This is our signout method:

The customWebview is passed as a parameter (it's the same customWebView we are using to open the interactive journeys.

`let allAccounts = try applicationContext.allAccounts()

let webViewParameters = MSALWebviewParameters(authPresentationViewController: parentViewController)
            
if let webview = customWebView {
    webViewParameters.webviewType = .wkWebView
    webViewParameters.customWebview = webview
}
            
let signoutParameters = MSALSignoutParameters(webviewParameters: webViewParameters)
signoutParameters.signoutFromBrowser = true
            
for account in allAccounts {
    applicationContext.signout(with: account, signoutParameters: signoutParameters) { success, error in
        if let error = error {
             print("error: \(error)")
        } else {
             print("success: \(success)")
        }
   }
}`

**Comment by ameyapat** [comment]
@ralexandre-ciandt Thank you for the observation. I'm assuming by blinking you mean web view pops up and disappears, please correct me if I'm wrong. Since you have specified signoutParameters.signoutFromBrowser = true, I think a request is made to the logout endpoint and the server will remove/invalidate any cookies from the session in browser to logout, hence it pops up the webview for the request.

**Comment by ralexandre-ciandt** [comment]
Hi @ameyapat !
Sorry to bother you again, but we could fix the "blink" thing :) 

We just got a different problem now, when we close my app and reopen it, it's possible to retrieve the token from acquireTokenSilently but when opening a journey we are prompted to log in again. Is it something we might be missing?
After logging in again the journeys work, but until the app is closed and reopened again =/

We are using WKWebview.

**Comment by oldalton** [comment]
WKWebView doesn't store session-only cookies after the app is restarted. You'd need to use one of the system WebViews, like ASWebAuthenticationSession instead. We have some more information here: https://docs.microsoft.com/en-us/azure/active-directory/develop/customize-webviews

**Comment by ralexandre-ciandt** [comment]
Hi @oldalton 

Thanks for your previous comment!

Just to give you a more detailed context:

- We use B2C and we have a login journey to access the app, then inside the native app, we have a menu where the user can update their account information like name, email, etc (this is another journey).
- Before, when opening a journey inside the app it prompted to login every time before showing the update account journey, we fixed it by sharing the same WebView's Process Pool.
- Now our only problem to stay logged in in the app is during the auto-login sessions, we needed to save the WebView cookies and add it to the WebView during the loadURL override method when opening the login journey.
- If we perform the autologin just by checking the acquire token silently method (which we think is the correct way), whenever we open the journeys inside the app it prompts the user to log in, so we would need to also load cookies there (but we didn't do this approach).

What we mean is, we want to replace our custom cookies management with MSAL's default one, because it's generating some bugs in production that may be related to it. 

According to your previous comment, the solution would be to use the ASWebAuthenticationSession but the team is having problems with using it:
- By using the ASWebAuthenticationSession the journeys open like a modal without our customization (today we use a custom WKWebView without the URL at the top, the close button, etc, some code before the loadUrl method to retrieve cookies)
- It opens with the browse url at the top and with the close button
- It prompts the user a dialog to allow the OAuth to be shown before each journey
- After the first successful login, if we close the app and reopen we cannot open any journey again, it crashes with an error we don't remember exactly what it is, but it's something related to "Provide a valid controller" or something.

Is that expected? Would you have a sample we could follow?

**Comment by oldalton** [comment]
Thank you for a thorough reply. MSAL doesn't provide a built-in cookie management for the WKWebView and we operate with tokens only.

```
By using the ASWebAuthenticationSession the journeys open like a modal without our customization (today we use a custom WKWebView without the URL at the top, the close button, etc, some code before the loadUrl method to retrieve cookies)
It opens with the browse url at the top and with the close button
```

The recommended solution is to indeed use ASWebAuthenticationSession, or SFSafariViewController. Neither of them provides customization that you might need, but it has a few advantages:
1. Persistent cookies are saved by the browser process, so you wouldn't need to implement your own cookie management
2. Standard UI that users are seeing across other apps

`It prompts the user a dialog to allow the OAuth to be shown before each journey`

If you would like to avoid seeing an OAuth dialog prompt before each journey, I'd recommend trying to use SFSafariViewController. You wouldn't get SSO across all apps, but it should work within your application and not prompt. It is also possible to avoid prompt with ASWebAuthenticationSession (see [prefersEphemeralWebBrowserSession ](https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALWebviewParameters.html#/c:objc(cs)MSALWebviewParameters(py)prefersEphemeralWebBrowserSession)), but you'll also loose persistent cookies. 

`After the first successful login, if we close the app and reopen we cannot open any journey again, it crashes with an error we don't remember exactly what it is, but it's something related to "Provide a valid controller" or something.`

This seems like a bug in your implementation. Make sure you always provide MSAL with a valid controller when initializing MSALWebViewParameters: https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALWebviewParameters.html#/c:objc(cs)MSALWebviewParameters(im)initWithAuthPresentationViewController:

We have a B2C sample here: https://github.com/Azure-Samples/active-directory-b2c-ios-swift-native-msal

If you'd prefer to use WKWebView to have customized UX, then you might need to continue having your own cookie management.
