### ISSUE TITLE
Influx of "Cannot connect" complaints

### ISSUE THREAD

**Issue by guidedways** [AzureAD/microsoft-authentication-library-for-objc#1125]
We'd had an unusual number of users complain today that they can no longer connect to their accounts. We haven't made any recent changes and so I don't know if this is a coincidence or just something at their end. Here's what we see:

```
MSAL: could not aquire token: Error Domain=MSALErrorDomain Code=-50005 "(null)" UserInfo={MSALErrorDescriptionKey=User cancelled the authorization session., MSALCorrelationIDKey=82BA005A-005B-4656-A32A-0AC1C99F8F82} => {
    MSALCorrelationIDKey = "82BA005A-005B-4656-A32A-0AC1C99F8F82";
    MSALErrorDescriptionKey = "User cancelled the authorization session.";
}
```

Is there any way for developers to actually figure out what these errors mean and why they cannot connect? The "Authorization Window" does not show at all for one of the users, I'm assuming MSAL is caching the result. What is the best way to force the window to show each time and how do we diagnose these cryptic errors? Everything from MSAL is always `-50005`, which doesn't help.

**Comment by guidedways** [comment]
I wonder if this is related? https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1123

The user that I mentioned earlier is on Big Sur

**Comment by guidedways** [comment]
> I wonder if this is related? https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1123
> 
> 
> 
> The user that I mentioned earlier is on Big Sur

I can confirm this was it. After making the proposed change it worked for one of our users. We are still on an older version of MSAL as we need to support macOS 10.11.

**Comment by kaisong1990** [comment]
@guidedways Sounds like this question is related to #1123, could you also help to confirm if the user is using Big Sur Beta 9 specifically? It seems to be a Apple bug in their beta os and we are still pending for their confirmations

**Comment by guidedways** [comment]
I believe they're all on the latest beta

**Comment by kaisong1990** [comment]
@guidedways in that case, would you mind closing this thread and merge into #1123?
