### ISSUE TITLE
More meaningful error codes.

### ISSUE THREAD

**Issue by maksirol** [AzureAD/microsoft-authentication-library-for-objc#1126]
Hello,

It is possible to return more meaningful error for this function:
`(nullable MSALAccount *)accountForIdentifier:(nonnull NSString *)identifier
                                         error:(NSError * _Nullable __autoreleasing * _Nullable)error;`
in MSALPublicClientApplication.h

Right now i just get Foundation._GenericObjCError.nilError and it's impossible to understand what is wrong.

**Comment by jasoncoolmax** [comment]
Hi @maksirol , do you mean you get back a nil error? Nil error means there is no error happening. You might want to check if there is any account being returned. If nil account is returned, it means there is no account found based on the provided identifier.

**Comment by maksirol** [comment]
I'm calling it from swift, so code looks like this:

`do {
            let client = try client.account(forIdentifier: id)
        } catch {}`

and it triggers catch block with nsError domain "Foundation._GenericObjCError" and code 0.

So can i assume that always when i get this error, it means that account does not exists? Or is it possible that something else went wrong.

**Comment by ameyapat** [comment]
@maksirol client object will be nil inside the try expression since your code defines client = try client.account. Is _client_ variable  initialized to a MSALPublicClientApplication object?

**Comment by maksirol** [comment]
Yes, client is initialized to MSALPublicClientApplication object. And sorry for confusion, with assigning to same variable name. This will be more clear:

`do { let account = try client.account(forIdentifier: id) } catch(let error) {}`

But my question is that can i assume that 'error' with domain "Foundation._GenericObjCError" and code 0 will always mean that account does not exist. Or it can happen that same error can mean that something else is wrong?
