### ISSUE TITLE
Testing/Mocking MSAL authentication

### ISSUE THREAD

**Issue by zntfdr** [AzureAD/microsoft-authentication-library-for-objc#1135]
Hi team,
I'm exploring how an app implementing the `MSAL` framework can test the sign in/up flow:

- is there a way we can achieve so without hitting your servers (via mock or other)?

Any direction is more than welcome 🙏 

Thank you in advance,
Federico

**Comment by ameyapat** [comment]
@zntfdr I guess you could use a mocking framework to mockout API calls in MSAL. What part of the authentication process are you trying to test?

**Comment by zntfdr** [comment]
@ameyapat thank you for the response, I would like to mock the whole process from when the app asks for a token (triggering the web view) until the sign in/up flow completes and the app gets a token back.

This is probably something we'd need to do via UI test (but I very welcome other suggestions).

To make it clearer, this is the flow I would like to have an automated test for (possibly without hitting real servers):
![RPReplay_Final1602902697 2020-10-17 09_51_00](https://user-images.githubusercontent.com/5277837/96326826-4a08e800-105e-11eb-886f-522b896b1933.gif)

Thank you again for your support!

**Comment by mipetriu** [comment]
@zntfdr MSAL doesn't provide a solution for mocking, so you might need to implement your own mocking solution to meet your testing needs. From a quick internet search, some options may be network stubbing or creating a mock server on your local machine, but I'm not completely sure that those solutions would work.

**Comment by zntfdr** [comment]
@ameyapat @mipetriu thank you for the support!

Is there a way to bypass the sign in process then? As in, "inject" a signed in account (a token or what else is needed) in a test.

In this case the goal is to test the app functionalities that are available only when a user is signed in.

Thank you again and wish you a nice day,
Federico

PS
I understand that this can be achieved by wrapping the MSAL library and have this wrapper behave differently during the test, still, I would like to know if there's a way to do so directly via the library. Thanks!

**Comment by mipetriu** [comment]
@zntfdr Unfortunately we don't provide a way to mock or bypass the sign in process directly with the MSAL library. Personally, I'm not an expert with mocking, but I think your idea for how to move forward is a good one.

**Comment by zntfdr** [comment]
@mipetriu thank you for the support!
