### ISSUE TITLE
iOS 14 authenticationSession webviewType dismisses when tapping outside the webview (iPad)

### ISSUE THREAD

**Issue by schlingding** [AzureAD/microsoft-authentication-library-for-objc#1139]
Xcode 12, MSAL 1.1.11

In iOS13, Tapping the background when the Authentication window is showing does nothing.

In iOS 14, you can tap the background around the window (iPad) which dismisses the authentication session without any notification or error. This can leave an application in an unexpected or unrecoverable state if login is trying to be enforced.

Is there a workaround or has this issue been seen?

Thank you

**Comment by mipetriu** [comment]
Thank you for reporting this, we will investigate and get back to you when we have an update.

**Comment by SeboRax** [comment]
Upvoting this iOS 14 behavior not handled by the library... Do you have an ETA for this fix?

**Comment by cdescours-amaris** [comment]
I reproduce this bug on my iOS 14 app, any news on that?

**Comment by mipetriu** [comment]
We've tested this scenario, and have been able to reproduce this behavior as well. After some investigation it seems that as of iOS 14, tapping outside of a view closes it, and we haven't been able to find any notification or delegate to handle that type of close. I will submit a radar to Apple with this issue and keep this thread updated with their response.

**Comment by schlingding** [comment]
This may be ASWebAuthenticationSession behavior?

**Comment by SeboRax** [comment]
Hi, you've reproduced this on your side, can you mark this as bug and provide a fix version? This affects all apps using Microsoft authentication on iOS 14, that's a lot...

**Comment by hieunguyenmsft** [comment]
Hi, we already submitted the bug ticket to Apple. Will kept you posted.

**Comment by jennyf19** [comment]
@hieunguyenmsft any update on this one? thx.

**Comment by hieunguyenmsft** [comment]
@jennyf19 I created a ticket to Apple in Oct 19, 2020 but haven't heard their response. 
The feedback ID is:
FB8813382

**Comment by mipetriu** [comment]
I had the chance to bring this issue up with an Apple developer technical support engineer, and they were able to test this and confirm that unfortunately there's no way to trigger a callback in this scenario or no workaround right now. We still need to hear back regarding the ticket that we previously submitted to be notified of a fix.

**Comment by br-johndavis** [comment]
Are the "willDismiss" or "shouldDismiss" methods of the sheet View Controller's presentation delegate not invoked in this scenario? Are there ways to re-present the interactive login window in the event the sheet is dismissed?

At the moment, if I try to re-present the login sheet I get an error: "Only one interactive session is allowed at a time."

**Comment by cdescours-amaris** [comment]
We have found an "acceptable" workaround on that bug : 

prior to any new authentication in the view controller, we have added those calls to enable the user to recreate a new interactive session:

```
// Cancel previous authorisation request 
MSALPublicClientApplication.cancelCurrentWebAuthSession()

// Dismiss the eventual modal presented by MSAL library 
self.presentedViewController?.dismiss(animated: false, completion: nil)

```
It remains a little 'visual glitch' but at least users are able to reconnect in such cases.

Hope that will help.

**Comment by br-johndavis** [comment]
That will absolutely help me, thank you. 

Apple introduced the ability to dismiss sheets interactively in iOS13, and they added the `UIAdaptivePresentationControllerDelegate` as a means to customize the behavior in the event you have a sheet that you want to respond to the dismissal of. 

I went to the viewController that I pass to the MSAL's interactive login method, and I overrode the present method like so:
```
        super.present(viewControllerToPresent, animated: flag) {
            print("Presented View Controller: \(viewControllerToPresent)")

            if NSStringFromClass(type(of: viewControllerToPresent)) == "SFAuthenticationViewController" {
                viewControllerToPresent.presentationController?.delegate = self
            }
            completion?()
        }
```

This enables me to grab the MSAL web view sheet after its been presented, and set the delegate of its presentationController.

I then implemented shouldDismiss and willDismiss of the delegate. 

```
extension ViewController: UIAdaptivePresentationControllerDelegate {
    func presentationControllerWillDismiss(_ presentationController: UIPresentationController) {
        print("WILL DISMISS")
    }

    func presentationControllerShouldDismiss(_ presentationController: UIPresentationController) -> Bool {
        print("SHOULD DISMISS")
        return true
    }
}
```

These callbacks happen even when the user taps outside of the sheet. If I return "false" in `shouldDismiss` then a tap outside the sheet _will not_ dismiss it. 

I think the MSAL framework could either disable dismissal by implementing this delegate internally, or at a minimum use the will/didDismiss callbacks to send the same completion event as the user tapping "cancel".

**Comment by hieunguyenmsft** [comment]
The community already provides the workaround, thank you @br-johndavis and @cdescours-amaris for providing it. 
We'd rather wait for the official fix from Apple.
Thanks,
