### ISSUE TITLE
MSAL with Edge iOS

### ISSUE THREAD

**Issue by ShilpaGavade** [AzureAD/microsoft-authentication-library-for-objc#1143]
Hello Team,

We have an ios app protected by Intune SDK and using MSAL auth library for login, MSAL uses system web browser by default for authentication purpose. 
In iOS, safari is the default browser (or depends on iOS versions..like, ASWebAuthenticationSession or SFSafariViewController etc.) but our intune policy restricts us to open login page on edge which is not happening in iOS, so we are getting error at the time of Login, in short, not able to login due to policy restriction.
So, can we do some changes or some configurations from iOS application side to open login page in edge browser, is it possible? or we should ask to change azure policy to allow login on safari.

Your help will be much appreciated.

**Comment by kaisong1990** [comment]
@ShilpaGavade Thanks for your question, even though user is able to switch to Edge or other 3rd party browsers as default one externally, iOS is still using Safari (system browser) for authentication internally. We don't have a way to configure this at the moment.

**Comment by ShilpaGavade** [comment]
Thanks @kaisong1990 for quick response, it means, we should change policy from azure side to allow authentication on safari browser.
Just to confirm one thing, as MSAL using safari internally, so, there is no harm to data, I mean, as edge is managed browser and intune takes care of data in case of edge, same happen with safari?

**Comment by kaisong1990** [comment]
@ShilpaGavade Just to be clear, MSAL is using ```ASWebAuthenticationSession``` which provided by Apple, and ```ASWebAuthenticationSession``` uses system browser internally. In the authentication process, we are passing a completion handler and listen to the response, rests are handled by Apple.

I am not sure what kind of data you mentioned here, would you provide more details?

**Comment by ShilpaGavade** [comment]
@kaisong1990 just wanted to confirm one thing, as you mentioned, currently there is no way to configure Edge browser for authentication purpose, but there are some iOS apps which uses edge, like, microsoft outlook, zoom etc.
So, have they applied some configurations form application side

**Comment by kaisong1990** [comment]
@ShilpaGavade Thanks for your question. For clarification, do you mean the Microsoft Outlook use Edge browser within the Microsoft Outlook app for authentication on iOS?

**Comment by ShilpaGavade** [comment]
@kaisong1990, thank you for you reply, we checked Microsoft outlook app on iOS and it seems it opens edge browser internally for authentication. I am not sure still confirming it.
Please clear and apologies if the question is wrong.

**Comment by kaisong1990** [comment]
@ShilpaGavade Theoretically there shouldn't be any 3rd party browser during authentication session within Outlook apps. Would you be able to share a screenshot if see this happening?

**Comment by ShilpaGavade** [comment]
@kaisong1990, yes will try to share it in sometime

**Comment by oldalton** [comment]
Adding @ShruthiAchutha from Intune MAM side to comment on ASWebAuthenticationSession and data protection.

**Comment by vigavadi** [comment]
@ShilpaGavade This seems to be as a result of using `isExternalURL`. It could be linked to the ongoing issue #1122

**Comment by neerajhr19** [comment]
Hello @ShilpaGavade ,
Any update on the login issue that you were facing?
In case it is solved, and you can login to your managed app, could you please share the steps taken or the changes made in the policy?
We are facing the same issue and as we are on a strict deadline, any help would be appreciated!

**Comment by brandwe** [comment]
The original issue was that when an admin blocks Safari as policy and only allows for the Intune Managed Browser (Edge), authentication fails if the app uses MSAL. This is because MSAL uses the System Browser by default and that System Browser is Safari in iOS. We should definitely investigate this internally because blocking all MSAL apps is an unintended consequence we may not be communicating to our admins. We also need to see if we can authenticate even if this policy is in place.

As a workaround, we said that the admin should turn off the exclusion of Safari on the devices. This will allow the users to sign in using the System Browser. 

This led to a new question: If the AFAuthenticationSession() offered the same protections as using the Intune Managed Browser. 

The answer is no. Although AFAuthenticationSession() is owned by the OS and secure, it does not offer the additional protections like URL restrictions, data wipe, and other features of the Intune Managed Browser. However, the Intune Managed Browser was never meant to be used to clear authentication state from the device, only the website data on the device. Therefore, although the protection isn't the same as Intune Managed Browser it is fine to use it for authentication.

Of course, nothing prevents the user from also using Safari as a browser. This is a conflict we will need to resolve with Intune and merits a new Issue being raised to track. 

Thoughts @oldalton ?

**Comment by brandwe** [comment]
Hey @neerajhr19 and @ShilpaGavade can you tell us exactly what you are seeing that appears broken? 

From discussing this with the engineers, you should be able to use System Browser within MSAL even if a policy is applied that blocks Safari on the device. We will allow it at the Azure AD service itself.

**Comment by neerajhr19** [comment]
Hey @brandwe,
I am using a personally owned device enrolled with intune using company portal.
My application is using MSAL libraries and it is wrapped using iOS intune wrapper to make this MAM enabled. While authentication, MSAL opens Safari browser for login but the admin only allows the authentication in Edge(Managed Browser),  So authentication fails in Safari. I need MSAL to open Edge by default for authentication so the authentication process is successful.

**Comment by oldalton** [comment]
@neerajhr19, thanks for the clarification. Could you please share a screenshot of the error you're seeing in Safari when authentication fails?

**Comment by neerajhr19** [comment]
Hi @oldalton,
I am getting the below error on safari while authentication.

![IMG-20210226-WA0000](https://user-images.githubusercontent.com/39955559/109255362-d5b73000-7819-11eb-931e-12f8831bff83.jpg)

**Comment by oldalton** [comment]
Thanks for sharing. This just means that your device needs to be enrolled into MDM. 
Can you double check a few more things?
1. Make sure your device is Intune-managed. Open Intune Company Portal app to double check. 
2. Make sure that you have a device identity certificate on your device (On your iPhone, open Settings -> General -> Device Management -> Mobile device management -> More details -> Under device identity certificates you should see 2 certificates. One of them should have a title "SCEP profile" and subtitle "MS-Organization-Access"
3. In the error page, tap on "More details" and send me a new screenshot (this will have a correlation ID to look up your request)

**Comment by lartisimi** [comment]
Hi @brandwe 

any updates on this issue? Is there any way to use Edge for MSAL authentication in iOS apps protected by Intune?

**Comment by kostask1978** [comment]
We also face a similar problem. We have Oracle CX mobile app that tries to connect with SSO. Browser window opens from the app internaly but ignores even the default browser app which is edge (intune managed) and opens from safari. That is why we get the following error. 

Devices are enrolled but we get this message from Conditional acces
530001
Failure reason	
Browser not supported.
Additional Details	
The user is using a browser that does not support device identification so the device state is unknown. Access to the resource requires a compliant device. To see a list of browsers that support device identification, see https://docs.microsoft.com/azure/active-directory/conditional-access/technical-reference#supported-browsers

Our protection policy is enabled but allows traffic to and from managed apps and unmanaged apps.

**Comment by Paul-JanPauptit** [comment]
We face a similar problem. Intune setup forces edge as the browser, app connects through MSAL (part or the Intune SDK setup). When authenticating, the browser dialog shows "you must use Microsoft Edge to access this resource", error code 530021.

If there is no way to setup MSAL to support this scenario, having explicit confirmation that there is no way to make MSAL/Intune based apps on iOS compatible with the "force edge" Intune policy would be a *good thing*.

**Comment by oldalton** [comment]
MSAL doesn't support Edge as the browser to sign-in. However, the recommended approach to get this scenario working would be to integrate with the Microsoft Authenticator app. MSAL will then delegate sign-in to the Authenticator app (we call it brokered login), and it will work end to end. As long as you follow the default steps in MSAL readme, and configure the redirectURI that is in the recommended format of msauth.$(PRODUCT_BUNDLE_IDENTIFIER)://auth, your app should be already all setup to use the broker. Please give it a try and let me know if that resolves the issue.
