### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [AzureAD/microsoft-authentication-library-for-objc#1144]
The README file in this repo has a bad link - [404:NotFound]

Status code [404:NotFound] - Link: https://docs.microsoft.com/en-us/azure/active-directory/develop/redirect-uris

This was found by an new experimental hobby project that I have just created: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
If this has been in any way helpful then please consider giving the above Repo a Star.

**Comment by kaisong1990** [comment]
@MrCull Thanks for the updates, we have updated the url from the following pull request:

https://github.com/AzureAD/microsoft-authentication-library-for-objc/pull/1145
