### ISSUE TITLE
ADFS + SSO Extension + Cert Based Authentication - Multiple authentication prompts

### ISSUE THREAD

**Issue by adiashok123** [AzureAD/microsoft-authentication-library-for-objc#1146]
While doing an authentication "ADFS + SSO Extension + Cert Based Authentication", we are seeing multiple login prompts in MSAL 1.1.10.

(Certification is pushed using MDM, SSO Extension is enabled.)

<img width="840" alt="image" src="https://user-images.githubusercontent.com/73838676/97934353-79785e00-1d9b-11eb-8ae4-b16807ca39b9.png">

[SSO_EXTENSION_CUSTOMER.txt](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/5475903/SSO_EXTENSION_CUSTOMER.txt)

**Comment by smudireddy** [comment]
The second auth screen comes with an empty user ID and expecting user to enter the email/upn value.

**Comment by smudireddy** [comment]
Any changes needed in SSO extension configuration (Attached here with this issue) ?

**Comment by smudireddy** [comment]
Any update ?

**Comment by oldalton** [comment]
@smudireddy, you'll need to disable browser_sso_interaction_enabled flag when certificate based authentication is in use. See documentation about this flag here: https://docs.microsoft.com/en-us/azure/active-directory//develop/apple-sso-plugin#allow-creating-sso-session-from-any-application. We're also looking into how to make this work with this flag, but we don't yet have an ETA. Assigning to @aherciya

**Comment by smudireddy** [comment]
Thanks for the information @oldalton

**Comment by smudireddy** [comment]
@oldalton  / @jasoncoolmax ,

Scenarios: Certificate based Auth + SSO extension 

We are getting  an error whenever user trying to Authenticate post token got expired.

Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set., MSALCorrelationIDKey=29B66572-67E4-4E15-A6C0-DF34A695471A, MSALBrokerVersionKey=6.5.4}

Could you please check and help us what caused this issue. If user removes the account manually from Authenticator app and try manually then it started working again. With next token expiry it will again causing the issue.

**Comment by oldalton** [comment]
@smudireddy, thank you for reporting this. Could you please send us an Authenticator incident ID?

**Comment by smudireddy** [comment]
![File (1)](https://user-images.githubusercontent.com/13241928/99335521-18767d00-28a7-11eb-8a26-3da73fc02bad.jpg)

**Comment by smudireddy** [comment]
[MS_Authenticator_Logs.log](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/5550828/MS_Authenticator_Logs.log)

**Comment by hieunguyenmsft** [comment]
Close this one as a duplication from this issue below, please track the progress in that issue:
https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1156

**Comment by rahulcode** [comment]
w.r.t https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1146#issuecomment-724091095
The 
Please re-open this issue.

JSON error is tracked separately and this issue was specifically for the SSO extension flag: **browser_sso_interaction_enabled**

**Comment by NerevarineRule** [comment]
Could you retry with the latest Authenticator build? Thanks.
