### ISSUE TITLE
MSAL login with Microsoft Authenticator session not shared to Safari

### ISSUE THREAD

**Issue by jussiron** [AzureAD/microsoft-authentication-library-for-objc#1148]
After calling acquireToken(with: parameters), Microsoft Authenticator opens, user authenticate and then app is called with the url parameters. However the session seems not to be shared to Safari, SafariViewController or WKWebView. Is that possible when device have broker installed?

**Comment by aherciya** [comment]
Do you mind giving us some context on what behaviors you'd like to implement?

**Comment by jussiron** [comment]
User can see list of news which are fetched from Sharepoint Rest API. Each of those news have orginalURL to point to Sharepoint page. That url would be opened with SFSafariViewController if user choose to do so by tapping the news item. IF there is no authentication broker installed, it'll of course work because user will use Safari to login, but with the broker it's different story.

**Comment by aherciya** [comment]
@jussiron Sorry, again I'm not catching what you'd like to implement or the question, but based on your previous comment that allotted to "session seems not to be shared to Safari, SafariViewController or WKWebView. Is that possible when device have broker installed?" It sounds like perhaps you are interested in sharing sign-in state across applications, if that is the case you can accomplish this via our support for [SSO on iOS](https://docs.microsoft.com/en-us/azure/active-directory/develop/single-sign-on-macos-ios).
