### ISSUE TITLE
Add error check for trying to use a User from a mismatched environment

### ISSUE THREAD

**Issue by RPangrle** [AzureAD/microsoft-authentication-library-for-objc#115]
Users are tied to a specific authentication environment (e.g. "login.microsoftonline.com" vs "login.microsoftonline.de") and currently are not supported to be used across environment. We should fail predictably in those cases.

**Comment by partnerinflight** [comment]
Sync with other platforms; we may want this for Build.

**Comment by unpluggedk** [comment]
Other platforms don't do this. Will investigate further on whether or not this is needed.

**Comment by unpluggedk** [comment]
@RPangrle  I think it is true for acquire token silent, but is this the case with interactive as well?

**Comment by unpluggedk** [comment]
This is an ongoing discussion and will depend on that decision, same for all other platforms.
