### ISSUE TITLE
Interfacing with SwiftUI

### ISSUE THREAD

**Issue by honkmaster** [AzureAD/microsoft-authentication-library-for-objc#1152]
SwiftUI has no concept of ViewControllers.
Unfortunately, `MSALWebviewParameters` needs exactly this as input.
Of course, we could use the `SceneDelegate`:

```
guard let sceneDelegate = UIApplication.shared.connectedScenes.first?.delegate as? SceneDelegate else {
	// Error handling
	return
}
guard let viewController = sceneDelegate.window?.rootViewController else {
	// Error handling
	return
}
let webviewParameters = MSALWebviewParameters(authPresentationViewController: viewController)
```

However, this approach does not feel native and fragile. Any better Idea how to handle this?

**Comment by kaisong1990** [comment]
@honkmaster Thanks for your question, SwiftUI should be compatible with UIKit and here are some guidances to Apple doc:
https://developer.apple.com/tutorials/swiftui/interfacing-with-uikit

Currently we don't have ways of supporting SwiftUI without UIKit
