### ISSUE TITLE
ITMS-90338: Non-public API usage - execute, initWithClientId:error:, initWithParentViewController:, removeAccount:error:

### ISSUE THREAD

**Issue by hroblesm** [AzureAD/microsoft-authentication-library-for-objc#1155]
Hi,

I'm trying to upload my app that use your MSAL library 1.1.7. After pass the initial validation I received the following from Apple:

Dear Developer,
We identified one or more issues with a recent delivery for your app, "XXXXXXXXX". Please correct the following issues, then upload again. 
ITMS-90338: Non-public API usage - The app references non-public selectors in WeavLT-prod-1.10.1: execute, initWithClientId:error:, initWithParentViewController:, removeAccount:error:. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/ 
Best regards,
The App Store Team

Best regards,
Hugo Robles

**Comment by aherciya** [comment]
Hi @hroblesm, neither MSAL 1.1.7 or MSAL latest contains those specific API's(i.e. we don't share the same method signatures as initWithClientId:error:, initWithParentViewController:, removeAccount:error). Were you able to submit a ticket with apple through the [support link?](https://developer.apple.com/support/technical/) they provided? If they isolate the issue to MSAL please let us know.

**Comment by hroblesm** [comment]
Hi @aherciya , following is the answer I got from Apple support team:

"This is Steven from Apple Developer Program Support, and I am following up with you regarding the message you received when you attempted your most recent upload to App Store Connect.

I have been informed that a review by my engineers has revealed the use of the API “initWithParentViewController:”, which is a non-public API. Please verify its inclusion in your project, and remove any references. Once removed, please attempt to re-upload your build again. "

**Comment by aherciya** [comment]
Hi @hroblesm, It seems you are using a [deprecated API](https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALWebviewParameters.html#/c:objc(cs)MSALWebviewParameters(im)initWithAuthPresentationViewController).

**Comment by hroblesm** [comment]
Hi @aherciya , which version should I use?

**Comment by aherciya** [comment]
@hroblesm For instance if you are using **initWithParentViewController**:, then you should replace that by using **initWithAuthPresentationViewController:** instead.

**Comment by hroblesm** [comment]
I'm not using initWithParentViewController at all. What Apple complains is about the methods.

**Comment by mbondoso** [comment]
Hi, I am also getting this error: 
ITMS-90338: Non-public API usage - The app references non-public selectors in XXXX: idToken, initWithParentViewController:, removeAccount:error:. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed.

**Comment by aherciya** [comment]
@mbondoso @hroblesm Can you tell us how you are consuming MSAL, i.e. CocoaPods, Carthage, Framework or a Static Lib?

**Comment by mbondoso** [comment]
@aherciya I'm using via Carthage

**Comment by ameyapat** [comment]
We'll open a feedback with Apple regarding this and provide an update.

**Comment by aherciya** [comment]
@mbondoso @hroblesm Do you mind providing either a ticker number or your app name and date when this App Store submission issue occurred? You can send this privately at aherciya@microsoft.com.

**Comment by mbondoso** [comment]
Hi, I emailed it to you.
Thanks for the help.

**Comment by hieunguyenmsft** [comment]
We've filed a TSI ticket with Apple and waiting for their response. Will keep you posted.

**Comment by mbondoso** [comment]
Hi @hieunguyenmsft any news from Apple?

**Comment by oldalton** [comment]
We're still following up with Apple, but haven't received any specific guidance yet. I think it would be great if you could also follow up on your side so that Apple could look into the specifics of your project/app. Thanks.

**Comment by mipetriu** [comment]
Marking as external to prevent this issue from becoming stale while we wait for a response from Apple.

**Comment by hieunguyenmsft** [comment]
Remove stale tag, still waiting for a response from Apple.

**Comment by hieunguyenmsft** [comment]
Hi @hroblesm @mbondoso pleaset let me know if you are still having this issue or I can close the ticket. Thank you.
