### ISSUE TITLE
Our App is rejected due to UIWebView api

### ISSUE THREAD

**Issue by TayyabAli652** [AzureAD/microsoft-authentication-library-for-objc#1161]
I used this library and also set ` webViewParamaters?.webviewType = .wkWebView` everything was good but when we upload app on app store app store reject app due to UIWebView used in this library. Please remove UIWebView and use only WKWebView.

![image](https://user-images.githubusercontent.com/46528730/99882494-b02af100-2c42-11eb-8ba2-63d5041ce699.png)

**Comment by oldalton** [comment]
Which MSAL version are you using? Some older MSAL versions had "UIWebView" in the comment which was triggering this. It should be now fixed, so please make sure you're using the latest version.

**Comment by TayyabAli652** [comment]
My mistake I'm using OneDriveSDK and MSAL both but forgot to remove OneDriveSDK and I thought it's MSAL error,
