### ISSUE TITLE
How to check the service availability(via MS Graph) for specified account?

### ISSUE THREAD

**Issue by S2V** [AzureAD/microsoft-authentication-library-for-objc#1162]
I was faced with some confusing behavior. I try to sign in with Office 365 account, which doesn't have access to the mail-box(Outlook, I mean). Of course, my application has required scope items like `[Mail.Send, User.Read]`. Sign in is successful with result scope `[Mail.Send, User.Read, email, openid, profile]`. And when I try to send mail, obvious, occurred the 404 error. How can I check the availability of sending mails via MS Graph directly or using scope `Mail.Send`, or configure my sign-in in a specific way to receive the error?

**Comment by antrix1989** [comment]
@S2V which URL are you using to send an email?

**Comment by S2V** [comment]
@antrix1989 I'm set up my request for sending with the`https://graph.microsoft.com/v1.0/me/sendMail` URL

**Comment by antrix1989** [comment]
That is a correct url. @S2V please capture a network trace and send it to my email: sedemche@microsoft.com. I will followup with out server team.

**Comment by S2V** [comment]
Hello @antrix1989 , pls check your email-box

**Comment by antrix1989** [comment]
Thanks @S2V, I replied in the email thread.
