### ISSUE TITLE
MSAL iOS how to leverage broker when device auth was triggered in silent auth call

### ISSUE THREAD

**Issue by JimmyLS** [AzureAD/microsoft-authentication-library-for-objc#1165]
We have a customer facing below issue:

They developed iOS app (object C) integrated with MSAL library, also configured required things for using Broker.

When calling MAM from the app it's leveraging broker fine, and got Access token & Refresh token back.

When calling other APIs, the app was using its own refresh token without going through Broker, and blocked by their MAM CA policy saying "Device auth required".

**However, their app then didn't forward request to broker and was trying to do PkeyAuth by itself which caused another error "Broker app not installed".**

My question is:

**From App side, how to leverage broker when device auth was triggered in silent auth call(with existing refresh token)? Is this supposed to be handled by MSAL ios automatically or we should add error handling logic to achieve this?**

**Comment by kaisong1990** [comment]
@JimmyLS Thanks for your question, broker doesn't support silent flow with existing refresh token from another app. However, MSAL provides a public API where developers can use to redeem new access token by using existing refresh token:

https://github.com/AzureAD/microsoft-authentication-library-for-objc#silently-acquiring-an-updated-token

Developers needs to implement this silent call as needed.

**Also could you clarify what do you mean by "When calling other APIs, the app was using its own refresh token without going through Broker"?**

Refresh token is used to get new access token and cannot be used to call other APIs directly

**Comment by JimmyLS** [comment]
@kaisong1990 

I should explain it more clear sorry. I mean when the application tries to redeem new access token with its refresh token, this auth call is blocked by Conditional access policy which requires Compliant MAM app (device auth required and the request must come from broker). **In such case will MSAL ios automatically handle the error and send request to broker instead, or developers should add error handling logic by themselves to deal with the error.**

**Comment by kaisong1990** [comment]
@JimmyLS Thanks for clarifying your question. We don't handle errors on behalf of our developers when there is a silent call error. So developers will need to handle the error accordingly

**Comment by JimmyLS** [comment]
@kaisong1990  
Yes I've proved that by testing, thanks for the clarificaiton!
