### ISSUE TITLE
Microsoft Authentication Login not working

### ISSUE THREAD

**Issue by ramohanreddy** [AzureAD/microsoft-authentication-library-for-objc#1167]
Hi @odin-2711 @boumenot @oldalton 

i am facing login issue. I am not able to get login option in alert.
Please find the below screen shot for reference.
![1606994832881](https://user-images.githubusercontent.com/18551145/101020725-ef3b3980-3594-11eb-871f-5707e68eda17.JPEG)

**Comment by kaisong1990** [comment]
@ramohanreddy Thanks for providing the screenshot. This error means current log in session is not closed yet and user is trying to start a new session.

Could you provide more details so that we can try to reproduce this issue? Thanks

**Comment by ramohanreddy** [comment]
Hi @kaisong1990 ,

What type details i need provide

**Comment by kaisong1990** [comment]
> Hi @kaisong1990 ,
> 
> 
> 
> What type details i need provide
> 
> 

For example, did you get the issue immediately after starting MSAL sample app or if you have tried to login and dismiss the login view somehow.

It would helpful if you could provide a video or the steps to reproduce the issue.

**Comment by ramohanreddy** [comment]
okay let me create video.

**Comment by guidedways** [comment]
I'm seeing the following for some users. This is for an O365 account. Any idea what's going on?

```
MSAL: could not aquire token: Error Domain=MSALErrorDomain Code=-50005 "(null)" UserInfo={MSALErrorDescriptionKey=User cancelled the authorization session., MSALCorrelationIDKey=B165E481-32B7-4FE1-8C7E-4C044172C5C4} => {
    MSALCorrelationIDKey = "B165E481-32B7-4FE1-8C7E-4C044172C5C4";
    MSALErrorDescriptionKey = "User cancelled the authorization session.";
}
```

**Comment by kaisong1990** [comment]
@guidedways Thanks for your question, this means user manually canceled the current authentication session (For example, user clicks the top left button to dismiss the log in view on iOS) which is an expected error.

If you think this is unexpected in your case, please create a separate issue in our repo and provide user scenarios.

**Comment by ramohanreddy** [comment]
Hi @kaisong1990  
i am not able  login with multiple accounts.
i am getting this error.

**Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=Multiple accounts found in cache., MSALInternalErrorCodeKey=-42102}**

can you please check this once.

**Comment by kaisong1990** [comment]
@ramohanreddy Thanks for your question. This error message normally means your current account changes when calls the following public API:

```- (void)getCurrentAccountWithParameters:(nullable MSALParameters *)parameters completionBlock:(MSALCurrentAccountCompletionBlock)completionBlock;```

Were you trying to log in a new account without logout the current account?
