### ISSUE TITLE
iOS Alert Pop Up Disappears

### ISSUE THREAD

**Issue by amansharma2014** [AzureAD/microsoft-authentication-library-for-objc#1183]
Hi,

I am facing one weird issue with current SDK. Whenever iOS Alert Controller appears which ask for user permissions via Web Interactive Login appears where we have options to **Continue** and **Cancel**. 

If user puts app in background then that alert Pop Up disappears and Azure starts giving error whenever user try to login again.

Is there any way by which we can know user has cancelled or given Permission for Interactive Login. 

Device - **iPhone X iOS 14.2**

**Comment by kaisong1990** [comment]
Hi @amansharma2014,

Thanks for your question, we are trying to reproduce the scenario and cannot put app into background when system popover is in front view. 

Developers should know if user canceled the current process or other type of errors in the ```completionBlock``` from ```MSALPublicClientApplication```. For example:

```- (void)acquireTokenWithParameters:(nonnull MSALInteractiveTokenParameters *)parameters completionBlock:(nonnull MSALCompletionBlock)completionBlock;```

Would you provide the error messages you were getting and the process to putting app into background while the popover is showing?

**Comment by amansharma2014** [comment]
> Hi @amansharma2014,
> 
> Thanks for your question, we are trying to reproduce the scenario and cannot put app into background when system popover is in front view.
> 
> Developers should know if user canceled the current process or other type of errors in the `completionBlock` from `MSALPublicClientApplication`. For example:
> 
> `- (void)acquireTokenWithParameters:(nonnull MSALInteractiveTokenParameters *)parameters completionBlock:(nonnull MSALCompletionBlock)completionBlock;`
> 
> Would you provide the error messages you were getting and the process to putting app into background while the popover is showing?

Hi,

Steps to Reproduce - 
1. Authentication Alert Pop Up Appears
2. Lock iPhone via Right Side Button
3. Unlock iPhone Alert Disappears

**Comment by kaisong1990** [comment]
Thanks and we will look into it

**Comment by kaisong1990** [comment]
We have tested and don't get callbacks from Apple API when device is locked in this scenario. Will reach out to Apple for guidance and post updates here
