### ISSUE TITLE
Is it possible to do client credentials flow for Microsoft Azure active directory with this library?

### ISSUE THREAD

**Issue by jeevanbalanmanoj** [AzureAD/microsoft-authentication-library-for-objc#1186]
Can this library be used to implement [client credentials flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow) for the azure active directory? If so please provide me with the samples or documentation on doing so

**Comment by kaisong1990** [comment]
Hi @jeevanbalanmanoj Thanks for your question.

Our library doesn't support client credentials flow. Flows which mobile is supported can be found [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows#client-credentials)
