### ISSUE TITLE
Azure Application Proxy accessing issue using MSAL token

### ISSUE THREAD

**Issue by pranayubs** [AzureAD/microsoft-authentication-library-for-objc#1187]
We are trying to access the Azure Application Proxy endpoint using MSAL token but it is being redirected to login.microsoft.com instead getting a json response

`https://login.microsoftonline.com/**tenant_id**/oauth2/authorize?response_type=code&client_id=**client_id**&scope=openid&nonce=**nonce**&redirect_uri=https%3a%2f%2fXXXXXXXXX.msappproxy.net%2fapi%2f&state=AppProxyState%3a%7b%22InvalidTokenRetry%22%3anull%2c%22IsMsofba%22%3afalse%2c%22OriginalRawUrl%22%3a%22https%3a%5c%2f%5c%2fXXXXXXXXXX.net%5c%2fapi%5c%2fv1%5c%2fmobile%5c%2flogin%22%2c%22RequestProfileId%22%3anull%7d%23EndOfStateParam%23&client-request-id=db0a936a-XXXXXXX`

Any ideas what's wrong here?

**Comment by kaisong1990** [comment]
Hi @pranayubs, could you provide the correlationId and we will take a look?

**Comment by pranayubs** [comment]
@kaisong1990 
Can you please advice from where I can get the correlationId? I am getting below response on the api call

`{ URL: https://login.microsoftonline.com/XXXXXXXXX/oauth2/authorize?response_type=code&client_id=XXXX&scope=openid&nonce=ddcacdae-8f62-4008-86d2-16b00126248b&redirect_uri=https%3a%2f%2fXXXX%2fapi%2f&state=AppProxyState%3a%7b%22InvalidTokenRetry%22%3atrue%2c%22IsMsofba%22%3afalse%2c%22OriginalRawUrl%22%3a%22https%3a%5c%2f%5c%2fXXXXXXXXXX%5c%2fapi%5c%2fv1%5c%2fmobile%5c%2flogin%22%2c%22RequestProfileId%22%3a%22f6fe682f-2aa5-47ea-8d1f-65232411340b%22%7d%23EndOfStateParam%23&client-request-id=3924575d-565e-43cd-8c8d-a45573587c32 } { Status Code: 200, Headers {
    "Cache-Control" =     (
        "no-store, no-cache"
    );
    "Content-Encoding" =     (
        gzip
    );
    "Content-Length" =     (
        47397
    );
    "Content-Type" =     (
        "text/html; charset=utf-8"
    );
    Date =     (
        "Wed, 06 Jan 2021 15:11:12 GMT"
    );
    Expires =     (
        "-1"
    );
    Link =     (
        "<https://aadcdn.msftauth.net>; rel=preconnect; crossorigin",
        "<https://aadcdn.msftauth.net>; rel=dns-prefetch",
        "<https://aadcdn.msauth.net>; rel=dns-prefetch"
    );
    P3P =     (
        "CP=\"DSP CUR OTPi IND OTRi ONL FIN\""
    );
    Pragma =     (
        "no-cache"
    );
    "Set-Cookie" =     (
        "buid=0.ASEAu9QWoEY09UOonB2eCJyX55fgqBiN7JBLlJ-IdTKHg24hAAA.AQABAAEAAABeStGSRwwnTq2vHplZ9KL4CWfDGulaRjr8sFLQbfvhaBS7uLCnYdxExeFqq1HHpc483ubI_oR3k7VwyarHlvIGpr96Gu5qpr0Pw3vwKL1zdQMAVGBTxo1SsdFsGDr6dykgAA; expires=Fri, 05-Feb-2021 15:11:12 GMT; path=/; secure; HttpOnly; SameSite=None",
        "fpc=AlaB15J77sJErGPPUjpy62BYLT1AAgAAAN7Jh9cOAAAA; expires=Fri, 05-Feb-2021 15:11:12 GMT; path=/; secure; HttpOnly; SameSite=None",
        "esctx=AQABAAAAAABeStGSRwwnTq2vHplZ9KL46S66xWy3T0stmnDjUX47JN4V7phvJSRqxmP1lHkJH0UQo4NWJMA0bHL2n9X-tZQOk2Lrzqrvx_AOlIyk_SmITXQz0goxojPmkfew03vFd34pvbh9W7UYQIHcoYEAmKVJ54Y5krUtLiOi62aHxy7_nSPknCfFKwYv65PZESadTVsgAA; domain=.login.microsoftonline.com; path=/; secure; HttpOnly; SameSite=None",
        "x-ms-gateway-slice=estsfd; path=/; secure; samesite=none; httponly",
        "stsservicecookie=estsfd; path=/; secure; samesite=none; httponly"
    );
    "Strict-Transport-Security" =     (
        "max-age=31536000; includeSubDomains"
    );
    Vary =     (
        "Accept-Encoding"
    );
    "X-Content-Type-Options" =     (
        nosniff
    );
    "X-DNS-Prefetch-Control" =     (
        on
    );
    "X-Frame-Options" =     (
        DENY
    );
    "x-ms-ests-server" =     (
        "2.1.11384.3 - WEULR1 ProdSlices"
    );
    "x-ms-request-id" =     (
        "50f90f23-c7f7-4855-be52-388cf98f2400"
    );
} })`

**Comment by kaisong1990** [comment]
@pranayubs 

correlationId can be found in logs like when there is an error returned during authentication.

After looking into your response, we noticed it said invalidTokenRetry within the URL, and the url you provided is for a new authentication flow. So the potential issue could be that the MSAL token you were using is invalid. Would you try to fetch a new access token and try again?

**Comment by pranayubs** [comment]
Thanks @kaisong1990 for your reply.

I tried with access token and refresh token but always retrieved same error.

**Comment by kaisong1990** [comment]
When putting the credentials after the new login screen prompt from above URL, will the new access token work for you? 

Could you give a try with our [iOS sample app](https://github.com/Azure-Samples/ms-identity-mobile-apple-swift-objc) and [Mac sample app](https://github.com/Azure-Samples/ms-identity-macOS-swift-objc) and see if the same thing happens?

**Comment by pranayubs** [comment]
Hi @kaisong1990,
I tried with your iOS sample app as well but **NO** luck.

We are getting access_token and using that token we are able to get the user details from Graph API.
https://graph.microsoft.com/v1.0/me/ 
Result from Graph: 
```
{
    "@odata.context" = "https://graph.microsoft.com/v1.0/$metadata#users/$entity";
    businessPhones =     (
    );
    displayName = "XXXX,XXXX";
    givenName = XXXX;
    id = "xxxxx-xxxxx-xxxx-xxx-xxxxx";
    jobTitle = "xxxxx";
    mail = "xxxxx@xxxxx.com";
    mobilePhone = "<null>";
    officeLocation = XXXX;
    preferredLanguage = EN;
    surname = XXXXXX;
    userPrincipalName = "xxxxxx@xxxx.com";
})
```

But when we tried to call the Azure Proxy URL/API, Its not working. It always return redirection URL instead JSON data.
Below is the request and response details.
```
func callAzureAppProxy() {        
        let url = URL(string: "https://xxxxx-xxxx.msappproxy.net/api/version/login")
        var request = URLRequest(url: url!)
        
        request.setValue("Bearer \(self.accessToken)", forHTTPHeaderField: "Authorization")
        request.addValue(self.accessToken, forHTTPHeaderField: "REQUIRED-HEADER-TO-ACCESS-ON-PREM-SERVICE")
        request.addValue("application/json", forHTTPHeaderField: "Content-Type")
        
        URLSession.shared.dataTask(with: request) { data, response, error in            
            if let error = error {
                self.updateLogging(text: "Couldn't get azure app proxy result: \(error)")
                return
            }
            guard let result = try? JSONSerialization.jsonObject(with: data!, options: []) else {
                self.updateLogging(text: "Couldn't deserialize azure app proxy result:")
                return
            }

            self.updateLogging(text: "Result from azure app proxy: \(result))")
            }.resume()
    }
```
Response:
```
Optional(<NSHTTPURLResponse: 0x280f01580> { URL: https://login.microsoftonline.com/xxxxx-xxxx-xxxxx-xxxx-xxxxxxxxx/oauth2/authorize?response_type=code&client_id=xxxxxxx-xxxxx-xxxxx-xxxx-xxxxxxx&scope=openid&nonce=xxxxx-xxxxx-xxxxx-xxxx-xxxxxx&redirect_uri=https%3a%2f%2fxxxxxxxx-xxxxxxxxx.msappproxy.net%2fapi%2f&state=AppProxyState%3a%7b%22InvalidTokenRetry%22%3atrue%2c%22IsMsofba%22%3afalse%2c%22OriginalRawUrl%22%3a%22https%3a%5c%2f%5c%2fxxxxxxx-xxxxxx.msappproxy.net%5c%2fapi%5c%2fv1%5c%2fmobile%5c%2flogin%22%2c%22RequestProfileId%22%3a%225fddf484-e994-49fb-xxxx-xxxxxxxe%22%7d%23EndOfStateParam%23&client-request-id=xxxxx-7357-xxx-bf8c-xxxxxx } { Status Code: 200, Headers {
    "Cache-Control" =     (
        "no-store, no-cache"
    );
    "Content-Encoding" =     (
        gzip
    );
    "Content-Length" =     (
        47400
    );
    "Content-Type" =     (
        "text/html; charset=utf-8"
    );
    Date =     (
        "Thu, 14 Jan 2021 05:57:47 GMT"
    );
    Expires =     (
        "-1"
    );
    Link =     (
        "<https://aadcdn.msftauth.net>; rel=preconnect; crossorigin",
        "<https://aadcdn.msftauth.net>; rel=dns-prefetch",
        "<https://aadcdn.msauth.net>; rel=dns-prefetch"
    );
    P3P =     (
        "CP=\"DSP CUR OTPi IND OTRi ONL FIN\""
    );
    Pragma =     (
        "no-cache"
    );
    "Set-Cookie" =     (
        "buid=0.ASEAu9QWoEY09UOonB2eCJyX55fgqBiN7JBLlJ-IdTKHg24hAAA.AQABAAEAAABeStGSRwwnTq2vHplZ9KL4Z99tZ62OTHNA9wQWhma2TAt0gBQqaqg6J9sVJQNjALVng1TCN6yCZcKyMgUi6JPhQwrv1KC1KTawyWGamxxEZGJ2wXhuQOkNX3v4BHIBNf4gAA; expires=Sat, 13-Feb-2021 05:57:48 GMT; path=/; secure; HttpOnly; SameSite=None",
        "fpc=AhaToMSqAwZBqo1yOf9Ih0xYLT1AAgAAAN3TkdcOAAAA; expires=Sat, 13-Feb-2021 05:57:48 GMT; path=/; secure; HttpOnly; SameSite=None",
        "x-ms-gateway-slice=estsfd; path=/; secure; samesite=none; httponly",
        "stsservicecookie=estsfd; path=/; secure; samesite=none; httponly"
    )
```

Can you help with this issue please?

**Comment by pranayubs** [comment]
Hi @kaisong1990, Any inputs on above please?

**Comment by kaisong1990** [comment]
Hi @pranayubs 

Sorry for the late reply, we are currently working with application proxy team and figuring out why the token is not working Will update with more info  in this  thread as soon as we get a response from the other team

**Comment by kalyankrishna1** [comment]
@pranayubs why are you send the token to *https://xxxxx-xxxx.msappproxy.net/api/version/login*? you should send it to your API exposed via App Proxy, i.e. the "External Url" [Reference](https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/application-proxy-secure-api-access)

**Comment by kalyankrishna1** [comment]
@pranayubs , if you have resolved this issue, let us know. We'd then close this issue.

**Comment by pranayubs** [comment]
@kalyankrishna1  https://xxxxx-xxxx.msappproxy.net/api this is the External URL only. We have mentioned Internal URL in Azure Portal and using external URL for API communication.

**Comment by pranayubs** [comment]
@kaisong1990, @kalyankrishna1  Any inputs on above please?

**Comment by kaisong1990** [comment]
@kalyankrishna1 Could you provide mode info here?

**Comment by kalyankrishna1** [comment]
oh, thanks for clarifying. @pranayubs there is no such thing as a MSAL token. what you have a token that is got a resource named "MS Graph", i.e. https://graph.microsoft.com". please replace the Graph URL with your URL, "https://xxxxx-xxxx.msappproxy.net" in the code and the new Access token that MSAL gets you would work for your App proxy endpoint

**Comment by kalyankrishna1** [comment]
@pranayubs , could you also share the code that signs-in the users and gets you a token..

**Comment by githubarpyka** [comment]
@pranayubs 
If the access token is not valid, the Azure AD Application Proxy will redirect the incoming request to login.microsoftonlie.com.

We have 2 articles that describe the scenario in detail, you'd like to implement:

https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/application-proxy-configure-native-client-application
https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/application-proxy-secure-api-access

Most of the time we see that the audience in the token is not the external URL of the Azure AD Application Proxy app, but something else.
Another common issue that the / is missing from the end of the external URL in the audience attribute.

Example:
Incorrect: https://test-contoso.msappproxy.net
Correct: https://test-contoso.msappproxy.net/

**Comment by kaisong1990** [comment]
@pranayubs we are closing this issue since there is no active conversation for more than 14 days. Feel free to reopen if you have further questions

**Comment by alex-ferener** [comment]
I've spent countless hours troubleshooting the issue as well. This  answer worked from me: https://learn.microsoft.com/en-us/answers/questions/1187666/ms-app-proxy-works-in-browser-fails-in-app-with-to
