### ISSUE TITLE
Swift PM instructions are invalid

### ISSUE THREAD

**Issue by guidedways** [AzureAD/microsoft-authentication-library-for-objc#1195]
The main page suggests we set 1.1.14 as the min version when setting up with Swift PM, yet no such version exists.

**Comment by guidedways** [comment]
I see this is because the `dev` branch seems to have been set as the main branch. Having said that, it's still not working if I pick `dev` as the branch to pull from. How can I test SwiftPM distribution?

**Comment by kaisong1990** [comment]
Hi @guidedways 

Thanks for your question. Yes, we haven't released the version 1.1.14 yet. We are still finalizing SPM support and will post more information in the [thread](https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/737) once it is ready for testing/integrating. Let us know if you have more questions.

**Comment by guidedways** [comment]
Thank you! Desperately waiting. Sick of dealing with all other distribution methods that come with their own sets of problems.

**Comment by kaisong1990** [comment]
@guidedways I will merge this thread to the SPM thread I posted above and feel free to reopen it if you have further question
