### ISSUE TITLE
How to get authorization code using provided MSAL framework, its urgent please help!

### ISSUE THREAD

**Issue by rishabsahu1996** [AzureAD/microsoft-authentication-library-for-objc#1196]
There are no instructions for how to get an authorization code using the library, there is only instructions for tokens.
Please help me I am stuck its urgent.

**Comment by oldalton** [comment]
Can you please clarify why you would need access to the authorization code?
MSAL doesn't provide you with a direct access to the authorization code - just the tokens (access and id tokens).

**Comment by rishabsahu1996** [comment]
Actually, I need an authorization code for calling web service APIs.

**Comment by rishabsahu1996** [comment]
https://login.microsoftonline.com/{tenant}/oauth2/v2.0/authorize?
client_id=6731de76-14a6-49ae-97bc-6eba6914391e
&response_type=code
&redirect_uri=http%3A%2F%2Flocalhost%2Fmyapp%2F
&response_mode=query
&scope=openid%20offline_access%20https%3A%2F%2Fgraph.microsoft.com%2Fmail.read
&state=12345
&code_challenge=YTFjNjI1OWYzMzA3MTI4ZDY2Njg5M2RkNmVjNDE5YmEyZGRhOGYyM2IzNjdmZWFhMTQ1ODg3NDcxY2Nl
&code_challenge_method=S256

**Comment by oldalton** [comment]
@rishabsahu1996, MSAL would make this request internally, then exchange authorization code for tokens and return you the tokens. You should be using access tokens to call APIs. You can read more about access tokens here: https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens

**Comment by krispykalsi** [comment]
I need to log in the user from the app and then send the authorization code to our backend server where it will exchange it for the access and refresh tokens for offline use. How can I achieve that?
