### ISSUE TITLE
Unable to Select Account and/or log in to a different account after having logged in before

### ISSUE THREAD

**Issue by tysonkerridge** [AzureAD/microsoft-authentication-library-for-objc#1197]
Hi, I'm having an issue where the "Select Account" login flow isn't working on iOS 14.2, seemingly regardless of the `promptType` applied to the `MSALInteractiveTokenParameters`. Noticed the issue using MSAL v1.0.6, and updating to v1.1.13 hasn't made a difference. I believe it worked at the end of 2020.

If I log into "Account 1", and then try to log in with "Account 2" it instead redirects to a page that wants to use "Account 1". I've found a 'workaround' which is to go into Safari, navigate to microsoft.com and log in and out there, and then I can go back to the app and log in with "Account 2" but this is less than ideal. I believe the log in flow used to show a list of existing accounts (in the case where `promptType` is set to `selectAccount`) but this no longer seems to be the case. 

Am I missing something or is there something that changed on MS end? Happy to provide any additional details. 

Here's some screenshots of the flow
Log in to Account 1:
![Log In 1](https://user-images.githubusercontent.com/3983116/104531715-8696b080-565a-11eb-82c1-c96e1e3b4426.PNG)
![Log in 2](https://user-images.githubusercontent.com/3983116/104531723-8b5b6480-565a-11eb-969d-f637d4e10030.PNG)
![Log in 3](https://user-images.githubusercontent.com/3983116/104531728-8eeeeb80-565a-11eb-8bbf-df8d22e895c8.PNG)

Attempt to log into Account 2 after having logged into Account 1:
![Log in again 1](https://user-images.githubusercontent.com/3983116/104531748-9910ea00-565a-11eb-84c4-8e7b33295c0a.PNG)
![Log in again 2](https://user-images.githubusercontent.com/3983116/104531750-9adaad80-565a-11eb-8273-8845163548ca.PNG)

Workaround - Log out of Account 1 in Safari (tapping log in auto signed in, then pressing sign out). After doing so, can try log in with Account 2:
![Sign out in safari 1](https://user-images.githubusercontent.com/3983116/104531797-b0e86e00-565a-11eb-8893-428c8b55a357.PNG)
![Sign out in safari 2](https://user-images.githubusercontent.com/3983116/104531822-b5ad2200-565a-11eb-9161-a9262b1e2080.PNG)

**Comment by hieunguyenmsft** [comment]
Thank you for reporting this bug. We're following with our server team to figure out the issue and will keep you posted.

**Comment by jasoncoolmax** [comment]
@tysonkerridge this looks like a regression that our server team has recently fixed. Could you try again to see if the issue has been resolved? If not, could you catch the network trace (like using Charles Trace) such that we can do further investigation? 
Thank you very much!

**Comment by tysonkerridge** [comment]
Hey @jasoncoolmax, it looks like the issue is fixed, to a degree. I don't think it works as it used to, as I believe it used to show a list of logged in accounts and/or to add to the list, but it at least gives the user the option to sign in using a different account now compared to no option at all. Screenshot included below, so closing this issue. Thanks for the info and investigating! I imagine the changes to the UX are for a reason 🙂
![login recent](https://user-images.githubusercontent.com/3983116/105653152-c7b67c80-5f06-11eb-9cd5-75678ddf4d90.jpeg)

**Comment by jasoncoolmax** [comment]
Thank you @tysonkerridge for getting back. Glad that your issue has been resolved.

Regarding the screen you saw, it is expected for Microsoft Account (MSA account), where we only support one MSA being signed in at a time. 
What you mentioned regarding seeing a list of signed-in accounts is only for AAD accounts, but not MSA accounts.

**Comment by tysonkerridge** [comment]
@jasoncoolmax Ahh yes, the AAD account difference makes sense, thanks!

**Comment by yyken** [comment]
Hi, I have the same issue on iOS 14, but it works on iOS 13

I try to log in with "Account 2"

![image](https://user-images.githubusercontent.com/2316280/106582350-dd6b1800-657e-11eb-89db-926f1f5d60ac.png)

![image](https://user-images.githubusercontent.com/2316280/106582303-cfb59280-657e-11eb-9234-be260df8e17c.png)

**it always shows "Account 1"**

![image](https://user-images.githubusercontent.com/2316280/106582336-d80dcd80-657e-11eb-8e04-a023815b54f3.png)
