### ISSUE TITLE
Crash found on webAuthSession start when running on iOS 13 simulator with M1 mac

### ISSUE THREAD

**Issue by zntfdr** [AzureAD/microsoft-authentication-library-for-objc#1198]
In `MSIDASWebAuthenticationSessionHandler.m`:
<img width="902" alt="Screenshot 2021-01-14 at 12 02 52" src="https://user-images.githubusercontent.com/5277837/104547794-fceae100-5661-11eb-8023-12c08bd7ca69.png">

This can be reproduced on the MSAL iOS sample app as well.

Steps to reproduce the issue:
1. `git clone https://github.com/Azure-Samples/ms-identity-mobile-apple-swift-objc.git`
2. run `pod install`
3. open `open MSALiOS.xcworkspace`
4. run `MSALiOS` with an iOS 13 simulator target (I used iPhone 12 Pro max, iOS 13.4)
5. tap `call Microsoft Graph API` on the app
6. see the crash happen

Environment:
- M1 air
- Xcode 12.2 running under rosetta (it won't even build if not under rosetta) .

No problem found when running on M1 with iOS 14 simulators, or on Intel macs (with any iOS).

Edit:
the sample app uses an old version of MSAL sdk, however it happens also when using the latest `1.1.13` version

**Comment by hieunguyenmsft** [comment]
Thank you for reporting the bug. We're trying to reproduce it and will update you.

**Comment by zntfdr** [comment]
Update: I've moved to `1.1.14`, SPM, and Xcode 12.4.

The crash still happen when running on iOS 13 simulators (no problems in iOS 14), just in a different, less helpful place:

<img width="847" alt="Screenshot 2021-01-26 at 09 48 55" src="https://user-images.githubusercontent.com/5277837/105793685-27bb2a80-5fbc-11eb-9eb0-211553af6f19.png">

The steps to get the crash are the same as before (replace the cocoapods steps with SPM installation).

**Comment by zntfdr** [comment]
Update: according to [Xcode 12.5 beta release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-12_5-beta-release-notes/), this is a known bug on Apple's side:

<img width="758" alt="Screenshot 2021-02-02 at 09 20 27" src="https://user-images.githubusercontent.com/5277837/106543263-ebe21100-6537-11eb-8997-78f2a62d83df.png">

**Comment by zntfdr** [comment]
This is now fixed in Xcode 12.5b2:
<img width="756" alt="Screenshot 2021-02-17 at 10 56 48" src="https://user-images.githubusercontent.com/5277837/108155181-fd6b1180-7110-11eb-88f1-cae1ee44b617.png">
