### ISSUE TITLE
Failed to retrieve the Device ID claim post device got registered to Azure through Authenticator App.

### ISSUE THREAD

**Issue by rahulcode** [AzureAD/microsoft-authentication-library-for-objc#1204]
**Issue** 
Failed to retrieve the Device ID claim post device got registered to Azure through Authenticator App
MSALErrorDescriptionKey = "Failed to get session key from JWE.";

Microsoft Authenticator Ticket ID 

![IMG_0131 3](https://user-images.githubusercontent.com/19573187/106245048-db792000-6231-11eb-8047-48ef233056e7.PNG)

Issue Description:

Sometimes using MSAL we are not able to retrieve the device ID with device ID claim from authenticator Application, though the device got registered it Azure AD successfully and shows correctly in Authenticator app as well as on azure portal.

As there are no specific steps to get into this state, attached all logs.

[Application_MSAL_Logs.txt](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/5892335/Application_MSAL_Logs.txt)
[Authenticator.log](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/5892337/Authenticator.log)

Snippet of Error
`29/01/2021 11:15:23:444|FLMSALLogManager|logMSALMessage:containsPii:logLevel:[604206]|78<Info>: TID=599377 MSAL 1.1.13 iOS 14.0 [2021-01-29 05:45:23] Handling broker response.
 29/01/2021 11:15:23:444|FLMSALLogManager|logMSALMessage:containsPii:logLevel:[604206]|78<Info>: TID=599377 MSAL 1.1.13 iOS 14.0 [2021-01-29 05:45:23] Init MSIDKeychainTokenCache with keychainGroup: WJ57EDFK5E.com.microsoft.adalcache
 29/01/2021 11:15:23:444|FLMSALLogManager|logMSALMessage:containsPii:logLevel:[604206]|78<Info>: TID=599377 MSAL 1.1.13 iOS 14.0 [2021-01-29 05:45:23] Init MSIDKeychainTokenCache with keychainGroup: WJ57EDFK5E.com.microsoft.adalcache
 29/01/2021 11:15:23:461|FLMSALLogManager|logMSALMessage:containsPii:logLevel:[604572]|78<Info>: TID=599377 MSAL 1.1.13 iOS 14.0 [2021-01-29 05:45:23] Id token was set to nil in token response!
 29/01/2021 11:15:23:465|FLMSALLogManager|logMSALMessage:containsPii:logLevel:[604572]|82<Error>: TID=599377 MSAL 1.1.13 iOS 14.0 [2021-01-29 05:45:23 - D9BEB0B9-0647-448E-8099-0C2A3DA5A596] Broker failed with error domain MSALErrorDomain, error code -42600, oauth error (null), sub error (null), description Failed to get session key from JWE.
 29/01/2021 11:15:23:465|FLMSALLogManager|logMSALMessage:containsPii:logLevel:[604572]|78<Info>: TID=599377 MSAL 1.1.13 iOS 14.0 [2021-01-29 05:45:23 - D9BEB0B9-0647-448E-8099-0C2A3DA5A596] [MSAL] Broker flow finished.
 29/01/2021 11:15:23:466|FLMSALLogManager|logMSALMessage:containsPii:logLevel:[604572]|82<Error>: TID=599377 MSAL 1.1.13 iOS 14.0 [2021-01-29 05:45:23 - D9BEB0B9-0647-448E-8099-0C2A3DA5A596] [MSAL] acquireToken returning with error: (MSALErrorDomain, -50000) Failed to get session key from JWE.`

-----
Note 

After cleaning/removing accounts in Authenticator(Registration not removed), Tried the fetch the Device ID again using claim, it was successful. We have started seeing this issue in the last few days but not in the past.
The device ID is critical for us and is used in compliance updates.
Let us know if any more details have to be given.

**Comment by rahulcode** [comment]
Hi @antrix1989 
Any updates on this issue ?

**Comment by antrix1989** [comment]
Thanks, @rahulcode. I will let you know once I finish the investigation.

**Comment by rahulcode** [comment]
Hi @antrix1989 / @oldalton 

New Log shared over the Email along with Charles session after reproducing the issue.
Suresh Will be sharing Details over mail.

**Comment by rahulcode** [comment]
Attaching here too : 
[JWE_Error_Details_Charles_Logs_Latest_5thFeb.zip](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/5931847/JWE_Error_Details_Charles_Logs_Latest_5thFeb.zip)

**Comment by rahulcode** [comment]
Any updates on this issue ( Failed to get session key from JWE.)

**Comment by oldalton** [comment]
@rahulcode - we're hoping that the upcoming Authenticator release will fix the issue (should be available in the App Store in 1-2 weeks from now, min version 6.5.33).

**Comment by emilmarkose** [comment]
Getting the same error message "**Failed to get session key from JWE.**" 

iPhone SE 2020 (14.4)
Authenticator version 6.5.38 (latest available in the AppStore)
MSAL SDK version 1.1.15

Can someone provide any insights?

**Comment by oldalton** [comment]
@emilmarkose, can you share an incident ID for the Authenticator app? Thanks.

**Comment by emilmarkose** [comment]
@oldalton This issue happened for one of our end user. He is unable to login to our app because of this issue. The user haven't raised an incident for this.

Thanks

**Comment by hieunguyenmsft** [comment]
@emilmarkose: the customer can follow this link to easily create an IncidentID: [link](https://github.com/AzureAD/azure-activedirectory-library-for-objc/wiki/Instructions-on-Collecting-Microsoft-Authenticator-Logs). After that we can further investigate.

**Comment by emilmarkose** [comment]
Thanks @hieunguyenmsft. I will ask the customer to do this. For now we fixed the issue with the following configuration.

```
msalConfiguration.bypassRedirectURIValidation = true
```

This configuration will avoid broker (authenticator app) and goes to the browser for authentication.

@hieunguyenmsft or @oldalton Does this configuration have any indirect implications?

**Comment by kaisong1990** [comment]
No active conversations for a while and closing the issue.
