### ISSUE TITLE
Get Account returning NULL 

### ISSUE THREAD

**Issue by kayvanhaverbeck** [AzureAD/microsoft-authentication-library-for-objc#1222]
I am trying to write a method that will return the current account logged in with MSAL. 

After successfully logging in, and then calling my GET Account Method - getCurrentAccountWithParameters: keeps returning null for both account and previous account. 

I have my keystore set up - not sure what else could be wrong? 

`RCT_REMAP_METHOD(getAccount,
                acct_resolver:(RCTPromiseResolveBlock)acct_resolve
                acct_rejecter:(RCTPromiseRejectBlock)acct_reject) {
    @try {
        RCTLog(@"TRYING TO GET THE CURRENT USER");

        MSALParameters *parameters = [MSALParameters new];
        parameters.completionBlockQueue = dispatch_get_main_queue();
                
        [application getCurrentAccountWithParameters:parameters
                                     completionBlock:^(MSALAccount * _Nullable account, MSALAccount * _Nullable previousAccount, NSError * _Nullable error)
        {
            RCTLog(@"%@", [[NSString alloc] initWithFormat:@"%@", account]);
            RCTLog(@"%@", [[NSString alloc] initWithFormat:@"%@", previousAccount]);
            acct_resolve(account);

        }];
    } @catch(NSError *error) {
        //reject([[NSString alloc] initWithFormat:@"%d", (int)error.code], error.description, error);
      RCTLog([[NSString alloc] initWithFormat:@"%d", (int)error.code], error.description, error);
        acct_reject([[NSString alloc] initWithFormat:@"%d", (int)error.code], error.description, error);
    }
}`

**Comment by NerevarineRule** [comment]
Hi @kayvanhaverbeck 

Thanks for your inquiry.

I've noticed two things: 
1) you need to pass in MSALAccountEnumerationParameters, rather than MSALParameters, into getCurrentAccountWithParameters API. 
Please see below code snippet for an example.

2) You are trying to directly print account and prev account, but they are of MSALAccount object type, which is a wrapper class containing information about the signed in MSAL account, so you will end up reading out pointer values. Instead, please refer to below code snippet also on how to print out information such as account name and identifier for a given MSAL account.

Thank you.

```
    MSALAccountEnumerationParameters *parameters = [MSALAccountEnumerationParameters new];
    parameters.returnOnlySignedInAccounts = YES;
    
    if (@available(iOS 13.0, *))
    {
        [application getCurrentAccountWithParameters:parameters
                                     completionBlock:^(MSALAccount * _Nullable account, __unused MSALAccount * _Nullable previousAccount, __unused NSError * _Nullable error)
        {
            self.currentAccount = account;
            
            NSLog(@"%@", [[NSString alloc] initWithFormat:@"current account name: %@ and identifier: %@", account.username, account.identifier]);
            NSLog(@"%@", [[NSString alloc] initWithFormat:@"previous account name: %@ and identifier: %@", previousAccount.username, previousAccount.identifier]);
            
            dispatch_async(dispatch_get_main_queue(), ^{
                [super refresh];
            });
        }];
    }
```
