### ISSUE TITLE
Multiple account

### ISSUE THREAD

**Issue by saj11** [AzureAD/microsoft-authentication-library-for-objc#1232]
Hi!

I see inside Android docs that MSAL support the use case of doing several logins from different accounts on the same app. So I search about iOS but I didn't find anything. Is it possible on iOS, too?

**Comment by oldalton** [comment]
Yes, MSAL supports multiple accounts. Here is a basic sample: https://github.com/AzureAD/microsoft-authentication-library-for-objc#acquiring-your-first-token-interactively

To summarize, you need to keep track of the account identifier and pass the correct account identifier to the acquireTokenSilent API. You can enumerate accounts that MSAL knows about by using the [allAccounts: API](https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALPublicClientApplication.html#/c:objc(cs)MSALPublicClientApplication(im)allAccounts:)

**Comment by saj11** [comment]
@oldalton Thanks for answer me the question. But what I see is that I can make an acquire token interactively and then use the allAccount to see which account had already logged. 

What I need to know is how can I login with more one user through acquire token interactively. I try to this flow but when I try it the second time with another account I get login but also get an error that I can't login again.
