### ISSUE TITLE
MSALErrorDescriptionKey=AADSTS9001011:+Device+policy+contains+unsupported+required+device+state:+domain_joined.

### ISSUE THREAD

**Issue by songwut** [AzureAD/microsoft-authentication-library-for-objc#1235]
Could not acquire token: Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=AADSTS9001011:+Device+policy+contains+unsupported+required+device+state:+domain_joined.
Trace+ID:+721e966f-bd4a-4254-b6f4-5ba321b40900
Correlation+ID:+5a9fb17c-6384-4398-b7c3-2a7ae2a227a9
Timestamp:+2021-02-09+11:17:03Z, MSALOAuthErrorKey=invalid_request, MSALCorrelationIDKey=5A9FB17C-6384-4398-B7C3-2A7AE2A227A9, MSALInternalErrorCodeKey=-42002}

How to fix this.

**Comment by oldalton** [comment]
This means that there's a conditional access policy to require device to be domain joined. This policy is unsupported on iOS. See more here: https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/require-managed-devices
