### ISSUE TITLE
Multiple Account - More than one interactively browser.

### ISSUE THREAD

**Issue by saj11** [AzureAD/microsoft-authentication-library-for-objc#1238]
@oldalton Thanks for answer me the question. But what I see is that I can make an acquire token interactively and then use the allAccount to see which account had already logged. 

What I need to know is how can I login with more one user through acquire token interactively. I try to this flow but when I try it the second time with another account I get login but also get an error that I can't login again.

Also, sorry for ask but I don't know why it gets close.

_Originally posted by @saj11 in https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1232#issuecomment-776756735_

**Comment by oldalton** [comment]
`I try to this flow but when I try it the second time with another account I get login but also get an error that I can't login again.`

Could you please share the error?

**Comment by saj11** [comment]
Sure @oldalton! The error is: 

MSALErrorDomain Code=-50000
MSALErrorDescriptionKey=Only one interactive session is allowed at a time.
MSALInternalErrorCodeKey=-42402

The flow that I have on the swift app is:
1. Do the login through browser while using acquireTokenInteractively
2. For security reasons, to be able to modify some settings an admin account is needed and for some cases the first user used before is not the same as the second one so again I do the login through browser while using acquireTokenInteractively
3. Here I get the token as response, but some seconds later I got the error that I write above and show me the azure verification view again to make the login when I already make the login.

**Comment by oldalton** [comment]
You might be calling acquireToken API multiple times. You need to wait for the first call to finish before starting second one. 

If you make sure that this is not the case, you can try calling [cancelCurrentWebAuthSession API](https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALPublicClientApplication.html#/c:objc(cs)MSALPublicClientApplication(cm)cancelCurrentWebAuthSession) before calling acquireToken API.

**Comment by saj11** [comment]
Thanks @oldalton! But neither the first case nor the second one works as expected. 

As you suggest, I call the cancelCurrentWebAuthSession before calling acquireToken, but I get the same result. After logged the second time, the azure permission alert show up. Also, I get more information when this occur.

The additional information I get is:
- Attempting to load the view of a view controller while it is deallocating is not allowed and may result in undefined behavior (<SFAuthenticationViewController: 0x7f81470b7800>)
- SFAuthenticationSession has already been cancelled but we still got a privacy alert callback from view service.
- Background Task 6 ("Interactive login"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.

**Comment by oldalton** [comment]
It seems something on your application side. Please make sure that the controller you're passing to MSAL is not getting deallocated.

**Comment by saj11** [comment]
Yeah! Thanks for all your help @oldalton. I will follow it with my team

**Comment by oldalton** [comment]
Closing the issue. Feel free to re-open if needed.
