### ISSUE TITLE
Implement MSAL for New SWIFT iOS App protocol

### ISSUE THREAD

**Issue by cappern** [AzureAD/microsoft-authentication-library-for-objc#1239]
I have searched high and low for any pointers/examples of how I can implement MSAL with the new SwiftUI App protocol ( https://developer.apple.com/documentation/swiftui/app) but I can't seem to find any useful information anywhere.

I am pretty new to swift/ iOS programming.. Anyone?

**Comment by kaisong1990** [comment]
Hi @cappern 

Thanks for your question, MSAL doesn't support SwiftUI without UIKit, please refer to the following issues for more details:

https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1152
https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/983

**Comment by kaisong1990** [comment]
Closing this issue for now and feel free to reopen if there were other questions :)
