### ISSUE TITLE
Documentation for MSALGlobalConfig.brokerAvailability // crashes

### ISSUE THREAD

**Issue by noxo** [AzureAD/microsoft-authentication-library-for-objc#1244]
I've noticed some random crashes on devices having Microsoft Authenticator installed, and having Single Sign-On MDM payload settings provisioned. In this case MSAL lib will use Apples Authentication Services framework.

App will crash without stacktrace right after calling _MsalApplication.acquireToken_, there seems to be "XPC connection interrupted" in console each time crash occures.

As an workaround, I've noticed, MSAL can be forced to use build-in implementation instead of broker/Apples Authentication Services, using

> MSALGlobalConfig.brokerAvailability = .none

Would be nice that some documentation would exist on this configuration flag.

**Comment by oldalton** [comment]
Hi. Could you please share a stack trace for the crash you're seeing?
We don't recommend disabling brokered authentication, because broker is required to support AAD conditional access policies.

**Comment by noxo** [comment]
Unfortunately the is no stack trace produced for crashes, and can't get my hands on on Device Logs on those crashing devices :)

Only evidence is the "XPC connection interrupted" right after doing silent auth using MsalApplication.acquireToken(), which sort of hints something triggered by MSAL & XPC (Apples Authentication Services uses XPC?).

Started gettings reports once MS Authenticator v6.5.15 was introduced in setup.
