### ISSUE TITLE
Nativescript Wrapper for MSAL  (application did not receive response from broker)

### ISSUE THREAD

**Issue by azriel46d** [AzureAD/microsoft-authentication-library-for-objc#1249]
Hi I am working on a wrapper for the iOS (and android) SDK for the MSAL. 
Now when Im working using the simulator, I have no issue. The app opens up, login is performed via the webview and the session works well. 
However, when using a device which has the **Authenticator** app, I am having trouble. 
The app navigates correctly to the Authenticator app, however on approval and returning back to the application there is no login occurring. 

Logwise this is what I'm seeing:
```
3 >> TID=1135516 MSAL 1.1.7 iOS 14.4 [2021-02-23 16:17:34] Init MSIDKeychainTokenCache with keychainGroup: Masked(not-null) false
3 >> TID=1135516 MSAL 1.1.7 iOS 14.4 [2021-02-23 16:17:34] Requiring default broker type due to app being built with iOS 13 SDK false
3 >> TID=1135516 MSAL 1.1.7 iOS 14.4 [2021-02-23 16:17:34 - 62C82B0D-5E47-41CE-87FA-42150158D510] [MSAL] -[MSALPublicClientApplication acquireTokenWithParameters:(
"api://15f1*************/access_as_user"
)
extraScopesToConsent:(null)
account:Masked(null)
loginHint:Masked(null)
promptType:MSALPromptTypePromptIfNecessary
extraQueryParameters:(null)
authority:(null)
webviewType:MSALWebviewTypeDefault
customWebview:No
correlationId:(null)
capabilities:(null)
claimsRequest:(null)] false
3 >> TID=1135516 MSAL 1.1.7 iOS 14.4 [2021-02-23 16:17:34 - 62C82B0D-5E47-41CE-87FA-42150158D510] [MSAL] Checking broker install state for version V2-broker-nonce false
3 >> TID=1135516 MSAL 1.1.7 iOS 14.4 [2021-02-23 16:17:34 - 62C82B0D-5E47-41CE-87FA-42150158D510] [MSAL] Broker version V2-broker-nonce found installed on device false
3 >> TID=1135516 MSAL 1.1.7 iOS 14.4 [2021-02-23 16:17:34 - 62C82B0D-5E47-41CE-87FA-42150158D510] [MSAL] Beginning broker flow. false
 3 >> TID=1135516 MSAL 1.1.7 iOS 14.4 [2021-02-23 16:17:34 - 62C82B0D-5E47-41CE-87FA-42150158D510] [MSAL] Resolving authority: Masked(not-null), upn: Masked(null) false
 3 >> TID=1135516 MSAL 1.1.7 iOS 14.4 [2021-02-23 16:17:34 - 62C82B0D-5E47-41CE-87FA-42150158D510] [MSAL] Resolved authority, validated: YES, error: 0 false
 3 >> TID=1135516 MSAL 1.1.7 iOS 14.4 [2021-02-23 16:17:34 - 62C82B0D-5E47-41CE-87FA-42150158D510] [MSAL] Invoking broker for authentication, correlationId 62C82B0D-5E47-41CE-87FA-42150158D510 false
error {
"message": "MSALErrorDomain",
"errorCode": -50000
}
 1 >> TID=1135516 MSAL 1.1.7 iOS 14.4 [2021-02-23 16:17:39] Creating Error with description: application did not receive response from broker. false
 3 >> TID=1135516 MSAL 1.1.7 iOS 14.4 [2021-02-23 16:17:39 - 62C82B0D-5E47-41CE-87FA-42150158D510] [MSAL] Broker flow finished. false
 1 >> TID=1135516 MSAL 1.1.7 iOS 14.4 [2021-02-23 16:17:39 - 62C82B0D-5E47-41CE-87FA-42150158D510] [MSAL] acquireToken returning with error: (MSALErrorDomain, -50000) Masked(not-null) false
```

My hunch is that this is linked to the UISceneDelegate.
I am not using UISceneDelegates (Nativescript does not provide it as far as aware) and so far every attempt to create/link a UISceneDelegate has failed (My main issue linked with this is linking the UISceneDelegate.)

Any assistance would be greatly appreciated.

**Comment by kaisong1990** [comment]
Hi @azriel46d 

Thanks for your logs, looks like your application did not handle the response from broker correctly. Could you check the following link and add the handler in appDelegate or SceneDelegate whichever you have when broker navigate back to your application?

https://github.com/AzureAD/microsoft-authentication-library-for-objc#ios-only-steps

```3. To handle a callback, add the following to appDelegate:```


Let us know if you have other questions

**Comment by azriel46d** [comment]
Hi @kaisong1990 , yep I have the appDelegate setup. And in fact if the Authenticator app is not installed , I can see the delegate part being accessed properly. 
However utilising when the Authenticator App is installed and login is performed with it , the Authenticator app loads, but on return the appDelegate seems to be skipped for some reason.

**Comment by kaisong1990** [comment]
@azriel46d Sounds like there is an Apple API that is not triggered when moving your app to foreground. Could you check if the url scheme is registered correctly in the info.plist?

[How to add URL Scheme](https://github.com/AzureAD/microsoft-authentication-library-for-objc#ios-only-steps)

and follow Step 1

**Comment by azriel46d** [comment]
As far as i can see these are also setup correctly
```
<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>msauth.com.x.y</string> <---- com.x.y reflects bundleID
			</array>
		</dict>
	</array>
```

```
<key>LSApplicationQueriesSchemes</key>
<array>
  <string>msauthv2</string>
  <string>msauthv3</string>
</array>
```

**Comment by kaisong1990** [comment]
@azriel46d The setting looks good

For further steps:

1. Update to use latest MSAL (1.1.15)
2. Follow [Apple doc](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623112-application) to make sure the conditions were met before triggering this method
3. If above doesn't help, please file a ticket to Nativescript team for more helps as this is a application delegate which is not in control of MSAL lib

**Comment by brandwe** [comment]
It'd be great if our SDK can work with , so let us know if anything needed to be changed so we can help others in the future @azriel46d

**Comment by azriel46d** [comment]
Update
- Updated the podfile to 1.1.15
-  All looks fine with regards to point two as it follows more established plugins:
 Delegation class creation
`https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/src/firebase.ios.ts#L482`
and function for the opening the URL
`https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/src/firebase.ios.ts#L309`

So far no luck :(

**Comment by kaisong1990** [comment]
Is there any sample project we can take a look?

**Comment by azriel46d** [comment]
@kaisong1990 We've published to git the source code of the plugin [here](https://github.com/medirectbank/ns-workspace) . It utilises the nativescript plugin workspace. What you have there are three parts:
1. A `demo` app folder with two demo apps (so far the Vanilla JS version is done, not the angular one)
2. The `packages` folder . Here you will find the core logic in exposing the native MSAL SDKs . 
3. The `tools` folder in which you have 
     -  under `assets/App_Resources` the `info.plist` which the demo app will use and under `demo/msal` 
     -  under `demo/msal/index` where the plugin can be initialised. 

The main readme should have how to get the workspace up and running. As well as this blog post. 
https://nativescript.org/blog/announcing-plugin-workspaces/

**Comment by kaisong1990** [comment]
Thanks for sharing, we will take a look

**Comment by kaisong1990** [comment]
We have informed our JS team to look and keep you posted once get anything back

**Comment by kaisong1990** [comment]
@azriel46d Sorry for the late replying, our JS team mentioned the same case that the app delegate could not be set up correctly. Unfortunately they don't use Nativescript and cannot provide more details.

Do you get any update from Nativescript? Looks like the setup is correct regarding MSAL, and will need expertise from Nativescript for more investigations

**Comment by azriel46d** [comment]
Unfortunately I did not hear back from anyone from the Nativescript (tried even through the official Discord channels) . For now I will close the ticket and will try to dig deeper on it on why its not able to recover back correctly. The plugin is following the same that other plugins hook up with the app delegate (see this [example](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/05be2bbf3f0883f46c1c84aed6b4d68bb84002f7/src/firebase.ios.ts#L496) . 
If I dig up anything new I'll let you know
