### ISSUE TITLE
Callback for external domain requests

### ISSUE THREAD

**Issue by ekscrypto** [AzureAD/microsoft-authentication-library-for-objc#1257]
Our B2C authentication page has a "Help" button which user can click on to be redirected to our support page, hosted on a different domain, in case they are unable to sign-in or register.  I believe that due to the navigationDelegate rules configured by the MSAL library we are unable to navigate outside of the B2C authentication domain, causing user interactions with the help button to be ignored.

Is it possible to have a callback/delegate for requests made to outside domains ?  

This would allow us to dismiss the authentication view and redirect the user to an external browser session to our Help site.

**Comment by mipetriu** [comment]
What version of MSAL are you using? As far as I know, the newest version of MSAL should be able to handle links that open in an external tab. Also, is an HTTP or HTTPS link? Only HTTPS links should work.

**Comment by ekscrypto** [comment]
We seem to be using version 1.1.15, the link is https.  FYI I'm using a customWebView to present MSAL.  Is there a delegate or callback that has to be setup?

**Comment by ekscrypto** [comment]
FYI, while we are using a custom WKWebView, we are not overriding the navigationDelegate and webviewConfiguration set by MSAL.

**Comment by mipetriu** [comment]
@ekscrypto I double-checked the code, and HTTPS links should work. Maybe you could debug the situation by placing a breakpoint in MSIDOAuth2EmbeddedWebviewController.m, in the `decidePolicyForNavigationAction:` method at line 358 to make sure that delegate gets triggered?

If it's triggered, you should be able to see why the link is not opening.

**Comment by ekscrypto** [comment]
I put a breakpoint as well as a NSLog entry in that function and neither got triggered -- is it at all possible that when using a customWebView that this code is not the one deciding on the policy?

```
            let webViewParameters = MSALWebviewParameters(authPresentationViewController: presentationController)
            webViewParameters.presentationStyle = UIModalPresentationStyle.fullScreen
            webViewParameters.webviewType = MSALWebviewType.wkWebView
            webViewParameters.customWebview = webview // <-- CUSTOM WEB VIEW SPECIFIED HERE
            let b2cInfo = Environment.active.b2c
            let interactiveParameters = MSALInteractiveTokenParameters(scopes: b2cInfo.scopes, webviewParameters: webViewParameters)
            interactiveParameters.promptType = .login
            interactiveParameters.loginHint = loginHint
            interactiveParameters.authority = b2cAuthority
            b2cApp.acquireToken(with: interactiveParameters) { (result, errorOrNil) in
            ...
```

**Comment by mipetriu** [comment]
@ekscrypto, we took another look at the code, and it seems that as long as the `loadView` function is being called, we should be setting the navigation delegate, no matter if it is a custom webview or not. Could you try to place a breakpoint in that method to make sure the navigation delegation is being set?

Another test to see what's happening could be to use our sample app with and without your custom webview configuration to see if the delegate is properly set in those cases? The sample app is here: [sample](https://github.com/Azure-Samples/ms-identity-mobile-apple-swift-objc)

**Comment by ekscrypto** [comment]
I will attempt to take a deeper look at this again this week.  In my last attempts none of my breakpoints were getting hit in the MSAL framework even the obvious ones that should have.  Thanks for double checking; I will let you know once I've had a chance to give this a go again

**Comment by ekscrypto** [comment]
Sorry busy with other priorities at the moment, still planning to continue solving this.
