### ISSUE TITLE
MSAL fails to retrieve token silently

### ISSUE THREAD

**Issue by maksirol** [AzureAD/microsoft-authentication-library-for-objc#1260]
Hello,

From time to time i keep notice that MSAL fails to retrieve token silently. I couldn't reproduce it locally, but i have those logs.

`TID=5346383 MSAL 1.1.12 iOS 14.4 [2021-03-03 21:34:45 - 462F998E-17A3-4C60-9B62-1E2082E28AEB] Processing an AAD error with error code -51412, error invalid_grant, suberror (null), description Masked`

`TID=5346383 MSAL 1.1.12 iOS 14.4 [2021-03-03 21:34:45 - 462F998E-17A3-4C60-9B62-1E2082E28AEB] Creating Error with description: User interaction is required`

`TID=5346383 MSAL 1.1.12 iOS 14.4 [2021-03-03 21:34:45 - 462F998E-17A3-4C60-9B62-1E2082E28AEB] [MSAL] acquireTokenSilent returning with error: (MSALErrorDomain, -50002) Masked(not-null)`

Any suggestions what might be wrong? Or Where should i look to find more info?

**Comment by kaisong1990** [comment]
@maksirol Thanks for your question. We are not able to find the logs based on the timestamp and correlationId provided above.

invalid_grant error is very generic and could be caused by different issues. 

Could you provide another set of correlationIds and more context/logs so that we can have a better understanding of the behavior?

**Comment by maksirol** [comment]
For refresh token i'm using this function 
`- (void)acquireTokenSilentWithParameters:(nonnull MSALSilentTokenParameters *)parameters
                         completionBlock:(nonnull MSALCompletionBlock)completionBlock;`

 From MSALPublicClientApplication

It happens just after app launch. 
I receive session start event at 19:25:14, and then app is trying to refresh token immediately. 

And here are another logs
`TID=7981694 MSAL 1.1.12 iOS 14.4 [2021-03-04 19:25:15 - 13403D4F-BB9D-4E2B-85E1-55F77B2FC927] Processing an AAD error with error code -51412, error invalid_grant, suberror (null), description Masked`

`TID=7981694 MSAL 1.1.12 iOS 14.4 [2021-03-04 19:25:15 - 13403D4F-BB9D-4E2B-85E1-55F77B2FC927] Creating Error with description: User interaction is required`

`TID=7981694 MSAL 1.1.12 iOS 14.4 [2021-03-04 19:25:15 - 13403D4F-BB9D-4E2B-85E1-55F77B2FC927] [MSAL] acquireTokenSilent returning with error: (MSALErrorDomain, -50002) Masked(not-null)`

After that i call 
`- (void)acquireTokenWithParameters:(nonnull MSALInteractiveTokenParameters *)parameters
                   completionBlock:(nonnull MSALCompletionBlock)completionBlock;`
                   
And receive another errors:
`TID=7981646 MSAL 1.1.12 iOS 14.4 [2021-03-04 19:25:16 - A272DB5A-0275-4DDC-AE27-39896769C235] Creating Error with description: Only one interactive session is allowed at a time.`

`TID=7981646 MSAL 1.1.12 iOS 14.4 [2021-03-04 19:25:16 - A272DB5A-0275-4DDC-AE27-39896769C235] [MSAL] acquireToken returning with error: (MSALErrorDomain, -50000) Masked(not-null)`

`TID=7981646 MSAL 1.1.12 iOS 14.4 [2021-03-04 19:25:22] Creating Error with description: parentViewController has no window! Provide a valid controller with view and window.`

But those are probably caused by bug in my implementation and are not related to refresh token errors.

Unfortunately i can't find any other info that could be helpfull to undestand the issue, i will try to reproduce it locally, but so far it happened only in production environment.

**Comment by kaisong1990** [comment]
@maksirol Also tried with ```13403D4F-BB9D-4E2B-85E1-55F77B2FC927```, but nothing pop up.

```Creating Error with description: Only one interactive session is allowed at a time.```

User didn't cancel the current authentication session correctly and try to start a new one, which is not allowed in our lib. Please make sure the logic is correct there

```Creating Error with description: parentViewController has no window! Provide a valid controller with view and window.```

The view controller is not passed in correctly, normally happens when the app is not in full foreground yet. Here is piece of code that you can try and verify/resolve the issue

`override func viewDidLoad() {
        super.viewDidLoad()
        
        let notificationCenter = NotificationCenter.default
        notificationCenter.addObserver(self, selector: #selector(appMovedToForeground), name: UIApplication.didBecomeActiveNotification, object: nil)        
        do {
            try self.initMSAL()
        } catch let error {
            self.updateLogging(text: "Unable to create Application Context \(error)")
        }
        
        self.loadCurrentAccount()
        self.platformViewDidLoadSetup()
    }
    
    @objc func appMovedToForeground() {
        acquireTokenInteractively()
        NotificationCenter.default.removeObserver(self)
    }`

**Comment by maksirol** [comment]
i've managed to solve  `Only one interactive session is allowed at a time.` and  `parentViewController has no window!` errors, thank you :)

But `Processing an AAD error with error code -51412, error invalid_grant` remains a mystery... :(

**Comment by kaisong1990** [comment]
@maksirol what type of the account it is? Is it common AAD users?

**Comment by maksirol** [comment]
We're using ADB2C accounts.

**Comment by kaisong1990** [comment]
@maksirol We have forwarded the correlationId to B2C teams and keep you posted if they found anything

**Comment by maksirol** [comment]
Hello, any news on this issue?

**Comment by kaisong1990** [comment]
> Hello, any news on this issue?

Sorry for the late replying, let me confirm with the team.

Meanwhile could you provide some new correlationIds and MSAL version you are running?

**Comment by maksirol** [comment]
Sorry for late response.
Here are some other logs:

One case:
`TID=9432052 MSAL 1.1.15 iOS 14.4.2 [2021-04-23 11:08:37 - 748EB11B-80FE-4532-BA08-7BC06D04599F] Processing an AAD error with error code -51412, error invalid_grant, suberror (null), description Mask`

`TID=9432052 MSAL 1.1.15 iOS 14.4.2 [2021-04-23 11:08:37 - 748EB11B-80FE-4532-BA08-7BC06D04599F] Creating Error with description: User interaction is required`

`TID=9432052 MSAL 1.1.15 iOS 14.4.2 [2021-04-23 11:08:37 - 748EB11B-80FE-4532-BA08-7BC06D04599F] [MSAL] acquireTokenSilent returning with error: (MSALErrorDomain, -50002) Masked(not-null)`

Second case:
`TID=10692293 MSAL 1.1.15 iOS 14.4.2 [2021-04-23 09:33:06 - FE872E14-F308-48F7-9B2F-26EA7BBCF8AD] Processing an AAD error with error code -51412, error invalid_grant, suberror (null), description Masked(not-null)`

`TID=10692293 MSAL 1.1.15 iOS 14.4.2 [2021-04-23 09:33:06 - FE872E14-F308-48F7-9B2F-26EA7BBCF8AD] Creating Error with description: User interaction is required`

`TID=10692293 MSAL 1.1.15 iOS 14.4.2 [2021-04-23 09:33:06 - FE872E14-F308-48F7-9B2F-26EA7BBCF8AD] [MSAL] acquireTokenSilent returning with error: (MSALErrorDomain, -50002) Masked(not-null)`

**Comment by kaisong1990** [comment]
@maksirol Thanks, shared the logs to B2C team
