### ISSUE TITLE
error "cannot find 'MSALPublicClientApplication' in scope"

### ISSUE THREAD

**Issue by thomas-topway-it** [AzureAD/microsoft-authentication-library-for-objc#1263]
Hello, when building on ios (11) in a flutter app I get the following error

"cannot find 'MSALPublicClientApplication' in scope"

do you have any idea how to solve it ?
Thanks
(Thomas)

**Comment by thomas-topway-it** [comment]
*** the solution is to import MSAL on top of the file, it was just missing from the documentation of the flutter library

```
import MSAL
```

**Comment by kaisong1990** [comment]
@thomas-topway-it Thanks for your question, this seems to be an issue where the MSAL lib is not imported into the project correctly by using Fluter.

Please refer to [this article](https://flutter.dev/docs/get-started/flutter-for/ios-devs)about Fluter for iOS developers

and create an issue to Fluter team [here](https://github.com/flutter/flutter) if the above doesn't help

Feel free to let us know if there is any specific MSAL question we can help with :)

**Comment by thomas-topway-it** [comment]
Hello Dave, yes, I wanted to close today
the thread with this note as well.  (I did it now)
Thanks for your comment. I have another issue,
error
"The operation couldn't be completed. (MSALErrorDomain error ~50000.)"
"currentAccount is null" (on signing-in)

I will open another thread, I'm still not sure from what is caused
on android it works fine
(Thomas)


 
 

Sent: Friday, March 05, 2021 at 9:50 PM

**Comment by thomas-topway-it** [comment]
@kaisong1990 
thanks for the comment, actually the flutter library at this address
https://pub.dev/packages/msal_mobile
has at least two missing details.

Now I'm experiencing the error 
```The operation couldn't be completed. (MSALErrorDomain error ~50000.)```
"currentAccount is null" (on signing-in)

while on android it works fine
