### ISSUE TITLE
Automatically remove trailing spaces on iOS provided email addresses

### ISSUE THREAD

**Issue by ekscrypto** [AzureAD/microsoft-authentication-library-for-objc#1264]
Using MSAL to interactively authenticate, when the user focuses the email input field iOS automatically suggests email addresses the user has configured on his profile, tapping one of those emails inserts it into the input field with a trailing space.

If the user hit "Next" without removing this space, authentication will fail.

MSAL should be updated to automatically strip the trailing space in the email address.

**Comment by kaisong1990** [comment]
@ekscrypto Thanks for your question, will verify this and report to our UX team. If nothing we can do from outside, will inform Apple for the issue

**Comment by kaisong1990** [comment]
@ekscrypto Could you also provide which OS version and MSALWebviewType you were using?

**Comment by ekscrypto** [comment]
iPadOS 14.4, MSALWebviewType.wkWebView with a customWebview configured.

In some previous life we handled it either in code in the app or in JavaScript with a onSubmit cleanup

**Comment by kaisong1990** [comment]
@ekscrypto We have chatted with the UX team and they do provided the logic to remove the trailing space, would you able to provide any video and/or network trace to make sure the error is caused by the trailing space?

**Comment by ekscrypto** [comment]
Is there a private address at which a video recording can be provided?  I would rather not share it publicly due to branding.

**Comment by kaisong1990** [comment]
@ekscrypto Sure my email address is kasong@microsoft.com, feel free to drop an email

**Comment by ekscrypto** [comment]
Not sure what happened or if our B2C User identity team changed scripts on their side, but the issue is no longer reproducible. Closing.
