### ISSUE TITLE
Error - unable to log the user out of MSAL, credentials persisted after logout call

### ISSUE THREAD

**Issue by rennarda** [AzureAD/microsoft-authentication-library-for-objc#1270]
I am experiencing an issue where I am not able to sign the user out properly from MSAL. After calling the sign-out api, the next time the app attempts to authenticate it is still picking up cached credentials, and signing straight back into that account. 

The only UI I see is the prompt screen "Are you trying to sign into [app name]?" with the user's account username already populated. 

Here's the code that I'm using. I'm calling the `signout(with:signoutParameters)` API, but I'm even also calling the `remove()` API just to try and force everything to get cleared.

```swift
signout(with: account, signoutParameters: signoutParams) { (success, error) in
    if let error = error {
        log?.error(error.localizedDescription)
    }
    do {
        try self.remove(account)
    } catch {
        log?.error("[MSAL] Unable to remove the account when logging out: \(error.localizedDescription)")
    }
}
```
I'm grabbing the user account from the `allAccounts` API and it looks correct.

I am not hitting any errors, so my assumption is that these calls are working correctly, and yet it still appears the user credentials are persisted.

Please point out what I'm doing wrong here.

**Comment by rennarda** [comment]
If I add `signoutParams.signoutFromBrowser = true` to the signout params, then MSAL prompts to open a new modal UX which allows me to pick an account to sign out of. 

This isn't the UX that we want though - it's very confusing to the user to be prompted to 'sign in' when they are really signing out, and this occurs before the user has interacted in any way after starting the logout process. 

What we're after is a one-shot logout process where we call al logout API and the user is fully logged out, and is required to re-authenticate. We don't want to have them have to perform additional actions to complete the logout process.

**Comment by kaisong1990** [comment]
Hi @rennarda Thanks for your question. Your sign out implementation looks good.

It could be some issues while trying to sign user back in.

Could you try to set the ```promptType``` to ```.login``` on ```MSALInteractiveTokenParameters```?

Also please try our sample apps for [iOS](https://github.com/Azure-Samples/ms-identity-mobile-apple-swift-objc) and [Mac](https://github.com/Azure-Samples/ms-identity-macOS-swift-objc), they should have provided the sign in and out code

**Comment by rennarda** [comment]
Thanks for the reply. 

It looks like this is a UX misunderstanding on my part. My assumption was that making the call to `signout` actually signed you out, but it seems as though that doesn't actually happen until after the user has selected an account to sign out of. I have made some UX tweaks to our logout flow and it's much more logical now.

Perhaps some clear documentation on this flow would be beneficial though.

**Comment by rennarda** [comment]
I have raised another issue #1271 following on from this, when the user cancels the signout process.
