### ISSUE TITLE
Signout always returns 'true' even if user cancels

### ISSUE THREAD

**Issue by rennarda** [AzureAD/microsoft-authentication-library-for-objc#1271]
Continuing my signout adventures from #1270, it seems as though when the user cancels the signout process the `signout(with:signoutParams)` callback always receives `true` and no error. 

My signout code looks like this:

```swift
signout(with: account, signoutParameters: signoutParams) { (success, error) in
    if let error = error {
        log?.error(error.localizedDescription)
    }
    do {
        try self.remove(account)
    } catch {
        log?.error("[MSAL] Unable to remove the account when logging out: \(error.localizedDescription)")
    }

    // Post signout cleanup goes here
}
```

When this method is called the user is first prompted with an alert that the app wants to open a website to authenticate, and then if they continue, a modal sheet showing the signout UI. **If the user selects `cancel` on the alert or on the modal, the callback returns `true` and no error**. 

There is no differentiation from when the user actually chooses to complete the signout.

I have post-signout cleanup that I perform in my app (not shown) - this should only occur when the user actually signs out. At the moment it seems I might have to dig into the `allAcounts` function to see if there is still a signed in account before I do this. 

It would be much better if the callback returned `false` if the user cancelled the signout, or a result enum with distinct cases for `cancelled`, `completed`, `errored`, etc.

**Comment by rennarda** [comment]
I don't seem to be able to obtain any information from the `MSALAccount` object that would tell me if the user is still signed in

**Comment by kaisong1990** [comment]
@rennarda We have confirmed this issue and currently it is expected. The cause is that server side does not return any callback/response whenever user signs out successfully or failed through browser. So client will not know when the logout happens or if it is finished or not. All we can rely on is when user click the cancel button. High level flow is as below:

`signout -> remove account in cache -> open browser -> click to signout in browser -> user click cancel to finish the session `

As you can see, removing account always happened first and call back will always return true even if user cancels the session intentionally in your case as we can't distinguish the logout state (cancelled by user before logging out or after logging out). 

Server side did have a plan to return us responses so that we can rely on in future

**Comment by rennarda** [comment]
How do you advise that we handle this situation? Is there an additional property we can query?

We have post signout clean up that we perform that we shouldn't do if the user has cancelled signout (removing some cached data, etc). We need to be able to tell if the user has actually completed the signout procedure or not.

Also as mentioned in #1270 it seems that until the user manually completes the signout then account credentials are still cached. I have verified this by logging all keychain items that are visible to the app, and there is a JSON object containing user ID and other data that is persisted after the `signout` call is made.

**Comment by kaisong1990** [comment]
1. When user click sign out, account is always removed from local cache, and if there is any error happened in this stage, the callback should catch
2. You can verify by calling ```allAccounts```, ```accountForIdentifier``` or other get account methods provided by ```MSALPublicClientApplication``` to confirm deletion
3. When we remove account locally, the access token, refresh token and id token were all removed so there is no credentials stays in the cache. If you set the ```wipeAccount``` to ```true``` on ```MSALSignoutParameters```, it will also remove the account from other apps that uses the same account. It is not recommended as SSO state will be gone 
4. The Json object you directly fetched which contains user ID from keychain is not credential related and we will have a task to clean that up when account is removed.
Let us know if you have further questions :)

**Comment by rennarda** [comment]
Thanks - that's not quite what I was asking. I need to know if the user has cancelled signout, because I need to not remove app caches and not pop them out to our app's home screen if they cancelled. 

I was wondering how I can detect the user has chosen to cancel the signout, if the actual signout method always returns `true`

**Comment by kaisong1990** [comment]
Understood, and unfortunately there is no way to tell at the moment without server makes the fix. Reason has been explained:

`As you can see, removing account always happened first and call back will always return true even if user cancels the session intentionally in your case as we can't distinguish the logout state (cancelled by user before logging out or after logging out).`

As a workaround, you can set ```signoutParams.signoutFromBrowser``` to ```false``` and MSAL will remove the account locally without showing the web session and set ```promptType``` to ```.login``` when user logs in interactively
