### ISSUE TITLE
Facebook login returns "The server has redirected to a non-https url" error

### ISSUE THREAD

**Issue by maksirol** [AzureAD/microsoft-authentication-library-for-objc#1272]
We noticed recently that MSAL login return error, but only for facebook provider.

`Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=The server has redirected to a non-https url., MSALInternalErrorCodeKey=-42602, MSALCorrelationIDKey=0446F02D-D0A2-4DEE-B297-29D63E3DA986}`

Everything works fine, if we will use 'MSALWebviewType.default' in configuration, but it returns error when we use 'MSALWebviewType.wkWebView'

Code snippet:
         
            let loginAuthority = try! MSALB2CAuthority(url: URL(string: "Authority url")!)
            let pcaConfig = MSALPublicClientApplicationConfig(clientId: "ClientId", redirectUri: nil, authority: loginAuthority)
            pcaConfig.knownAuthorities = [loginAuthority]

            let client = try! MSALPublicClientApplication(configuration: pcaConfig)
            
            let webviewParameters = MSALWebviewParameters(authPresentationViewController: viewController)
            
            webviewParameters.customWebview = customWebView
            //.wkWebView configuration causes an error, if we use .default everything works as expected
            webviewParameters.webviewType = .wkWebView
            
            let interactiveParameters = MSALInteractiveTokenParameters(scopes: scopes, webviewParameters: webviewParameters)
            
            client.acquireToken(with: interactiveParameters, completionBlock: { result, error in
                //Callback logic, always returns error for facebook provider
            }
            
Any ideas how we can fix it?

**Comment by jasoncoolmax** [comment]
Hi @maksirol , could you please collect the network trace to see what network request is causing that error? That will help us to further provide the suggestion here. Thank you!

**Comment by maksirol** [comment]
Hi @jasoncoolmax 
I've tracked down that embedded webView calls WKNavigationDelegate function 
`(void)webView:(WKWebView *)webView decidePolicyForNavigationAction:(WKNavigationAction *)navigationAction decisionHandler:(void (^)(WKNavigationActionPolicy))decisionHandler`
From MSIDOAuth2EmbeddedWebviewController and request url is 
`about:srcdoc`

I've tried to intercept this call and add additional rule for it. 

        func webView(_ webView: WKWebView, decidePolicyFor navigationAction: WKNavigationAction, decisionHandler: @escaping (WKNavigationActionPolicy) -> Void) {
            let requestURL = navigationAction.request.url?.absoluteString
        
            if requestURL?.contains("about:srcdoc") ?? false {
                decisionHandler(.allow)
                return
            }
        
            MSALNavigationDelegate?.webView?(webView, decidePolicyFor: navigationAction, decisionHandler: decisionHandler)
        }
        
And this seemed to solve the issue, but i'm not sure if this workaround won't introduce any side effects..

**Comment by hieunguyenmsft** [comment]
@maksirol I think your change should be fine, as my understanding `about:blank` and `about:srcdoc` both are special URLs for iFrame. 
https://chromium.googlesource.com/chromium/src.git/+/master/docs/special_case_urls.md
I will add update our lib to handle `about:srcdoc`

**Comment by ameyapat** [comment]
Fix for this is committed and will be rolled out in next release
