### ISSUE TITLE
Problem with Authenticator app when switching app to non-broker to broker flow - iOS

### ISSUE THREAD

**Issue by mayuri-03** [AzureAD/microsoft-authentication-library-for-objc#1276]
My App was initially published to App Store with non-brokered flow. In next app update I have updated app to brokered flow. In my plist file when my app was in non broker flow I have added URL types with msauth.{bundle ID 1}. Please note {bundle ID 1} is not same ID as per my app's bundle ID. 

In my app update, because we have added support for brokered flow I have updated URL Types with msauth.{APP's Bundle ID}. Even though my app's bundle Id and URL types mentioned bundle ID is same. MSAL is still not opening Authenticator app.
Still, app is supporting non-broker flow even though it's updated to brokered flow. 

Is this a cache issue?

Please suggest in case if we change URL in URL Types, do we have have to clear cache to support broker flow?

MSAL Swift version -  1.1.11

**Comment by kaisong1990** [comment]
@mayuri-03 Thanks for you question.

Could you share if there is any error in the log when trying to using Authenticator. 

[Here](https://github.com/AzureAD/microsoft-authentication-library-for-objc#ios-only-steps) is the guidance on how to set up in plist

Also I would recommend to take a look at our [iOS Sample app](ms-identity-mobile-apple-swift-objc/) and check if redirectUri/bundleId is set correctly in your project

**Comment by mayuri-03** [comment]
Thanks for the reply. I don't have any error log for this. The deep linking code for Authenticator app is as per given link. Somehow below pop up is not coming to open any third party application from MSAL sdk when we switch app from non-brokered flow to brokered. 
 "<Application name> wants to open "Authenticator""

**Comment by hieunguyenmsft** [comment]
@mayuri-03 It's hard to further investigate the issue without any information from log. Would you any chance collect the log and send to us?

**Comment by mayuri-03** [comment]
This issue was raised by one of our user on App Store app build. Information logs are not possible to fetch from their device. 

Thank you for your time for investing this issue.  You can close this issue, if we can't proceed without logs.

**Comment by hieunguyenmsft** [comment]
Sure, I will close it for now. If you have any additional information, feel free to open it and tag me.
Thank you.
