### ISSUE TITLE
Is SSO supported on iOS 13/14 with WkWebView or SFSafariViewController?

### ISSUE THREAD

**Issue by zzdravkin** [AzureAD/microsoft-authentication-library-for-objc#1279]
Hi,
App. open and successfully sign in with MSAL.
After opening wkwebview or instance of SFSafariViewController is asking again for sign-in.

I've tried with all webviewType, as .default, .authenticationSession and custom wkWebView.

**Comment by antrix1989** [comment]
Closing as a [duplicate](https://github.com/Azure-Samples/active-directory-b2c-ios-swift-native-msal/issues/50).

**Comment by zzdravkin** [comment]
Suddenly after login from webview with MSAL return a blank page, instead of redirecting to the right page as before? Any help will be appreciated
