### ISSUE TITLE
Getting Keychain -34018 error (failed to set item into keychain)

### ISSUE THREAD

**Issue by pzelenak** [AzureAD/microsoft-authentication-library-for-objc#1281]
Hi there,

We are trying to add MSAL support into our **macOS** application. According to the documentation (https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-v2-keychain-objc?tabs=objc) it should be possible
to configure MSAL not to use Keychain Sharing (see "Disable Keychain Sharing") by specifying
`config.cacheConfig.keychainSharingGroup = [[NSBundle mainBundle] bundleIdentifier];`
but it doesn't appear to work as advertised. We are seeing -34018 error with this setup.

Setup
- macOS App, XCode 10.3
- Keychain Sharing capability **Not** enabled
- Application is **Not** code signed (during development)

Any ideas? Also, what is the best way to work with MSAL while debugging/development when we don't want to configure XCode to codesign binaries (codesigning is OFF)?

Thanks

**Comment by antrix1989** [comment]
Hi @pzelenak, which MacOS version are you using?

**Comment by pzelenak** [comment]
Hi @antrix1989 
macOS Catalina (version 10.15.6)
Thanks

**Comment by antrix1989** [comment]
Thanks @pzelenak, please use [xcode 11](https://developer.apple.com/documentation/xcode-release-notes/xcode-11-release-notes) or 12. Keychain groups on MacOS aren't available in xcode 10.

**Comment by pzelenak** [comment]
Hey,

@antrix1989 - Sorry, I am not following. Would you be able to expand with additional info, please?
Keychain sharing is available in XCode 10. 

**Docs says the following:**
If you don't want to share SSO state between multiple apps, or use any keychain access group, disable keychain sharing by passing the application bundle ID as your keychainGroup...

I was understanding this as enabling Keychain sharing is not required to use the library, hence my original question.
No?

Thanks

**Comment by antrix1989** [comment]
@pzelenak The [API that enables keychain groups on MacOS](https://developer.apple.com/documentation/security/ksecusedataprotectionkeychain?language=objc) is available in  macOS SDK 10.15+. XCode 10 doesn't contain this SDK. It was added to the [Xcode 11](https://developer.apple.com/documentation/xcode-release-notes/xcode-11-release-notes).

**Comment by pzelenak** [comment]
@antrix1989 - As far as I can tell the API mentioned enables treating of macOS keychain items as iOS keychain items. The general support for Keychain access groups has existed for a long time and doesn't require XCode 11 or macOS SDK 10.15.

[In Setup info](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-differences-ios-macos)
we have
macOS
When you set up your project on macOS, ensure that your application is signed with a valid development or production certificate. MSAL still works in the unsigned mode, but it will behave differently with regards to cache persistence. The app should only be run unsigned for debugging purposes. If you distribute the app unsigned, it will:
On 10.14 and earlier, MSAL will prompt the user for a keychain password every time they restart the app.

I am asking about the following
**MSAL still works in the unsigned mode, but it will behave differently with regards to cache persistence. The app should only be run unsigned for debugging purposes.** 

Is it possible to do this (run the app integrated with MSAL unsigned while debugging without Keychain Access Group capability enabled/setup) and how? It seems without adding Keychain Access Group and signing the app, MSAL doesn't work. 

Thanks

**Comment by antrix1989** [comment]
Hi @pzelenak, yes, the app needs to be signed even for debugging purposes. When you provide a bundle identifier as a keychain sharing group, you don't completely "disable" cache, but rather configure MSAL to save tokens into your own keychain "island".  Also, we recommend you switching to the Xcode 12 since we only support the latest major Xcode version.
