### ISSUE TITLE
Crashes seen MSAL Library 

### ISSUE THREAD

**Issue by rahulcode** [AzureAD/microsoft-authentication-library-for-objc#1282]
**Issue:** 
Crashes in MSAL library

**Nature:**
Intermittent

Happens in the host application after opening the application.(fore4ground)

**Symbolicated Stack traces collected:**
Symbolicated crashes show the following threads to be the reason for Crash.
Both look the same.

**Stack trace 1**

> `
> Termination Signal: Segmentation fault: 11
> Termination Reason: Namespace SIGNAL, Code 0xb
> Terminating Process: exc handler [200]
> Triggered by Thread:  7
> 
> 
> Thread 7 name:  Dispatch queue: msid.aadvalidation.queue
> Thread 7 Crashed:
> 0   ???                           	000000000000000000 0 + 0
> 1   MSAL                          	0x0000000101c21c78 -[MSIDURLSessionManager initWithConfiguration:delegate:delegateQueue:] + 793720 (MSIDURLSessionManager.m:0)
> 2   MSAL                          	0x0000000101c21b94 +[MSIDURLSessionManager initialize] + 793492 (MSIDURLSessionManager.m:50)
> 3   libobjc.A.dylib               	0x0000000196535064 CALLING_SOME_+initialize_METHOD + 20
> 4   libobjc.A.dylib               	0x000000019653b0b0 initializeNonMetaClass + 712
> 5   libobjc.A.dylib               	0x000000019653c410 initializeAndMaybeRelock+ 37904 (objc_class*, objc_object*, mutex_tt<false>&, bool) + 300
> 6   libobjc.A.dylib               	0x000000019654a52c lookUpImpOrForward + 856
> 7   libobjc.A.dylib               	0x0000000196535820 _objc_msgSend_uncached + 64
> 8   MSAL                          	0x0000000101bd6cdc -[MSIDHttpRequest init] + 486620 (MSIDHttpRequest.m:0)
> 9   MSAL                          	0x0000000101b86fe0 -[MSIDAADAuthorityMetadataRequest initWithEndpoint:authority:context:] + 159712 (MSIDAADAuthorityMetadataRequest.m:34)
> 10  MSAL                          	0x0000000101b87f28 -[MSIDAadAuthorityResolver sendDiscoverRequestWithAuthority:validate:context:completionBlock:] + 163624 (MSIDAadAuthorityResolver.m:135)
> 11  MSAL                          	0x0000000101b87a88 __96-[MSIDAadAuthorityResolver resolveAuthority:userPrincipalName:validate:context:completionBlock:]_block_invoke + 162440 (MSIDAadAuthorityResolver.m:99)
> 12  libdispatch.dylib             	0x0000000181deb298 _dispatch_call_block_and_release + 24
> 13  libdispatch.dylib             	0x0000000181dec280 _dispatch_client_callout + 16
> 14  libdispatch.dylib             	0x0000000181d94dcc _dispatch_lane_serial_drain$VARIANT$mp + 612
> 15  libdispatch.dylib             	0x0000000181d958a8 _dispatch_lane_invoke$VARIANT$mp + 424
> 16  libdispatch.dylib             	0x0000000181d9f338 _dispatch_workloop_worker_thread + 712
> 17  libsystem_pthread.dylib       	0x00000001c9bed5a4 _pthread_wqthread + 272
> 18  libsystem_pthread.dylib       	0x00000001c9bf0874 start_wqthread + 8
> `

**Stack trace 2**
`

> Termination Signal: Segmentation fault: 11
> Termination Reason: Namespace SIGNAL, Code 0xb
> Terminating Process: exc handler [292]
> Triggered by Thread:  8
> 
> 
> Thread 8 name:  Dispatch queue: msid.aadvalidation.queue
> Thread 8 Crashed:
> 0   ???                           	000000000000000000 0 + 0
> 1   MSAL                          	0x00000001019334b8 -[MSIDHttpRequest sendWithBlock:] + 488632 (MSIDHttpRequest.m:0)
> 2   MSAL                          	0x000000010196bd2c -[MSIDSilentTokenRequest acquireTokenWithRefreshTokenImpl:completionBlock:] + 720172 (MSIDSilentTokenRequest.m:486)
> 3   MSAL                          	0x0000000101903af4 __63-[MSIDAuthority loadOpenIdMetadataWithContext:completionBlock:]_block_invoke + 293620 (MSIDAuthority.m:239)
> 4   MSAL                          	0x0000000101933074 -[MSIDHttpRequest sendWithBlock:] + 487540 (MSIDHttpRequest.m:92)
> 5   MSAL                          	0x0000000101903a20 -[MSIDAuthority loadOpenIdMetadataWithContext:completionBlock:] + 293408 (MSIDAuthority.m:240)
> 6   MSAL                          	0x000000010196b874 -[MSIDSilentTokenRequest refreshAccessToken:completionBlock:] + 718964 (MSIDSilentTokenRequest.m:393)
> 7   MSAL                          	0x000000010196b358 -[MSIDSilentTokenRequest tryAppRefreshToken:completionBlock:] + 717656 (MSIDSilentTokenRequest.m:358)
> 8   MSAL                          	0x000000010196aaa4 -[MSIDSilentTokenRequest executeRequestImpl:] + 715428 (MSIDSilentTokenRequest.m:269)
> 9   MSAL                          	0x0000000101903440 __78-[MSIDAuthority resolveAndValidate:userPrincipalName:context:completionBlock:]_block_invoke + 291904 (MSIDAuthority.m:127)
> 10  MSAL                          	0x00000001018e3c7c __96-[MSIDAadAuthorityResolver resolveAuthority:userPrincipalName:validate:context:completionBlock:]_block_invoke.14 + 162940 (MSIDAadAuthorityResolver.m:0)
> 11  MSAL                          	0x00000001018e4374 __94-[MSIDAadAuthorityResolver sendDiscoverRequestWithAuthority:validate:context:completionBlock:]_block_invoke_2 + 164724 (MSIDAadAuthorityResolver.m:162)
> 12  MSAL                          	0x00000001018e100c -[MSIDAadAuthorityCache processMetadata:openIdConfigEndpoint:authority:context:completion:] + 151564 (MSIDAadAuthorityCache.m:85)
> 13  MSAL                          	0x00000001018e4198 __94-[MSIDAadAuthorityResolver sendDiscoverRequestWithAuthority:validate:context:completionBlock:]_block_invoke + 164248 (MSIDAadAuthorityResolver.m:152)
> 14  MSAL                          	0x0000000101933074 -[MSIDHttpRequest sendWithBlock:] + 487540 (MSIDHttpRequest.m:92)
> 15  MSAL                          	0x00000001018e3fa0 -[MSIDAadAuthorityResolver sendDiscoverRequestWithAuthority:validate:context:completionBlock:] + 163744 (MSIDAadAuthorityResolver.m:169)
> 16  MSAL                          	0x00000001018e3a88 __96-[MSIDAadAuthorityResolver resolveAuthority:userPrincipalName:validate:context:completionBlock:]_block_invoke + 162440 (MSIDAadAuthorityResolver.m:99)
> 17  libdispatch.dylib             	0x0000000181deb298 _dispatch_call_block_and_release + 24
> 18  libdispatch.dylib             	0x0000000181dec280 _dispatch_client_callout + 16
> 19  libdispatch.dylib             	0x0000000181d94dcc _dispatch_lane_serial_drain$VARIANT$mp + 612
> 20  libdispatch.dylib             	0x0000000181d958a8 _dispatch_lane_invoke$VARIANT$mp + 424
> 21  libdispatch.dylib             	0x0000000181d9f338 _dispatch_workloop_worker_thread + 712
> 22  libsystem_pthread.dylib       	0x00000001c9bed5a4 _pthread_wqthread + 272
> 23  libsystem_pthread.dylib       	0x00000001c9bf0874 start_wqthread + 8
> `

Not able to fetch any other debugging-related information.
Please can we look into the stack trace, and suggest provide some resolution for the same.

**Comment by antrix1989** [comment]
hi @rahulcode, could you please provide more details:
- steps to reproduce
- OS name and version
- xcode version

Does this happen when you run unit tests or when you run app extension?

**Comment by rahulcode** [comment]
Hi @antrix1989 

**Steps to Reproduce**
As such there are no specific steps to reproduce.
It happened in our Application where we have functionality wherein Authentication happens silently whenever we launch and some other conditions. Normally it works absolutely fine, but in some cases after launching our application sometimes it crashes randomly with this stack trace.

**Test scenario::**
The application had **MSAL 1.1.5** with all functionality working fine.
Upgraded Application to newer test version with **MSAL 1.1.13**
After Upgrading the Application successfully, crashes seen in MSAL
Workflow and functionality are proper after crashes.

**OS name and version**
iOS 14.4 iPad Mini

**Xcode Version for the Application**
12.1

These crashes happened in normal Application testing.
SSO Extension was not present in this scenario.

**Comment by antrix1989** [comment]
This looks like your device is out of memory. @rahulcode, could you check if that is the case?
