### ISSUE TITLE
MSAL 1.1.16 Error: While building for Mac Catalyst, no library for this platform was found in

### ISSUE THREAD

**Issue by lrun-cmck** [AzureAD/microsoft-authentication-library-for-objc#1290]
Hi,

I'm attempting to build a private framework that has all the MSAL logic inside it, which will be used in an app that should support `macOS 11.0 +`. I'm using `SPM` for importing it. While building for `macOS`, I'm getting this error: `While building for Mac Catalyst, no library for this platform was found in ... MSAL/MSAL.xcframework`

<img width="1645" alt="Screenshot 2021-04-16 at 15 21 52" src="https://user-images.githubusercontent.com/72737527/115024958-6ed4ff80-9ec9-11eb-98ee-2d753208287a.png">
<img width="1024" alt="Screenshot 2021-04-16 at 15 22 23" src="https://user-images.githubusercontent.com/72737527/115024966-71cff000-9ec9-11eb-95ba-5af200893ddf.png">

Any idea how this building error can be fixed ?

Thank you for the support !

**Comment by ameyapat** [comment]
Hi, Currently we don't support mac catalyst. Currently we have a [feature](https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/649) tracking this.
