### ISSUE TITLE
MSAL iOS B2C login cache is not saved. we use custom policy for sign-in and change password. after successful signing change password policy again asking for user credentials

### ISSUE THREAD

**Issue by AvinashKiran** [AzureAD/microsoft-authentication-library-for-objc#1294]

**Comment by AvinashKiran** [comment]
For change password flow, MSAL is asking for credentials even user has already signed into the application.

**Comment by kaisong1990** [comment]
@AvinashKiran Thanks for reaching out. Could you provide more details on the signing flow to the app? Is it through web browser?

**Comment by AvinashKiran** [comment]
Yes, Authentication happens using a web page.  We have two policies for login and change passwords.  When a user tries to change the password, the web page is opening with the Login and proceeds to the change password flow. I am unable to pass the session information to change the password flow. I have set the account and login hint but no use. Pls help me with this issue.

I have tried with 'webviewType = .safariViewController' and works only with the login flow , but in on next visit where authentication is happening through silentAcccount method,  change password flow is asking for login.

**Comment by kaisong1990** [comment]
@AvinashKiran Can you provide correlationId and timestamp, and we might be able to pull the logs

**Comment by AvinashKiran** [comment]
["TID=629854 MSAL 1.1.16 iOS 14.4.2 [2021-04-28 03:09:45 - 8F4BE9BA-48AC-4B5F-8DF8-FD6428EED1EB] [MSAL] -[MSALPublicClientApplication acquireTokenWithParameters:(\n    \"https://meghaqa.onmicrosoft.com/api/read\"\n)\n                                     extraScopesToConsent:(null)\n                                                  account:Masked(not-null)\n                                                loginHint:auth.placeholder-dacdd3e4__carrier.com\n                                               promptType:MSALPromptTypePromptIfNecessary\n                                     extraQueryParameters:(null)\n                                                authority:<MSALB2CAuthority: 0x281385020>\n                                              webviewType:MSALWebviewTypeDefault\n                                            customWebview:No\n                                            correlationId:(null)\n                                             capabilities:(null)\n                                            claimsRequest:(null)]"]
["TID=629854 MSAL 1.1.16 iOS 14.4.2 [2021-04-28 03:09:45 - 8F4BE9BA-48AC-4B5F-8DF8-FD6428EED1EB] [MSAL] -[MSALPublicClientApplication acquireTokenWithParameters:(\n    \"https://meghaqa.onmicrosoft.com/api/read\"\n)\n                                     extraScopesToConsent:(null)\n                                                  account:Masked(not-null)\n                                                loginHint:auth.placeholder-dacdd3e4__carrier.com\n                                               promptType:MSALPromptTypePromptIfNecessary\n                                     extraQueryParameters:(null)\n                                                authority:<MSALB2CAuthority: 0x281385020>\n                                              webviewType:MSALWebviewTypeDefault\n                                            customWebview:No\n                                            correlationId:(null)\n                                             capabilities:(null)\n                                            claimsRequest:(null)]"]
["TID=629854 MSAL 1.1.16 iOS 14.4.2 [2021-04-28 03:09:45 - 8F4BE9BA-48AC-4B5F-8DF8-FD6428EED1EB] [MSAL] Beginning interactive flow."]
["TID=629854 MSAL 1.1.16 iOS 14.4.2 [2021-04-28 03:09:45 - 8F4BE9BA-48AC-4B5F-8DF8-FD6428EED1EB] [MSAL] Beginning interactive flow."]
["TID=629854 MSAL 1.1.16 iOS 14.4.2 [2021-04-28 03:09:45] Start background app task with type 0"]
["TID=629854 MSAL 1.1.16 iOS 14.4.2 [2021-04-28 03:09:45] Start background app task with type 0"]
["TID=629854 MSAL 1.1.16 iOS 14.4.2 [2021-04-28 03:09:45 - 8F4BE9BA-48AC-4B5F-8DF8-FD6428EED1EB] [MSAL] Resolving authority: Masked(not-null), upn: 445d8c05"]
["TID=629854 MSAL 1.1.16 iOS 14.4.2 [2021-04-28 03:09:45 - 8F4BE9BA-48AC-4B5F-8DF8-FD6428EED1EB] [MSAL] Resolving authority: Masked(not-null), upn: 445d8c05"]
["TID=629854 MSAL 1.1.16 iOS 14.4.2 [2021-04-28 03:09:45 - 8F4BE9BA-48AC-4B5F-8DF8-FD6428EED1EB] [MSAL] Resolved authority, validated: NO, error: 0"]
["TID=629854 MSAL 1.1.16 iOS 14.4.2 [2021-04-28 03:09:45 - 8F4BE9BA-48AC-4B5F-8DF8-FD6428EED1EB] [MSAL] Resolved authority, validated: NO, error: 0"]

**Comment by kaisong1990** [comment]
@AvinashKiran Thanks, shared those logs to B2C team for more information
