### ISSUE TITLE
How to make unified login flow to the mobile app.

### ISSUE THREAD

**Issue by Naveen-workboard** [AzureAD/microsoft-authentication-library-for-objc#1297]
Hi,

I'm not sure this is correct place to ask, but I'm looking for a solution for a problem we are facing.
We have our mobile app (iPhone and Android) which has it's own authentication flow to login the users and this is done using SSO. Some vendors of our app use Microsoft corporate accounts for SSO login. Now one vendor is asking us to integrate the MS Intune in the app so that they can apply the policy which they create for their org.

We have followed the guidelines and documentation from [here](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios) and implemented.

Now we see once our app make SSO login successful, calling (void)loginAndEnrollAccount: (NSString *)identity; API takes user to login again in order to enroll user/app for policy and reterival.

This is kind of making two logins by end user

Is there a way we can unify a single login to our server and also apply policy to our app?

Thanks.

**Comment by mipetriu** [comment]
Hi @Naveen-workboard, we're not experts about the Intune SDK, but it seems that there might be other API's that are available to apply policies once the user is signed in.

Feel free to raise the question to the Intune MAM SDK repo here: https://github.com/msintuneappsdk/ms-intune-app-sdk-ios

**Comment by Naveen-workboard** [comment]
@mipetriu : Thanks, I'll check with intune team.
