### ISSUE TITLE
App rejection because of App Tracking Transparency (ATT)

### ISSUE THREAD

**Issue by Joshua-Newar** [AzureAD/microsoft-authentication-library-for-objc#1301]
Our app got rejected because in iOS14.5 the MSAL lib throws a ATT alert but when the user selects not to be tracked, the user is not signed in. In fact, the user us brought back to the same screen where he is presented with the alert again if he wants to login. Thus Apple says we are forcing the user to allow tracking. Since this is happening in the MSAL library we don't know how to change this. We tried some solutions like App Bound Domains and using a customWebView but nothing helped. In addition we also tried to setup ATT for the whole app but even when ATT is allowed for the app, the MSAL still pops up its own alert (so using ATT for the whole app didn't bring us any further).
Can this be fixed? Or is there a workaround?
![ATT edited](https://user-images.githubusercontent.com/84087184/117996065-20891400-b342-11eb-85f2-45618acf3259.jpg)

**Comment by Joshua-Newar** [comment]
In addition we also tried to setup ATT for the whole app but even when ATT is allowed for the app, the MSAL still pops up its own alert (so using ATT for the whole app didn't bring us any further).

**Comment by hieunguyenmsft** [comment]
Thank you @Joshua-Newar and we are sorry to hear that. To be honest, Application rejected by ATT is new to me. Would you mind to share the reject message from Apple? 
Thank you

**Comment by Joshua-Newar** [comment]
Hi,

I think that Apple just started to enforce ATT on app submissions.

So what happens is if you click Don’t Allow for the tracking, you just go back to the sign in screen.
This means you are forced to click Allow if you want to sign in.

This is the message we received from Apple and the 2 screenshots they attached:

From Apple
Guideline 2.1 - Performance - App Completeness


We discovered one or more bugs in your app. Specifically, We noticed when we tap on “ don’t allow” for the tracking activity the app will not continue into he login, forced to say “ allow “. Please review the details below and complete the next steps. 

Review device details:

- Device type: iPad and iPhone 
- OS version: iOS 14.5.1

Next Steps

Please run your app on a device to reproduce the issues, then revise and submit your app for review.If at first you're unable to reproduce the issue, try the following: 

- For new apps, uninstall all previous versions of your app from a device, then install and follow the steps to reproduce. 
- For app updates, install the new version as an update to the previous version, then follow the steps to reproduce.

If we misunderstood the intended behavior of your app, please reply to this message in Resolution Center to provide information on how these features were intended to work.

Resources

- For information about testing apps and preparing them for review, see Technical Note TN2431: App Testing Guide <https://developer.apple.com/library/archive/technotes/tn2431/_index.html>.
- To learn about troubleshooting networking issues, see About Networking <https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/Introduction/Introduction.html>.

**Comment by hieunguyenmsft** [comment]
Thank you, I will try to repro the bug on my side and keep you posted.

**Comment by Joshua-Newar** [comment]
FYI
You will need at least iOS 14.5 and a real device.
The simulator doesn’t seem to show the alert.
Also for some reason once you are past the Sign In with MSAL, the alert is never shown again.
I had to fully reset my iPad mini to get the alert back.

Thanks for looking into this.

**Comment by hieunguyenmsft** [comment]
@Joshua-Newar: Hi I checked with my team and this bug is already reported to Apple. They will provide a fix for that in the next OS release (14.6). They also have a RADAR/feedback item to track on that, once I got the link I will share you.
About your app rejection, I think you can forward that information to them to get it back to the store, your app did nothing wron.

**Comment by Joshua-Newar** [comment]
Thanks for your message.

Please forward me the link.
In the mean time we did manage to get the app approved by using a custom web view but the screens differ because there is no bar on top and bottom for navigation and to cancel the request. So we added a button to leave the authentication view. This is not a nice option. Also there are some white screens with this custom web view sometimes. At least Apple did approve app now, but please provide the link because I would like to roll back this solution whenever possible.

Thanks for your support,
Joshua

**Comment by hieunguyenmsft** [comment]
Hi @Joshua-Newar , this is the information I got from my team:

> This is a known WebKit issue within 14.5 and 14.5.1, tracked with: FB9096871.   Apple confirmed that the fix (<rdar://problem/75619058>) will be in iOS and iPadOS 14.6, to address native app sign-in showing the prompt.  The prompt does not occur due to anything done by the app developer or the live.com login page that is being used here.  Apple should allow the app through.

 
Hope it will help your app get approval back to the store.
Thank you.

**Comment by Joshua-Newar** [comment]
Thanks for helping out.

Let’s see what Apple says.
