### ISSUE TITLE
MSIDOAuth2EmbeddedWebviewController may allow forged log entries

### ISSUE THREAD

**Issue by br-earl-gaspard** [AzureAD/microsoft-authentication-library-for-objc#1303]
In MSIDOAuth2EmbeddedWebviewController.m lines 255-259, it looks like it is possible for someone to forge log entries or inject malicious content into the log because a part of the `requestURL` is being written to the log which later happens in MSIDLogger.
```
- (void)webView:(WKWebView *)webView decidePolicyForNavigationAction:(WKNavigationAction *)navigationAction decisionHandler:(void (^)(WKNavigationActionPolicy))decisionHandler
{
    NSURL *requestURL = navigationAction.request.URL;
    
    MSID_LOG_WITH_CTX_PII(MSIDLogLevelVerbose, self.context, @"-decidePolicyForNavigationAction host: %@", MSID_PII_LOG_TRACKABLE(requestURL.host));
```
Is this something that can be fixed?

**Comment by hieunguyenmsft** [comment]
Hi @br-earl-gaspard , thank you for reporting this finding. 
I haven't understood the attack yet, would you please elaborate on the harmful activity here? MSAL is an open-source library, so anyone can customize it and print out the information they want.
Thank you.

**Comment by br-earl-gaspard** [comment]
In the code when a link is tapped the `decidePolicyForNavigationAction` gets called and then logs the `requestURL.host` to the console. It is possible, however unlikely, that link's host could be setup in a way to contain erroneous information that could get logged as a fake log entry. An example might be `userloggedout`. Overall, I think this is a very minor concern and not likely to happen.

**Comment by hieunguyenmsft** [comment]
Good call-out and I agree the attack surface here is relatively small ( attacker needs to set up a new identity provider server for forging false information into the log). I closed it with no further activity.
Thank you.
