### ISSUE TITLE
MSIDDevicePopManager could be writing unvalidated input into JSON

### ISSUE THREAD

**Issue by br-earl-gaspard** [AzureAD/microsoft-authentication-library-for-objc#1304]
In MSIDDevicePopManager.m line 149, it is possible this call could be writing unvalidated input into JSON. This could allow injection of arbitrary elements or attributes into the JSON entity.
```
NSDictionary *publicKeyDict = [NSJSONSerialization JSONObjectWithData:publicKeyData options:0 error:error];
```

The JSON injection occurs from two places:
1. in MSIDAssymetricKeyPair.m at line 95
```
_keyExponent = [[publicKeyBits subdataWithRange:NSMakeRange(iterator, exp_size)] base64EncodedStringWithOptions:0];
```

2. in MSIDDevicePopManager.m at line 149
```
_keyModulus = [[subData subdataWithRange:NSMakeRange(1, subData.length-1)] base64EncodedStringWithOptions:0];
```

Can someone verify if this is something that could happen or is a concern?
Thanks.

**Comment by antrix1989** [comment]
Hi @br-earl-gaspard. The public key is generated by the client and stored in the keychain, so I don't see any concerns here.

**Comment by Edord99** [comment]
ii
