### ISSUE TITLE
library is not building arm7,armv7 arcetecture

### ISSUE THREAD

**Issue by parora9594** [AzureAD/microsoft-authentication-library-for-objc#1317]
We are facing issue is MSAL Library, This library is getting build only for x86_64 arm64 architecture. 
We tried using pod and Carthage it is only getting build for x86_64 arm64.  We have checked released version of MSAL like 1.1.17, 1.1.18. it same there.

Xcode cersion: 11.6 CLT: 11.6 
Language: Objective C

We need this to build for all the architecture.

`ld: warning: ignoring file /Users/Puneet/Documents/Mobicontrol/MobiControl/iOSWorkspace/iOSAgent/Carthage/Build/iOS/MSAL.framework/MSAL, missing required architecture armv7 in file /Users/Puneet/Documents/Mobicontrol/MobiControl/iOSWorkspace/iOSAgent/Carthage/Build/iOS/MSAL.framework/MSAL (2 slices)
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_MSALInteractiveTokenParameters", referenced from:
      objc-class-ref in DeviceConfigurationTableViewController.o
  "_MSALErrorDomain", referenced from:
      ___62-[DeviceConfigurationTableViewController acquireTokenSilently]_block_invoke in DeviceConfigurationTableViewController.o
  "_OBJC_CLASS_$_MSALClaimsRequest", referenced from:
      objc-class-ref in DeviceConfigurationTableViewController.o
  "_OBJC_CLASS_$_MSALWebviewParameters", referenced from:
      objc-class-ref in DeviceConfigurationTableViewController.o
  "_OBJC_CLASS_$_MSALPublicClientApplicationConfig", referenced from:
      objc-class-ref in DeviceConfigurationTableViewController.o
  "_OBJC_CLASS_$_MSALSilentTokenParameters", referenced from:
      objc-class-ref in DeviceConfigurationTableViewController.o
  "_OBJC_CLASS_$_MSALAADAuthority", referenced from:
      objc-class-ref in DeviceConfigurationTableViewController.o
  "_OBJC_CLASS_$_MSALPublicClientApplication", referenced from:
      objc-class-ref in AppDelegate.o
      objc-class-ref in DeviceConfigurationTableViewController.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Please look into this.

**Comment by ameyapat** [comment]
Hi @parora9594 , Could you provide details for which device and os version you're trying to build for?

**Comment by parora9594** [comment]
hi Stale, We are using iphone 6 with OS 10.

**Comment by ameyapat** [comment]
Hi @parora9594 , MSAL currently supports iOS 11+ : https://github.com/AzureAD/microsoft-authentication-library-for-objc#supported-versions . Could you retry on device with iOS 11 or above?

**Comment by parora9594** [comment]
@ameyapat IS there any way to use this, my app support from iOS.

I found one macro which can be used to build it for only arm64 and install it lower iOS versions.
Like this:
#ifdef __aarch64__
MSALAADAuthority *msalAuthority;
MSALPublicClientApplicationConfig *config;
MSALPublicClientApplication *application;
MSALClaimsRequest *request;
MSALWebviewParameters *webParameters;
#endif

Is it fine to use this, or it can create problems in future.

**Comment by parora9594** [comment]
@ameyapat  Waiting for your esponse.

**Comment by ameyapat** [comment]
Hi @parora9594 , I think adding that macro will just exclude those variables during compilation for architecture that is not 64 bit like armv7. For your original issue, can you make sure if the MSAL library is linked correctly to your target? https://github.com/Azure-Samples/ms-identity-mobile-apple-swift-objc is a link to our sample app, you can refer to it to make sure how MSAL is included in your app. Can you check if the sample app build and runs for your device?

**Comment by jasoncoolmax** [comment]
Not sure if it will help, you may also pay attention regarding what iOS version you support in the pod file.
However, our current MSAL supports iOS 11 onwards. We don't support iOS 8 anymore. Good luck to you :)
