### ISSUE TITLE
Error: The UIWindowScene for the returned window was not in the foreground active state

### ISSUE THREAD

**Issue by adiashok123** [AzureAD/microsoft-authentication-library-for-objc#1319]
While doing a interactive login, we are getting an error in loop, it repeatedly ask for login credentials and fails with the same error.

Attaching the error logs:

: MSAL-Auth: Error: Error Domain=com.apple.AuthenticationServices.WebAuthenticationSession Code=3 "The UIWindowScene for the returned window was not in the foreground active state." UserInfo={NSDebugDescription=The UIWindowScene for the returned window was not in the foreground active state., MSALCorrelationIDKey=XXXXXXXXXXXXXXXX}

Device : iPhone
MSAL SDK : 1.1.13
iOS Version : 14.4.2

**Comment by kaisong1990** [comment]
@adiashok123 Thanks for your question, 

Which MSAL API are you using?

In general ,MSAL APIs are getting triggered while your app is not fully in foreground, and cannot get viewController from UIWindowScene. So it is not a MSAL lib issue.

In order to avoid such issue, you could follow Apple's API [here](https://developer.apple.com/documentation/uikit/uiscenedidactivatenotification?language=objc) and make sure app is fully active before triggering MSAL APIs.

**Comment by adiashok123** [comment]
MSAL SDK : 1.1.13

**Comment by kaisong1990** [comment]
@adiashok123 Do you have a specific name of the API you are calling from publicClientApplication? Please try with suggested and make sure the app scene is active.

**Comment by parasjain10** [comment]
[Error: Error Domain=com.apple.AuthenticationServices.WebAuthenticationSession Code=3 "The UIWindowScene for the returned window was not in the foreground active state." UserInfo={NSDebugDescription=The UIWindowScene for the returned window was not in the foreground active state.,

**Comment by parasjain10** [comment]
@adiashok123  how did you overcome this error?
I am also getting the same when i used the package react-native-msal: 4.0.4 in my react native project, while opening the iOS app I am getting this error:

[Error: Error Domain=com.apple.AuthenticationServices.WebAuthenticationSession Code=3 "The UIWindowScene for the returned window was not in the foreground active state." UserInfo={NSDebugDescription=The UIWindowScene for the returned window was not in the foreground active state.,
