### ISSUE TITLE
Broker auth flow fails - Error: MSALInternalErrorCodeKey=-42700

### ISSUE THREAD

**Issue by parveen-bhatia** [AzureAD/microsoft-authentication-library-for-objc#1320]
Hi,

I am using MSAL interactive signIn auth flow with Intune SDK. App is able to open broker app and after selecting an account able to return to my app. And then getting below error

``
Error Domain=MSALErrorDomain Code=-50000 \"(null)\" UserInfo={MSALErrorDescriptionKey=application did not receive response from broker., MSALInternalErrorCodeKey=-42700, MSALCorrelationIDKey=97BE84D2-64A8-4D62-8A9C-B64FA6B7A1C6}"
``

I am also handling `appdelegate open url` callback as mentioned in https://github.com/AzureAD/microsoft-authentication-library-for-objc#swift-1 and also configuring `msal` as mentioned https://github.com/AzureAD/microsoft-authentication-library-for-objc#configuring-msal

On removing broker auth app (Microsoft Authenticator), auth with browser works fine.

Attaching error logs `-` [IntuneMAMDiagnosticFiles.txt](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/6641008/IntuneMAMDiagnosticFiles.txt)

**Comment by kaisong1990** [comment]
HI @parveen-bhatia Thanks for your question, could you put a breakpoint at **function openrul within the app delegate or scence delegate if you have** as about link mentioned and see if it was triggered?

Also please provide an incidentId so that we can check if the broker response is in expected format.

Here is [link](
https://github.com/AzureAD/azure-activedirectory-library-for-objc/wiki/Instructions-on-Collecting-Microsoft-Authenticator-Logs) on how to get incidentId

**Comment by parveen-bhatia** [comment]
Thanks @kaisong1990 for follow up.

Was able to resolve this issue. So, the issue is when `sourceApplication` is being passed as empty string `""` (after we extract it like `sourceApplication = options[UIApplicationOpenURLOptionsSourceApplicationKey]`) in below method. (Which is happening as in my case AppDelegate is in ObjC and wrapper class  over MSAL in Swift uses `sourceApplication` string as non-optional)

```
MSALPublicClientApplication.handleMSALResponse(url, sourceApplication: "")
```

In above case this method returns false and flow doesn't work correctly.

However when we pass `nil` (after we extract it like `sourceApplication = options[UIApplicationOpenURLOptionsSourceApplicationKey]`)

```
MSALPublicClientApplication.handleMSALResponse(url, sourceApplication: nil)
```

Then it works fine.

Still seems that its minor fix which can be adopted by `MSALPublicClientApplication.handleMSALResponse`

**Comment by kaisong1990** [comment]
@parveen-bhatia Glad you resolved the issue! Let me bring this to the team and see if we can handle this better. Will keep you posted :)

**Comment by kaisong1990** [comment]
@parveen-bhatia 
Looks like there is an issue on our side and sourceApplication is not expected to be nil or empty. Could you provide some more information why empty string is passed as sourceApplication in your case?

**Comment by parveen-bhatia** [comment]
When we extract sourceApplication using ` NSString *sourceApplication = options[UIApplicationOpenURLOptionsSourceApplicationKey];` (AppDelegate is in ObjC), it returns nil.

And we have Swift wrapper class over `MSALPublicClientApplication.handleMSALResponse` which takes `sourceApplication` as non optional parameter like `handleOpenURL(_ url: URL, application: String) -> Bool`. I think due to objc/swift bridging application parameter is being received empty string "", instead of nil in wrapper class.

In my case, i just updated the code in my wrapper class (in Swift) to check if it is empty string then pass nil like
```
let sourceApp = application.isEmpty ? nil : application
 MSALPublicClientApplication.handleMSALResponse(url, sourceApplication: sourceApp)
```
So, using `nil` when sourceApp is empty is working fine.

**Comment by kaisong1990** [comment]
@parveen-bhatia Thanks for confirming. We have a PR open to treat empty and nil the same way.

https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/1004

Closing this issue and feel free to reopen if you find anything wrong after testing
