### ISSUE TITLE
Can we use Silent SSO with a Developer ID signed app that does not use provisioning profiles?

### ISSUE THREAD

**Issue by crosshawk** [AzureAD/microsoft-authentication-library-for-objc#1321]
In our MAC application “Automatically manage signing” under Signing & Capabilities is enabled and so far we didn’t have to use a provisioning profile on our devices as the app doesn’t use Keychain Sharing. In order for Silent Single Sign-On (SSO) for MSAL to work we need to add a new Keychain group to our project’s capabilities. That seems to require a provisioning profile to work, but our Bamboo build agents don’t have one as we haven’t registered them and would like to avoid having to do so as it would be pretty costly to maintain and troubleshoot.
So the question is, is it possible to make Silent SSO for MSAL work with a Developer ID signed app that does not use provisioning profiles?

**Comment by kaisong1990** [comment]
@crosshawk Thanks for your question, you might need to raise a question to Apple [here](https://developer.apple.com/forums/) and ask if there is any workaround on this.
