### ISSUE TITLE
Is OAuth 2.0 Client Credentials flow available ?

### ISSUE THREAD

**Issue by toseefkhilji** [AzureAD/microsoft-authentication-library-for-objc#1328]
Hi,

Is there any classes or method to use this auth flow?

Thanks.

**Comment by kaisong1990** [comment]
@toseefkhilji Thanks for your question.

Client Credentials flow is not supported on client, please refer to this [issue](https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1186)

**Comment by toseefkhilji** [comment]
@kaisong1990 Thanks for the early reply.

My app provides users to have some shared activity/functionality where users can (save/create/upload files and folder and give access), Users don't require to Login in there Microsoft account. 
We interactive login and get access tokens from our app.

Can you please suggest a flow or other way for our requirement?

**Comment by jasoncoolmax** [comment]
I don't have a good suggestion regarding your requirement. Following is some resources that may or may not help :)
https://developer.apple.com/documentation/devicecheck/validating_apps_that_connect_to_your_server
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-client-applications

**Comment by toseefkhilji** [comment]
@jasoncoolmax Thanks!!!
I'll check.
