### ISSUE TITLE
Issue with cancel flow with acquireToken(with: parameters) 

### ISSUE THREAD

**Issue by parveen-bhatia** [AzureAD/microsoft-authentication-library-for-objc#1329]
**Steps to replicate:**
- Launch the app (no broker app installed)
- MSAL web auth flow asks for credential
- Cancel the web auth popup.
- Kill and Launch the app again

**Issue:**
`clientApp.acquireToken(with: parameters)` doesn't pop up with web auth and immediately fails with below error

``
The operation couldn’t be completed. (com.apple.AuthenticationServices.WebAuthenticationSession error 3.)
``

This issue is not consistent. But most of the time `acquireToken(with: parameters)` method throws above error without even prompting for web auth.

Please let me know if we have any resolution or workaround to fix this?

**Comment by jasoncoolmax** [comment]
Hi @parveen-bhatia , may I know which version of MSAL and macOS were you using for the repro?

**Comment by parveen-bhatia** [comment]
I am using MSAL (1.1.17), with iOS SDK (14.5) and macOS Big Sure (11.4)

**Comment by jasoncoolmax** [comment]
Hi @parveen-bhatia I have tried teh same settings as well as the same repro steps as you mentioned, but no luck I am not able to reproduce it.

Is it possible for you to provide the MSAL logs? Instruction of how to enable logging: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging-ios?tabs=objc

**Comment by parveen-bhatia** [comment]
@jasoncoolmax thanks for your response.

This issue is inconsistent.  To reproduce it we can 
- Launch the app and continue with user prompt to Sign In from `ASWebAuthenticationSession`
- Then we can tap on `Cancel` on the web browser  initiated by by `ASWebAuthenticationSession`
- Launch app again. And repeat above steps at least 3 times or more. (Sometimes it happen on first time also)
- Then we would be able to see this issue.

Attached logs 
[IntuneMAMDiagnosticFiles_1329.txt](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/6751288/IntuneMAMDiagnosticFiles_1329.txt)

**Comment by kohanian** [comment]
@parveen-bhatia I've run into this issue before. I believe this is actually an Apple specific error. You're getting the following error:
```
ASWebAuthenticationSessionErrorCodePresentationContextInvalid: The presentation context returned was not elligible to show the authentication UI. For iOS, validate that the UIWindow is in a foreground scene.
```
A good example of this happening would be when a system alert is displayed in the foreground on top of your app's window, and when the `ASWebAuthenticationSession` modal asking the user to log in tried to display itself, it can't because it's window isn't in the foreground. Your best bet is to handle this error silently and have some sort of button the user can press to manually attempt to log in again.

**Comment by parveen-bhatia** [comment]
Thanks @kohanian for providing with me this clue and details about the root cause.

In my case, i was trying to `signIn` with `MSAL` (which is trying to present `ASWebAuthenticationSession`) before AppDelegate's `application:didFinishLaunch` is completed. 
I tried doing it, after little delay on app launch and even UI by tapping on button.
Both are working fine.

Thanks for the help and fine to close this ticket.
