### ISSUE TITLE
MSALErrorInternal Error while doing a Silent Auth

### ISSUE THREAD

**Issue by adiashok123** [AzureAD/microsoft-authentication-library-for-objc#1332]
**Issue**: While doing a sign silently, we are getting (MSALErrorDomain, -50000) MSALErrorInternal in MSAL 1.1.19 and not MSALErrorInteractionRequired [as in MSAL 1.1.13] when the sign in frequency has expired.
However, in earlier SDK of MSAL, this was MSALErrorInteractionRequired and this was the basis for us to go for interactive login. This is for both password as well as certificate based authentication. [with SSO Extension case]

This test was in continuation of our earlier filed tickets testing reg. "[JSON error](https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1156)" . Now, with MSAL 1.1.19 we don't see the JSON Error but with this newly introduced issue we are not able to get the access token.

**NOTE:**
We are not seeing JSON issue as well as "[Enroll Now/Continue](https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1156#issuecomment-823887139)" issue as mentioned in this ticket.

SDK: 1.1.19
iOS : 14.0.1
Device : iPhone 7
MS Authenticator App : Latest

Note:
Logs Attached.
SSO Extension Profile Attached. We include our app bundle id in it.

[
[TicketLogs.log](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/6714098/TicketLogs.log)
![MS Auth App](https://user-images.githubusercontent.com/73838676/123382309-67a82d00-d5af-11eb-90ea-371de72578e7.png)
](url)

**Comment by hieunguyenmsft** [comment]
Thank you for reporting it. We will look at the logs and keep you posted.
