### ISSUE TITLE
WatchOS support

### ISSUE THREAD

**Issue by JMCPH** [AzureAD/microsoft-authentication-library-for-objc#1339]
When will the MSAL SDK become available for watchOS?

**Comment by antrix1989** [comment]
Hi @JMCPH . I am not aware of any plans to support Device Code flow in MSAL ObjC. + @brandwe to track this feature request.

**Comment by JMCPH** [comment]
@antrix1989 thank you for your quick reply.

**Comment by NerevarineRule** [comment]
@JMCPH  is it ok for us to close this issue? I see you closed it and then reopened it immediately after. do you have any new concerns?
