### ISSUE TITLE
[QUESTION] Custom login viewcontroller?

### ISSUE THREAD

**Issue by JMCPH** [AzureAD/microsoft-authentication-library-for-objc#1340]
Hi,

Is it possible to present our own custom `AuthViewController` instead of the WKWebView using the framework, or is there any other way to do so?

**Comment by NerevarineRule** [comment]
I believe we support a customized WkWebView instance, as long as it is a subclass of WKWebView.

**Comment by JMCPH** [comment]
Thanks for the reply, but is there anyway to login without using a custom WKWebView?

**Comment by NerevarineRule** [comment]
we don't support custom view controller with custom UI. we recommend that you use one of the webview types supported by our MSAL library, which will handle view controller generation/logic.

**Comment by ameyapat** [comment]
Closing this issue, feel free to re-open if there are any further questions
