### ISSUE TITLE
SSO between two iOS native B2C apps not working

### ISSUE THREAD

**Issue by jrodrigues88** [AzureAD/microsoft-authentication-library-for-objc#1341]
Hi,

We have two mobile apps setup with Azure B2C and they are using a signup/signin journey. The SSO between these apps are not working in iOS. I know that MSAL itself wont handle the SSO, instead the browser handles it. I am using **webviewType = .authenticationSession** as per the documentations.
At the same time in Android, SSO is working using Chrome browser.

Following is the iOS code used for setting the configuration.

```
let authority = try MSALB2CAuthority(url: authorityURL)        
        let msalConfiguration = MSALPublicClientApplicationConfig(clientId: kClientID, redirectUri: kRedirectUri, authority: authority)
        msalConfiguration.knownAuthorities = [authority]
        msalConfiguration.bypassRedirectURIValidation = true

        self.applicationContext = try MSALPublicClientApplication(configuration: msalConfiguration)
        self.webViewParamaters = MSALWebviewParameters(authPresentationViewController: self)
        self.webViewParamaters?.webviewType = .authenticationSession
```

Following is the iOS code for calling acquire token.

```
 let parameters = MSALInteractiveTokenParameters(scopes: kScopes, webviewParameters: webViewParameters)
        parameters.promptType = .promptIfNecessary        
        applicationContext.acquireToken(with: parameters) { (result, error) in
        }
```

The signin/signup journey url contains **nonce=defaultNonce** and **response_type=id_token**. But I can't find any way to set it up in the MSAL related code.

_https://{​​​​​​​tenant}​​​​​​​.b2clogin.com/{​​​​​​​directory}​​​​​​​.onmicrosoft.com/oauth2/v2.0/authorize?p={​​​​​​​Policy}​​​​​​​&client_id={​​​​​​​clientID}​​​​​​​&nonce=defaultNonce&redirect_uri={​​​​​​​redirectURI}​​​​​​​&scope=openid&response_type=id_token_

Also I fond this issue in web, which is similar to mine - [SSO issue](https://docs.microsoft.com/en-us/answers/questions/365956/sso-in-ios-with-safari-browser.html)

Thanks in advance!

**Comment by ameyapat** [comment]
Hi @jrodrigues88 , thanks for bringing light to this issue. What is the iOS version that is being used? There was a bug in iOS 14 from apple where the browser wouldn't attach cookies in subsequent calls. Here are the details : https://developer.apple.com/forums/thread/663533 . It was fixed in iOS 14.5.
A workaround for iOS 14 was using keep me signed in : [KMSI](https://docs.microsoft.com/en-us/azure/active-directory-b2c/session-behavior?pivots=b2c-user-flow#enable-keep-me-signed-in-kmsi)

**Comment by jrodrigues88** [comment]
Thanks @ameyapat, tested with iOS 14.5 and its working. 

> There was a bug in iOS 14 from apple where the browser wouldn't attach cookies in subsequent calls.
Does that mean SSO will work in iOS13?

**Comment by ameyapat** [comment]
@jrodrigues88 Yes it should be working for iOS 13. The bug was just in iOS versions 14-14.4
