### ISSUE TITLE
ADFS and MSAL - Question

### ISSUE THREAD

**Issue by peterveeva** [AzureAD/microsoft-authentication-library-for-objc#1354]
I notice in the documentation https://docs.microsoft.com/en-us/azure/active-directory/develop/config-authority that there is the following note:

Modern authentication with Active Directory Federation Services as identity provider (ADFS) is not supported (see ADFS for Developers for details). ADFS is supported through federation.

I also see in the MSAL library that there is an ADFSAuthority that is not currently supported on iOS.  Will that be supported in the future?  If it is will it allow an ios application to connect directly to an AD FS both 2016 and 2019 or maybe even just 2019?

**Comment by kaisong1990** [comment]
@peterveeva Thanks for reaching out, we will support for just 2019, but no ETA yet
