### ISSUE TITLE
MSAL Intune MDM flow re-asks for user relogin even if is already logged in

### ISSUE THREAD

**Issue by eldimious** [AzureAD/microsoft-authentication-library-for-objc#1355]
Hey we are facing issues when we are using MSAL, and try to install ipa via intune into MDM devices. While the user is logged-in it keeps reasks for relogin. Although when we get the build from testflight in not managed devices the flow is working properly. In our current implementation we have a method called loginUser which makes the following steps:

1. creates MSALPublicClientApplication
2. tries to find logged in account using `applicationContext.getCurrentAccount` or `applicationContext.account(forIdentifier: id)` (have tried both of them)
3. If account != nil calls acquireTokenSilent to get new token silently: `.acquireTokenSilent(with: parameters) { result, error in`
4. If account == nil call acquireToken to re-login user

We have set webViewParamaters.webviewType = .authenticationSession

 From my understanding, while i am able to acquire initially a token, when call these methods - we call it before make request to protected API endpoints - the returned MSALAccount is nil

Do you have any idea what is going wrong? Is something related to MDM+intune, cause when we install it via testflight in our devices seems is working properly?

Btw i have attached below a snapshot of our login flow
[LoginTestFlow.swift.zip](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/6907222/LoginTestFlow.swift.zip)

**Comment by kaisong1990** [comment]
@eldimious Thanks for your question, the setup looks good to me. Did you get errors before prompting for relogin? CorrelationId would be helpful from the error response

**Comment by eldimious** [comment]
Hey @kaisong1990 thanks for reaching me. I think the issue is related to re-resign the app before we push it to intunes. So the flow is that we resign the app before we push it to testflight, and then we re-resign the .ipa with another cert to push the ipa to intune for MDM distribution.
From managed devices i found the below error:
```Error Domain=NSOSStatusErrorDomain Code=-34018 "Client explicitly specifies access group qqqqq.wwwww.eeeee.rrrrr.tttt but is only entitled for (    "qqqqq.*",
"qqqqq.*",
"com.apple.token"
)" UserInfo={numberOfErrorsDeep=0, NSDescription=Client explicitly specifies access group qqqqq.wwwww.eeeee.rrrrr.tttt but is only entitled for (
"qqqqq.*",
"qqqqq.*",
"com.apple.token"
)}
```

**Comment by kaisong1990** [comment]
Looks like the certificate is massed up during resign? I would suggest to reach out to Intune repo regarding signing certificate question [here](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios)
