### ISSUE TITLE
MSAL silent token acquisition doesn't have an interface to add extra parameters

### ISSUE THREAD

**Issue by InesCarton** [AzureAD/microsoft-authentication-library-for-objc#1356]
I need to pass extra parameters to the silent token acquisition to be added to the body of the request so that it can be passed to our custom API so that extra information about the user account can be returned to the client. 

This is possible in the .Net library but there is no interface in objective C for this functionality.

**Comment by kaisong1990** [comment]
Hi @InesCarton Thanks for reaching out.

The ```extraQueryParameters``` in interactive call API is only for /auth not for /token endpoint. For security reasons, we are not exposing extra param for /token during both silent and interactive call.

Could you provide a bit more details in your scenarios? Is it for B2C?

**Comment by InesCarton** [comment]
Hello @kaisong1990 

We have some custom logic which is invoked after the first interactive sign in. We use the silent token acquisition with force refresh to get updated information from the server, but we need to tell the server somehow which block of data we want to retrieve. We then want to use the token containing the data for other services.

For example, imagine that we have a database where a specific user has 3 entries of data. We need to tell the server which of the 3 we want to know about and get it back as part of the token so that we can provide it to other services.

Do you have any other way to do this? If we were to contribute to the library, would this be accepted or should we have our own fork?

Thanks for the help.

**Comment by jasoncoolmax** [comment]
May I know what kind of extra query parameters you want to pass?
Currently MSAL provides the option to pass claims challenge to server: https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/dev/MSAL/src/public/MSALClaimsRequest.h

**Comment by InesCarton** [comment]
@jasoncoolmax  We need to pass an id, which will be then from b2c forwarded to our custom api. And our custom api then will assign a value to our custom claim. Are the claims request passed to the custom API?

**Comment by InesCarton** [comment]
@jasoncoolmax Basically we need to pass an ID to our custom API and then we return information related to that ID as part of the token.
