### ISSUE TITLE
microsoft-authentication-library-for-objc Returning Account name as nil

### ISSUE THREAD

**Issue by alexxxx12** [AzureAD/microsoft-authentication-library-for-objc#1357]
Hi Team,
We are in the middle of integrating the Microsoft-authentication-library with our Enterprise App, but the ios app is returning current and previous Accounts as nil. Even though we have installed Microsoft Authenticator and other Microsoft Apps are working fine.

Here are details of the environment: Version 12.5 (12E262)
MSAL Package using: Swift Dependency Manager.
let me know if you need further information .love to provide the sample code we are using, even though it's primarily derived from your sample code provided.
thanks.

![unnamed](https://user-images.githubusercontent.com/47609413/128330269-60dbaa4b-3651-4e66-a361-373f894babe8.png)

**Comment by kaisong1990** [comment]
@alexxxx12 Could you provide more info? Did you not get any account, or you were able to get account, but account name is nil?

Also, the screenshot shows as sign out page, so not sure which steps you were in.

Make sure your app has correct setup by following [here](https://github.com/AzureAD/microsoft-authentication-library-for-objc)

**Comment by alexxxx12** [comment]
Hi Kai,  
No, we do not see any account(current and previous); the sign-out button is only active after installing the Microsoft Authenticator app, which is weird. I have also added the sample code (but I need to remove all the identifiers due to privacy and code protection)
We have opened an internal ticket with a Microsoft Azure team as well.

[AzureAD.zip](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/6994193/AzureAD.zip)

**Comment by kaisong1990** [comment]
@alexxxx12 As discussed today, the current account is the account you have signed in to the current app, not the account which was signed in to other applications (eg Outlook.Teams). You will need to call acquire token interactively first.

Closing this for now and feel free to reopen for other questions
