### ISSUE TITLE
Question: "acquireTokenSilent" results in error "AADB2C90088"

### ISSUE THREAD

**Issue by KarinBerg** [AzureAD/microsoft-authentication-library-for-objc#1358]
Question about method "acquireTokenSilent" on class "MSALPublicClientApplication"

I call the method acquireTokenSilent with an account of the policy "B2C_1_sign-up".

`
let silentParameters = MSALSilentTokenParameters(scopes: kScopes, account: account)
application.acquireTokenSilent(with: silentParameters)
`

This results in the following error.

**Printing description of error:**
Error Domain=MSALErrorDomain Code=-50002 "(null)" UserInfo={MSALErrorDescriptionKey=User interaction is required, MSALOAuthErrorKey=invalid_grant, MSALCorrelationIDKey=E746DDC9-4C33-48C4-8A63-2F696F5F98F7, NSUnderlyingError=0x280c233f0 {Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=**AADB2C90088: The provided grant has not been issued for this endpoint. Actual Value : B2C_1_sign-in and Expected Value : B2C_1_sign-up**
Correlation ID: 1abb2656-7899-4707-870e-3f2ad0460e78
Timestamp: 2021-08-06 15:17:34Z
, MSALOAuthErrorKey=invalid_grant, MSALCorrelationIDKey=E746DDC9-4C33-48C4-8A63-2F696F5F98F7, MSALInternalErrorCodeKey=-42004}}}

I assume that the B2C server is expecting a policy of "B2C_1_sign-in" or "B2C_1_sign-in-sign-up" to silently login the user. So a call with a "sign-up" policy will not work, right?

Can you confirm that?
Btw. I thing the values are swapped in sentence "Actual Value : B2C_1_sign-in and Expected Value : B2C_1_sign-up". Actual Value should be "B2C_1_sign-up".

_Background story:_
Why I'm calling acquireTokenSilent with an sign-up policy?
Because I do not use an "B2C_1_SignUpSignIn". I have in my app two buttons: one for sign in and one for sign up. If the user signs-up successfully he can use the app. As long as the app is not closed completely (e.g. via Task-Manager) everything works fine. But if the app ist starting after a completely termination I try to login the user silently. In this case I only have a sign-up account in the account cache, so I use this to do the silent login. But this is failing with the above error message, so the user has to log in again once after a registration.

**Comment by jasoncoolmax** [comment]
Yes, sign-up policy token can only be used for signup, not sign in. That's why you are seeing the error from server.
I guess the possible solution here is either use B2C_1_SignUpSignIn policy, or use signUp policy and signIn policy together (which means you need to sign in after sign up).
