### ISSUE TITLE
Webview - solve authentication challenge

### ISSUE THREAD

**Issue by andreiChis70** [AzureAD/microsoft-authentication-library-for-objc#1371]
**Question**
I have to provide a user and password in order to access a page. (using custom policy)
Is there a way to override `didReceiveAuthenticationChallenge` and use a `URLCredential` in order to access the specific page?

**What I have tried?**
I've tried using a custom webview and listening to `didReceiveAuthenticationChallenge` but the webview doesn't show on screen and it doesn't call it's delegate in my object.

```
customWebView = WKWebView(frame: UIScreen.main.bounds)
customWebView?.navigationDelegate = self
let webViewParameters = MSALWebviewParameters(authPresentationViewController: viewController)
webViewParameters.webviewType = .wkWebView
webViewParameters.customWebview = customWebView

let parameters = MSALInteractiveTokenParameters(scopes: Constants.kScopes,
                                                        webviewParameters: webViewParameters)
...
```

Best regards,
Andrei

**Comment by ameyapat** [comment]
Hi @andreiChis70, even if you pass your custom webview , we override this method to handle oauth challenges and passing your URLCredential won't work.
