### ISSUE TITLE
User does not get option to login when selecting "Have an admin account?" during auth

### ISSUE THREAD

**Issue by guidedways** [AzureAD/microsoft-authentication-library-for-objc#1385]
Please have a look at these side by side screenshots from App A (some other app) on the left and our app on the right during a regular authentication attempt. 

![Screenshot 2021-09-23 at 12 20 23](https://user-images.githubusercontent.com/202437/134475831-4cd9dfb4-1b7e-4d29-94eb-64330889824a.png)

When the user gets such a prompt, they click on "Have an admin account? Sign in with that account" but the next screen does not allow them to sign into an account of their choosing when they use our app (we're using MSAL), whereas they get a prompt to sign in from App A. 

![Screenshot 2021-09-23 at 12 20 28](https://user-images.githubusercontent.com/202437/134476193-189f5a44-9011-40a0-8ccc-1f902b29c635.png)

I have no idea why - I've looked at the various options available to us (for our macOS app) and I cannot see how to force the browser to show them the login option. Is there a special parameter we must pass? Also, not sure if App A is using MSAL but they seem to be opening it in a browser tab whereas our auth request opens in a separate window. 

This is what we're doing:

```
                  MSALWebviewParameters *webParams = [[MSALWebviewParameters alloc] init];
                  MSALInteractiveTokenParameters *parameters = [[MSALInteractiveTokenParameters alloc] initWithScopes:@[scope] webviewParameters:webParams];
                  
                  parameters.loginHint = loginHint;
                  parameters.promptType = MSALPromptTypePromptIfNecessary;
                  
[msalAppClient acquireTokenWithParameters:parameters completionBlock:^(MSALResult * _Nullable result, NSError * _Nullable error) {
...
}];
```

**Comment by Veena11** [comment]
Investigating

**Comment by guidedways** [comment]
Any news on this?

**Comment by guidedways** [comment]
That did not help
