### ISSUE TITLE
SSO not working Native App -> Safari

### ISSUE THREAD

**Issue by MaikoHermans** [AzureAD/microsoft-authentication-library-for-objc#1386]
We are working on the implementation of sso and trying to get it all to work correctly.
Right now we have a problem where it doesn't seem to recognise or send the needed cookies to the system.

So what we are doing is signing in on the app, with the default webmethod, so it should be `aswebauthenticationsession` then going to safari and trying to navigate to one of the webpages, however it will require authorisation again then.

The code we are using:
```
    init(from viewController: UIViewController?, with policy: B2CPolicy) {
        self.policy = policy
        kClientId = policy.clientId
        kTenantName = policy.tenantName
        kSignUpOrSignInPolicy = policy.policy
        kScopes = policy.scope
        kEndPoint = policy.endPoint
        
        fromViewController = viewController
        setLogging()
        
        do {
            let authority = try getAuthority(forPolicy: kSignUpOrSignInPolicy)
            let b2cConfiguration = MSALPublicClientApplicationConfig(clientId: kClientId, redirectUri: policy.returnURL, authority: authority)
            b2cConfiguration.knownAuthorities = [authority]
            applicationContext = try MSALPublicClientApplication(configuration: b2cConfiguration)
            initWebViewParams()
        } catch {
            print(error)
        }
    }

private func initWebViewParams() {
        guard let fromViewController = self.fromViewController else { return }
        webViewParameters = MSALWebviewParameters(authPresentationViewController: fromViewController)
    }
    
private func getAuthority(forPolicy policy: String) throws -> MSALB2CAuthority {
        guard let authorityURL = URL(string: String(format: kEndPoint, kTenantName, policy)) else {
                throw NSError(domain: "B2CLogin",
                     code: 1,
                     userInfo: ["errorDescription": "Unable to create authority URL!"])
                }
        return try MSALB2CAuthority(url: authorityURL)
}
```

I also grabbed the logs.

I noticed that there is an error saying that it isn't an b2c authority. I'm not sure what this is about and if this could be the cause of the issue in some way?

> MSAL log: Optional("TID=6905411 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:11 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] No cached preferred_network for authority")
MSAL log: Optional("TID=6905411 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:11 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Sending network request: (not-null), headers: (not-null)")
MSAL log: Optional("TID=6907001 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12] session:didReceiveChallenge:completionHandler - nsurlauthenticationmethodservertrust. Host: x.b2clogin.com. Previous challenge failure count: 0")
2021-09-23 15:09:12.160177+0200 x Acc[33797:6907001] [connection] nw_endpoint_handler_set_adaptive_read_handler [C1.1 20.190.160.129:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: utun6, ipv4, dns)] unregister notification for read_timeout failed
2021-09-23 15:09:12.161215+0200 x Acc[33797:6907001] [connection] nw_endpoint_handler_set_adaptive_write_handler [C1.1 20.190.160.129:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: utun6, ipv4, dns)] unregister notification for write_timeout failed
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Received network response: (not-null), error (null)")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12] Creating Error with description: It is not B2C authority.")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Parsed response: (not-null), error (null), error domain: (null), error code: 0")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12] Stop background task with type 0")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Validate and save token response...")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] Token extraction. Attempt to extract the data from the server response.")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] Missing correlation id - No correlation id received for request with correlation id: 11D1BFE2-0201-4F07-87CB-942D3FA76C66")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12] Creating Error with description: It is not B2C authority.")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12] Enrollment id read from intune cache : (null).")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12] Creating Error with description: It is not B2C authority.")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12] Creating Error with description: It is not B2C authority.")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12] Creating Error with description: It is not B2C authority.")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12] Creating Error with description: It is not B2C authority.")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Get keychain items, key info (account: Masked(not-null) service: fae8b6fd-d19e-40b7-a3e6-e53bac946658 generic: (null) type: 5001, keychainGroup: adal keychain group)")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Trying to find keychain items...")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Keychain find status: 0")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Found 1 items.")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Saving token response, only save SSO state 0")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] (Default accessor) Saving multi resource refresh token")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12] Creating Error with description: It is not B2C authority.")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12] Enrollment id read from intune cache : (null).")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] (Default cache) Removing credentials with type AccessToken, environment x.b2clogin.com, realm /x.onmicrosoft.com/B2C_1A_signup_signin-mfa, clientID fae8b6fd-d19e-40b7-a3e6-e53bac946658, unique user ID e22d6657, target https://x.onmicrosoft.com/accapi/read")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] (MSIDAccountCredentialCache) retrieving cached credentials using credential query")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Get keychain items, key info (account: Masked(not-null) service: (null) generic: {length = 103, bytes = 0x61636365 7373746f 6b656e2d 66616538 ... 676e696e 2d6d6661 } type: 2001, keychainGroup: adal keychain group)")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Trying to find keychain items...")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Keychain find status: 0")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Found 1 items.")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] (MSIDAccountCredentialCache) retrieved 1 cached credentials")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] (MSIDAccountCredentialCache) credential query requires exact match with the cached credential items. Performing additional filtering checks.")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] (MSIDAccountCredentialCache) performing filtering check on cached credential item with the following properties - client ID: fae8b6fd-d19e-40b7-a3e6-e53bac946658, target: https://x.onmicrosoft.com/accapi/read, realm: /x.onmicrosoft.com/B2C_1A_signup_signin-mfa, environment: x.b2clogin.com, familyID: (null), homeAccountId: e22d6657, enrollmentId: Masked(null), appKey: Masked(null), applicationIdentifier: Masked(null), tokenType: (null)")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] (MSIDAccountCredentialCache) returning 1 filtered credentials")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] (Default cache) Removing multiple credentials")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] (Default cache) Removing credential Masked(not-null) for userID e22d6657 with environment x.b2clogin.com, realm /x.onmicrosoft.com/B2C_1A_signup_signin-mfa, clientID fae8b6fd-d19e-40b7-a3e6-e53bac946658,")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Remove keychain items, key info (account: Masked(not-null) service: accesstoken-fae8b6fd-d19e-40b7-a3e6-e53bac946658-/x.onmicrosoft.com/b2c_1a_signup_signin-mfa-https://x.onmicrosoft.com/accapi/read, keychainGroup: adal keychain group)")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Trying to delete keychain items...")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Keychain delete status: 0")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] (Default cache) Saving token Masked(not-null) for userID e22d6657 with environment x.b2clogin.com, realm /x.onmicrosoft.com/B2C_1A_signup_signin-mfa, clientID fae8b6fd-d19e-40b7-a3e6-e53bac946658,")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Saving keychain item, item info Masked(not-null)")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Set keychain item, key info (account: Masked(not-null) service: accesstoken-fae8b6fd-d19e-40b7-a3e6-e53bac946658-/x.onmicrosoft.com/b2c_1a_signup_signin-mfa-https://x.onmicrosoft.com/accapi/read, keychainGroup: adal keychain group)")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Trying to update keychain item...")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Keychain update status: -25300")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Trying to add keychain item...")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Keychain add status: 0")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12] Creating Error with description: It is not B2C authority.")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] (Default cache) Saving token Masked(not-null) for userID e22d6657 with environment x.b2clogin.com, realm /x.onmicrosoft.com/B2C_1A_signup_signin-mfa, clientID fae8b6fd-d19e-40b7-a3e6-e53bac946658,")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Saving keychain item, item info Masked(not-null)")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Set keychain item, key info (account: Masked(not-null) service: idtoken-fae8b6fd-d19e-40b7-a3e6-e53bac946658-/x.onmicrosoft.com/b2c_1a_signup_signin-mfa-, keychainGroup: adal keychain group)")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Trying to update keychain item...")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Keychain update status: -25300")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Trying to add keychain item...")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Keychain add status: 0")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] (Default accessor) Saving SSO state")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12] Creating Error with description: It is not B2C authority.")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] (Default cache) Saving token Masked(not-null) for userID e22d6657 with environment x.b2clogin.com, realm (null), clientID fae8b6fd-d19e-40b7-a3e6-e53bac946658,")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Saving keychain item, item info Masked(not-null)")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Set keychain item, key info (account: Masked(not-null) service: refreshtoken-fae8b6fd-d19e-40b7-a3e6-e53bac946658--, keychainGroup: adal keychain group)")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Trying to update keychain item...")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Keychain update status: -25300")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Trying to add keychain item...")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Keychain add status: 0")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12] Creating Error with description: It is not B2C authority.")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Saving app\'s metadata Masked(not-null)")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Saving keychain item, item info (clientId=fae8b6fd-d19e-40b7-a3e6-e53bac946658 environment=x.b2clogin.com familyId=)")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Set keychain item, key info (account: Masked(not-null) service: appmetadata-fae8b6fd-d19e-40b7-a3e6-e53bac946658, keychainGroup: adal keychain group)")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Trying to update keychain item...")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Keychain update status: 0")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12] Creating Error with description: It is not B2C authority.")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] (Default cache) Saving account Masked(not-null)")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Get keychain items, key info (account: Masked(not-null) service: /x.onmicrosoft.com/b2c_1a_signup_signin-mfa generic: (null) type: 1003, keychainGroup: adal keychain group)")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Trying to find keychain items...")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Keychain find status: 0")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Found 1 items.")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Saving keychain item, item info Masked(not-null)")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Set keychain item, key info (account: Masked(not-null) service: /x.onmicrosoft.com/b2c_1a_signup_signin-mfa, keychainGroup: adal keychain group)")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Trying to update keychain item...")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Keychain update status: 0")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Saved token response successfully.")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Interactive flow finished. Result (not-null), error: 0 error domain: (null)")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Saving keychain item, item info <MSIDThrottlingMetaData: 0x2801d4d80>")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Set keychain item, key info (account: Masked(not-null) service: Ver1, keychainGroup: adal keychain group)")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Trying to update keychain item...")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] Keychain update status: 0")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12] Creating Error with description: It is not B2C authority.")
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12] Parsing result access token")
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IkRyVnJwbHpicExJbkk5Zk9qb2hucC1FZnAzRW5LT0ZNMmhMZXk4S2ZIZTQifQ.eyJpc3MiOiJodHRwczovL2FjY2xlZGVudnZhYS5iMmNsb2dpbi5jb20vOTc1NmQ4NTQtMmUzMi00Mjc3LTg4YWItNWE4ZWI1M2JiZWU5L3YyLjAvIiwiZXhwIjoxNjMyNDA2MTUyLCJuYmYiOjE2MzI0MDI1NTIsImF1ZCI6ImU4ZmQ1MmIyLWM5ZGMtNDVjOC04MDliLTM5ODU5YWUzNzVmYiIsInN1YiI6ImRkNGE1Zjk5LTk1NWQtNDZkZi1hM2UzLTNjMWIyNGQ4NDA1ZSIsIm5hbWUiOiJUZXN0VXNlciAyMjc5OTEiLCJnaXZlbl9uYW1lIjoiVGVzdCBVc2VyIiwiZmFtaWx5X25hbWUiOiJHZWJydWlrZXIgVE1DIiwiZXh0ZW5zaW9uX25vbWZhIjpmYWxzZSwid2luZG93c2FjY291bnRuYW1lIjoiMjI3OTkxIiwidXNlclByaW5jaXBhbE5hbWUiOiJkZDRhNWY5OS05NTVkLTQ2ZGYtYTNlMy0zYzFiMjRkODQwNWVAYWNjbGVkZW52dmFhLm9ubWljcm9zb2Z0LmNvbSIsImVtYWlsIjoiMjI3OTkxQHZ2YWEubmwiLCJ2cGFjY291bnQiOiIyMjc5OTFAdnAudnZhYS5ubCIsInRpZCI6Ijk3NTZkODU0LTJlMzItNDI3Ny04OGFiLTVhOGViNTNiYmVlOSIsInNjcCI6InJlYWQiLCJhenAiOiJmYWU4YjZmZC1kMTllLTQwYjctYTNlNi1lNTNiYWM5NDY2NTgiLCJ2ZXIiOiIxLjAiLCJpYXQiOjE2MzI0MDI1NTJ9.hFyOL5psV6R6uYW4M4BgveRPjVaxWpK-2_zd7oUPXrNIqj7CZLlph1WUwMzZwLi9LTrZ97sUiI9zANNeWRxdl-nKOSGV0g3o_n-iHHTFTlDiC79087wpBM4RYk9SF9gYN2cwD2FSS3-r8AfHq4jVs4ji687rd2QgT_0jp6UDA15_nN5T-rs5lNJOMnQBLdJOCHbfiJfuAN88jx0AP8cKQa72rdfiXEslhlIiOc0XhjRBdFFdB-GKvEjH1h5qV-4UCCLC57QzkMtJ6c1-nHZUJ34XweppwmGXifpG5sPim0LsPb6o_cBL4ny5ZIi4J6LMmEEkL-LSm9chC0q-ehXdBQ
MSAL log: Optional("TID=6906994 MSAL 1.1.22 iOS 14.7.1 [2021-09-23 13:09:12 - 11D1BFE2-0201-4F07-87CB-942D3FA76C66] [MSAL] acquireToken returning with at: d307644 scopes:(\n    \"https://x.onmicrosoft.com/accapi/read\"\n) expiration:2021-09-23 14:09:12 +0000")

**Comment by Veena11** [comment]
@MaikoHermans , could you please also provide network trace? 
Are you checking the check box that says keep me signed in ?
