### ISSUE TITLE
Please Provide some provision for Third Party Apps to customise the status bar light or dart content mode.

### ISSUE THREAD

**Issue by sehaswaran** [AzureAD/microsoft-authentication-library-for-objc#1410]
Hi Team

Third Party Apps who use your framework ,

calling the acquireToken, which presents the webview with your own navigation controller.

Problem:

Default navigation controller status bar style is black or darkContent.
But, Third Party Apps might support light and dark mode of content .

Please Provide some provision for Third Party Apps to customise the status bar

**Comment by jasoncoolmax** [comment]
Hi @sehaswaran, thank you for providing your input.
You can actually provide your own webview controller to MSAL, such that you have control of how it looks:
https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/master/MSAL/src/public/MSALInteractiveTokenParameters.h#L64 

Let me know if the above solves your issue. Thank you!

**Comment by sehaswaran** [comment]
Thanks @jasoncoolmax I will check
