### ISSUE TITLE
Please provide account deletion feature

### ISSUE THREAD

**Issue by ivanpnn** [AzureAD/microsoft-authentication-library-for-objc#1414]
Hello,

Corresponding to Apple rule : [https://developer.apple.com/news/?id=mdkbobfo](url)
I'm using MSAL pod in my apps. When logging in to OneDrive, in the application can create account from the SDK. 

Can MSAL support this Account Deletion feature since it's required by Apple?

Thank you in advance.

**Comment by jasoncoolmax** [comment]
@ivanpnn Sorry for the late reply.

May I know if you are handling AAD account or B2C account? Such that I can redirect the request to the right team.

**Comment by ivanpnn** [comment]
We're handling B2C account

**Comment by jasoncoolmax** [comment]
Let me ask internally and get back to you later.

**Comment by Veena11** [comment]
We are still checking internally, meanwhile could you check if a custom policy could be set to handle account deletion . https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-policy-overview

**Comment by ivanpnn** [comment]
I can't make sure that custom policy will be solve the account deletion policy. Because it's the Apple's reviewer role to decide it.
But, I can give an advise to you. If the effort to add User Deletion feature in your service is too high, maybe you can add disable User Creation feature in your service, just like in DropboxSDK. There is a function to disable User Creation feature in DropboxSDK.

**Comment by jasoncoolmax** [comment]
Thank you @ivanpnn for your patience during the holiday season.
We have reached the correct team. From what I heard, B2C does provide a custom policy to delete an account after creation. The deletion is using "AlternativeSecurityId". I am waiting for more guidance regarding how to do it.

**Comment by jasoncoolmax** [comment]
Our B2C team has come back with the following instruction:
https://github.com/azure-ad-b2c/samples/tree/master/policies/delete-my-account 

Let me know if that meets your needs.

**Comment by applidesign** [comment]
Hi @jasoncoolmax , thank you for your supports.
I've read the instruction, but I don't know about how to proceed the instruction into my project since the instruction is using xml and my project is in Objective-C.

Is there any instruction how to implement it in obj-c or swift?

**Comment by ivanpnn** [comment]
Hi @jasoncoolmax , thank you for your supports.
I've read the instruction, but I don't know about how to proceed the instruction into my project since the instruction is using xml and my project is in Objective-C.

Is there any instruction how to implement it in obj-c or swift?

**Comment by JasSuri** [comment]
Once you have setup the delete account policy as per the [sample](https://github.com/azure-ad-b2c/samples/tree/master/policies/delete-my-account), you will have to update the Authority in MSAL to point to the new AAD B2C policy Id. 

Then create a button in your application that executes MSAL with this authority. The user will then be taken through this Delete account B2C policy.

**Comment by jasoncoolmax** [comment]
Free free to reopen if issue remains.
