### ISSUE TITLE
MSAL is not safe for use in application extensions

### ISSUE THREAD

**Issue by artemisia-absynthium** [AzureAD/microsoft-authentication-library-for-objc#1418]
Hello,

I'm using MSAL in an app which has also a Widget extension where I need to make authenticated calls to refresh data, and since I started using MSAL from inside the widget I'm getting this warning:

```
linking against a dylib which is not safe for use in application extensions: /.../MSAL.framework/MSAL
```

So far nothing wrong has happened in this widget but I'm concerned that with time and/or changes, either in my app or in future MSAL updates, something wrong may start to happen since compatibility is not guaranteed in the first place.

Could it be possible to make the lib safe or, alternatively, release a separate module that's safe for application extensions?

Thank you very much!

**Comment by hieunguyenmsft** [comment]
Thanks for reporting it.
There are quite a few scenarios that we don't support running in app extension (you can search for places that call [MSIDAppExtensionUtil isExecutingInAppExtension], basically we will return early if MSAL is running in app extension). 
About the plan to release a separate module for that, I don't have any info yet. Let me just mark it as a new ask here.

**Comment by hieunguyenmsft** [comment]
Other apps that use MSAL in their extension doesn't see the warning. Can you follow suggestion in this link to see if it helps:
https://stackoverflow.com/questions/28652102/how-to-suppress-warning-linking-against-dylib-not-safe-for-use-in-application

**Comment by artemisia-absynthium** [comment]
Hi @hieunguyenmsft , thanks for pointing that out, I get the point now, anyway I don't feel comfortable in suppressing warnings so I will keep it.
Maybe you could file a feedback report to Apple though, for presenting the warning even if the unsafe code is properly isolated.
As for this issue, if I got it right and it's just a false positive, you can close it.
Thanks!

**Comment by hieunguyenmsft** [comment]
Issue resolved. Thanks for reporting.

**Comment by 3a4oT** [comment]
I faced with same issue `MSAL 1.2.13`
