### ISSUE TITLE
How to default internal web SSO only even if authenticator app exist

### ISSUE THREAD

**Issue by YoonLee** [AzureAD/microsoft-authentication-library-for-objc#1420]
Hi is there option for just having internal web SSO? InTunes authenticator app installed which jumps to that app each time, manually deleting displays internal web SSO. I would like to approach internal web SSO only. Any input on this? Thanks.

**Comment by hieunguyenmsft** [comment]
Could you give us more detail of your setup? With applications from Microsoft (e.g Teams, Outlook,...) and the Authenticator app is installed, the request will always reroute to Authenticator to handle auth. If app is developed by you, you can turn the broker flow on/off. 
Hope that helps.

**Comment by jasoncoolmax** [comment]
close due to no response. Feel free to reopen if more info is ready.

**Comment by YoonLee** [comment]
Our organization distributes inTune iPad (Outlook, Team, Authenticator, and Comp Portal preinstalled. 
I feel having authenticator app to do authenticate are high coupling,
- App need to go external Authenticator app space and return back is extra steps. Instead preferred for  internal authenticate.
- The iPad can be shared with other associates, and log out then log in jumping back and force app to other app is hassle.
- VPN is required to MSAL> SSO, but some remote associate disconnected VPN due to timeout session and by doing so Authenticator app caches for certain period (meaning can't log in or restart the authenticator app). Can't control Authenticator app clearing cache is big catch.

So my question is, is there option to be login internal web SSO even if existence of having Authenticator app?

**Comment by hieunguyenmsft** [comment]
Hi @YoonLee, thank you for your suggestions. IMHO, balancing between security compliance and ease of use really needs our attention here.
- Can you elaborate more about internal web SSO for my learning? I wonder if that's internal, how is the SSO session shared between apps that using ADAL/MSAL or not using our libs at all (and to the extension of system apps e.g Safari browser)? 
- Shared device flow: We design a new workflow for that scenario. I think we will release to GA soon ( I will check with my colleague who owns the feature).
- For any bug/suggestions on the Authenticator app, please suggest with the team directly using your app.
