### ISSUE TITLE
Errors: "No token matching arguments found in the cache"

### ISSUE THREAD

**Issue by guidedways** [AzureAD/microsoft-authentication-library-for-objc#1423]
We've got a few users that have recently reported that as they authenticate (successfully) they are immediately prompted with an error:

```
No token matching arguments found in the cache, user interaction is required
```

This usually means an interactive token request is required - however the problem is that this is what the user is doing. The interactive token request passes, and immediately when we invoke `acquireTokenSilentWithParameters`, it fails with this error.

What would be the cause of this? This is what I see in the logs:

```
Error Domain=MSALErrorDomain Code=-50002 "(null)" UserInfo={MSALErrorDescriptionKey=No token matching arguments found in the cache, user interaction is required, MSALCorrelationIDKey=EB20BFBE-8576-4F14-8A43-1832D78D2243}
```

**Comment by antrix1989** [comment]
@guidedways please capture MSAL logs and send them to sedemche@microsoft.com and I will take a look. Thanks!

**Comment by guidedways** [comment]
@antrix1989 thanks - I've tried capturing it but it seems it won't capture since we use a custom file logger and our customers don't know how to extract MSAL logs. The logs won't get captured in the normal stream we capture to disk.

I'm seeing more users report the same issue - not sure what's going on.

**Comment by guidedways** [comment]
Okay I found something - what does this mean?

```
default	09:10:49.472528+0530	secd	BusyCal[7654]/1#-1 LF=0 copy_matching Error Domain=NSOSStatusErrorDomain Code=-34018 "Client explicitly specifies access group com.busymac.busycal3.com.microsoft.identity.universalstorage but is only entitled for (
    "com.apple.token"
)" UserInfo={numberOfErrorsDeep=0, NSDescription=Client explicitly specifies access group com.XXXX.XXXX.com.microsoft.identity.universalstorage but is only entitled for (
    "com.apple.token"
)}
```

**Comment by antrix1989** [comment]
Seems "com.microsoft.identity.universalstorage" group wasn't added to the project Capabilities. See [here](https://github.com/AzureAD/microsoft-authentication-library-for-objc#configuring-msal).

**Comment by jasoncoolmax** [comment]
Feel free to reopen if issue remains.

**Comment by guidedways** [comment]
@jasoncoolmax this seems to be an ongoing issue, we are in fact using `com.microsoft.identity.universalstorage` - instead the user just told us that logging out of Office 365 on the Mac and logging back in fixed it in our app. What's going on?
