### ISSUE TITLE
After logging in to the iOS Native app using the MSAL SDK, open wkWebView, you need to log in again

### ISSUE THREAD

**Issue by slzButton** [AzureAD/microsoft-authentication-library-for-objc#1427]
title:After logging in to the iOS Native app using the MSAL SDK, open wkWebView, you need to log in again
标题：iOS native app使用MSAL sdk 登录后，打开wkwebview，还需要再次登录

Content:
The iOS app call
MSALPublicClientApplication
/ * *
Acquire a token for a provided parameters using interactive authentication.

@param  parameters Parameters used for interactive authentication.
@param  completionBlock The completion block that will be called when the authentication
flow completes, or encounters an error.
* /
- (void)acquireTokenWithParameters:(nonnull MSALInteractiveTokenParameters *)parameters
completionBlock:(nonnull MSALCompletionBlock)completionBlock;

After logging in to MSAL, wkWebView was used in the app to open the webpage requiring AAD authorization login, which still requires login to view the content.
We want this login state to be shared by other WKWebViews in the application after logging in to MSAL.
I tried to use the Edge browser to open this web page, and found that I could browse normally without a second login after LOGGING in to the Edge. I hope our app can also realize such operation mode.

内容：
iOS app 调用
MSALPublicClientApplication
/**
 Acquire a token for a provided parameters using interactive authentication.
 
 @param  parameters Parameters used for interactive authentication.
 @param  completionBlock The completion block that will be called when the authentication
 flow completes, or encounters an error.
 */
- (void)acquireTokenWithParameters:(nonnull MSALInteractiveTokenParameters *)parameters
                   completionBlock:(nonnull MSALCompletionBlock)completionBlock;
登录了MSAL后，又在app内使用wkwebview，打开了需要aad授权登录的网页， 这个网页依旧需要登录才能查看内容。
我们希望在登录MSAL后，应用中的其他wkwebview可以共享这个登录状态。
我尝试使用edge浏览器打开这个网页，发现可以在我登录edge后不需要二次登录就能正常浏览，我希望我们的app也能实现这样的操作方式。

**Comment by mipetriu** [comment]
@slzButton I responded in the sample repo earlier, copying here if you'd prefer to discuss here:

Apologies for the delayed response. The MSAL library is designed to authenticate users in order for apps to receive tokens and use to access specific cloud resources within the app. MSAL cannot directly pass tokens to a browser to sign in users within the browser.

I recommend that you look into using a system browser such as ASWebAuthenticationSession when acquiring a token with MSAL. System browsers can share cookies with Safari browsers, and that may help you achieve the scenario you're looking for. More information on system browsers and how to use them with MSAL is [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/customize-webviews).

**Comment by jasoncoolmax** [comment]
Feel free to reopen it if the issue remains.
