### ISSUE TITLE
Can I use MSALWebviewParameters within SwiftUI or do I have to use UIKit?

### ISSUE THREAD

**Issue by arbyruns** [AzureAD/microsoft-authentication-library-for-objc#1428]
I'm attempting to authenticate using MSAL and SwiftUI and I can successfully get this to work with the code below when I call MyMSFTLogin(), but I'm left with designing the login within UIKit. However, I'd like to wrap the Sign In portion completely within a SwiftUI button. 

Here's what I got to work

    class MSFTLoginController: UIViewController {
    
        override func viewDidLoad() {
            super.viewDidLoad()
        }
    
        override func viewWillAppear(_ animated: Bool) {
            super.viewWillAppear(animated)
    
            let button = UIButton(frame: CGRect(x: 20, y: self.view.frame.height - 100, width: self.view.frame.width - 40, height: 52))
            button.backgroundColor = .orange
            button.setTitle("Login", for: .normal)
            button.setTitleColor(.white, for: .normal)
            button.addTarget(self, action: #selector(buttonTapped), for: .touchUpInside)
    
            self.view.addSubview(button)
        }
    
        @objc func buttonTapped(_ sender: UIButton) {
    
            let kClientID = "REDACTED"
            let kRedirectUri = "msauth.com.arby.MSALSwiftUISample://auth"
    
            do {
                let authority = try MSALB2CAuthority(url: URL(string: "https://login.microsoftonline.com/common")!)
                let msaConfig = MSALPublicClientApplicationConfig(clientId: kClientID, redirectUri: kRedirectUri, authority: authority)
    
                let application = try MSALPublicClientApplication(configuration: msaConfig)
                let webViewParameters = MSALWebviewParameters(authPresentationViewController: self)
                let interactiveParameters = MSALInteractiveTokenParameters(scopes: ["user.read"], webviewParameters: webViewParameters)
    
                application.acquireToken(with: interactiveParameters) { (result, error) in
                    guard let result = result else {
                        print("error \(String(describing: error?.localizedDescription))")
                        return
                    }
                    if let account = result.account.username {
                        print("account \(account)")
                        UIApplication.shared.windows.first {
                            $0.isKeyWindow
                        }!.rootViewController = UIHostingController(rootView: ContentView())
                    }
                }
            } catch {
                 print(error)
            }
        }
    }

 

    struct MyMSFTLogin: UIViewControllerRepresentable {
        typealias UIViewControllerType = MSFTLoginController
    
        func makeUIViewController(context: UIViewControllerRepresentableContext<MyMSFTLogin>) -> MSFTLoginController {
            return MSFTLoginController()
        }
        func updateUIViewController(_ uiViewController: MSFTLoginController, context: Context) {
    
        }
    }

I'm finding that I'm not able to login when I call `authViewModel.signInMSAL()`. I get the error `Optional("The operation couldn’t be completed. (MSALErrorDomain error -50000.)")` and that's because I'm not getting `MSALWebviewParameters(authPresentationViewController: self)` to present the MSAL signin screen or at least that's my guess.

    class AuthViewModel: UIViewController, ObservableObject {
    
        func signInMSAL() {
            let kClientID = "REDACTED"
            let kRedirectUri = "msauth.com.arby.MSALSwiftUISample://auth"
    
            do {
                let authority = try MSALB2CAuthority(url: URL(string: "https://login.microsoftonline.com/common")!)
                let msaConfig = MSALPublicClientApplicationConfig(clientId: kClientID, redirectUri: kRedirectUri, authority: authority)
    
                let application = try MSALPublicClientApplication(configuration: msaConfig)
                let webViewParameters = MSALWebviewParameters(authPresentationViewController: self)
                let interactiveParameters = MSALInteractiveTokenParameters(scopes: ["user.read"], webviewParameters: webViewParameters)
    
                application.acquireToken(with: interactiveParameters) { (result, error) in
    
                    guard let result = result else {
                        print("error \(String(describing: error?.localizedDescription))")
                        return
                    }
    
                    if let account = result.account.username {
                        print("account \(account)")
                        UIApplication.shared.windows.first {
                            $0.isKeyWindow
                        }!.rootViewController = UIHostingController(rootView: ContentView())
                    }
    
                }
            } catch {
                 print(error)
            }
        }
    }

Here's the SwiftUI part of the code.

        var body: some View {
            VStack {
                Button(action: {
                    showLogin = true
                    authViewModel.signInMSAL() <== this is ideally what I would like and that fails.
                }) {
                    Text("Sign In")
                }
            }
            .sheet(isPresented: $showLogin) {
                MyMSFTLogin() <== this works
            }
        }
    }

**Comment by kaisong1990** [comment]
In your 1st implementation, the button is within the view. The view has to be presented first and lives in window hierarchy before clicking to sign in.

In the 2nd implementation, MSAL lib is wrapped into a VC class, but the VC is never presented based on the last part of the code
