### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by dsonigara** [AzureAD/microsoft-authentication-library-for-objc#1430]
Hello

I am using MSAL and API. When I login with Microsoft I got an "access token". This access token I am using in other API calls. After some time token is expired. How to refresh the token? Please help me as soon as possible

Thanks

**Comment by ameyapat** [comment]
Hi @dsonigara, when an access token expires, a new access token needs to be requested using a refresh token. YOu can read about access tokens here : https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens and refresh tokens here : https://docs.microsoft.com/en-us/azure/active-directory/develop/refresh-tokens

Using MSAL you can silently update token as stated here : https://github.com/AzureAD/microsoft-authentication-library-for-objc#objective-c-5

**Comment by jasoncoolmax** [comment]
Feel free to reopen if the issue remains.
