### ISSUE TITLE
MSALErrorDescriptionKey=The required app scheme $(PRODUCT_BUNDLE_IDENTIFIER) is not registered even after being set.

### ISSUE THREAD

**Issue by arbyruns** [AzureAD/microsoft-authentication-library-for-objc#1431]
I'm getting back an error that `msauth.$(PRODUCT_BUNDLE_IDENTIFIER)` is not registered in the app's info.plist file, but I can see that I registered it here.

![image](https://user-images.githubusercontent.com/2520545/148787647-cfeb7633-1d30-41aa-ba70-6cbf7209d0d2.png)
I can also see that my redirectURi is set properly.  Is there somewhere else within the info.plist I need to set this value?

```
Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=The required app scheme "msauth.com.arby.MSAL-SwiftUI" is not registered in the app's info.plist file. Please add "msauth.com.arby.MSAL-SwiftUI" into Info.plist under CFBundleURLSchemes without any whitespaces and make sure that redirectURi "msauth.com.arby.MSAL-SwiftUI://auth" is register in the portal for your app., MSALInternalErrorCodeKey=-42001}
```

**Comment by arbyruns** [comment]
Ah I see what I did wrong now.

**Comment by AC40** [comment]
Could you tell me what you did wrong? I am having exactly the same issue, and can't find a solution. Thanks in advance.

**Comment by idelfonsog2** [comment]
Same here @arbyruns could you elaborate on your solution ?
