### ISSUE TITLE
[Question] Method to retrieve authorization code

### ISSUE THREAD

**Issue by deste91** [AzureAD/microsoft-authentication-library-for-objc#1434]
Hi,
I know this was already asked but I need to know if there is a chance to have this in the future.
For an account linking flow we need an authorization code from Azure B2C to be passed to a third party provider. It would be possible to have a method on MSAL library to retrieve an authorization code instead of an access token in order to send this code to backend?

**Comment by jasoncoolmax** [comment]
Hi @deste91 , currently our library is not supporting auth code returning. May I know which flow you are actually working on? Such that I can take a closer look.

**Comment by deste91** [comment]
Thanks @jasoncoolmax . Basically we need auth code to complete this account linking to an Alexa skill: [https://developer.amazon.com/en-US/docs/alexa/account-linking/app-to-app-account-linking-starting-from-your-app.html#how-it-works
](url)
Amazon needs the authorization code to detach an access token and a refresh token on behalf of the user, and we are investigating if the mobile app could retrieve it using MSAL (that we are currently using to authenticate the user), since Azure B2C does not allow us to retrieve it directly from our backend.

**Comment by jasoncoolmax** [comment]
Thank you for the link. Now I know better about the flow you are implementing. Currently, MSAL doesn't support returning auth code.

**Comment by VladIacobIonut** [comment]
Hey @deste91,

We are having the exact same issue on our side. Did you find a temporary workaround to retrieve the auth code for Alexa's A2AAL? We are currently facing a blocker because of this.

Thanks.

**Comment by mikeyyyzhao** [comment]
Same issue here, @deste91 @VladIacobIonut have you guys found a workaround?
