### ISSUE TITLE
Not getting a 2.0 token using acquireToken

### ISSUE THREAD

**Issue by mlynch** [AzureAD/microsoft-authentication-library-for-objc#1446]
When using `application.acquireToken` API, we are getting back an access token that is version 1.0 and one that has an incorrect `aud` field that is not the client id. We need to get a 2.0 token that has the client id in the `aud` field. How can we ensure we get this token format back when using this API? The id token is correctly returning as a 2.0 token.

In the below example, `scopes` is `["https://graph.microsoft.com/.default"]`	

```swift
if (interactive) {
    let interactiveParameters = MSALInteractiveTokenParameters(scopes: scopes, webviewParameters: webviewParameters)
    application.acquireToken(with: interactiveParameters, completionBlock: completionBlock)
} else {
    guard let account = try? application.account(forUsername: upn!) else {
        call.reject("Unable to find account to refresh, must call acquireToken for interactive flow")
        return
    }
    let silentParameters = MSALSilentTokenParameters(scopes: scopes, account: account)
    application.acquireTokenSilent(with: silentParameters, completionBlock: completionBlock)
}
```

**Comment by ameyapat** [comment]
Hi @mlynch , for 2.0 access tokens you will have to configure it as such in app manifest of your App registration in Azure portal. Here is the doc on how to do it : https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-app-manifest#accesstokenacceptedversion-attribute

**Comment by mlynch** [comment]
Okay thank you, will give that a shot and see if it works for what we need!
