### ISSUE TITLE
Is there a way to use Login keychain instead of Local Items/iCloud in MSALPublicClientApplication?

### ISSUE THREAD

**Issue by crosshawk** [AzureAD/microsoft-authentication-library-for-objc#1447]
Hello all. We are seeing an issue with our application where some users that have the Local Items keychain locked/corrupted cannot store their credentials, which is normal. However, they seem to have other applications, like MS Office and Chrome that work fine, even though the Local Items keychain is locked, as they use the Login keychain.
So the question is, can we somehow through the code when we setup the MSALPublicClientApplication pass a config to specify the keychain we want to use instead of always using Local Items/iCloud which could be locked?

**Comment by ameyapat** [comment]
Hi @crosshawk , we use keychain to store tokens and not credentials. Are you looking for a configuration to store tokens in Login keychain?

**Comment by crosshawk** [comment]
Sorry @ameyapat , you are right, what I wrote was wrong. We store tokens, not credentials.
Yes we are looking for a configuration to store tokens in Login keychain (which if I understand correctly it should always be unlocked when a user is logged in to their Mac, so there is a smaller possibility that MSAL won't be able to store tokens).

**Comment by crosshawk** [comment]
Hi @ameyapat or anyone else who might know, so is it possible to use the Login keychain instead of the Local Items one?

**Comment by ameyapat** [comment]
Hi @crosshawk, we are moving towards using iOS style keychain on mac as it is Apple's recommendation. Office is using our ADAL library that uses ACL but in the near future it will also shift to use ios style keychain. 
Sorry, we won't be supporting to use Login keychain as it is Apple's recommendation to use iOS style keychain.
