### ISSUE TITLE
MSAL fails to compile on macOS with Xcode 13.2.1 .

### ISSUE THREAD

**Issue by ArikShtineL** [AzureAD/microsoft-authentication-library-for-objc#1453]
Hi!

I am using MSAL 1.2.0, macOS(Rosetta) 12.1.
When I try to build macOS app with `macos-arm64_x86_64` I get the following:

Warning:
```
warning: Couldn't resolve framework symlink for '${CODESIGNING_FOLDER_PATH}/msal-ios-sdk/MSAL.xcframework/macos-arm64_x86_64/MSAL.framework/Versions/Current': readlink(${CODESIGNING_FOLDER_PATH}/msal-ios-sdk/MSAL.xcframework/macos-arm64_x86_64/MSAL.framework/Versions/Current): Invalid argument (22) (in target 'XXXX' from project 'XXXX')
```

And error:
```
CodeSign /{CODESIGNING_FOLDER_PATH}/xxxxx.app (in target 'xxxx' from project 'xxxxx')
    cd /{CODESIGNING_FOLDER_PATH}/xxxxx
    export CODESIGN_ALLOCATE\=/Applications/Xcode_13.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    
    Signing Identity:     "Apple Development: XXXXX (XXXXXXXX)"
    Provisioning Profile: "Mac Team Provisioning Profile: XXXXXXX"
                          (XXXXXXXXXXXXXXXXXXXXXXXXXXX)
    
    /usr/bin/codesign --force --sign XXXXXXXXXXXXXXXX -o runtime --entitlements /{CODESIGNING_FOLDER_PATH}/XXXXXX.app.xcent --timestamp\=none --generate-entitlement-der /{CODESIGNING_FOLDER_PATH}/XXXXXXX.app

/{CODESIGNING_FOLDER_PATH}/XXXXXXXXXXX.app: code object is not signed at all
In subcomponent: /{CODESIGNING_FOLDER_PATH}XXXXXXXX.app/Contents/Frameworks/MSAL.framework
```

I check with other similar framework and I see that there are files where there should be symlinks:
Current->Versions/A
Headers->  Versions/Current/Headers
MSAL -> Versions/Current/MSAL
Modules -> Versions/Current/Modules
Resources -> Versions/Current/Resources

After I create symbolic links the project builds successfully! 

From looking at the release script I think that the zip is missing `--symlinks` flag.

**Comment by kaisong1990** [comment]
@ArikShtineL Thanks for your question, could you provide how to use MSAL SDK as a dependency in your project? Like SPM, Cocoapod or something else?

**Comment by ArikShtineL** [comment]
We add the xcframework manual to the target. @kaisong1990

**Comment by kaisong1990** [comment]
Thanks for the update, we will look into it

**Comment by ameyapat** [comment]
1.2.1 is released and contains the fix for this. The symlinks are preserved in the package and codesigning shouldn't fail now.
