### ISSUE TITLE
MSAL Library is still fetching tokens without MFA enable

### ISSUE THREAD

**Issue by idelfonsog2** [AzureAD/microsoft-authentication-library-for-objc#1457]
I have a native mobile app (iOS & Android) in which I'm trying to enable the MFA or Broker Based Authentication in the MSAL Library. (I also have the Azure app registered, per the documentation) I have noticed the following scenarios:

```gherkin
Given the device "does not have" the broker based application installed
When the user tries to login within my application 
And the application displays the Safari views to authenticate with AD (company)
Then the user is prompted for username and password
And the user is given an "Access Token" 
```

We **don't want** the the access token to be given if the user did not went through MFA or Broken based authentication
And we want to be able to catch that as an error/exception or if the API is able to fetch that

```gherkin
Given the device "does have" the broker based application (MS Authenticator) installed and logged in
When the user tries to login within my application 
Then my application will make a round trip to the broker based application
And the user will be given an "Access Token" 
```
The above scenario works, which is only if the end employee has the broker base application installed

In both case scenarios the cloud-based Azure application is not logging any activity for this user and the authentication and login they just did

**Comment by jasoncoolmax** [comment]
First, if you want users to go through MFA and have broker installed, you will need to set up the conditional access policy at the portal.

Second, once the conditional policy is set, users will be guided to do the MFA or to install broker at the webview. Client don't need to worry about how to teach users to finish MFA or install broker.

Let me know if more info is needed.
