### ISSUE TITLE
MSAL iOS library is not finishing is background task

### ISSUE THREAD

**Issue by idelfonsog2** [AzureAD/microsoft-authentication-library-for-objc#1459]
What needs to be done from my end ?
```
[BackgroundTask] Background Task 9 ("Interactive login"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.
```

**Comment by jasoncoolmax** [comment]
May i know why you want to call interactive login in background thread? interactive login needs UI.

**Comment by jasoncoolmax** [comment]
Is it possible for you to provide me the full logs? such that I can take a deeper look

**Comment by idelfonsog2** [comment]
Thank you for the response Jason, I completely move to another task at the time and here I'm again facing still the issue. I will put it in the main thread

**Comment by Frederikdam** [comment]
Facing the same issue warning in the logs.

I'm calling `applicationContext.acquireToken(with: parameters)` from the main thread.

**Comment by danielt1263** [comment]
Can reproduce using the official sample app in MSAL 1.2.2 (does not happen with 1.1.x) Client code is not doing anything on a background thread.
To reproduce:

1. Run the sample app.
2. Click on the "Call Microsoft Graph API" button.
3. Click on the "Cancel" button of the alert that pops up.
4. Wait 30 seconds to see the warning.

(It seems to only happen the first time. Subsequent clicks on the call and cancel button do not exhibit the problem.

Sample output:
```
TID=843050 MSAL 1.2.2 iOS Sim 15.5 [2022-07-27 21:00:25] Creating Error with description: User cancelled the authorization session.
TID=843050 MSAL 1.2.2 iOS Sim 15.5 [2022-07-27 21:00:25 - 19210521-EBFA-4E95-9FD6-34A1D90BACB7] [MSAL] Result from authorization session callbackURL host: (null) , has error: YES
TID=843050 MSAL 1.2.2 iOS Sim 15.5 [2022-07-27 21:00:25 - 19210521-EBFA-4E95-9FD6-34A1D90BACB7] [MSAL] Interactive flow finished. Result (null), error: -51700 error domain: MSIDErrorDomain
TID=843050 MSAL 1.2.2 iOS Sim 15.5 [2022-07-27 21:00:25 - 19210521-EBFA-4E95-9FD6-34A1D90BACB7] [MSAL] acquireToken returning with error: (MSALErrorDomain, -50005) Masked(not-null)
2022-07-27 17:00:25.529512-0400 MSALiOS[96578:843050] [Warning] Attempting to load the view of a view controller while it is deallocating is not allowed and may result in undefined behavior (<SFAuthenticationViewController: 0x14905ce00>)
2022-07-27 17:00:55.857329-0400 MSALiOS[96578:843050] [BackgroundTask] Background Task 1 ("Interactive login"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.
```
Note that there are a couple of concerning warnings at the end of the log...

**Comment by LeonidGrebeniuk** [comment]
We are facing the same issue. Version 1.2.13.
