### ISSUE TITLE
Cannot "paste" password any more

### ISSUE THREAD

**Issue by guidedways** [AzureAD/microsoft-authentication-library-for-objc#1460]
I realize this isn't a MSAL issue per se, however a number of users have reported that in the last few weeks, something changed with the authentication flow where the password entry window / dialog no longer accepts "pasting" passwords into the field. Is there something we need to do at our end?

**Comment by hieunguyenmsft** [comment]
Can you give us more detail about the OS version and MSAL version, your scenario? And possible a screenshot/ screenrecord. We aren't aware of any recent change on MSAL but may be something on the Web UX.
Thank you.

**Comment by guidedways** [comment]
This isn't stale - requesting user(s) to provide us with some examples.

**Comment by guidedways** [comment]
We're using the latest version of MSAL (1.2.1) and this is how we setup our prompt:

```
      // Configuration
      MSALPublicClientApplicationConfig *pcaConfig = [[MSALPublicClientApplicationConfig alloc] initWithClientId:clientID redirectUri:redirectURL authority:nil];
      MSALGlobalConfig.loggerConfig.logLevel = MSALLogLevelVerbose;
            
      NSError *error = nil;
      MSALPublicClientApplication *msalAppClient = [[MSALPublicClientApplication alloc] initWithConfiguration:pcaConfig error:&error];

                  MSALWebviewParameters *webParams = [[MSALWebviewParameters alloc] init];
                  webParams.webviewType = MSALWebviewTypeWKWebView;
                  
                  MSALInteractiveTokenParameters *parameters = [[MSALInteractiveTokenParameters alloc] initWithScopes:scopes webviewParameters:webParams];
                  
                  parameters.loginHint = loginHint;
                  parameters.promptType = MSALPromptTypePromptIfNecessary;
                  
                  [msalAppClient acquireTokenWithParameters:parameters completionBlock:^(MSALResult * _Nullable result, NSError * _Nullable error) {
...
}];
```

**Comment by guidedways** [comment]
Here's a screen recording - I'm trying to paste text into the field but CMD+V won't do anything, and right clicking there's no paste option:

https://user-images.githubusercontent.com/202437/164385186-438be4b0-88e9-46e0-a225-edf016df02d9.mp4

**Comment by guidedways** [comment]
This is macOS 12.3.1

**Comment by sullivanisoc** [comment]
I'm continuing to have the very same experience, and I do _not_ have the same experience when, for instance, I am prompted to authenticate a MSFT application (so, I was presented with a visually identical login prompt for Office applications and could both paste into them and also could talk to my password manager).  I am also using macOS 12.3.1. I do not know how to identify the version of MSAL I'm using, but I will if someone can tell me how.

**Comment by hieunguyenmsft** [comment]
Our web interface team is looking at this issue.
@guidedways  @sullivanisoc can you please confirm if the paste function still work on other fields?
@sullivanisoc Unless you own the app, there is no easy way to figure out if the app using MSAL or not, and which version.
Thank you for reporting the error.

**Comment by sullivanisoc** [comment]
On Mon, May 02, 2022 at 09:38:15AM -0700, Hieu Nguyen wrote:
***@***.***  @sullivanisoc can you please confirm if the paste function still work on other fields?

The only thing I ever get the dialogue for is authentication in the application, so I'll have to wait until it times out again to check this.

Thanks,

A
-- 
Andrew Sullivan
President & CEO, Internet Society
***@***.***
+1 416 731 1261

**Comment by hieunguyenmsft** [comment]
Hi, the UX team asks for more info and that would be great if you can help to provide them to narrow down the scope of this issue:
1. Network trace (Fiddler or Charles).
2. Try other identity providers (Google, Facebook, Apple..) to see if the error still persists.
3. Use MSA (Microsoft personal account e.g live.com or outlook.com account).
Thank you.

**Comment by sullivanisoc** [comment]
Hi,

I don't know what you all did, but just now pasting the password into the dialogue worked for me again.

Busycal Version 2022.2.2 (202220228)

This is on my macOS 12.3.1 (21E258) on an M1.

Hope this is useful.

A

On Mon, May 02, 2022 at 01:20:43PM -0700, Hieu Nguyen wrote:
>Hi, the UX team asks for more info and that would be great if you can help to provide them to narrow down the scope of this issue:
>1. Network trace (Fiddler or Charles).
>2. Try other identity providers (Google, Facebook, Apple..) to see if the error still persists.
>3. Use MSA (Microsoft personal account e.g live.com or outlook.com account).
>Thank you.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1460#issuecomment-1115325613
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>

-- 
Andrew Sullivan
President & CEO, Internet Society
***@***.***
+1 416 731 1261

**Comment by guidedways** [comment]
Had to switch to a different authentication mechanism. Their web view authentication is broken.

**Comment by guidedways** [comment]
@antrix1989 Has this been fixed?
