### ISSUE TITLE
Logout doesn't redirect back to my iOS app

### ISSUE THREAD

**Issue by RajendraNayak** [AzureAD/microsoft-authentication-library-for-objc#1462]
I am using MSAL auth library in my iOS app & login is perfectly working.
I want logout using browser so I made below

signoutParameters.signoutFromBrowser = true

But On calling logout(), I expect the browser to be redirected to my app once the logout process is completed. However, I just get a screen "You signed out of your account ..." and it stays there.

![Simulator Screen Shot - iPhone 13 - 2022-03-22 at 14 38 26](https://user-images.githubusercontent.com/3063882/159622292-4227a192-0874-4dfd-b107-3650912b1c48.png)

**Comment by hieunguyenmsft** [comment]
Thanks for reporting this. This is a known limitation in AAD logout flow, we don't have any plan to implement it in the near future.

**Comment by RajendraNayak** [comment]
@hieunguyenmsft  Thank you for your quick reply.
