### ISSUE TITLE
How to remove MSAL cache (which keeps user info) from iOS keychain after logout

### ISSUE THREAD

**Issue by RajendraNayak** [AzureAD/microsoft-authentication-library-for-objc#1463]
I am using MSAL auth library in my iOS app.

My organisation security team dumped the keychain while testing my iOS app & found that, they can see some confidential user information in the keychain (like username, client_id, encrypted password etc) even after successful logout from MSAL. You can see this in below image. 

<img width="1439" alt="Screenshot 2022-03-25 at 3 24 59 PM" src="https://user-images.githubusercontent.com/3063882/160105415-ec0bcb78-6097-4a5f-9b65-a19846c902aa.png">

My question is how to remove this MSAL cache info from keychain?

I have implemented below code to sign-out & it's working well ( I am using signoutFromBrowser = false)
I am also removing current account after successful logout like below code

<img width="1084" alt="Screenshot 2022-03-25 at 4 12 32 PM" src="https://user-images.githubusercontent.com/3063882/160106309-8597b396-fb17-4fd4-adc8-447c710720ea.png">

**Comment by antrix1989** [comment]
Hello @RajendraNayak. Please use [wipeCacheForAllAccounts flag](https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/0b7810a95080ec9bd7c2bf04a6b2d244600a2d98/MSAL/src/public/MSALSignoutParameters.h#L69) to clear all data in the keychain on signout. The api was added in our [1.2.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-objc/releases/tag/1.2.0).
