### ISSUE TITLE
Sign-out is showing wrong consent message in iOS, how to change this message?

### ISSUE THREAD

**Issue by RajendraNayak** [AzureAD/microsoft-authentication-library-for-objc#1465]
I am using MSAL auth library in my iOS app
I am using below parameter for logging out

signoutParameters.signoutFromBrowser = true

But on calling signout method, app is showing an alert which says ".... wants to use 'microsoftonline.com' to **sign in**".  This is wrong, it should be ".... wants to use 'microsoftonline.com' to **sign out**"

How can i change this message?

![Simulator Screen Shot - iPhone 13 - 2022-03-29 at 23 08 55](https://user-images.githubusercontent.com/3063882/160676338-bae05519-413d-44a3-93a5-963eefe789c2.png)

**Comment by antrix1989** [comment]
This is the default message that comes from ASWebAuthenticationSession. Unfortunately, we cannot change it.
