### ISSUE TITLE
How to disable Broker Authentication?

### ISSUE THREAD

**Issue by kanyaks** [AzureAD/microsoft-authentication-library-for-objc#1467]
I am setting byPassRedirectURIValidation as true but I still see it is launching the broker app.

**Comment by juan-arias** [comment]
Hi @kanyaks, in general this is not recommended, please let us know if there is any specific reason you would like to prevent launching the broker app.

**Comment by jasoncoolmax** [comment]
Feel free to reopen if the issue remains.
