### ISSUE TITLE
mdmEnrolledAccount is fine, but getCurrentAccountWithParameters is null

### ISSUE THREAD

**Issue by didldum** [AzureAD/microsoft-authentication-library-for-objc#1468]
I have integrated intune SDK and MSAL into a LOB iOS app for SSO on enrolled devices, receive the mdm UPN instantly, but don't receive any MSALAccount to get an accessToken and work with it.

✅ [[IntuneMAMEnrollmentManager instance] mdmEnrolledAccount] returns the UPN instantly correctly.
❌ But [application getCurrentAccountWithParameters ...] always returns null, even when the enrollment dialogue finished, and I restarted the app. App configuration policies are instantly received fine.

What are the possible causes for this behaviour? 

I triple checked everything, but seem to be missing something. For android and another iOS app in the same account it works just fine.

**Comment by juan-arias** [comment]
Hi @didldum, do you have any error message as part of the completionBlock (`MSALCurrentAccountCompletionBlock`)?

**Comment by didldum** [comment]
No, error argument is null (or false).

We also noticed the enrollment dialogue after PIN/fingerprint sometimes hangs and never finishes. Maybe related?

**Comment by juan-arias** [comment]
@didldum, can you please share the logs from the app? They will help us troubleshoot the issue.

**Comment by jasoncoolmax** [comment]
@didldum Do you happen to have the logs that we need? Feel free to reopen this issue when that is ready. Thank you very much!
