### ISSUE TITLE
Intune Wrapping Tools can share the login session or cookies via MSALWebviewTypeAuthenticationSession Setting ?

### ISSUE THREAD

**Issue by AceChen1** [AzureAD/microsoft-authentication-library-for-objc#1469]
Hi guys, may i know we can get the login session or cookie after use wrapping tools way login successfully? for currently, we use AAD as KEYCLOAK IDP, i need load the KEYCLOAK url to get the KEYCLOAK grant code, then use grant code to get the KEYCLOAK token (OAuth flow), but if the wrapping tools login session can't be shared to app, we need login again on the KEYCLOAK side. any way can just need one login on wrapping tools side, then  Keycloak see the AAD already login, no need pop the Keycloak login page again, then redirect callback url with Keycloak grant code, then i can use the grant code to get the Keycloak token.  ?

https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/issues/77

**Comment by ameyapat** [comment]
Hi @AceChen1 , Can you provide some clarification on what Keycloak is? Is keycloak using MSAL? If not, I think you should open a issue with keycloak

**Comment by AceChen1** [comment]
> Hi @AceChen1 , Can you provide some clarification on what Keycloak is? Is keycloak using MSAL? If not, I think you should open a issue with keycloak

Hi @ameyapat i just want to know the MSAL lib can set the MSALWebviewTypeAuthenticationSession setting to let Intune Wrapping Tools also use MSALWebviewTypeAuthenticationSession config in IOS side?

**Comment by ameyapat** [comment]
You can set the default web view by following https://docs.microsoft.com/en-us/azure/active-directory/develop/customize-webviews#change-the-default-browser-for-the-request. The SSO/cookie sharing implications of which are : https://docs.microsoft.com/en-us/azure/active-directory/develop/customize-webviews#cookie-sharing-and-single-sign-on-sso-implications

**Comment by jasoncoolmax** [comment]
Feel free to reopen if issue remains. Thank you!
