### ISSUE TITLE
Should acquireTokenSilent be called concurrently?

### ISSUE THREAD

**Issue by kqiuciic** [AzureAD/microsoft-authentication-library-for-objc#1479]
I'm trying to do sth like https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-mobile-acquire-token#ios-1
to call APIs after getting the access token, but there're chances that multiple API calls are made at the same time when the access token is expired and I did notice multiple requests sent from the app:
<img width="1300" alt="145206209-73479351-cace-459d-bc12-676557fe27c7" src="https://user-images.githubusercontent.com/80233469/165661575-8793e570-5aab-44d8-b487-3074d89f18ce.png">

Inferred from https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/9c277c9378858767a83d0be5877edbfa757a49ef/MSAL/test/app/MSALStressTestHelper.m#L83
it seems to be thread-safe to call acquireTokenSilent concurrently, but would it issue multiple requests just like https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2884, or it's just fine to issue multiple requests

**Comment by kaisong1990** [comment]
Hi @kqiuciic 

Thanks for reaching out, it should be fine to call multiple requests silently, and I don't think there could be an issue.

Let me know if you have any issue with this.

Also, can you provide some contexts/scenarios why need to call acquire token silently multiple times?

**Comment by kqiuciic** [comment]
@kaisong1990 Our APIs are all protected, so I just try to get a fresh access token every time since `acquireTokenSilent` simply returns the token if it's not expired and will try to refresh it if expired. Do you have any suggestions?

**Comment by kaisong1990** [comment]
@kqiuciic Thanks for the info. In our ```MSALSilentTokenParameters```,  there is a ```forceRefresh``` (Bool) where you can set to skip local AT lookup to refresh a new AT each time. In general, it should be good, though I am not very clear why new AT is needed for the protected resource :)

**Comment by kqiuciic** [comment]
@kaisong1990 Oh, actually I'm making use of the cache. I need a *fresh* AT to avoid 401, not a *new* AT every time. Though being satisfied with current strategy (it's simple: you get one when you need one), I'm also curious if I should instead store and renew the AT routinely. Is it possible to get a cached about-to-expire AT from `acquireTokenSilent`?

**Comment by kqiuciic** [comment]
@kaisong1990 btw, is there any API to clean the AT from the cache for testing purposes?

**Comment by kaisong1990** [comment]
@kqiuciic 
```btw, is there any API to clean the AT from the cache for testing purposes?```
There is no direct way of doing so, and the only way is to clean up eveyrthing, please refer to this [link](https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/dev/MSAL/src/public/MSALSignoutParameters.h#L69)


```Oh, actually I'm making use of the cache. I need a fresh AT to avoid 401, not a new AT every time. Though being satisfied with current strategy (it's simple: you get one when you need one), I'm also curious if I should instead store and renew the AT routinely. Is it possible to get a cached about-to-expire AT from acquireTokenSilent?```

I assume the fresh AT means cahced AT, but not expired one, right? You can try to```acquireTokenSilently```, if remote resource rejected this AT, call ```forceRefresh``` to guarantee that you get a new AT

**Comment by kqiuciic** [comment]
@kaisong1990 sorry but we're facing crashes around `MSALPublicClientApplication.getCurrentAccount`, is it safe to call this concurrently?

**Comment by jasoncoolmax** [comment]
Hi @kqiuciic Could you provide the MSAL logs + crash logs/reports for the crashes you mentioned? The crash is not expected.

**Comment by jasoncoolmax** [comment]
Feel free to reopen the issue when logs/crash reports are ready. thank you!

**Comment by jasoncoolmax** [comment]
Feel free to reopen the issue if issue remains.
