### ISSUE TITLE
MSAL stopped working after setting Google Chrome as the default browser (macOS)

### ISSUE THREAD

**Issue by anton-simakov** [AzureAD/microsoft-authentication-library-for-objc#1480]
Hi,

I use `MSAL` with [Microsoft Graph SDK for ObjC](https://github.com/microsoftgraph/msgraph-sdk-objc) in my application, and I ran into a problem after setting `Google Chrome` as the default browser. 

### Steps to reproduce

1. Go to System Preferences → General and set `Google Chrome` as the default browser.
1. Run [macOS Sample Code](https://github.com/Azure-Samples/active-directory-macOS-swift-native-v2) and press Call Microsoft Graph API.
1. Click Continue in the appeared message.

Google Chrome window opens up. It **does not** show the log-in page. Google Chrome keeps focus, and it does not allow to switch to other apps. Those steps are not complete. It may take more than one try to reproduce the issue. On my machine, it worked great until some specific point. I am not sure what happened, but it started to behave like this after this point. And this is not only my machine. I have several examples of this issue reproducing on **other machines** too.

[Video demonstration](https://1drv.ms/v/s!Ah6zhlPRLxGBfApM6y9jBkzAjGc?e=FNUXiv)

### Workaround

1. Quite Google Chrome. 
1. Go to `Activity Monitor` and force quit the `SafariLaunchAgent` process. 
1. Observe the error in the `macOS Sample Code` app. 

    ```
    Could not acquire token: Error Domain=NSCocoaErrorDomain Code=4097 "connection to service on pid 0 named com.apple.SafariLaunchAgent" UserInfo={NSDebugDescription=connection to service on pid 0 named com.apple.SafariLaunchAgent}
    ```

1. Set `Safari` as the default browser

### Environment
* `macOS Big Sur` Version 11.6.5, Apple M1
* `MSAL` Version 1.2.1 
* `Safari` Version 15.4 (16613.1.17.1.13, 16613)
* `Google Chrome` Version 101.0.4951.41 (Official Build) (arm64)

**Comment by jasoncoolmax** [comment]
Hi @anton-simakov , we do hear from some customers about similar behaviors as what you desribed. Some of them told us that the weird behavior will disappear once they upgrade their mac version to the latest. Would you mind trying the same?

If upgrading the system doesn't help, let me know and I can help take a deeper look. Thank you!

**Comment by anton-simakov** [comment]
Hi @jasoncoolmax, thank you for your reply. I am on macOS **Big Sur** at the moment. I have **all** the latest updates installed. Did you mean that I need to upgrade to macOS **Monterey**?

**Comment by jasoncoolmax** [comment]
Yes. Let me know if upgrading to the latest Monterey solves your issue.

**Comment by jasoncoolmax** [comment]
Free free to reopen if the issue remains
