### ISSUE TITLE
WKWebview Silent Login - Session not working

### ISSUE THREAD

**Issue by kepe94** [AzureAD/microsoft-authentication-library-for-objc#1481]
The silent login doesn’t work on the WKWebview, by logging in with the method ‘acquireTokenSilent’ using the wkWebView as webviewType.

After logging in, it requires to login again when opening the url with WKWebview.

How could I solve this issue?

Thank you in advance

**Comment by jasoncoolmax** [comment]
Hi @kepe94 , to be able to log in silently, you have to login in successfully interactively. The silent login call actually doesn't use the webview. 

If you still cannot figure out, you can share with me the MSAL logs. I can help to take a look.

**Comment by kepe94** [comment]
Thank you! Other question:
why if I open a sharepoint site on ios <15 the webview requires the login and after, instead of opening the article, it goes in loop with the login and on ios 15 everything works correctly?

**Comment by jasoncoolmax** [comment]
>  if I open a sharepoint site on ios <15 the webview requires the login and after 
Is the above involving MSAL? If yes, can you provide the MSAL logs such that I can take a look?

**Comment by jasoncoolmax** [comment]
Feel free to reopen if issue remains.
