### ISSUE TITLE
Granting subset of scopes to clients

### ISSUE THREAD

**Issue by brenmcnamara** [AzureAD/microsoft-authentication-library-for-objc#1482]
Following up on an issue here that my team is having with MSAL authentication flow. We spoke with Microsoft Technical Support today, and they recommended we file an issue here.

Currently, our application is requesting a couple of scopes: `https://graph.microsoft.com/Calendars.ReadWrite.Shared` and `https://graph.microsoft.com/OnlineMeetings.ReadWrite` which fail to get granted when authenticating with consumer Microsoft accounts. When attempting to authenticate a consumer email account with either or both of these scopes on iOS, the Microsoft SDK gives us an error, indicating that authentication has failed. These scopes work fine for Microsoft organization accounts.

This behavior also happens on Web, however the Web SDK does not make this a hard failure (our Web application gets back a list of scopes that were successfully granted and authentication can continue). However, on iOS, the SDK treats this as a non-recoverable failure, indicating to us that there was an error without providing any authentication tokens we can then use.

On iOS, we do not get a refresh token or access token, just the error indicating authentication has failed due to not all scopes being granted (error code -50002).

The ideal solution would be the iOS SDK to behave like web, and return us the access token, the id token, and the scopes that were authorized. We also did an audit of the SDK and found that the server does provide this data to the MSAL SDK on iOS, though the error handling logic prevents this information from getting surfaced to our application.

**Comment by jasoncoolmax** [comment]
Hi @brenmcnamara , you can check here for a detailed example for how to handle MSALErrorServerDeclinedScopes error:
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-error-handling-ios#error-handling-in-msal-for-iosmacos 

Let me know if it helps. Thank you!

**Comment by brenmcnamara** [comment]
Hi @jasoncoolmax , thanks for the response.

I saw the error-handling approach provided in the link, but a bit confused on how exactly it would work.

The example has the following line of code:

```swift
let silentParameters: MSALSilentTokenParameters = ...
```

It looks like it is assuming that we somehow already have silent parameters that we can use to make a follow-up request, but I'm not really sure how to create this unless we already had a successful authentication attempt.

* In order to generate silent parameters, we need a `MSALAccount` object
* In order to have a `MSALAccount` object, we need to know the username and identifier for the account the user wants to log into
* In order to have the `username` and `identifier`, the user would have to had successfully authenticated

Tried inspecting the `userInfo` of the declined scopes error on Swift to see if this includes any account information. I don't see any info that provides the account information.

Inspecting the `userInfo` on the error, I'm seeing the following:

```
▿ 3 elements
  ▿ 0 : 2 elements
    - key : "MSALCorrelationIDKey"
    - value : <Obfuscated>
  ▿ 1 : 2 elements
    - key : "MSALErrorDescriptionKey"
    - value : Server returned less scopes than requested
  ▿ 2 : 2 elements
    - key : "MSALBrokerVersionKey"
    - value : <Obfuscated>
```

There is no info about granted, declined scopes, or account info included in the error, just the above information. Please let me know if I'm missing something.

A few extra notes that may be relevant:
- The `promptType` we are using with the interactive authentication is `.selectPrompt`
- Using `MSAL` version `1.2.1` on Cocoapods
