### ISSUE TITLE
AcquireToken returning an error: (com.apple.AuthenticationServices.WebAuthenticationSession, 3)

### ISSUE THREAD

**Issue by dragantr** [AzureAD/microsoft-authentication-library-for-objc#1484]
I am using the MSAL 1.2.1 version and during the `MSALPublicClientApplication acquireTokenWithParameters` it returns the following error:
`2022-05-11T13:55:56.460Z	WARN		com.symphony.intune	0			 IntuneMAM: TID=114384 MSAL 1.2.1 iOS 15.4.1 [2022-05-11 13:55:56 - DD636EF2-49C3-42FD-AD1F-C72DAAA246E3] [MSAL] acquireToken returning with error: (com.apple.AuthenticationServices.WebAuthenticationSession, 3) Masked(not-null), (null), error code: 0
`

The call is in the viewDidAppear and I added a delay before invoking the method. 

What are the next steps to try to resolve the issue? 

Thank you,
Dragan

**Comment by jasoncoolmax** [comment]
@dragantr If possible, could you share the MSAL logs or even better a video of the repro? So far I don't have enough info to decrypt what actually happened :P

**Comment by dragantr** [comment]
hi, @jasoncoolmax thanks for a quick response. I attached the full logs:

[IntuneMAMDiagnosticFiles.txt](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/8684784/IntuneMAMDiagnosticFiles.txt)

**Comment by dragantr** [comment]
Hi @jasoncoolmax I found the issue and solve it. You can close the issue. Thank you

**Comment by ShmuelCammebys** [comment]
@dragantr what was the issue?
