### ISSUE TITLE
Unable to fetch access-token from acquireToken(with: parameters)

### ISSUE THREAD

**Issue by arisun** [AzureAD/microsoft-authentication-library-for-objc#1486]
Our iOS app uses WKWebView for authentication, it was working few months back, but it is not getting worked right now.
It gives the following error: 
`MFA Error: TID=5064945 MSAL 1.2.0 iOS 15.4.1 [2022-05-13 23:44:19 - 4466CC51-9C93-4A77-8820-904EAB301F85] [MSAL] Start webview authorization session with webview controller class MSIDAADOAuthEmbeddedWebviewController.`

Any guidance will be appreciable.

**Comment by antrix1989** [comment]
@arisun Could you send the full log to this email sedemche@microsoft.com
