### ISSUE TITLE
Potential security issues reported from Veracode scan

### ISSUE THREAD

**Issue by shafersystems** [AzureAD/microsoft-authentication-library-for-objc#1497]
MSIDSymmetricKey.m. line 217, tmpFixedInput is used without validating that the memory was successfully allocated.
MSIDBrokerCryptoProvider.m line 125, return value of getCString is ignored so you don't know if memory was successfully allocated.
MSIDSymmetricKey.m line 193, keyDerivated is not checked to make sure memory was allocated before being used

**Comment by juan-arias** [comment]
Hi @shafersystems, thanks for reporting this, we will apply some changes to prevent these possible issues.

**Comment by juan-arias** [comment]
MSAL version 1.2.2 has been released.
