### ISSUE TITLE
Implicit declaration of function 'MSID_LOG_WITH_CTX' is invalid in C99

### ISSUE THREAD

**Issue by stutivaidya** [AzureAD/microsoft-authentication-library-for-objc#1503]
Hello, after adding pod 'MSAL' when i try to build the project, i am running into the following error "Implicit declaration of function 'MSID_LOG_WITH_CTX' is invalid in C99"
Xcode version : 13.3.1
MSAL version: 1.2.1

<img width="971" alt="Screen Shot 2022-06-05 at 6 01 33 PM" src="https://user-images.githubusercontent.com/11149194/172078469-5f5eec4d-2679-4b56-b387-e61e7c1717e3.png">

**Comment by oldalton** [comment]
Per offline discussion, you're including both ADAL and MSAL in your project. CocoaPods doesn't really know how to resolve same submodule dependency for both of them correctly. That's why you're seeing this issue. Please try removing ADAL and see if this resolves your issue.

**Comment by ameyapat** [comment]
Closing issue, please let us know if the issue persists
