### ISSUE TITLE
ID token expires before access token but doesn't get refreshed until access token expires

### ISSUE THREAD

**Issue by artemisia-absynthium** [AzureAD/microsoft-authentication-library-for-objc#1512]
Hello, I'm having an issue with the access token and id token expiration times being different from each other, details follow.

## Context

My use case is about AAD: I retrieve tokens with standard scopes and I'm using the access token to call Microsoft Graph APIs and the id token to call my custom server APIs, because the standard access token format doesn't allow my server to verify it ("aud" field is intended for MS Graph APIs and doesn't match my app).
I've chosen to do so because I think that requesting another access token with a custom scope would've forced my users to log in twice, because the `MSALResult` object only has one `accessToken` field and one `idToken` field and that would've made my app way less usable.

## The issue

I can correctly get access token and id token, **the issue is that the idToken expiration is different from the access token one and always occurs before**.
My app doesn't store the tokens but it acquires them before each call to an API that needs one but **it never gets fresh tokens until the access token is expired**, so I have a variable window of time where the token that I use to call my server is expired and it seems I cannot do anything about it.

## Expected result

I'd expect both of the tokens to have the exact same expiration time or to be able to request them individually or to force a refresh (the latter is less ideal).

## Actual result

The tokens have different expiration times.
e.g. I've acquired a token on 2022-06-21 11:05:48 and id token expiration is _Tue Jun 21 2022 12:05:47 GMT+0200_, while access token expiration is _Tue Jun 21 2022 12:09:50 GMT+0200_. The delta is really variable, sometimes it's even half an hour.

## Further details

This is the code I'm using (actual error handling is omitted to simplify):
```swift
actor MyAuthActor {
    private let kAuthority = URL(string: "https://login.microsoftonline.com/<tenant-id>")!
    private let kClientID = "<client-id>"
    private let kScopes: [String] = ["User.Read.All"]
    @MainActor private var application : MSALPublicClientApplication?

    @MainActor
    private func applicationContext() throws -> MSALPublicClientApplication {
        if let application = application {
            return application
        }
        let authority = try MSALAADAuthority(url: kAuthority)
        let config = MSALPublicClientApplicationConfig(clientId: kClientID, redirectUri: nil, authority: authority)
        let application = try MSALPublicClientApplication(configuration: config)
        self.application = application
        return application
    }

    private func getCurrentAccount(applicationContext: MSALPublicClientApplication) async throws -> MSALAccount {
        let (currentAccount, _) = try await withCheckedThrowingContinuation { (continuation: CheckedContinuation<(MSALAccount, MSALAccount?), Error>) in
            applicationContext.getCurrentAccount(with: nil) { currentAccount, previousAccount, error in
                guard let currentAccount = currentAccount, error == nil else {
                    continuation.resume(throwing: error ?? NSError(...))
                    return
                }
                continuation.resume(returning: (currentAccount, previousAccount))
            }
        }
        return currentAccount
    }

    func acquireTokenSilently() async throws -> MSALResult {
        let applicationContext = try await applicationContext()
        let parameters = MSALSilentTokenParameters(
            scopes: kScopes,
            account: try await getCurrentAccount(applicationContext: applicationContext))
        return try await withCheckedThrowingContinuation { (continuation: CheckedContinuation<MSALResult, Error>) in
            applicationContext.acquireTokenSilent(with: parameters) { result, error in
                guard let result = result, error == nil else {
                    return continuation.resume(throwing: error ?? NSError(...))
                }
                continuation.resume(returning: result)
            }
        }
    }
}
```

## Conclusion

Is this an issue with MSAL or is there something I'm supposed to do additionally or differently? The documentation is not really clear about this.

Thank you!

**Comment by hieunguyenmsft** [comment]
Hi @artemisia-absynthium, the idToken and accessToken issued for Graph should be only used for that service. Can you share more detail on how your service uses idToken?

**Comment by artemisia-absynthium** [comment]
Hi @hieunguyenmsft , thanks for the response, the idToken has my app id in the aud field, so I'm using that to call APIs on my server, while I'm using the accessToken only for Graph. How should it be instead if I need to access both Graph and my server?

**Comment by hieunguyenmsft** [comment]
IMHO, OAuth2 tokens aren't designed for cross-resources and shouldn't be used likewise. Think about breaching a promise with your user: in UI your app was asking for user consent to access Graph resource but in the background, it also reached out to another resource. 
There are several options I think of:
- 2 separate requests to get 2 sets of tokens for different resources.
- If your service want to use Graph's idToken, why does it need to care about expired date? Could that constraint be removed?

**Comment by hieunguyenmsft** [comment]
Close as I think this is not a MSAL's issue.

**Comment by artemisia-absynthium** [comment]
Hi @hieunguyenmsft , thanks for providing options, it's clearer now.
