### ISSUE TITLE
SwiftUI previews (canvas) no longer work properly after adding MSAL framework to project.

### ISSUE THREAD

**Issue by k-payne-lex** [AzureAD/microsoft-authentication-library-for-objc#1514]
SwiftUI canvas previews working just fine until I added MSAL framework to project.  Now i get "Failed to build the scheme "myTestProject" for all views.  If I look at the diagnostics of the problem, i see the following:  

> linker command failed with exit code 1 (use -v to see invocation)
> 
> Link myTestProject (x86_64):
> ld: warning: ignoring file /myTestProject/Carthage/Build/iOS/MSAL.framework/MSAL, building for iOS Simulator-x86_64 but attempting to link with file built for iOS-arm64
> ld: warning: Could not find or use auto-linked framework 'FBLPromises'
> Undefined symbols for architecture x86_64:
>   "_OBJC_CLASS_$_MSALAccount", referenced from:
>       objc-class-ref in MSALManager.o
>   "_OBJC_CLASS_$_MSALInteractiveTokenParameters", referenced from:
>       objc-class-ref in MSALManager.o
>   "_OBJC_CLASS_$_MSALSilentTokenParameters", referenced from:
>       objc-class-ref in MSALManager.o
>   "_OBJC_CLASS_$_MSALAADAuthority", referenced from:
>       objc-class-ref in MSALManager.o
>   "_OBJC_CLASS_$_MSALWebviewParameters", referenced from:
>       objc-class-ref in MSALManager.o
>   "_OBJC_CLASS_$_MSALPublicClientApplicationConfig", referenced from:
>       objc-class-ref in MSALManager.o
>   "_MSALErrorDomain", referenced from:
>       closure  (__C.MSALResult?, Swift.Error?) -> () in myTestProject.MSALManager.(acquireTokenSilently in _719C75F6169226FC68AB2325B1A83063)(_: __C.MSALAccount?, scopes: [Swift.String], onSuccess: (Swift.String?) -> (), onFailure: (Swift.Error) -> (), onComplianceNeeded: () -> ()) -> () in MSALManager.o
>   "_OBJC_CLASS_$_MSALPublicClientApplication", referenced from:
>       objc-class-ref in MyTestProjectApp.o
>       objc-class-ref in MSALManager.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have tried to add "arm64" to the Excluded Architectures build setting, I get the same result. Is it possible the framework needs to be built as a xcxframework? Carthage seems to build everything just fine. perhaps the simulators binary is not included or setup properly?

SwiftUI is Apple's direction for all new projects moving forward.  I would like to get this working properly so that I can continue to move with Apple.

Any help would be much appreciated.

**Comment by hieunguyenmsft** [comment]
Hi @k-payne-lex it looks like an architecture configuration issue, not an MSAL problem. Can you have a look at this link: https://developer.apple.com/forums/thread/669274 to see if it's similar to your issue.

**Comment by k-payne-lex** [comment]
Some additional information, I use carthage to pull and build the framework.  The resulting msal.framework file is then included in the project.  I am thinking my project needs a xcframework.  Thoughts?  I think xcode previews will only work if the ios-simulator binary is linked?  I am thinking the carthage build only creates .framework file, thus arm64 is missing?

**Comment by hieunguyenmsft** [comment]
@k-payne-lex which command did you use for Carthage build? I just ran on my end using ```carthage update --use-xcframeworks``` and it produces a .xcframework.

**Comment by hieunguyenmsft** [comment]
Inside that xcframework folder, I see 3 outputs: ios-arm64, ios-arm64_x86_84-simulator, and macos-arm64_x86_64 so I guess they are enough to run on a real device/ simulator. Let me know if you think otherwise.

**Comment by honkmaster** [comment]
The issue still persists when using SPM. Here, we have no influence how the package is build...

**Comment by honkmaster** [comment]
@hieunguyenmsft Please reopen and investigate this issue.
MSAL is mentioned a lot in a related thread in the Apple Dev Forum.
https://developer.apple.com/forums/thread/707569

**Comment by hybridcattt** [comment]
the problem seems to go away on its own on Xcode 14.1 beta 3
