### ISSUE TITLE
Is Async/Await support in the library?

### ISSUE THREAD

**Issue by idelfonsog2** [AzureAD/microsoft-authentication-library-for-objc#1517]
I get the following docs

![Screen Shot 2022-07-07 at 11 50 05CDT](https://user-images.githubusercontent.com/7195235/177827793-52238812-c527-4a49-a20f-7478d6559dc1.png)

It seems it comes from the Objective-C Interface, although other methods are not using this "magic" is it supported in all methods or not? is there a specific branch that I should use the library from? or any information related to it?

**Comment by antrix1989** [comment]
Yes, the public API of the MSLA library is Objective-C based. Objective-C methods with completion blocks are automatically translated into async methods in Swift. For example:

```
    func abc() async throws
    {
        let a = MSALPublicClientApplication()
        
        let acc: MSALAccount? = nil
        let p = MSALSignoutParameters()
        try await a.signout(with: acc!, signoutParameters: p)
        
        let sp: MSALSilentTokenParameters? = nil
        try await a.acquireTokenSilent(with: sp!)
        
        let ip: MSALInteractiveTokenParameters? = nil
        try await a.acquireToken(with: ip!)
    }
```
