### ISSUE TITLE
`acquireToken(with: parameters)` Main Thread Checker

### ISSUE THREAD

**Issue by idelfonsog2** [AzureAD/microsoft-authentication-library-for-objc#1518]
I have the following warning for this code:

`[UIViewController view] must be used from main thread only`
`self.applicationContext.acquireToken(with: parameters)` 

should I wrap that line on the mainThread ?

**Comment by antrix1989** [comment]
Yes, `acquireToken(with: parameters) `needs to be called from the main thread. We also provide the API to configure the [completion block queue](https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/dev/MSAL/src/public/MSALParameters.h).
