### ISSUE TITLE
App stopped working for GCC High tenants after migrating from ADAL to MSAL

### ISSUE THREAD

**Issue by Happy202121** [AzureAD/microsoft-authentication-library-for-objc#1520]
Describe the bug
Our app is in production. After migrating from ADAL to MSAL, our Intune-integrated app no longer works for GCC High customers. After entering their email and password, they get the error "AADSTS700016: Application with identifier not found in the directory (domain name)".

With ADAL, our GCC High customers did not get this error.

Smartphone:
Device: All iOS devices
iOS Version: All iOS versions
Browser: All iOS browsers
MSAL Version: 1.13.0

To Reproduce
User opens the app
User enters their email address
User enters their password
Auth request goes to user's tenant
User gets error "AADSTS700016: Application with identifier not found in the directory (domain name)"

Expected behavior
The GCC High tenant finds the client_id in the Azure commercial cloud and allows the sign-in to complete.

Actual Behavior
The client_id is not found and the sign-in fails.

**Comment by kaisong1990** [comment]
@Happy202121 Can you provide correlationIds and MSAL logs. Also, would be great if you can provide authorities and parameters you passed into MSAL

**Comment by Happy202121** [comment]
Thanks, working to gather those now.

**Comment by jasoncoolmax** [comment]
Feel free to reopen the issue once the data requested is ready.
