### ISSUE TITLE
Refresh accesstoken silently after logging in with Firebase

### ISSUE THREAD

**Issue by Nicolaidam** [AzureAD/microsoft-authentication-library-for-objc#1521]
Im using firebase for Microsoft authentication for an application. After login it should be possible to fetch data from Microsoft Graph.  When the user is authenticated with Firebase an OAuth access token and OAuth ID is provided, and the accesstoken can be used to fetch data from Microsoft Graph. Everything is working!

However, when the user is away from the app for a day (or something like that) the accesstoken provided from firebase is not valid anymore used with Microsoft Graph because it needs to be refreshed. And this is the problem,  the token should be refreshed in the background cause i dont want the users to re-authenticate with another popup.

I was thinking to use function acquireTokenSilent to refresh, but im not sure how to generate a MSALAccount for the user that is already logged in with Firebase.. I have tried to generate a MSALAccount with applicationContext.account(forUsername: "email") and applicationContext.account(forIdentifier: "OAuthID") but with no luck. 

Is it even possible to generate an access token silently, now that Im not using this libary for the initial login? 🤔

**Comment by kaisong1990** [comment]
@Nicolaidam Would you give try with MSAL for interactive login as well? We don't support the mixed senarios.

**Comment by Nicolaidam** [comment]
> @Nicolaidam Would you give try with MSAL for interactive login as well? We don't support the mixed senarios. 

Actually I have already experimented with MSAL for the interactive login and it works fine, also when refreshing the graph token silently.

However my problem was that I wanted to use Firebase SDK for the Authentication part (where a graph token is provided as well) and refresh that token silently afterwards. But it seems like this is not possible to refresh silently, that's is my issue. It is not possible in firebase sdk so that's why I wanted to experiment with MSAL.

A solution could be to use this libary for the authentication instead of Firebase. However we would really like to use Firebase if possible since it gives also us other login opportunities "for free" like google and Facebook. So my question was if you had any guidance on how I could silently refresh a valid graph token without using MSAL for the interactive login (if it is possible) 

Thanks a lot for the time! ☺️

**Comment by kaisong1990** [comment]
@Nicolaidam Thanks for the details. MSAL has its own system and logic of managing tokens/account, and will not work with mixed flow as you mentioned above. 

1. You might reach out to Firebase and ask if they provide a way of refreshing/managing tokens. Or
2. Use both Firebase for FB/Google login flows and MSAL for MS graph

**Comment by Nicolaidam** [comment]
> @Nicolaidam Thanks for the details. MSAL has its own system and logic of managing tokens/account, and will not work with mixed flow as you mentioned above. 
> 
> 
> 
> 1. You might reach out to Firebase and ask if they provide a way of refreshing/managing tokens. Or
> 
> 2. Use both Firebase for FB/Google login flows and MSAL for MS graph

Yeah okay.That was also what I was thinking. 
We have decided to do the token handling ourself on our custom python backend and then use MSAL for Microsoft login and graph token refreshing. 
Thanks a lot! 🙏🏼
