### ISSUE TITLE
UIApplication.endBackgroundTask not being called properly in version 1.2.2

### ISSUE THREAD

**Issue by danielt1263** [AzureAD/microsoft-authentication-library-for-objc#1526]
Can reproduce using the official sample app with MSAL 1.2.2 (does not happen with 1.1.x) Client code is not doing anything on a background thread.
To reproduce:
1. Run the sample app.
2. Click on the "Call Microsoft Graph API" button.
3. Click on the "Cancel" button of the alert that pops up.
4. Wait 30 seconds to see the warning.

(It seems to only happen the first time. Subsequent clicks on the call and cancel button do not exhibit the problem.

Sample output:
```
TID=843050 MSAL 1.2.2 iOS Sim 15.5 [2022-07-27 21:00:25] Creating Error with description: User cancelled the authorization session.
TID=843050 MSAL 1.2.2 iOS Sim 15.5 [2022-07-27 21:00:25 - 19210521-EBFA-4E95-9FD6-34A1D90BACB7] [MSAL] Result from authorization session callbackURL host: (null) , has error: YES
TID=843050 MSAL 1.2.2 iOS Sim 15.5 [2022-07-27 21:00:25 - 19210521-EBFA-4E95-9FD6-34A1D90BACB7] [MSAL] Interactive flow finished. Result (null), error: -51700 error domain: MSIDErrorDomain
TID=843050 MSAL 1.2.2 iOS Sim 15.5 [2022-07-27 21:00:25 - 19210521-EBFA-4E95-9FD6-34A1D90BACB7] [MSAL] acquireToken returning with error: (MSALErrorDomain, -50005) Masked(not-null)
2022-07-27 17:00:25.529512-0400 MSALiOS[96578:843050] [Warning] Attempting to load the view of a view controller while it is deallocating is not allowed and may result in undefined behavior (<SFAuthenticationViewController: 0x14905ce00>)
2022-07-27 17:00:55.857329-0400 MSALiOS[96578:843050] [BackgroundTask] Background Task 1 ("Interactive login"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.
```
Note that there are a couple of concerning warnings at the end of the log...

**Comment by danielt1263** [comment]
This is a rehash of issue #1459

**Comment by mipetriu** [comment]
@danielt1263 Thank you for reporting this. I will attempt to repro this on my end as well to see if I can take a closer look.

**Comment by mfclarke-ts** [comment]
We're facing this issue as well. It's concerning because it may mess with our system budget for background fetch.

**Comment by mipetriu** [comment]
@danielt1263, @mfclarke-ts. Thanks again for bringing attention to these issues.

For the background task warning, there was indeed a bug in the background task handling for system webview requests. I've checked in a fix that will be in the next release, which will likely be available by early next week.

Regarding the "Attempting to load the view of a view controller", as far as I can tell we are following Apple's guidelines regarding our use of the system browser. It may be worth opening a feedback request to Apple to dig into that warning.

**Comment by jasoncoolmax** [comment]
Fix will be out in the coming release next week if everything goes well. Feel free to reopen the ticket if that doesnt' solve the warning. Thank you!

**Comment by LeonidGrebeniuk** [comment]
We are still facing this issue. Version 1.3.0

acquireToken isMainThread:  true
Background Task 2 ("Interactive login"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.
acquireToken isMainThread:  true
