### ISSUE TITLE
TLS error showing up

### ISSUE THREAD

**Issue by guidedways** [AzureAD/microsoft-authentication-library-for-objc#1527]
Any idea why we're seeing this?

```
Error Domain=MSALErrorDomain Code=-50000 "Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=AADSTS1002016: You are using TLS version 1.0, 1.1 and/or 3DES cipher which are deprecated to improve the security posture of Azure AD. Your TenantID is: e7c22e39-fee7-4a4a-989e-18dbbf43474b. Please refer to https://go.microsoft.com/fwlink/?linkid=2161187 and conduct needed actions to remediate the issue. For further questions, please contact your administrator. 
```

**Comment by kaisong1990** [comment]
@guidedways MSAL SDK does not provide/limit TLS version, and should use Apple's networking framework. I would suggest checking your app configurations and local networking to make sure TLS 1.1 + is supported

**Comment by jasoncoolmax** [comment]
Feel free to reopen the ticket if the issue remains.

**Comment by guidedways** [comment]
@jasoncoolmax we don't have any configuration within the app - more users are reporting the same issue: 
```
Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=AADSTS1002016: You are using TLS version 1.0, 1.1 and/or 3DES cipher which are deprecated to improve the security posture of Azure AD. Your TenantID is: 4bd93eae-37cc-476a-a89c-25ed8e0357fb
```

**Comment by guidedways** [comment]
If you google for this, you'll find all kinds of complaints coming from Azure services so I think this is related to a bug in MSAL or Microsoft in general:

https://www.google.com/search?q=%22You+are+using+TLS+version+1.0%2C+1.1+and%2For+3DES%22&rlz=1C5CHFA_enAE951AE952&oq=%22You+are+using+TLS+version+1.0%2C+1.1+and%2For+3DES%22&aqs=chrome..69i57j69i59l4.402j0j7&sourceid=chrome&ie=UTF-8

**Comment by guidedways** [comment]
More links, but these are related to Windows. Our user is on macOS: https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/security/enable-tls-1-2-client

**Comment by guidedways** [comment]
I have a feeling this has something to do with `NSAllowsArbitraryLoads` set to `true` in the Info.plist file. This is probably causing it to connect via TLS v1.0. Is there a way to override this in code?
