### ISSUE TITLE
ValidateAuthority should be a method parameter 

### ISSUE THREAD

**Issue by oldalton** [AzureAD/microsoft-authentication-library-for-objc#153]
Currently validateAuthority is a property and it's not obvious for developers that it should be changed. Moreover, the default value is NO. We should look into making it a method parameter or at least making it YES by default.

**Comment by RPangrle** [comment]
The default value definitely should be YES.

**Comment by RPangrle** [comment]
Also, validateAuthority really is not a per-request thing. Either all of authority strings within a single environment should be validated when used with a application or none of them, so it is something more appropriately set when created the public client application object.

**Comment by oldalton** [comment]
This discussion is coming from #149, when @unpluggedk  pointed out that it might be a good idea to include it as a method parameter. We agreed that it might be worth to have additional discussion. In any case, we should fix validateAuthority not being YES by default (#164)
