### ISSUE TITLE
MSAL SSO Extension - Azure AD vs Redirect Type Differences

### ISSUE THREAD

**Issue by LibertyDev18** [AzureAD/microsoft-authentication-library-for-objc#1538]
We are seeing a difference in behavior with SSO Extension and LOB apps when setting up the SSO configuration profile 'SSO app extension type' as Redirect vs. Microsoft Azure AD.

With the type set to Redirect we get exactly as we would expect where the first launch of the app and call to MSAL acquireTokenWithParameters briefly presents (slides up) a screen that is dismissed and the user is seamlessly and successfully authenticated.

With the type set to Microsoft Azure AD the same call to MSAL acquireTokenWithParameters on first launch of the app will instead present the generic Microsoft login screen asking for UPN. If the user taps 'Cancel' AND a subsequent call is made to MSAL acquireTokenWithParameters, MSAL will then briefly present the screen that is dismissed and the user is seamlessly and successfully authenticated.

In both cases a UPN hint is being passed along during the initial call to acquireTokenWithParameters.

Is there a setting that we are missing when using 'SSO app extension type' of Microsoft Azure AD that would be causing the initial call to present the generic Microsoft login screen?

Mentioning @ameyapat for reference as we have worked on related topics to SSO Extension behavior in the past.

Thank you for your help.

**Comment by antrix1989** [comment]
@LibertyDev18 please capture MSAL and Authenticator logs (Hamburger button -> Send feedback -> Having trouble?). Send MSAL logs and Authenticator incident id to sedemche@microsfot.com.

**Comment by LibertyDev18** [comment]
@antrix1989, email sent with requested information. Please let me know if we can provide anything additional.

**Comment by antrix1989** [comment]
Azure AD configuration has extra settings to do the device registration and linking to Intune during the initial token request. This behavior is a known issue and the fix is expected to be rolled out in September.
