### ISSUE TITLE
Override / specify TLS version?

### ISSUE THREAD

**Issue by guidedways** [AzureAD/microsoft-authentication-library-for-objc#1544]
Please see this issue:

https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1527

It turns out that when you use `NSAppTransportSecurity` and enable `NSAllowsArbitraryLoads`, macOS somehow seems to connect via TLS 1.0 or 1.1 but NOT 1.2. The server (a university in this case) the user is connecting to requires v1.2 explicitly. 

When we made the following change, it fixed it for them:

```
<key>NSExceptionDomains</key>
		<dict>			
			<key>office365.com</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<false/>
				<key>NSExceptionMinimumTLSVersion</key>
				<string>TLSv1.2</string>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
			<key>onmicrosoft.com</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<false/>
				<key>NSExceptionMinimumTLSVersion</key>
				<string>TLSv1.2</string>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
			<key>outlook.com</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<false/>
				<key>NSExceptionMinimumTLSVersion</key>
				<string>TLSv1.2</string>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
			<key>outlook.office365.com</key>
			<dict>
				<key>NSExceptionMinimumTLSVersion</key>
				<string>TLSv1.2</string>
				<key>NSExceptionAllowInsecureHTTPLoads</key>
				<false/>
			</dict>
```

However now some other users are complaining it won't connect to their server. It seems in their case they're using TLS 1.1:

https://docs.microsoft.com/en-us/exchange/troubleshoot/client-connectivity/connection-to-mail-server-timed-out

Is there a way to automatically select the correct version of TLS or is this outside the scope of MSAL?

**Comment by mipetriu** [comment]
Hi @guidedways, MSAL doesn't contain any logic for selection a TLS version - this should be controlled by the underlying Apple networking framework. If TLS version 1.2 is available, but the client isn't selecting the highest available version, it might be beneficial to open a support ticket with Apple? Their engineers would be best placed to investigate any issues.
