### ISSUE TITLE
Deleted Accounts Caching?

### ISSUE THREAD

**Issue by jukemoon** [AzureAD/microsoft-authentication-library-for-objc#1545]
I've been having trouble switching accounts in Authenticator. I've removed the account entirely from Authenticator and added my new one. Still, each time I run my iOS application, it prompts me to log in with the account that was just deleted from Authenticator. The only way I've had luck switching accounts is by performing a factory reset of the device.

Could you please assist?

**Comment by mipetriu** [comment]
Hi @jukemoon, which prompt are you referring to when you continue to see the removed account? Are you referring to the Authenticator account list that's shown when starting an interactive token request with the Authenticator present? If possible, maybe a screenshot of the prompt may help.

Could you also upload Authenticator logs of the issue and share the incidentID? We can take a look on our side.

**Comment by antrix1989** [comment]
hi @jukemoon, the broker was called with login_hint parameter. Make sure the account provided to MSAL is correct. If you believe it is correct, please record the demo of user flow and send us both MSAL and broker logs. You can send the demo and logs to this email: sedemche@microsoft.com.

**Comment by jukemoon** [comment]
Hi, @antrix1989. I've sent the email; please let me know if there's anything I can provide to troubleshoot.

**Comment by antrix1989** [comment]
Discussed over email.
