### ISSUE TITLE
Expired tokens returned from Authenticator

### ISSUE THREAD

**Issue by dtatcbrain** [AzureAD/microsoft-authentication-library-for-objc#1555]
We have a customer for an Intune iOS app with MSAL login through the MS Authenticator app against an Azure AD. Sometimes, for up to an hour at a time, some of their users get expired tokens from Authenticator. Looking at our logs, they have usually expired recently (less than 20 minutes prior to the login attempt).

We have been able to reproduce the behaviour, but only by setting back the clock on the iOS device and then letting the token expire. We have checked the time on the servers and iOS devices involved.

We have built the app with MSAL version 1.1.22

We are calling
```
MSALPublicApplication acquireTokenWithParameters:(MSALInteractiveTokenParameters *)parameters
                   completionBlock:(MSALCompletionBlock)completionBlock
```
which swithes to Authenticator before giving us a token in the completion.

Two questions:

1. Is there anything, besides setting the clock wrong, that might cause expired tokens to be returned?
2. Is there any way we can force MSAL/Authenticator to give us a new token? We have tried removing the account using MSALPublicClientApplication.removeAccount prior to logging in, but we still get the same token from Authenticator afterwards.

**Comment by mipetriu** [comment]
Hi @dtatcbrain, what is the experience that the user sees? Are they acquiring a token through MSAL/Authenticator that is then being rejected by the resource?

The scenario of the Authenticator returning expired tokens without manipulating the clock seems incorrect. If the user can repro the issue, could they upload logs and share the IncidentID? We can take a look on our side.

**Comment by dtatcbrain** [comment]
Thanks for getting back to us. I should clarify the flow in our app: We are passing the ID token obtained via MSAL from our app to our server, where it is validated and exchanged for a session. The session then serves as our access token. It is the ID token that has sometimes expired. It appears that we have run into a variation of this issue:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3119

We will try the workarounds suggested there, setting the "force refresh" parameter on acquireTokenSilent, and configuring the lifetime of ID tokens in Azure.

Since posting the issue we have also updated MSAL to version 1.2.3, and introduced a call to acquireTokenSilent before resorting to acquireToken. We were missing that call before.

**Comment by antrix1989** [comment]
Thanks for the details. Let us know if additional help is needed.
