### ISSUE TITLE
MSAL's dSYM files

### ISSUE THREAD

**Issue by nevertheless1975** [AzureAD/microsoft-authentication-library-for-objc#1556]
Where can get the MSAL dSYM file? I had hoped it would be part of the release, but I didn't found it. I have some crash reports indicating MSAL been involved. However, I'm missing the symbols that would allow me to read stack traces.

**Comment by mipetriu** [comment]
Hi @nevertheless1975, how are you integrating MSAL into your project? For example through Cocoapods or Swift Package Manager?

**Comment by mipetriu** [comment]
@nevertheless1975 After taking a closer look, you can find the MSAL dSYM file if you archive your application. If you right-click one of the archives in your list and select "open in Finder" and then "show package contents" on it, I believe you should be able to find the dSYM there.

**Comment by nevertheless1975** [comment]
Hi @mipetriu, we're integrating the compiled MSAL framework. My understanding is that dSYMs would only be created for frameworks we are building as dependency of the app target. At least for those dependencies we have dSYMs, for already compiled frameworks not. I was wondering if dSYMs would be somewhere online for each MSAL version, so I don't have to change the build process.

**Comment by nevertheless1975** [comment]
If I just add MSAL via Cocoapods, archiving the project will give me the dSYM. I'm good. Thanks.

**Comment by nevertheless1975** [comment]
The dSYM I generated of course has a different UUID. So I need the dSYM that was build for the released binaries. Do you have these somewhere online or can I ask you to provide for a specific version?

**Comment by mipetriu** [comment]
@nevertheless1975 Apologies for the late reply. Were you able to match the generated dSYM file to the crash logs?

If not, could you please give a little more context on this problem you're seeing: "The dSYM I generated of course has a different UUID."? Is it something along the lines of this [this forum post](https://developer.apple.com/forums/thread/26221), where the UUID of the dSYM is different from the one of their app downloaded from the App Store?

**Comment by mipetriu** [comment]
@nevertheless1975 Closing the issue due to no response. Please feel free to re-open if you're still seeing the issue.
