### ISSUE TITLE
Unable to create MSAL context for federated authority : "AD FS authority is not supported yet in MSAL"

### ISSUE THREAD

**Issue by alexeystrakh** [AzureAD/microsoft-authentication-library-for-objc#1562]
MSAL [ADFS docs](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-net-adfs-support#msal-connects-directly-to-ad-fs) claim that this should be supported although when I try to create an MSAL context using federated authority, it crashes with the following error:

> Unable to create Application Context Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=AD FS authority is not supported yet in MSAL, MSALInternalErrorCodeKey=-42008}

```
let kAuthority = "https://<my_federated_server_address>/adfs"
guard let authorityURL = URL(string: kAuthority) else {
    print("Unable to create authority URL")
    return
}
let authority = try MSALADFSAuthority(url: authorityURL)
let msalConfiguration = MSALPublicClientApplicationConfig(clientId: kClientID, redirectUri: nil, authority: authority)
let applicationContext = try MSALPublicClientApplication(configuration: msalConfiguration)
```

Does MSAL.NET support federated authorities (MSALADFSAuthority)?

**Comment by antrix1989** [comment]
The doc that you shared refers to MSAL.NET sdk. In MSAL ObjC we don't support adfs at the moment.

**Comment by alexeystrakh** [comment]
Thanks for confirmation.
