### ISSUE TITLE
SwiftUI previews crashing because of MSAL dependency

### ISSUE THREAD

**Issue by mapedd** [AzureAD/microsoft-authentication-library-for-objc#1565]
Hello everyone

I'm using MSAL with SwiftPM, Xcode 14.

I'm getting this crash when trying to use SwiftUI previews:

```
HumanReadableSwiftError

SettingsError: noExecutablePath(<IDESwiftPackageStaticLibraryProductBuildable:ObjectIdentifier(0x0000600016e21980):'MSAL'>)
```

Anybody seen this and have any idea how to fix that?

**Comment by hybridcattt** [comment]
The same issue is happening in AppCenter, and they've prepared a fix: https://github.com/microsoft/appcenter-sdk-apple/pull/2433

Please make the same fix here so we can continue using SwiftUI previews 🙏

**Comment by hybridcattt** [comment]
@mapedd  FYI the problem seems to go away on Xcode 14.1 beta 🎉

**Comment by antonioalwan** [comment]
Issue resolved
