### ISSUE TITLE
Does MSAL iOS support SSO with Flutter framework? 

### ISSUE THREAD

**Issue by DaisyCG9** [AzureAD/microsoft-authentication-library-for-objc#1566]
The Code sample will use the system browser for SSO by default. However, one of the app vendor is using the Flutter framework, and it could not SSO. The backend logs showed it was using the webView browser, which was not supported sharing auth cookies for SSO.
here is the code lines for WebViewParameter. The app vendor did not change the browser setting, and it should use the system browser. 
![image](https://user-images.githubusercontent.com/62054144/193184456-bf755838-d6f5-4d7d-ad35-b68c58359dd1.png)

Does MSAL iOS support SSO with the Flutter framework? 

Appreciate your insights.

**Comment by antonioalwan** [comment]
@DaisyCG9 We don't have any official support for Flutter and it is not on the roadmap.

**Comment by kaisong1990** [comment]
Closing due to no official support for Flutter framework
