### ISSUE TITLE
Wiped accounts are not forgotten

### ISSUE THREAD

**Issue by mjKosmic** [AzureAD/microsoft-authentication-library-for-objc#1570]
When using MSAL to signout from an SSOE session on iOS, safari still sees the account as a remembered account to try to log in with. Both `wipeAccount` and `signoutFromBrowser` are being used and it does seem to sign the account out correctly but it's still being remembered in the cache somewhere. This can pose a leak of Personally Identifiable Information in certain business contexts. Is there either something I'm missing or a fix we can get for this?

**Comment by antonioalwan** [comment]
@mjKosmic Do you mean the account still shows up in the account picker in the browser? Also, if there are logs you can share or video recording that would be great.

**Comment by swasti29** [comment]
Closing due to no response. Please feel free to reopen.

**Comment by mjKosmic** [comment]
Sorry for the late reply. Yes the account still shows up in the account picker in the browser. This is a proprietary workflow but I'll see if I can get a quick video of it

**Comment by mjKosmic** [comment]
Sorry for the late reply. Yes the account still shows up in the account picker in the browser. I'll see if I can grab a quick video of it
