### ISSUE TITLE
How to set timeout for acquireTokenSilent

### ISSUE THREAD

**Issue by crosshawk** [AzureAD/microsoft-authentication-library-for-objc#1574]
Hello,

I am using MSAL 1.2.3 in Swift and my question is how can I set a timeout for the acquireTokenSilent calls.
Some users with network issues are reporting that they get a timeout after 5 mins and I want to reduce that.
In Windows we do that using a cancellation token but I haven't figured out how to do it in MAC.

Thank you in advance!

**Comment by antonioalwan** [comment]
@crosshawk thanks for your question. We don't have any timeout setting for acquireTokenSilent call. I would suggest using a wrapper with timeout handler in this case.

**Comment by crosshawk** [comment]
Thank you for you answer. I think I'll just patch s_requestTimeoutInterval in MSIDHttpRequest.m.
