### ISSUE TITLE
Add support for `domain_hint` parameter when initiating login

### ISSUE THREAD

**Issue by faradayfan** [AzureAD/microsoft-authentication-library-for-objc#1576]
In the documentation for [OAuth 2.0 authorization code flow in Azure Active Directory B2C](https://learn.microsoft.com/en-us/azure/active-directory-b2c/authorization-code-flow#1-get-an-authorization-code) one parameter that can be used to pre-select an identity provider is `domain_hint`. I can't find that support in this library, but would it be possible to add the support?

**Comment by faradayfan** [comment]
It looks like the support for `domain_hint` might be added with this PR: #1539

**Comment by kaisong1990** [comment]
@faradayfan Can you try to add ```domain_hint``` in extra params when creating the request?

**Comment by faradayfan** [comment]
@kaisong1990, it looks like that is supported using the extra params. Thank you!
