### ISSUE TITLE
Crash when acquireTokenSilentWithParameters

### ISSUE THREAD

**Issue by robin202205** [AzureAD/microsoft-authentication-library-for-objc#1587]
OS Version: iOS 15.3 (19D50)
Report Version: 104

Exception Type: EXC_CRASH (SIGABRT)
Crashed Thread: 4

Application Specific Information:
SMS Lite > SMS Lite(67747,0x16faaf000) malloc: Heap corruption detected, free list is damaged at 0x2812813b0
*** Incorrect guard value: 72057602002338833

Thread 4 Crashed:
0   libsystem_kernel.dylib          0x36fd43964         __pthread_kill
1   libsystem_pthread.dylib         0x3e36cf374         pthread_kill
2   libsystem_c.dylib               0x316d45f4c         abort
3   libsystem_malloc.dylib          0x3249b5a04         malloc_vreport
4   libsystem_malloc.dylib          0x3249b5ca0         malloc_zone_error
5   libsystem_malloc.dylib          0x3249b0174         nanov2_allocate_from_block
6   libsystem_malloc.dylib          0x3249af218         nanov2_allocate
7   libsystem_malloc.dylib          0x3249af808         nanov2_calloc
8   libsystem_malloc.dylib          0x32499e080         _malloc_zone_calloc
9   CoreFoundation                  0x300ec7d64         _CFRuntimeCreateInstance
10  CoreFoundation                  0x300ec3f9c         __CFStringCreateImmutableFunnel3
11  CoreFoundation                  0x300ee3e48         CFStringCreateWithSubstring
12  CoreFoundation                  0x300edea64         _retainedComponentString
13  CoreFoundation                  0x300ec66f4         CFURLCreateStringWithFileSystemPath
14  CoreFoundation                  0x300ecc340         CFURLCopyFileSystemPath
15  Foundation                      0x303f06c64         -[NSURL(NSURL) path]
16  Foundation                      0x303f35b64         -[NSURL(NSURLPathUtilities) pathComponents]
17  MSAL                            0x102f0e3d8         +[MSIDADFSAuthority isAuthorityFormatValid:context:error:]
18  MSAL                            0x102f05380         +[MSIDAADAuthority isAuthorityFormatValid:context:error:]
19  MSAL                            0x102f058b4         +[MSIDAADAuthority realmFromURL:context:error:]
20  MSAL                            0x102ee54b8         -[MSIDAuthority initWithURL:validateFormat:context:error:]
21  MSAL                            0x102f0495c         -[MSIDAADAuthority initWithURL:context:error:]
22  MSAL                            0x102f04b24         -[MSIDAADAuthority initWithURL:rawTenant:context:error:]
23  MSAL                            0x102ebfb60         -[MSIDAADRequestConfigurator configure:]
24  MSAL                            0x102f0aa20         -[MSIDAADRefreshTokenGrantRequest initWithEndpoint:authScheme:clientId:redirectUri:enrollmentId:scope:refreshToken:claims:extraParameters:context:]
25  MSAL                            0x102f0f4d0         -[MSIDAADV2Oauth2Factory refreshTokenRequestWithRequestParameters:refreshToken:]
26  MSAL                            0x102f502a4         -[MSIDSilentTokenRequest acquireTokenWithRefreshTokenImpl:completionBlock:]
27  MSAL                            0x102ee5fb8         -[MSIDAuthority loadOpenIdMetadataWithContext:completionBlock:]
28  MSAL                            0x102f4fe48         -[MSIDSilentTokenRequest redeemAccessTokenWith:completionBlock:]
29  MSAL                            0x102f4f5d4         -[MSIDSilentTokenRequest tryRefreshToken:tokenType:completionBlock:]
30  MSAL                            0x102f4ed34         __45-[MSIDSilentTokenRequest executeRequestImpl:]_block_invoke.125
31  MSAL                            0x102f4f2d0         -[MSIDSilentTokenRequest fetchCachedTokenAndCheckForFRTFirst:shouldComplete:completionHandler:]
32  MSAL                            0x102f4ec54         -[MSIDSilentTokenRequest executeRequestImpl:]
33  MSAL                            0x102ee5af8         __78-[MSIDAuthority resolveAndValidate:userPrincipalName:context:completionBlock:]_block_invoke
34  MSAL                            0x102ec1384         -[MSIDAadAuthorityResolver handleRecord:authority:completionBlock:]
35  MSAL                            0x102ec0744         -[MSIDAadAuthorityResolver resolveAuthority:userPrincipalName:validate:context:completionBlock:]
36  MSAL                            0x102ee5890         -[MSIDAuthority resolveAndValidate:userPrincipalName:context:completionBlock:]
37  MSAL                            0x102f4db60         -[MSIDSilentTokenRequest executeRequestWithCompletion:]
38  MSAL                            0x102f08580         -[MSIDSilentController acquireTokenWithRequest:completionBlock:]
39  MSAL                            0x102f08224         -[MSIDSilentController acquireToken:]
40  MSAL                            0x102e9a8a0         -[MSALPublicClientApplication acquireTokenSilentWithParameters:completionBlock:]
41  SMS Lite                        0x200f3d7c8         <redacted>
42  SMS Lite                        0x201096504         <redacted>
43  libdispatch.dylib               0x3008ac920         _dispatch_call_block_and_release
44  libdispatch.dylib               0x3008ae66c         _dispatch_client_callout
45  libdispatch.dylib               0x3008b5df0         _dispatch_lane_serial_drain
46  libdispatch.dylib               0x3008b6964         _dispatch_lane_invoke
47  libdispatch.dylib               0x3008c11b4         _dispatch_workloop_worker_thread
48  libsystem_pthread.dylib         0x3e36c90f0         _pthread_wqthread

Thread 0
0   libsystem_kernel.dylib          0x36fd3d504         mach_msg_trap
1   libsystem_kernel.dylib          0x36fd3db98         mach_msg
2   CoreFoundation                  0x300ea3734         __CFRunLoopServiceMachPort
3   CoreFoundation                  0x300ea7a28         __CFRunLoopRun
4   CoreFoundation                  0x300ebb464         CFRunLoopRunSpecific
5   GraphicsServices                0x338619388         GSEventRunModal
6   UIKitCore                       0x305d075cc         -[UIApplication _run]
7   UIKitCore                       0x305a85f70         UIApplicationMain
8   SMS Lite                        0x200584f88         <redacted>
9   <unknown>                       0x102be5aa4         <redacted>

Thread 1
0   libsystem_kernel.dylib          0x36fd3dae4         __semwait_signal
1   libsystem_c.dylib               0x316d2aefc         nanosleep
2   libsystem_c.dylib               0x316d3ef38         sleep
3   MobileProtect                   0x102c898b8         __27-[DTDebuggerAttached setup]_block_invoke
4   libdispatch.dylib               0x3008ac920         _dispatch_call_block_and_release
5   libdispatch.dylib               0x3008ae66c         _dispatch_client_callout
6   libdispatch.dylib               0x3008b5df0         _dispatch_lane_serial_drain
7   libdispatch.dylib               0x3008b6964         _dispatch_lane_invoke
8   libdispatch.dylib               0x3008c11b4         _dispatch_workloop_worker_thread
9   libsystem_pthread.dylib         0x3e36c90f0         _pthread_wqthread

Thread 2
0   libswiftCore.dylib              0x30a6f142c         swift::Demangle::__runtime::TypeDecoder<T>::decodeMangledProtocolType
1   libswiftCore.dylib              0x30a6f13c8         swift::Demangle::__runtime::TypeDecoder<T>::decodeMangledProtocolType
2   libswiftCore.dylib              0x30a6ee2b4         swift::Demangle::__runtime::TypeDecoder<T>::decodeMangledType
3   libswiftCore.dylib              0x30a6f4404         swift::Demangle::__runtime::TypeDecoder<T>::decodeMangledFunctionInputType::lambda::operator()
4   libswiftCore.dylib              0x30a6f1d14         swift::Demangle::__runtime::TypeDecoder<T>::decodeMangledFunctionInputType
5   libswiftCore.dylib              0x30a6ed054         swift::Demangle::__runtime::TypeDecoder<T>::decodeMangledType
6   libswiftCore.dylib              0x30a6ea888         swift_getTypeByMangledNodeImpl
7   libswiftCore.dylib              0x30a6ea48c         swift::swift_getTypeByMangledNode
8   libswiftCore.dylib              0x30a6eaea8         swift_getTypeByMangledNameImpl
9   libswiftCore.dylib              0x30a6e7810         swift::swift_getTypeByMangledName
10  libswiftCore.dylib              0x30a6e7b20         swift_getTypeByMangledNameInContext
11  AttributeGraph                  0x364ff5c5c         AG::swift::metadata::mangled_type_name_ref
12  AttributeGraph                  0x364ff69e8         AG::swift::metadata_visitor::visit_field
13  AttributeGraph                  0x364ff52bc         AG::swift::metadata::visit
14  AttributeGraph                  0x364ff3510         AG::LayoutDescriptor::Builder::visit_element
15  AttributeGraph                  0x364ff6a20         AG::swift::metadata_visitor::visit_field
16  AttributeGraph                  0x364ff52bc         AG::swift::metadata::visit
17  AttributeGraph                  0x364ff3510         AG::LayoutDescriptor::Builder::visit_element
18  AttributeGraph                  0x364ff6a20         AG::swift::metadata_visitor::visit_field
19  AttributeGraph                  0x364ff52bc         AG::swift::metadata::visit
20  AttributeGraph                  0x364ff3510         AG::LayoutDescriptor::Builder::visit_element
21  AttributeGraph                  0x364ff6a20         AG::swift::metadata_visitor::visit_field
22  AttributeGraph                  0x364ff52bc         AG::swift::metadata::visit
23  AttributeGraph                  0x364ff3510         AG::LayoutDescriptor::Builder::visit_element
24  AttributeGraph                  0x364ff6a20         AG::swift::metadata_visitor::visit_field
25  AttributeGraph                  0x364ff52bc         AG::swift::metadata::visit
26  AttributeGraph                  0x364ff5730         AG::LayoutDescriptor::make_layout
27  AttributeGraph                  0x364ff6af4         AG::(anonymous namespace)::LayoutCache::drain_queue
28  libdispatch.dylib               0x3008ae66c         _dispatch_client_callout
29  libdispatch.dylib               0x3008bfefc         _dispatch_root_queue_drain
30  libdispatch.dylib               0x3008c0604         _dispatch_worker_thread2
31  libsystem_pthread.dylib         0x3e36c90b4         _pthread_wqthread

Thread 3
0   libsystem_kernel.dylib          0x36fd3d504         mach_msg_trap
1   libsystem_kernel.dylib          0x36fd3db98         mach_msg
2   libdispatch.dylib               0x3008c9288         _dispatch_mach_send_and_wait_for_reply
3   libdispatch.dylib               0x3008c9638         dispatch_mach_send_with_result_and_wait_for_reply
4   libxpc.dylib                    0x3e370cb98         xpc_connection_send_message_with_reply_sync
5   Foundation                      0x303f25140         __NSXPCCONNECTION_IS_WAITING_FOR_A_SYNCHRONOUS_REPLY__
6   Foundation                      0x303f2b0c0         -[NSXPCConnection _sendInvocation:orArguments:count:methodSignature:selector:withProxy:]
7   Foundation                      0x303f641e0         -[NSXPCConnection _sendSelector:withProxy:arg1:arg2:]
8   Foundation                      0x303f78c5c         _NSXPCDistantObjectSimpleMessageSend2
9   CoreTelephony                   0x301c9d2e0         -[CoreTelephonyClient(Subscriber) copyMobileSubscriberCountryCode:error:]
10  CoreTelephony                   0x301c9e91c         -[CTTelephonyNetworkInfo getMobileCountryCode:andIsoCountryCode:forContext:withError:]
11  CoreTelephony                   0x301ca1354         -[CTTelephonyNetworkInfo updateNetworkInfoAndShouldNotifyClient:forContext:]
12  CoreTelephony                   0x301c90624         -[CTTelephonyNetworkInfo initWithClient:]
13  CoreTelephony                   0x301c96f9c         -[CTTelephonyNetworkInfo init]
14  Heap                            0x102b2c7d8         +[Heap getCarrier]
15  Heap                            0x102b2b730         __37+[Heap unsafeInitialize:withOptions:]_block_invoke
16  Heap                            0x102b39038         __108+[NSBlockOperation HEAP_safeBlockOperationWithBlock:fromObject:selector:bailOnException:skipIfBailed:]_block_invoke
17  Foundation                      0x303f36c60         __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
18  Foundation                      0x303f48df4         -[NSBlockOperation main]
19  Foundation                      0x303f21780         __NSOPERATION_IS_INVOKING_MAIN__
20  Foundation                      0x303f326fc         -[NSOperation start]
21  Foundation                      0x303f35ca8         __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__
22  Foundation                      0x303f43d4c         __NSOQSchedule_f
23  libdispatch.dylib               0x3008ac920         _dispatch_call_block_and_release
24  libdispatch.dylib               0x3008ae66c         _dispatch_client_callout
25  libdispatch.dylib               0x3008b1b40         _dispatch_continuation_pop
26  libdispatch.dylib               0x3008b119c         _dispatch_async_redirect_invoke
27  libdispatch.dylib               0x3008bfddc         _dispatch_root_queue_drain
28  libdispatch.dylib               0x3008c0604         _dispatch_worker_thread2
29  libsystem_pthread.dylib         0x3e36c90b4         _pthread_wqthread

Thread 4 Crashed:
0   libsystem_kernel.dylib          0x36fd43964         __pthread_kill
1   libsystem_pthread.dylib         0x3e36cf374         pthread_kill
2   libsystem_c.dylib               0x316d45f4c         abort
3   libsystem_malloc.dylib          0x3249b5a04         malloc_vreport
4   libsystem_malloc.dylib          0x3249b5ca0         malloc_zone_error
5   libsystem_malloc.dylib          0x3249b0174         nanov2_allocate_from_block
6   libsystem_malloc.dylib          0x3249af218         nanov2_allocate
7   libsystem_malloc.dylib          0x3249af808         nanov2_calloc
8   libsystem_malloc.dylib          0x32499e080         _malloc_zone_calloc
9   CoreFoundation                  0x300ec7d64         _CFRuntimeCreateInstance
10  CoreFoundation                  0x300ec3f9c         __CFStringCreateImmutableFunnel3
11  CoreFoundation                  0x300ee3e48         CFStringCreateWithSubstring
12  CoreFoundation                  0x300edea64         _retainedComponentString
13  CoreFoundation                  0x300ec66f4         CFURLCreateStringWithFileSystemPath
14  CoreFoundation                  0x300ecc340         CFURLCopyFileSystemPath
15  Foundation                      0x303f06c64         -[NSURL(NSURL) path]
16  Foundation                      0x303f35b64         -[NSURL(NSURLPathUtilities) pathComponents]
17  MSAL                            0x102f0e3d8         +[MSIDADFSAuthority isAuthorityFormatValid:context:error:]
18  MSAL                            0x102f05380         +[MSIDAADAuthority isAuthorityFormatValid:context:error:]
19  MSAL                            0x102f058b4         +[MSIDAADAuthority realmFromURL:context:error:]
20  MSAL                            0x102ee54b8         -[MSIDAuthority initWithURL:validateFormat:context:error:]
21  MSAL                            0x102f0495c         -[MSIDAADAuthority initWithURL:context:error:]
22  MSAL                            0x102f04b24         -[MSIDAADAuthority initWithURL:rawTenant:context:error:]
23  MSAL                            0x102ebfb60         -[MSIDAADRequestConfigurator configure:]
24  MSAL                            0x102f0aa20         -[MSIDAADRefreshTokenGrantRequest initWithEndpoint:authScheme:clientId:redirectUri:enrollmentId:scope:refreshToken:claims:extraParameters:context:]
25  MSAL                            0x102f0f4d0         -[MSIDAADV2Oauth2Factory refreshTokenRequestWithRequestParameters:refreshToken:]
26  MSAL                            0x102f502a4         -[MSIDSilentTokenRequest acquireTokenWithRefreshTokenImpl:completionBlock:]
27  MSAL                            0x102ee5fb8         -[MSIDAuthority loadOpenIdMetadataWithContext:completionBlock:]
28  MSAL                            0x102f4fe48         -[MSIDSilentTokenRequest redeemAccessTokenWith:completionBlock:]
29  MSAL                            0x102f4f5d4         -[MSIDSilentTokenRequest tryRefreshToken:tokenType:completionBlock:]
30  MSAL                            0x102f4ed34         __45-[MSIDSilentTokenRequest executeRequestImpl:]_block_invoke.125
31  MSAL                            0x102f4f2d0         -[MSIDSilentTokenRequest fetchCachedTokenAndCheckForFRTFirst:shouldComplete:completionHandler:]
32  MSAL                            0x102f4ec54         -[MSIDSilentTokenRequest executeRequestImpl:]
33  MSAL                            0x102ee5af8         __78-[MSIDAuthority resolveAndValidate:userPrincipalName:context:completionBlock:]_block_invoke
34  MSAL                            0x102ec1384         -[MSIDAadAuthorityResolver handleRecord:authority:completionBlock:]
35  MSAL                            0x102ec0744         -[MSIDAadAuthorityResolver resolveAuthority:userPrincipalName:validate:context:completionBlock:]
36  MSAL                            0x102ee5890         -[MSIDAuthority resolveAndValidate:userPrincipalName:context:completionBlock:]
37  MSAL                            0x102f4db60         -[MSIDSilentTokenRequest executeRequestWithCompletion:]
38  MSAL                            0x102f08580         -[MSIDSilentController acquireTokenWithRequest:completionBlock:]
39  MSAL                            0x102f08224         -[MSIDSilentController acquireToken:]
40  MSAL                            0x102e9a8a0         -[MSALPublicClientApplication acquireTokenSilentWithParameters:completionBlock:]
41  SMS Lite                        0x200f3d7c8         <redacted>
42  SMS Lite                        0x201096504         <redacted>
43  libdispatch.dylib               0x3008ac920         _dispatch_call_block_and_release
44  libdispatch.dylib               0x3008ae66c         _dispatch_client_callout
45  libdispatch.dylib               0x3008b5df0         _dispatch_lane_serial_drain
46  libdispatch.dylib               0x3008b6964         _dispatch_lane_invoke
47  libdispatch.dylib               0x3008c11b4         _dispatch_workloop_worker_thread
48  libsystem_pthread.dylib         0x3e36c90f0         _pthread_wqthread

Thread 5 name: com.apple.uikit.eventfetch-thread
0   libsystem_kernel.dylib          0x36fd3d504         mach_msg_trap
1   libsystem_kernel.dylib          0x36fd3db98         mach_msg
2   CoreFoundation                  0x300ea3734         __CFRunLoopServiceMachPort
3   CoreFoundation                  0x300ea7a28         __CFRunLoopRun
4   CoreFoundation                  0x300ebb464         CFRunLoopRunSpecific
5   Foundation                      0x303efec90         -[NSRunLoop(NSRunLoop) runMode:beforeDate:]
6   Foundation                      0x303f3fdc4         -[NSRunLoop(NSRunLoop) runUntilDate:]
7   UIKitCore                       0x305c80748         -[UIEventFetcher threadMain]
8   Foundation                      0x303f4e408         __NSThread__start__
9   libsystem_pthread.dylib         0x3e36c99a0         _pthread_start

Thread 6
0   libobjc.A.dylib                 0x332044bf0         objc_opt_isKindOfClass
1   libswiftCore.dylib              0x30a703ebc         swift_dynamicCastObjCClassImpl
2   libswiftCore.dylib              0x30a6bce88         tryCastToObjectiveCClass
3   libswiftCore.dylib              0x30a6bb208         tryCast
4   libswiftCore.dylib              0x30a6bb4d8         tryCast
5   libswiftCore.dylib              0x30a6badb0         swift_dynamicCastImpl
6   libswiftFoundation.dylib        0x309c92314         __JSONDecoder.container<T>
7   libswiftFoundation.dylib        0x309c866f0         __JSONDecoder
8   libswiftCore.dylib              0x30a6862e4         Decoder.container<T>
9   SMS Lite                        0x201e72038         <redacted>
10  SMS Lite                        0x201e702c8         <redacted>
11  libswiftCore.dylib              0x30a6861c0         Decodable.init
12  libswiftFoundation.dylib        0x309c887c8         __JSONDecoder.unbox_
13  libswiftFoundation.dylib        0x309c743f8         JSONDecoder.decode<T>
14  libswiftFoundation.dylib        0x309cac3f0         JSONDecoder.decode<T>
15  SMS Lite                        0x200a80d84         <redacted>
16  SMS Lite                        0x201096504         <redacted>
17  libdispatch.dylib               0x3008ac920         _dispatch_call_block_and_release
18  libdispatch.dylib               0x3008ae66c         _dispatch_client_callout
19  libdispatch.dylib               0x3008b1794         _dispatch_queue_override_invoke
20  libdispatch.dylib               0x3008bfddc         _dispatch_root_queue_drain
21  libdispatch.dylib               0x3008c0604         _dispatch_worker_thread2
22  libsystem_pthread.dylib         0x3e36c90b4         _pthread_wqthread

Thread 7
0   libsystem_kernel.dylib          0x36fd3db2c         __workq_kernreturn
1   libsystem_pthread.dylib         0x3e36c913c         _pthread_wqthread

Thread 8
0   libsystem_kernel.dylib          0x36fd3dae4         __semwait_signal
1   libsystem_c.dylib               0x316d2aefc         nanosleep
2   libsystem_c.dylib               0x316d3ef38         sleep
3   SMS Lite                        0x201fa4964         __cxa_throw
4   libsystem_pthread.dylib         0x3e36c99a0         _pthread_start

Thread 9
0   libsystem_kernel.dylib          0x36fd3d504         mach_msg_trap
1   libsystem_kernel.dylib          0x36fd3db98         mach_msg
2   libsystem_kernel.dylib          0x36fd4922c         thread_suspend
3   SMS Lite                        0x201fa0650         __cxa_throw
4   libsystem_pthread.dylib         0x3e36c99a0         _pthread_start

Thread 10
0   libsystem_kernel.dylib          0x36fd3d504         mach_msg_trap
1   libsystem_kernel.dylib          0x36fd3db98         mach_msg
2   SMS Lite                        0x201fa067c         __cxa_throw
3   libsystem_pthread.dylib         0x3e36c99a0         _pthread_start

Thread 11
0   libsystem_kernel.dylib          0x36fd3dae4         __semwait_signal
1   libsystem_c.dylib               0x316d2aefc         nanosleep
2   Foundation                      0x303f60a14         +[NSThread sleepForTimeInterval:]
3   SMS Lite                        0x201f59d3c         <redacted>
4   Foundation                      0x303f4e408         __NSThread__start__
5   libsystem_pthread.dylib         0x3e36c99a0         _pthread_start

Thread 12
0   libsystem_kernel.dylib          0x36fd3d504         mach_msg_trap
1   libsystem_kernel.dylib          0x36fd3db98         mach_msg
2   CoreFoundation                  0x300ea3734         __CFRunLoopServiceMachPort
3   CoreFoundation                  0x300ea7a28         __CFRunLoopRun
4   CoreFoundation                  0x300ebb464         CFRunLoopRunSpecific
5   AudioSession                    0x31370a304         CADeprecated::GenericRunLoopThread::Entry
6   AudioSession                    0x313713d60         CADeprecated::CAPThread::Entry
7   libsystem_pthread.dylib         0x3e36c99a0         _pthread_start

Thread 13
0   libsystem_kernel.dylib          0x36fd3db2c         __workq_kernreturn
1   libsystem_pthread.dylib         0x3e36c913c         _pthread_wqthread

Thread 14
0   libsystem_kernel.dylib          0x36fd3db2c         __workq_kernreturn
1   libsystem_pthread.dylib         0x3e36c913c         _pthread_wqthread

Thread 15
0   libsystem_pthread.dylib         0x3e36c8e8c         start_wqthread

Thread 16
0   libsystem_kernel.dylib          0x36fd3db2c         __workq_kernreturn
1   libsystem_pthread.dylib         0x3e36c913c         _pthread_wqthread

Thread 17
0   libsystem_kernel.dylib          0x36fd3db2c         __workq_kernreturn
1   libsystem_pthread.dylib         0x3e36c913c         _pthread_wqthread

**Comment by swasti29** [comment]
@robin202205 Can you help with authority url passing. Also we do not support ADFS Authority with MSAL.

**Comment by alberto093** [comment]
@swasti29 news about ADFS?
