### ISSUE TITLE
NSOSStatusErrorDomain Code=-34018 "Client explicitly specifies access group XXXX.com.microsoft.adalcach

### ISSUE THREAD

**Issue by ankasani** [AzureAD/microsoft-authentication-library-for-objc#1591]
Hi Team,  I am using the sample, i have change the bundle ID and my Azure app registered details.
https://learn.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-ios

Locally it was working fine! but when we run the app center test (http://appcenter.ms), I see below issue (this is in all devices and all version of ios)

<img width="288" alt="image" src="https://user-images.githubusercontent.com/35102519/197235717-7f1f2c96-7b83-460e-8f8e-46feb45f89be.png">

In devices logs I see error like below:
MSALiOS[1391]/1#18 LF=0 copy_matching Error Domain=NSOSStatusErrorDomain Code=-34018 "Client explicitly specifies access group B6N6VT45UJ.com.microsoft.adalcache but is only entitled for (
    "B6N6VT45UJ.*",
    "B6N6VT45UJ.com.xamarin.xtcapp9",
    "group.com.xamarin.xtcapp9.group9",
    "group.com.xamarin.xtcapp9.group8",
    "group.com.xamarin.xtcapp9.group7",
    "group.com.xamarin.xtcapp9.group6",
    "group.com.xamarin.xtcapp9.group5",
    "group.com.xamarin.xtcapp9.group4",
    "group.com.xamarin.xtcapp9.group3",
    "group.com.xamarin.xtcapp9.group2",
    "group.com.xamarin.xtcapp9.group10",
    "group.com.xamarin.xtcapp9.group1",
    "com.apple.token"
)" UserInfo={numberOfErrorsDeep=0, NSDescription=Client explicitly specifies access group B6N6VT45UJ.com.microsoft.adalcache but is only entitled for (
    "B6N6VT45UJ.*",
    "B6N6VT45UJ.com.xamarin.xtcapp9",
    "group.com.xamarin.xtcapp9.group9",
    "group.com.xamarin.xtcapp9.group8",
    "group.com.xamarin.xtcapp9.group7",
[m[0;37mOct 21 15:21:23 [1;36msecurityd[0;36m[99] [0;32m<Notice>:[1;37m MSALiOS[1391]/1#18 LF=0 copy_matching Error Domain=NSOSStatusErrorDomain Code=-34018 "Client explicitly specifies access group B6N6VT45UJ.com.microsoft.workplacejoin but is only entitled for (
    "B6N6VT45UJ.*",
    "B6N6VT45UJ.com.xamarin.xtcapp9",
    "group.com.xamarin.xtcapp9.group9",
    "group.com.xamarin.xtcapp9.group8",
    "group.com.xamarin.xtcapp9.group7",
    "group.com.xamarin.xtcapp9.group6",
    "group.com.xamarin.xtcapp9.group5",
    "group.com.xamarin.xtcapp9.group4",
    "group.com.xamarin.xtcapp9.group3",
    "group.com.xamarin.xtcapp9.group2",
    "group.com.xamarin.xtcapp9.group10",
    "group.com.xamarin.xtcapp9.group1",
    "com.apple.token"
)" UserInfo={numberOfErrorsDeep=0, NSDescription=Client explicitly specifies access group B6N6VT45UJ.com.microsoft.workplacejoin but is only entitled for (
    "B6N6VT45UJ.*",
    "B6N6VT45UJ.com.xamarin.xtcapp9",
    "group.com.xamarin.xtcapp9.group9",
    "group.com.xamarin.xtcapp9.group8",
    "group.com.xamarin.xtcapp9.grou
[m[0;37mOct 21 15:21:23 [1;36mMSALiOS[0;36m(AppSSOCore)[1391] [0;32m<Notice>:[1;37m -[SOConfigurationClient init]  on <private>
[m[0;37mOct 21 15:21:23 [1;36mMSALiOS[0;36m(AppSSOCore)[1391] [0;32m<Notice>:[1;37m <SOServiceConnection: 0x280d385e0>: new XPC connection
[m[0;37mOct 21 15:21:23 [1;36msecurityd[0;36m[99] [0;32m<Notice>:[1;37m MSALiOS[1391]/1#18 LF=0 copy_matching Error Domain=NSOSStatusErrorDomain Code=-34018 "Client explicitly specifies access group B6N6VT45UJ.com.microsoft.workplacejoin.v2 but is only entitled for (
    "B6N6VT45UJ.*",
    "B6N6VT45UJ.com.xamarin.xtcapp9",
    "group.com.xamarin.xtcapp9.group9",
    "group.com.xamarin.xtcapp9.group8",
    "group.com.xamarin.xtcapp9.group7",
    "group.com.xamarin.xtcapp9.group6",
    "group.com.xamarin.xtcapp9.group5",
    "group.com.xamarin.xtcapp9.group4",
    "group.com.xamarin.xtcapp9.group3",
    "group.com.xamarin.xtcapp9.group2",
    "group.com.xamarin.xtcapp9.group10",
    "group.com.xamarin.xtcapp9.group1",
    "com.apple.token"
)" UserInfo={numberOfErrorsDeep=0, NSDescription=Client explicitly specifies access group B6N6VT45UJ.com.microsoft.workplacejoin.v2 but is only entitled for (
    "B6N6VT45UJ.*",
    "B6N6VT45UJ.com.xamarin.xtcapp9",
    "group.com.xamarin.xtcapp9.group9",
    "group.com.xamarin.xtcapp9.group8",
    "group.com.xamarin.xtcapp

**Note: App Center will do resign the uploded ios app when doing test on app center test cloud devices with there profile and cert!**

This is similer issue with dotnet library also with app center
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/783

In this about issue link i see:
If going through AppCenter, you might have to use a wildcard...we have to do something [similar](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/tests/devapps/XForms/XForms/TestPage.xaml.cs#L52) for our AppCenter builds to work
**builder.WithIosKeychainSecurityGroup("*");**

So, Is there any similar think is there with swift library also ?

**Comment by swasti29** [comment]
@ankasani We do not have any simillar thing for swift lib now. You can try the same thing sd for donet.

**Comment by ankasani** [comment]
@swasti29 Thanks, Please can you share any sample if you have, how to use the .Net for Swift ?

**Comment by swasti29** [comment]
@ankasani 
The error: "-34018" translates to errSecMissingEntitlement. This means that your app is trying to use a keychain access group for which it does not have entitlements." - from this [Apple forum post](https://developer.apple.com/forums/thread/114456). Please check if the necessary keychain groups were added to your application for the release build uploaded in app center, according to the [MSAL doc](https://github.com/AzureAD/microsoft-authentication-library-for-objc#adding-msal-to-your-project).

**Comment by ankasani** [comment]
@swasti29 , As i mentioned in the previous message.

**Note:** App Center will do **resign** the uploded ios app when doing test on app center test cloud devices with there profile and cert!

So, to overcome this we need to use like below : 
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/783
**builder.WithIosKeychainSecurityGroup("*");**


so, Is there any possibility of using the same in the native ios msal project ?

**Comment by swasti29** [comment]
@ankasani As mentioned [here](https://discussions.apple.com/thread/430971?answerId=2068075022#2068075022) Keychain holds specific text and therefore cannot be 'scriptable'. I would suggest to reach out the App center team for this request.

**Comment by kaisong1990** [comment]
There is no active conversation for more than a month, closing..

@ankasani Feel free to reopen if you still had issues
