### ISSUE TITLE
Not all oauth errors are mapped correctly

### ISSUE THREAD

**Issue by oldalton** [AzureAD/microsoft-authentication-library-for-objc#160]
MSALErrorCodeForOAuthError maps only invalid_request and invalid_client to MSALErrors, but there 6 total errors to map according to documentation: https://tools.ietf.org/html/rfc6749#section-5.2. I think 6 errors is not that many to map them all. Currently when we get invalid_scope from server, we still return interactionRequired error.

**Comment by RPangrle** [comment]
We're not looking for a 1:1 mapping of OAuth errors as several them end up devolving to internal errors in the library itself that are not actionable by an app developer.

**Comment by oldalton** [comment]
Yes, but currently for example invalid_scope ends up with InteractionRequired, which will trigger UI. Should we instead return a better default error maybe?
