### ISSUE TITLE
Error for Undefined symbol _MSID_BROKER_APP_BUNDLE_ID and _MSID_BROKER_APP_BUNDLE_ID_DF

### ISSUE THREAD

**Issue by MaiquanNguyen** [AzureAD/microsoft-authentication-library-for-objc#1617]
Hi i just updated pod of MSAL to 1.2.5 and go this error when compile the project
```
error build: Undefined symbol: _MSID_BROKER_APP_BUNDLE_ID
error build: Undefined symbol: _MSID_BROKER_APP_BUNDLE_ID_DF
```
Don't know what cause it, the project still work fine until i change the version of MSAL to latest.

**Comment by swasti29** [comment]
I have tried updating MSAL to the 1.2.5 version in our MSAL Sample App, i did see any issues. I have done giving exact version in the pod file and then did Pod update. The constants "MSID_BROKER_APP_BUNDLE_ID and MSID_BROKER_APP_BUNDLE_ID_DF" are still the part of latest build.  Also now we have 1.2.6, I would suggest updating to this version. If you still see the issue, Kindly help me with the steps how you are updating to latest.
<img width="701" alt="image" src="https://user-images.githubusercontent.com/12692041/205745093-558d88c0-1695-4c87-ba99-3cb7873aecc5.png">

**Comment by ameyapat** [comment]
@MaiquanNguyen Closing this for now. Feel free to reopen if the issue persists.
