### ISSUE TITLE
"Cancel" button instead of "Done" button

### ISSUE THREAD

**Issue by dheeraj1603** [AzureAD/microsoft-authentication-library-for-objc#1624]
We see here, a **Cancel** button to dismiss the popover. As per the Apple Human Interface Guideline, we should have “**Done**” button to simply dismiss the screen. There is nothing to cancel, because you're already signed out.

![You're signed out here, but](https://user-images.githubusercontent.com/119605705/205749061-40bf51d5-4188-4bbb-a791-191a888b9e11.png)

**Comment by sharmadhiraj86** [comment]
Hii @dheeraj1603 Can I work on this issue? If yes, please specify the file in which the change needs to be made.

**Comment by juan-arias** [comment]
Hi @dheeraj1603, similar to https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1623, this is handled by the OS and we cannot customize.
