### ISSUE TITLE
Error for only some rare users: The request is malformed or incorrect

### ISSUE THREAD

**Issue by john-work-ios** [AzureAD/microsoft-authentication-library-for-objc#1628]
Using MSAL 1.1.24 in an app that supports uploading to OneDrive for a year now.
Some users reported that they sometimes (not 100% of the time) see their upload fail.
The error message is "The request is malformed or incorrect".
Attached is a screenshot with the full error message returned by the servers:
![msal_error](https://user-images.githubusercontent.com/87691187/207138323-07d919d1-76f1-417e-ab13-954c14bf0392.jpg)

What should I do to fix this?

Thanks!!

**Comment by ameyapat** [comment]
I'm not sure if this issue relates to MSAL. If you feel this is related to MSAL, please provide MSAL logs so that we can investigate. Can you contact the graph/OneDrive teams regarding this?

**Comment by ameyapat** [comment]
Closing issue. Please provide MSAL logs if the issue relates to MSAL. Thanks!
