### ISSUE TITLE
Can not get MSALResult from Microsoft Authenticator Broker

### ISSUE THREAD

**Issue by suzhen-github** [AzureAD/microsoft-authentication-library-for-objc#1629]
hi, I tried to acquire the access token from the Microsoft Authenticator Broker with the following interactively method.
and I have configed all the necessary informations step by step as described in the https://github.com/AzureAD/microsoft-authentication-library-for-objc;
However I could not get the MSALResult from acquireTokenWithParameters:parameters completionBlock:^(MSALResult *result, NSError *error)
I have also tried to insert some Nslogs into MSIDBrokerInteractiveController of MSAL and my MSALUtil, I found the following cases.
 1."[MSAL] Beginning broker flow." can be output, but "[MSAL] Broker flow finished." can not be found.
 2.method[completeAcquireToken] is excuted,but method[completeAcquireTokenWithResult] seems not to be excuted.
  ***Please see #[MSAL_SelfInsert_Log].

 3.The following completionBlock code of acquireTokenWithParameters can not be excuted.

*MSALUtil.m
 *signInAccountWithParentController
    *    [application acquireTokenWithParameters:parameters completionBlock:^(MSALResult *result, NSError *error)
	 {
---------->>>The following completionBlock can not be excuted
	        if (error)
	        {
	            signInBlock(nil, nil, error);
	            return;
	        }
	        
	        // In the initial acquire token call we'll want to look at the account object
	        // that comes back in the result.
	        MSALAccount *account = result.account;
	        
	        // The identifier in the MSALAccount is the key to retrieve this account from
	        // the cache in the future. Save this piece of information in a place you can
	        // easily retrieve in your app. In this case we're going to store it in
	        // NSUserDefaults.
	        [[NSUserDefaults standardUserDefaults] setValue:account.homeAccountId.identifier forKey:CURRENT_ACCOUNT_KEY];
	        
	        signInBlock(account, result.accessToken, error);
	 }];

About MSAL Log and [MSAL_SelfInsert_Log], Please see the attached file [To_MSAL_QA.txt].
I would be very grateful for your help!

[To_MSAL_QA.txt](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/10241991/To_MSAL_QA.txt)
[AppDelegate.txt](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/10241981/AppDelegate.txt)
[LoginViewController.txt](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/10241982/LoginViewController.txt)
[MSALUtil.txt](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/10241983/MSALUtil.txt)
[MSIDBrokerInteractiveController.txt](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/10241984/MSIDBrokerInteractiveController.txt)

**Comment by mipetriu** [comment]
Hi @suzhen-github, I see in your logs that you mention "Step2.Select login user from Microsoft Authenticator Broker". Just to confirm, you're seeing that the UI is flipped to Microsoft Authenticator app to continue your login? If so, could you reproduce the issue again, send logs from the Authenticator app, and then provide us an incidentID given when you submit?

**Comment by suzhen-github** [comment]
> 
thank you for your reply.
>>I see in your logs that you mention "Step2.Select login user from Microsoft Authenticator Broker". Just to confirm, you're >>seeing that the UI is flipped to Microsoft Authenticator app to continue your login?
--->Yes, First I opened my app, then it would call Microsoft Authenticator app automatically, and the UI is flipped to Microsoft Authenticator app to let me select a login user,  After I selected login user from Microsoft Authenticator app Such as Step2,  
the UI would be flipped to Microsoft Authenticator app again in a few seconds. 

>>If so, could you reproduce the issue again, send logs from the Authenticator app, and then provide us an incidentID given >>when you submit?
--->I am sorry, I don't know how to get logs from Authenticator app. If you know it, please tell me.
I would be very grateful for your help!

**Comment by suzhen-github** [comment]
@mipetriu
thank you for your reply.
>>I see in your logs that you mention "Step2.Select login user from Microsoft Authenticator Broker". Just to confirm, you're >>seeing that the UI is flipped to Microsoft Authenticator app to continue your login?
--->Yes, First I opened my app, then it would call  Microsoft Authenticator app automatically, and the UI is flipped to Microsoft Authenticator app to let me select a login user,  After I selected login user from Microsoft Authenticator app Such as Step2,  
the UI would be flipped to Microsoft Authenticator app again in a few seconds. 

>>If so, could you reproduce the issue again, send logs from the Authenticator app, and then provide us an incidentID given >>when you submit?
--->I am sorry, I don't know how to get logs from Authenticator app. If you know it, please tell me.
I would be very grateful for your help!

**Comment by suzhen-github** [comment]
Hi @mipetriu 
I have uploaded  the logs from Authenticator app with different Azure AD.
Please Confirm them. Thanks!

[AuthenticatorLog_Azure AD1.txt](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/10285897/AuthenticatorLog_Azure.AD1.txt)
[AuthenticatorLog_Azure AD2.txt](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/10285898/AuthenticatorLog_Azure.AD2.txt)

**Comment by mipetriu** [comment]
@suzhen-github Thank you for sending, I will take a look and let you know what I'm seeing.

**Comment by mipetriu** [comment]
Hi @suzhen-github, I've taken a look at the logs from the Authenticator, and it seems that the responses are being sent back to the app properly with the intended authentication tokens.

I saw you mentioned this:
_"First I opened my app, then it would call Microsoft Authenticator app automatically, and the UI is flipped to Microsoft Authenticator app to let me select a login user, After I selected login user from Microsoft Authenticator app Such as Step2,
the UI would be flipped to Microsoft Authenticator app again in a few seconds."_

In your MSAL_QA logs, it seems that you're sending multiple authentication requests in quick succession - I'm seeing log lines that indicate another UI switch to the Authenticator is being prepared as MSAL is starting to process a token response. If you run a test specifically to request a token interactively only once, are you able to get the MSALResult?

**Comment by suzhen-github** [comment]
Hi @mipetriu
I am sorry to be late for reply.

I have confirmed my source, I did not find that how I sent multiple authentication requests in quick succession.
Could you please confirm them in the following attached source files? Is there any mistake on using MSAL?

Thanks!
I would be very grateful for your help!

[AppDelegate.txt](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/10452514/AppDelegate.txt)
[LoginViewController.txt](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/10452515/LoginViewController.txt)
[MSALUtil.txt](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/10452516/MSALUtil.txt)

**Comment by mipetriu** [comment]
Hi @suzhen-github, I may have misread the MSAL_QA logs from your application, I didn't realize the snippets were from different time periods. Do you mind sharing a full MSAL log from your application, so I can follow the whole story. Thank you!

**Comment by mipetriu** [comment]
Hello, this issue has remained inactive for a longer period of time, so I will close it. If you'd like to continue investigation and would be willing to provide a new set of logs, please feel free to re-open.
