### ISSUE TITLE
Login prompt does not allow switching to a different email address

### ISSUE THREAD

**Issue by guidedways** [AzureAD/microsoft-authentication-library-for-objc#1632]
Please see screenshot - the user has logged into one of his accounts, but when he adds another account, the login prompt shows him his "currently logged in account" and won't let him switch or change. What do we have to do to force the web view to allow them to switch to a different account?

![Attachment](https://user-images.githubusercontent.com/202437/210295303-582e7d99-fc58-419b-910d-f007a0f91d58.png)

**Comment by guidedways** [comment]
We were using `MSALPromptTypePromptIfNecessary` - does that not work?

**Comment by guidedways** [comment]
Docs for this say:

```
/**
     The SSO experience will be determined by the presence of cookies in the webview and account type.
     User won't be prompted unless necessary.
     If multiple users are signed in, select account experience will be presented.
     */
```

So I'm assuming this should have worked, but it does not as you can see.

**Comment by jasoncoolmax** [comment]
The comment means that if there are cookies, it will use cookies. That's why you see a logged in account being shown there.

**Comment by guidedways** [comment]
Thanks - we'll switch to `MSALPromptTypeLogin` and see if this helps - will re-open if this remains an issue.
