### ISSUE TITLE
Can't figure out the authority for my B2C instance

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [AzureAD/microsoft-authentication-library-for-objc#1633]
I have created a B2C instance called `myB2CDemonstration` and there I created a Experience Framework flow called `B2C_1A-SIGNUP_SIGNIN`.

My code looks like this:

```swift
let kClientID = "d7628 ... 4a34d"
let kGraphEndpoint = "https://graph.microsoft.com/"
let kAuthority1 = "https://login.microsoftonline.com/7fb6a ... 427"
let kAuthority2 = "https://myB2CDemonstration.b2clogin.com/myB2CDemonstration.onmicrosoft.com/B2C_1A_SIGNUP_SIGNIN"
let kAuthority3 = "https://myB2CDemonstration.onmicrosoft.com/7fb6a ... 427"
let kRedirectUri = "msauth.br.com.edenred.ticket://auth"

let kAuthority = kAuthority1 // or 2 or 3

guard let authorityURL = URL(string: kAuthority) else {
      self.updateLogging(text: "Unable to create authority URL")
      return
  }
  
  let authority = try MSALAADAuthority(url: authorityURL)
  
  let msalConfiguration = MSALPublicClientApplicationConfig(clientId: kClientID,
                                                            redirectUri: kRedirectUri,
                                                            authority: authority)
  msalConfiguration.knownAuthorities = [authority]
  self.applicationContext = try MSALPublicClientApplication(configuration: msalConfiguration)
  self.initWebViewParams()
```

if I use `kAuthority1` or `kAuthority2` I get the error 
 > Could not acquire token: Error Domain=MSALErrorDomain Code=-50000
 UserInfo={MSALErrorDescriotionKey=AADSTS50049: Unknown or invalid instance.
 MSALOAutherrorKey=invalid_instance, MSALInternalErrorCOdeKey=-42010}
 (and a bunch of trace ids e correlation ids and etc)

if I use `kAuthority3` I get the error 
> The operation couldn’t be completed. (MSIDErrorDomain error -51112.)
TID=3929455 MSAL 1.2.5 iOS Sim 16.2 [2023-01-05 20:48:01] Creating Error with description: Trying to initialize AAD authority with B2C authority url.

**Comment by jasoncoolmax** [comment]
If it is B2C, can you try to use `MSALB2CAuthority` instead of `MSALAADAuthority`?
Let me know if that works.

**Comment by Leonardo-Ferreira** [comment]
@jasoncoolmax tks for the input. The error changed to "Authority validation is not supported for this type of authority"

**Comment by Leonardo-Ferreira** [comment]
I got some progress. I added the authority to ` msalConfiguration.knownAuthorities = [authority]` again

**Comment by Leonardo-Ferreira** [comment]
after removing the scopes, it worked like a charm!
