### ISSUE TITLE
How can I share authentication session between native app and web browser (web app) ? 

### ISSUE THREAD

**Issue by iraklivasha** [AzureAD/microsoft-authentication-library-for-objc#1640]
I authenticate using the authenticator app and the web api calls also succeed. 
I have some parts of the application, which need to be opened in an internal browser, but when I'm trying to render the content in browser, it asks me to re-authenticate at least once. Next time it won't... 

Is it possible to avoid this ? 

Version: - MSAL (1.2.4)

**Comment by antrix1989** [comment]
Hi @iraklivasha , you can provide the access token in the "Authorization" header of the Webview.

**Comment by iraklivasha** [comment]
> 

It doesn't work ...

**Comment by antrix1989** [comment]
@iraklivasha, unfortunately, we don't have API in MSAL SDK to construct web cookies.
