### ISSUE TITLE
MSAL+MS Authenticator is unable to return to the initiating app with the "<app name> is no longer available" error

### ISSUE THREAD

**Issue by alexeystrakh** [AzureAD/microsoft-authentication-library-for-objc#1648]
I have an iOS app which uses MSAL + MS Authenticator to authenticate users. The app registers everything per [this Microsoft guide](https://learn.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-ios) and I'm able to use it for authentication on one device (iOS 16.0). The same app returns an error on another device (iOS 15.7) after selecting an account in the MS Authenticator. Steps:

1. Open the app with integrated MSAL
2. Call AcquireTokenInteractively on MSAL library - MS Authenticator is activated succesfully
3. Select account/enter credentials
4. Result: An error displayed "<app name> is no longer available"

<img width="299" alt="image" src="https://user-images.githubusercontent.com/3697084/214927404-f0aecb2b-98fe-403a-91d1-722eb9ef360f.png">

I assume that the app is properly configured with the callback schema because it does work on one device. Also, if the callback schema wouldn't be configured, MSAL doesn't activate the MS Authenticator at all, but in my case I was able to activate MS Authenticator no problem on both devices. 

What can be wrong with the MSAL setup for that particular device/iOS version?

> MSAL iOS v1.2.3
> MS Authenticator v6.7.2
> iOS 15.7

**Comment by mipetriu** [comment]
Hi @alexeystrakh, there shouldn't be anything particularly wrong about the OS/device version you mentioned. Could you submit logs from the Authenticator app and provide us the Incidient ID so we can take a look at what's happening in the Authenticator app?

**Comment by alexeystrakh** [comment]
Is there a good way to grab detailed logs from MS Authenticator for you? I was able to fetch console logs and can't find anything related to the error there from authenticator. Please advise on the logs collection and I will proceed with this step.

**Comment by mipetriu** [comment]
@alexeystrakh, sure - go to the settings in the top left -> Send Feedback -> Having Trouble? -> Complete the small form and then send. It will show you an Incident ID, please share that with me here. Thanks!

**Comment by alexeystrakh** [comment]
Were able to find the culprit of this behavior on the only device affected. On that particular device two instance of the same app were installed that have different bundle id (basically same app just different bundle id). After removing both and installing from scratch the new app, MSAL + MS Auth connection worked just fine. Closing as no longer an issue.
