### ISSUE TITLE
Support multi-target/schemes

### ISSUE THREAD

**Issue by chibombo** [AzureAD/microsoft-authentication-library-for-objc#1651]
I'm trying to add the library in a multi-target project, but when I add the library to the production target it works, when I try to add the library to the other targets while the production target has the library assigned, The library doesn't appear in the library list. 

If I remove the library from the production target and then try to add it to another target of the project I can. 

- v1.2.8
- Xcode 14.2
- Swift Package Manager
- No cocoapods in the project.

![Screenshot 2023-01-30 at 2 10 35 PM](https://user-images.githubusercontent.com/30416292/215584763-70d1f072-58ae-440e-abfe-c986d1a3aca4.png)

**Comment by ameyapat** [comment]
Hi @chibombo, I'm not sure how this is related to MSAL, you may open a feedback ticket with Apple or check Swift package manager forums to resolve this?

**Comment by chibombo** [comment]
I tried with some forums, and the workaround was to download and use the `xcframework` directly, but the other packages I implemented in the project work, even if I add a new one. The issue is only with the MSAL package, It may be an MSAL issue.

**Comment by ameyapat** [comment]
@chibombo In your screenshot above, there is a drop down "Add other..." at the bottom right. After clicking on that, when you click "Add package dependency...", does it allow you to add MSAL package? It adds it to the project

**Comment by chibombo** [comment]
No, it doesn't let me add it with that option 😔

**Comment by ameyapat** [comment]
I don't think this is an MSAL issue, closing it for now
