### ISSUE TITLE
How to pass info to backed with MSAL SDK

### ISSUE THREAD

**Issue by mruvim** [AzureAD/microsoft-authentication-library-for-objc#1655]
I need to pass language to backend when calling `MSALPublicClientApplication.acquireToken(with:, completionBlock:)` for backend to render login page in a correct language. I've tried adding query params to authority URL `MSALB2CAuthority(url: )`, seems like query params are ignored. Is there a way to pass data through SDK to backend?

Thank you

**Comment by antonioalwan** [comment]
Hi @joelklabo, were you able to build the sample app listed in the main [Readme](https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/dev/CHANGELOG.md) file: https://github.com/Azure-Samples/active-directory-ios-swift-native-v2?

**Comment by antonioalwan** [comment]
hi @mruvim, do you mind adding "mkt" to extraQueryParameters dictionary with your preferred language when calling `MSALPubicClinetApplication.acquireTokenWithParameters(with: completionBlock:)` as follows:

```swift
parameters.extraQueryParameters = ["mkt":"fr-FR"]
```
