### ISSUE TITLE
Not Able to Run the SampleApp

### ISSUE THREAD

**Issue by joelklabo** [AzureAD/microsoft-authentication-library-for-objc#1658]
Unable to resolve build file: XCBCore.BuildFile (The workspace has a reference to a missing target with GUID '47ccab60363fed7765ff3b2896d7fa5ec47bed0a41fed76244bab67606b71abb')

**Comment by antonioalwan** [comment]
Hi @joelklabo, were you able to build the sample app listed in the main [Readme](https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/dev/CHANGELOG.md) file: https://github.com/Azure-Samples/active-directory-ios-swift-native-v2?

**Comment by antonioalwan** [comment]
Hi @joelklabo, were you able to build the sample app listed in the main [Readme](https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/dev/CHANGELOG.md) file: https://github.com/Azure-Samples/active-directory-ios-swift-native-v2?

**Comment by joelklabo** [comment]
> Hi @joelklabo, were you able to build the sample app listed in the main [Readme](https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/dev/CHANGELOG.md) file: https://github.com/Azure-Samples/active-directory-ios-swift-native-v2?

Yeah, I wasn't aware there was another one. Thanks! Looks like it's running
