### ISSUE TITLE
Exposing refreshToken through MSALResult

### ISSUE THREAD

**Issue by srikanth-kr** [AzureAD/microsoft-authentication-library-for-objc#1671]
Right now `MSALResult` returned through the method `acquireTokenSilent` and `acquireToken` has only `accessToken` property.

**My Suggestion**
In addition to accessToken, shall we add a new property as `refreshToken` and return refreshToken from it?

**Query**
Is it a design decision to hide the refreshToken from msal or do we have any ways to access it?

**Comment by antrix1989** [comment]
It is a design decision to not make the RT available in the public API. The refresh token should only be utilized by the SDK, and the app should solely rely on the access token. Additionally, there may be instances where the SDK does not have access to the refresh token, such as in broker SSO extension flows

**Comment by ahmedelmoughazy** [comment]
I have a question about this, can I at least get the expiration date of a refresh token ?

**Comment by appiotic** [comment]
Also interested in knowing how to get the expiration date of the refreshtoken

**Comment by shibayan** [comment]
App Service has a feature called client-directed sign-in, and since this feature also manages refresh_tokens, I would like MSAL to be able to obtain refresh_tokens as well.

https://learn.microsoft.com/en-us/azure/app-service/configure-authentication-customize-sign-in-out#client-directed-sign-in

**Comment by ahmedelmoughazy** [comment]
I actually did something to check the refresh token expiration date, I can't remember the exact steps, as it was a while ago, and I strongly don't recommend this for production, I enabled the logging for MSAL and was able to get the keychain service id and account of where the token is saved, and accessed them with a custom piece of code, and was able to get the expiration date, but of course I needed that for only development, so unfortunately I got ride of the code I used. I hope this helps also.
