### ISSUE TITLE
Migrate from deprecated Keys API

### ISSUE THREAD

**Issue by susie-lee** [AzureAD/microsoft-authentication-library-for-objc#1679]
MSAL utilizes a couple legacy key operations that Apple deprecated on iOS 15, for example:

- [SecKeyDecrypt](https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/blob/8242b1b0860747a588f55f34c52a3da176f85df5/IdentityCore/src/util/MSIDJWTHelper.m#L60)
- [SecKeyRawSign](https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/blob/8242b1b0860747a588f55f34c52a3da176f85df5/IdentityCore/src/util/NSData%2BJWT.m#L46)

It would be great to migrate to the new [Keys](https://developer.apple.com/documentation/security/certificate_key_and_trust_services/keys?language=objc) API.

**Comment by juan-arias** [comment]
Thanks a lot for reporting this @susie-lee, we have created a task to track this work internally.

**Comment by susie-lee** [comment]
@juan-arias i would appreciate if you can let me know which version you plan to target releasing these changes in when you know so that my team is aware of a general timeline. thank you!

**Comment by juan-arias** [comment]
@susie-lee, this is planned to be included in the next release. You can track this here: https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/1252
