### ISSUE TITLE
MSAL Library not clearing the user access token from iOS keychain from the environment "login.microsoftonline.com"

### ISSUE THREAD

**Issue by SrikanthVel** [AzureAD/microsoft-authentication-library-for-objc#1683]
Hi Team,

We are using MSAL library v1.2.5 for user authentication in our mobile app. The library is saving user access token in the keychain under environment "**login.microsoftonline.com**". 

The following details are getting saved in keychain
"client_id", "secret", "principal_home_account_id", "principal_username". These are most sensitive information and it includes user details. 

**Actual Behaviour**
This data is exposed in keychain in the following scenarios
1. When user performs logout .
2. When user deletes the app without logging out and after launch of the app after re-install before another user login.

**Expected Behaviour**
The MSAL library has to clear all the sensitive data in the 2 scenarios mentioned above.

Here is what we are doing when user performs logout

`{
        
        let msalParameters = MSALParameters()
        
        msalParameters.completionBlockQueue = DispatchQueue.main

        self.msalApp.getCurrentAccount(with: msalParameters, completionBlock: {(currentAccount, previousAccount, error) in
            if let err = error {
                /// Handle error
                return
            }
            // currentAccount is the currently signed in account
            // previousAccount is the previously signed in account if any
            guard let account = currentAccount else {
                /// Unable to fetch account
                return
            }
            let webViewParameters = MSALWebviewParameters(authPresentationViewController: parent)
            let signoutParameters = MSALSignoutParameters(webviewParameters: webViewParameters)
            signoutParameters.signoutFromBrowser = false
            signoutParameters.completionBlockQueue = DispatchQueue.main
            signoutParameters.wipeAccount = true

            self.msalApp.signout(with: account, signoutParameters: signoutParameters, completionBlock: { (success, error) in
                if let err = error{
                    // Handle error
                }
                if success {
                    do {
                        clearJWTokenFromSecureStore() /// Explicitly clearing the token from our keychain/user defaults
                        try self.msalApp.remove(account)
                        DispatchQueue.main.async {
                            completionHandler(.success(success))
                        }
                    } catch  {
                        DispatchQueue.main.async {
                            completionHandler(.failure(error))
                        }
                        FMUtility.DebugLog("Unable to remove account with \(String(describing: account.username))")
                    }
                }
            })
        })
    }`

As this is a high priority security issue, we would request you to provide solution for this asap.

**Comment by ameyapat** [comment]
Hi @SrikanthVel , based on your requirements in your signout parameters I think you need to set the wipeCacheForAllAccounts to YES. Can you give that a try? 

```
/*
  Removes account from the keychain with either com.microsoft.adalcache shared group by default or the one provided when configuring MSALPublicClientApplication.

  This is a destructive action and will remove the SSO state from all apps sharing the same cache!
  It's intended to be used only as a way to achieve GDPR compliance and make sure all user artifacts are cleaned on user sign out.
  It's not intended to be used as a way to reset or fix token cache.
  Please make sure end user is shown UI and/or warning before this flag gets set to YES.
  NO by default.
*/
@property (nonatomic) BOOL wipeAccount;

/*
  When flag is set, following should happen:
    - Wipe all known universal cache locations regardless of the clientId, account etc. Should include all tokens and metadata for any cloud.
    - Wipe all known legacy ADAL cache locations regardless of the clientId, account etc.
    - MSALWipeCacheForAllAccountsConfig contains a list of additional locations for partner caches to be wiped (e.g. Teams, VisualStudio etc). Wipe operation should wipe out all those additional locations. This file includes "display identifier" of the location (e.g. Teams cache), and precise identifiers like kSecAttrAccount, kSecAttrService etc.
    - If SSO extension is present, call SSO extension wipe operation. Wipe operation should only be allowed to the privileged applications like Intune CP on macOS or Authenticator on iOS.
    - Failing any of the steps should return error back to the app including exact locations and apps that failed to be cleared.
  NO by default.
  This is a dangerous operation.
*/
@property (nonatomic) BOOL wipeCacheForAllAccounts;
```

**Comment by jasoncoolmax** [comment]
close it due to no response. Please feel free to reopen it when more info is provided.

**Comment by SrikanthVel** [comment]
Hi @jasoncoolmax, @ameyapat ,
It has taken some time to verify this implemented solution, the issue is still persist. After implementing the suggested fix also, the access token was not removed from the key chain. Would request you to re-open this defect and provide alternate solution for this.

**Comment by SrikanthVel** [comment]
Hi @ameyapat, @jasoncoolmax 
Posted new question as team did not get the exact fix for this question https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1729 by including the proposed solution.

**Comment by munkii** [comment]
@jasoncoolmax I've looked at this and the second issue [#1729](https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1729)

Neither of them have a solution for the second scenario in the OP

> Actual Behaviour
> This data is exposed in keychain in the following scenarios
> 
> When user performs logout .
> **When user deletes the app without logging out and after launch of the app after re-install before another user login.**

"When the user deletes the app without logging out". Is there a way of storing the cache in a place that is secure ( on iOS) and gets deleted as part of an uninstall?
