### ISSUE TITLE
MSAL does not save login info (from WebView) in cookies 

### ISSUE THREAD

**Issue by OleksandrOleksyn** [AzureAD/microsoft-authentication-library-for-objc#1686]
Preconditions:
Login to the application is implemented the following way:
- using custom sign in policy
- using webviewType parameter of MSALWebviewParameters as MSALWebviewTypeWKWebView 

Steps to reproduce:
- log in as described above
- user wants to change password using MSAL library with custom policy
- application does change password the same way as login
Actual result:
- WebView has no data about the fact that user is already logged in (no data in cookies)
- As a result user needs to enter credentials firstly, then proceed with changing of password
Expected result:
- user is able to change password right away, without login in (using custom policy)
- WebView knows that user is already signed in (has data in cookies)

Side notes:
In case of using  webviewType parameter of MSALWebviewParameters as MSALWebviewTypeDefault the issue is NOT present

**Comment by hieunguyenmsft** [comment]
Hi @OleksandrOleksyn, SSO (sharing Cookie) in WKWebView is not supported so user re-enter credential is expected. Please check out this document for more information:
https://learn.microsoft.com/en-us/azure/active-directory/develop/customize-webviews#cookie-sharing-and-sso-implications
