### ISSUE TITLE
Sign in with Apple without webview

### ISSUE THREAD

**Issue by RadekNov** [AzureAD/microsoft-authentication-library-for-objc#1702]
Hi, I would love to know if there's a possibility to implement "Sign in with Apple" button without opening a web page using Swift on iOS.

I followed sample [here](https://github.com/Azure-Samples/ms-identity-mobile-apple-swift-objc), configured everything on Apple side, in Azure portal and currently, when I try to authorize, the app opens webview with apple login which triggers popup shown below, user gets authorized, gets a record in Azure AD B2C users and is redirected back to the app.

Are we able to, somehow, implement the authorization without opening the web page? It would be great that user gets the system prompt right after tapping "Authorize" (as it was designed by Apple) without opening any page which might look kinda shady.

Thanks for response!

![](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/appleid/ios14-iphone-11-pro-sign-in-with-apple.jpg)

**Comment by kaisong1990** [comment]
@RadekNov Sorry for the delaying. I have checked with MSAL team and there is no plan for supporting such feature yet. I will keep you posted if the feature will be available in the future.

**Comment by RadekNov** [comment]
Got it. Thanks for response
