### ISSUE TITLE
Min iOS versions supported by latest release

### ISSUE THREAD

**Issue by namrata690** [AzureAD/microsoft-authentication-library-for-objc#1703]
Hi team,
Just wanted to know where I can get the info about the minimum iOS version supported by latest releases (particularly looking for 1.2.9)

Thanks!

**Comment by Veena11** [comment]
Hi
Minimum os version supported for iOS and macOS is  iOS14 and macOS 10.13 respectively. The repo was updated to support these minimum versions with 1.2.6 release.

Thanks
