### ISSUE TITLE
Version mismatch Package - Tag

### ISSUE THREAD

**Issue by umutonat** [AzureAD/microsoft-authentication-library-for-objc#1707]
Tag version on Github is 1.2.12 but in package version is 1.2.11

`
Could not resolve package dependencies:
  failed downloading 'https://github.com/AzureAD/microsoft-authentication-library-for-objc/releases/download/1.2.11/MSAL.zip' which is required by binary target 'MSAL': badResponseStatusCode(404)
  fatalError
`

**Comment by antonioalwan** [comment]
@umutonat Can you please try again now. The release tag is fixed

**Comment by umutonat** [comment]
@antonioalwan It now points to 1.2.10, still mismatches

**Comment by antonioalwan** [comment]
@umutonat this could be some caching issue. Do you mind clearing swift package manager cache and retry?

**Comment by umutonat** [comment]
@antonioalwan It is nothing to do with cache, https://github.com/AzureAD/microsoft-authentication-library-for-objc/releases/download/1.2.11/microsoft-authentication-library-for-objc-1.2.11.zip 
this zip contains at Line 16 of the Package.swift following code

```
.binaryTarget(name: "MSAL", url: "https://github.com/AzureAD/microsoft-authentication-library-for-objc/releases/download/1.2.10/MSAL.zip", checksum: "3a9dbe5f1cf562076d1bee99297f0cbf6a4b8013769614d5ddeace86ef808ca4")
```
