### ISSUE TITLE
Package.swift points to the wrong download

### ISSUE THREAD

**Issue by dylanashe** [AzureAD/microsoft-authentication-library-for-objc#1708]
The Package.swift for 1.2.11 points to https://github.com/AzureAD/microsoft-authentication-library-for-objc/releases/download/1.2.10/MSAL.zip

**Comment by antonioalwan** [comment]
@dylanashe Can you please recheck if MSAL at release tag 1.2.11 is pointing to https://github.com/AzureAD/microsoft-authentication-library-for-objc/releases/download/1.2.11/MSAL.zip

**Comment by dylanashe** [comment]
I just checked and the 1.2.11 tag of Package.swift contains the line:

      .binaryTarget(name: "MSAL", url: "https://github.com/AzureAD/microsoft-authentication-library-for-objc/releases/download/1.2.10/MSAL.zip", checksum: "3a9dbe5f1cf562076d1bee99297f0cbf6a4b8013769614d5ddeace86ef808ca4")

(1.2.10 vs 1.2.11)

**Comment by dylanashe** [comment]
The head of Package.swift also contains 1.2.10 and not 1.2.11

**Comment by antonioalwan** [comment]
@dylanashe this could be some caching issue. Do you mind clearing swift package manager cache and retry?

**Comment by dylanashe** [comment]
Not a caching issue.

In your browser navigate to:

https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/dev/Package.swift

If you notice, the download path is:

https://github.com/AzureAD/microsoft-authentication-library-for-objc/releases/download/1.2.10/MSAL.zip

and not:

https://github.com/AzureAD/microsoft-authentication-library-for-objc/releases/download/1.2.11/MSAL.zip

NOTE: If you go to the 1.2.11 release page and tap any of the downloads, and examine Package.swift you'll get the same result.

**Comment by antonioalwan** [comment]
@dylanashe btw that was referencing dev branch vs master.
However, this is fixed and updated to match master, please take another look and update me if you see the issue again

**Comment by dylanashe** [comment]
That resolved the issues.   Thank you!
