### ISSUE TITLE
MSALPublicClientApplication.acquireTokenSilent() completionBlock not called

### ISSUE THREAD

**Issue by noxo** [AzureAD/microsoft-authentication-library-for-objc#1710]
I'm reporting #1531  again - this time with MSAL logs included.

Code / symptoms are still same.` MSALPublicClientApplication.acquireTokenSilent()` not returning the callback randomly.

Details are in MSAL logs, this seems to occur at time users accessToken expires, and MSAL tries to renew the token, but implementation seems to hang on MSAL in `ASAuthorizationController.performRequests().`

[MSAL.log](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/11330482/MSAL.log)

**Comment by antonioalwan** [comment]
@noxo Looking at the snippet in the example #1503 it looks like you're using a DispatchSemaphore. Would you consider not using a Semaphore and report if you see the same hang. Semaphores on main thread would [block](https://stackoverflow.com/questions/57693314/can-i-use-a-dispatchsemaphore-to-control-a-thread-on-main-queue) the execution.

**Comment by noxo** [comment]
Thanks @antonioalwan. I guess it was implemented in assumption, that `acquireTokenSilent` executes async in separate thread, and finishes in few milliseconds.

We'll try moving the `acquireTokenSilent` in separate thread or dropping semaphores.

**Comment by swasti29** [comment]
@noxo 
Closing this issue, feel free to contact us again in case if it still a problem.
