### ISSUE TITLE
MSAL Library not clearing the user access token from iOS keychain from the environment "login.microsoftonline.com

### ISSUE THREAD

**Issue by SrikanthVel** [AzureAD/microsoft-authentication-library-for-objc#1729]
Hi Team,

We are using MSAL library v1.2.11 for user authentication in our mobile app. The library is saving user access token in the keychain under environment "login.microsoftonline.com".

The following details are getting saved in keychain
"client_id", "secret", "principal_home_account_id", "principal_username". These are most sensitive information and it includes user details.

Actual Behaviour
This data is exposed in keychain in the following scenarios
1. When user performs logout .
2. When user deletes the app without logging out and after launch of the app after re-install before another user login.

Expected Behaviour
The MSAL library has to clear all the sensitive data in the 2 scenarios mentioned above.

Here is what we are doing when user performs logout

`{

    let msalParameters = MSALParameters()
    
    msalParameters.completionBlockQueue = DispatchQueue.main

    self.msalApp.getCurrentAccount(with: msalParameters, completionBlock: {(currentAccount, previousAccount, error) in
        if let err = error {
            /// Handle error
            return
        }
        // currentAccount is the currently signed in account
        // previousAccount is the previously signed in account if any
        guard let account = currentAccount else {
            /// Unable to fetch account
            return
        }
        let webViewParameters = MSALWebviewParameters(authPresentationViewController: parent)
        let signoutParameters = MSALSignoutParameters(webviewParameters: webViewParameters)
        signoutParameters.signoutFromBrowser = false
        signoutParameters.completionBlockQueue = DispatchQueue.main
        signoutParameters.wipeAccount = true
        signoutParameters.wipeCacheForAllAccounts = true

        self.msalApp.signout(with: account, signoutParameters: signoutParameters, completionBlock: { (success, error) in
            if let err = error{
                // Handle error
            }
            if success {
                do {
                    clearJWTokenFromSecureStore() /// Explicitly clearing the token from our keychain/user defaults
                    try self.msalApp.remove(account)
                    DispatchQueue.main.async {
                        completionHandler(.success(success))
                    }
                } catch  {
                    DispatchQueue.main.async {
                        completionHandler(.failure(error))
                    }
                    FMUtility.DebugLog("Unable to remove account with \(String(describing: account.username))")
                }
            }
        })
    })
}`
As this is a high priority security issue, we would request you to provide solution for this asap.

**Comment by antrix1989** [comment]
HI @SrikanthVel, could you please provide the following details:
- Are you using [Microsoft Authenticator app](https://apps.apple.com/us/app/microsoft-authenticator/id983156458)?
- Are you using [Microsoft Enterprise SSO plug-in](https://learn.microsoft.com/en-us/azure/active-directory/develop/apple-sso-plugin)?
- Under which keychain group do you see the mentioned PII items?

**Comment by SrikanthVel** [comment]
Hi @antrix1989, please find the requested details as below

We are not using both of them, we have integrated MSAL library using 
`pod MSAL`.

The PII information is getting saved under "login.microsoftonline.com" keychain group.

**Comment by SrikanthVel** [comment]
Hi @antrix1989, Please let me know if you need any further information on this. Would request you to expedite this.

**Comment by antrix1989** [comment]
Thanks @SrikanthVel, we don't own "login.microsoftonline.com" keychain group. We use `com.microsoft.adalcache`, see [here](https://github.com/AzureAD/microsoft-authentication-library-for-objc#configuring-msal). I suggest you to play with our MSAL Test App, you can get it by downloading the SDK from the our github repo. I verified you code in that app and I see no issues with the code. Try these steps:
1) Launch MSAL Test App.
2) Select https:/graph.microsoft.com/.default scope
3) Tap "acquireToken" button.
4) Finish the sign in in web view.
5) Open `Cache` tab in the app, pull down to refresh the table.
6) Cache should contains tokens.
7) Modify the [signout code](https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/89bed70e0ec91d841a370f6dc4a91ab6df8a85f8/MSAL/test/app/ios/MSALTestAppAcquireTokenViewController.m#L356) here by adding `wipeAccount` and `wipeCacheForAllAccounts` flags:

```
+    signoutParameters.wipeAccount = YES;
+    signoutParameters.wipeCacheForAllAccounts = YES;
```
8) Launch the app again.
9) Pick user account under `user` row.
10) Tap `signout` button.
11) Open `Cache` tab in the app, pull down to refresh the table.
12) The cache should be empty.

**Comment by RajendraNayak** [comment]
Hi @antrix1989 

I followed your above suggestion and downloaded your sample app however while running "SampleAppiOS-Swift" app, I am getting this compilation error (**could not find included file '../IdentityCore/IdentityCore/xcconfig/identitycore__common__ios.xcconfig' in search paths**)

Also I found that "IdentityCore" doesn't contain any files

<img width="1401" alt="Screenshot 2023-05-31 at 4 28 39 PM" src="https://github.com/AzureAD/microsoft-authentication-library-for-objc/assets/3063882/2ba4e037-7683-4f91-bf3e-9dccdeba30d4">


<img width="913" alt="Screenshot 2023-05-31 at 4 27 56 PM" src="https://github.com/AzureAD/microsoft-authentication-library-for-objc/assets/3063882/9de3a48d-5052-402a-a51f-59c9c39f1908">

Please suggest us the next step.

Thanks
Rajendra

**Comment by AlkaKRai** [comment]
How I can test using my client id?
I am facing this issue to get silent token in my native iOS app
[+oneAppLog][AzureUtility.getTokenSilently(policy:completionHandler:)] - Azure Utility acquireToken SILENTLY error : Optional(Error Domain=MSALErrorDomain Code=-50002 "(null)" UserInfo={MSALErrorDescriptionKey=User interaction is required, MSALOAuthErrorKey=invalid_grant, MSALCorrelationIDKey=9CB85855-62A1-4EFE-99FE-4EE364304B15, NSUnderlyingError=0x3007620d0 {Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=AADB2C90129: The provided grant has been revoked. Please reauthenticate and try again.
 
Correlation ID: a8589387-c7bc-429d-9322-1fe0f390de77
