### ISSUE TITLE
Getting already expired token with acquireSilent()

### ISSUE THREAD

**Issue by PigLardLord** [AzureAD/microsoft-authentication-library-for-objc#1781]
I'm having a problem with id token renewal in my iOS app. I implemented it following the [guidelines](https://learn.microsoft.com/en-us/azure/active-directory-b2c/enable-authentication-ios-app) and everything looks working properly until the token expires. when I try to get it again using `self.applicationContext.acquireTokenSilent(with: parameters)` I get an already expired token.

**Comment by kaisong1990** [comment]
Hi @PigLardLord, can you please provide MSAL logs and we will look into it

**Comment by PigLardLord** [comment]
[MSAL.log](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/11848089/MSAL.log)
Here are the logs. Of course, the last logout is performed because the token is expired.

**Comment by kaisong1990** [comment]
Hi @PigLardLord, sorry for the delaying. The log shows it called into Authenticator broker, and got the token back without issues. Also looks like you are calling **interactively** from the log by using [the following API](https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/a58ed00d6b1d767023d927652f8bcd78883fd252/MSAL/src/public/MSALPublicClientApplication.h#L283):

`-[MSALPublicClientApplication acquireTokenWithParameters:(`

Please try to use [silent API](https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/a58ed00d6b1d767023d927652f8bcd78883fd252/MSAL/src/public/MSALPublicClientApplication.h#L365) which best fits your needs.

Can you please repro by using acquireTokenSilent API and if there is still issues, please share a new MSAL log. Thanks!

**Comment by kaisong1990** [comment]
Closing as no activities for a while
