### ISSUE TITLE
ADFS Support

### ISSUE THREAD

**Issue by alberto093** [AzureAD/microsoft-authentication-library-for-objc#1785]
Is there an ETA to release ADFS Support?

**Comment by antonioalwan** [comment]
Hi @alberto093 we already support ADFS. Can you please provide more details. meanwhile please check:
- https://learn.microsoft.com/en-us/azure/active-directory/authentication/active-directory-certificate-based-authentication-ios
- https://learn.microsoft.com/en-us/azure/active-directory/authentication/active-directory-certificate-based-authentication-get-started
