### ISSUE TITLE
MSAL and MF Authenticator issue when session expires

### ISSUE THREAD

**Issue by parveen-bhatia** [AzureAD/microsoft-authentication-library-for-objc#1786]
**Bug Description:** 
When app is already authenticated using MSAL with MF Authenticator. And session is revoked. Then if user tries to acquire token interactively then MF Authenticator doesn't ask for password. MSAL returns that authentication is successful

**Steps to Replicate**
- User authenticates with MSAL using acquire token interactively
- Azure AD session expires or it is revoked by admin. See steps below under section `Steps to Revoke user session`.
- App tries to to interactively acquire token using MSAL. User is taken to MF Authenticator. In MF authenticator, after selecting pre existing account user is returned back to the app without being asked for password. And no error is received from MSAL and it returns Azure AD auth is successful.

**Steps to Revoke user session:**

- Go to: https://endpoint.microsoft.com/#view/Microsoft_AAD_UsersAndTenants/UserManagementMenuBlade/~/AllUsers
- Select the user
- Click Revoke sessions

**Versions:**
MSAL Version: 1.2.12
iOS Version: iOS 15 and above

**Comment by PigLardLord** [comment]
I'm facing the same issue. And I'm having the same problem also using the MSALPublicClientApplication.acquireTokenSilent(with:). Which leads to receiving an already expired ID token.

It might have the same source than: https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1781

**Comment by antonioalwan** [comment]
Hi @parveen-bhatia Access tokens or ID tokens cannot be revoked. You can, however, [revoke refresh tokens](https://learn.microsoft.com/en-us/azure/active-directory/enterprise-users/users-revoke-access).
When the access token expires, the refresh token won't be honored and the user will be logged out.

**Comment by parveen-bhatia** [comment]
Hi @antonioalwan, when i am revoking session from Azure AD. Then problem is auth using `MSALPublicClientApplication.acquireTokenInteractively` is still successful and MF Authenticator doesn't prompt for password. And MSAL returns expired token similar issue reported by @PigLardLord with silent auth.
With these tokens i cannot access services like Intune MAM and getting token expired error.

**Comment by antonioalwan** [comment]
@parveen-bhatia unless you use acquireTokenInteractively with prompt=login, the behavior is similar to acquireTokenSilent by reading access token from cache.
