### ISSUE TITLE
How To Open System Safari Browser to login and back to iOS app

### ISSUE THREAD

**Issue by chetan-duke** [AzureAD/microsoft-authentication-library-for-objc#1788]
Hello everyone,

I've successfully implemented SSO using in-app-browser. But the issue is in-app-browser doesn't get shared data from the Safari browser so I could not access already logged in session from the browser and in-app-browser asks me to enter password.

As I've seen many apps like Zoom in iOS opens the System Safari browser and use the existing session and backs to the app.

I've tried to find in the demo and forums but I could not get any luck. 
I would request you to share sample or any demo link over here.

Thank you.

**Comment by chetan-duke** [comment]
@mipetriu please help and guide asap if you could. :)

**Comment by swasti29** [comment]
@chetan-duke Are you referring to SSO Browser Extension ?
If not then Kindly use MSAL Webview Type: ASWebAuthenticationSession https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession

For more information regarding the different webviews please refer: https://learn.microsoft.com/en-us/azure/active-directory/develop/customize-webviews#cookie-sharing-and-sso-implications

**Comment by chetan-duke** [comment]
@swasti29 thank you.

![Simulator Screenshot - iPhone 14 Pro Max - 2023-07-07 at 10 20 00](https://github.com/AzureAD/microsoft-authentication-library-for-objc/assets/21120612/92db1561-b90f-43de-a9a8-a482f787ae34)

![Simulator Screenshot - iPhone 14 Pro Max - 2023-07-07 at 10 20 13](https://github.com/AzureAD/microsoft-authentication-library-for-objc/assets/21120612/21d69d40-19a9-4535-9d81-d58c608c58b5)

I'VE ALREADY SUCCESSFULLY IMPLEMENTED SSO LOGIN WITH ASWebAuthenticationSession.
But for the first time it asks user to enter password even if user has login session in Safari browser.
Our requirement is app must not asks the password if user has session in system browser. So in this case we have to follow Zoom app.


https://github.com/AzureAD/microsoft-authentication-library-for-objc/assets/21120612/e924fe6b-d152-474f-97cb-64bd2439710b

Please review above zoom video. I need to change as zoom and need help on it.

**Comment by jasoncoolmax** [comment]
@chetan-duke Could you please share the MSAL logs? such that I can take a look. The system browser in your screenshot and the safari browser in your video should share the same cookies. So if there is an active session available, it should be able to work without asking for passowds. If you can give me logs or Charles trace or at least the correlation id, I can help dig deeper.

**Comment by chetan-duke** [comment]
@jasoncoolmax here is the log: 

TID=3533719 MSAL 1.2.5 iOS 16.5.1 [2023-08-03 15:26:54] Keychain find status: 0
TID=3533719 MSAL 1.2.5 iOS 16.5.1 [2023-08-03 15:26:54] Querying MSAL accounts with parameters (identifier=Masked(null), tenantProfileId=Masked(null), username=Masked(null), return only signed in accounts 1)
TID=3533719 MSAL 1.2.5 iOS 16.5.1 [2023-08-03 15:26:54] Keychain find status: 0
TID=3533719 MSAL 1.2.5 iOS 16.5.1 [2023-08-03 15:26:54] (Default accessor) Get accounts.
TID=3533719 MSAL 1.2.5 iOS 16.5.1 [2023-08-03 15:26:54] Keychain find status: 0
TID=3533719 MSAL 1.2.5 iOS 16.5.1 [2023-08-03 15:26:54] (MSIDAccountCredentialCache) retrieving cached credentials using credential query
TID=3533719 MSAL 1.2.5 iOS 16.5.1 [2023-08-03 15:26:54] Keychain find status: -25300
TID=3533719 MSAL 1.2.5 iOS 16.5.1 [2023-08-03 15:26:54] (MSIDAccountCredentialCache) retrieved 0 cached credentials
TID=3533719 MSAL 1.2.5 iOS 16.5.1 [2023-08-03 15:26:54] (MSIDAccountCredentialCache) credential query requires exact match with the cached credential items. Performing additional filtering checks.
TID=3533719 MSAL 1.2.5 iOS 16.5.1 [2023-08-03 15:26:54] (MSIDAccountCredentialCache) returning 0 filtered credentials
TID=3533719 MSAL 1.2.5 iOS 16.5.1 [2023-08-03 15:26:54] (Default accessor) Looking for token with aliases (null), tenant (null), clientId b404ed27-7996-44da-b7e4-7804d0deefe7, scopes (null)
TID=3533719 MSAL 1.2.5 iOS 16.5.1 [2023-08-03 15:26:54] (MSIDAccountCredentialCache) retrieving cached credentials using credential query
TID=3533719 MSAL 1.2.5 iOS 16.5.1 [2023-08-03 15:26:54] Keychain find status: -25300
TID=3533719 MSAL 1.2.5 iOS 16.5.1 [2023-08-03 15:26:54] (MSIDAccountCredentialCache) retrieved 0 cached credentials
TID=3533719 MSAL 1.2.5 iOS 16.5.1 [2023-08-03 15:26:54] (MSIDAccountCredentialCache) credential query requires exact match with the cached credential items. Performing additional filtering checks.
TID=3533719 MSAL 1.2.5 iOS 16.5.1 [2023-08-03 15:26:54] (MSIDAccountCredentialCache) returning 0 filtered credentials
TID=3533719 MSAL 1.2.5 iOS 16.5.1 [2023-08-03 15:26:54] Keychain find status: 0
TID=3533719 MSAL 1.2.5 iOS 16.5.1 [2023-08-03 15:26:54] (Default accessor) No accounts found in default accessor.
TID=3533719 MSAL 1.2.5 iOS 16.5.1 [2023-08-03 15:26:54] Keychain find status: -25300
TID=3533719 MSAL 1.2.5 iOS 16.5.1 [2023-08-03 15:26:54] (Default accessor) No accounts found in other accessors.
TID=3533719 MSAL 1.2.5 iOS 16.5.1 [2023-08-03 15:26:54] Found MSAL accounts with count 0
TID=3533719 MSAL 1.2.5 iOS 16.5.1 [2023-08-03 15:26:54] Found MSAL account with current account Masked(null), previous account Masked(null)
Account signed out. Updating UX
TID=3533719 MSAL 1.2.5 iOS 16.5.1 [2023-08-03 15:26:54] Requiring default broker type due to app being built with iOS 13 SDK
TID=3533719 MSAL 1.2.5 iOS 16.5.1 [2023-08-03 15:26:54 - 2546C572-17E8-4959-B34E-4953360557A7] [MSAL] -[MSALPublicClientApplication acquireTokenWithParameters:(
    "user.read"
)
                                     extraScopesToConsent:(null)
                                                  account:Masked(null)
                                                loginHint:auth.placeholder-be68877f__incentx.com
                                               promptType:MSALPromptTypePromptIfNecessary
                                     extraQueryParameters:(null)
                                                authority:(null)
                                              webviewType:MSALWebviewTypeAuthenticationSession
                                            customWebview:No
                                            correlationId:(null)
                                             capabilities:(null)
                                            claimsRequest:(null)]
TID=3533719 MSAL 1.2.5 iOS 16.5.1 [2023-08-03 15:26:54 - 2546C572-17E8-4959-B34E-4953360557A7] [MSAL] Beginning interactive flow.
TID=3533719 MSAL 1.2.5 iOS 16.5.1 [2023-08-03 15:26:54] Start background app task with type 0 & taskId : 22
TID=3533719 MSAL 1.2.5 iOS 16.5.1 [2023-08-03 15:26:54 - 2546C572-17E8-4959-B34E-4953360557A7] [MSAL] Resolving authority: Masked(not-null), upn: auth.placeholder-be68877f__incentx.com
TID=3533719 MSAL 1.2.5 iOS 16.5.1 [2023-08-03 15:26:54 - 2546C572-17E8-4959-B34E-4953360557A7] [MSAL] Resolved authority, validated: YES, error: 0
TID=3533719 MSAL 1.2.5 iOS 16.5.1 [2023-08-03 15:26:54 - 2546C572-17E8-4959-B34E-4953360557A7] [MSAL] Start webview authorization session with webview controller class MSIDSystemWebviewController:

**Comment by chetan-duke** [comment]
@jasoncoolmax  here is the correlation id:

MSALCorrelationIDKey=2546C572-17E8-4959-B34E-4953360557A7

**Comment by jasoncoolmax** [comment]
Hi @chetan-duke, sorry I was on vacation. Not sure if the issue has been resolved.

By looking up the server logs by the provided correlation id, I see there is no active session in the safari browser. Could you do a full repro and share the correlation id and videos again? 
It will be great if you can capture the network trace as well just in case I might need it as well :)

**Comment by chetan-duke** [comment]
Hey @jasoncoolmax thank you for the update on your availability.
I'm referring video  ZoomSSO3.mov posted in this comment thread and my simple question is how Zoom has done the open system Safari.app (external safari browser and **not in-app-browser**) 

[Asking it as could not find that way in the library and I need it to implement that way only].

So by setting which parameter object in the MSAL configuration to achieve requirement.
Looking forward to you @jasoncoolmax !!!

**Comment by chetan-duke** [comment]
@jasoncoolmax  please ack on this once you are available.

**Comment by jasoncoolmax** [comment]
Seems Zoom is calling openURL to open safari browser directly. 
ASWebAuthenticationSession is provided by Apple to give a more integrated experience to users. It shares the same cookies with Safari browser. It is what is being used in MSAL.You just need to set MSAL Webview Type to be ASWebAuthenticationSession.

**Comment by chetan-duke** [comment]
Thanks @jasoncoolmax to clarify the exact scenario.

Using webViewParameters.webviewType = .authenticationSession

Many times it happened that MSAL doesn't use (or safari don't share the active session of user from System Safari app) session and must has to enter re-login in the app's browser. That's why I need to follow Zoom SSO way.

I'm done with opening browser and able to login there as well. But @jasoncoolmax  can you help me where to configure call back to app opening and share the access token with app.

Thank you.
