### ISSUE TITLE
Multiple Accounts Found in Cache After Deregistering and Unenrolling Account

### ISSUE THREAD

**Issue by jukemoon** [AzureAD/microsoft-authentication-library-for-objc#1790]
I have an app protected via Intune; some users must access it using different accounts. With that being said, I'm seeking input for the correct way that a user can log out of one account and into another without factory resetting their device.
 
We're using the method below to log out a user so that a new one can log in.
 
```objectivec
/**
*  This method will remove the provided account from the list of
*  registered accounts.  Once removed, if the account has enrolled
*  the application, the account will be un-enrolled.
*
*  @note In the case where an un-enroll is initiated, this method will block
*  until the MAM token is acquired, then return.  This method must be called before 
 *  the user is removed from the application (so that required AAD tokens are not purged
*  before this method is called).
*
*  @note Do not use this in an extension.  If you do so, we will return
*  IntuneMAMEnrollmentStatusUnsupportedAPI in the IntuneMAMEnrollmentDelegate.
*
*  @param identity The UPN of the account to be removed.
*  @param doWipe   If YES, a selective wipe if the account is un-enrolled
*/
- (void)deRegisterAndUnenrollAccount:(NSString *_Nonnull)identity withWipe:(BOOL)doWipe;
```
 
Both accounts have the same Intune policy and are in the same tenant. However, we still see the logged-out account's
information still on the device. The method we're calling that's returning a multi-account caching-related error is below.
 
```objectivec
/**
Gets the current account and return previous account if present. This can be useful to detect if the current account changes.
This method must be called whenever the application is resumed or prior to running a scheduled background operation.
 If there're multiple accounts present, MSAL will return an ambiguous account error, and application should do account disambiguation by calling other MSAL Account enumeration APIs.
*/
- (void)getCurrentAccountWithParameters:(nullable MSALParameters *)parameters
                        completionBlock:(MSALCurrentAccountCompletionBlock)completionBlock;
```
 
The exact error returned from the completion block is below.
 
```
Error Domain = MSALErrorDomain 
Code = -50000 "(null)" 
UserInfo = {
  MSALErrorDescriptionKey = Multiple accounts found in cache., 
  MSALInternalErrorCodeKey = -42102
}
```
 
What is the best way to log the user out of the app and log in with a different account?

**Comment by jasoncoolmax** [comment]
@jukemoon I cannot find the `getCurrentAccountWithParameters` API in the MSAL repo. I believe that is not an MSAL API.

To signout an account from MSAL, you can use the APIs provided by MSAL. Currently you have two choices from MSAL, i.e. `removeAccount` and `signoutWithAccount`:
https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/e97d8374d8dcaa5c2882f517e2093309de11c065/MSAL/src/public/MSALPublicClientApplication.h#L447

Hope the above information helps.

**Comment by jukemoon** [comment]
Thanks for the input, @jasoncoolmax. This method is actually within [ms-intune-app-sdk-ios](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios) in the file [IntuneMAMEnrollmentManager.h](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/blob/8f0e6bdf08e0afd4cf0c8d1ff4edf8ea8c7f5436/IntuneMAMSwift.xcframework/ios-arm64/IntuneMAMSwift.framework/Headers/IntuneMAMEnrollmentManager.h). For completeness, the second method, getCurrentAccountWithParameters, is in the file [MSALPublicClientApplication+SingleAccount.h](https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/e97d8374d8dcaa5c2882f517e2093309de11c065/MSAL/src/public/MSALPublicClientApplication%2BSingleAccount.h) located within this repository. 

Since the two methods are related but located to two separate repositories, I wanted to start here and seek guidance for whether or not an issue should be opened under [microsoft-authentication-library-for-objc](https://github.com/AzureAD/microsoft-authentication-library-for-objc). 

Please let me know your thoughts.

**Comment by jasoncoolmax** [comment]
@jukemoon Sorry, i just edited my previous reply. 

`deRegisterAndUnenrollAccount ` from Intune SDK won't delete the MSAL accounts. If you want to delete the account or sign out of the account, you should call 
`removeAccount` or `signoutWithAccount`:

https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/e97d8374d8dcaa5c2882f517e2093309de11c065/MSAL/src/public/MSALPublicClientApplication.h#L447

Let me know if that helps.

**Comment by jukemoon** [comment]
Thank you for the information, @jasoncoolmax! I'll run with this; if any issues arise, I'll let you know. In the meantime since I have no further questions, I'll close this issue.
