### ISSUE TITLE
Error Login using MSAL 

### ISSUE THREAD

**Issue by AhmadMhmoud** [AzureAD/microsoft-authentication-library-for-objc#1793]
I am trying to login to Azure using MSAL interactive Sign In

I have created an instance of MSALInteractiveTokenParameters with my scopes and setting  MSALPromptType.Login.

When I call the function that initializes the sign In the logger writes this:
'com.apple.AuthenticationServices.WebAuthenticationSession error 2'

I am using MacOS 11.7.9 -x64

**Comment by ameyapat** [comment]
Hi @AhmadMhmoud Can you provide MSAL logs? Briefly looking at the error it might be an implementation error on your side

**Comment by AhmadMhmoud** [comment]
The log contained this:
The operation could not be completed (com.apple.AuthenticationService.WebAuthenticationService error 2).
I am using MSAL for login.

**Comment by ameyapat** [comment]
@AhmadMhmoud  Please follow instructions in https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-logging-ios?tabs=objc to setup MSAL logging and provide MSAL logs to investigate further. Thanks

**Comment by kaisong1990** [comment]
Closing for now.
@AhmadMhmoud  feel free to reopen once you get the new MSAL logs
