### ISSUE TITLE
Interception of JS Commands/Messages with webViewParameters.customWebview

### ISSUE THREAD

**Issue by odariusgeorge** [AzureAD/microsoft-authentication-library-for-objc#1832]
Is it possible to implement the interception of JS commands/messages([github link](https://github.com/FirebaseExtended/analytics-webview/blob/master/ios/swift/FirebaseAnalyticsWeb/ViewController.swift)) with the help of: `webViewParameters.customWebview`

Context: 
SwiftUI App:

```
let webViewParameters = MSALWebviewParameters(authPresentationViewController: UIApplication.topViewController)
webViewParameters.webviewType = .wkWebView
let parameters = MSALInteractiveTokenParameters(scopes: getScopes(), webviewParameters: webViewParameters)
parameters.loginHint = email
parameters.extraQueryParameters = [centerQueryParameterName: favoriteCenterIdentifier]

applicationContext.acquireToken(with: parameters) { result, error in
                guard let value = result else {
                    appLogger.error("[🔑] Could not acquire token: \(String(describing: error))")
                    return promise(.failure(checkAuthenticationError(error: error)))
                }
                appLogger.info("[🔑] Acquired access token interactively")
                return promise(.success(value.accessToken))
}
```

From my understanding it has to be something like this:

```
class DummyVC: UIViewController, WKScriptMessageHandler {

        var webView: WKWebView?

        func userContentController(_ userContentController: WKUserContentController, didReceive message: WKScriptMessage) {
            guard let body = message.body as? [String: Any],
                  let command = body["command"] as? String,
                  let name = body["name"] as? String else { return }

            if command == "setUserProperty" {
                guard let value = body["value"] as? String else { return }
                Analytics.setUserProperty(value, forName: name)
            } else if command == "logEvent" {
                guard let params = body["parameters"] as? [String: NSObject] else { return }
                Analytics.logEvent(name, parameters: params)
            }
        }
}
```

And in the end, the dummyVC should be used to construct the 'MSALWebviewParameters', but I ran into the following error: 
```parentViewController is a required parameter on iOS```

**Comment by mipetriu** [comment]
Hi @odariusgeorge, I don't think this scenario has been tested, as I'm not sure its an officially supported scenario.

That being said, is it possible that the `UIApplication.topViewController` that you are passing as the `authPresentationViewController` is resolving to nil? We've seen this situation occur when the app is not fully active in foreground the window hierarchy is not ready.

**Comment by odariusgeorge** [comment]
Hi @mipetriu. Thanks for the reply.

It's not possible in the context that I'm using it and the scenario that I was talking about it's not really and edge case.
As soon as I'm trying to pass the custom webview, the Azure WebView is not presented anymore.

The code below is not working:

```
            let customWebView = WKWebView(frame: .zero, configuration: .init())
            let webViewParameters = MSALWebviewParameters(authPresentationViewController: UIApplication.topViewController)
            webViewParameters.webviewType = .wkWebView
            webViewParameters.customWebview = customWebView
```

The code below is working:

```
            let customWebView = WKWebView(frame: .zero, configuration: .init())
            let webViewParameters = MSALWebviewParameters(authPresentationViewController: UIApplication.topViewController)
            webViewParameters.webviewType = .wkWebView
```

Do you have a working example/code snippet for the scenario where a custom webview is passed to the MSALWebviewParameters?

**Comment by odariusgeorge** [comment]
I found the way to make it work:

```
        let frame = UIApplication.topViewController.view.frame
        webView = .init(frame: frame)
        webView.configuration.userContentController.add(MessageHandler(), name: "firebase")
```

and then:

```
            UIApplication.topViewController.view.addSubview(webView)
            let webViewParameters = MSALWebviewParameters(authPresentationViewController: UIApplication.topViewController)
            webViewParameters.webviewType = .wkWebView
            webViewParameters.customWebview = webView
```

The only issue left is that now I dont have the navigation bar on the topViewController anymore and I cannot cancel the process.

Any idea on how to handle that?
Thanks

**Comment by mipetriu** [comment]
Hi @odariusgeorge, if you are using your own custom webview, you will need to handle functionality such navigation bars and buttons yourself as part of that webview's implementation. There is some documentation regarding custom webviews [here](https://learn.microsoft.com/en-us/azure/active-directory/develop/customize-webviews). Apple should also have rich documentation as well.
