### ISSUE TITLE
Receiving an expired token when using MSALPublicClientApplication.acquireTokenSilent

### ISSUE THREAD

**Issue by aaa-1902** [AzureAD/microsoft-authentication-library-for-objc#1833]
Details 
MSAL 1.2.5

Working on new installs, however when the token has reached it's expiration it still gets the previous token.
For context when the App receives a 401 error it requests a token using acquireTokenSilent however the retrieved value is still the previous token.

Seems like a similar case with #1781

**Comment by kaisong1990** [comment]
@aaa-1902 Thanks for reaching out. Do you mean the resource service returned 401 or the MS authentication service did?

Please also share MSAL logs and we can take a look.

**Comment by kaisong1990** [comment]
Closing as no updates for a week. Please reopen once you have  new logs

**Comment by aaa-1902** [comment]
Hi @kaisong1990 

Here's the logs

MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] No cached preferred_network for authority
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] Caching AAD Environements
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] networkHost: login.microsoftonline.com, cacheHost: login.windows.net, aliases: login.microsoftonline.com, login.windows.net, login.microsoft.com, sts.windows.net
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] networkHost: login.partner.microsoftonline.cn, cacheHost: login.partner.microsoftonline.cn, aliases: login.partner.microsoftonline.cn, login.chinacloudapi.cn
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] networkHost: login.microsoftonline.de, cacheHost: login.microsoftonline.de, aliases: login.microsoftonline.de
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] networkHost: login.microsoftonline.us, cacheHost: login.microsoftonline.us, aliases: login.microsoftonline.us, login.usgovcloudapi.net
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] networkHost: login-us.microsoftonline.com, cacheHost: login-us.microsoftonline.com, aliases: login-us.microsoftonline.com
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] Resolved authority, validated: YES, error: 0
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] Looking for access token...
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] (Default accessor) Looking for token with aliases (
    "login.windows.net",
    "login.microsoftonline.com",
    "login.windows.net",
    "login.microsoft.com",
    "sts.windows.net"
), tenant 67d6a216-1e3e-4dcf-b7df-b84dee09e7a1, clientId 68839108-195e-4b18-94a6-16316fe17852, scopes api://68839108-195e-4b18-94a6-16316fe17852/access_as_user
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] (MSIDAccountCredentialCache) retrieving cached credentials using credential query
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] Keychain find status: 0
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] (MSIDAccountCredentialCache) retrieved 1 cached credentials
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] (MSIDAccountCredentialCache) credential query requires exact match with the cached credential items. Performing additional filtering checks.
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] (MSIDAccountCredentialCache) returning 1 filtered credentials
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] (Default accessor) Found 1 tokens
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] Found access token for account 5665d95f:auth.placeholder-a3f6f8b2__staehr.as which expires in 2975.322781
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] Found valid access token.
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] Looking for family refresh token...
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] Keychain find status: 0
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] Didn't find family refresh token
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] Looking for app refresh token...
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] (Default accessor) Looking for token with aliases (
    "login.windows.net",
    "login.microsoftonline.com",
    "login.windows.net",
    "login.microsoft.com",
    "sts.windows.net"
), tenant (null), clientId 68839108-195e-4b18-94a6-16316fe17852, scopes (null)
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] (MSIDAccountCredentialCache) retrieving cached credentials using credential query
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] Keychain find status: 0
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] (MSIDAccountCredentialCache) retrieved 2 cached credentials
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] (MSIDAccountCredentialCache) credential query requires exact match with the cached credential items. Performing additional filtering checks.
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] (MSIDAccountCredentialCache) cached item had mismatching homeAccountID or environment/aliases with the credential query. excluding from the results.
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] (MSIDAccountCredentialCache) returning 1 filtered credentials
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] (Default accessor) Found 1 tokens
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] Found app refresh token.
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] (Default accessor) Looking for token with aliases (
    "login.windows.net",
    "login.microsoftonline.com",
    "login.windows.net",
    "login.microsoft.com",
    "sts.windows.net"
), tenant 67d6a216-1e3e-4dcf-b7df-b84dee09e7a1, clientId 68839108-195e-4b18-94a6-16316fe17852, scopes (null)
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] (MSIDAccountCredentialCache) retrieving cached credentials using credential query
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] Keychain find status: 0
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] (MSIDAccountCredentialCache) retrieved 1 cached credentials
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] (MSIDAccountCredentialCache) credential query requires exact match with the cached credential items. Performing additional filtering checks.
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] (MSIDAccountCredentialCache) returning 1 filtered credentials
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] (Default accessor) Found 1 tokens
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] Found id token Masked(not-null) for account 5665d95f:Masked(not-null).
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] Keychain find status: 0
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36] Stop background task with type 1 & taskId : 53
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] Silent flow finished. Result (not-null), error: 0 error domain: (null)
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36] Parsing result access token
MSAL log: TID=353045 MSAL 1.1.23 iOS Sim 16.4 [2023-09-06 08:45:36 - E362A8CD-ED92-4AE0-9103-D17B277E2FC9] [MSAL] acquireTokenSilent returning with at: dc2cd8c scopes:(
    "api://68839108-195e-4b18-94a6-16316fe17852/access_as_user"
) expiration:2023-09-06 09:35:12 +0000

**Comment by aaa-1902** [comment]
Just to add sending the token acquired silently to https://login.microsoftonline.com/common/oauth2/v2.0/token  return us this error

{"error":"invalid_request","error_description":"AADSTS900144: The request body must contain the following parameter: 'assertion'.\r\nTrace ID: 35ded3ca-0ff6-4ff6-ac2d-a14115148d00\r\nCorrelation ID: 1f688e9b-b663-43af-b9fe-7e0a036ab473\r\nTimestamp: 2023-09-06 08:33:10Z","error_codes":[900144],"timestamp":"2023-09-06 08:33:10Z","trace_id":"35ded3ca-0ff6-4ff6-ac2d-a14115148d00","correlation_id":"1f688e9b-b663-43af-b9fe-7e0a036ab473","error_uri":"https://login.microsoftonline.com/error?code=900144"}
