### ISSUE TITLE
Security review issue (Weak encryption)

### ISSUE THREAD

**Issue by sme-bock030** [AzureAD/microsoft-authentication-library-for-objc#1834]
Hi!
After migrating to MSAL iOS framework for authentication, we have got the following issue in the latest security review report for our app:

Null Initialization Vector Used for Symmetric Encryption
The vulnerable code locations perform AES encryption using the CBC mode.
In this mode of operation, an Initialization Vector (IV) must be supplied to ensure that the same message encrypted with the same key multiple times produces completely different outputs. Hence, the IV needs to be rotated on every cryptographic operation to ensure a different output.
The App instead uses a NULL IV, which never changes across different encryption operations. This allows for an example an attacker that is watching all the encrypted messages exchanged to identify when a previously sent message is sent again.
 
 
-[NSData (AES) msidAES128DecryptedDataWithKey:keySize:] calls CCCrypt(, _, _, _, _, NULL, _)
Stack Trace
The following related source code symbols were identified:
{{-[MSIDWPJKeyPairWithCert .cxx_destruct]
-[MSIDWPJKeyPairWithCert setKeyChainVersion:]
-[_OBJC_CLASS_$_NSData (AES) msidSignHashWithPrivateKey:]
-[_OBJC_CLASS_$_NSData dataWithBytesNoCopy:length:]
-[(id) length]
-[(id) bytes]}}
This code was identified within the HelpDeskUAT.app/Frameworks/MSAL.framework/MSAL binary.

As for as I understand, this method is used for broker response handling. Is it a real security issue?
Thank you!

**Comment by antonioalwan** [comment]
Hi @sme-bock030, this question has been raised before [here](https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/issues/990)
Let me know if you have other questions!
