### ISSUE TITLE
Question: Skip consent alert?

### ISSUE THREAD

**Issue by theedov** [AzureAD/microsoft-authentication-library-for-objc#1838]
Hello,

Is it possible to skip the consent alert that is showing every time I try to acquire an access token? 
`[APP_NAME] Wants to Use "microsoftonline.com" to Sign In`

Or it's being shown by the system and there is no way to change/skip that?

**Comment by antonioalwan** [comment]
Hi @theedov thanks for raising this question. this consent is shown by Apple as part of using ASWebAuthenticationSession as a system browser for the interactive login. If you'd like to not see the prompt, you could configure MSAL to use a WKWebView rather than a system browser through [MSALWebviewType](https://azuread.github.io/microsoft-authentication-library-for-objc/Enums/MSALWebviewType.html). You can find more info about the implications of choosing either webview option in this doc: https://learn.microsoft.com/en-us/azure/active-directory/develop/customize-webviews.

**Comment by theedov** [comment]
Thank you @antonioalwan for the link.
I've tried to change the type to `.safariViewController` but it seems that `acquireToken` closure is not getting fired anymore. I assume it has someting to do with `** For SSO to work, tokens need to be shared between apps. This requires a token cache, or broker application, such as Microsoft Authenticator for iOS.` Could you point me in the right direction on how to implement token caching when `safariViewController` is selected.

**Comment by antonioalwan** [comment]
Hi @theedov, please see guidance in MSAL readme: https://github.com/AzureAD/microsoft-authentication-library-for-objc#objective-c for details.

**Comment by theedov** [comment]
> Hi @theedov, please see guidance in MSAL readme: https://github.com/AzureAD/microsoft-authentication-library-for-objc#objective-c for details.

Yes, I followed the readme and it was working well before I changed `.webviewType`.

Here is my code:

```
    var applicationContext : MSALPublicClientApplication?
    
    private func initMSAL() {
        let config = MSALPublicClientApplicationConfig(clientId: "CLIENT_ID")
        let application = try? MSALPublicClientApplication(configuration: config)
        guard let application = application else { return }

        self.applicationContext = application
    }

    func auth() {
        guard let applicationContext { return }

        let webviewParameters = MSALWebviewParameters(authPresentationViewController: self)
        webviewParameters.webviewType = .safariViewController

        let interactiveParameters = MSALInteractiveTokenParameters(scopes: kScopes, webviewParameters: webviewParameters)

        applicationContext.acquireToken(with: interactiveParameters, completionBlock: { [weak self] (result, error) in
            guard let self else { return }

            guard let authResult = result, error == nil else {
                return
            }

            sendSuccessEvent(authResult)
        })
    }
```

**Comment by theedov** [comment]
@antonioalwan Sorry, I indeed forgot to implement SceneDelegate(I use SwiftUI). All works now.
