### ISSUE TITLE
Azure AD DeviceID is not retrieved from the Broker by MSAL

### ISSUE THREAD

**Issue by stevejmonk** [AzureAD/microsoft-authentication-library-for-objc#1840]
Azure AD DeviceID is not retrieved from the Broker by MSAL, our mobile app which is a custom browser is then blocked by conditional Access, this happens because the Device ID value is null and the Azure AD lookup to see if the device is registered in Azure AD fails, this prevents our browser from signing in to all Microsoft sites and services.

How do we force getting the DeviceID on all authentication requests from MSAL?

**Comment by swasti29** [comment]
@stevejmonk Kindly share the Authenticator logs. 
To collect the Authenticator logs kindly follow the instructions given [here](https://learn.microsoft.com/en-us/troubleshoot/azure/active-directory/send-microsoft-authenticator-logs)
