### ISSUE TITLE
MSAL SDK for IOS current version can be support IOS 12.0 or not?

### ISSUE THREAD

**Issue by msyinjie** [AzureAD/microsoft-authentication-library-for-objc#1841]
Hi

Colud you tell me the MSAL SDK current version for IOS can be support the IOS 12.0 or not?

thank you.

**Comment by swasti29** [comment]
@msyinjie MSAK SDK supports iOS 14 and above. 
Please find more information [here](https://github.com/AzureAD/microsoft-authentication-library-for-objc#supported-versions) regarding supported versions
