### ISSUE TITLE
Xcode 15 beta 8

### ISSUE THREAD

**Issue by guo-pf** [AzureAD/microsoft-authentication-library-for-objc#1842]
Successfully used cocoapods, but failed to use Carthage.
 
 
#!/usr/bin/env sh
 
set -euo pipefail
 
xcconfig=$(mktemp /tmp/static.xcconfig.XXXXXX)
trap 'rm -f "$xcconfig"' INT TERM HUP EXIT
 
echo 'IPHONEOS_DEPLOYMENT_TARGET = 11.0' >> $xcconfig
echo "ENABLE_BITCODE=NO" >> $xcconfig
 
export XCODE_XCCONFIG_FILE="$xcconfig"
carthage "$@"
 
carthage bootstrap --platform iOS --cache-builds --use-xcframeworks

 
*** Fetching microsoft-authentication-library-for-objc
*** Building scheme "MSAL (iOS Framework)" in MSAL.xcworkspace
 … … …
### Build Failed
  Task failed with exit code 65:
The following build commands failed:
  CompileC /Users/abcd/Library/Caches/org.carthage.CarthageKit/DerivedData/15.0_15A5229m/microsoft-authentication-library-for-objc/main/Build/Intermediates.noindex/ArchiveIntermediates/MSAL\ (iOS\ Framework)/IntermediateBuildFilesPath/MSAL.build/Release-iphoneos/MSAL\ (iOS\ Framework).build/Objects-normal/arm64/MSIDInteractiveRequestParameters+MSALRequest.o /Users/abcd/Desktop/MyTestsDemo/CarthageXcode15Demo/Carthage/Checkouts/microsoft-authentication-library-for-objc/MSAL/src/MSIDInteractiveRequestParameters+MSALRequest.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'MSAL (iOS Framework)' from project 'MSAL')
(1 failure)

**Comment by swasti29** [comment]
@guo-pf Kindly help me with more details of failures and errors. Is this issue happening only for Xcode 15 beta 8 or with previous versions of Xcode?

**Comment by guo-pf** [comment]
@swasti29  First of all, thank you for your reply.  

Currently, it only occurs in Xcode15. Xcode14 was not found.

### Log:
[carthage.log](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/12554712/carthage.log)

**Comment by swasti29** [comment]
@guo-pf MSAL supports 14.0 and above. Also the latest MSAL version is 1.2.15. Kindly use the latest version.

To use MSAL via carthage, Kindly follow the instruction [here](https://learn.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-ios#carthage)
