### ISSUE TITLE
MSAL 1.2.16 release - new APIs

### ISSUE THREAD

**Issue by lucac-apps** [AzureAD/microsoft-authentication-library-for-objc#1860]
In the release note of [1.2.16](https://github.com/AzureAD/microsoft-authentication-library-for-objc/releases/tag/1.2.16) there is the following statement:

"Expose APIs for manually setting time_Interval for request and session resource (https://github.com/AzureAD/microsoft-authentication-library-for-objc/pull/1288)"

Is there any documentation about these APIs? In case there is not, can you please help me to undestand what is all about ?

Please notice that the linked issue [1288 ](https://github.com/AzureAD/microsoft-authentication-library-for-objc/pull/1288)seems to be unrelated to those APIs.

**Comment by jasoncoolmax** [comment]
Hi @lucac-apps , sorry for the confusion. The #1288 is actually a PR in common core [here](https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/1288/files). It is basically providing an option to set the timeout for network calls. 

Let me know if you need more information or if you have a more specific request.
