### ISSUE TITLE
Sign in popup when signout is triggered

### ISSUE THREAD

**Issue by ncubelic** [AzureAD/microsoft-authentication-library-for-objc#1896]
Issue Summary:
After successfully logging in, performing a sign-out operation triggers a sign-in popup. If the user taps "Cancel," the sign-out process is completed, but a "Continue MSAL" popup is presented. Meanwhile, the user is signed out in the background.

Code Example:

```swift
func signOut(viewController: UIViewController, handler: @escaping () -> Void) {
    logger.info("Signing out from the current account")
    let webviewParameters = MSALWebviewParameters(authPresentationViewController: viewController)
    let signoutParameters = MSALSignoutParameters(webviewParameters: webviewParameters)
    signoutParameters.signoutFromBrowser = true
    
    guard let accountId else {
        logger.error("Account ID is null")
        handler()
        return
    }
    guard let account = try? application?.account(forIdentifier: accountId) else {
        logger.error("Could not get the account for accountID: \(accountId)")
        handler()
        return
    }
    application?.signout(with: account, signoutParameters: signoutParameters) { [logger] success, error in
        if let error {
            logger.error("Could not sign out from Microsoft: \(error)")
            handler()
            return
        }
        UserDefaults.standard.removeObject(forKey: Consts.UserDefaults.loginUsingActiveDirectory)
        UserDefaults.standard.removeObject(forKey: Consts.UserDefaults.activeDirectoryAccountId)
        logger.info("Successfully signed out from Microsoft")
        handler()
    }
}
```
Expected Behavior:
After executing the sign-out function, the user should be signed out without encountering any additional sign-in or "Continue MSAL" popups.

Actual Behavior:
The sign-out process triggers a sign-in popup. Despite these popups, the user is signed out in the background.

Screenshot:

![IMG_4767](https://github.com/AzureAD/microsoft-authentication-library-for-objc/assets/4377760/d34499e5-abe6-480f-8a1e-786a1d73f42b)

Additional Information:

Version of MSAL: 1.2.17
iOS Version: 15, 16, 17

Please let me know if you need any further information to assist in resolving this issue.

**Comment by ameyapat** [comment]
The behavior is expected when signoutParameters.signoutFromBrowser = true. We need to open a web view to sign out from there and clear cookies.
To clarify the problem, can you specify which type of browser are you using? And can you provide a screen recording of the behavior?

**Comment by ncubelic** [comment]
@ameyapat Here is the screen recording. On 'Logout' action, signOut function from above is called. 

We had another problem without parameter `signoutParameters.signoutFromBrowser = true`. Depending on the user we have different azure configurations: kClientId, kRedirectUri and kAuthority. First user signs in using AD and after some time, if other user with different azure configuration tries to sign in, in the webview popup we get an error saying that user is trying to sign in with invalid credentials but seems like library is trying to sign in the user with previous configurations.

https://github.com/AzureAD/microsoft-authentication-library-for-objc/assets/4377760/f4a1bd2d-a5b3-4eef-9868-a30a3b35e2ee

**Comment by ameyapat** [comment]
@ncubelic If the user clicks 'cancel' as in the video, local sign out will be performed but signout from browser will not happen because the browser needs to popup for its cookies to be cleared. If user clicks continue a browser will briefly popup allowing us to clear cookies.
If signoutFromBrowser = false, then cookies for the previous users might still be cached in the browser and will be valid until its expiry

**Comment by ncubelic** [comment]
@ameyapat how can I handle this?

1. Log in with "user-1" in "tenant-1"
2. On sign out - application?.signout(with: "user-1-account", signoutParameters: signoutParameters)
3. Log in with "user-2" in "tenant-2"
4. I get popup showing that "user-1" does not exist on "tenant-1" 

I need the sign in popup in which I should be able to add new account and enter "user-2" credentials to log in

When I set signoutFromBrowser = true, upon new log in I get an popup to add another account for sign in. And it works as expected, but then I have that popup with cancel and continue when sign out is performed.

**Comment by ameyapat** [comment]
@ncubelic to clear the cookies from ASWebAuthenticationSession the pop up with continue and cancel shows up because that is an iOS behavior that is not in out control. User will have to click continue and then try to sign-in using user-2
