### ISSUE TITLE
Bundled Consent & AADSTS530003

### ISSUE THREAD

**Issue by macdrevx** [AzureAD/microsoft-authentication-library-for-objc#1900]
The iOS app I work on uses an OBO auth flow with bundled consent:

1. Interactive token request:
    scopes: ["api://\<our server app ID\>/.default"]
    prompt: .selectAccount
2. Silent token request:
    account ID from the interactive token request result
    scopes: ["https://graph.microsoft.com/.default"]
    forceRefresh: true
3. Pass access token obtained in step 1 to our server which uses it as the assertion in the OBO token request

We have some customers for whom step 2 is failing with the error `AADSTS530003: Your device is required to be managed to access this resource.`

2 of them have opened support tickets in the Azure portal, and I was able to join a support call related to one of them today, but wasn't able to understand whether there is anything we can change about our auth flow to enable them to sign in successfully.

Another customer who experienced the same error said that they resolved it by first signing into the Apple Mail app on the same device. Does it make sense that that would resolve the issue? Might there be any other solutions that would not require redirecting folks outside of our own app?

**Comment by mipetriu** [comment]
Hello @macdrevx, that error code is coming from the server, and it seems at first look to be related to a conditional access policy that requires a device to be MDM managed in order to access a particular resource. Do you happen to have an MSAL log from an instance of this error, or at least a correlationID and timestamp of an instance of the error? I can check the policies from my end.

**Comment by macdrevx** [comment]
Hi @mipetriu thanks for the reply. I do have some correlationIDs and timestamps, but they're from customer tenants — is there a way for me to share those with you privately?

**Comment by mipetriu** [comment]
@macdrevx - yes, feel free to send the correlationID and timestamps via email to me directly at mipetriu@microsoft.com.

Regarding Apple Mail, the customers may have the same conditional access policy requirements set for Apple Mail resources as they do for "https://graph.microsoft.com/.default". That way, the interactive request in Apple Mail results in tokens with claims that can also pass the CA check silently in request number 2 in your app. If the resource accessed by your app's interactive request does not have the same CA requirement, those claims may not be requested.

I should be able to check the CA requirements in the example correlationIDs.

**Comment by macdrevx** [comment]
@mipetriu done!

> If the resource accessed by your app's interactive request does not have the same CA requirement, those claims may not be requested.

Our app's interactive token request is supposed to trigger bundled consent — our server app's manifest lists our client app ID in its knownClientApplications array. The goal here is for the customer to auth & consent once and have it apply to both the client and the server. Shouldn't the bundled consent process also account for CA requirements for all resources that the apps will need?

**Comment by macdrevx** [comment]
Hi @mipetriu, have you had a chance to look into this error?

**Comment by mipetriu** [comment]
Hi @macdrevx, yes I have. Firstly, I'm not very familiar with the bundle ID consent flow - my understanding is that this is a method to consent to a web API inside an app as the user is consenting to the app itself. This consent flow is not related to CA, as CA is calculated and resolved during a login attempt.

I see that there is indeed a device compliance-based CA policy on the resource in call #2 from your original message. I also see that the device used is actually managed, but that is not being recognized in your app. I would normally ask for MSAL logs to try to understand this further.

I also notice that the MSAL version being used is pretty old, I would recommend updating to the most recent version.

**Comment by macdrevx** [comment]
@mipetriu thanks for the reply. To clarify, it's "bundled consent" unrelated to the concept of iOS Bundle ID. See [knownClientApplications docs](https://learn.microsoft.com/en-us/entra/identity-platform/reference-app-manifest#knownclientapplications-attribute).

Re: old MSAL — we released an app update that uses the latest MSAL version a week ago, but the logs I emailed you were from an older version. That said, we have seen the same error even with the latest MSAL. I can email you some additional logs if needed.

> the device used is actually managed, but that is not being recognized in your app

Exactly, this is the core of what I'm trying to understand. I need to figure out what needs to change so that the silent token request will not fail due to it not recognizing that the device actually is managed.

**Comment by mipetriu** [comment]
@macdrevx - is your application configured to use the authentication broker if it is on the device? If the Authenticator app is on the device, is your auth routed through it?

**Comment by macdrevx** [comment]
Yes

**Comment by mipetriu** [comment]
@macdrevx 
Regarding this:
> I need to figure out what needs to change so that the silent token request will not fail due to it not recognizing that the device actually is managed.

If the customer has a different CA policy on the "https://graph.microsoft.com/.default" scope requested in the silent request that wasn't applied to the scopes from the initial interactive request, the user will need another interactive request to complete a device authentication in order to resolve the CA policy.

In terms of the example request - I see from the server-side logs that after the CA policy requires your app to complete another interactive request, there is no device information sent in that ensuing request. If that request was routed through the broker, I would ask the affected user to submit Authenticator logs to take a closer look. Is that something that is feasible in this case?

In case its needed: https://github.com/AzureAD/azure-activedirectory-library-for-objc/wiki/Instructions-on-Collecting-Microsoft-Authenticator-Logs

**Comment by macdrevx** [comment]
@mipetriu so if the customer added a CA policy on the `api://<our server app ID>/.default` scope that was otherwise equivalent to the policy on the `https://graph.microsoft.com/.default` scope, then this might work?

And the other option is that we'd need to make the app fall back to using an interactive token request for `https://graph.microsoft.com/.default` when we see this error?

**Comment by macdrevx** [comment]
@mipetriu is my understanding in the previous comment correct?

**Comment by mipetriu** [comment]
@macdrevx, yes, that's correct. I would expect a device authentication to complete successfully during an interactive token request for a resource that's protected by a CA policy (if the device is managed and compliant). Based on that, I believe those options should work.

Its generally recommended to follow a silent token failure with an interactive request, so I would nudge in that direction.

**Comment by macdrevx** [comment]
I'll give this a try and let you know what I find.

**Comment by chasemac** [comment]
@macdrevx  I'm having a similar issue

**Comment by mipetriu** [comment]
@macdrevx - If the service is looking for a Graph API access token and the customer has a CA policy protecting the Graph API resource, it doesn't seem unexpected to me that a CA-related error message would be returned.

Apologies for being less knowledgeable about the OBO flow - why does the token from #1 need to be given to the backend service if the service needs to acquire a Graph API token? Would it work to use the token from Graph API in #3?

**Comment by macdrevx** [comment]
> why does the token from step 1 need to be given to the backend service if the service needs to acquire a Graph API token? Would it work to use the token from Graph API in step 3?

The token is used as the "assertion". According to the [docs](https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-on-behalf-of-flow),

> `assertion` | Required | The access token that was sent to the middle-tier API. This token must have an audience (aud) claim of the app making this OBO request (the app denoted by the client-id field). Applications can't redeem a token for a different app (for example, if a client sends an API a token meant for Microsoft Graph, the API can't redeem it using OBO. It should instead reject the token).

Might there be someone from another team who we could loop in to help here?

**Comment by bgavrilMS** [comment]
I will provide some background info on how this is supposed to work. From a naming standpoint, I will use:

- **client** - the iOS app requesting token for the your web api
- **middle-tier api** - your web api
- **downstream api** - what your web api wants to call, Graph in this case.

So client gets token for middle-tier api, who then uses OBO to get token for downstream API. This all works fine until a tenant admin adds a conditional access policy (CAP) around the downstream API (Graph), e.g. device CAP. But they don't add the same policy for the middle-tier api. 

There are 2 ways around this: 

1. [More of a workaround] Ask the tenant admin to set the same CAP on the middle-tier API. No code changes should be needed.

2. [Actual solution, but needs work] When the middle-tier web api performs OBO and fails, the failure will be `MsalUIRequiredException` (assuming you use MSAL) and some `claims` (please confirm). This is called a `claims challenge`. You then have to reply back to the client 401 + WWW-Authenticate header containing those claims. The client parses the header and makes a new token request with the  `claim challenge`. MSAL on the client knows to bypass its token cache and go directly to the STS, where the claim challenge is taken into account. In your case, if the device is not managed, the end-user will get a message stating "Please install Authenticator" (@mipetriu will keep me honest on the last part).


For more details about OBO + Conditional Access / Incremental Consent please see https://learn.microsoft.com/en-us/entra/msal/dotnet/acquiring-tokens/web-apps-apis/on-behalf-of-flow#handling-multi-factor-auth-mfa-conditional-access-and-incremental-consent

If you are on .NET, we do recommend using our higher level library that will take care of most things on the web api, see https://github.com/MicrosoftDocs/microsoft-authentication-library-dotnet/blob/live/msal-dotnet-articles/acquiring-tokens/web-apps-apis/on-behalf-of-flow.md#if-you-are-using-aspnet-core

**Comment by macdrevx** [comment]
@bgavrilMS I really appreciate your reply. Thank you!

One point of clarification — is the result of handling the claim challenge a token for the downstream API with clientID = "client app ID"? Does the client then need to get a new token for the middle-tier api so that the middle-tier can retry the OBO request?

**Comment by bgavrilMS** [comment]
The middle-tier web api can't handle the claims challenge, because a web api can't prompt a user. Only the client can prompt. 

So yes, the client need to get a new token for the middle-tier API (all MSALs support add CLAIMS to a request) that proves the claims challenge. Then the web api then needs to call OBO using the new token from the client. It must not retrieve an old API from the cache.

It's important to think of OBO as session based, not user based. Do not try to cache OBO tokens on a user by user basis, but on a session basis. We recommend either using `sid` optional claim (needs config) in the client token or using `hash(client_token)` - this is what MSAL.NET does for caching.

**Comment by macdrevx** [comment]
Thank you!

> It's important to think of OBO as session based, not user based.

Can you say more about why this is the case?

**Comment by macdrevx** [comment]
Also, given that our first interactive request *does* get consent for all the static scopes defined by both the client and the middle-tier, isn't it a bit odd that it doesn't also know to fulfill any conditional access requirements related to the scopes for the middle-tier?

**Comment by bgavrilMS** [comment]
> Thank you!
> 
> > It's important to think of OBO as session based, not user based.
> 
> Can you say more about why this is the case?

Imagine this scenario: 

1. user with managed device gets token on client for middle tier web api. Then web api gets token for Graph and caches the token for Graph in some cache (e.g. Redis), using [user_id] -> [token for Graph]
2. the same user with an **un-managed** device gets token for middle tier web api. This is allowed if tenant admin did not set the policy for accessing web api, only for Graph. Now middle-tier api tries to get token for Graph. 

Normally, if middle-tier API goes to AAD (the token issuer), the CA policy will be enforced and they will get an error.
However, if the middle-tier API may instead retrieve the token from it's cache, since it knows the [user_id]. This is a security issue, because you just by-passed the CA policy.

This is why we recommend treating OBO as session based, when caching OBO tokens.

**Comment by bgavrilMS** [comment]
> Also, given that our first interactive request _does_ get consent for all the static scopes defined by both the client and the middle-tier, isn't it a bit odd that it doesn't also know to fulfill any conditional access requirements related to the scopes for the middle-tier?

Yeah, this is a fair point. It really depends on how CA policy has been setup, they are very flexible - tenant admin can specify a client app (the middle-tier api, the ios Client) and a resource (Graph) etc.

But I would expect that if a device managed client makes token requests, the tokens will have the a "device ID" claim inside them. As far as I know, this requires your iOS app to be configured to talk to Authenticator, @mipetriu can keep me honest here.  Here's an access token from a managed Windows device: 

<img width="366" alt="image" src="https://github.com/AzureAD/microsoft-authentication-library-for-objc/assets/12273384/e8683ed4-f7e6-4b43-abed-395fa0ad539a">

The token issuer - Entra ID / Azure AD - will know to propagate that claim when it performs the on-behalf-of flow. If this doesn't happen, then it's a bug on our side.

**Comment by bgavrilMS** [comment]
Possible workaround - I wonder if this is a bug with combined (bundled) consent...  Can you try to request token for Graph interactively and the for your api silently?

**Comment by macdrevx** [comment]
> I wonder if this is a bug with combined (bundled) consent... Can you try to request token for Graph interactively and the for your api silently?

Do you mean to do this as the initial step of the flow? Or only as a fallback after we see an error?

If the former, how would the user consent to our API?

**Comment by bgavrilMS** [comment]
I don't know the MSAL ObjC API in detail, but combined consent means: 

- when going to the authorization endpoint, use scope = resource1 + resource2
- then go to token_endpoint and use auth_code flow to get an access token for resource1
- then go to token_endpoint and use refresh_token flow to get an access token for resource2

Isn't this what you use? i.e. the user needs to consent both to Graph and to your API?

**Comment by macdrevx** [comment]
MSAL ObjC doesn't expose combined consent directly in the API and also [does not expose the auth code](https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1434).

Additionally, we want our flow to work for both Microsoft accts and Work + School accts, and during development, we found that combined consent only works with Microsoft accts if you specify the default scope for the API (credit to Will Fiddes of the AAD Developer Support team who was assisting us at the time. He chronicled some of his findings [here](https://blogs.aaddevsup.xyz/2023/07/how-to-bundle-consent/). See "STEP 3: THE SIGN-IN REQUEST" where he explains why the `.default` scope for the API must be used if you need to support Microsoft accounts).

In light of these 2 things, we…

* Client asks MSAL to do an "interactive token request" using scope = .default for our API (this triggers combined consent since we've configured [knownClientApplications](https://learn.microsoft.com/en-us/entra/identity-platform/reference-app-manifest#knownclientapplications-attribute). This results in an access token for our API
    * I think this does go to the authorization endpoint, but maybe it's different if there's a broker app installed. go to the token_endpoint and use auth_code to get access token for our API
* Client asks MSAL to do a "silent token request" using scope = .default for Microsoft Graph. This results in an access token for MS Graph
* Client passes API access token to API
* API goes to token_endpoint and uses OBO flow to get access token for MS Graph

**Comment by bgavrilMS** [comment]
Yeah, I was on an email thread with Will about that... Ultimately, if the client has tokens for your api and for Graph, it means consent must have been given. The error from the web api isn't about consent (although that can be treated in a similar way), it's about device conditional access policy. 

Updating the the client and web api to be able to handle claims is cleanest way to proceed. It will avoid lengthy investigations about device state and token caches. 

Otherwise, you'll have to provide @mipetriu with details about the state of the device so that he can investigate that part. Tokens obtained though Authenticator (and I think through a browser too) on a should be marked as being device complaint, e.g. via a "DeviceID" claim and OBO will copy the device compliance state.

**Comment by macdrevx** [comment]
@bgavrilMS @mipetriu I've reproduced this error in a test tenant via the following:

1. Set up a compliant-device CA policy that applies to Office 365 but not to our API
2. Configure the device compliance policy in the Intune portal
3. Enroll my iOS device using the Intune Company Portal app
4. Sign in to our iOS app
    * The interactive token request for a middle-tier access token succeeds (this is where we bundle consent)
    * The silent token request for a microsoft graph access token fails with `AADSTS530003: Your device is required to be managed to access this resource.`

I updated our app to do an interactive token request when the above happens:
    * Interactive token request for a microsoft graph access token succeeds. The first time you do this on a given device, it prompts you to use a certificate when connecting to `device.login.microsoftonline.com`:
<img width="480" alt="Screenshot 2024-01-11 at 11 17 34 AM" src="https://github.com/AzureAD/microsoft-authentication-library-for-objc/assets/205658/998f1b77-25ac-4bf1-bf21-f06e9f4fa4ec">
    * Silent token request for a middle-tier access token with force refresh set to true succeeds.

After that, the OBO request succeeds, and subsequent sign-ins appear to succeed without the second interactive token request.

I did not see the `DeviceID` claim in any of the tokens. Presumably the client certificate is involved in providing the necessary proof of device compliance?

Is there anyone who we could talk to about making it so that the first interactive token request evaluates the CA policies? As suggested earlier, it seems like the service would have enough information to know that should happen (e.g. the `knownClientApplications` reference). This would be a much better solution for us — getting tenant admins to list our middle-tier in their CA policies provides the smoothest sign-in experience but is an operational burden for us and is a hassle for our customers. Using a second interactive token request also works, but it makes for a chaotic UI, a complex implementation that we need to maintain, and misses out on the value we were trying to provide by using `knownClientApplications`.

**Comment by bgavrilMS** [comment]
Thanks for following up @macdrevx . It's great that you have a solution to the problem and I agree that the solution is too low-level. We have other partners (internal and external) who find out this complex part of the protocol the hard way :(. 

As far as I can tell, [knownClientApplications](https://learn.microsoft.com/en-us/entra/identity-platform/reference-app-manifest#knownclientapplications-attribute), as well as [preAuthorizedApplications](https://learn.microsoft.com/en-us/entra/identity-platform/reference-app-manifest#preauthorizedapplications-attribute) deal with **consent** only, not with Conditional Access. 

CC @psignoret and @localden

**Comment by Veena11** [comment]
Closing as no further action required. Feel free to open if need be.
