### ISSUE TITLE
Interactive auth files with error] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MSIDInteractiveTokenRequestParameters fillWithWebViewParameters:useWebviewTypeFromGlobalConfig:customWebView:error:]: unrecognized

### ISSUE THREAD

**Issue by rajenshar** [AzureAD/microsoft-authentication-library-for-objc#1907]
Hello,

I am using MSAL library for objc. I wrote a simple app and I see an error with Interactive auth. on Mac OS 10.15 and above, as per documentation ASWebAuthSession is available on Systembrowser. But looks like system browser is not invoked. I see a similar issue logged here [ ](https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1416) but I do not see any resolution. Is the fix similar to what is done for library for js which I see merged in May? Will this be ported to objective c as well or am I missing something in my code?
[](https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/651)

**Comment by rajenshar** [comment]
just  some more information on what I am trying. I have a simple story board macOs app. NSapplication, ViewContorller and Appdelegate. similar to sample given for switfUI. The only difference is I am building MSAL library (static), libIdentityCore and libMSAL (macOS Static Library).a and linking it to the app and trying to call MSAl apis.  Please cut the slack on me as I am working on this first time.

**Comment by rajenshar** [comment]
I am not an expert on objective-c but I tried to debug the issue. I feel fillWithWebViewParameters is called on object of class MSIDInteractiveTokenRequestParameters. But fillWithWebViewParameters definition  is in its base class named MSIDInteractiveRequestParameters. There is no definition in MSIDInteractiveTokenRequestParameters with super class invocation of fillWithWebViewParameters.  perhaps that is why it is complaining unrecognised selector.

**Comment by rajenshar** [comment]
Same issue is with   setAccountIdentifierFromMSALAccount.   [MSIDInteractiveTokenRequestParameters setAccountIdentifierFromMSALAccount:]: unrecognized selector sent to instance 0x131e04ef0. By the way just to test, I commented the call to fillWithWebViewParameters and setAccountIdentifierFromMSALAccount in MSALPublicClientApplication  and linked the library to my app and ran, I can see system browser invoked and showing the logged in account etc and flow goes through.

**Comment by swasti29** [comment]
@rajenshar This should not be issue in general. Kindly follow the quickstart given [here](https://learn.microsoft.com/en-us/entra/identity-platform/quickstart-mobile-app-ios-sign-in).

Also you mentioned the simillar issue reported here, Kindly tag the same here.

Let me know if you still see the issue following the quickstart.

**Comment by rajenshar** [comment]
@swasti29  Thank you for the reply.

https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1416 

This  above link mentions similar issue. Also the quick start link you gave I had tried already and sample give for swift I was able to run without any issues. I tried this sample 

https://github.com/Azure-Samples/ms-identity-macOS-swift-objc and used url mentioned in notes as swift dependency and everything works fine. But if I take MSAL source code and compile the code to get static libs and use those static libs with a sample app in objective-c, I see this issue. Perhaps the way it is compiled or optimised has some issue, I do not know. But it is easy to reproduce the issue.

1. Compile the source code of release 1.2.18 in Xcode. 
2. generatelibMSAL (macOS Static Library).a
3. Link this with basic app (objective-c)
4. Call acquireTokenInteractively
5. Issue is seen. fillWithWebViewParameters:useWebviewTypeFromGlobalConfig:customWebView:error:]: unrecognized selector

**Comment by swasti29** [comment]
Hi @rajenshar,

How are you including the header files? 
The header files need to be included in Header Search Path under Build Settings as given below. Then you can include those header in respective objective C code of your basic app. 
![image](https://github.com/AzureAD/microsoft-authentication-library-for-objc/assets/12692041/95d83bb1-a415-46b6-a26c-ead00a5f4cab)

If you still see the issue, I would recommend using command "nm -a" with generated static library to verify if something is missing for specific architecture. 

Also is it possible for you to share your codebase? I will take a look.

**Comment by rajenshar** [comment]
@swasti29 , yes indeed all needed header files from public folder I am referring in source files and I have set the path in header search paths. 

Anyway, I will share a sample code soon

**Comment by swasti29** [comment]
@rajenshar you can share [identity-apple-eng@microsoft.com](mailto:identity-apple-eng@microsoft.com).

Also did you see any undefined symbols errors?

**Comment by rajenshar** [comment]
@swasti29 < I have sent the tar file of the project to the email id you mentioned. 

As I said, I did not see any undefined symbol errors while compiling except WPJ related i.eUndefined symbol: _OBJC_CLASS_$_MSALWPJMetaData. But for this, I had to add the .m file in compilation list and the compilation was successful. this is the only change I did to get code compiled succesfully.

**Comment by rajenshar** [comment]
@swasti29, just wanted to check if you received zipped project file that I sent. if not please let me know.

**Comment by rajenshar** [comment]
@swasti29  any update on if you received my sample on the email id you shared?  At least want to make sure that I sent it and was delivered.

**Comment by swasti29** [comment]
Hi @rajenshar 
 I noticed that MSAL has been included both as a static library and submodule in the project, resulting in the entire MSAL being part of the project, which might not be necessary and might be resulting into unnecessary issues you are seeing since those files might not be required by MSAL. To streamline this, please follow these steps after building MSAL in Xcode:

1. Link the generated MSAL and identity static libraries in the "Frameworks and Libraries" section under "Build Phases" from your Build Folder.
2. Create a new folder (for e.g. MSAL as here) within your project directory and manually copy all the generated public headers into your project. Then, update the paths for these headers in the "Header Search Path" under the "Build Settings" of your project from your Build Folder.

![image](https://github.com/AzureAD/microsoft-authentication-library-for-objc/assets/12692041/99818ec6-3274-4aa1-8197-4fd6e3e1439b)

![image](https://github.com/AzureAD/microsoft-authentication-library-for-objc/assets/12692041/78d6b1f6-8961-4a73-84b5-2d404d9a6e17)

![image](https://github.com/AzureAD/microsoft-authentication-library-for-objc/assets/12692041/778cd670-ca36-4031-8871-38c8f1bb9954)

Moreover, could you please share the rationale behind consuming MSAL as a static library instead of utilizing Cocoapods or Swift Package Manager (SPM)? I strongly recommend using MSAL through Cocoapods or SPM for better integration and maintenance.

**Comment by rajenshar** [comment]
@swasti29 Thanks for the reply. In fact for my actual project I had copied only static libs generated (which I had compiled separately). took two libs and also copied header files from public folder in an include folder created and then used those headers and used libs linked in my build phase. Just to share with you I did a sample like this (because eventually project builds libs and I did use that as dependency in project). 


Nevertheless, the rationale behind wanting this static lib was that I had a basic NSApllication which calls a C++ library. And within that library I wanted to use MSAL calls (which can be called from C++ code). So I had to write C wrapper calls and from inside I wanted to call MSAL objective c code MSAL calls. And simplest way for me was to compile the code, build MSAL lib and write a wrapper apis like aquireTokenSilently etc in .m file and expose that in C++ code to be called by app at higher level.

Also as I said last time in my earlier comment

"By the way just to test, I commented the call to fillWithWebViewParameters and setAccountIdentifierFromMSALAccount in MSALPublicClientApplication and linked the library to my app and ran, I can see system browser invoked and showing the logged in account etc and flow goes through".

So it would be great if these libs were compiled and could be used to be consumed in C++ code (there is no C++ library for MSAL).

**Comment by rajenshar** [comment]
@swasti29  I am also attaching the screenshots of header path and lib linked in my actual project. 
![Uploading HEaderFilePAth.png…]()

**Comment by rajenshar** [comment]
![LibraryLinked](https://github.com/AzureAD/microsoft-authentication-library-for-objc/assets/76589203/bd1d3f61-abed-4c7a-a6eb-5518fdf091cf)

**Comment by rajenshar** [comment]
@swasti29 , I did download MSAL framework release version 1.2.20 and directly used it as framework linked to my project and it seems to be working fine. Thank you for all your support. Please feel free to close the ticket.

**Comment by kaisong1990** [comment]
@rajenshar Thanks for confirming, closing for now. Feel free to reopen

**Comment by kaisong1990** [comment]
@rajenshar Thanks for comfirning, closing for now. Feel free to reopen
