### ISSUE TITLE
Request to provide Privacy Manifest file for MSAL SDK

### ISSUE THREAD

**Issue by Shwethamugeraya** [AzureAD/microsoft-authentication-library-for-objc#1913]
We are consuming the MSAL SDK in our App. As mentioned in the WWDC23 video, also it is explained in [Privacy manifest files | Apple Developer Documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files), if we are using any third-party library, then SDK should contain a Privacy Manifest file. But currently, for MSAL SDK, the file is missing. So can anyone please add the Privacy Manifest file for the repo ?

**Comment by jasoncoolmax** [comment]
AFAIK, MSAL library, as an open-source library, won't collect privacy data itself. You can declare the PrivacyManifest at the app level as eventually all PrivacyManifest will be gathered together to generate a final one. But not that MSAL library does provide APIs to log or output telemetry. If your app is using those MSAL APIs, you probably will need to declare it at your app level.
