### ISSUE TITLE
Regarding Account Deactivate or Delete functionality

### ISSUE THREAD

**Issue by nemesisat** [AzureAD/microsoft-authentication-library-for-objc#1953]
Hi,

Want to know if we can deactivate the customer accounts? Apple policy states this is required. we are using Microsoft Commerce and in our IOS app, this is the feature we want to add.

**Comment by mipetriu** [comment]
Hi @nemesisat, MSAL does not handle new account creation or deletion from within the library. Such functions may occur from within the webview when the user is directed to sign in. Are you working with Entra ID, MSA, or B2C accounts?

**Comment by jasoncoolmax** [comment]
Close it for now due to inactivity. Feel free to reopen it when the required info is provided.
