### ISSUE TITLE
CocoaPods could not find compatible versions for pod "MSAL"

### ISSUE THREAD

**Issue by keerthikaitmit** [AzureAD/microsoft-authentication-library-for-objc#1954]
% arch -x86_64 pod install
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "MSAL":
  In snapshot (Podfile.lock):
    MSAL (= 1.2.5)

  In Podfile:
    MSAL (~> 1.2.5)

None of your spec sources contain a spec satisfying the dependencies: `MSAL (~> 1.2.5), MSAL (= 1.2.5)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

[!] Automatically assigning platform `iOS` with version `13.0` on target `TkConnect` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

 % pod repo update
pod update
Updating spec repo `trunk`

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod repo update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.11.2
        Ruby : ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]
    RubyGems : 3.0.3.1
        Host : macOS 12.6 (21G115)
       Xcode : 14.2 (14C18)
         Git : git version 2.37.1 (Apple Git-137.1)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0

**Comment by keerthikaitmit** [comment]
sudo gem install cocoapods
Password:
Fetching cocoapods-1.14.3.gem
Fetching cocoapods-core-1.14.3.gem
Fetching xcodeproj-1.23.0.gem
Fetching cocoapods-downloader-2.1.gem
Successfully installed xcodeproj-1.23.0
Successfully installed cocoapods-downloader-2.1
Successfully installed cocoapods-core-1.14.3
Successfully installed cocoapods-1.14.3
Parsing documentation for xcodeproj-1.23.0
Installing ri documentation for xcodeproj-1.23.0
Parsing documentation for cocoapods-downloader-2.1
Installing ri documentation for cocoapods-downloader-2.1
Parsing documentation for cocoapods-core-1.14.3
Installing ri documentation for cocoapods-core-1.14.3
Parsing documentation for cocoapods-1.14.3
Installing ri documentation for cocoapods-1.14.3
Done installing documentation for xcodeproj, cocoapods-downloader, cocoapods-core, cocoapods after 2 seconds
4 gems installed
pranesh@Tranes-MacBook-Pro tracking-TkConnect-ios % arch -x86_64 pod install  
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "MSAL":
  In snapshot (Podfile.lock):
    MSAL (= 1.2.5)

  In Podfile:
    MSAL

None of your spec sources contain a spec satisfying the dependencies: `MSAL, MSAL (= 1.2.5)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

[!] Automatically assigning platform `iOS` with version `13.0` on target `TkConnect` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
pranesh@Tranes-MacBook-Pro tracking-TkConnect-ios % pod setup
Setup completed
pranesh@Tranes-MacBook-Pro tracking-TkConnect-ios % pod --version           
1.14.3
pranesh@Tranes-MacBook-Pro tracking-TkConnect-ios % arch -x86_64 pod install
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "MSAL":
  In snapshot (Podfile.lock):
    MSAL (= 1.2.5)

  In Podfile:
    MSAL

None of your spec sources contain a spec satisfying the dependencies: `MSAL, MSAL (= 1.2.5)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

[!] Automatically assigning platform `iOS` with version `13.0` on target `TkConnect` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
pranesh@Tranes-MacBook-Pro tracking-TkConnect-ios %

**Comment by mipetriu** [comment]
Hello @keerthikaitmit, I'm having a bit of trouble following your post, apologies. Were you able to run `pod repo update`? Similarly to your pod install call, you may need to run `arch -x86_64 pod install --repo-update` on the M1 Mac.

**Comment by jasoncoolmax** [comment]
Close it for now due to inactivity. Feel free to reopen it when the required info is provided.
