### ISSUE TITLE
unable to edit 2FA settings for B2C user

### ISSUE THREAD

**Issue by jacobbullock** [AzureAD/microsoft-authentication-library-for-objc#1959]
I am trying to integrate a new policy for editing a user's 2FA setting. When I first integrated the new policies in the environment, during the call to `acquireToken` for login I was prompted if I wanted to turn on 2FA.  I selected no and finished login and got my user token.  When it try to load the policy for editing the 2FA setting I get the following error:

```
Printing description of nsError:
Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=AADB2C99002:+This+user+does+not+exist+and+profile+'AAD-UserReadUsingEmailAddress'+requires+the+user+to+have+already+been+created.
Correlation+ID:+6c820ec0-b60c-416d-b854-2030deeda173
Timestamp:+2024-01-04+21:41:51Z
, MSALOAuthErrorKey=server_error, MSALCorrelationIDKey=DE1BA36B-089D-47A8-A19A-3D9062B1C315, MSALInternalErrorCodeKey=-50006}
```

I am trying to use the `acquireToken` call the same way as I have in the past for a request to modify a user's profile settings like name and phone number.  Is there any specific that needs to be done to make this work.  Supposedly this policy works fine for the web version of the b2c integration, but for mobile iOS, Im stuck with this error.

**Comment by antonioalwan** [comment]
Hi @jacobbullock, Please take a look at documentation here: [Configure session behavior in Azure Active Directory B2C](https://learn.microsoft.com/en-us/azure/active-directory-b2c/session-behavior?pivots=b2c-user-flow).  However, if this still an issue would you mind sharing MSAL logs.

**Comment by jacobbullock** [comment]
it turns out our problem was related to the loginHint not being passed in.  things seem to be working since we implemented that.
