### ISSUE TITLE
[iOS] MSAL withBroker (authenticator)  error- The operation couldn’t be completed. (MSALErrorDomain error -50000.)

### ISSUE THREAD

**Issue by rahulsak** [AzureAD/microsoft-authentication-library-for-objc#1982]
Using MSAL sdk in iOS iPad app to complete the authentication. Trying to authenticate using broker app (authenticator) to complete the authentication. 
Following this documentation [https://learn.microsoft.com/en-us/entra/identity-platform/migrate-objc-adal-msal#broker-support](url) to configure redirect url on [Microsoft Entra admin center](https://entra.microsoft.com/?feature.broker=true#view/Microsoft_AAD_RegisteredApps/ApplicationsListBlade) and the plist configurations 

When initiating login flow, new popup is getting launch to select an account from list. When selecting the account, popup is getting dismiss. On console, getting below error. 

_The operation couldn’t be completed. (MSALErrorDomain error -50000.)
ASAuthorizationController credential request failed with error: Error Domain=com.apple.AuthenticationServices.AuthorizationError Code=-6000 "(null)" UserInfo={NSUnderlyingError=0x2813a8450 {Error Domain=MSALErrorDomain Code=-50000 "(null)"}}_

If I try to executing the flow with `MSALGlobalConfig.brokerAvailability = MSALBrokeredAvailability.none`, able to authenticate successfully and getting access token 

I am trying to get tokens interactively [https://github.com/AzureAD/microsoft-authentication-library-for-objc?tab=readme-ov-file#acquiring-your-first-token-interactively](url)

**Comment by hieunguyenmsft** [comment]
Can you repro and share with us the Authenticator IncidentID. Please follow [this](https://learn.microsoft.com/en-us/troubleshoot/azure/active-directory/send-microsoft-authenticator-logs) on how to get Authenticator logs.
It's also very helpful if you can collect MSAL logs and share with us the timestamp + correlationId when it happened. Follow this guide to collect MSAL logs:
https://learn.microsoft.com/en-us/entra/identity-platform/msal-logging-ios?tabs=objc

**Comment by hieunguyenmsft** [comment]
Hi @rahulsak , I checked the logs and see this error:
`openid,
    profile,
    "offline_access"
)} are reserved scopes and may not be specified in the acquire token call.}.`
Please update the request scope and if error still persists, feel free to reopen this.
Thank you.
