### ISSUE TITLE
OBO & AADSTS50076

### ISSUE THREAD

**Issue by macdrevx** [AzureAD/microsoft-authentication-library-for-objc#1989]
An iOS app I work on uses the OBO flow to obtain Microsoft Graph access tokens for both the client and for a middle-tier API service. We've noticed several errors recently when making the OBO token request:

```
AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000003-0000-0000-c000-000000000000'.
```

While I haven't yet reproduced the error, I *think* that this can happen in situations where there's a Conditional Access policy that is conditionally evaluated based on location (e.g. IP range). If the client is in a location where the CA policy does not apply, but the middle-tier server is in a location where the CA policy does apply, then the assertion used for OBO will not be guaranteed to demonstrate the relevant CA criteria, resulting in the error.

It's not clear to me how to handle this error. The middle-tier can't do an interactive token request, but even if the client does attempt another interactive token request, the CA policy wouldn't apply due to the client's location.

**Comment by macdrevx** [comment]
@bgavrilMS based on your helpful guidance on #1900, I suspect you might be able to provide some insight here.

**Comment by juan-arias** [comment]
Hi @macdrevx, we recommend going through Azure support channels directly for this kind of questions.
