### ISSUE TITLE
Implementing Account Sync across devices via keychain?

### ISSUE THREAD

**Issue by timvonwerne** [AzureAD/microsoft-authentication-library-for-objc#1998]
Hello there,
I've been working on integrating MSAL into my iOS project, aiming to enable account synchronization between multiple devices via (iCloud) keychain. The desired outcome is for users to set up their OneDrive account on one device and have it automatically available on other devices without requiring them to sign in again. This functionality has been successfully implemented in apps like "Infuse", indicating its feasibility.

Despite investing several hours into implementing this feature, I've hit a roadblock and haven't been able to make further progress. The possible initialization methods of `MSALPublicClienApplication` all seem to depend on the account identifier which is of course not available on the other device?

If anyone has experience or insights into implementing account synchronization across devices via iCloud Keychain using MSAL, your input would be greatly appreciated.

Thanks in advance and best regards,
Tim

**Comment by ameyapat** [comment]
@timvonwerne Are you suggesting synching access tokens from the keychain from one device to another?

**Comment by timvonwerne** [comment]
@ameyapat Indeed. However, after considering the potential integration of other cloud providers in the near future, I've opted to utilize [AppAuth](https://github.com/openid/AppAuth-iOS) instead. This choice grants me greater control over managing access and refresh tokens, as well as the ability to handle the keychain aspect independently. Thanks anyways!
