### ISSUE TITLE
UIApplication.endBackgroundTask not being called

### ISSUE THREAD

**Issue by LeonidGrebeniuk** [AzureAD/microsoft-authentication-library-for-objc#2063]
Can reproduce using the official sample app with MSAL 1.3.0
To reproduce:
1. Sign in with Microsoft
2. Type email
3. Push Next button
4. Wait 30 seconds

```
Start webview authorization session with webview controller class MSIDSystemWebviewController: 
Unknown client: SampleAppiOS-Swift
Background Task 3 ("Interactive login"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.
```
![Screenshot 2024-02-27 at 2 32 46 PM](https://github.com/AzureAD/microsoft-authentication-library-for-objc/assets/157328347/ea902792-dfc3-400b-93c9-400fbdb86a89)

**Comment by Veena11** [comment]
@LeonidGrebeniuk ,

Is this a warning that you see or are you seeing any crash ? What is the behavior ?
Do you see the same behavior with previous release of MSAL:1.2.22 (https://github.com/AzureAD/microsoft-authentication-library-for-objc/releases/tag/1.2.22) 

We do have endBackgroundTaskCall here :
https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/blob/7036009938a547408a87cbf96982bb23d6a5293c/IdentityCore/src/webview/background/ios/MSIDBackgroundTaskManager.m#L106

**Comment by Veena11** [comment]
For the mentioned scenario, we do have the handling via expiration handler : https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/blob/7036009938a547408a87cbf96982bb23d6a5293c/IdentityCore/src/webview/background/ios/MSIDBackgroundTaskManager.m#L84 and through it the endBackgroundTaskCall is invoked

**Comment by kaisong1990** [comment]
Closing due to no active conversation
