### ISSUE TITLE
Cannot get MSAL's PrivacyManifests when using CocoaPods.

### ISSUE THREAD

**Issue by ika020202** [AzureAD/microsoft-authentication-library-for-objc#2074]
Hello

I am unable to get PrivacyManifests for MSAL using CocoaPods.
I think it is necessary to add PrivacyInfo.xcprivacy to the resource_bundles in the .podspec file.

For more information, please refer to the following threads and other library implementations.
ref: https://github.com/CocoaPods/CocoaPods/issues/10325

**Comment by Veena11** [comment]
@ika020202 Thank you for bringing this to our notice. Opened PR : https://github.com/AzureAD/microsoft-authentication-library-for-objc/pull/2075

**Comment by Veena11** [comment]
Yeah , unfortunately we missed the change in 1.3.1. Sorry about that. We plan to include it in the next release

**Comment by hatchedlabs-tomasz-frontczak** [comment]
@Veena11 when do you plan to make this release? This manifest is mandatory by Apple from May 1

**Comment by Veena11** [comment]
This is included in 1.3.2 release
