### ISSUE TITLE
AcquireTokenSilent should return interactionRequired if User object is empty during Preview

### ISSUE THREAD

**Issue by brandwe** [AzureAD/microsoft-authentication-library-for-objc#209]
Right now MSAL .Net returns interactionRequired if the User object is empty. This is to support the pattern where `AcquireTokenSilent()` should be the first method a developer calls in order to check if there is a user in the cache. 

There is a debate what we should do across all the MSAL libraries with `AcquireTokenSilent()` and the necessity to always pass a `User` object. However at this time we may want to match .Net so developers aren't confused during Preview

**Comment by unpluggedk** [comment]
As @brandwe suggests, MSAL .Net version throws MsalUiRequiredException.UserNullError.

We currently return MSALErrorInvalidParameter, but to be in sync, we can create MSALErrorNullUser error as a part of interaction required errors, i.e./ code number -421XX.

**Comment by oldalton** [comment]
Fixed: https://github.com/AzureAD/microsoft-authentication-library-for-objc/pull/697
