### ISSUE TITLE
With reference to [Bug] MSAL OAuth2 + EWS not working #1274

### ISSUE THREAD

**Issue by ahmedwasiullah** [AzureAD/microsoft-authentication-library-for-objc#2108]
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1274
I am facing the same above mentioned issue when I am trying to use a MSAL Generated Token Against a hotmail Account,in ews I am getting 403 Forbidden response code.I have gone through the above thread and haven't found the solution meanwhile the status is that of closed.

**Comment by swasti29** [comment]
@ahmedwasiullah Is the issue related to MSAL Obj C or MSAL .Net? 
Kindly eloborate the issue in detail.

**Comment by ahmedwasiullah** [comment]
I am using MSAL java SDK and EWS,  The Issue is simple when I am using MSAL generated token in EWS service to access the resources, it's throwing a 403 exception, while I have configurated the app in accordance with the documentation.(Note-when I am generating a token against Usual Office365 account its working fine. The Issue is only when I use a Hotmail Account.)

**Comment by swasti29** [comment]
It should be supported, but I would recommend posting the issue with MSAL Java here: [MSAL Java GitHub Issues](https://github.com/AzureAD/microsoft-authentication-library-for-java/issues) so that you can receive support with accurate implementation details.

**Comment by swasti29** [comment]
Also for your information, https://outlook.office365.com/EWS.AccessAsUser.All is the right scope to be used. However OAuth authentication for EWS is only available in Exchange Online as part of Microsoft 365. (https://learn.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-authenticate-an-ews-application-by-using-oauth) The scope is invalid for personal accounts since they're not supported by EWS.

**Comment by ahmedwasiullah** [comment]
I have been using the same scope, but I was trying to login my personal hotmail account.May be that is the reason that token is getting invaildated. I have gone through the whole documentation and haven't found a way out of the problem. Isn't there any way through which we can access a personal outlook account in ews without using third app password?

**Comment by swasti29** [comment]
As per the documentation personal account is no longer supported by EWS.
