### ISSUE TITLE
Privacy manifest missing NSPrivacyAccessedAPICategoryFileTimestamp

### ISSUE THREAD

**Issue by hatchedlabs-tomasz-frontczak** [AzureAD/microsoft-authentication-library-for-objc#2138]
After sending app to test flight I am getting email from Apple
```
Hello,

We noticed one or more issues with a recent submission for App Store review for the following app:

------------
Version -----
Build -------
Although submission for App Store review was successful, you may want to correct the following issues in your next submission for App Store review. Once you've corrected the issues, upload a new binary to App Store Connect.

ITMS-91053: Missing API declaration - Your app’s code in the “grocery-ios” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryFileTimestamp. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: [https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api](https://urldefense.com/v3/__https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api__;!!MiZrGOEI0vA!bOS28k-agohhIjQcLzDb8YD6AIvQmaLTkCCEh7hTg3puGpnNxRjLVpTf_E2n-bJ9_kBokokRMaD68zfLMOiZPTvlyp72M_w$).

Apple Developer Relations
```

I started checking libraries included in my project and after adding 

```
        <dict>
            <key>NSPrivacyAccessedAPIType</key>
            <string>NSPrivacyAccessedAPICategoryFileTimestamp</string>
            <key>NSPrivacyAccessedAPITypeReasons</key>
            <array>
                <string>C617.1</string>
            </array>
        </dict>
```
to MSAL manifest warning is gone.
I think you have to validate your manifest and prepare new release.

**Comment by hatchedlabs-tomasz-frontczak** [comment]
@juan-arias @oldalton @Veena11 tagging people who were involved in adding manifest

**Comment by oldalton** [comment]
@hatchedlabs-tomasz-frontczak, thanks for letting us know. I took a look at the list of APIs for this key described here: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278393. I don't see MSAL using any of the listed APIs. Did Apple provide the exact API that is missing? Could it be that you have another library using this API and Apple doesn't correctly enforce those checks for the correct library?

@juan-arias, will ask your help with this follow-up if any action is needed from our side.

**Comment by hatchedlabs-tomasz-frontczak** [comment]
May be related to your dependencies not MSAL itself

**Comment by oldalton** [comment]
@hatchedlabs-tomasz-frontczak, MSAL doesn't include any dependencies. Could you please take another look at other libraries in your codebase?

**Comment by hatchedlabs-tomasz-frontczak** [comment]
Now warning is gone without any modification on my side. I think it was apple validation hiccup. Thx for checking.
