### ISSUE TITLE
Brokered Authentication for Personal Accounts

### ISSUE THREAD

**Issue by jeff-dialpad** [AzureAD/microsoft-authentication-library-for-objc#2142]
In our iOS app we are configuring `MSALGlobalConfig.brokerAvailability = .auto`, as we are required to support Microsoft Authenticator brokered login.

This works for "corporate" accounts (those that show up with the header "Microsoft Entra ID" in the Authenticator app). But when a "personal" account (one which shows up with the header "Microsoft" in the Authenticator app) who could previously log in through the MSAL web interface (ie non-brokered auth) attempts an interactive login, whether they can successfully do so depends on whether they have the Authenticator app installed. 

In the case where the Authenticator app is not installed, the user can properly get the token from the web based interface. But if the user has installed the Authenticator app then when the user starts an interactive login, they are brought to the Authenticator app to choose an Identity. However it seems that the personal account is not present in the list of identities to choose from in the Authenticator app. Only any Microsoft Entra ID accounts are presented in my testing.

**Is it possible for a personal account to get a token when they have the authenticator app installed?**

**Comment by ameyapat** [comment]
Hi, @jeff-dialpad you can add personal account in Authenticator using the '+' button in the Authenticator app located at top-right in the accounts list view : https://support.microsoft.com/en-us/account-billing/add-personal-microsoft-accounts-to-the-microsoft-authenticator-app-92544b53-7706-4581-a142-30344a2a2a57
