### ISSUE TITLE
MSAL doesnt suports os less than 14

### ISSUE THREAD

**Issue by amanmorgan1409** [AzureAD/microsoft-authentication-library-for-objc#2144]
i have updated the msal version to from 1.2.4 to latest 1.3.2 due to xcode 15 compatibility issue but it doesnt supports os lower than 14 where as my deployment target is 12.0. how can i run my app on xcode 15 for lower os like 12 13.

**Comment by fidelianawar** [comment]
Hi @amanmorgan1409, thanks for reaching out.

MSAL dropped the minimum support for macOS 12, so unfortunately there is no way to integrate 2 different versions of MSAL into your app. You will need to do one of the following:
 
- Update your app's minimum version support macOS 12+
- Use a maximum capable MSAL version which still supports macOS 12 (can find in MSAL release history)

Let me know if this helps.
