### ISSUE TITLE
Single Sign On - MAM

### ISSUE THREAD

**Issue by ebainto** [AzureAD/microsoft-authentication-library-for-objc#218]
Im trying to test iOS MSAL sample application for single sign on without inputing your Enterprise Account (Active directory) my iOS device is registered to MAM. 

Single Sign-0n works fine after your initially login. Since my iOS device is registered to MAM is there a way to achieve SSO during initial load without providing your credentials?

**Comment by ebainto** [comment]
Correction, my iOS device is registered to MDM.

**Comment by ebainto** [comment]
@RPangrle do you have any idea on this scenario? thank you

**Comment by RPangrle** [comment]
This can not work because SSO provided in MSAL is done through cookie sharing in SFSafariViewController (which is also going away in iOS 11...), MAM enrollment is done through in-app webview, and even if it was switched to SafariViewController the SSO support is going away in iOS 11.

**Comment by ebainto** [comment]
Thanks @RPangrle. Also, Do you have plans in the future to support Brokered Authentication? using Azure Authenticator app that can support MDM and MAM?

**Comment by ebainto** [comment]
@RPangrle do you know when is the potential GA for MSAL? thank you

**Comment by oldalton** [comment]
This should be resolved :)
