### ISSUE TITLE
ClientId should not be removed from scopes in Active Directory B2C

### ISSUE THREAD

**Issue by MrAsterisco** [AzureAD/microsoft-authentication-library-for-objc#220]
I have spent the last few weeks attempting to make this library work with Active Directory B2C. No matter what I tried, there was no way to make it authenticate successfully: I kept getting an error that told me that the _accessToken_ was missing from the response.

After some debugging, I have identified the core issue to this function, in MSALBaseRequest:

```swift
- (MSALScopes *)requestScopes:(MSALScopes *)extraScopes
{
    NSMutableOrderedSet *requestScopes = [_parameters.scopes mutableCopy];
    if (extraScopes)
    {
        [requestScopes unionOrderedSet:extraScopes];
    }
    [requestScopes unionOrderedSet:s_reservedScopes];
    [requestScopes removeObject:_parameters.clientId]; // <-- Why?
    return requestScopes;
}
```

This function removes the ClientID from the request scopes, making impossible to use it with Active Directory B2C. As clearly stated in the Azure Active Directory B2C documentation:

> The convention for requesting a token to yourself is to use your app's client ID as the scope

_I had previously made a pull request on this, but then I realized that the changes that I needed were too much different, hence I decided to fork this repository and keep my version. If you want to take a look at the things that I've modified, feel free to visit my repo: the latest version hosted there doesn't have this issue._

**Comment by 7sharp9** [comment]
I think the client scope was removed from the v2 api calls, which is annoying if you created B2C while it was version1.

**Comment by MrAsterisco** [comment]
@7sharp9 I'm sorry, I did not understand your answer. Can you please elaborate a bit more?

For further reference, the link to the documentation I cited in the previous issue is here: https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-oidc#get-a-token

**Comment by oldalton** [comment]
Should be fixed in the latest MSAL.
