### ISSUE TITLE
MSALErrorDescriptionKey  AADSTS70000

### ISSUE THREAD

**Issue by mojtabacazi** [AzureAD/microsoft-authentication-library-for-objc#221]
I'm getting the following error trying to authenticate using AD B2C. 

```
Error Domain=MSALErrorDomain Code=-42100 "(null)" UserInfo={
MSALErrorDescriptionKey=AADSTS70000: Transmission data parser failure: Authorization Code is malformed or invalid.
Trace ID: ########
Correlation ID: ########
Timestamp: 2017-08-25 05:47:27Z, MSALOAuthErrorKey=invalid_grant
}
```

Sample Code

    NSString *clientID = @"########";  // App Client ID from Azure AD B2C Portal
    NSString *authority = @"https://login.microsoftonline.com/########";
    NSDictionary *params = @{@"p": @"########"}; // Policy from Azure Portal
    NSArray *scopes = @[clientID];
    NSError *error = nil;
    
	MSALPublicClientApplication *application = [[MSALPublicClientApplication alloc] initWithClientId:clientID authority:authority error:&error];
    [application acquireTokenForScopes:scopes loginHint:nil uiBehavior:MSALUIBehaviorDefault extraQueryParameters:params completionBlock:^(MSALResult *result, NSError *error) {
        if (error) {
            NSLog(@"%@", error);
        }
    }];

**Comment by RPangrle** [comment]
It is possible that you're asking for too many scopes in your tokens, which is causing the authorization code to be too large
