### ISSUE TITLE
Interactive auth fails with error code 3: com.apple.AuthenticationServices.WebAuthenticationSession

### ISSUE THREAD

**Issue by ShmuelCammebys** [AzureAD/microsoft-authentication-library-for-objc#2221]
It is a rare bug, but it happens often enough to cause an issue. Unsure what the solution is.
```log
TID=1607680 MSAL 1.4.0 iOS 17.5.1 [2024-06-25 15:27:34 - 63CD1BFD-118A-4390-81A1-D702B8E18F4B] [MSAL] Interactive flow finished. Result (null), error: 3 error domain: com.apple.AuthenticationServices.WebAuthenticationSession
```

**Comment by hieunguyenmsft** [comment]
Seems like the code 3 is 
 `ASWebAuthenticationSessionErrorCodePresentationContextInvalid API_AVAILABLE(ios(13.0), macos(10.15)) = 3,` and from Apple, I don't think MSAL able to help here. It would be best if you can provide a feedback item to them.
Thanks
