### ISSUE TITLE
Customised domain with MSAL

### ISSUE THREAD

**Issue by kirthika** [AzureAD/microsoft-authentication-library-for-objc#225]
How can I add customised domain rather than https://login.microsoftonline.com ?

**Comment by oldalton** [comment]
When you're initializing the MSALPublicClientApplication you can provide your custom authority, e.g:

`let application = try MSALPublicClientApplication.init(clientId: kClientID, authority: **kAuthority**)`

**Comment by oldalton** [comment]
I'll close this issue, feel free to reopen it if you feel like your issue wasn't resolved.

**Comment by RK905** [comment]
when i add custom domain the safariview does not open

**Comment by oldalton** [comment]
Please make sure you're providing a valid authority URL and see what error message you get back from the MSAL.
