### ISSUE TITLE
Error while calling acquireTokenSilentForScopes

### ISSUE THREAD

**Issue by kirthika** [AzureAD/microsoft-authentication-library-for-objc#226]
I get the following error when I call acquireTokenSilentForScopes : 
Error Domain=MSALErrorDomain Code=-42100 "(null)" UserInfo={MSALErrorDescriptionKey=AADB2C90129: The provided grant has been revoked. Please reauthenticate and try again.
Correlation ID: 1cee1076-0805-4786-a3fc-88df64462f5a
Timestamp: 2017-10-11 13:42:52Z
, MSALOAuthErrorKey=invalid_grant}

**Comment by oldalton** [comment]
It normally means that your refresh token is no longer valid and we couldn't get an access token for it. At this point you would need to call acquireTokenForScopes to get a fresh refresh token.

**Comment by oldalton** [comment]
I'll close this issue, feel free to reopen it if you feel like your issue wasn't resolved.
