### ISSUE TITLE
-42402 error when opening a deep link using customised domain with MSAL

### ISSUE THREAD

**Issue by kirthika** [AzureAD/microsoft-authentication-library-for-objc#227]
When I try to open a deep link using customised domain with MSAL, on first click on deep link it works fine but on the following clicks it gives me the following error : 
**Error Domain=MSALErrorDomain Code=-42402 "(null)" UserInfo={MSALErrorDescriptionKey=Only one interactive session is allowed at a time.}**

**Comment by kirthika** [comment]
Used cancelCurrentWebAuthSession method and it helped. Thanks !

**Comment by RK905** [comment]
wow did you get msal customized domain to work?
When i do custom the safari view does not open

**Comment by kirthika** [comment]
@RK905 Yeah ! just set **validateAuthority** to **false**, it works.

**Comment by sunny131984** [comment]
I am facing same issue in mobile app. when i try to click first time on forgot password link it works fine but on second time whole page links got disable. Please suggest what to do to clear all things.

**Comment by Shayila** [comment]
> I am facing same issue in mobile app. when i try to click first time on forgot password link it works fine but on second time whole page links got disable. Please suggest what to do to clear all things.

I'm also getting into the same scenario trap.
Even after setting the **validateAuthority** to **False** and also including `MSALPublicClientApplication.cancelCurrentWebAuthSession;` 
I'm facing the below warning or error situations.

Using ` [MSALPublicClientApplication handleMSALResponse:url];` 
 i encountered the following error:
**Error Domain=MSALErrorDomain Code=-42402 "(null)" UserInfo={MSALErrorDescriptionKey=Only one interactive session is allowed at a time., MSALCorrelationIDKey=0A8F2159-3E69-4F67-AAAA-71AE2258112F}**

Using ` [MSALPublicClientApplication handleMSALResponse:url sourceApplication:UIApplicationOpenURLOptionsSourceApplicationKey];` handler i came up with the following warning:
**Warning: Attempt to present <SFSafariViewController: 0x166d5460> on <SFSafariViewController: 0x165cc4a0> whose view is not in the window hierarchy!**

Please provide solution for these issues.
