### ISSUE TITLE
MSAL.xcframework Is Signed By Microsoft Corporation

### ISSUE THREAD

**Issue by jukemoon** [AzureAD/microsoft-authentication-library-for-objc#2273]
Hello,

I'm attempting to automate uploading my IPA to TestFlight. However, I'm running into trouble because `MSAL.xcframework` is signed by Microsoft Corporation. Specifically, 

**Team Name:** Microsoft Corporation
**Team ID:** UBF8T346G9
**Kind:** Apple Developer Program

Typically, `xcframework`s are unsigned. For awareness, I'm obtaining this artifact by downloading `MSAL.zip` under [Release `1.4.0`](https://github.com/AzureAD/microsoft-authentication-library-for-objc/releases/tag/1.4.0). Could you please ship this `xcframework` without it being signed?

Thank you in advance!

**Comment by Veena11** [comment]
@jukemoon , could you try resigning the framework after you embed it ? Xcode should allow you to configure signing settings for any framework dependencies that you have in your app.

**Comment by jukemoon** [comment]
> @jukemoon , could you try resigning the framework after you embed it ? Xcode should allow you to configure signing settings for any framework dependencies that you have in your app.

@Veena11, let me conduct some research and get back to you. I hope to have information to share out next week.

**Comment by jukemoon** [comment]
> > @jukemoon , could you try resigning the framework after you embed it ? Xcode should allow you to configure signing settings for any framework dependencies that you have in your app.
> 
> @Veena11, let me conduct some research and get back to you. I hope to have information to share out next week.

Hello, @Veena11. Thank you for your patience. I'll run with the information to manually remove the signing of `MSAL.xcframework`. I appreciate the help.  If any troubles arise or additional questions, I'll reopen the issue.
