### ISSUE TITLE
Can the safari toolbar be hidden?

### ISSUE THREAD

**Issue by kirthika** [AzureAD/microsoft-authentication-library-for-objc#228]
Can the safari toolbar be hidden on SFSafariViewController that is being used to open azure pages?

**Comment by oddgoo** [comment]
Would this violate this security recommendation?

> Encouraging users to enter credentials in an embedded web-view
   without the usual address bar and other identity features that
   browsers have makes it impossible for the user to know if they are
   signing in to the legitimate site, and even when they are, it trains
   them that it's OK to enter credentials without validating the site
   first.

from section 5.1 here:

https://tools.ietf.org/html/draft-wdenniss-oauth-native-apps-02#section-5.1

**Comment by RPangrle** [comment]
SFSafariViewController is entirely controlled by the OS, and thus can not be customized for security reasons.
