### ISSUE TITLE
MSAL for Share Extension App

### ISSUE THREAD

**Issue by bao-nguyen1** [AzureAD/microsoft-authentication-library-for-objc#2286]
Hi,

The main app integrates with MSAL libraries and supports the Share Extension. However, I am not sure if these MSAL libraries can work with the Share Extension. 
How can I integrate MSAL with the Share Extension like how to config and get the policy from share extension app?

**Comment by mipetriu** [comment]
Hello @bao-nguyen1, could you share a little more about how MSAL would be used in the Share Extension? Also, are you running into build or runtime issues when taking a dependency on MSAL?

**Comment by bao-nguyen1** [comment]
Hi @mipetriu 
My app uses the share extension to check whether the main app has granted access, and then accesses the shared database from the main application. However, when initializing the share extension, it crashes.
```
2024-09-09 16:00:36.833447+0700 AppShareExtension[6696:259421] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSDictionaryM setObject:forKey:]: object cannot be nil (key: A02995F1-A2B3-4B9D-9085-E25B08223AC4)'
*** First throw call stack:
(0x1bbe04cb4 0x1b4ea03d0 0x1bbfaaf84 0x1bbfb6664 0x1bbdfd278 0x1c945f008 0x1c32ca320 0x1c32cbeac 0x1c32d3534 0x1c32d40a4 0x1c32decdc 0x21bc35ddc 0x21bc35b7c)
libc++abi: terminating due to uncaught exception of type NSException
```
I am using a real device: 
iPhone 14 Plus running iOS 16.6, 
with MSAL version 1.4.0 installed via CocoaPods

**Comment by bao-nguyen1** [comment]
Hi @mipetriu 
I want to retrieve the MDM policy from the Share Extension application. Could you provide me with some instructions?

**Comment by ameyapat** [comment]
@bao-nguyen1 Can you elaborate on what you are trying to achieve? That is why does the share extension need to retrieve or handle MDM policies? Is the crash happening in MSAL? The crash report snippet is not symbolicated
