### ISSUE TITLE
MSAL Support for Mac Catalyst

### ISSUE THREAD

**Issue by FarooqMS** [AzureAD/microsoft-authentication-library-for-objc#2287]
Hello,

When we are trying to build mac catalyst app, MSAL has some redefinition compilation errors in class MSIDBrokerKeyProvider.  We are consuming 1.4.0 version.  

Appreciate if you could have build ready to support mac catalyst.

**Comment by mipetriu** [comment]
Hello, there is currently no plan for MSAL to support Mac Catalyst. I will close this issue as the main discussion around this topic is [here](https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/649).
