### ISSUE TITLE
 MSAL Webview deleted saved password 

### ISSUE THREAD

**Issue by eminemArun** [AzureAD/microsoft-authentication-library-for-objc#2308]
is there any way to remove or delete the saved password from MSAL Webview at the time of login?

**Comment by juan-arias** [comment]
Hi @eminemArun, saved passwords is a functionality of the browser or the OS. Can you share a sample screenshot of what you are experiencing?

**Comment by eminemArun** [comment]
Hi @juan-arias 

Is it possible to disable and hide **"Sign in to miscrosoftonline.com with your saved password"** ?
Please, refer to screenshot for the same.



![Simulator Screenshot - iPhone SE (3rd generation) - 2024-09-06 at 08 30 13](https://github.com/user-attachments/assets/a59fb7cd-2536-47b2-a3dc-86c28055fbc0)

**Comment by juan-arias** [comment]
@eminemArun no, there is no way to disable it, and in my opinion I think it's a good feature that avoids password reuse across apps/sites. The saved password can be found using these instructions: https://support.apple.com/en-gb/104955 and then it can be deleted from your device.
