### ISSUE TITLE
Need a way to have a background service continue to query on user's behalf once the user authenticates on client

### ISSUE THREAD

**Issue by chaitualuru** [AzureAD/microsoft-authentication-library-for-objc#2325]
Currently, I do not see a way to:
1. Get a refresh token from auth on the ios client
2. Setup a shared cache with my server so that I can continue to query on behalf of the client

This seems to be possible on the .NET library
See, [advanced token cache](https://github.com/Azure-Samples/ms-identity-dotnet-advanced-token-cache)
And, [server side auth issue](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3485).

How do I accomplish the same on ios? My app lets users sign in with their Outlook account and helps them manager their calendar. But calendar management is automated and does not need the user to interact with the app once they authenticate.

**Comment by chaitualuru** [comment]
Best SO answer I found on this topic - https://stackoverflow.com/questions/59184252/how-to-implement-on-behalf-of-obo-flow-for-personal-microsoft-accounts-msa

Any help would be much appreacited.

**Comment by Be-Maps** [comment]
There is a problem with getting token from background. I get the 1st silent refreshed token in gui, after 40 min I request a refresh of the token in background - Somehow the second valid access token stops working after 1h from start (20min from its creation) of the app when requested from background. I think this is a defect or I have the Azure permissions wrong (trying to find our what is wrong for 2 weeks now).
MSAL is managing refresh token automatically (you do not have access to it, and you do not need). But somehow maybe is using wrong scopes or some wrong settings when used from background as the access to email is lost after 1h (in background, when second token should be still valid for 40min). NOTE: I have offline_access permission, so it should work.

To get you started here are 2 tutorials for GUI token management with MSAL:
https://cocoapods.org/pods/MSAL
https://learn.microsoft.com/de-de/graph/tutorials/ios-swift?tutorial-step=3

I do it in the following way from background:
{
            logd("OAuthTokenRequestReceiver_onReceive - ..... OK ..... received data")
            // refresh token
            Task {
                try await Task.sleep(nanoseconds: UInt64(1) * 1000000)
                if ((OAuthDetails.getExpiery().getTimeSeconds() - Date().getTimeSeconds()) > (20*60)) {
                    Log.d(AppDelegate.sTAG,"OAuthTokenRequestReceiver_onReceive: No need to get token")
                    return
                } else {
                    OAuthDetails.setExpiery(Date().add(minutes: 22))
                    Log.d(AppDelegate.sTAG,"OAuthTokenRequestReceiver_onReceive: Getting token")

                    do {
                        let authority = try MSALAADAuthority(url: URL(string: App.kAuthority)!)
                        let msalConfiguration = MSALPublicClientApplicationConfig(clientId: App.kClientID, redirectUri: nil, authority: authority)
                        //msalConfiguration.
                        
                        if (OAuthDetails.getApplicationContext() == nil) {
                            OAuthDetails.setApplicationContext( try MSALPublicClientApplication(configuration: msalConfiguration))
                            Log.d(AppDelegate.sTAG,  "acquireTokenSilently: New MSALPublicClientApplication CREATED")
                        }
                        let msalApplicationContext = OAuthDetails.getApplicationContext()!
                        //let msalParameters = MSALParameters()
                        //msalParameters.

                        let config:MailConfig = MailConfig(); config.SynchConfigFromDB();
                        
                        let account = try msalApplicationContext.allAccounts().first!
                        //let account = try msalApplicationContext.account(forUsername: config.getUserName())
                        //let account = try msalApplicationContext.account(forIdentifier: App.getMSAccountIdentifier())
                        //account.
                        let silentParameters = MSALSilentTokenParameters(scopes: App.kScopes, account: account)
                        //silentParameters.allowUsingLocalCachedRtWhenSsoExtFailed = false
                        silentParameters.scopes = App.kScopes
                        silentParameters.authority = authority
                        silentParameters.forceRefresh = true
                        
                        
                        let msalResponse = try await msalApplicationContext.acquireTokenSilent(with: silentParameters)
                        
                        // save Token details
                        OAuthDetails.setToken(msalResponse.accessToken)
                        OAuthDetails.setExpiery(msalResponse.expiresOn!)

                        Log.d(AppDelegate.sTAG, "acquireTokenSilently: Access Token is: \(OAuthDetails.getToken())")
                        Log.d(AppDelegate.sTAG, "acquireTokenSilently: Username is            : \(msalResponse.account.username!)")
                        Log.d(AppDelegate.sTAG, "acquireTokenSilently: Access token expiery is: \(Date.asString(OAuthDetails.getExpiery()))")
                        Log.d(AppDelegate.sTAG, "acquireTokenSilently: Account Identifier is  : \(msalResponse.account.identifier!)")
                        App.saveMSAccountIdentifier(msalResponse.account.identifier!)
                        
                    } catch {
                        Log.d(AppDelegate.sTAG,  "Unable to get new Microsoft OAuth Silent Token \(error)")
                    }
                }
            }
        }

**Comment by Be-Maps** [comment]
PS. I took MSAL Log when I get token from GUI and background. And both logs look the same. I think the problem might be with offline_access , or how MSAL refreshes token. I am using private user scopes:
                            "https://outlook.office.com/IMAP.AccessAsUser.All",
                            "https://outlook.office.com/SMTP.Send"
maybe MSAL is using *365 scopes for offline_access to get refresh token which is different realm - and maybe this makes it not working after 1h from app start (while I am having token valid still for 40min), but maybe to *354 realm, not to outlook.office.com realm.
... above is my hunch but I might be wrong. Also my permissions might need some special setup ... no idea.

**Comment by ameyapat** [comment]
@chaitualuru Hi can you elaborate what you are trying to achieve with the refresh token? MSAL should use the refresh token whenever your access token is expired. Your service can keep using MSAL to get/refresh access tokens

**Comment by chaitualuru** [comment]
Hey @ameyapat! My app lets users sign in with their Outlook account and helps them manage their calendar. But calendar management is automated and does not need the user to interact with the app once they authenticate. 
Therefore, I need to be able to fetch the user's calendar events on the server side. But this is not possible without a refresh token. MSAL does indeed manage everything on the client side but that is not sufficient for this use case.
