### ISSUE TITLE
iOS 18 blank sign in screen

### ISSUE THREAD

**Issue by lukaszciastko-spica** [AzureAD/microsoft-authentication-library-for-objc#2349]
Trying to sign in on iOS 18 in the Simulator (using the browser view), all I can see is a blank screen. Tested a few versions of MSAL up to 1.5.1. This works on a real device with the Authenticator app installed (haven't tried without it), but it's an issue during development since we can't sign in into the app.

![Simulator Screenshot - iPhone 16 - 2024-09-25 at 19 43 48](https://github.com/user-attachments/assets/c2a6c675-d862-453b-a270-42c061d58752)

**Comment by Veena11** [comment]
Could you share the xcode version that you are using ? is it iOS18 beta simulator ?

**Comment by sabrahamsmartv** [comment]
Even i am getting the same error. A blank screen while loading simulators running with iOS 18.0. Where as it is working in all previous simulators less than iOS 18.  Xcode version is Version 16.0 (16A242d). Is there any solution or workaround for the same?

**Comment by Veena11** [comment]
Hi , I tested on xcode 16.1 beta 2 /xcode 16.0 and simulators 18 and 18.1 , but couldnt repro the issue

![image](https://github.com/user-attachments/assets/f943a8de-c765-499a-a187-48f01ad9359b)
![image](https://github.com/user-attachments/assets/d77d28b6-2f3e-4a40-802e-9736e1c82439)

**Comment by lukaszciastko-spica** [comment]
Thanks @sabrahamsmartv , this works, but I'm not sure this is a long-term solution. As far as I recall, MSALWebviewTypeWKWebView doesn't support passwords fill-in.

@Veena11, when I create a new app and try to reproduce it, it works perfectly fine. I don't think the issue is specifically with MSAL, because I see the same problem when trying to open any link now. But only in our existing app. I can't figure out exactly what's causing it.

**Comment by Veena11** [comment]
@lukaszciastko-spica , is this issue resolved for you now ? Can we close the ticket ?

**Comment by lukaszciastko-spica** [comment]
> @lukaszciastko-spica , is this issue resolved for you now ? Can we close the ticket ?

No, we still have the issue and no solution.

**Comment by vinaykumar0339** [comment]
@lukaszciastko-spica did you solve the issue?

**Comment by ameyapat** [comment]
This doesn't seem to be an MSAL issue and maybe an iOS issue. Please reach out to Apple via Dev Forums/Feedback. Closing this

**Comment by diwakar445** [comment]
Trying to sign in on iOS 18.2 in the Simulator (using the browser view), all I can see is a blank screen. and it's working fine on the real device.
