### ISSUE TITLE
MSAL sign out popup bug

### ISSUE THREAD

**Issue by ntharunnuance** [AzureAD/microsoft-authentication-library-for-objc#2411]
![Simulator Screenshot - IPhone SE - 2024-12-04 at 11 50 10](https://github.com/user-attachments/assets/2cc2cf4a-e5c9-447a-b1b5-3bbefe1deb43)

the code that I am using below..
```
        applicationContext.signout(with: account, signoutParameters: signoutParameters) { _, error in
            completion(error)
        }

```
I need to change either popup message to signOut instead of SignIn or remove pop all together

**Comment by ntharunnuance** [comment]
I am not sure if there is any API that I can use to remove popup or if that's not possible at least change popup message

**Comment by ameyapat** [comment]
@ntharunnuance That pop-up is generated by iOS and we do not have control over it. Basically, during signout we try to open webview to clear cookies from it, but iOS thinks it is a sign-in request. If you want to opt out of clearing cookies you can configure signOutFromBrowser to NO in https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALSignoutParameters.html
