### ISSUE TITLE
How to use Intune iOS SDK with MSAL, instead of ADAL?

### ISSUE THREAD

**Issue by yaroslavbabenko** [AzureAD/microsoft-authentication-library-for-objc#245]
How to use Intune SDK with MSAL, instead of ADAL? In the official documentation only examples of ADAL https://docs.microsoft.com/en-us/intune/app-sdk-ios, but I need to use Intune with new auth library MSAL. Is it possible, any sample or tutorial?

**Comment by oldalton** [comment]
Unfortunately, it's not yet supported, because Intune SDK itself would need to do updates.

**Comment by yaroslavbabenko** [comment]
Ok. Thanks for response.

**Comment by OxyFlax** [comment]
Is it still true or is there any changes on this point?

**Comment by danieldobalian** [comment]
This is still the case, but it's something we're closely tracking and evaluating soon. 

My email is on my Github profile if you want to reach out and chat in more detail.

**Comment by OxyFlax** [comment]
Ok thanks, hope it will be updated this year!

**Comment by dragantr** [comment]
Any updates on this? 
Thanks.

**Comment by oldalton** [comment]
@dragantr, this should be already supported with latest MSAL and Intune SDK.

**Comment by dragantr** [comment]
@oldalton thanks. Is there a sample app or documentation on how we can use MSAL and Intune SDK?

**Comment by oldalton** [comment]
@dragantr, here you go: https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#configure-adalmsal

**Comment by viveknegi51288** [comment]
@oldalton Can we use MSAL and intune android sdk  ? As per the official documentation, there is only ADAL configuration is explained . Please help

**Comment by oldalton** [comment]
@viveknegi51288, do you mind opening this as question in the MSAL Android repository? Thanks. https://github.com/AzureAD/microsoft-authentication-library-for-android
