### ISSUE TITLE
Carthage build failing for dev branch

### ISSUE THREAD

**Issue by mmysliwiec** [AzureAD/microsoft-authentication-library-for-objc#247]
Since few commits, Carthage is no longer building dev branch. The issue was introduced in commit #265bc5695eac510f0bbf40211bc32078c516ef1f. I was not able to build the project with Carthage since then despite it's building fine with Xcode. Now I've tested it on commit #8bccc7f988bbe280c4a6cc2fdb60111754a6ab26.

Here is the log file from Carthage:
[carthage-xcodebuild.gvyUrH.log](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/1539092/carthage-xcodebuild.gvyUrH.log)

My test had only the MSAL in Cartfile:
`github "AzureAD/microsoft-authentication-library-for-objc" "dev"`

I was building with:
`carthage update --platform iOS`

I got such error from the Carthage:
```Building scheme "MSAL (iOS Framework)" in MSAL.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/mmysliwiec/Desktop/CarthageTest/Carthage/Checkouts/microsoft-authentication-library-for-objc/MSAL.xcworkspace -scheme MSAL\ (iOS\ Framework) -configuration Release -derivedDataPath /Users/mmysliwiec/Library/Caches/org.carthage.CarthageKit/DerivedData/9.1_9B55/microsoft-authentication-library-for-objc/8bccc7f988bbe280c4a6cc2fdb60111754a6ab26 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath ./ SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO (launched in /Users/mmysliwiec/Desktop/CarthageTest/Carthage/Checkouts/microsoft-authentication-library-for-objc)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/0w/vdmx8c1d1090srxjm68cxxj43ldpln/T/carthage-xcodebuild.gvyUrH.log
```

I'm on macOS 10.13.1 with Xcode 9.1 but was testing also on macOS 10.12 with Xcode 9.2 with same error.

**Comment by oldalton** [comment]
Please make sure you point Carthage to the master branch. If you want to test the dev branch, please make sure you configure Carthage to also fetch the submodules.
