### ISSUE TITLE
Silent aquireToken and password changed for user

### ISSUE THREAD

**Issue by mkowalski87** [AzureAD/microsoft-authentication-library-for-objc#248]
Hi
When I retrieve idToken for user, and changed password in AD for given user then I'm still able to silently acquire token. Is it possible to detect if password was changed?

**Comment by oldalton** [comment]
Hi, MSAL will return you an access token until it expires. Once it's expired, MSAL won't be able to return an access token anymore, because refresh token won't be valid anymore.
