### ISSUE TITLE
How can I configure the sample to work with Azure AD enterprise accounts

### ISSUE THREAD

**Issue by sarmisen** [AzureAD/microsoft-authentication-library-for-objc#259]
Hello,

I've been strugling with the Swidt iOS sample provided with the Library. I can get it working with "common" scenarios, but not with enterprise Azure AD. I posted a question at stackoverflow explaining in detail my steps

https://stackoverflow.com/questions/48597765/msal-objective-c-library-ios-sample-dont-know-how-to-configure-it

I think, I'm not entering the right data here

let kClientId = "[MyCustomersAzureADAppId]"
let kCurrentUserIdentifier = "MSALCurrentUserIdentifier"
let kAuthority = "https://login.microsoftonline.com/[myCustomerAzureId]

And I allways get the same error

_AADSTS90130: Application '[MyCustomersAppIdinAzureAD]' ([MyCustomersAppNameinAzureAD]) is not supported over the /common or /consumers endpoint. Please use the /organizations or tenant-specific endpoint._

Can anybody help me with this?

Kind regards,

Sergio.

**Comment by sarmisen** [comment]
Solved. In the sample I had to pass the authority constant, that was not used

return try MSALPublicClientApplication(clientId: kClientId, **authority: kAuthority**)

**Comment by eglibecerra** [comment]
@sarmisen, you are a legend! always trust a man with an eye patch :)
