### ISSUE TITLE
Not possible to specify common keychain sharing group

### ISSUE THREAD

**Issue by schroepf** [AzureAD/microsoft-authentication-library-for-objc#260]
In my setup I'd like to use the MSAL library from an App Extension and it's companion app. After the user has logged into the companion app he shall be able to use the same account (i.e. tokens) from the extension as well to authenticate some backend requests.

Both component use different bundle identifiers, and therefore I must be able to change MSAL's default keychain share group to something that doesn't rely on bundle IDs.

**Comment by schroepf** [comment]
a PR to address this issue: #258

**Comment by oldalton** [comment]
Resolved in latest MSAL release.
