### ISSUE TITLE
Change audience for token

### ISSUE THREAD

**Issue by christophercarlsson** [AzureAD/microsoft-authentication-library-for-objc#261]
Hi,
Im trying to authenticate to be able to go against the Office 365 EWS SOAP API. I've setup the AAD app and Office 365 online permissions and they seem to be working correctly. Im using `https://login.microsoftonline.com/{tenant}` as authenticator uri. Most seems fine, however -
 when I get the token back, the aud (audience) property of the token says `https://graph.microsoft.com`. This in turn makes request that I do against `https://outlook.office365.com/` an unauthorized request. How can I change the audience property? When reading the docs for the AAD it seems like I need to send a resource parameter with the request bit I cannot find any support for that in this library.

**Comment by danieldobalian** [comment]
The audience represents the resource the token is issued for, and cannot be modified once the token has been minted & signed. 

In v2 (and when using MSAL), scopes map to a resource.  You'll need to modify the scopes requested in the `acquireToken` call to map to an OAuth2.0 scope the O365 API exposes.  If the API does expose these scopes, the structure would be something like `https://outlook.office365.com/<SCOPE1>`. 

With that being said, I bet the data you're trying to access is available behind the [Microsoft Graph API](https://graph.microsoft.io).  If so, the requests you're already making are likely close to what you need, and the Graph docs will explain any additional ones needed.
