### ISSUE TITLE
AcquireToken always return result as nil and error object in case of B2C tenant

### ISSUE THREAD

**Issue by vaibhav915** [AzureAD/microsoft-authentication-library-for-objc#265]
Hi,

I wanted to authenticate Azure B2C users in our iOS native app, so we are using MSAL library and calling acquireToken function with scope as either empty or "https://graph.microsoft.com/user.read" but in both the cases it is returning result as nil and error with some error object
(instance_type = 0x000060400024da70 -> 0x0000000103209ac8 (void *)0x0000000103209b18: NSError).

I think this is because Azure B2C tenant doesn't returning access token (as same happened with Android app) but it should return other parameters like refresh token, id token etc.. in result.

Any help will be appreciated

**Comment by oldalton** [comment]
Hi, can you please provide a code sample of using MSAL and exact details about error you're receiving. Thanks.

**Comment by vaibhav915** [comment]
Hello,
It's the same code that is available on Microsoft site for MSAL (https://azure.microsoft.com/en-us/resources/samples/active-directory-b2c-ios-swift-native-msal/)

So, when we are calling acquireToken function for B2C user it returns nil in result whereas throws below error message

Error Description:
(instance_type = 0x000060400024da70 -> 0x0000000103209ac8 (void *)0x0000000103209b18: NSError)

**Comment by oldalton** [comment]
Please file an issue in here: https://github.com/Azure-Samples/active-directory-b2c-ios-swift-native-msal

**Comment by oldalton** [comment]
Closing the issue due to inactivity. Please reopen if needed.
