### ISSUE TITLE
iOS 11.3 SDK Crash in Swift

### ISSUE THREAD

**Issue by LaurentiuUngur** [AzureAD/microsoft-authentication-library-for-objc#268]
**Environment:** Swift 4.1, Xcode 9.3, iOS 11.3 SDK. Latest library from master branch.

**Problem:** It seems the app crashes when handling the redirect from the SFSafariViewController. This is the backtrace:

`* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00000001138c12cf libswiftCore.dylib`swift_getObjectType + 47
    frame #1: 0x000000010e9b30f8 MyApp`@objc AppDelegate.application(_:open:sourceApplication:annotation:) at AppDelegate.swift:0
    frame #2: 0x000000011142633f UIKit`__58-[UIApplication _applicationOpenURLAction:payload:origin:]_block_invoke + 1037
    frame #3: 0x0000000111425c31 UIKit`-[UIApplication _applicationOpenURLAction:payload:origin:] + 652
    frame #4: 0x00000001205bbcb8 SafariServices`-[SFSafariViewController remoteViewController:hostApplicationOpenURL:] + 205
    frame #5: 0x00000001205adc28 SafariServices`-[SFBrowserRemoteViewController willOpenURLInHostApplication:] + 68
    frame #6: 0x00000001105f8ccc CoreFoundation`__invoking___ + 140
    frame #7: 0x00000001105f8b84 CoreFoundation`-[NSInvocation invoke] + 308
    frame #8: 0x000000011538e848 libdispatch.dylib`_dispatch_client_callout + 8
    frame #9: 0x0000000115393e14 libdispatch.dylib`_dispatch_block_invoke_direct + 592
    frame #10: 0x00000001173be470 FrontBoardServices`__FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
    frame #11: 0x00000001173be12e FrontBoardServices`-[FBSSerialQueue _performNext] + 439
    frame #12: 0x00000001173be68e FrontBoardServices`-[FBSSerialQueue _performNextFromRunLoopSource] + 45
    frame #13: 0x0000000110617bb1 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    frame #14: 0x00000001105fc4af CoreFoundation`__CFRunLoopDoSources0 + 271
    frame #15: 0x00000001105fba6f CoreFoundation`__CFRunLoopRun + 1263
    frame #16: 0x00000001105fb30b CoreFoundation`CFRunLoopRunSpecific + 635
    frame #17: 0x0000000117c50a73 GraphicsServices`GSEventRunModal + 62
    frame #18: 0x000000011141d0b7 UIKit`UIApplicationMain + 159
  * frame #19: 0x000000010e9b4277 MyApp`main at AppDelegate.swift:14
    frame #20: 0x000000011540b955 libdyld.dylib`start + 1
    frame #21: 0x000000011540b955 libdyld.dylib`start + 1`

**FIX:** Use `func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool` instead of `func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool` when handling the redirect from the SFSafariViewController in Swift.

**Comment by marcinwalus** [comment]
I can confirm this issue: it happens also in my app.
@LaurentiuUngur Thank you for workaround.

**Comment by sheinix** [comment]
Any progress on this? Thanks.

**Comment by oldalton** [comment]
Can you please retry with MSAL 0.2.0?
