### ISSUE TITLE
Building in xcodebuild results in timeout in Carthage. Maybe build error?

### ISSUE THREAD

**Issue by brandwe** [AzureAD/microsoft-authentication-library-for-objc#269]
When trying to build in Carthage, get the following error:

```
[brwerner@Brandons-MacBook-Pro active-directory-ios-swift-native-v2 (dev)]$ carthage update
*** Fetching microsoft-authentication-library-for-objc
*** Checking out microsoft-authentication-library-for-objc at "3e7cfd6662e802620f0494daee9ff077924b9946"
*** xcodebuild output can be found in /var/folders/wq/jy3793q52qx2v2bl8_r8v5v40000gn/T/carthage-xcodebuild.Yv9mo0.log
xcodebuild timed out while trying to read MSAL.xcodeproj 😭
```
There is nothing in the log file, it is 0b.

It's possible from reports around the Internet that the build flags you are using in your `build.py` file are required for building, and that is not something Carthage can use to build. A typical culprit is trying to sign the build with keys which the flags in `build.py` prevent but again.. Carthage would have no way knowing to use `build.py` to provide those flags to a developer using it. My guess anyway.

**Comment by oldalton** [comment]
Closing the issue due to inactivity. Please reopen if the issue still occurs.
