### ISSUE TITLE
Changing kAuthority to consumers doesn't work

### ISSUE THREAD

**Issue by jthake-msft** [AzureAD/microsoft-authentication-library-for-objc#274]
I'm using the MSAL Preview for iOS and this[ swift sample](https://github.com/Azure-Samples/active-directory-ios-swift-native-v2).

Based on the [documentation here](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols#endpoints), I should be using consumers not common to force it to Personal accounts only.

In the [ViewDidLoad function](https://github.com/Azure-Samples/active-directory-ios-swift-native-v2/blob/323c9e884968f45760f62a5b9aef3e4b6e8127ed/MSALiOS/ViewController.swift#L206)

`self.applicationContext = try MSALPublicClientApplication.init(clientId: kClientID, authority: kAuthority)`
Changing kAuthority to

`https://login.microsoftonline.com/consumers/oauth2/v2.0/authorize`
Should lock it to consumer accounts only.

But this seems to throw an error of "This doesn't look like a work or school email. You can't sign in here iwth a personal account. User your work or school account instead." It does work for that kAuthority if i put in org account.

If i change to

`https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize`
It allows allows org in but not consumer account.

Both work if I set back to code sample default of

`https://login.microsoftonline.com/common/oauth2/v2.0/authorize`
I have noticed that if I hit this in a browser

`https://login.microsoftonline.com/consumers/oauth2/v2.0/authorize?client_id=##clientid##&response_type=code&redirect_uri=http%3A%2F%2Flocalhost&response_mode=query&scope=openid%20offline_access%20https%3A%2F%2Fgraph.microsoft.com%2Fmail.read&state=12345`
this works fine in a browser. So I don't think its an application configuration issue. unless its to do with native vs web calling this?

I noticed in the latest sample , kAuthority has been shortened.

`let kAuthority = "https://login.microsoftonline.com/common/"`
Tried this and doesn't make a difference.

**Comment by oldalton** [comment]
I just did a quick test and this seems to be resolved. @jthake Can you verify?

**Comment by jthake** [comment]
I'm using the latest version of this project cloned fresh and ran pod install https://github.com/Azure-Samples/active-directory-ios-swift-native-v2

If I change the kAuthority to
let kAuthority = "https://login.microsoftonline.com/consumers/"

I get this still
![image](https://user-images.githubusercontent.com/6786616/41822841-cc38f742-77aa-11e8-953d-3408176060df.png)

Actually now I get an error when signing in with a organization account too

![image](https://user-images.githubusercontent.com/6786616/41822832-b130371c-77aa-11e8-8327-ff9cb971fb6c.png)
