### ISSUE TITLE
Login page does not render for iPhone X

### ISSUE THREAD

**Issue by jthake-msft** [AzureAD/microsoft-authentication-library-for-objc#277]
Originally I found this bug when debugging whilst plugged into my iPhone X. But then once I released it for testing via TestFlight, I found out that other iPhone X users also have this problem.

Essentially, when the MSAL library wants to show the sign in screen, the Safari window pops up with grey top navigation and bottom bar. But nothing ever loads in the middle of screen.

If you force quit the app on iOS, and turn off Wi-Fi and launch app again. The login screen loads correctly. 

This consistently happens on iPhone X for anyone who hasn't launched the app before. Or who permanently removes the application and tries launching it again.

I have used the code in this [sample](https://github.com/Azure-Samples/active-directory-ios-swift-native-v2 inside my application) .

The iPhone X devices range from 11.3 - latest beta. 

It appears once they do this wifi off thing and sign in, this problem goes away. I cannot replicate this problem on any other hardware device.

**Comment by unpluggedk** [comment]
I've been trying to reproduce this issue on 11.3 and now 11.4 on iPhone X; both with Wifi on and off. 
I cannot get this reproduced. Were you using the sample as it was or change something?

From the description however, the fact that the safari view controller loaded fine, if the middle only is blank, there isn't much that can be done from the library.

Can you see if this is still reproducible?

Thanks heaps!

**Comment by jthake-msft** [comment]
I finally worked out that I needed to take this out of the viewDidAppear to  viewDidLoad and this seems to have resolved this issue. The samples may need updating to stop others making this mistake.
