### ISSUE TITLE
Possibility to open the Safari Window in a modal VC

### ISSUE THREAD

**Issue by HannesVDB** [AzureAD/microsoft-authentication-library-for-objc#284]
Is there the possibility to open the `Safari Window` in a Modal View Controller on an iPad?

**Comment by oldalton** [comment]
It's currently not supported, but should be technically possible.

**Comment by colinhumber** [comment]
+1 for this

**Comment by colinhumber** [comment]
I'm working on contributing an enhancement to provide this functionality.

https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/399

Once this has been approved I'll work on integrating this into the main MSAL library.

**Comment by unpluggedk** [comment]
#534

**Comment by oldalton** [comment]
Should be fixed in the latest MSAL. Please reopen if needed.
