### ISSUE TITLE
Incorrect token URL for Azure B2C

### ISSUE THREAD

**Issue by eriklamanna** [AzureAD/microsoft-authentication-library-for-objc#291]
I've been trying to get this library to work with Azure B2C tenants and was unable to get the code working out of the box. Upon further examination I've discovered that the token endpoint that's generated after the authorization step is not generated correctly. It seems that the policy query parameter is dropped in the flow process.

So for example, if you pass the policy `p` query value in `extraQueryParameters` to `aquireTokenForScopes`, the authorization call properly adds the policy to the URL. However once the callback is complete from the SFSafariViewController, the `aquireToken:` call in `MSALBaseRequest.m` no longer has the query parameter. This causes the final leg of the login flow to fail. 

So for example, the URL that does work is in the format of:

https://login.microsoftonline.com/tenant/oauth2/v2.0/token?p=policyname

but the SDK is using

https://login.microsoftonline.com/tenant/oauth2/v2.0/token

The endpoint the SDK is using ends up having Azure B2C return an MSALError of 42100, which is an invalid_grant error. If I modify the library to add the policy, then the call works.

I'm happy to add more info if necessary, but at the moment it appears this library is incompatible with the Azure B2C flow. If that's not the case I'm happy to be shown otherwise.

**Comment by oldalton** [comment]
Hi. There're multiple ways to specify policies with Azure B2C (through query parameters or path components). However, MSAL only supports the second one. So, to use B2C policies, your authority needs to be in the following format "https://<host>/tfp/<tenant>/<policy>/". e.g. https://login.microsoftonline.com/tfp/contoso.onmicrosoft.com/B2C_1_signup_signin/

Please let me know if it works.

**Comment by eriklamanna** [comment]
Thank you for the response. I've tried every combination of the TFP URL and I only get 404s. 

https://login.microsoftonline.com/tfp/my_tenant.onmicrosoft.com/b2c_1a_signup_signin/v2.0/oauth/authorize

I've tried almost every permutation of the last part of this path and all I get is 404s for an authorize endpoint on B2C.

**Comment by oldalton** [comment]
Thanks for the additional information. Let me take a look at it.

**Comment by oldalton** [comment]
Hi, please make sure that both your policy name and tenant name are valid. We've now verified B2C setup with MSAL end to end and it is working.

**Comment by eriklamanna** [comment]
Thank you for following up. I must have something incorrect in my config somewhere. I'll retry setting it up again.

**Comment by rodrigorodriguez** [comment]
@eriklamanna , now I got this 404 error. Did the Azure B2C tenants worked?
