### ISSUE TITLE
Not allowed to install pod for platform :ios, '9.0'

### ISSUE THREAD

**Issue by MiteshiOS** [AzureAD/microsoft-authentication-library-for-objc#292]
It shows me this error.

Specs satisfying the `MSAL (from `https://github.com/AzureAD/microsoft-authentication-library-for-objc`, tag `0.1.3`)` dependency were found, but they required a higher minimum deployment target.

I want my minimum deployment target 9.0. Please let me know what i should do for that ? 

https://apps.dev.microsoft.com/portal/quickstart/ios

I tried with this but it shows me **We are unable to issue token from this api version for a Microsoft account**
![simulator screen shot - ipad air 2 - 2018-07-18 at 20 28 39](https://user-images.githubusercontent.com/17427703/42889991-556f505c-8ac9-11e8-9a39-03c3cad74802.png)

**Comment by MiteshiOS** [comment]
@oldalton Thank you for the information. Actually what i did is i changed deployment target to iOS 10 after that i install pod and it successfully installed. Now from my xcode project i changed target to iOS 9 and log in with microsoft working.
So there will be any issue further with this approach ?

**Comment by oldalton** [comment]
As I mentioned above, we'll be dropping support of iOS 9 for MSAL in a couple of months. That means we won't be able to guarantee MSAL compatibility with that iOS version anymore (just for clarity, we still support iOS 9.3.x as of the current moment). While you might still find it working on iOS 9 going forward, we won't be able to support you if you experience iOS 9 specific issues or API incompatibilities. 

Just FYI, 95% of users currently use iOS 10 and iOS 11 according to https://developer.apple.com/support/app-store/. Once iOS 12 is released, iOS 9 market share will decrease even more.

**Comment by MiteshiOS** [comment]
@oldalton Thank you for the information and support.

**Comment by oldalton** [comment]
@MiteshiOS, looks like the issue was resolved. I'll close this issue. Please reopen if you're still experiencing problems.
