### ISSUE TITLE
May I know when the MSAL can support MacOS?

### ISSUE THREAD

**Issue by JimmyLS** [AzureAD/microsoft-authentication-library-for-objc#317]
I saw the similar question posted here last year. May I know if there're any updates now? Or could you please provide an ETA when the MacOS can be supported to use this library. 

Thanks a lot in advance.

Jimmy Sun

**Comment by oldalton** [comment]
We'll start adding support for macOS after we finish adding all ADAL features to MSAL for iOS. We're currently working on a more detailed plan/timeline for macOS support.

**Comment by JimmyLS** [comment]
Thanks for this info. Hope you can provide the plan/timeline soon.

**Comment by mohacs** [comment]
@oldalton thank you, can you provide ETA? almost a year passed and we did not hear anything about it?

**Comment by oldalton** [comment]
We're planning to be feature complete for iOS in 2-3 months from now. We'll pick up macOS after that. For macOS, we're currently missing caching mechanism and a test app. Otherwise, it should be fully functional. Caching is the most complicated piece with macOS supporting access groups only for iCloud Keychain. We're estimating this to be another 2-3 months of work. 

We appreciate external contributions if anybody wishes to contribute e.g. macOS test app or other missing pieces :)

**Comment by kamleshgk** [comment]
@oldalton 
Do you have an update for macOS support?  
Thank you.

**Comment by mohacs** [comment]
@oldalton 
Do you have an update for macOS support?
Thank you.

**Comment by oldalton** [comment]
@kamleshgk, @mohacs, This is something we're working on right now. 
macOS MSAL is currently only missing caching, and the test app. For caching, you can see some work in progress here: https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/374.

**Comment by kamleshgk** [comment]
Thanks @oldalton

**Comment by mohacs** [comment]
@oldalton Thank you so much for information. Cheers.

**Comment by SteveDCronin** [comment]
Please consider providing an update - the cache thread above is now 3 months old...  What versions of macOS will be supported?

**Comment by oldalton** [comment]
Hi, we have made a lot of progress, and we're finalizing the caching part right now. We're expecting the first release with macOS support to be available in 2-3 weeks (with caching, but no SSO support between multiple apps yet - this will come in the next release). You can already try out MSAL macOS test app in the dev branch of MSAL, and report any issues you're seeing. Looking forward to the feedback! Thanks.

**Comment by SteveDCronin** [comment]
On Jun 17, 2019, at 11:08 PM, Olga Dalton <notifications@github.com> wrote:Hi, we have made a lot of progress, and we're finalizing the caching part right now. We're expecting the first release with macOS support to be available in 2-3 weeks (with caching, but no SSO support between multiple apps yet - this will come in the next release). Thank-You!   a bunch of good news there!  If I just have a single macOS app then the lack of SSO should not impact me yes?You can already try out MSAL macOS test app in the dev branch of MSAL, and report any issues you're seeing. I'm baffled by all the GitHub repos... Could help me out here?I THINK what you are talking about is:    github.com/AzureAD/microsoft-authentication-library-for-objc	note: on GitHub this shows dev as the default branch - so is this URL what you meant?	note: when I look at sample code associated with this it is Swift not ObjC...

**Comment by oldalton** [comment]
Yes, it's the default "dev" branch: https://github.com/AzureAD/microsoft-authentication-library-for-objc. MSAL uses submodules, so make sure you run "git submodule update --init" after checking it out. For testing, I'd recommend to run the MSAL macOS test app target in the MSAL project, and some test code we use in Obj-C is here: https://github.com/AzureAD/microsoft-authentication-library-for-objc/tree/dev/MSAL/test/app/mac

**Comment by guidedways** [comment]
@oldalton That's great news - can we also have the 'ReadMe' updated to reflect that it now supports macOs and official support is imminent?

**Comment by guidedways** [comment]
@oldalton Also, I see a bunch of errors when trying to compile the sample macOS test app, such as these:

`error: /Users/myuser/Downloads/microsoft-authentication-library-for-objc-dev/MSAL/xcconfig/msal__common.xcconfig:1: could not find included file '../IdentityCore/IdentityCore/xcconfig/identitycore__common.xcconfig' in search paths (in target 'MSAL (Mac Framework)')`

There are a bunch of these in the console and I can see there are no such `xcconfig` files in the `identitiyCore` folder.

**Comment by oldalton** [comment]
@guidedways, we'll update Readme once the MSAL version with macOS support is officially released. Regarding the error you're seeing, it's likely happening due to Git Submodule. After checking out the code, make sure you run "git submodule update --init" to resolve MSAL dependencies.

**Comment by oldalton** [comment]
First version supporting macOS has shipped: https://github.com/AzureAD/microsoft-authentication-library-for-objc/releases/tag/0.5.0

**Comment by guidedways** [comment]
@oldalton The release notes refer to some "Advanced features of SSO" - can you please specify what these features are so we know if we should hold back?

**Comment by oldalton** [comment]
Apps will have an ability to pass other trusted applications when writing items to cache. That way if you're shipping multiple apps on macOS, all your apps will be able to share SSO with each other.

**Comment by smmcdonald** [comment]
> @guidedways, we'll update Readme once the MSAL version with macOS support is officially released. Regarding the error you're seeing, it's likely happening due to Git Submodule. After checking out the code, make sure you run "git submodule update --init" to resolve MSAL dependencies.

I had the issue that @guidedways encountered and trying the git submodule update did not work for me. This happened because I cloned the project via zip file, which does not inherit any of the Git files. I instead cloned the project with the Github Desktop app and the build compiled right out of the box on the first try.

**Comment by oldalton** [comment]
@smmcdonald, if you want to use zip, please download microsoft-authentication-library-for-objc-xxx.zip file instead. It should include dependencies.

**Comment by oldalton** [comment]
Fixed. Closing the issue.
