### ISSUE TITLE
Unable to find a specification for `MSAL`.

### ISSUE THREAD

**Issue by SoftDev0420** [AzureAD/microsoft-authentication-library-for-objc#332]
When I run `pod update`, I get `Unable to find a specification for MSAL` message.
How can I solve this? It did work before.

**Comment by oldalton** [comment]
Hi. The previous MSAL CocoaPods definition wasn't official MSAL one and it was maintained by a third party dev pointing to a different repository. In the effort to make sure MSAL CocoaPods is pointing to an official Microsoft maintained repository, we'll be switching it to the official Microsoft CocoaPods and taking over maintenance of it. We're right in the process of doing so. You can expect a new update to CocoaPods in less than 24 hours. I'll update this thread once it's available. 

Sorry for the inconvenience!

**Comment by SoftDev0420** [comment]
Thank you for your kind reply!


On September 12, 2018 at 9:52:13 PM, Olga Dalton (notifications@github.com)
wrote:

Hi. The previous MSAL CocoaPods definition wasn't official MSAL one and it
was maintained by a third party dev pointing to a different repository. In
the effort to make sure MSAL CocoaPods is pointing to an official Microsoft
maintained repository, we'll be switching it to the official Microsoft
CocoaPods and taking over maintenance of it. We're right in the process of
doing so. You can expect a new update to CocoaPods in less than 24 hours.
I'll update this thread once it's available.

Sorry for the inconvenience!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/332#issuecomment-420775566>,
or mute the thread

**Comment by oldalton** [comment]
MSAL CocoaPods 0.1.4 is now available: https://cocoapods.org/pods/MSAL
Please let me know if you have any questions.

**Comment by SoftDev0420** [comment]
I just saw it. It would be better if you add the installation guide using CocoaPod at document.

Thank you.

**Comment by SoftDev0420** [comment]
Yes, it works! (Actually, I did `pod update`.)

Thank you again.
