### ISSUE TITLE
Use of undeclared type 'MSALUser'

### ISSUE THREAD

**Issue by hooliooo** [AzureAD/microsoft-authentication-library-for-objc#344]
Hello,

I've been using MSAL for an existing project. It was versioned 0.2.4 before but when I ran pod update MSAL. The version went to 0.1.4. And I get compile errors saying that MSALUser is an undeclared type.
It was working last week but now it is not.

What can I do to resolve this?

<img width="551" alt="screen shot 2018-09-17 at 10 05 39 am" src="https://user-images.githubusercontent.com/7699349/45611877-58404080-ba61-11e8-88ee-1f11e74dcefa.png">

**Comment by oldalton** [comment]
Hi. MSALUser has been replaced with MSALAccount.
Also, 0.2.4 CocoaPods wasn't maintained by Microsoft. It was maintained by another dev and wasn't pointing to correct repository. 0.1.4 is now maintained by Microsoft, that's why the version numbers have changed.

**Comment by hooliooo** [comment]
Thank you for the info :)
