### ISSUE TITLE
 'AuthenticationServices/AuthenticationServices.h' file not found’

### ISSUE THREAD

**Issue by lololopez** [AzureAD/microsoft-authentication-library-for-objc#365]
I have tried to install the next branch "pod 'MSAL', :git => 'https://github.com/AzureAD/microsoft-authentication-library-for-objc', :branch => 'master', :submodules => true” and I have received this error 'AuthenticationServices/AuthenticationServices.h' file not found’ when I tried to import '#import <AuthenticationServices/AuthenticationServices.h>’

I also have tried to install "pod 'MSAL', '~> 0.2’” but i received any problem. 

Could you tell me which branch i have to install? 

Thank you.

**Comment by oldalton** [comment]
@lololopez Can you make sure you're using Xcode 10. AuthenticationServices framework was added by Apple in iOS 12+.

**Comment by oldalton** [comment]
@lololopez Did you try the suggested fix? Thanks

**Comment by lololopez** [comment]
Yes, i could test It and It was right.

**Comment by oldalton** [comment]
Thanks @lololopez.
