### ISSUE TITLE
Can't clear cookie when logout

### ISSUE THREAD

**Issue by youlianqi** [AzureAD/microsoft-authentication-library-for-objc#378]
I am trying to logout and clear all data, but when I login in again, old account is in cookie.

The function for logout is :

NSHTTPCookieStorage* cookieStorage = [NSHTTPCookieStorage sharedHTTPCookieStorage];
    for(NSHTTPCookie* cookie in [cookieStorage cookies])
    {
        if(cookie)
            [cookieStorage deleteCookie:cookie];
    }
[self.msalClient removeUser:self.user error:&error_];

**Comment by youlianqi** [comment]
How to true logout for MSAL?

**Comment by oldalton** [comment]
You cannot clear cookies using NSHTTPCookieStorage from SFSafariViewController or SFAuthenticationSession. Apple doesn't give developers any control over cookies in those components.

We have the "true logout" on our roadmap, where logout will open the web component and logout of the account globally.

**Comment by youlianqi** [comment]
Present SFSafariViewController with logoutURL  https://login.microsoftonline.com/common/oauth2/v2.0/logout, success in iOS 10. But fail in iOS 11 and iOS 12. 

@oldalton  Do you have any suggestions? Thanks a lot.

**Comment by oldalton** [comment]
Which MSAL version are you using? Latest MSAL doesn't use SFSafariViewController by default anymore on iOS 11+.

**Comment by aanthonyDOL** [comment]
My pod was updated now , when I'm doing authentication instead of seeing users in the code im seeing accounts. Now my Microsoft redirect throws a error: acquireToken returning with error: (NSOSStatusErrorDomain, -34018)

if  try API.applicationContext.**accounts()**.isEmpty

**Comment by oldalton** [comment]
@aanthonyDOL, -34018 means errSecMissingEntitlement, please follow our guidance on resolving it here: [-34018 Failed to set item into keychain errors](https://github.com/AzureAD/microsoft-authentication-library-for-objc/wiki/Keychain-on-iOS#-34018-failed-to-set-item-into-keychain-errors)

**Comment by aanthonyDOL** [comment]
I was previously using 0.1.4 and everything was working find. Way the Keychain feature added in a later version?

**Comment by oldalton** [comment]
0.1.4 should have the same keychain functionality. We fixed a couple of bugs in the latest 0.2.0 version. Can you please let me know which keychain sharing groups are declared in your entitlements and which ones you're providing to MSAL?

**Comment by oldalton** [comment]
@aanthonyDOL is this your entitlement configuration? What are you passing to MSAL?
MSAL uses "com.microsoft.adalcache" as a default group. If you're not changing the access group in MSAL, you have to register that one in your entitlements.

**Comment by aanthonyDOL** [comment]
My entitlement configuration is the default settings , and so is what im passing to MSAL. I havent changed any keychain configurations. In addition using MS login worked before with the default keychain configurations.

**Comment by aanthonyDOL** [comment]
When I cloned the project I didn't change any Keychain configurations, so both of the com.microsoft.MSALTestApp and com.microsoft.msalcache are included in the entitlement file and in the Keychain group in the Keychain Sharing under Capabilities

**Comment by oldalton** [comment]
Thanks. When you say you "cloned the project". Which project are you referring to? Is it some kind of a sample?

**Comment by aanthonyDOL** [comment]
I'm missing $(AppIdentifierPrefix)com.microsoft.workplacejoin from entitlements. Yes it was a sample.

**Comment by aanthonyDOL** [comment]
That was it I was missing $(AppIdentifierPrefix)com.microsoft.adalcache

**Comment by youlianqi** [comment]
> You cannot clear cookies using NSHTTPCookieStorage from SFSafariViewController or SFAuthenticationSession. Apple doesn't give developers any control over cookies in those components.
> 
> We have the "true logout" on our roadmap, where logout will open the web component and logout of the account globally.

Do you mean that user must use ASWebAuthenticationSession/SFAuthenticationSession to open logout url https://login.microsoftonline.com/common/oauth2/v2.0/logout, and then manual pick an account to sign out?  After that dismiss web view from call back url?
As this article said. https://stackoverflow.com/questions/47207914/sfauthenticationsession-aswebauthenticationsession-and-logging-out

**Comment by oldalton** [comment]
Yes, you'd also need to pass some extra additional parameters. Please see information [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#send-a-sign-out-request). Implementing this functionality as part of MSAL is on our roadmap as well.

**Comment by aanthonyDOL** [comment]
I'm using MSAL framework to login to this app that I developed. On the login screen I cannot get the Token. Nothing Changed in My code. I'm getting the following message in Console: 
%@ TID = 10238 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:41 - B6626163-BFED-471E-8717-0A94A6FEDA7B] Get keychain items, key info (account: (not-nil) service: (nil))
%@ TID = 10238 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:41 - B6626163-BFED-471E-8717-0A94A6FEDA7B] Trying to find keychain items...
%@ TID = 10238 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:41 - B6626163-BFED-471E-8717-0A94A6FEDA7B] Keychain find status: 0
%@ TID = 10238 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:41 - B6626163-BFED-471E-8717-0A94A6FEDA7B] Found 1 items.
%@ TID = 10238 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:41 - B6626163-BFED-471E-8717-0A94A6FEDA7B] Get keychain items, key info (account: (not-nil) service: (not-nil))
%@ TID = 10238 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:41 - B6626163-BFED-471E-8717-0A94A6FEDA7B] Trying to find keychain items...
%@ TID = 10238 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:41 - B6626163-BFED-471E-8717-0A94A6FEDA7B] Keychain find status: 0
%@ TID = 10238 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:41 - B6626163-BFED-471E-8717-0A94A6FEDA7B] Found 1 items.
%@ TID = 10238 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:41 - B6626163-BFED-471E-8717-0A94A6FEDA7B] HTTP request login.microsoftonline.com://login.microsoftonline.com
%@ TID = 10363 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:42 - B6626163-BFED-471E-8717-0A94A6FEDA7B] Refreshing access token
%@ TID = 10363 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:42 - B6626163-BFED-471E-8717-0A94A6FEDA7B] HTTP request login.microsoftonline.com://login.microsoftonline.com

-----------------------------

I have these in Keychain Section of xCode 
$(AppIdentifierPrefix)com.microsoft.MSALTestApp
$(AppIdentifierPrefix)com.microsoft.adalcache
$(AppIdentifierPrefix)com.microsoft.workplacejoin

**Comment by aanthonyDOL** [comment]
> Yes, you'd also need to pass some extra additional parameters. Please see information [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#send-a-sign-out-request). Implementing this functionality as part of MSAL is on our roadmap as well.

I'm using MSAL framework to login to this app that I developed. On the login screen I cannot get the Token. Nothing Changed in My code. I'm getting the following message in Console:
%@ TID = 10238 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:41 - B6626163-BFED-471E-8717-0A94A6FEDA7B] Get keychain items, key info (account: (not-nil) service: (nil))
%@ TID = 10238 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:41 - B6626163-BFED-471E-8717-0A94A6FEDA7B] Trying to find keychain items...
%@ TID = 10238 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:41 - B6626163-BFED-471E-8717-0A94A6FEDA7B] Keychain find status: 0
%@ TID = 10238 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:41 - B6626163-BFED-471E-8717-0A94A6FEDA7B] Found 1 items.
%@ TID = 10238 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:41 - B6626163-BFED-471E-8717-0A94A6FEDA7B] Get keychain items, key info (account: (not-nil) service: (not-nil))
%@ TID = 10238 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:41 - B6626163-BFED-471E-8717-0A94A6FEDA7B] Trying to find keychain items...
%@ TID = 10238 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:41 - B6626163-BFED-471E-8717-0A94A6FEDA7B] Keychain find status: 0
%@ TID = 10238 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:41 - B6626163-BFED-471E-8717-0A94A6FEDA7B] Found 1 items.
%@ TID = 10238 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:41 - B6626163-BFED-471E-8717-0A94A6FEDA7B] HTTP request login.microsoftonline.com://login.microsoftonline.com
%@ TID = 10363 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:42 - B6626163-BFED-471E-8717-0A94A6FEDA7B] Refreshing access token
%@ TID = 10363 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:42 - B6626163-BFED-471E-8717-0A94A6FEDA7B] HTTP request login.microsoftonline.com://login.microsoftonline.com

I have these in Keychain Section of xCode
$(AppIdentifierPrefix)com.microsoft.MSALTestApp
$(AppIdentifierPrefix)com.microsoft.adalcache
$(AppIdentifierPrefix)com.microsoft.workplacejoin

**Comment by oldalton** [comment]
@Shayila, which web component are you using?
If you want to force user to enter his password next time, you can use WKWebView for authentication, or pass MSALForceLogin as ui behavior for next login.
MSAL currently doesn't support signing out from device, but it's on our roadmap.

**Comment by Shayila** [comment]
Thanks, I used MSALForceLogin and it works.

**Comment by cjwillis809** [comment]
@oldalton Are there any updates to when the true logout will be implemented, or how prioritized it is on the roadmap? We are using this library for our application to authenticate users through a client's Azure Active Directory and would be _very_ interested in having this functionality in ASAP.

Thanks

**Comment by GithubAshishHere** [comment]
> Thanks, I used MSALForceLogin and it works.

can please let me know how you code? for logout?

**Comment by oldalton** [comment]
In the latest MSAL, you can now call [signout API](https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALPublicClientApplication.html#/c:objc(cs)MSALPublicClientApplication(im)signoutWithAccount:signoutParameters:completionBlock:), and if you set [signoutFromBrowser](https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALSignoutParameters.html#/c:objc(cs)MSALSignoutParameters(py)signoutFromBrowser) to YES, this will also do the browser signout.

**Comment by Jins17994** [comment]
@oldalton how to call signet API and set signoutFromBrowser in our code? plz share a sample code....plzzz
in my case when user sign out from account(Facebook is I am using in azure ad b2c) and again click on sign in button with another user then MSALwebView shows previously logged user detail(cache not cleared).

**Comment by oldalton** [comment]
@Jins17994, here's a sample: https://github.com/AzureAD/microsoft-authentication-library-for-objc#implement-signout

**Comment by Jins17994** [comment]
thanks for the reply,

this is my code, plz check is there any mistake

*let* viewController = *self* /*replace with your main presentation
controller here */

            *let* webViewParameters =
MSALWebviewParameters(authPresentationViewController: viewController)

            *let* signoutParameters =
MSALSignoutParameters(webviewParameters: webViewParameters)

            signoutParameters.signoutFromBrowser = *false*





            //thisAccount is MSAL Account

            *if* *let* accountToRemove = thisAccount {

            applicationContext!.signout(with: accountToRemove,
signoutParameters: signoutParameters, completionBlock: {(success, error)
*in*



                *if* *let* error = error {

                    print("Couldn't sign out account with error: \(error)")

                    *return*

                }

                print("Sign out completed successfully")

            })

            }*else* {

                print("There is no account to signing out!")

            }

code successfully executed. but again trying to login, then shows previous
logged customer details.
