### ISSUE TITLE
xcode10 : Failed to verify bitcode in MSAL.framework/MSAL: error: Cannot extract bundle from /var/folders/dx/3d4k2yp11d7_twlknf2r0vk80000gn/T/XcodeDistPipeline.HZB/Root/Payload/app/Frameworks/MSAL.framework/MSAL (i386)

### ISSUE THREAD

**Issue by mahasp** [AzureAD/microsoft-authentication-library-for-objc#392]
Hello,

XCode version : 10.0
Carthage version: 0.31.2
microsoft-authentication-library-for-objc at "0.1.3"

When I archive my app i am getting the following error:

Failed to verify bitcode in MSAL.framework/MSAL:
error: Cannot extract bundle from /var/folders/dx/3d4k2yp11d7_twlknf2r0vk80000gn/T/XcodeDistPipeline.HZB/Root/Payload/app/Frameworks/MSAL.framework/MSAL (i386)

Here is what i have tried so far:
lipo -remove i386 MSAL -o MSAL
lipo -remove x86_64 MSAL -o MSAL

clean build and then run the app getting the  following error:
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_MSALPublicClientApplication", referenced from:
      objc-class-ref in AppDelegate.o
      objc-class-ref in DashboardController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

update carthage...then cannot archive my app.

Any help is appreciated.

**Comment by oldalton** [comment]
@mahasp, Can you verify if you see the same issue with the latest version? 0.1.3 is quite an old version...

**Comment by mahasp** [comment]
I did the following and the oissue was resolved:

On your application targets’ “Build Phases” settings tab, click the “+” icon and choose “New Run Script Phase”. Create a Run Script in which you specify your shell (ex: /bin/sh), add the following contents to the script area below the shell:
/usr/local/bin/carthage copy-frameworks
and add the paths to the frameworks you want to use under “Input Files”, e.g.:

$(SRCROOT)/Carthage/Build/iOS/MSAL.framework

And removed the MSAL framework from embeded libraries
