### ISSUE TITLE
Enable Accessibility for WebView

### ISSUE THREAD

**Issue by hlineholm-flir** [AzureAD/microsoft-authentication-library-for-objc#396]

**Comment by oldalton** [comment]
@hlineholm-flir, Can you please provide more information on this request? Thanks.

**Comment by oldalton** [comment]
@hlineholm-flir, Some additional information about this request would be highly appreciated. Thanks.

**Comment by oldalton** [comment]
Closing the issue due to inactivity. Please reopen if needed with additional information.
