### ISSUE TITLE
Supported version for xcode 9.4.1

### ISSUE THREAD

**Issue by kishorekankata** [AzureAD/microsoft-authentication-library-for-objc#409]
Please let me know which version of this library supports xcode 9.4.1, as I am getting a Carthage build fail while running?

**Comment by antrix1989** [comment]
Version [0.1.3](https://github.com/AzureAD/microsoft-authentication-library-for-objc/releases/tag/0.1.3) supports xcode 9, but we recommend you switch to xcode 10 and use latest MSAL version, which is [0.2.2](https://github.com/AzureAD/microsoft-authentication-library-for-objc/releases/tag/0.2.2).
