### ISSUE TITLE
loginHint parameter doesn't work with SignUp policy

### ISSUE THREAD

**Issue by DimaGershman** [AzureAD/microsoft-authentication-library-for-objc#413]
Hi
I am trying to use the overload for `acquireToken` method with the loginHint parameter, but it doesn't seem to work - the sign-up page opens fine, but the username field is still empty.

`application.acquireToken(forScopes: kScopes, loginHint: loginHint) { (result, error) in ...`

MSALAuthority is contracted using: `"https://login.microsoftonline.com/tfp/%@/%@/v2.0/"`

THANKS!

**Comment by oldalton** [comment]
@parakhj Any comment if that's something that B2C supports?

**Comment by parakhj** [comment]
It is supported in custom policies, but not built-in policies. Although let me see if we can get it added into the v2 policies.

**Comment by oldalton** [comment]
@DimaGershman, seems it's not supported by B2C at the moment. Closing the issue as it's not an MSAL issue. Please feel free to reopen if you have additional questions.
