### ISSUE TITLE
Unable to Aquire Token Silently 

### ISSUE THREAD

**Issue by aanthonyDOL** [AzureAD/microsoft-authentication-library-for-objc#422]
I'm using MSAL framework to login to this app that I developed. On the login screen I cannot get the Token. Nothing Changed in My code. I'm getting the following message in Console:
%@ TID = 10238 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:41 - B6626163-BFED-471E-8717-0A94A6FEDA7B] Get keychain items, key info (account: (not-nil) service: (nil))
%@ TID = 10238 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:41 - B6626163-BFED-471E-8717-0A94A6FEDA7B] Trying to find keychain items...
%@ TID = 10238 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:41 - B6626163-BFED-471E-8717-0A94A6FEDA7B] Keychain find status: 0
%@ TID = 10238 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:41 - B6626163-BFED-471E-8717-0A94A6FEDA7B] Found 1 items.
%@ TID = 10238 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:41 - B6626163-BFED-471E-8717-0A94A6FEDA7B] Get keychain items, key info (account: (not-nil) service: (not-nil))
%@ TID = 10238 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:41 - B6626163-BFED-471E-8717-0A94A6FEDA7B] Trying to find keychain items...
%@ TID = 10238 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:41 - B6626163-BFED-471E-8717-0A94A6FEDA7B] Keychain find status: 0
%@ TID = 10238 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:41 - B6626163-BFED-471E-8717-0A94A6FEDA7B] Found 1 items.
%@ TID = 10238 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:41 - B6626163-BFED-471E-8717-0A94A6FEDA7B] HTTP request login.microsoftonline.com://login.microsoftonline.com
%@ TID = 10363 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:42 - B6626163-BFED-471E-8717-0A94A6FEDA7B] Refreshing access token
%@ TID = 10363 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:42 - B6626163-BFED-471E-8717-0A94A6FEDA7B] HTTP request login.microsoftonline.com://login.microsoftonline.com

I have these in Keychain Section of xCode
$(AppIdentifierPrefix)com.microsoft.MSALTestApp
$(AppIdentifierPrefix)com.microsoft.adalcache
$(AppIdentifierPrefix)com.microsoft.workplacejoin

**Comment by antrix1989** [comment]
This line indicates that MSAL was able to find refresh token in the cache and trying to get new access token: 
> %@ TID = 10363 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:13:42 - B6626163-BFED-471E-8717-0A94A6FEDA7B] Refreshing access token

So cache seems to be good. Can you show what happens after? If you have sensitive information, please mask it before uploading logs. Thanks!

**Comment by aanthonyDOL** [comment]
This is what I have next 
%@ TID = 13434 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:31:40 - F2EDC7E9-A2AE-4ACC-ADAD-F6D7D0169668] Refreshing access token
%@ TID = 13434 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:31:40 - F2EDC7E9-A2AE-4ACC-ADAD-F6D7D0169668] HTTP request login.microsoftonline.com://login.microsoftonline.com
%@ TID = 13397 MSAL 0.1.4-dev iOS 12.1.1 [2018-12-10 18:31:40 - F2EDC7E9-A2AE-4ACC-ADAD-F6D7D0169668] acquireTokenSilent returning with error: (MSALErrorDomain, -42004)

**Comment by antrix1989** [comment]
So you getting MSALErrorInvalidGrant (42004). It means that refresh token was rejected by the server. It is either invalid or has expired. Does MSAL shows web view and asking you to enter login/password?

It would be nice if you can send a full log and [network trace](https://github.com/AzureAD/azure-activedirectory-library-for-objc#network-traces) to this emails address: sedemche@microsoft.com. Please mask all sensetive info before sending logs/network trace. Thanks!

**Comment by antrix1989** [comment]
Yeah, your refresh token becomes invalid after you change a password. 

> but my application doesn't redirect me back to the Microsoft Login Screen.

Because it is a silent request, MSAL doesn't show the web view. Instead, it should return you MSALErrorInteractionRequired (42100). When you get this error you should call interactive request with same parameters as you provided to silent request, so MSAL will popup the webview and ask a user to log in again. After user logs in interactively, we will update refresh token in the cash.

**Comment by aanthonyDOL** [comment]
okay thanks

**Comment by aanthonyDOL** [comment]
Which function or bit of code handles the redirect to Microsoft Login page?

**Comment by antrix1989** [comment]
See example [here](https://github.com/AzureAD/microsoft-authentication-library-for-objc#silently-acquiring-an-updated-token-objective-c).

**Comment by antrix1989** [comment]
See an example of error handling [here](https://github.com/AzureAD/microsoft-authentication-library-for-objc/wiki/Error-Handling).
