### ISSUE TITLE
Remove reserved scopes from dictionary under MSALGrantedScopesKey

### ISSUE THREAD

**Issue by antrix1989** [AzureAD/microsoft-authentication-library-for-objc#426]
We suppose developer should pass back all scopes received under MSALGrantedScopesKey to the MSAL. Currently, it also contains reserved scopes. As a result, MSAL rejects the request with the following error:

```
Encountered error with code -51112, description {(
    openid,
    profile,
    "offline_access"
)} are reserved scopes and may not be specified in the acquire token call.
```

**Comment by oldalton** [comment]
@antrix1989, has this been fixed? If yes, please close the issue.

**Comment by ShmuelCammebys** [comment]
@oldalton No, it has not been fixed.

**Comment by aadarsh977** [comment]
Not resolved. Still getting the error.
