### ISSUE TITLE
URGENT: building for iOS Simulator simulator, but linking against dylib (Carthage/Build/Mac/MSAL.framework/MSAL) built for macOS. Note: This will be an error in the future.

### ISSUE THREAD

**Issue by chrisriner** [AzureAD/microsoft-authentication-library-for-objc#439]
I followed the doc and imported the MSAL framework using Carthage and I get this error when building without any code as I simply running builder after importing the framework.

**Comment by oldalton** [comment]
Thanks for reporting this. Can you please confirm if you're trying to use MSAL for iOS or macOS?

**Comment by oldalton** [comment]
Thanks for confirming. We'll take a closer look at this issue.

**Comment by chrisriner** [comment]
Hello, I was wondering if there is any update.  Also I need to modify and older objective-c app and I was trying to make sure of the sdks to authenticate user and use the graph etc and I was wondering since I am having so many issues with these three sdks would I be better off just using the rest urls and not using the sdk

**Comment by oldalton** [comment]
@chrisriner, I did a fresh setup myself with all the steps from our main page, pointing Carthage to master branch. It all worked without warnings on Xcode 10.1 and I was able to run it on iOS simulator.

From your particular issue, it seems that you're linking an iOS project with macOS MSAL. Note that when you build MSAL with Carthage, there will be 2 frameworks built for iOS and for macOS. It seems your app is trying to use the macOS version one located here: Carthage/Build/Mac/MSAL.framework/MSAL. Instead, it needs to use the iOS version of MSAL located here: Carthage/Build/iOS/MSAL.framework/MSAL

I'd suggest double checking which MSAL you're linking in your project and making sure it's coming from iOS build folder. Additionally, double check your project settings like framework search paths etc and copy files phase. 

If you have an empty project where this issue reproduces, you can just zip it together and sent it to my [email][oldalton@[replace-with-my-employer].com], and I'd be happy to take a look at what is the issue with the configuration that you're experiencing. On my end, unfortunately, the issue doesn't reproduce.

**Comment by oldalton** [comment]
@chrisriner, have you had a chance to try out the resolution steps? Thanks.

**Comment by chrisriner** [comment]
I should be able to work on this tomorrow

**Comment by chrisriner** [comment]
Users/cdriner/Directory/Carthage/Build/iOS/MSGraphMSALAuthProvider.framework - that is path showing for my framework - also my search path shows - $(PROJECT_DIR)/Carthage/Build/iOS - I don't see the Mac version anywhere in my project and only see me referencing the iOS version

**Comment by oldalton** [comment]
Thanks, Users/cdriner/Directory/Carthage/Build/iOS/MSGraphMSALAuthProvider.framework is not MSAL framework. Can you provide a link to the repository your Carthage is pointing to?

**Comment by chrisriner** [comment]
Sorry pasted wrong one.  Users/cdriner/Directory/Carthage/Build/iOS/MSAL.framework

my cartfile looks like:
github "microsoftgraph/msgraph-sdk-objc-auth" "master"
github "microsoftgraph/msgraph-sdk-objc" "master"
github "AzureAD/microsoft-authentication-library-for-objc" "master"

**Comment by chrisriner** [comment]
Also here is what happens when I run Carthage update:

Chriss-iMac:Directory cdriner$ ls
Archive of Frameworks.zip		CoolSecurity.framework
CTidy.m					Directory
CXHTMLDocument.m			Directory.plist
CXMLDocument.m				Directory.xcodeproj
CXMLDocument_CreationExtensions.m	Directory.xcworkspace
CXMLDocument_PrivateExtensions.m	Kal.framework
CXMLElement.m				Keychain
CXMLElement_CreationExtensions.m	LoginView.storyboard
CXMLElement_ElementTreeExtensions.m	LoginViewController.m
CXMLNamespaceNode.m			Podfile
CXMLNode.m				Podfile.lock
CXMLNode_CreationExtensions.m		Pods
CXMLNode_PrivateExtensions.m		Soap.framework
CXMLNode_XPathExtensions.m		TouchXML.framework
Cartfile				libxml2.dylib
Chriss-iMac:Directory cdriner$ carthage update
Please update to the latest Carthage version: 0.32.0. You currently are on 0.31.2
*** Fetching msgraph-sdk-objc-auth
*** Fetching msgraph-sdk-objc
*** Fetching microsoft-authentication-library-for-objc
*** Checking out microsoft-authentication-library-for-objc at "39172cf44fd170207689b3fee47d5e1edfb52eb2"
*** Checking out msgraph-sdk-objc-auth at "fb17ce21f561004a162b7b0b71c67ead640c4fda"
*** Checking out msgraph-sdk-objc at "a07f52b5b08be85385255537b1d23c133ef9f8c1"
*** xcodebuild output can be found in /var/folders/1c/3mq4ch_j6gxgpvcmyxktwynw5hfkwj/T/carthage-xcodebuild.Y2h8RE.log
*** Building scheme "MSAL (Mac Framework)" in MSAL.xcworkspace
*** Building scheme "MSAL (iOS Framework)" in MSAL.xcworkspace
*** Building scheme "MSGraphClientSDK" in MSGraphClientSDK.xcodeproj
*** Building scheme "MSGraphMSALAuthProvider" in MSGraphMSALAuthProvider.xcworkspace
Chriss-iMac:Directory cdriner$

**Comment by chrisriner** [comment]
I reset everything back and tried Carthage update again and imported the frameworks again and this time it compiled.  I do get this error now - /Carthage/Build/Mac/MSAL.framework/Headers/MSAL.h:51:9: 'MSAL/MSALWebviewType.h' file not found

**Comment by chrisriner** [comment]
I reset everything back and tried Carthage update again and imported the frameworks again and this time it compiled.  I do get this error now - /Carthage/Build/Mac/MSAL.framework/Headers/MSAL.h:51:9: 'MSAL/MSALWebviewType.h' file not found

**Comment by chrisriner** [comment]
It seems maybe my example is old and I am trying now to just use the doc and so I removed the stuff from the example O365-iOS-Microsoft-Graph-Connect and now I am just trying to get it working very basic.  I am still getting this error and I don't understand why as I see the file is there and also again it is pointing to Mac for some reason even though I did not include the Mac version of the framework.
/Carthage/Build/Mac/MSAL.framework/Headers/MSAL.h:51:9: 'MSAL/MSALWebviewType.h' file not found

**Comment by chrisriner** [comment]
I have it working now.  It seems the old version of the app had an entry for the frameworks search path and for some reason the new frameworks search path I was adding to the existing one was not working and I had to go back and remove and then readd the old one and it now works.  I just had to guess at this issue.
