### ISSUE TITLE
MSAL iOS B2C login cache is not saved. we use custom policy for sign-in and change password. after successful signing change password policy again asking for user credentials  

### ISSUE THREAD

**Issue by CA-hub** [AzureAD/microsoft-authentication-library-for-objc#455]

**Comment by oldalton** [comment]
Thanks for reporting this issue. If I understand correctly, everything works until user changes their password? If that's the case, does password change policy also revoke the refresh token?

**Comment by CA-hub** [comment]
It's not about refresh token getting expired. we have two custom policies  1. Sign-in policy 2.chage password policy.

**Comment by oldalton** [comment]
Thanks for additional information. What kind of a webview type are you using? If you're using default webview type, it should have cookies from the sign in policy credential prompt, so I agree that you shouldn't need to enter credentials again. Adding @parakhj to confirm on B2C service side.

**Comment by danieldobalian** [comment]
@CA-hub can you capture some logs or use a network tracer to capture a correlation ID? This will help us look into the issue and see what's going on. As Olga mentioned, this is not expected - the cookies from your SiSu policy should allow your user to not need to sign in again for subsequent policy requests.

**Comment by oldalton** [comment]
Closing the issue due to inactivity. Please reopen if needed with additional information requested.

**Comment by AvinashKiran** [comment]
I am facing this issue when the user goes to change password flow, a Web page is opening with login form and after successful authentication change password flow is displaying. 
is there any way to open the change password page directly?
