### ISSUE TITLE
I'm facing issue in forgot password link during more than one time trial.

### ISSUE THREAD

**Issue by Shayila** [AzureAD/microsoft-authentication-library-for-objc#464]
For the first time or after killing the application I'm able to access the forgot password link and it works good.but in second time (clicking the forgot password link) it throws error. below i've mentioned the code used for handling the open url.

 After setting the validateAuthority to False and also including `MSALPublicClientApplication.cancelCurrentWebAuthSession`;
I'm facing the below error.

Using `[MSALPublicClientApplication handleMSALResponse:url];` or `[MSALPublicClientApplication handleMSALResponse:url sourceApplication:UIApplicationOpenURLOptionsSourceApplicationKey];`
i encountered the following error:
**Error Domain=MSALErrorDomain Code=-42402 "(null)" UserInfo={MSALErrorDescriptionKey=Only one interactive session is allowed at a time., MSALCorrelationIDKey=0A8F2159-3E69-4F67-AAAA-71AE2258112F}**

Please provide solution for Forgot Password link issue.

**Comment by oldalton** [comment]
It normally means you called another acquireToken call that didn't complete. Are you getting a completionHandler callback for the first request?

**Comment by oldalton** [comment]
Closing the issue due to inactivity. Please reopen if needed with the additional information.
