### ISSUE TITLE
No token received with acquireToken method (MSALErrorDomain, -42500)

### ISSUE THREAD

**Issue by agcmdl** [AzureAD/microsoft-authentication-library-for-objc#477]
Using this sample: https://github.com/AzureAD/microsoft-authentication-library-for-objc/tree/dev/Samples/ios/SampleAppiOS-Swift and some other similar ones.

1) I have added MSAL library v0.2.3 using cocoapods. Integration worked very well.
2) I have configured the kClientID in Info.plist file and in ViewController.swift file
3) Also I have set the kTenantName to the name provided by our API _<ourTenantName>_.onmicrosoft.com
4) I have set the value of kSignupOrSigninPolicy to the one we have set in our API
5) kScopes was left as is: "https://fabrikamb2c.onmicrosoft.com/demoapi/demo.read"
6) kEndpoint is also left as is: "https://login.microsoftonline.com/tfp/%@/%@"

So, after pressing the "Authorize" button in app, it executes the "authorizationButton" method which in turn executes application.acquireToken(forScopes method.
And that method returns always error: **(MSALErrorDomain, -42500) Authentication response received without expected accessToken**

So the callback is executed, but result is nil and error keeps showing up.

What could cause such issue? What should I check or fix to get this issue resolved?

BTW! The android sample for the same thing (but with MSAL v0.1.1) seems to work with same input data (scopes, policies, tenant names, clientId).

Any hints and help would be greatly appreciated!

Adding verbose logger, gives this log:
```

%@ TID = 1312965 MSAL 0.2.3 iOS 12.1 [2019-03-01 13:56:30 - D9FEAF29-5129-4AA0-A721-117DFD2F5494] Sending network request: (not-nil), headers: (not-nil)
%@ TID = 1313064 MSAL 0.2.3 iOS 12.1 [2019-03-01 13:56:30] session:didReceiveChallenge:completionHandler - nsurlauthenticationmethodservertrust. Host: login.microsoftonline.com. Previous challenge failure count: 0
%@ TID = 1313089 MSAL 0.2.3 iOS 12.1 [2019-03-01 13:56:30 - D9FEAF29-5129-4AA0-A721-117DFD2F5494] Received network response: (not-nil), error (nil)
%@ TID = 1313089 MSAL 0.2.3 iOS 12.1 [2019-03-01 13:56:30 - D9FEAF29-5129-4AA0-A721-117DFD2F5494] Parsed response: (not-nil), error (nil), error domain: (null), error code: 0
%@ TID = 1312965 MSAL 0.2.3 iOS 12.1 [2019-03-01 13:56:37 - D9FEAF29-5129-4AA0-A721-117DFD2F5494] No cached preferred_network for authority
%@ TID = 1312965 MSAL 0.2.3 iOS 12.1 [2019-03-01 13:56:37 - D9FEAF29-5129-4AA0-A721-117DFD2F5494] Sending network request: (not-nil), headers: (not-nil)
%@ TID = 1313090 MSAL 0.2.3 iOS 12.1 [2019-03-01 13:56:38 - D9FEAF29-5129-4AA0-A721-117DFD2F5494] Received network response: (not-nil), error (nil)
%@ TID = 1313090 MSAL 0.2.3 iOS 12.1 [2019-03-01 13:56:38 - D9FEAF29-5129-4AA0-A721-117DFD2F5494] Parsed response: (not-nil), error (nil), error domain: (null), error code: 0
%@ TID = 1312965 MSAL 0.2.3 iOS 12.1 [2019-03-01 13:56:38 - D9FEAF29-5129-4AA0-A721-117DFD2F5494] acquireToken returning with error: (MSALErrorDomain, -42500)
Could not acquire token: Error Domain=MSALErrorDomain Code=-42500 "(null)" UserInfo={MSALErrorDescriptionKey=Authentication response received without expected accessToken}
```

**Comment by oldalton** [comment]
Hi @agcmdl. It probably means that scopes are not recognized by B2C. If it's not recognized, the unrecognized scope will be ignored and no access token would be returned. 

Can you make sure that kScopes `"https://fabrikamb2c.onmicrosoft.com/demoapi/demo.read"` is registered in your tenant?

Thanks.

**Comment by agcmdl** [comment]
Hello @oldalton 

Thanks for your reply!

> Can you make sure that kScopes `"https://fabrikamb2c.onmicrosoft.com/demoapi/demo.read"` is registered in your tenant?

Just to make it clear, Could you please explain, where exactly should I check if scope is registered in tenant?

**Comment by agcmdl** [comment]
Ok 
We got it sorted out. The scope was wrong indeed. With new scope it started to work and tokens are received as expected.
Thanks for the pointing to correct direction!

**Comment by oldalton** [comment]
Thanks for an update. Glad it worked.

**Comment by ajaykeshri** [comment]
I am getting same error, 
What is kScopes basically  . Is this reply Url or something else, please can anyone share the step to create kScopes

**Comment by oldalton** [comment]
@ajaykeshri, is your question B2C or AAD specific (as this thread was about B2C specifically). If it is B2C you can follow this guidance: https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-web-application?tabs=applications

Generic information about scopes can be found here: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent
