### ISSUE TITLE
Device Identifier Not Available

### ISSUE THREAD

**Issue by joeldhenry** [AzureAD/microsoft-authentication-library-for-objc#478]
When i login to an enterprise azure domain, i get the following error:

``` Your sign-in was successful but your admin requires your device to be managed by [Company Name] to access this resource```

My device is registered with the company, but in the request I see that Device Identifier is "Not Available" and Device State is "Unregistered"

I am initialising with my clientID & Authority and then get AquireTokenForScopes using the current user & authority, but cant see where the DeviceID gets initialised or passed as a parameter

**Comment by oldalton** [comment]
Hi @joeldhenry. Which type of the webview are you using in your app? And when you're saying your device is registered, do you mean it's MDM enrolled?

**Comment by oldalton** [comment]
Closing the issue due to inactivity. Please reopen if needed.

**Comment by mckmoffatt** [comment]
I am seeing this same problem and have no resolution.

**Comment by oldalton** [comment]
@mckmoffatt - same question, which webview type are you using?

**Comment by mckmoffatt** [comment]
More specifically, I'm trying to use AAD to log into Yammer and I get this message. When I look at the details, it shows that my device identifier is missing.
![image](https://user-images.githubusercontent.com/57155180/94717223-e0ba7280-0304-11eb-8335-eb5819dc83b9.png)
