### ISSUE TITLE
Xcode Analyzer issues

### ISSUE THREAD

**Issue by paulnelsontx** [AzureAD/microsoft-authentication-library-for-objc#486]
There are four analyzer issues that should be fixed:

Showing All Issues
Analyze /Users/nelson/Developer/iOS/active-directory-ios-swift-native-v2-master/Pods/MSAL/MSAL/src/instance/MSALAuthority.m normal x86_64 (in target: MSAL)
    cd /Users/nelson/Developer/iOS/active-directory-ios-swift-native-v2-master/Pods
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu11 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/nelson/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/nelson/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -fmodule-name=MSAL -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DPOD_CONFIGURATION_DEBUG=1 -DDEBUG=1 -DCOCOAPODS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=10.0 -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -fobjc-abi-version=2 -fobjc-legacy-dispatch -D__clang_analyzer__ -Xclang -analyzer-output=plist-multi-file -Xclang -analyzer-config -Xclang path-diagnostics-alternate=true -Xclang -analyzer-config -Xclang report-in-main-source-file=true -Xclang -analyzer-config -Xclang osx.NumberObjectConversion:Pedantic=true -Xclang -analyzer-checker -Xclang security.insecureAPI.UncheckedReturn -Xclang -analyzer-checker -Xclang security.insecureAPI.getpw -Xclang -analyzer-checker -Xclang security.insecureAPI.gets -Xclang -analyzer-checker -Xclang security.insecureAPI.mkstemp -Xclang -analyzer-checker -Xclang security.insecureAPI.mktemp -Xclang -analyzer-disable-checker -Xclang security.insecureAPI.rand -Xclang -analyzer-disable-checker -Xclang security.insecureAPI.strcpy -Xclang -analyzer-checker -Xclang security.insecureAPI.vfork -iquote /Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MSAL.build/MSAL-generated-files.hmap -I/Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MSAL.build/MSAL-own-target-headers.hmap -I/Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MSAL.build/MSAL-all-non-framework-target-headers.hmap -ivfsoverlay /Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MSAL.build/all-product-headers.yaml -iquote /Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MSAL.build/MSAL-project-headers.hmap -I/Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Products/Debug-iphonesimulator/MSAL/include -I/Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MSAL.build/DerivedSources/x86_64 -I/Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MSAL.build/DerivedSources -F/Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Products/Debug-iphonesimulator/MSAL -include /Users/nelson/Developer/iOS/active-directory-ios-swift-native-v2-master/Pods/Target\ Support\ Files/MSAL/MSAL-prefix.pch -MMD -MT dependencies -MF /Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MSAL.build/StaticAnalyzer/Pods/MSAL/normal/x86_64/MSALAuthority.d --analyze /Users/nelson/Developer/iOS/active-directory-ios-swift-native-v2-master/Pods/MSAL/MSAL/src/instance/MSALAuthority.m -o /Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MSAL.build/StaticAnalyzer/Pods/MSAL/normal/x86_64/MSALAuthority.plist

/Users/nelson/Developer/iOS/active-directory-ios-swift-native-v2-master/Pods/MSAL/MSAL/src/instance/MSALAuthority.m:51:5: warning: nil returned from a method that is expected to return a non-null value
    return nil;
    ^~~~~~~~~~
1 warning generated.

Analyze /Users/nelson/Developer/iOS/active-directory-ios-swift-native-v2-master/Pods/MSAL/MSAL/src/MSALErrorConverter.m normal x86_64 (in target: MSAL)
    cd /Users/nelson/Developer/iOS/active-directory-ios-swift-native-v2-master/Pods
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu11 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/nelson/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/nelson/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -fmodule-name=MSAL -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DPOD_CONFIGURATION_DEBUG=1 -DDEBUG=1 -DCOCOAPODS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=10.0 -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -fobjc-abi-version=2 -fobjc-legacy-dispatch -D__clang_analyzer__ -Xclang -analyzer-output=plist-multi-file -Xclang -analyzer-config -Xclang path-diagnostics-alternate=true -Xclang -analyzer-config -Xclang report-in-main-source-file=true -Xclang -analyzer-config -Xclang osx.NumberObjectConversion:Pedantic=true -Xclang -analyzer-checker -Xclang security.insecureAPI.UncheckedReturn -Xclang -analyzer-checker -Xclang security.insecureAPI.getpw -Xclang -analyzer-checker -Xclang security.insecureAPI.gets -Xclang -analyzer-checker -Xclang security.insecureAPI.mkstemp -Xclang -analyzer-checker -Xclang security.insecureAPI.mktemp -Xclang -analyzer-disable-checker -Xclang security.insecureAPI.rand -Xclang -analyzer-disable-checker -Xclang security.insecureAPI.strcpy -Xclang -analyzer-checker -Xclang security.insecureAPI.vfork -iquote /Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MSAL.build/MSAL-generated-files.hmap -I/Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MSAL.build/MSAL-own-target-headers.hmap -I/Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MSAL.build/MSAL-all-non-framework-target-headers.hmap -ivfsoverlay /Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MSAL.build/all-product-headers.yaml -iquote /Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MSAL.build/MSAL-project-headers.hmap -I/Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Products/Debug-iphonesimulator/MSAL/include -I/Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MSAL.build/DerivedSources/x86_64 -I/Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MSAL.build/DerivedSources -F/Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Products/Debug-iphonesimulator/MSAL -include /Users/nelson/Developer/iOS/active-directory-ios-swift-native-v2-master/Pods/Target\ Support\ Files/MSAL/MSAL-prefix.pch -MMD -MT dependencies -MF /Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MSAL.build/StaticAnalyzer/Pods/MSAL/normal/x86_64/MSALErrorConverter.d --analyze /Users/nelson/Developer/iOS/active-directory-ios-swift-native-v2-master/Pods/MSAL/MSAL/src/MSALErrorConverter.m -o /Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MSAL.build/StaticAnalyzer/Pods/MSAL/normal/x86_64/MSALErrorConverter.plist

/Users/nelson/Developer/iOS/active-directory-ios-swift-native-v2-master/Pods/MSAL/MSAL/src/MSALErrorConverter.m:129:13: warning: Converting a pointer value of type 'NSNumber *' to a primitive boolean value; instead, either compare the pointer to nil or call -boolValue
        if (mappedErrorCode)
        ~~~~^~~~~~~~~~~~~~~~
/Users/nelson/Developer/iOS/active-directory-ios-swift-native-v2-master/Pods/MSAL/MSAL/src/MSALErrorConverter.m:152:12: warning: nil passed to a callee that requires a non-null 1st parameter
    return [NSError errorWithDomain:msalDomain code:msalErrorCode userInfo:msalUserInfo];
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 warnings generated.

Analyze /Users/nelson/Developer/iOS/active-directory-ios-swift-native-v2-master/Pods/MSAL/MSAL/IdentityCore/IdentityCore/src/oauth2/aad_v2/MSIDAADV2Oauth2Factory.m normal x86_64 (in target: MSAL)
    cd /Users/nelson/Developer/iOS/active-directory-ios-swift-native-v2-master/Pods
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu11 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/nelson/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/nelson/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -fmodule-name=MSAL -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DPOD_CONFIGURATION_DEBUG=1 -DDEBUG=1 -DCOCOAPODS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=10.0 -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -fobjc-abi-version=2 -fobjc-legacy-dispatch -D__clang_analyzer__ -Xclang -analyzer-output=plist-multi-file -Xclang -analyzer-config -Xclang path-diagnostics-alternate=true -Xclang -analyzer-config -Xclang report-in-main-source-file=true -Xclang -analyzer-config -Xclang osx.NumberObjectConversion:Pedantic=true -Xclang -analyzer-checker -Xclang security.insecureAPI.UncheckedReturn -Xclang -analyzer-checker -Xclang security.insecureAPI.getpw -Xclang -analyzer-checker -Xclang security.insecureAPI.gets -Xclang -analyzer-checker -Xclang security.insecureAPI.mkstemp -Xclang -analyzer-checker -Xclang security.insecureAPI.mktemp -Xclang -analyzer-disable-checker -Xclang security.insecureAPI.rand -Xclang -analyzer-disable-checker -Xclang security.insecureAPI.strcpy -Xclang -analyzer-checker -Xclang security.insecureAPI.vfork -iquote /Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MSAL.build/MSAL-generated-files.hmap -I/Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MSAL.build/MSAL-own-target-headers.hmap -I/Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MSAL.build/MSAL-all-non-framework-target-headers.hmap -ivfsoverlay /Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MSAL.build/all-product-headers.yaml -iquote /Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MSAL.build/MSAL-project-headers.hmap -I/Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Products/Debug-iphonesimulator/MSAL/include -I/Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MSAL.build/DerivedSources/x86_64 -I/Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MSAL.build/DerivedSources -F/Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Products/Debug-iphonesimulator/MSAL -include /Users/nelson/Developer/iOS/active-directory-ios-swift-native-v2-master/Pods/Target\ Support\ Files/MSAL/MSAL-prefix.pch -MMD -MT dependencies -MF /Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MSAL.build/StaticAnalyzer/Pods/MSAL/normal/x86_64/MSIDAADV2Oauth2Factory.d --analyze /Users/nelson/Developer/iOS/active-directory-ios-swift-native-v2-master/Pods/MSAL/MSAL/IdentityCore/IdentityCore/src/oauth2/aad_v2/MSIDAADV2Oauth2Factory.m -o /Users/nelson/Library/Developer/Xcode/DerivedData/MSALiOS-blfseepmylxksldrlxhtvvonplly/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MSAL.build/StaticAnalyzer/Pods/MSAL/normal/x86_64/MSIDAADV2Oauth2Factory.plist

/Users/nelson/Developer/iOS/active-directory-ios-swift-native-v2-master/Pods/MSAL/MSAL/IdentityCore/IdentityCore/src/oauth2/aad_v2/MSIDAADV2Oauth2Factory.m:93:20: warning: Potential null dereference.  According to coding standards in 'Creating and Returning NSError Objects' the parameter may be null
            *error = MSIDCreateError(MSIDOAuthErrorDomain,
            ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.

**Comment by oldalton** [comment]
Addressed in #490
