### ISSUE TITLE
get "newUser" from B2C 

### ISSUE THREAD

**Issue by yazoonic** [AzureAD/microsoft-authentication-library-for-objc#511]
B2C application can claim if the user is new wit this flag "newUser", can you add it to MSAL library for iOS/Android  so we can fetch this data? or is there any other way to fetch it?

**Comment by oldalton** [comment]
@yazoonic, can you provide more information on the "newUser" flag? Is this part of the id token?
@danieldobalian FYI

**Comment by yazoonic** [comment]
Yes @oldalton, I tested that and I parsed the token using jwt.ms, it has "newUser" flag when the user sign up for the first time. 
in Azure B2c --> application claims -->User is new:  True, if the user has just signed-up for your application. 

in token, it will come as newUser = true ( if user is new )

**Comment by oldalton** [comment]
Thanks for the info. We're currently working on improving our accounts API and exposing additional id token claims there. You can see an in progress PR here: https://github.com/AzureAD/microsoft-authentication-library-for-objc/pull/510. @jasoncoolmax can provide more info.

**Comment by jasoncoolmax** [comment]
Hi @yazoonic, the class`MSALResult` has the field called `NSString *idToken`, which is the raw id token containing the field you mentioned (assuming "newUser" flag is in the id token). If you decode the id token, you will get what you want.

However, we are making some improvements to provide an easy way to fetch the claims in the id token. such that you don't have to decode the id token. Hopefully that will solve your issue :)

**Comment by oldalton** [comment]
Improved in the latest MSAL version. Please try it out and reopen the issue if needed.
