### ISSUE TITLE
Accessing EWS via MSAL

### ISSUE THREAD

**Issue by dsanghan** [AzureAD/microsoft-authentication-library-for-objc#518]
When I try to request `https://outlook.office365.com/EWS.AccessAsUser.All` scope for accessing EWS using OAuth2, I'm getting the following:

```
Error Domain=MSALErrorDomain Code=-42005 "(null)" UserInfo={MSALErrorDescriptionKey=The provided resource value for the input parameter 'scope' is not valid., MSALOAuthErrorKey=invalid_scope}
```

I've added the correct API permissions to my V2 Azure AD App Registration:

<img width="1053" alt="Screen Shot 2019-04-16 at 12 00 28 PM" src="https://user-images.githubusercontent.com/6698354/56187182-7d208480-603f-11e9-8fcf-2c66ef72b319.png">

What's the correct way to get access to this scope?

I do manage to get an access token if I change the scope to only `EWS.AccessAsUser.All` but that doesn't give me the correct audience in the ID JWT. Without the `https://outlook.office365.com` my audience is my tenant ID, which does not give access to external O365 accounts with EWS. 

When I try to use the access token with the incorrect audience, I get a 403 from EWS. The NSURLSessionDataTask does not have an NSError set in response, instead the NSURLHTTPResponse shows:

```
<NSHTTPURLResponse: 0x2837d3160> { URL: https://outlook.office365.com/EWS/Exchange.asmx } { Status Code: 403, Headers {
    "Cache-Control" =     (
        private
    );
    "Content-Length" =     (
        0
    );
    Date =     (
        "Tue, 16 Apr 2019 06:52:21 GMT"
    );
    Server =     (
        "Microsoft-IIS/10.0"
    );
    "Set-Cookie" =     (
        "exchangecookie=0f81c4d6ad724e9eb2c92aef78b70618; expires=Thu, 16-Apr-2020 06:52:21 GMT; path=/; HttpOnly"
    );
    "X-AspNet-Version" =     (
        "4.0.30319"
    );
    "X-BEServer" =     (
        MA1PR01MB2730
    );
    "X-BackEndHttpStatus" =     (
        403,
        403
    );
    "X-BeSku" =     (
        WCS5
    );
    "X-CalculatedBETarget" =     (
        "MA1PR01MB2730.INDPRD01.PROD.OUTLOOK.COM"
    );
    "X-CalculatedFETarget" =     (
        "MA1PR01CU006.internal.outlook.com"
    );
    "X-DiagInfo" =     (
        MA1PR01MB2730
    );
    "X-FEProxyInfo" =     (
        "MA1PR01CA0165.INDPRD01.PROD.OUTLOOK.COM"
    );
    "X-FEServer" =     (
        MA1PR01CA0165,
        BMXPR01CA0008
    );
    "X-Powered-By" =     (
        "ASP.NET"
    );
    "X-RUM-Validated" =     (
        1
    );
    "request-id" =     (
        "87982b1b-ee20-4906-83c6-3689b64a7bd0"
    );
    "x-ms-appId" =     (
        0000000044264486
    );
} }
```

So clearly, it's internally refusing access without the correct audience.

**Comment by antrix1989** [comment]
Please capture the [network trace ](https://github.com/AzureAD/azure-activedirectory-library-for-objc#network-traces) and send it to sedemche@microsoft.com. Make sure to remove passwords from the network trace prior to sending.

**Comment by guidedways** [comment]
Any update on the issue? 

I’m trying to use MSAL (instead of ADAL) to authenticate my app in order to connect to EWS calendaring endpoints (managing the users calendars), which the app has been managing successfully using Basic authentication and auto discovery in the past. 

Am I at the right place?

**Comment by dsanghan** [comment]
@antrix1989 @guidedways 

There is a confirmed issue with personal accounts (outlook.com, etc):
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1274

Office365 / Exchange online accounts are working fine.

**Comment by guidedways** [comment]
@dsanghan thanks! Looks like a dead-end, so is this something that we can't support without moving away from EWS?

**Comment by guidedways** [comment]
@ahmedwasiullah switching to using Graph is the only way
