### ISSUE TITLE
 Attempt to present <UIViewController> on <SFAuthenticationViewController> whose view is not in the window hierarchy!

### ISSUE THREAD

**Issue by wham** [AzureAD/microsoft-authentication-library-for-objc#521]
I have a view controller `SignInViewController` and want to perform segue `showHome` when `acquireToken()`succeeds. This segue shows another view controller `HomeViewController`.

In `SignInViewController`:

```
application.acquireToken(forScopes: kScopes) { (result, error) in
    if  error == nil {
        self.performSegue(withIdentifier: "showHome", sender: self)
    }
}
```

The segue is not performed. There is an error `Attempt to present <UIViewController: 0x7fb5faf3e4f0> on <SFAuthenticationViewController: 0x7fb5fc018e00> whose view is not in the window hierarchy!`

I worked around this by wrapping `performSegue()` into `DispatchQueue.main.asyncAfter(deadline: .now() + 1.0)` but the user experience is not good - the delay is visible.

**Example app:** https://github.com/wham/active-directory-b2c-ios-swift-native-msal/tree/perform-segue

**Comment by antrix1989** [comment]
Hi @wham, thanks for reporting this problem.

I believe this happens because of the completion block of ASWebAuthenticationSession is being called before the webview of ASWebAuthenticationSession is completely dismissed.

I've opened a radar on this.

**Comment by antrix1989** [comment]
Apple has confirmed it is their issue. As a workaround you could defer your segue until `viewDidAppear(_:)` is called:

1. Add a state tracking Boolean to your view controller.

```
class ViewController: UIViewController {
    …
    var isSeguePending: Bool = false
    …
}
```

2. In your completion handler, set that Boolean:

```
application.acquireToken(forScopes: kScopes) { (result, error) in
    if  error == nil {
        self.isSeguePending = true
    }
}
```

3. In your `viewDidAppear(_:)` method, run the segue if requested:

```
override func viewDidAppear(_ animated: Bool) 
{
    super.viewWillAppear(animated)

    if self.seguePending {
        self.seguePending = false
        self.performSegue(withIdentifier: "showHome", sender: self)
    }
}
```
