### ISSUE TITLE
"SSO" from Intune Company Portal app

### ISSUE THREAD

**Issue by oyvind-hauge** [AzureAD/microsoft-authentication-library-for-objc#525]
Is it possible to share access token from the Intune Company Portal app to a third party MSAL enabled iOS app? I'd expect to be able to `aquireTokenSilent` in my app after being authenticated in the Company Portal app. My app is using the default **com.microsoft.adalcache** keychain access group to store/look for tokens.

**Comment by antrix1989** [comment]
It is not possible since keychain sharing in iOS is enabled only for the applications with the same team ID:

> Xcode automatically prefixes keychain groups with your team ID. This ensures that your groups are specific to your development team.

See more info [here](https://developer.apple.com/documentation/security/keychain_services/keychain_items/sharing_access_to_keychain_items_among_a_collection_of_apps?language=objc).

**Comment by oyvind-hauge** [comment]
Hi @antrix1989! That's too bad, but I do understand why this is not possible now. Thanks for your quick reply.

**Comment by natuamol** [comment]
adding dummy comment to verify if the close event gets registered.
