### ISSUE TITLE
Grouped authentication for multiple different resources

### ISSUE THREAD

**Issue by Brynjulf** [AzureAD/microsoft-authentication-library-for-objc#549]
Hello,

We are currently using ADAL in production and are typically using at least 3 different resources with our apps (eg. a common API, a client specific API and AAD) in which we authenticate against in one login at the start of the application. With MSAL you would authenticate separately against all these resources.

Is there currently a way to authenticate to all the different resources in one go, to help us avoid redesigning our application flow or is this something that you have in your roadmap?

**Comment by oldalton** [comment]
Hi @Brynjulf. Thanks for the question. Can you please clarify how are you authenticating in one login using ADAL or provide some sample code? MSAL provides very similar API surface and functionality, so I'm wondering why there's a difference. 

Depending on which resource/clientId you're using, you can do one of the following:

1. Acquire token interactively for the first resource. After first token acquisition, call acquireTokenSilent twice for resource nr 2 and resource nr 3. 
2. If user needs to consent to all 3 resources, and you would like to do it once, you can pass scopes for resource 1 in your acquireToken call, and scopes for resource 2 and resource 3 in the extraScopesToConsent parameter. AcquireToken call would then return access token for resource 1, you'd need to call acquireTokenSilent for resource 2 and 3, but user wouldn't need to do any interaction.

**Comment by Brynjulf** [comment]
@oldalton, my mistake, I was thinking of consent for all resources on first login. The last suggestion works like a charm.

**Comment by oldalton** [comment]
Great!
