### ISSUE TITLE
MSALErrorInternal error mapping

### ISSUE THREAD

**Issue by unpluggedk** [AzureAD/microsoft-authentication-library-for-objc#582]
https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/458/files/7a387a0e5258c4700cdb671d5de535e524d58f79#diff-7087f43f9332800e57f71222840ab9c5

context:
we should either add a new key to MSALInternalError, which we will map to MSIDErrorInternal or avoid using MSIDErrorInternal and specify a concrete error instead (btw, we already using MSIDErrorInternal in few other places, so we will need to update them too).

**Comment by oldalton** [comment]
Should be fixed.
