### ISSUE TITLE
Customer issue: login into O365 is trying to open in Safari

### ISSUE THREAD

**Issue by youlianqi** [AzureAD/microsoft-authentication-library-for-objc#589]
Our client integration O365 about half a year. Recently, a customer complaint that "When you login into the office 365 integration from the mobile app is trying to open in Safari."  Do you know what's problem of her. Maybe some permissions is not granted?? Our app is enterprise application.

**Comment by oldalton** [comment]
Hi. When you say it opens in Safari, do you mean it shows a Safari like view inside your app? Which MSAL version is your app using? Thanks.

**Comment by youlianqi** [comment]
I using MSAL 2.0. It seems would open in Safari app at last in this customer.

**Comment by manojkatragadda16** [comment]
Any update on it? Safari is blocked in our 0365 as well. We are not able to get auth token using MSAL

**Comment by oldalton** [comment]
Hi, you can change MSAL to use WKWebView instead of Safari (ASWebAuthenticationSession). See here: https://github.com/AzureAD/microsoft-authentication-library-for-objc/wiki/Customizing-Browsers-and-WebViews
