### ISSUE TITLE
Refresh token or authorization code: For passing to server

### ISSUE THREAD

**Issue by crspybits** [AzureAD/microsoft-authentication-library-for-objc#618]
I've seen that getting a refresh token directly isn't supported yet (https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/231). I'm wondering how I can support the use case where a long-lived token (a refresh token  or an authorization code) needs to be sent to a server-- so the server can do operations on behalf of the user. In my case, these are to provide the user ongoing OneDrive access on the server.

Thoughts?
Thanks,
Chris.

**Comment by oldalton** [comment]
Hi. I don't think you should be passing refresh token or authorization code to your service. 

As stated in OAuth2 spec (https://tools.ietf.org/html/rfc6749#section-10.4):

```
Refresh tokens MUST be kept confidential in transit and storage, and
   shared only among the authorization server and the client to whom the
   refresh tokens were issued.  The authorization server MUST maintain
   the binding between a refresh token and the client to whom it was
   issued.  Refresh tokens MUST only be transmitted using TLS as
   described in Section 1.6 with server authentication as defined by
   [RFC2818].
```

Please take a look at a slightly different way to implement it with the On-behalf-of flow: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow

**Comment by crspybits** [comment]
Thanks for the info on the on-behalf-of flow-- that looks like what I need.
