### ISSUE TITLE
Failure to upload to App Store

### ISSUE THREAD

**Issue by guidedways** [AzureAD/microsoft-authentication-library-for-objc#626]
Our bundle ID for the app is `com.company.ourappv3` and for some reason this won't work when added to URL types as required by MSAL. We get this when uploading the app to the app store:

`ERROR ITMS-90158: "The following URL schemes found in your app are not in the correct format: [msauth.com.company.ourappv3://auth]. URL schemes need to begin with an alphabetic character, and be comprised of alphanumeric characters, the period, the hyphen or the plus sign only. Please see RFC1738 for more detail."`

Any idea what we need to do to get this to work?

**Comment by oldalton** [comment]
Since this issue was closed, I assume it got resolved.
