### ISSUE TITLE
OKTA / Duo phone authentication with MSAL?

### ISSUE THREAD

**Issue by guidedways** [AzureAD/microsoft-authentication-library-for-objc#627]
We've been using AutoDiscovery in the past and have just recently added MSAL to our project. I was under the impression that all flavors of Office 365 authentication would magically work.

However one of our beta testers has just written back saying "Sorry, it did not link to our OKTA portal and then it would have had to link to our DUO phone authenication."

I'm not sure what that means. What do we have to do to make this work with their Office 365 account?

**Comment by oldalton** [comment]
Hi @guidedways. I'm not aware of any limitations related to MSAL with Okta. As far as MSAL is concerned, it's just a federated auth scenario and it should work. 

However, I'd like to look a bit closer into it. Do you have any additional information from the tester? e.g. correlationId of the failed request or MSAL log? Thanks.

**Comment by guidedways** [comment]
Yes it was apparent he was doing something wrong after we obtained the logs from them. They've now confirmed there are no issues and it's working as it should. I'm super thrilled, given we had no way of testing this out otherwise.
