### ISSUE TITLE
Fatal Build Errors for macOS release (0.5.0)

### ISSUE THREAD

**Issue by SteveDCronin** [AzureAD/microsoft-authentication-library-for-objc#628]
I am using macOS 10.14.5 and Xcode 10.3
I have downloaded the zip file on the announcement for macOS support (0.5.0).

I cannot build MSAL (Mac framework) nor the MSAL Test App (Mac).
I get a number of:
/Users/steve/Documents/.../Microsoft/microsoft-authentication-library-for-objc-0.5.0/MSAL/IdentityCore/IdentityCore/src/logger/MSIDLogger.m:83:9: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior

Please advise as to how best to move forward.

**Comment by guidedways** [comment]
@SteveDCronin instead of downloading the zip, clone the git library to disk and then run `git submodule update --init` inside of it, that should work. I've had no issues when following these steps.

**Comment by SteveDCronin** [comment]
guidedways - Thanks!  Confirm that after following above I can build both MSAL (Mac framework) and the MSAL Test App (Mac) without errors.
