### ISSUE TITLE
macOS: silent auth requests frequently fail after mac wakes up

### ISSUE THREAD

**Issue by guidedways** [AzureAD/microsoft-authentication-library-for-objc#638]
We're got MSAL running in a beta version of our app. So far so good. However we're receiving frequent complaints of the same thing over and over: when a user's mac wakes up after a sleep, our app frequently fails to connect to their Office 365 account. 

Upon closer inspection of their logs, it does seem as though silent authentication requests are failing with the following error:

`Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={NSLocalizedDescription=The Internet connection appears to be offline., NSErrorFailingURLStringKey=https://login.microsoftonline.com/..."`

However, internet connection is certainly not offline as otherwise our requests wouldn't have gone through - the app checks for a valid connection before submitting a request. This is what we're doing:

1. Construct a `NSMutableRequest` instance with the actual request (PUT / GET etc)
2. Call `acquireTokenSilentWithParameters` on each request in order to obtain a refreshed token in case its expired. -→ *failing here*
3. Call resume on a `NSURLSession`

Could it be that `acquireTokenSilentWithParameters` is relying on some cached state which may be failing on the mac frequently? Or could the internet really have died abruptly and we need to simply retry again? Other than inserting `acquireTokenSilentWithParameters` into our request creation workflow, we haven't made any other changes to the app and have never seen this problem come up before.

It's going to be difficult to obtain more detailed logs from the users as they only share crash logs + stuff the app was doing around that time.

**Comment by guidedways** [comment]
I *think* I know what's going on. The completion block on `acquireTokenSilentWithParameters` should be called on the main thread (I think I read that in the documentation), but it seems in case there's a network failure down the line, such as when the internet connection drops when the lid is closed on a laptop, the completion block _may_ actually be called on a different thread. This may be why I'm seeing this odd behavior and a new crash we've never experienced before. Either way, I'm now dispatching the response manually back onto the main thread to in case, and will report back if that has put an end to these error reports.

**Comment by guidedways** [comment]
Okay that's it, the completion block seems to be called on some background thread. The documentation should make this clear and / or call the completion on the main thread (like many 3rd party libraries do).

**Comment by oldalton** [comment]
Thanks for the feedback. I've added some documentation here: https://github.com/AzureAD/microsoft-authentication-library-for-objc/pull/647
