### ISSUE TITLE
Using example from web, currentAccount() method returns nil after sign in

### ISSUE THREAD

**Issue by crspybits** [AzureAD/microsoft-authentication-library-for-objc#653]
I am using the example in https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-ios and all looks good in my example app-- except that after a sign in the method currentAccount() returns nil. I'm using iOS 12 and this is happening both on the simulator and on an actual iPhone. I'm using v0.5.0 of MSAL.

 Suggestions?

Thanks,
Chris.

**Comment by oldalton** [comment]
Did you configure keychain access groups for your project? Can you confirm that you completed this step: add a new keychain group to your project Capabilities com.microsoft.adalcache.

**Comment by crspybits** [comment]
That has fixed it. Thanks! Somehow I missed that step in the instructions.
