### ISSUE TITLE
ios 13.1 beta and MSAL 0.5

### ISSUE THREAD

**Issue by kvenkata1974** [AzureAD/microsoft-authentication-library-for-objc#655]
Hi 
In ios 13.1 beta and MSAL 0.5, unable to reset or login again with another user id.

So if I logout, it goes to the AZURE login page and gets redirected to the app straight away without allowing for the user to login again.

It works with MSAL 0.4.3.

Cheers
Karthik

**Comment by oldalton** [comment]
@kvenkata1974, do you mean logout from web UI? Or logout through MSAL "removeAccount" API? Thanks.

**Comment by kvenkata1974** [comment]
Hi,
I logout through MSAL using removeAccount API and then go back the login
page. It logs in back straight away with the current user.

This works fine with MSAL 0.4 where in the login page is shown and a new
user can login.

Cheers
Karthik

**Comment by oldalton** [comment]
@kvenkata1974, latest MSAL have changed the default promptType. Previously, MSAL was always sending prompt=select_account by default. Latest versions are not doing that. If you would like to revert to the previous behavior, you can change prompt type yourself. See here: https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALInteractiveTokenParameters.html#/c:objc(cs)MSALInteractiveTokenParameters(py)promptType

**Comment by oldalton** [comment]
Please update to the latest MSAL version that supports iOS 13 (0.7.0+).
