### ISSUE TITLE
Getting silent token even after password change in AD

### ISSUE THREAD

**Issue by suresh777** [AzureAD/microsoft-authentication-library-for-objc#658]
Actually i am checking changing password feature. I changed my password in azure directory, After that i tried silent token it is providing token. But it should throw some error like authentication failed. Is it expected behaviour?

**Comment by oldalton** [comment]
Hi, password change doesn't invalidate access tokens. It only invalidates refresh tokens. Therefore, wait for some time after password change (depending on access token expiry timeframe, by default it's 1 hour) and check if you are getting the InteractionRequired error then.

**Comment by suresh777** [comment]
I am getting same response in both cases(user interaction login and silent login). Once i get silent login accesstoken i am replacing  existing accesstoken with new token. After that i am using this token for further api calls.

**Comment by oldalton** [comment]
Closing the issue. Please reopen if you have additional questions.
