### ISSUE TITLE
MSAL 0.6.0 login in fail in iOS 13.1 

### ISSUE THREAD

**Issue by youlianqi** [AzureAD/microsoft-authentication-library-for-objc#660]
I update MSAL to 0.6.0 and integrate it into our project. But it sign in fail. 
The error message is "error:Error Domain=com.apple.AuthenticationServices.WebAuthenticationSession Code=2 "Cannot start ASWebAuthenticationSession without providing presentation context. Set presentationContextProvider before calling -start." UserInfo={NSDebugDescription=Cannot start ASWebAuthenticationSession without providing presentation context. Set presentationContextProvider before calling -start. "

I have used new MSALInteractiveTokenParameters as below
MSALInteractiveTokenParameters *interactiveParams = [[MSALInteractiveTokenParameters alloc] initWithScopes:scopes webviewParameters:webviewParameters];

**Comment by youlianqi** [comment]
After I modify MSAL source code as below,  MSAL work fine in iOS 13.1. 

#ifdef __IPHONE_13_0
@interface MSIDAuthenticationSession()
<ASWebAuthenticationPresentationContextProviding>
@end
#endif

@implementation MSIDAuthenticationSession{
UIViewController *_parentViewController;
}

- (void)startWithCompletionHandler:(MSIDWebUICompletionHandler)completionHandler
{
    if (!completionHandler)
    {
        MSID_LOG_WITH_CTX(MSIDLogLevelWarning,_context, @"CompletionHandler cannot be nil for interactive session.");
        return;
    }

#if !MSID_EXCLUDE_WEBKIT

    [[MSIDBackgroundTaskManager sharedInstance] startOperationWithType:MSIDBackgroundTaskTypeInteractiveRequest];

    NSError *error = nil;

    if (@available(iOS 11.0, *))
    {
        _telemetryRequestId = [_context telemetryRequestId];
        [[MSIDTelemetry sharedInstance] startEvent:_telemetryRequestId eventName:MSID_TELEMETRY_EVENT_UI_EVENT];
        _telemetryEvent = [[MSIDTelemetryUIEvent alloc] initWithName:MSID_TELEMETRY_EVENT_UI_EVENT
                                                             context:_context];

        _completionHandler = [completionHandler copy];

        void (^authCompletion)(NSURL *, NSError *) = ^void(NSURL *callbackURL, NSError *authError)
        {
            if ([self isErrorCodeCanceledLogin:authError])
            {
                authError = MSIDCreateError(MSIDErrorDomain, MSIDErrorUserCancel, @"User cancelled the authorization session.", nil, nil, nil, _context.correlationId, nil);
                [_telemetryEvent setIsCancelled:YES];
            }

            [[MSIDTelemetry sharedInstance] stopEvent:_telemetryRequestId event:_telemetryEvent];

            [self notifyEndWebAuthWithURL:callbackURL error:authError];
            _completionHandler(callbackURL, authError);
        };

        [MSIDNotifications notifyWebAuthDidStartLoad:_startURL userInfo:nil];

        if (@available(iOS 12.0, *))
        {
            _webAuthSession = [[ASWebAuthenticationSession alloc] initWithURL:_startURL
                                                            callbackURLScheme:_callbackURLScheme
                                                            completionHandler:authCompletion];

#ifdef __IPHONE_13_0
            if (@available(iOS 13.0, *)) {
                _webAuthSession.presentationContextProvider = self;
            }
#endif
            if ([_webAuthSession start]) return;
        }
        else
        {
            _authSession = [[SFAuthenticationSession alloc] initWithURL:_startURL
                                                      callbackURLScheme:_callbackURLScheme
                                                      completionHandler:authCompletion];
            if ([_authSession start]) return;
        }

        error = MSIDCreateError(MSIDErrorDomain, MSIDErrorInteractiveSessionStartFailure, @"Failed to start an interactive session", nil, nil, nil, _context.correlationId, nil);
    }
    else
    {
        error = MSIDCreateError(MSIDErrorDomain, MSIDErrorUnsupportedFunctionality, @"SFAuthenticationSession/ASWebAuthenticationSession is not available for iOS 10 and older.", nil, nil, nil, _context.correlationId, nil);
    }

    [self notifyEndWebAuthWithURL:nil error:error];
    completionHandler(nil, error);
#endif
}

#ifdef __IPHONE_13_0
- (ASPresentationAnchor)presentationAnchorForWebAuthenticationSession:(ASWebAuthenticationSession *)session
API_AVAILABLE(ios(12.0)){
    return _parentViewController.view.window;
}
#endif

**Comment by youlianqi** [comment]
`    if ([NSThread isMainThread])
    {
        [s_currentSession.webviewController startWithCompletionHandler:startCompletionBlock];
    }
    else
    {
        dispatch_async(dispatch_get_main_queue(), ^{
            [s_currentSession.webviewController startWithCompletionHandler:startCompletionBlock];
        });
    }`

**Comment by oldalton** [comment]
@youlianqi, thanks for reporting this. We'll have it fixed in our 0.7.0 release.

**Comment by hendrik-dev** [comment]
We are experiencing the same error with the beta versions of iOS 13. When will MSAL version 0.7.0 be released?

The Apple Special Event is tomorrow and the public release of iOS 13 is getting closer. We would like to upgrade our app to the fixed version of MSAL, so that we don't have a broken version of our app in the App Store when iOS 13 goes public.

**Comment by oldalton** [comment]
@hendrik-dev, @youlianqi, we've released MSAL 0.7.0 here: https://github.com/AzureAD/microsoft-authentication-library-for-objc/releases/tag/0.7.0

See additional info here: https://github.com/AzureAD/microsoft-authentication-library-for-objc/wiki/iOS-13-and-macOS-10.15-support-in-MSAL

Please let me know if you have additional questions or seeing any issues.

**Comment by hendrik-dev** [comment]
@oldalton Thank you, that was fast. The 0.7.0 update indeed fixed the problem for us.

**Comment by youlianqi** [comment]
@oldalton 0.7.0 works well in iOS 13.1, Thanks.
