### ISSUE TITLE
Unable to use scopes with user_impersonation

### ISSUE THREAD

**Issue by scordonnier** [AzureAD/microsoft-authentication-library-for-objc#664]
Hello,

I'm trying to acquire a token and use it with Azure DevOps REST API.

As starting point, I followed your documentation to register a new app with appropriate permissions, then I modified your iOS app sample to get a token with these scopes :

`let parameters = MSALInteractiveTokenParameters(scopes: ["User.Read", "https://app.vssps.visualstudio.com/user_impersonation"])`

When I give my consent, the login screen closes and the following message is printed in the console output :

> TID=10668764 MSAL 0.6.0 iOS Sim 12.4 [2019-09-08 18:54:01 - B21C4AFE-B1A9-4395-87EE-3DCE4CB9E3A7] [MSAL] acquireToken returning with error: (MSALErrorDomain, -50003) Masked(not-null)
App error: Error Domain=MSALErrorDomain Code=-50003 "(null)" UserInfo={MSALDeclinedScopesKey=(
    "https://app.vssps.visualstudio.com/user_impersonation"
), MSALGrantedScopesKey=(
    "User.Read",
    email
), MSALErrorDescriptionKey=Server returned less scopes than requested, MSALInvalidResultKey=<MSALResult: 0x6000034a5800>}

I tried to use other scope that uses user_impersonation such as https://management.azure.com/user_impersonation with the same result (scope declined).

I also tried to replace the URL by the resource GUID but with the same result too.

If I replace the user_impersonation scope with another one like Mail.Read, Mail.Send, etc... it works fine.

**Comment by scordonnier** [comment]
I tried again with the version 1.0.0 and now it works fine with scope="499b84ac-1321-427f-aa17-267ca6975798/user_impersonation"

**Comment by AbhishekVashisth** [comment]
Hi scordonnier, 

Could you please elaborate what exactly to did as I am facing the same issue. 
I am trying with these scopes ["calendars.read calendars.readwrite offline_access user.readbasic.all openid"]. and facing same issue.
