### ISSUE TITLE
Unable to set `keychainSharingGroup` to `nil` in MSALCacheConfig

### ISSUE THREAD

**Issue by dbxdb** [AzureAD/microsoft-authentication-library-for-objc#668]
Prior version `0.6.0` I have been using the following code to avoid sharing user accounts while keeping them in app's local Keychain:

```let app = MSALPublicClientApplication(clientId: clientId, keychainGroup: nil, authority: authority)```

In the `0.6.0` release this initializer was marked as deprecated. Thus, I had to use a new one which accepts `MSALPublicClientApplicationConfig`. To achieve a similar functionality I tried to configure its like this (pseudo-code):

```appConfig.cacheConfig.keychainSharingGroup = nil```

Unfortunately, the property `keychainSharingGroup` is declared as a `nonnull`, so I got a compiler error.

Please consider making the `keychainSharingGroup` nullable in the `0.7.0` or suggest another way to keep credentials private for an application.

**Comment by oldalton** [comment]
Please set it to your bundleIdentifier to prevent token sharing. See more here: https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALCacheConfig.html#/Configure%20keychain%20sharing

**Comment by oldalton** [comment]
You can see more information here: https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALCacheConfig.html#/c:objc(cs)MSALCacheConfig(py)keychainSharingGroup

**Comment by dbxdb** [comment]
It works 👍 Closing the issue.
