### ISSUE TITLE
MSAL 0.50 failing with invalid scope error for some users

### ISSUE THREAD

**Issue by guidedways** [AzureAD/microsoft-authentication-library-for-objc#674]
I've just received the following error from our user saying they keep seeing this when they try and login. The app simply presents this error when it fails to connect. Why would it say `invalid_scope`? Anything we're doing wrong? Others haven't had any issues:

> Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDesicriptionKey=The provided resource value for the input parameter 'scope' is not valid., MSALOAuthErrorKey=invalid_scope, MSALInternalErrorCodeKey=-42005}

**Comment by guidedways** [comment]
We're using `https://outlook.office365.com/EWS.AccessAsUser.All` as the scope by the way. Could this mean their installation does not allow this scope?

**Comment by guidedways** [comment]
I've heard back from one particular user and they said they're using a 'Personal Office 365' account. Is that not supported by this scope?

**Comment by guidedways** [comment]
@oldalton any help would be appreciated

**Comment by oldalton** [comment]
This seems like a similar issue: https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/518

**Comment by guidedways** [comment]
It does indeed - but is there no way for this to work? We don't really know what to tell our users since other apps using the ADAL library to authenticate don't seem to have this issue it seems?

**Comment by oldalton** [comment]
@guidedways, this is something that needs to be fixed from EWS side, it's not an MSAL issue. In the meantime, you can set authority to "https://login.microsoftonline.com/organizations" when requesting a token for EWS resource to restrict personal account users from seeing this error.

**Comment by guidedways** [comment]
> @guidedways, this is something that needs to be fixed from EWS side, it's not an MSAL issue. In the meantime, you can set authority to "https://login.microsoftonline.com/organizations" when requesting a token for EWS resource to restrict personal account users from seeing this error.

Sorry never got back to you as the user never got back to us :D I'm seeing more of this now. How exactly do I get to do this?? @oldalton

**Comment by guidedways** [comment]
@oldalton sadly that doesn't work:

![Screenshot 2024-02-18 at 00 29 49@2x](https://github.com/AzureAD/microsoft-authentication-library-for-objc/assets/202437/2090541f-7793-4d85-983c-68e7c0474ce9)
