### ISSUE TITLE
Description needs to specify supported iOS / macOS versions

### ISSUE THREAD

**Issue by guidedways** [AzureAD/microsoft-authentication-library-for-objc#676]
After the recent crash on macOS I just realized the library's main description page does not document the supported versions of iOS / macOS. Moreover, release notes aren't immediately clear if certain changes are required for macOS too (such as the `msauthv3` plist addition). Given the library supports both platforms now, the release notes and documentation needs to be explicit in what's supported and what isn't. Testing also needs to be performed on all supported macOS / iOS versions in order to avoid us releasing an app update with the updated version of the library.

**Comment by oldalton** [comment]
Thanks for your feedback. We'll definitely keep it in mind!
