### ISSUE TITLE
MSAL requires administrator permission on AAD account

### ISSUE THREAD

**Issue by AdamCrabtreeMSFT** [AzureAD/microsoft-authentication-library-for-objc#680]
I'm on boarding a new application with MSAL being used as the authentication library. I followed the instructions of registering the application  and editing info.plist information. However when I sign in it says that I don't actually have permissions from my administrator to do what is needed (the scopes are UserActivity.ReadWrite.CreatedByApp)

and I was wondering how I could get that. I through documentation but found nothing.

**Comment by oldalton** [comment]
Tenant administrator would need to grant consent from Azure Portal. See an example here: https://docs.microsoft.com/en-us/azure/active-directory/develop/consent-framework
