### ISSUE TITLE
MSAL with B2C directory: error accessing accoutClaims

### ISSUE THREAD

**Issue by barrettlee** [AzureAD/microsoft-authentication-library-for-objc#701]
I have a swift 5  (xcode 11) application configured to use the current release MSAL lib for objective-c v0.8.0 to obtain tokens issued by my Azure B2C directory and it is working - I do get tokens and they are valid to use with my API.  

The issue I have is that i am having problems accessing the user's identity from the MSALAccount object in swift. 
When I view `userId` field, the value is  "Missing from the token response" yet i can see it in the objective-c library code objects when the tokens are decoded - and it is actually present in the ID and access tokens. So I need to look for identity elsewhere.

In Swift when I access any field or list keys or values in the `MSALAccount.accountClaims` i get **this error**:
```
Could not cast value of type '__NSCFNumber' (0x7fff87a89500) to 'NSString' (0x7fff87b450e8).
error: Execution was interrupted, reason: signal SIGABRT.
```

When examining the claims code when debugging the MSAL library objective-c code i get this for claims (and its basically the same when decoding the ID token in jwt.ms)
Indeed, in the objective-c claims object the numbers below are "long" type and accessible.
```
{
    alg = RS256;
    "at_hash" = "-9Mxxxxxxxxxx";
    aud = "4xxxxxb-xxxx-4xxx-axxx-9xxxxxxxxxxx";
    "auth_time" = 1569377757;
    emails =     (
        "bobsmith@someemail.com"
    );
    exp = 1569381357;
    iat = 1569377757;
    iss = "https://mytennant.b2clogin.com/tfp/2xxxxx-cxxx-4xxx-9xxx-xxxxxxxxxx/b2c_1_signInFlow/v2.0/";
    kid = "X43ejkdjkle3jklrew....";
    name = "Bob smith";
    nbf = 1569377757;
    sub = "dxxxx-0xxx-4xxx-bxxx-xxxxxxxxx";
    tfp = "B2C_1_signInFlow";
    typ = JWT;
    ver = "1.0";
}
```
the field `NSDictionary<NSString *, NSString *> *accountClaims;` in `MSALRestult.m` returns the claims and the numeric fields without issue when accessed in objective-c code but when it finally calls the completion block and passes to Swift as `MSALResult`, the `accountClaims` field is `[String: String]` and throws the error above when any part is accessed. 

Am i missing some configuration setting or is this a real bug? 

Thanks 
Barrett

**Comment by oldalton** [comment]
I'm suspecting the type is incorrect. Let me change `NSDictionary<NSString *, NSString *> *accountClaims;` to a more genetic `NSDictionary *accountClaims`, as `<NSString *, NSString *>` is actually incorrect here.

**Comment by oldalton** [comment]
@barrettlee, please try MSAL 1.0 and let me know if the issue is resolved. Thanks!

**Comment by barrettlee** [comment]
@oldalton It works perfectly. 

also I was able to stop using BOOL validateAuthority=false and start using knownAuthorities with my tennant.b2clogin.com/tfp/... URL - seems to have started working right at some point too. (maybe it was my error before )

congrats on  V1.0  ;)

Thanks,
Barrett

**Comment by pradeepktg** [comment]
Hello, How to get the JWT? I'm getting the JWT decoded data, but I need JWT encoded/raw value.

**Comment by oldalton** [comment]
Raw id_token is exposed as part of MSALResult object: https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALResult.html#/c:objc(cs)MSALResult(py)idToken
