### ISSUE TITLE
Clarification required regarding minimum requirements for macOS

### ISSUE THREAD

**Issue by guidedways** [AzureAD/microsoft-authentication-library-for-objc#706]
I just saw this: `macOS - MSAL supports macOS (OSX) 10.12 and above.`

But that's not true, at least for v0.5. We're using this on 10.11 without issues. Can you please clarify why upgrading to v1.0 of the library won't work on 10.11 anymore? Does that mean we're stuck on v0.50 of the library?

**Comment by oldalton** [comment]
Sorry for a late response. We decide supported versions by a combination of following criteria:
1. Percentage of users on that macOS version
2. Cost of testing and maintaining the library for one more macOS version

At the current moment, we're seeing a relatively low number of users on 10.11 and below. Additionally, we generally drop previous macOS version when we add support for a new one. In this case, 10.15 Catalina was released, so we dropped support for 10.11.

Supported macOS version indicates a version that we'll help resolving issues with. Older versions might still work, but we don't perform regular testing with these.
