### ISSUE TITLE
In iOS 13, MSAL Acquire token giving an error.

### ISSUE THREAD

**Issue by arbintaj** [AzureAD/microsoft-authentication-library-for-objc#708]
Hi,

Am getting this below error while trying to call acquire token function. but same  code is working fine with below versions of iOS 13.

Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALInternalErrorCodeKey=-42008}.

Please help out.

**Comment by ricsantos** [comment]
Duplicate of #698

**Comment by oldalton** [comment]
@arbintaj, what MSAL version are you using? Can you make sure you're not using any deprecated MSAL APIs? MSAL requires passing view controller on iOS 13 due to Apple new API requirements. Make sure you're providing it as well. Thanks!

**Comment by arbintaj** [comment]
@oldalton  am using latest MSAL version 1.0.0  with latest MSAL APIs and  am am passing view controller as well but still facing the same error

Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALInternalErrorCodeKey=-42008}

Not getting proper description in error log as well :)
Thanks

**Comment by oldalton** [comment]
@arbintaj, can you enable [MSAL logging](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msal-for-ios-and-macos) with following configuration: 
1. Enable PII: `MSALGlobalConfig.loggerConfig.piiEnabled = true`
2. Set level to verbose: `MSALGlobalConfig.loggerConfig.logLevel = .verbose`

Check the log output. It should have all the possible details about the failure for us to analyze. Please only use this configuration for debugging purposes.

**Comment by DanielOuwendijk** [comment]
I Have the exact same problem. Also for IOS 13. I tried to enable MSAL Logging with those 2 lines you answered with (set in de viewDidLoad() function), but the error message stayed the same. still:

Could not acquire token: Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALInternalErrorCodeKey=-42008}

**Comment by oldalton** [comment]
Can you please provide a sample of how you're invoking MSAL?

**Comment by oldalton** [comment]
Another thing to make sure is that UIViewController that you're passing as parentViewController is retained. MSAL doesn't retain the parentViewController and that's what might be causing the error you're seeing.

**Comment by DanielOuwendijk** [comment]
I'll just provide the whole code:

`
func viewDidLoad() {
do {
            try self.initMSAL()
        } catch let error {
            print("Unable to create Application Context \(error)")
        }

 guard let currentAccount = self.currentAccount() else {
            // We check to see if we have a current logged in account.
            // If we don't, then we need to sign someone in.
            acquireTokenInteractively()
            return
        }
        acquireTokenSilently(currentAccount)
}

 func initMSAL() throws {
           guard let authorityURL = URL(string: kAuthority) else {
            print("Unable to create authority URL")
            return
        }
        
        let authority = try MSALB2CAuthority(url: authorityURL)
        
        let msalConfiguration = MSALPublicClientApplicationConfig(clientId: kClientID, redirectUri: 
        kRedirectUri, authority: authority)
        
        self.applicationContext = try MSALPublicClientApplication(configuration: msalConfiguration)
        
        self.webViewParamaters = MSALWebviewParameters(parentViewController: self)
    }
    
    func initWebViewParams() {
          self.webViewParamaters = MSALWebviewParameters(parentViewController: self)
    }`

func acquireTokenInteractively() {
        
        guard let applicationContext = self.applicationContext else { return }
        guard let webViewParameters = self.webViewParamaters else { return }


        let parameters = MSALInteractiveTokenParameters(scopes: kScopes, webviewParameters: webViewParameters)
        parameters.promptType = .selectAccount;
        
        applicationContext.acquireToken(with: parameters) { (result, error) in
            
            if let error = error {
                
                print("Could not acquire token: \(error)")
                return
            }
            
            guard let result = result else {
                
                print("Could not acquire token: No result returned")
                return
            }
            
            CosmosDbData.accesToken = result.accessToken
            print("Access token is \(CosmosDbData.accesToken)")
            self.getClaims()
        }
    }

**Comment by DanielOuwendijk** [comment]
Could you maybe provide an example of how to retain the UIViewController? I'm not sure how to do this

**Comment by oldalton** [comment]
Basically, you need to make sure that your instance of parentViewController is alive, e.g. if some other object is having a strong reference with it. MSAL will only keep a weak reference to your parentViewController to avoid a retain cycle. Additionally, you need to make sure that your view controller has a valid window, so I'd recommend taking a look at your view controller's lifecycle. Your source code looks fine, as long as all constant values are correct and the view controller is retained.

I've also submitted a PR to have some more logging around this scenario, and it should be included in the next release (1.0.1). This should help us to identify the issue.

**Comment by DanielOuwendijk** [comment]
Thanks for the help. I figured it out (by just trying things)!

so these lines of code were in de viewDidLoad function:

```
guard let currentAccount = self.currentAccount() else {
                   // We check to see if we have a current logged in account.
                   // If we don't, then we need to sign someone in.
                   acquireTokenInteractively()
                   return
               }
               acquireTokenSilently(currentAccount)
```
I moved this code to the ViewDidAppear function and now it works! Yeey!

Maybe you have a better idea why this works, because I'm not sure. Atleast it's solved!

**Comment by oldalton** [comment]
It might be that your view controller doesn't have a window yet, which is normally the case when the viewDidLoad method is called. MSAL requires a valid window to present ASWebAuthenticationSession (see [Apple's API](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationpresentationcontextproviding/3237230-presentationanchorforwebauthenti?language=objc)).

**Comment by arbintaj** [comment]
Yeah , Thanks for solution,  function was getting called before view loads so it was causing that error :) .
I called the function on main thread when window is available and it worked.
