### ISSUE TITLE
Xcode 11 iOS 13 - can't build an ipa

### ISSUE THREAD

**Issue by chrisriner** [AzureAD/microsoft-authentication-library-for-objc#709]
I am trying to build an ipa for my project and nothing has changed but a few lines and a new internal built framework.  Also the project will not build even based on last build with no changes.  We try to archive and get "IPA processing failed".  We look at the logs and see this:
Assertion failed: Expected 4 archs in otool output:
/var/folders/1c/3mq4ch_j6gxgpvcmyxktwynw5hfkwj/T/IDEDistributionOptionThinning.~~~1vFIB7/Payload/Directory.app/Frameworks/MSAL.framework/MSAL

**Comment by oldalton** [comment]
@chrisriner, what are the architectures supported by your app? Is it standard architectures?

**Comment by oldalton** [comment]
Should be fixed in 1.0.1 that is now released. Please reopen the issue if it still persists in 1.0.1.
