### ISSUE TITLE
You can't sign in here with a personal account

### ISSUE THREAD

**Issue by scordonnier** [AzureAD/microsoft-authentication-library-for-objc#713]
Hello,

I have created an app registration with signInAudience = AzureADandPersonalMicrosoftAccount and I'm using MSAL 1.0.0.

When I try to sign in with a personal account, I receive the following message "You can't sign in here with a personal account".

If I try to sign in with a work account, everything works as expected.

Any ideas why this problem and how to solve it ?

Thank you

**Comment by oldalton** [comment]
Can you provide information about scopes you're passing to MSAL?

**Comment by scordonnier** [comment]
499b84ac-1321-427f-aa17-267ca6975798/user_impersonation (Azure DevOps REST API)

**Comment by oldalton** [comment]
@scordonnier, What is probably happening here is that 499b84ac-1321-427f-aa17-267ca6975798 is a v1 resource that only supports AAD accounts. While MSAL supports getting a token for any account type (including AAD, MSA and B2C), the resource you're trying to get a token for needs to support this account type as well. I'd recommend to followup on MSA account support by opening an issue in Azure REST API documentation: https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-5.1#client-libraries

**Comment by oldalton** [comment]
@scordonnier, Did you resolve the issue?

**Comment by oldalton** [comment]
Closing the issue due to inactivity. Please reopen if it is still an issue. Thanks!

**Comment by kimdv** [comment]
@scordonnier did you solve this problem? 
I use the scope `"https://app.vssps.visualstudio.com/user_impersonation"`

I have enabled Live SDK support

**Comment by rzulkoski** [comment]
@oldalton, is the Azure DevOps REST API being a `v1 resource` a permanent state of affairs or will this eventually be allowed?

**Comment by SurbhitBhatnagar** [comment]
Hi @oldalton, 
I am having the same issue with msal-browser. In my case, the scope is 'https://management.azure.com/user_impersonation'.
signInAudience set as 'Accounts in any organizational directory and personal Microsoft accounts’. Any suggestions?

**Comment by clarkd** [comment]
We are having the same issue - did anyone manage to resolve this?

**Comment by nik-net** [comment]
Did anyone manage to solve this issue? We have the exact same problem
