### ISSUE TITLE
'AuthenticationServices/AuthenticationServices.h' file not found. in ios using swift 

### ISSUE THREAD

**Issue by Paragdhanani** [AzureAD/microsoft-authentication-library-for-objc#714]

**Comment by Paragdhanani** [comment]
When i run the project it gives me Build Faild... and Error is AuthenticationServices/AuthenticationServices.h' file not found.
Please give me the solution

**Comment by oldalton** [comment]
@Paragdhanani, how are you consuming MSAL? CocoaPods/Carthage/direct download? Can you please provide a bit more info on your setup?

**Comment by oldalton** [comment]
@Paragdhanani, can you provide the info requested above? Thanks!

**Comment by oldalton** [comment]
@Paragdhanani, I'll be closing this issue because we haven't been able to reproduce it. Please reopen the issue with any additional information you can provide if you're still seeing it. Thanks!
