### ISSUE TITLE
Webview suddenly disappears in login flow (iOS 12.2)

### ISSUE THREAD

**Issue by BastiaanAndriessen** [AzureAD/microsoft-authentication-library-for-objc#727]
## Description
We are experiencing an issue where the SFSafariView suddenly disappears (without animation) at seamingly random moments in the login flow. We've encountered this bug with versions 1.0 and 0.7 of the MSAL library, but it's also possible that it has been introduced in older versions.
We're experiencing this on device managed iPads running iOS 12.2. We are not able to reproduce it (yet) in debug mode.

[Video](https://drive.google.com/file/d/1ScVqxv3ZYhRUfG3OZhqx68n85ITeBzxb/view?usp=sharing)

Our suspicion is that the session is not cancelled correctly somewhere and that's the cause of the errors listed below. We're clueless about what could trigger the disappearance of the view.

We've been looking at this for quite a while, so any help is greatly appreciated.

## Errors
As seen in the video, we alert all errors thrown from the <code>createClientApplication</code> method and received from the <code>acquireToken</code> completion closure. We receive following errors:

```
MSALErrorCode: -50005 (MSALErrorUserCanceled)
MSALErrorDescriptionKey: Authorization session was cancelled programatically.
```

```
MSALErrorCode: -50000 (MSALErrorInternal)
MSALErrorDescriptionKey: Only one interactive session is allowed at a time.
MSALInternalError: -42402 (MSALInternalErrorInteractiveSessionAlreadyRunning)
```

## Code

We're calling the MSAL methods in a RxSwift Observable creation block, which we complete after successfully receiving the MSALResult object (in the completion closure). RxSwift version is 5.0.

### Configuration
	let config: MSALPublicClientApplicationConfig = {
    	let tenantID = UserDefaults.standard.msalTenantID!
    	let url = URL(string: "https://login.microsoftonline.com/\(tenantID)/v2.0")!
    	let authority = try? MSALAuthority(url: url)

    	let config = MSALPublicClientApplicationConfig(
      		clientId: UserDefaults.standard.msalClientID!,
      		redirectUri: "msalcom.nephroflow.assistant://auth",
      		authority: authority
    	)

    	config.cacheConfig.keychainSharingGroup = Bundle.main.bundleIdentifier!

    	return config
 	}()

### MSAL Implementation

	func rxLogin(in viewController: UIViewController) -> Observable<MSALResult> {
         return Observable.create { observer in
             let disposable = Disposables.create {
                 MSALPublicClientApplication.cancelCurrentWebAuthSession()
             }

             let completion = { (result: MSALResult?, error: Error?) in
                 if disposable.isDisposed {
                     return
                 }

                 guard let acquireTokenResult = result, error == nil else {
                     observer.onError(error!)
                     return
                 }

                 observer.onNext(acquireTokenResult)
                 observer.onCompleted()
             }

             do {
                 let application = try self.createClientApplication()

                 let webViewParameters = MSALWebviewParameters(parentViewController: viewController)
                 webViewParameters.presentationStyle = .popover

                 if #available(iOS 13.0, *) {
                     webViewParameters.prefersEphemeralWebBrowserSession = true
                 }

                 let interactiveParameters =
                 MSALInteractiveTokenParameters(scopes: ["email"], webviewParameters: webViewParameters)

                 interactiveParameters.promptType = .login

                 application.acquireToken(with: interactiveParameters, completionBlock: completion)
             } catch let error {
                 observer.onError(error)
             }

             return disposable
         }
  	}

**Comment by oldalton** [comment]
Thanks for a detailed writeup!
MSAL passes the parentViewController that you provide to Apple API that Apple is using to present signin window. https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/blob/master/IdentityCore/src/webview/systemWebview/ios/MSIDAuthenticationSession.m#L70

Note that MSAL doesn't retain the controller to avoid possible reference cycle. One thing that might be happening is that parentController that you're passing gets deallocated in the middle of the flow. Please double check that parentController and its window are alive throughout the whole authentication flow.

Another thing I noted in your code is that you're calling MSAL cancellation:

```
         let disposable = Disposables.create {
             MSALPublicClientApplication.cancelCurrentWebAuthSession()
         }
```

I'd recommend to look a little bit closer and make sure that this doesn't get called in the middle of the flow. `MSALPublicClientApplication.cancelCurrentWebAuthSession()` will immediately cancel any ongoing authentication flows.

Since you mentioned you're seeing it on iPads, I'd double check on the first idea first (making sure that controller and window doesn't get deallocated or dismissed during auth flow).

**Comment by BastiaanAndriessen** [comment]
Hi,

Thanks for your quick response and interpretation of the symptoms. The parent controller we pass to MSAL is the view controller with the plus icon and is never dismissed/deallocated in the login flow. The case were the observable would be prematurely disposed is one we can still investigate more.

Good news is that we've updated the iPads of our clients to iOS13 and haven't encountered the issue since then.

**Comment by Krusheuski** [comment]
@oldalton 
Hi,
I have a similar problem after upgrading to version 1.0.

> The application 'ClientId' asked for scope 'user.read' that doesn't exist. Contact the app vendor.

On version 0.4.3 everything works.

**Comment by oldalton** [comment]
It looks like you're trying to request a scope that doesn't exist. Can you double check that API c39d1c84-b0cb-4949-b7f5-d00000000000 has "user.read" scope registered?

**Comment by Krusheuski** [comment]
@oldalton 
Exists, since it works with version 0.4.3.

**Comment by oldalton** [comment]
Thanks. Older MSAL versions were automatically removing a scope which contained your clientId in it. Therefore, it might be that it wasn't actually working, but it wasn't explicitly failing either. 

Would it be possible to provide a correlationId and/or MSAL log for the working case with MSAL 0.4.3? I want to confirm my theory and verify which scopes were actually returned. Thanks.

**Comment by Krusheuski** [comment]
Works:
> TID=463993 MSAL 0.4.3 iOS 10.2.1 [2019-10-30 07:36:48] Default app's access group: "(not-null)".
TID=463993 MSAL 0.4.3 iOS 10.2.1 [2019-10-30 07:36:48] Using "(not-null)" Team ID.
TID=463993 MSAL 0.4.3 iOS 10.2.1 [2019-10-30 07:36:48] Init MSIDKeychainTokenCache with keychainGroup: adal keychain group
TID=463993 MSAL 0.4.3 iOS 10.2.1 [2019-10-30 07:36:48 - 36B9180F-A678-4D32-AFF5-252AE734AC06] [MSAL] -[MSALPublicClientApplication acquireTokenForScopes:(not-null)
                               extraScopesToConsent:(null)
                                            account:(null)
                                          loginHint:(null)
                                         promptType:MSALPromptTypeSelectAccount
                               extraQueryParameters:(null)
                                          authority:(null)
                                        webviewType:MSALWebviewTypeDefault
                                      customWebview:(null)
                                      correlationId:(null)
                                       capabilities:(null)
                                      claimsRequest:(null)]
TID=463993 MSAL 0.4.3 iOS 10.2.1 [2019-10-30 07:36:48 - 36B9180F-A678-4D32-AFF5-252AE734AC06] [MSAL] Beginning interactive flow.
TID=463993 MSAL 0.4.3 iOS 10.2.1 [2019-10-30 07:36:48 - 36B9180F-A678-4D32-AFF5-252AE734AC06] [MSAL] Resolving authority: https://login.microsoftonline.com/e78825a9-07b5-4645-9f7d-2c66311b35ff, upn: (null)
TID=464448 MSAL 0.4.3 iOS 10.2.1 [2019-10-30 07:36:48 - 36B9180F-A678-4D32-AFF5-252AE734AC06] [MSAL] No cached preferred_network for authority
TID=464448 MSAL 0.4.3 iOS 10.2.1 [2019-10-30 07:36:48 - 36B9180F-A678-4D32-AFF5-252AE734AC06] [MSAL] Waiting on Authority Validation Queue
TID=464379 MSAL 0.4.3 iOS 10.2.1 [2019-10-30 07:36:49] error is missing.
TID=464379 MSAL 0.4.3 iOS 10.2.1 [2019-10-30 07:36:49 - 36B9180F-A678-4D32-AFF5-252AE734AC06] [MSAL] Caching AAD Environements
TID=464379 MSAL 0.4.3 iOS 10.2.1 [2019-10-30 07:36:49 - 36B9180F-A678-4D32-AFF5-252AE734AC06] [MSAL] Resolved authority, validated: YES, error: 0
TID=464448 MSAL 0.4.3 iOS 10.2.1 [2019-10-30 07:36:49 - 36B9180F-A678-4D32-AFF5-252AE734AC06] [MSAL] Returned from Authority Validation Queue
TID=464379 MSAL 0.4.3 iOS 10.2.1 [2019-10-30 07:36:49] error is missing.
TID=464612 MSAL 0.4.3 iOS 10.2.1 [2019-10-30 07:37:12 - 36B9180F-A678-4D32-AFF5-252AE734AC06] [MSAL] (Default accessor) Saving multi resource refresh token
TID=464612 MSAL 0.4.3 iOS 10.2.1 [2019-10-30 07:37:12 - 36B9180F-A678-4D32-AFF5-252AE734AC06] [MSAL] Keychain find status: -25300
TID=464612 MSAL 0.4.3 iOS 10.2.1 [2019-10-30 07:37:12 - 36B9180F-A678-4D32-AFF5-252AE734AC06] [MSAL] Keychain find status: 0
TID=464612 MSAL 0.4.3 iOS 10.2.1 [2019-10-30 07:37:12 - 36B9180F-A678-4D32-AFF5-252AE734AC06] [MSAL] Interactive flow finished result (not-null), error: 0 error domain: (null)
TID=464612 MSAL 0.4.3 iOS 10.2.1 [2019-10-30 07:37:12 - 36B9180F-A678-4D32-AFF5-252AE734AC06] [MSAL] acquireToken returning with at: (not-null) scopes:(not-null) expiration:2019-10-30 08:37:12 +0000

**Comment by Krusheuski** [comment]
@oldalton , so what about my case?

**Comment by oldalton** [comment]
@Krusheuski, the only real difference I am seeing between those two requests is the promptType. MSAL 0.4.3 was using prompt=select_account by default, whereas 1.0.1 doesn't. 

It would be very strange if that is the reason for the failure, but just to double check, can you try setting promptType when creating MSALInteractiveTokenparameters in 1.0.1 and see if you're still getting an error?

e.g. 

```
MSALInteractiveTokenParameters *parameters = [[MSALInteractiveTokenParameters alloc] initWithScopes:... webviewParameters:webviewParameters];

parameters.promptType = MSALPromptTypeSelectAccount;```

**Comment by Krusheuski** [comment]
@oldalton , thank! Now everything works.

**Comment by diwakar26** [comment]
I'm calling something like this still I'm getting issue  this issue
["MSALCorrelationIDKey": 8BAC66C9-2997-4303-B3B0-D8130D8B0C91, "MSALErrorDescriptionKey": Only one interactive session is allowed at a time., "MSALInternalErrorCodeKey": -42402]

Below code used for fetching token
 guard let clientApp = msalClientApp, let tokenParams = getAcquireTokenParameters(policyType: .signUpSignIn) else { return }
        tokenParams.promptType = .selectAccount
        MSALPublicClientApplication.cancelCurrentWebAuthSession()
        clientApp.acquireToken(with: tokenParams) { (result, error) in } )
