### ISSUE TITLE
Getting same token with acquireSilent, even when it is expired

### ISSUE THREAD

**Issue by DanielOuwendijk** [AzureAD/microsoft-authentication-library-for-objc#730]
I have a problem when I'm calling acquireTokenSilently. When the app refreshes the token, it is always the same. The token never changes. When it is expired, the function still thinks the token works (no error given). This means when I'm getting data from my database, it doesn't work... Any idea what the problem can be?

my function:

 ```
func acquireTokenSilently(_ account : MSALAccount!) {

        guard let applicationContext = self.applicationContext else { return }

        let parameters = MSALSilentTokenParameters(scopes: kScopes, account: account)
        applicationContext.acquireTokenSilent(with: parameters) { (result, error) in

            if let error = error {

                let nsError = error as NSError

                // interactionRequired means we need to ask the user to sign-in. This usually happens
                // when the user's Refresh Token is expired or if the user has changed their password
                // among other possible reasons.

                if (nsError.domain == MSALErrorDomain) {

                    if (nsError.code == MSALError.interactionRequired.rawValue) {

                       DispatchQueue.main.async {
                            print("Interaction for token needed! error: ", nsError)

                            self.acquireTokenInteractively()
                        }
                        return
                    }
                }

                print("Could not acquire token silently: \(error)")
                return
            }

            guard let result = result else {

                print("Could not acquire token: No result returned")
                return
            }

            let accesToken = result.accessToken
            //getting my data with the token
        }
        
    }
```

**Comment by oldalton** [comment]
@DanielOuwendijk, how do you know it is the same token? Do you mean it is the same string? Is it AAD or MSA account? Thanks.

**Comment by DanielOuwendijk** [comment]
I'm printing the token to the console and it is constantly the same. Yes, I'm talking about the string and I'm using a AAD account, or well... I'm using B2C authority. But I've done some research, and now I understand the problem better:

On B2C (in the portal), the lifetime of the token is specified at 180 minutes and I think MSAL thinks this a well as it should. The weird thing is that the token is actually expired after 60 minutes(?) so the API gives an error. If I test it in Postman, I can clearly see it is expired after one hour. 

So for now, I've set the token lifetime to 60 minutes so that everyone thinks the token lasts 60 minutes. I hope this works.

I'm not sure if this is related to MSAL, but do you know what the problem could be?

**Comment by oldalton** [comment]
That's an interesting finding. Let me followup on this and get back to you. Thanks!

**Comment by oldalton** [comment]
@DanielOuwendijk, I followed up with our B2C team and they weren't aware of this behavior. They also did a quick test in a production tenant themselves, and they weren't getting shorter lived tokens.

Therefore, can you provide a bit more information here? Which API are you sending the access token for? Perhaps the API itself doesn't enforce the token lifetime correctly and that is why token is rejected earlier?

**Comment by DanielOuwendijk** [comment]
Thank you. I understand.

I made an .NET Core API myself for getting data from and sending data to Cosmos DB. This is the code I use to verify it:

```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthentication(options =>
            {
                options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
            })
                 .AddJwtBearer(jwtOptions =>
                 {
                     jwtOptions.Authority = $"https://login.microsoftonline.com/tfp/{Configuration["AzureAdB2C:Tenant"]}/{Configuration["AzureAdB2C:Policy"]}/v2.0/";
                     jwtOptions.Audience = Configuration["AzureAdB2C:ClientId"];
                     jwtOptions.Events = new JwtBearerEvents
                     {
                         OnAuthenticationFailed = AuthenticationFailed
                     };
                     jwtOptions.TokenValidationParameters = new Microsoft.IdentityModel.Tokens.TokenValidationParameters
                     {
                         ValidIssuer = "https://<myTenant>.b2clogin.com/<tenantId>/v2.0/"
                     };
                 });
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
        }
```

From Swift, I call this authority url: https://login.microsoftonline.com/tfp/<myTeneantName>.onmicrosoft.com/<myPolicy>

You should know that I didn't have this problem before. It popped up pretty sudden. As I said, I set the token lifetime to 60 minutes and everything works now, so (for me) it is not a big deal.
