### ISSUE TITLE
Can't connect to App behind Application Proxy from iOS

### ISSUE THREAD

**Issue by jowe13** [AzureAD/microsoft-authentication-library-for-objc#736]
Hi,

I'm trying to accomplish what is shown in the image below.

<img width="654" alt="Bildschirmfoto 2019-10-28 um 16 30 40" src="https://user-images.githubusercontent.com/38559352/67692432-6a005100-f9a0-11e9-8a07-bc830a0f78d0.png">

I'm authenticating to Azure AD using the iOS Example App. ( [https://docs.microsoft.com/en-us/azure////active-directory/develop/tutorial-v2-ios](url)). This step is working as expected. A webview opens and after entering my email i get redirected to my company's sign in page. After entering my password i get a positive result including the accesstoken.

When trying to call my API after authenticating i get the following result:
`
{ type: 'default',
  status: 200,
  ok: true,
  statusText: undefined,
  headers: 
   { map: 
      { 'content-type': 'text/html; charset=utf-8',
        'x-ms-ests-server': '2.1.9587.8 - DUB2 ProdSlices',
        pragma: 'no-cache',
        'content-encoding': 'gzip',
        p3p: 'CP="DSP CUR OTPi IND OTRi ONL FIN"',
        'x-dns-prefetch-control': 'on',
        'cache-control': 'no-cache, no-store',
        'x-ms-request-id': 'XXXXXXXXXX',
        date: 'Mon, 28 Oct 2019 15:35:38 GMT',
        'set-cookie': 'buid=XXXXXXX; expires=Wed, 27-Nov-2019 15:35:39 GMT; path=/; secure; HttpOnly; SameSite=None, fpc=XXXXXX; expires=Wed, 27-Nov-2019 15:35:39 GMT; path=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=prod; path=/; SameSite=None; secure; HttpOnly, stsservicecookie=ests; path=/; secure; HttpOnly',
        link: '<https://aadcdn.msauth.net>; rel=preconnect; crossorigin, <https://aadcdn.msauth.net>; rel=dns-prefetch, <https://aadcdn.msftauth.net>; rel=dns-prefetch',
        expires: '-1',
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        'content-length': '44656',
        'x-content-type-options': 'nosniff',
        vary: 'Accept-Encoding',
        'x-frame-options': 'DENY' } },
  url: 'https://login.microsoftonline.com/TENANTID/oauth2/authorize?response_type=code&client_id=MYCLIENTID&scope=openid&nonce=47e4d049-9798-424b-94f2-b8cfe5b1ce96&redirect_uri=https%3a%2f%2fM>APPNAME-MYINTERNALURL%2f&state=AppProxyState%3a%7b%22InvalidTokenRetry%22%3atrue%2c%22IsMsofba%22%3afalse%2c%22OriginalRawUrl%22%3a%22https%3a%5c%2f%5c%2fMYAPPNAME-MYINTERNALURL%5c%2fpostping%22%2c%22RequestProfileId%22%3a%22679abdfe-8e1c-4506-83a9-59c793795629%22%7d%23EndOfStateParam%23&client-request-id=1c3b0884-13ab-4708-a27a-ae0b8c743c94',
  _bodyInit: 
   { _data: 
      { size: 171732,
        offset: 0,
        blobId: 'FA6153FF-DEB0-495E-B6E0-2F48ECE01EAF',
        type: 'text/html',
        name: 'authorize.html',
        __collector: {} } },
  _bodyBlob: 
   { _data: 
      { size: 171732,
        offset: 0,
        blobId: 'FA6153FF-DEB0-495E-B6E0-2F48ECE01EAF',
        type: 'text/html',
        name: 'authorize.html',
        __collector: {} } } }
`

Which basically means: I am not authorized to call this (?!?).

However, when accessing my API Endpoint through a browser i can connect to it without any problems. (Including authenticating to Azure AD).

I'm trying to call my endpoint using the function below

`await fetch(MYENDPOINT, {
          method: 'GET',
          headers: {
            Authorization: 'Bearer ' + accessToken,
            'Content-Type': 'application/json'
          }
        })
          .then(res => {
            console.log('res', res);
          })
          .catch(error => {
            console.log('error inner', error);
          });
`

Even though this called is trigger from inside a react native app it should not make any problems. On the other hand i get the same error if i call my endpoint from my native iOS ViewController.

Any help with this is appreciated.

**Comment by oldalton** [comment]
Is the access token that you're sending issued for your API?

**Comment by jowe13** [comment]
Thanks for your quick reply. I will have a look at it

**Comment by oldalton** [comment]
You can either do it this way, or just pass a list of scopes in MSAL request. 

For example, if your API is "https://myapi.com" and the scope it needs is "user.read", you can pass MSAL a list of scopes with @["https://myapi.com/user.read"]

You can pass your scopes in MSALTokenParameters: https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALTokenParameters.html#/c:objc(cs)MSALTokenParameters(py)scopes

**Comment by oldalton** [comment]
@jowe13, do you still have open questions? If everything is resolved, please close the issue when possible. Thanks!

**Comment by jowe13** [comment]
Hey, i got it to work out. Thanks for your help!

**Comment by saadkhalidkhan** [comment]
Hi,
i am getting same issue. Able to get access token successfully, but when try to call web api i get no response. Do we need to add scopes for web api? I think i have added all scopes which we need for our app.
