### ISSUE TITLE
Not able to retrieve authenticated user's roles on Swift app

### ISSUE THREAD

**Issue by pabloabadsanz** [AzureAD/microsoft-authentication-library-for-objc#744]
Hi team,

@plamber and me created an app on our Azure tenant, having some endpoints we try to hit from an iOS app once the user gets authenticated by means of MSAL v1.0.
Everything is working like a charm, but we are facing an issue when trying to retrieve the Roles of an authenticated user. We cannot see a way for extracting that information from the user account's object.
However, when we take the access token from the response and decode it, we can see that the Roles of the user are on the Payload.

So we'd like to know whether we're missing something either in the iOS app's configuration, or in the Azure app's configuration.

Thank you so much in advance for your time.

Best

**Comment by oldalton** [comment]
MSAL will return a tenantProfile as part of MSALResult: https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALResult.html#/c:objc(cs)MSALResult(py)tenantProfile
MSALTenantProfile has a property called "claims" which contains all claims from a decoded id_token: https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALTenantProfile.html#/c:objc(cs)MSALTenantProfile(py)claims

As part of the decoded id_token, you should be able to retrieve the "roles" claim: https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens

Can you try it out and let me know if you're not seeing "roles" claim in the claims dictionary? In that case, please provide MSAL log for further investigation. Thanks.

**Comment by pabloabadsanz** [comment]
Thank you @oldalton,

That (inside claims property) is exactly the place I was checking while debugging. Unfortunately not roles claim is in there. That's why after decoding not the id token, but the access token, I was able to see the roles claim in the Payload.
Maybe @plamber and me are missing anything in the Azure app's configuration which is preventing the "roles" claim to be included in the returned id token...

Where should I get the MSAL log from?

Thanks again!

**Comment by plamber** [comment]
Thank you @oldalton,

I would like to share some more details about the architecture of the solution.

We have a central Web.API secured with AzureAD, roles, and custom scopes. The role definition is directly assigned to the AzureAD application associated with the Web.API.

We have multiple client applications (one of these applications is a mobile application) that is able to obtain a token from the Web.API. When requesting the token we would love to see the associated roles of the currently logged in user.

Under the Authentication section of the Web.API I do not have the "Access tokens" and "ID token" flags enabled since we are not having an implicit flow. Do we have to do further configurations on our Web.API to return the proper data? Or do you have some suggestions on how we could change our architecture and get the desired information?

Ideally, all permission management is handled only on Web.API level and not on client-side. The client should only receive the information what role the user is in

**Comment by oldalton** [comment]
Have you followed this guide and assigned roles for the user group? https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-add-app-roles-in-azure-ad-apps.

**Comment by plamber** [comment]
Yes, we followed these instructions. The groups have been configured on our back-end web API with its dedicated Azure AD application. The roles have been assigned to users.

We have a mobile application (dedicated Azure AD application) that does not have the roles assigned.
We thought to keep the permission handling on our web API only, roles included.

With this setup, we are wondering what is the best practice to let an application know what are the roles assigned for a user in that specific web api? How do you solve this problem in the most elegant way?

**Comment by psignoret** [comment]
@plamber, 

It looks like you figured this out by now, but just as a reminder:
- The ID token is for the _client_ (the iOS app, in this case)
- The access token is for the _resource_ app (the API)
- A token will only include roles applicable to the app for which the token is intended (i.e. the audience)

If the client and resource apps are registered as different apps in Azure AD, and you've assigned the users to roles on the resource app, then it is normal that the ID token (which is for the client) does not include those roles, but the access token (which is for the resource) does.

You have three options here:
1. Use the same app registration (i.e. the same app ID) for both the client and the resource. This is a common approach when the client and the API are part of the same package/solution.
2. Build an method in your API to return the user's roles. This method would receive (and validate) the access token, and return what is in the access token's roles claim.
   - Note: If you find you are tempted to just look at the access token from within the client app (which you should _not_ do), then it is likely option 1 here is a better option for you.
3. Define roles for the client application, assign users there also.
   - Note: If you find you are duplicating every role in the API, and assigning the same users to the same roles, then it is likely that option 1 here is a better option for you.

**Comment by plamber** [comment]
Thank you @psignoret for your summary. We will go with option 2.

**Comment by pabloabadsanz** [comment]
Thanks a lot @psignoret !! Appreciate it :)
