### ISSUE TITLE
How to force Microsoft Authentication Webview to not preload an account found in the keychain

### ISSUE THREAD

**Issue by Valpertui** [AzureAD/microsoft-authentication-library-for-objc#752]
Hello,

I'm looking at how to force the library to not load a microsoft account it already found (from the keychain ?).
The user is logged with one account but would like to sign in with another but the authentication webview is always preloaded with the previous account with no option to logout/sign in with another account (see video).

my usecase is the following:  
1. As a user I log in with Microsoft Authentication Interactive flow into my app with my account `accountA@outlook.com`.  
2. I log out from the app.  
3. I want to log in again with Microsoft Authentication Interactive flow into my app but this time with my account `accountB@outlook.com` . 

Expected:
- I can log in with another account easily

Current:
- `accountA@outlook.com` is prefiled into the Microsoft Authentication Interactive flow webview and I can either continue (login) or cancel the flow.  
  
  
Workaround:
I found a workaround which let me connect with another account but it is far from ideal : I need to download the Microsoft Authenticator app, which then will be opened when I start the Microsoft Authentication from my app, but no account will be prefilled there and I will be asked for the account identifier everytime.

Video of the issue (sorry for the gif but github doesn't support mp4)
[https://imgur.com/z4CNR7M](https://imgur.com/z4CNR7M)

**Comment by oldalton** [comment]
Can you try passing different promptType? e.g.

```
MSALInteractiveTokenParameters *parameters = [[MSALInteractiveTokenParameters alloc] initWithScopes:... webviewParameters:webviewParameters];
parameters.promptType = MSALPromptTypeSelectAccount;
```

**Comment by Valpertui** [comment]
This is exactly what I was looking for.
Thanks a lot 😄
