### ISSUE TITLE
Only one interactive session is allowed at a time MSALInternalErrorCodeKey=-42402 

### ISSUE THREAD

**Issue by veselaIl** [AzureAD/microsoft-authentication-library-for-objc#760]
I have an issues looping with an error only when hiding the application in the background after first time logged in. When I reach the app again in few seconds constantly showing popup for sign in. Only happens in iOS 13
- ERROR signing in: Optional(Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=Only one interactive session is allowed at a time., MSALInternalErrorCodeKey=-42402

**Comment by oldalton** [comment]
This error means that you called acquireToken API while another acquireToken was in progress. MSAL only allows a single acquireToken API at the time. Please make sure you don't start another MSAL acquireToken call when the app comes to the foreground.

**Comment by oldalton** [comment]
@veselaIl, did you resolve this issue?

**Comment by sxudan** [comment]
I am facing same error `Only one interactive session is allowed at a time.`
It occurs when the AD webview modal controller is cancelled through interactive drag down rather than pressing cancel button and afterward trying to login again

**Comment by rahulcode** [comment]
Any Updates On this issue , is there are fix to handle such cases wherein the user can cancel current request and continue with a new request.

**Comment by sxudan** [comment]
> Any Updates On this issue , is there are fix to handle such cases wherein the user can cancel current request and continue with a new request.

Cancel the session if "-42402" error is thrown. This line of code simply did a trick for me.
`MSALPublicClientApplication.cancelCurrentWebAuthSession()`
