### ISSUE TITLE
Failed to delete broker key with error: -34018

### ISSUE THREAD

**Issue by aaronjedwards** [AzureAD/microsoft-authentication-library-for-objc#764]
This issue seems to be related to brokered authentication. With the Authenticator app installed, I am experiencing the following error when calling `acquireToken`:
```
Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=Failed to delete broker key with error: -34018, MSALInternalErrorCodeKey=-42708}
```

For context I am using iOS 13.2. This _does not_ happen when the Microsoft Authenticator app is uninstalled.

Any help would be much appreciated.

**Comment by aaronjedwards** [comment]
Doh. I found the culprit. A typo:

![Screen Shot 2019-11-13 at 3 37 56 PM](https://user-images.githubusercontent.com/15369925/68810559-adf38700-062b-11ea-98fd-7a464adedf46.png)

Posting as this may help someone else in the future.

**Comment by cnfuzedRk62** [comment]
Hi @aaronjedwards  please help me , i am getting same error message , and i also add same solution as you mentioned but it not works for me.

**Comment by cnfuzedRk62** [comment]
Hey Guys please Add com.microsoft.adalcache 
in the KeyChain. In above screen shot there is misspelled and it waste my whole day.

**Comment by aaronjedwards** [comment]
@cnfuzedRk62 That was my point in posting the screenshot, to note that it was misspelled and that was the reason for the error. Were you able to get it resolved?

**Comment by Drzaln** [comment]
Hi @aaronjedwards 
I'm facing the exact same issue, but my keychain already correct and using iOS 15.4.1

**Comment by Drzaln** [comment]
> @Drzaln  did you get the issues solved now? I am seeking a way to fix it now.

Nope, I can't get the fix for this issue, so I'm not using this package.

**Comment by parasjain10** [comment]
Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=Broker authentication already in progress, MSALInternalErrorCodeKey=-42402, MSALCorrelationIDKey=EA9A26FD-A0E1-469D-8BFC-CF369BED0E14}
--
