### ISSUE TITLE
 loading the B2C loginWebview in  viewDidLoad get error MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALInternalErrorCodeKey=-42008}

### ISSUE THREAD

**Issue by a-elnajjar** [AzureAD/microsoft-authentication-library-for-objc#767]
I am trying to load the B2C loginWebview in  viewDidLoad when I call `self.authorization()` I get this error message 

> Could not acquire token: Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALInternalErrorCodeKey=-42008}

```
override func viewDidLoad() {
        super.viewDidLoad()

          do {
               
                  let authority = try self.getAuthority(forPolicy: self.kSignupOrSigninPolicy)
                  let pcaConfig = MSALPublicClientApplicationConfig(clientId: kClientID, redirectUri: nil, authority: authority)
                  self.application = try MSALPublicClientApplication(configuration: pcaConfig)
            
                  self.authorization()
              } catch {
                 print("Unable to create application \(error)")
              }
          }
          
    func getAuthority(forPolicy policy: String) throws -> MSALB2CAuthority {
        guard let authorityURL = URL(string: String(format: self.kEndpoint, self.kTenantName, policy)) else {
            throw NSError(domain: "SomeDomain",
                          code: 1,
                          userInfo: ["errorDescription": "Unable to create authority URL!"])
        }
        return try MSALB2CAuthority(url: authorityURL)
    }
    
   
    
    func updateLoggingText(text: String) {
        DispatchQueue.main.async{
            print(text)
        }
    }
    private func authorization() {
        do {
       
             
            let authority = try self.getAuthority(forPolicy: self.kSignupOrSigninPolicy)
            
            let webViewParameters = MSALWebviewParameters(parentViewController: self)
            let parameters = MSALInteractiveTokenParameters(scopes: kScopes, webviewParameters: webViewParameters)
            parameters.promptType = .selectAccount
            parameters.authority = authority
            application.acquireToken(with: parameters) { (result, error) in
                
                guard let result = result else {
                    print( "Could not acquire token: \(error ?? "No error informarion" as! Error)")
                    return
                }
                
                self.accessToken = result.accessToken
            }
        } catch {
            self.updateLoggingText(text: "Unable to create authority \(error)")
        }
    }
```

**Comment by oldalton** [comment]
Can you please provide MSAL logs? https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msal-for-ios-and-macos

**Comment by a-elnajjar** [comment]
MSAL Log 

>  %@ TID=365685 MSAL 1.0.0 iOS Sim 13.2.2 [2019-11-15 14:17:40] Encountered error with code -51118, description The required app scheme "msauth.com.microsoft.identity.client.sample.MSALiOSB2C" is not registered in the app's info.plist file. Please add "msauth.com.microsoft.identity.client.sample.MSALiOSB2C" into Info.plist under CFBundleURLSchemes without any whitespaces and make sure that redirectURi "msauth.com.microsoft.identity.client.sample.MSALiOSB2C://auth" is register in the portal for your app.
> %@ TID=365685 MSAL 1.0.0 iOS Sim 13.2.2 [2019-11-15 14:17:57] Default app's access group: "".
> Could not acquire token: Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALInternalErrorCodeKey=-42008}
> %@ TID=365685 MSAL 1.0.0 iOS Sim 13.2.2 [2019-11-15 14:18:00] Using "" Team ID.
> %@ TID=365685 MSAL 1.0.0 iOS Sim 13.2.2 [2019-11-15 14:18:32] Init MSIDKeychainTokenCache with keychainGroup:.com.microsoft.adalcache
> %@ TID=365685 MSAL 1.0.0 iOS Sim 13.2.2 [2019-11-15 14:18:41 - 41BBC7A7-1325-46F3-9EFB-8ED3DEE19353] [MSAL] acquireToken returning with error: (MSALErrorDomain, -50000)

**Comment by oldalton** [comment]
I think the error is telling you what is missing:

`The required app scheme "msauth.com.microsoft.identity.client.sample.MSALiOSB2C" is not registered in the app's info.plist file. Please add "msauth.com.microsoft.identity.client.sample.MSALiOSB2C" into Info.plist under CFBundleURLSchemes without any whitespaces and make sure that redirectURi "msauth.com.microsoft.identity.client.sample.MSALiOSB2C://auth" is register in the portal for your app.`

Have you completed this step?
