### ISSUE TITLE
Implementing iOS 13 SDK new feature prefersEphemeralWebBrowserSession

### ISSUE THREAD

**Issue by a-elnajjar** [AzureAD/microsoft-authentication-library-for-objc#768]
watch this video from Apple's WWDC [What's New in Authentication](https://developer.apple.com/videos/play/wwdc2019/516/) go forward to 14:17 minutes. in [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession) class they have to option to configure a session in webView called [prefersEphemeralWebBrowserSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession/3237231-prefersephemeralwebbrowsersessio) this will give user more controller and reduce the login steps

**Comment by oldalton** [comment]
This is already supported by latest versions of MSAL. See details here: https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALWebviewParameters.html#/c:objc(cs)MSALWebviewParameters(py)prefersEphemeralWebBrowserSession

However, note that you'd be losing SSO with Safari and other apps if you enable it. Depending on your project requirements this might or might not be preferred.

**Comment by a-elnajjar** [comment]
thanks
