### ISSUE TITLE
interactiveTokenError: Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=Interaction is not supported in an app extension., MSALInternalErrorCodeKey=-42405

### ISSUE THREAD

**Issue by SteveDCronin** [AzureAD/microsoft-authentication-library-for-objc#772]
On iOS I am attempting to add value to an app by providing an app extension that performs similar functionality without the tedious process of 'Copy' - 'Switch App'- 'Navigate' - 'Paste' - 'perform Action'. However I do not see how to accomplish this using iOS 13 and MSAL 1.0.

If I attempt to use 'getInteractiveToken' I get this error.  If I attempt to re-use the token obtained by the host app I get a '401'.

I have been successful using both Google tools and Salesforce tools to accomplish this same task from within an app extension.

I would like to understand if obtaining tokens from inside an app extension is something that will be available in the future of if I need to reduce expectations for the MSGraph (Office) capabilities.

Can any forward looking statement be made?

**Comment by oldalton** [comment]
At the moment, you should be able to acquire a token silently if there's a token in cache. 

So this should be supported:

`If I attempt to use 'getInteractiveToken' I get this error. If I attempt to re-use the token obtained by the host app I get a '401'.`

There must be some other reason why you're getting 401. Can you provide a little bit more details on what scopes are you trying to use?

`If I attempt to use 'getInteractiveToken' I get this error.`

MSAL currently blocks all interaction within app extensions, as interaction requires presenting a web controller (ASWebAuthenticationSession). Can you provide a bit more context about your app extension (e.g. what type of extension it is)? Thanks.

**Comment by oldalton** [comment]
@SteveDCronin, did the recommendation above help? Are you still facing the issue?

**Comment by SteveDCronin** [comment]
Olga;

Thanks for responding.  11 days ago you posted a comment that posed a few questions and made it clear that I had failed to convey my problem.
You asked at one point what scopes I am requesting: @[graphContactScope,graphCategoryScope];

Here's another attempt to convey my issue.  I have a iPhone app which contains a Share Action (.appex).  For the app itself I have the entire process working.  I use MSALPublicClientApplication initWithConfiguration and then 'acquireTokenWithParameters:completionBlock:'. I store the MSALResult.accessToken in the Keychain and life is good.  It is within the app's Share Action where I run into difficulty.  I would like to use MSGraph support inside the .appex.  This would allow the user to merely select some text and then 'Share' instead of the normal 'Copy' - switch apps - 'Paste' - perform action sequence which is tedious enough but on the iPhone even more so!!

Keychain does not provide access to the accessToken retrieved by the app.  The app and the .appex are two different processes (not the same).  I have tried to re-use the access token by providing it to the appex using the sharedDefaults but the authentication process throws a 401 when the appex tries to use the accessToken obtained by the app.

So it appears to me that the .appex must present its own authentication.  I have such a flow working for Google...

You originally stated that "...you should be able to acquire a token silently if there's a token in cache..."  This does not seem to apply to my case.  Yes there is a token (obtained by the app) but it does not appear to be valid to use this token inside the .appex...  In which case it seems necessary that the .appex obtain its own token...  So later in your original message you state "...MSAL currently blocks all interaction within app extensions, as interaction requires presenting a web controller..."  

Please let me know if I can provide any further helpful details.  As of now my app has appex support for Apple Contacts, Google Contacts, Daylite Contacts, and Salesforce.  I shipped without an appex for Office365...

**Comment by oldalton** [comment]
`Keychain does not provide access to the accessToken retrieved by the app. The app and the .appex are two different processes (not the same). I have tried to re-use the access token by providing it to the appex using the sharedDefaults but the authentication process throws a 401 when the appex tries to use the accessToken obtained by the app.`

Keychain does provide a capability to share between app and the extension, as long as both your app and extension have declared the same [keychain access group](https://developer.apple.com/documentation/security/keychain_services/keychain_items/sharing_access_to_keychain_items_among_a_collection_of_apps?language=objc) and share the same App identifier prefix. You shouldn't try writing access token to user defaults, because it will expire quickly. 

Instead, you should ensure that both your app and the extension declare the same access group (`com.microsoft.adalcache` is the default). MSAL AcquireTokenSilent API should then work with no issues in your share extension.

**Comment by SteveDCronin** [comment]
> On Nov 27, 2019, at 4:56 PM, Olga Dalton <notifications@github.com> wrote:
> 
> and share the same App identifier prefix

What is ‘App Identifier prefix’? 

Do you mean Product Bundle Identifier?

app:  com.CoName.ProductName.iphone

appex:  com.CoName.ProductName.iphone.ActionName

They already do have Keychain Sharing set with a shared value of: com.CoName.ProductName.iphone.keychain

I guess I will re-run testing…  Does this require a specific version of MSAL?

Thanks for your time!
Steve

**Comment by oldalton** [comment]
ok, seems you're using a custom keychain access group. 
Can you please make sure you're telling MSAL about that group by passing it to cacheConfig. See instructions here: https://docs.microsoft.com/en-us/azure/active-directory/develop/single-sign-on-macos-ios#silent-sso-between-apps

For example:

```
let config = MSALPublicClientApplicationConfig(clientId: "<my-client-id>")
**config.cacheConfig.keychainSharingGroup = "com.CoName.ProductName.iphone.keychain"**
        
do {
	let application = try MSALPublicClientApplication(configuration: config)
  // continue on with application          
} catch let error as NSError {
  // handle error here
} 
```

And here's some more information about app id prefixes: https://developer.apple.com/library/archive/technotes/tn2311/_index.html

Generally, you don't need to worry about App Id prefixes unless you have an old app. The article has more information on possible edge-case scenarios.

**Comment by SteveDCronin** [comment]
Olga;

You’ve been patient and helpful - thank-you!

I’ve made some progress but am stuck on something I’m just not understanding:

I have 2 different app registrations @ https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/RegisteredApps <https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/RegisteredApps>

One registration is for the app itself and the other is for the ‘Action’ (.appex).
They both have the green check under ‘Certificates & secrets’
The App and the Share Action (the .appex) both have a shared ‘App Group’ and ‘Keychain Sharing’ value.

The main app behavior is working fine - no issues!
The ‘Action’ (.appex) is where I still have difficulties.

Inside the main app after I authenticate I store the access token in the Keychain.
NOTE: When the .appex initializes I CAN read this value from the Keychain.  (Keychain Sharing is working)
NOTE: Other logging shows me that the ‘App Group’ sharing is also working...

Inside the .appex I need a MSALAccount in order to use ‘MSALSilentTokenParameters’.
I need MSALPublicClientApplication in order to use ‘allAccounts’ to get the appropriate MSALAccount.

I always get an error when I try and instantiate MSALPublicClientApplication from inside the .appex:
-[XYZContactService loadMakeContactServiceCore] appContext Error: Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=The required app scheme “ msauth.xyz.abc.iphone.office365Action" is not registered in the app's info.plist file. Please add “ sauth.xyz.abc.iphone.office365Action" into Info.plist under CFBundleURLSchemes without any whitespaces and make sure that redirectURi “msauth.xyz.abc.iphone.office365Action://auth <msauth.info.swampdog.whodo.iphone.office365action://auth>" is register in the portal for your app., MSALInternalErrorCodeKey=-42001}

NOTE:  I do have that exact value registered in the Azure console (for the Action)
Actions (.appex) do not allow for ‘URL Types’ to be attached to their info.plist
In a vain hope probably have attached the 2 redirect URI from the Azure portal to the main app.


Here’s the code I am using to instantiate MSALPublicClientApplicaton:
NSError *initError;
authority = [[MSALAADAuthority alloc] initWithURL:[NSURL URLWithString:kAuthority] error:&initError];
if (initError==nil) {
	//config = [[MSALPublicClientApplicationConfig alloc] initWithClientId:kClientID_IPHONE redirectUri:nil authority:authority];
	config = [[MSALPublicClientApplicationConfig alloc] initWithClientId:kClientID_IPHONE_ACTION redirectUri:nil authority:authority];
	config.cacheConfig.keychainSharingGroup = @"com.CoName.ProductName.iphone.keychain";
	applicationContext = [[MSALPublicClientApplication alloc] initWithConfiguration:config error:&initError];
	if (initError!=nil) {
		NSLog(@"%s appContext Error: %@",__func__,initError);
	}
...
}

NOTE:  this is the same code I use in the main App, where it works fine!! (I use #ifdef ISAPPLICATION and #ifdef ISAPPEX)
I have tried this code using the clientID from the Azure portal for both the iPhone app registration (kClientID_IPHONE) as well as the iPhoneAction registration (kClientID_IPHONE_ACTION).  I get exactly the same results. 

Because I cannot get the MSALAccount I don’t understand how to proceed, as you have directed, with using ‘MSALSilentTokenParameters’.

Hopefully this is clear enough that you might be able to shed some light on what’s going on!
Thanks again for all of your help

Steve

1) Do i actually need a separate app registration in the Azure console for the .appex?

**Comment by oldalton** [comment]
@SteveDCronin, sorry for a bit of delay. I wanted to try out a sample myself before responding back. 

You don't need a separate app registration for your extension. In fact, to achieve SSO, you must use same app registration for both your app and the extension (so clientId should be the same).

Regarding the error, you're facing, you're missing a scheme registration in the Info.plist file of your app extension. 

I just verified this by creating an Action extension with MSAL. I followed following steps:

1. Open Info.plist of your extension as Source (right click -> open as -> source code)
2. Paste this to the end before the closing </dict>

```
    <key>CFBundleURLTypes</key>
    <array>
        <dict>
            <key>CFBundleURLSchemes</key>
            <array>
                <string>msauth.info.swampdog.whodo.iphone.office365action</string>
            </array>
        </dict>
    </array>
```

Try rerunning your code. Please make sure that the clientId for both main app and the extension are the same.

> Actions (.appex) do not allow for ‘URL Types’ to be attached to their info.plist

This should be possible and this is the step you're likely missing!

**Comment by oldalton** [comment]
@SteveDCronin, did you ever resolve this issue?

**Comment by SteveDCronin** [comment]
On Dec 11, 2019, at 2:19 PM, Olga Dalton <notifications@github.com> wrote:
> @SteveDCronin <https://github.com/SteveDCronin>, did you ever resolve this issue?
> 

Olga;

Yes I did!! I followed your last set of instructions and the .appex now functions exactly as expected!!  YEAH  Thank-You.

You are the only person from Microsoft who has ever responded to any inquiry I have made and you have been patient, thorough, and very helpful!
Thank-You for your time!

So I’m going to ask you this question even though I realize it is not related to your expertise at all!

___________________________
15 minutes after you sent me the email cited above I got an email from 'o365dev@microsoft.com’ with the subject: 'WARNING: Your Office 365 trial developer subscription has expired’

The body of the email contained this:
Warning: Your Office 365 trial developer subscription expired on 12/12/2019 (UTC) due to lack of development activity:

Subscription ID: xyz.onmicrosoft.com <http://xyz.onmicrosoft.com/> (not the real email!)
Your administrator access, your subscription, and all your data will be deleted on 2/10/2020 (UTC).

To avoid subscription deletion, we encourage you to take advantage of your developer subscription to develop solutions for Office 365 products and technologies, including:

Excel, Outlook, Word, and PowerPoint web add-ins
SharePoint
Microsoft Teams
Microsoft Graph
_________________
I have an active account at ‘portal.azure.com’ where I have registered my app (which we have been discussing in this thread)

What is the relationship of the Azure account and the Office 365 account noted in this email?
Is my Azure app registrations in danger due to this account being closed?
I am using Graph in the .appex files in order to create a new contact…  Am I NOT an Office 365 Developer?
As you can see I am confused - can you send this email to someone who might provide clarity or refer me to a link which would help?

Thanks Again for the straight shooting on my .appex issue - you killed it!
Steve

**Comment by jasoncoolmax** [comment]
Hi @SteveDCronin, your app registration should not be in danger as Office 365 subscription is not required to be able to register an app in Azure portal. 
For Microsoft Graph, you can contact Microsoft Graph support here: https://developer.microsoft.com/en-us/graph/support.
Hope it could help!

**Comment by manasabujji** [comment]
I always get an error when I try and instantiate MSALPublicClientApplication from inside the .appex:
-[XYZContactService loadMakeContactServiceCore] appContext Error: Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=The required app scheme “ msauth.xyz.abc.iphone.office365Action" is not registered in the app's info.plist file. Please add “ sauth.xyz.abc.iphone.office365Action" into Info.plist under CFBundleURLSchemes without any whitespaces and make sure that redirectURi “msauth.xyz.abc.iphone.office365Action://auth <msauth.info.swampdog.whodo.iphone.office365action://auth>" is register in the portal for your app., MSALInternalErrorCodeKey=-42001}
![Uploading Screenshot 2022-03-01 at 5.18.03 PM.png…]()

**Comment by manasabujji** [comment]
please tell me  how to slove the error
