### ISSUE TITLE
Provided value for the input parameter scope is not valid because it contains more than one resource

### ISSUE THREAD

**Issue by 19hours** [AzureAD/microsoft-authentication-library-for-objc#774]
I need my users to have access to two scopes, Graph api and my own api. I know this is expected behavior so my question is, should I acquire the token for one then silently acquire the token for the other when I need to access it?

```
MSALErrorDescriptionKey=AADSTS28000: Provided value for the input parameter scope is not valid because it contains more than one resource. Scope https://graph.microsoft.com/User.Read api://47d7e121-61a8-4ed5-bd16-90285e62b14d/MyAPI.All.ReadWrite openid profile offline_access is not valid.
```

**Comment by oldalton** [comment]
Yes, you can call `acquireTokenSilent` with your second resource's scopes and get a token silently.

**Comment by 19hours** [comment]
Ok. Is it good practice to store these tokens? Or is it better to acquire them before every request?

**Comment by oldalton** [comment]
MSAL will store tokens for you and refresh whenever token is expired. Just call `acquireTokenSilent` to get an access token silently, and if you get an error, call `acquireToken` (see details on error handling here: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-handling-exceptions#msal-for-ios-and-macos-errors)

**Comment by 19hours** [comment]
Okay thanks!
