### ISSUE TITLE
Error Invalid Grant keeps coming back IOS 12

### ISSUE THREAD

**Issue by DanielOuwendijk** [AzureAD/microsoft-authentication-library-for-objc#777]
Hi,

I recently got an error message when trying to call acquireTokenSilent. Every time it needs interaction from the user with the following error message: 

> Error Domain=MSALErrorDomain Code=-50002 "(null)" UserInfo={MSALErrorDescriptionKey=User interaction is required, MSALOAuthErrorKey=invalid_grant, MSALCorrelationIDKey=96348A39-2F57-45D2-8B2B-5DDA76B376E9, NSUnderlyingError=0x280d46520 {Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=AADB2C90128: The account associated with this grant no longer exists. Please reauthenticate and try again.

So when I login as required, I get a new token and it works fine. The moment I call acquireTokenSilent again, I get the same error message again and requires me to login again. 

I was wondering what the problem could be. Is it a problem with caching the refresh token? I couldn't find much on the internet, so I hope you can help me with identifying the problem.

**Comment by DanielOuwendijk** [comment]
After some more research it looks like this problem is not for IOS 13 devices. everything works fine here. But when I test for example on an Iphone 6 , I get this error.

**Comment by oldalton** [comment]
Can you please collect an MSAL log to investigate this issue?

**Comment by DanielOuwendijk** [comment]
Okay. This is my log when I open the app:

> SAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38] (Default cache) Get app metadata entries with clientId <B2C-ClientId>, environment (null)
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38] Trying to find keychain items...
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38] Keychain find status: 0
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38] Found 1 items.
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38] (Default accessor) Get accounts.
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38] Trying to find keychain items...
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38] Keychain find status: 0
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38] Found 13 items.
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38] Trying to find keychain items...
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38] Keychain find status: 0
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38] Found 3 items.
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38] (Default accessor) Looking for token with aliases (null), tenant (null), clientId <B2C-ClientId>, scopes (null)
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38] Trying to find keychain items...
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38] Keychain find status: 0
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38] Found 3 items.
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38] (Default accessor) Found 3 tokens
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38] (Default accessor) Found 3 tokens
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38] (Default accessor) Found 3 tokens
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38] Trying to find keychain items...
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38] Keychain find status: -25300
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38] Found 0 items.
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38] (Legacy accessor) Found no refresh tokens
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38] Trying to get wipe info...
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38] Get wipe info status: 0
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38] Trying to find keychain items...
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38] Keychain find status: 0
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38] Request authority cache look up for https://login.microsoftonline.com/tfp/<myTenantName>.onmicrosoft.com/B2C_1_<myPolicy>, using https://login.microsoftonline.com/tfp/<myTenantId>/B2C_1_<myPolicy> instead
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] Beginning silent flow.
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] Resolved authority, validated: YES, error: 0
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] Looking for access token...
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] (Default accessor) Looking for token with aliases (
>     "login.microsoftonline.com"
> ), tenant <myTenantId>, clientId <B2C-ClientId>, scopes https://<myTenantName>.onmicrosoft.com/ConnectingYourLoveAPI/Write https://<myTenantName>.onmicrosoft.com/ConnectingYourLoveAPI/Read https://<myTenantName>.onmicrosoft.com/ConnectingYourLoveAPI/user_impersonation
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] (Default accessor) Looking for token with aliases (
>     "login.microsoftonline.com"
> ), tenant <myTenantId>, clientId <B2C-ClientId>, scopes https://<myTenantName>.onmicrosoft.com/ConnectingYourLoveAPI/Write https://<myTenantName>.onmicrosoft.com/ConnectingYourLoveAPI/Read https://<myTenantName>.onmicrosoft.com/ConnectingYourLoveAPI/user_impersonation
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] Trying to find keychain items...
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] Keychain find status: 0
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] Found 2 items.
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] (Default accessor) Found 0 tokens
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] Access token wasn't found.
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] Looking for Family Refresh token...
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] (Default cache) Get app metadata entries with clientId <B2C-ClientId>, environment (null)
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] Trying to find keychain items...
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] Keychain find status: 0
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] Found 1 items.
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] Family Refresh token wasn't found, looking for Refresh token...
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] (Default accessor) Looking for token with aliases (
>     "login.microsoftonline.com"
> ), tenant (null), clientId <B2C-ClientId>, scopes (null)
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] (Default accessor) Looking for token with aliases (
>     "login.microsoftonline.com"
> ), tenant (null), clientId <B2C-ClientId>, scopes (null)
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] Trying to find keychain items...
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] Keychain find status: 0
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] Found 3 items.
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] (Default accessor) Found 1 tokens
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] (Default accessor) Found 1 tokens
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] (Default accessor) Found refresh token by home account id
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] Found Refresh token, using it...
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] Refreshing access token
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] Sending network request: (not-null), headers: (not-null)
> MSAL log: TID=263258 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38] session:didReceiveChallenge:completionHandler - nsurlauthenticationmethodservertrust. Host: login.microsoftonline.com. Previous challenge failure count: 0
> MSAL log: TID=263262 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] Received network response: (not-null), error (null)
> MSAL log: TID=263262 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] Parsed response: (not-null), error (null), error domain: (null), error code: 0
> MSAL log: TID=263262 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] Acquiring Access token via Refresh token...
> MSAL log: TID=263262 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] No cached preferred_network for authority
> MSAL log: TID=263262 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:38 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] Sending network request: (not-null), headers: (not-null)
> MSAL log: TID=263258 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:39 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] Received network response: (not-null), error (null)
> MSAL log: TID=263258 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:39 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] Validate and save token response...
> MSAL log: TID=263258 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:39 - 161E9167-0476-4B18-912B-9B2B09DDE66E] Creating Error with description: User interaction is required
> MSAL log: TID=263258 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:39 - 161E9167-0476-4B18-912B-9B2B09DDE66E] [MSAL] Silent flow finished result (null), error: -51115 error domain: MSIDErrorDomain
> Error Domain=MSALErrorDomain Code=-50002 "(null)" UserInfo={MSALErrorDescriptionKey=User interaction is required, MSALOAuthErrorKey=invalid_grant, MSALCorrelationIDKey=161E9167-0476-4B18-912B-9B2B09DDE66E, NSUnderlyingError=0x2829364c0 {Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=AADB2C90128: The account associated with this grant no longer exists. Please reauthenticate and try again.
> 
> Correlation ID: 2f282bfc-c14d-4d49-976f-3ab28aabfa32
> 
> Timestamp: 2019-11-21 08:44:38Z
> 
> , MSALOAuthErrorKey=invalid_grant, MSALCorrelationIDKey=161E9167-0476-4B18-912B-9B2B09DDE66E, MSALInternalErrorCodeKey=-42004}}}
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:39 - 12618FA6-9AB5-495C-9C5D-DE21D5821F11] [MSAL] Beginning interactive flow.
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:39 - 12618FA6-9AB5-495C-9C5D-DE21D5821F11] [MSAL] Resolved authority, validated: YES, error: 0
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:39 - 12618FA6-9AB5-495C-9C5D-DE21D5821F11] [MSAL] Sending network request: (not-null), headers: (not-null)
> MSAL log: TID=263258 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:39 - 12618FA6-9AB5-495C-9C5D-DE21D5821F11] [MSAL] Received network response: (not-null), error (null)
> MSAL log: TID=263258 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:39 - 12618FA6-9AB5-495C-9C5D-DE21D5821F11] [MSAL] Parsed response: (not-null), error (null), error domain: (null), error code: 0
> MSAL log: TID=263147 MSAL 1.0.3 iOS 12.4.2 [2019-11-21 08:44:39] Start background app task with type 0

**Comment by DanielOuwendijk** [comment]
So, any idea what the problem is? I am still not able to figure it out

**Comment by DanielOuwendijk** [comment]
Okay, now it works again. After logging out and deleting my app and then reinstalling, it works like normal.  If the problem stays gone, i'll close the issue in a few days.

**Comment by oldalton** [comment]
@DanielOuwendijk, I took a closer look at your logs, and one thing that might be happening is that account you're using doesn't match the policy in your authority URL.

For B2C scenarios, you cannot use account retrieved for one policy for other policies (e.g. you get an account as a result of performing a sign-in policy, you cannot silently get a token for password reset policy with the same account). 

Can you please confirm that the you're using same policyId for silent acquireToken request as you were using for the interactive token acquisition?

**Comment by DanielOuwendijk** [comment]
Yes, I can confirm. It is the same for all functions.

 I do know though, that the problem started when I logged out. When I tried logging back in, the problem popped up. 

I just tested logging out and logging back in and everything works fine. I guess it was a one off...?

**Comment by oldalton** [comment]
Perhaps, just want to make sure there's no bug here. When you're saying "logout" - do you mean logout in the browser? or calling MSAL's removeAccount() API? Thanks.

**Comment by DanielOuwendijk** [comment]
When I'm logging out, I'm calling MSAL's removeAccount() API

**Comment by DanielOuwendijk** [comment]
Alright, I'm closing the issue now. Thank you for your help!
