### ISSUE TITLE
WKWebView shared sessions

### ISSUE THREAD

**Issue by tritter** [AzureAD/microsoft-authentication-library-for-objc#780]
Whenever Im Authenticated with my Application I get a GraphToken and everything works. But whenever I try to open a Word document from OneDrive or the a SharePoint page it asks again for a login. I use the default WKWebView for that, it seems that the SSO session is not shared there. 

How can I get this to work?

**Comment by oldalton** [comment]
WKWebView doesn't support sharing cookies between multiple processes.
However, we support some other ways to achieve SSO. See guidance here: https://docs.microsoft.com/en-us/azure/active-directory/develop/single-sign-on-macos-ios

**Comment by oldalton** [comment]
Closing this question, please reopen if needed.
