### ISSUE TITLE
Default authorization with MSAL swift

### ISSUE THREAD

**Issue by alfetch** [AzureAD/microsoft-authentication-library-for-objc#800]
Hi all

I know this is not an issue, but i don't know where to ask for it. So please just close the issue when it's answered. 

I need answer for this question: Is MSAL for IOS (also Android) using authorization code as default response_type and not implicit flow (accesstoken) - further is PKCE default used, or should the client do something to enable it? 

thanks in advance.

**Comment by oldalton** [comment]
Yes, MSAL for iOS and Android uses authorization code flow, and doesn't support implicit flow. PKCE is enabled by default.

**Comment by alfetch** [comment]
> Yes, MSAL for iOS and Android uses authorization code flow, and doesn't support implicit flow. PKCE is enabled by default.

Thanks a lot :+1:
