### ISSUE TITLE
Unable to switch accounts after login

### ISSUE THREAD

**Issue by fangios** [AzureAD/microsoft-authentication-library-for-objc#805]
After logging into your account with the latest version, you cannot switch accounts the next time you open the authorization login page. The old version can. Can you help me see how to solve this problem?

**Comment by oldalton** [comment]
Old MSAL versions were sending prompt=select_account by default. This behavior changed in the latest MSAL versions, so account selection screen is not going to be shown by default. 

You can override this behavior by explicitly specifying prompt=select_account in MSAL. See documentation here: https://azuread.github.io/microsoft-authentication-library-for-objc/Enums/MSALPromptType.html#/c:@E@MSALPromptType@MSALPromptTypeSelectAccount

**Comment by fangios** [comment]
Thanks

**Comment by jasoncoolmax** [comment]
Please reopen the issue if you still experience the same issue.
