### ISSUE TITLE
how to update code to use Keychain instead of UserDefaults  

### ISSUE THREAD

**Issue by a-elnajjar** [AzureAD/microsoft-authentication-library-for-objc#806]
I want to ask how can I update the example code to store the currentAccountIdentifier I want to use keychain instead of UserDefaults 

    var currentAccountIdentifier: String? {
        get {
            return UserDefaults.standard.string(forKey: kCurrentAccountIdentifier)
        }
        set (accountIdentifier) {
            // The identifier in the MSALAccount is the key to retrieve this user from
            // the cache in the future. Save this piece of information in a place you can
            // easily retrieve in your app. In this case we're going to store it in
            // NSUserDefaults.
            UserDefaults.standard.set(accountIdentifier, forKey: self.kCurrentAccountIdentifier)
        }
    }

**Comment by oldalton** [comment]
I assume this issue got resolved?
