### ISSUE TITLE
using url endpoint "https://{tenant}.b2clogin.com/" instead of "https://login.microsoftonline.com/

### ISSUE THREAD

**Issue by a-elnajjar** [AzureAD/microsoft-authentication-library-for-objc#818]
We are trying to use "https://{tenant}.b2clogin.com/"  instead of "https://login.microsoftonline.com/"  in swift code. because we have "Invalid Azure B2C Token Issuer invalid ". our resource endpoints will accept a token issued form URL auth "https://{tenant}.b2clogin.com/" endpoint, on the other hand, it will reject any token form issued from URL auth "https://login.microsoftonline.com/".

**Comment by jasoncoolmax** [comment]
Hi @a-elnajjar, may I know more details about the issue you are facing? What issue do you face when you change your authroity to `your-tenant-name.b2clogin.com`?

**Comment by a-elnajjar** [comment]
yes, can we override authority URL form "https://login.microsoftonline.com/"  to your-tenant-name.b2clogin.com?

**Comment by jasoncoolmax** [comment]
Yes, you can use the `your-tenant-name.b2clogin.com` format authority in MSAL. More details could be found [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/config-authority#b2c). Let me know if you need any further help.

**Comment by a-elnajjar** [comment]
thanks
