### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by odarynakorolevych** [AzureAD/microsoft-authentication-library-for-objc#819]
In this issue https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/796 was stated that the fix will be part of your next release. But in the release 1.0.6 I don't see these changes and these changes are very important for us.

How much time do we need to wait for this fix to be released?

**Comment by jasoncoolmax** [comment]
Hi @odarynakorolevych, the release 1.0.6 was finalized before the issue was addressed. In #796, the `next release` actually mean the next release after 1.0.6. Sorry for the confusion. For the time line of next release, let me collect more info tomorrow before I could provide you more info.

**Comment by oldalton** [comment]
Fixed in 1.1.0. Closing the issue.
