### ISSUE TITLE
Clicking on "forgotten password policy link" returns -50000 error code

### ISSUE THREAD

**Issue by Nasicus** [AzureAD/microsoft-authentication-library-for-objc#822]
I use MSAL for B2C and when I click on the "Forgot my password" link on my "SignUp" policy I don't receive a good error code, but only `-50000`  which isn't helpful since this is the default error code (`https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/4084ea19902c9081fd37e5654d9df1dbc4a1f075/MSAL/src/public/MSALError.h`).

When I enable verbose logging and stuff I can see that somewhere is another error code:
`Interactive flow finished result (null), error: -51440 error domain: MSIDOAuthErrorDomain`
However I cannot find a documentation for it, plus I don't know how to even access this error code from the error object.

So my question:
- How should I handle this currently?

**Comment by rohitnarula7176** [comment]
@Nasicus Thank you for reporting this. We were able to reproduce this issue. Currently in MSAL we do not handle the error "access_denied". 

A workaround you can use is to handle this error description below "AADB2C90118:+The+user+has+forgotten+their+password" and once you receive it, redirect the user to password reset page.

Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=AADB2C90118:+The+user+has+forgotten+their+password.
Correlation+ID:+7553500f-d946-43c1-a7a4-c4b94727c09b
Timestamp:+2020-01-22+18:11:06Z
, MSALOAuthErrorKey=access_denied, MSALInternalErrorCodeKey=-42104}
