### ISSUE TITLE
Server returned less scopes than requested

### ISSUE THREAD

**Issue by eltonjhony** [AzureAD/microsoft-authentication-library-for-objc#832]
Hi,

I'm trying to use the Authorization code flow to connect on my B2C instance and I'm receiving an error validation that the MSAL library is performing after the requests.

I saw in the logs that I could make the ```/authorize``` and the ```/token``` requests, and I have received the response that I needed from Azure AD (Ex.: accessToken, refreshToken, idToken, etc..). However, the lib is performing a validation after it and is giving me the following error:

```
Error Domain=MSALErrorDomain Code=-50003 "(null)" UserInfo={MSALDeclinedScopesKey=(
    "496d9127-5493-4d0b-b98b-e3d8fb2e557e"
), MSALGrantedScopesKey=(
    "/"
), MSALErrorDescriptionKey=Server returned less scopes than requested, MSALInvalidResultKey=<MSALResult: 0x6000014d0420>}
```

That's the configs I'm using:
```
endpoint: "https://b2biamgbusdev.b2clogin.com/b2biamgbusdev.onmicrosoft.com"
policy: "BFDJ2BCSignin_DR" -> (Fake policy - just to illustrate)
scopes: ["4962749827428y4824y2"] -> This is my clientId (not the real one - just to illustrate)
clientId: "4962749827428y4824y2"
```

That's the code to init the MSAL library:
```
private func initMSAL() throws {

	guard let authorityURL = URL(string: "\(configuration.endpoint)/\(configuration.policy)") else {
		return
	}

	let authority = try MSALB2CAuthority(url: authorityURL)


	let msalConfiguration = MSALPublicClientApplicationConfig(clientId: configuration.clientId, redirectUri: "\(configuration.scheme)\(configuration.redirectUri)", authority: authority)
	msalConfiguration.knownAuthorities = [authority]

	applicationContext = try MSALPublicClientApplication(configuration: msalConfiguration)
}
```

**Comment by oldalton** [comment]
Can you please make sure that the client_id that you're passing as a scope is indeed valid? B2C will ignore any scopes in your request that it doesn't recognize. When MSAL is processing result, it verifies that you receive a token for all scopes you requested and notify you when it is not the case. Based on your error description it looks like that is what is happening, so next step should be understanding why B2C doesn't recognize your requested scope. 

Could you also check some settings in your app registration? Specifically if you have enabled "Include web app / web API" and "Allow implicit flow" and let me know how you have it configured.

**Comment by eltonjhony** [comment]
Hi @oldalton 

We did some adjustments in our Azure settings and the issue has been fixed. 
Thanks! I'll close this issue.

**Comment by oldalton** [comment]
Thanks for an update, @eltonjhony. Do you know which setting was updated exactly? This could help other developers running into the same issue :)
