### ISSUE TITLE
ADAL Error to MSAL Error mappings for migration

### ISSUE THREAD

**Issue by bullsseye** [AzureAD/microsoft-authentication-library-for-objc#842]
There are two different error codes returned via ADAL **ERROR_SERVER_USER_INPUT_NEEDED** and **ERROR_SERVER_REFRESH_TOKEN_REJECTED** for which I could not find corresponding error codes in MSAL.

If these errors are distinguished inside **InteractionRequired** via description in userInfo, please let me know these descriptions as I could not find it in the documentation

**Comment by oldalton** [comment]
Thanks for the question. I recommend to take a look at [MSAL error handling guide](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-handling-exceptions?tabs=iosmacos#msal-for-ios-and-macos-errors). MSAL improved error handling over ADAL significantly and there're only a handful of errors you need to handle.

To answer your specific question, both ERROR_SERVER_USER_INPUT_NEEDED and ERROR_SERVER_REFRESH_TOKEN_REJECTED map to MSALErrorInteractionRequired. If you want to understand the reason for interaction required, I recommend taking a look at additional userInfo in the error object. For example, you can find out OAuth error code returned by the server in the userInfo under MSALOAuthErrorKey key (corresponding to ERROR_SERVER_REFRESH_TOKEN_REJECTED). See here: https://azuread.github.io/microsoft-authentication-library-for-objc/Constants.html#/c:@MSALOAuthErrorKey

**Comment by oldalton** [comment]
Closing the issue. Feel free to reopen if you still have questions. Thanks.
