### ISSUE TITLE
How to intercept requests inside the WebView

### ISSUE THREAD

**Issue by eltonjhony** [AzureAD/microsoft-authentication-library-for-objc#843]
Hi,

I have a situation using MSAL lib where I need to intercept some clicks inside the ```WebView``` to take some actions. 

For example, in the following screen, if the user taps the forgot password link, I want to intercept this click to take an action on the native app. 
<img width="395" alt="Screenshot at Feb 01 16-36-06" src="https://user-images.githubusercontent.com/25302517/73598007-70f3ae00-4511-11ea-90a9-27354db408df.png">

Probably, I will have more than one case like this one on the same screen.

Since I cannot override the ```WKNavigationDelegate``` using a ```customWebView```, how can I handle that using MSAL lib?

**Comment by oldalton** [comment]
If you're using custom links, one thing you can do is to mimic OAuth responses in your redirects. For example, for the "forgot password link" in your example, you can return a standard response starting with your Redirect Uri:

If your Redirect Uri is `msauth.com.microsoft.msaltestapp://auth`

You can return:

`msauth.com.microsoft.msaltestapp://auth?error=access_denied&error_description=<your error message>&state=<your OAuth state>`

MSAL would return you this as a result:

`Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=<your error message>, MSALOAuthErrorKey=access_denied, MSALInternalErrorCodeKey=-42104}`

`MSALOAuthErrorKey` key returns `error` returned as a result. MSALErrorDescriptionKey returns `error_description` 

Note that this is just an example and you can return different error code and message. This method would work with both WKWebView and ASWebAuthenticationSession (the latter is the recommended way). 

For password reset specifically, B2C should already return default error information. See more information here: https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/822

Let me know if that answers your question.

Thanks

**Comment by eltonjhony** [comment]
Hi @oldalton 

Thanks for the response :)

That would be enough for us.
