### ISSUE TITLE
Build Failure using pods

### ISSUE THREAD

**Issue by ledzep9012** [AzureAD/microsoft-authentication-library-for-objc#849]
Getting multiple semantic issues while building the app with MSAL pod.

`pod 'MSAL', '~> 1.0'`

Build Error:
![image](https://user-images.githubusercontent.com/19204594/74326858-27c51900-4db1-11ea-8012-b4bce10aff03.png)

**Comment by oldalton** [comment]
Looks like submodule is incorrectly downloaded. What CocoaPods version are you using?
Can you try rerunning "pod update"?

**Comment by ledzep9012** [comment]
Its still the same, I'm using cocoapods version 1.8.4

**Comment by ledzep9012** [comment]
my podfile was missing `use_frameworks!`, closing this issue.

**Comment by ledzep9012** [comment]
I also had `ADAL` dependency in podfile, removed that and it worked. Closing this.
