### ISSUE TITLE
Authority fails validation during login

### ISSUE THREAD

**Issue by jeffgilbert** [AzureAD/microsoft-authentication-library-for-objc#851]
In my app, when I complete the login form I get a -51100 error "Authentication response received without expected" from `[MSIDB2COauth2Factory verifyResponse:context:error:]` (called from `[MSIDTokenResponseValidator  validateTokenResponse:…]`).

Inside `[MSIDB2CAuthority isAuthorityFormatValid:context:error:]` it is parsing a url that looks like https://foobar.b2clogin.com/<tenant>/v2.0/

It is checking that it is a b2c authority, and since it does not have tfs as the 2nd component of the URL it fails with an MSIDErrorInternal error.

Are b2c urls required to have tfs in their path?

NB I did not configure the account setup for MSAL. Is there anything I can ask the people that did?

**Comment by oldalton** [comment]
No, you can use your custom B2C authority, but you need a few extra steps.
See guidance here: https://docs.microsoft.com/en-us/azure/active-directory/develop/config-authority#b2c

Let me know if that helps. Thanks!

**Comment by jeffgilbert** [comment]
Thanks for the additional info. I was setting the knownAuthorities when receiving that error. Here is what my login function looks like. Does everything else look reasonable?

```
    func login()
    {
        let authorityURL: URL = "https://foobarauth.b2clogin.com/foobarauth.onmicrosoft.com/B2C_1_signupin"
        guard let authority = try? MSALB2CAuthority(url: authorityURL) else { return }
        let config = MSALPublicClientApplicationConfig(clientId: <clientID>, redirectUri: <redirectURL>, authority: authority)
        config.knownAuthorities = [authority]
        
        let scopes: [String] = []
        
        if let application = try? MSALPublicClientApplication(configuration: config) {
                    
            let viewController = self // Pass a reference to the view controller that should be used when getting a token interactively
            let webviewParameters = MSALWebviewParameters(parentViewController: viewController)
            
            let interactiveParameters = MSALInteractiveTokenParameters(scopes: scopes, webviewParameters: webviewParameters)
            interactiveParameters.promptType = .selectAccount
            interactiveParameters.authority = try? MSALB2CAuthority(url: authorityURL)

            application.acquireToken(with: interactiveParameters, completionBlock: { (result, error) in
                guard let authResult = result, error == nil else
                {
                    print(error!.localizedDescription)
                    return
                }
                
                // Get access token from result
                let _ = authResult.accessToken
                
                // You'll want to get the account identifier to retrieve and reuse the account for later acquireToken calls
                let _ = authResult.account.identifier
            })
        }
        else
        {
            print("Unable to create application.")
        }
    }
```

Do we need to have any scopes defined? The backend team has not defined any scopes.

**Comment by oldalton** [comment]
Yes, maybe you're getting an error because access token is not returned. I've added a feature request to track this: https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/852

In the meantime, you can try passing your "clientId" as a scope. Or you can follow steps here: https://github.com/Azure-Samples/active-directory-b2c-ios-swift-native-msal/issues/28#issuecomment-586553656

**Comment by jeffgilbert** [comment]
I got it working! I really appreciate all your time and help with this!

I ended up passing a scope that the backend had previously defined. My backend lead thought I didn't need to use a scope because we aren't using Azure JWTs in a stateless manner (or words to that effect, which I don't understand :-)

**Comment by jasoncoolmax** [comment]
Close as issue is resolved.
