### ISSUE TITLE
Xcode 11.3.1 Cathage is failed to build framework from master 

### ISSUE THREAD

**Issue by alokc83** [AzureAD/microsoft-authentication-library-for-objc#853]
I am using this 
github "AzureAD/microsoft-authentication-library-for-objc" "master" 
in cart file. 

carthage update --platform ios 

it fails and give this error: 
** ARCHIVE FAILED **

The following build commands failed:
	CompileC /Users/XXXXXXXX/Library/Caches/org.carthage.CarthageKit/DerivedData/11.3.1_11C504/microsoft-authentication-library-for-objc/49949c48e510762b9a8d4e8036724f9d050ee187/Build/Intermediates.noindex/ArchiveIntermediates/MSAL\ (iOS\ Framework)/IntermediateBuildFilesPath/MSAL.build/Release-iphoneos/MSAL\ (iOS\ Framework).build/Objects-normal/arm64/MSALADFSAuthority.o /Users/XXXXXXX/Documents/XXXXXXXXX/APP-ios/Carthage/Checkouts/microsoft-authentication-library-for-objc/MSAL/src/instance/MSALADFSAuthority.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

**Comment by alokc83** [comment]
As well as on release 1.0.7. Is anyone else is having the same issue?

**Comment by rohitnarula7176** [comment]
@alokc83 Thank you for reporting this. I tried to install the msal framework using Carthage and it worked for me for both master branch and release 1.0.7. 
Can you please try cleaning your Carthage cache (rm -rf ~/Library/Caches/org.carthage.CarthageKit) and retrying it. 
Is that does not help, Can you attach the full verbose logs of the xcodebuild output you are seeing.

**Comment by alokc83** [comment]
You were absolutely right. It was the cache that was causing the build to fail.  Thank you so much @rohitnarula7176
