### ISSUE TITLE
How to intercept Conditional Policy Error using MSAL?

### ISSUE THREAD

**Issue by ledzep9012** [AzureAD/microsoft-authentication-library-for-objc#855]
I'm getting following error while trying to do a `acquireTokenWithParameters:`
![image](https://user-images.githubusercontent.com/19204594/74878829-fc809200-538d-11ea-9a7a-16e714160643.png)

How do I intercept this error and call Intune Methods to apply CA policy?
I'm handling `MSALErrorServerProtectionPoliciesRequired` in my completionBlock and calling Intune's `remediateComplianceForIdentity` for that particular UPN. Am I Missing something? 

This happens in MSAL version 0.8.0 and 1.0.6.

Thanks

**Comment by oldalton** [comment]
Thanks for reporting this issue. We will take a look at your logs and follow up. Just so that we fully understand the scenario, are you trying to build a new app integrated with Intune MAM SDK?

**Comment by ledzep9012** [comment]
Yes that's correct. I'm integrating Intune SDK with MSAL in a LOB app.

**Comment by NicolasLourenco** [comment]
Hello, I'm facing the same issue. Any update on this?

**Comment by ledzep9012** [comment]
> Hello, I'm facing the same issue. Any update on this?

it was fixed for me in 1.1.5.

**Comment by NicolasLourenco** [comment]
Did you try to update to the latest version to see if there's a regression?

**Comment by ledzep9012** [comment]
No, I didn't.
