### ISSUE TITLE
Is there a way to perform incremental and dynamic consent using MSAL for iOS?

### ISSUE THREAD

**Issue by Poornima-singh** [AzureAD/microsoft-authentication-library-for-objc#858]

**Comment by Poornima-singh** [comment]
I am trying to get authorization over two resources microsoft graph api and SharePoint REST API. But the code only shows how to get access token for single resource. How can I get access token which is valid for microsoft graph api as well as SharePoint REST calls?

**Comment by oldalton** [comment]
Thanks for the question. Each access token can only be issued for a single resource. So you cannot request an access token for multiple resources.

However, if you want to collect consent for multiple resources at the time, you can pass your additional scopes as "extraScopesToConsent" by specifying them in this API: https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALInteractiveTokenParameters.html#/c:objc(cs)MSALInteractiveTokenParameters(py)extraScopesToConsent

So, you can do following:
1. Step1: Call acquireToken with:
- scopes: Microsoft Graph scopes
- extra scopes to consent: Sharepoint scopes
Result: user will be asked for consent for both Microsoft Graph and Sharepoint scopes. You'll get an access token for Microsoft Graph.

2. Step 2: Call acquireTokenSilent with:
- account: account identifier from step 1
- scopes: Sharepoint scopes
Result: This should now silently return an access token for Sharepoint scopes. Note that there're edge cases related to conditional access where this might not work silently, and you'd need to go to step 3. In most cases this should work silently.

3. Step 3: Execute only if step 2 returns MSALInteractionRequired
- account: account identifier from step 1
- scopes: Sharepoint scopes
Result: This will execute additional conditional access policies if needed and return an access token for Sharepoint scopes. 

Hope it helps!

**Comment by Poornima-singh** [comment]
Hello Olga, 

query 1: what is the difference between step 2 and step 3? step 2 makes call to acquireTokenSilent, and what does step 3 makes call to?

query 2: I tried the combination of step 1 and 2 but I find the errors stating that the call is not able to find refresh token . Apparently it tries to fetch refresh token from acquireToken call response, but this call only responds with accesstoken and idtoken.

Really appreciate your help!

**Comment by Poornima-singh** [comment]
Another finding, now my app is able to find the refresh token but when it tries to get access token using refresh token it gets error:
No registration information found.
Received PKeyAuth request but no WPJ info..
then it throws AAD error, invalid_client

**Comment by Poornima-singh** [comment]
One more update, it works fine on our development tenant of O365 where MFA is not used, but gives the above error on production tenant where MFA is being used. Hope it helps to identify the roadblock.

**Comment by oldalton** [comment]
Thanks for the information. It likely means that you have additional device based conditional access requirements for the second resource. Just to confirm - are you getting MSALInteractionRequired error for the silent call, or MSALErrorInternal? If it is the latter, looks like we need to apply a fix. 

To clarify, step nr 3 should be acquireToken call.

**Comment by Poornima-singh** [comment]
Yes, it ends with MSALErrorInternal -50000

**Comment by Poornima-singh** [comment]
<img width="175" alt="MSALerror" src="https://user-images.githubusercontent.com/54657738/75743408-ec29c900-5d36-11ea-9929-97c0fec52c68.PNG">

Really sorry for the bad image, this is the exact queue of error

**Comment by Poornima-singh** [comment]
Hi Olga, 

any update on this?

**Comment by oldalton** [comment]
@Poornima-singh, Sorry for a late reply. It looks like your application is misconfigured and is marked as a confidential client in the directory. 

Can you please double check your application registration and make sure that:
1. You have registered Redirect URIs with the type of "Public client"
2. This setting is turned on "Default client type - public client - YES" (it is under authentication tab of your app registration)

**Comment by Poornima-singh** [comment]
Hello Olga,

Thank you for replying. I did check the two configurations you mentioned. 

1.  We have added three types of redirect urls
- Web
- iOS / macOS
- Mobile and desktop applications

but we are running the code or trying to login via iOS app.

2. Setting for Default client type - public client - is already YES. 

:(

**Comment by rohitnarula7176** [comment]
@Poornima-singh We are still looking into this issue and will get back once we have an update.

**Comment by oldalton** [comment]
Updating status to avoid issue being closed, since it hasn't been yet resolved.

**Comment by jasoncoolmax** [comment]
@Poornima-singh Could you try to create a new application and see if the issue still persists? We used to have some server side regression. If issuer persists, could you please share with me the correlation id again? Thank you!

**Comment by AhmadiRamin** [comment]
Hi @oldalton I'm trying to replace your suggested steps in my office addins project (nodejs)
I can get the access token in step 1, but I don't know how to call it again (step 2):
here is my code:

`

import * as Msal from "msal";
import configuration from "../utilities/configuration";
import { ImplicitMSALAuthenticationProvider } from "@microsoft/microsoft-graph-client/lib/src/ImplicitMSALAuthenticationProvider";
import {MSALAuthenticationProviderOptions} from '@microsoft/microsoft-graph-client/lib/src/MSALAuthenticationProviderOptions';
import { AuthenticationParameters } from "msal";

Office.initialize = function() {
  if (Office.context.ui.messageParent) {
    userAgentApp.handleRedirectCallback(authCallback);
    // The very first time the add-in runs on a developer's computer, msal.js hasn't yet
    // stored login data in localStorage. So a direct call of acquireTokenRedirect
    // causes the error "User login is required". Once the user is logged in successfully
    // the first time, msal data in localStorage will prevent this error from ever hap-
    // pening again; but the error must be blocked here, so that the user can login
    // successfully the first time. To do that, call loginRedirect first instead of
    // acquireTokenRedirect.
    if (localStorage.getItem("loggedIn") === "yes") {      
        userAgentApp.acquireTokenRedirect(requestObj);
    } else {
      // This will login the user and then the (response.tokenType === "id_token")
      // path in authCallback below will run, which sets localStorage.loggedIn to "yes"
      // and then the dialog is redirected back to this script, so the
      // acquireTokenRedirect above runs.
      userAgentApp.loginRedirect(requestObj);
    }
  }
};

const msalConfig: Msal.Configuration = {
  auth: {
    clientId: configuration.clientId, //This is your client ID
    authority: "https://login.microsoftonline.com/common",
    redirectUri: "https://localhost:3000/fallbackauthdialog.html",
    navigateToLoginRequestUrl: false
  },
  cache: {
    cacheLocation: "localStorage", // Needed to avoid "User login is required" error.
    storeAuthStateInCookie: true // Recommended to avoid certain IE/Edge issues.
  }
};

const scopes = ['User.Read','Mail.ReadWrite'];
const extraScopesToConsent = [`https://mytenant.sharepoint.com/.default`];

var requestObj: AuthenticationParameters = {
  scopes,
  extraScopesToConsent
};

const userAgentApp: Msal.UserAgentApplication = new Msal.UserAgentApplication(
  msalConfig
);

const options = new MSALAuthenticationProviderOptions(scopes);
const authProvider = new ImplicitMSALAuthenticationProvider(userAgentApp, options);


function authCallback(error, response) {
  if (error) {
    Office.context.ui.messageParent(JSON.stringify({ status: "failure", result: error }));
  } else {
    if (response.tokenType === "id_token") {
      localStorage.setItem("loggedIn", "yes");
    } else {

      Office.context.ui.messageParent(JSON.stringify({ status: "success", result: response.accessToken, authProvider }));
    }
  }
}
`

Should I go through this process again?

**Comment by oldalton** [comment]
@AhmadiRamin, this looks like MSAL JS issue. Would you mind opening it in the correct repository? Thanks.
