### ISSUE TITLE
Retrieve token from cache

### ISSUE THREAD

**Issue by spyrosskordos** [AzureAD/microsoft-authentication-library-for-objc#862]
How can I retrieve token from keychain.I get the account but there is no a property for token

**Comment by oldalton** [comment]
You'd need to call acquireToken or acquireTokenSilent API. There'll be an accessToken and idToken in the result. See guidance in MSAL readme: https://github.com/AzureAD/microsoft-authentication-library-for-objc#objective-c

**Comment by rohitnarula7176** [comment]
Closing this issue for now. Please reopen if you still have any issues.
