### ISSUE TITLE
Provide acquireTokenSilent synchronously

### ISSUE THREAD

**Issue by eltonjhony** [AzureAD/microsoft-authentication-library-for-objc#866]
Hi all,

Can you guys provide in MSAL lib for IOS a way to `acquireTokenSilent` synchronously just like we have for Android lib: https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/java/com/microsoft/identity/client/IMultipleAccountPublicClientApplication.java line 129

We have a scenario here in our business that requires a synchronous call for this method.

All the best!

**Comment by oldalton** [comment]
Thanks for the suggestion. What Android library is doing is wrapping asynchronous request with a synchronous API by using a lock/semaphore and blocking the current thread until the response is received. So essentially the API is still asynchronous. You could easily replicate this in your code by calling MSAL acquireTokenSilent and making it synchronous with locks. Would that help to address your scenario?

**Comment by eltonjhony** [comment]
Yes! Absolutely @oldalton!

**Comment by oldalton** [comment]
Thanks for the confirmation, @eltonjhony. Please close this issue if that addresses your scenario. Feel free to reopen if you're having any new issues with this approach.

**Comment by eltonjhony** [comment]
@oldalton Can you let me know when we have another release with this suggested feature?

**Comment by rohitnarula7176** [comment]
@eltonjhony We assume this code as part of what the developer can integrate in his codebase if they need to call this api in a synchronous manner. We do not have any plans of adding this to our codebase yet. Please let us know if you need guidance on how to implement this.

**Comment by eltonjhony** [comment]
Ok @rohitnarula7176 ! Thanks for the response.
