### ISSUE TITLE
Please provide a way to programmatically retrieve the SDK version number

### ISSUE THREAD

**Issue by ovolab** [AzureAD/microsoft-authentication-library-for-objc#878]
Please provide a way for the client app to retrieve the version number (or string) of the MSAL iOS SDK. I see this symbol is declared in the MSAL.h header file:

```C
FOUNDATION_EXPORT const unsigned char MSAL__Framework_VersionString[];
```

But it doesn't seem to be defined anywhere, and in fact I'm getting a link-time error if I try to use it.

**Comment by oldalton** [comment]
Thanks for the suggestion. Can you please provide a little more information about the scenario where you would need to know MSAL version? This would help us to understand how you're using MSAL a little bit better. Thanks.

**Comment by ovolab** [comment]
A standard feature of the apps we develop is an “about box” where we list all 3rd-party SDKs we use, along with their version numbers.  While we release app updates on a regular basis, some users aren’t quick to update to the latest release, especially in corporate, B2B scenarios.

When our help desk receives a support request for an issue that may involve a 3rd-party component, we ask the reporter to copy the about box text so we know exactly which versions of the SDKs were current at build time.

So, the version number API I’m requesting would be for informative purposes only.  We are not going to take runtime decisions based on the SDK version.

**Comment by jasoncoolmax** [comment]
Thank you for the feature request. We are considering adding the API in future release.

**Comment by kaisong1990** [comment]
@ovolab We added a class property to get SDK version form ```MSALPublicClientApplication```:

```MSALPublicClientApplication.sdkVersion```

Thanks for your feedback
