### ISSUE TITLE
Pressing "cancel" triggers MSALErrorInternal

### ISSUE THREAD

**Issue by richardtop** [AzureAD/microsoft-authentication-library-for-objc#882]
Hi, I found an issue when pressing "cancel" in the authorisation dialog:

![77307414-dc801d80-6d01-11ea-9c83-306a5bb329cf](https://user-images.githubusercontent.com/8013017/79423317-140f7c00-7fc7-11ea-8ca1-25d071899421.png)

The MSAL library returns internal error:
<img width="556" alt="Skärmavbild 2020-03-23 kl  12 24 18" src="https://user-images.githubusercontent.com/8013017/77307114-5a8ff480-6d01-11ea-8261-55b38d8d0a66.png">

However, I think the error "User Cancelled" is more appropriate here:
```Objective-C
    
    /**
     The user cancelled the web auth session by tapping the "Done" or "Cancel" button in the web browser.
     Handling of this error is optional.
     */
    MSALErrorUserCanceled                        = -50005,
```

Having this issue requires actually inspecting an `MSALErrorInternal` and doing additional handling of it on the client side, instead of just logging the error. And, in case it's "user cancelled" error, it would be ignored by the client (since the user has an option to re-initiate login again).

To me it looks like an error in the library, since the description of the `MSALErrorUserCanceled ` perfectly matches my actions, but I'm getting a completely different error in code.

Relevant part of the client-side code:
```Swift

    private let msalApplication: MSALPublicClientApplication

    @objc func acquireTokenInteractively(viewController: UIViewController,
                                   loginHint: String? = nil,
                                   msalAccount: MSALAccount? = nil,
                                   completionBlock: @escaping MSALCompletionBlock) {
        let webViewParameters = MSALWebviewParameters(parentViewController: viewController)

        let params = MSALInteractiveTokenParameters(scopes: [], webviewParameters: webViewParameters)
        params.promptType = .default
        params.loginHint = loginHint
        params.account = msalAccount

        msalApplication.acquireToken(with: params, completionBlock: completionBlock)
    }

```

**Comment by oldalton** [comment]
Thanks for raising this issue. We need to look a little bit closer in all possible scenarios that can trigger an "access_denied" error from STS. Those errors might not necessarily always translate to end user visible cancellation, so we want to make sure that returning MSALErrorUserCanceled would be the right thing before we make the change. For now, you can get the error code from the internal error details.

**Comment by richardtop** [comment]
Hi Olga, thanks for a quick reply. This bug makes `MSALErrorUserCanceled` lose its meaning since now every error has to be inspected deeply which results in complication of the client code. I'd be very happy if this gets fixed.

**Comment by oldalton** [comment]
This should be fixed in MSAL 1.1.2: https://github.com/AzureAD/microsoft-authentication-library-for-objc/releases/tag/1.1.2. Please give it a try and let us know if you're still seeing this issue. Thanks!

**Comment by richardtop** [comment]
Hi Olga, thanks for a quick fix. The solution works for me and I was able to remove any client-side error conversion from my application.

However, I'd like to ask is there a possibility of interfering with a real "access denied" error, e.g. if the user doesn't have access to the resource?

In my solution, I was checking for the string "because+user+declined" in the `userinfo`:

```Swift
    private func patchInternalErrorIfUserCancelledSignOn(_ error: Error?) -> Error? {
        if let msalError = error as NSError? {
            if msalError.code == MSALError.internal.rawValue {
                if let description = msalError.userInfo[MSALErrorDescriptionKey] as? String {
                    if description.contains("because+user+declined") {
                        return NSError(domain: MSALErrorDomain,
                                       code: MSALError.userCanceled.rawValue,
                                       userInfo: msalError.userInfo) as Error
                    }
                }
            }
        }
        return error
    }
```

**Comment by oldalton** [comment]
Thanks a lot for the feedback. We discussed scenarios where access_denied would be returned, and in case of AAD those would be equivalent to "cancellation" - e.g. user declined consent, or user didn't proceed with the flow. Therefore, we decided to simplify it for developers. However, we should still be returning "access_denied" in the user info as oauth error code if developer needs further information for a particular oauth error code. Do you think that approach makes sense?

See full list of AAD errors: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#error-codes-for-authorization-endpoint-errors

**Comment by richardtop** [comment]
Hi Olga, thanks for following up on my concern. Simplifying the experience for developers should definitely be a focus (and was the whole point of raising this issue by me). After checking on the AAD errors, I have no objections to this solution, I think it works best for me.
I believe, we can close this issue now, since the code I've posted above has been removed from my app's codebase.

**Comment by oldalton** [comment]
Thanks for the confirmation! Closing the issue. Feel free to reopen if you have additional suggestions.
