### ISSUE TITLE
Request to get Interface from ADAL iOS SDK to get AAD deviceID if the device is already registered

### ISSUE THREAD

**Issue by valangot** [AzureAD/microsoft-authentication-library-for-objc#883]
**Repro Steps:**
1. Make sure Authenticator app is not installed
2. Call acquireToken(withResource) ADAL API with claims: "access token deviceID essential=true"
3. Enter valid credentials on ADAL signing WebView page 
4. Get Authenticate app screen will appear from ADAL
5. Once we click on "Get App" button then App Store will get launch

As per Apple AppStore policy, They don't allow applications to get published if any app asking/forcing to install other app.

AAD deviceID is essential in iOS MTD(Microsoft Threat Defence) application as MTD app required to send MDATP Portal. 

We don't get AAD deviceId from ADAL ADResult by default, to get it we have to claim from ADAL acquireToken() APIs.
That claim query result into device registration.

**Comment by jasoncoolmax** [comment]
Tag the issue with proper tag.

**Comment by oldalton** [comment]
Closing this issue as this is available in the latest MSAL release. Feel free to reopen if needed.

**Comment by tanahu** [comment]
My issue is when android device is registered in authentication app it shows registered successfully in azure portal but on the device no device I’d and sign in account. When try to open outlook mobile it passes through the credential and asks to register the device, when click on register, it throws an error 501291 which when check by that error code it says need to register the device prior to accessing the app. Any suggestions to check?
