### ISSUE TITLE
Missing `xcconfig` files

### ISSUE THREAD

**Issue by idelfonsog2** [AzureAD/microsoft-authentication-library-for-objc#886]
Hi there,

I was trying to run the project found at `Samples/ios/SampleAppiOS-Swift` but got the following  errors:

`
/Users/igutierrez/Developer/microsoft-authentication-library-for-objc/MSAL/xcconfig/msal__common__ios.xcconfig:1: could not find included file '../IdentityCore/IdentityCore/xcconfig/identitycore__common__ios.xcconfig' in search paths

**Comment by oldalton** [comment]
Hi, please run `git submodule update --init` command after you clone the repository. Thanks.

**Comment by idelfonsog2** [comment]
Thank you @oldalton !
