### ISSUE TITLE
Provisioning Profile and Certificates issues in `unit-test-host target`

### ISSUE THREAD

**Issue by idelfonsog2** [AzureAD/microsoft-authentication-library-for-objc#889]
hi @oldalton I'm trying to run tests fo the MSAL.xcworkspace I'm having issues running the following:

- MSAL Test App (iOS)
- unit-test-host
- MSAL Test Automation (iOS)
- MSIDTestHostApp
- IdentityCoreTests
- IdentityCore

All this is related to provisioning profiles and certificates. I tried changing the bundleID and the Team to my account but was wondering if this was the appropriate way of doing it?

Thank you in advance!

**Comment by oldalton** [comment]
Thanks for the question. Yes, it is fine to update the TeamID in signing settings, but you shouldn't need to update the BundleIdentifier as long as you have wildcard development provisioning profile (with keychain sharing enabled).
