### ISSUE TITLE
Error in carthage

### ISSUE THREAD

**Issue by ashu2451990** [AzureAD/microsoft-authentication-library-for-objc#890]
I am using xcode 10.0 

Got following error while using carthage to install MSAL framework :
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/XXX/XXX/XXXX-develop/Carthage/Checkouts/microsoft-authentication-library-for-objc/MSAL.xcworkspace -scheme MSAL\ (iOS\ Framework) -configuration Release -derivedDataPath /Users/XXXX/org.carthage.CarthageKit/DerivedData/10.0_10A255/microsoft-authentication-library-for-objc/081e94e7e7909629328a9c7aa64a870bb5248bfb -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/z8/f1gp9ncx1211lr68kz3206h40000gn/T/microsoft-authentication-library-for-objc SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/XXX/Documents/XXXXX/Carthage/Checkouts/microsoft-authentication-library-for-objc)

**Comment by oldalton** [comment]
Thanks for the question. Can you please try with Xcode 11? I don't think we support Xcode 10 anymore with latest released versions.

**Comment by ashu2451990** [comment]
@oldalton  thanks for your quick response but our project made with xcode 10 and we asked from our team not to upgrade our project for now. Any other help will be helpful to fix it. Please suggest.

**Comment by antrix1989** [comment]
Because Apple announced deprecation in [April](https://developer.apple.com/news/?id=03262020b), we moved to Xcode 11 and only support Xcode 11 going forward.

**Comment by rohitnarula7176** [comment]
@ashu2451990 Closing this issue for now.
