### ISSUE TITLE
ADFS support through Federation

### ISSUE THREAD

**Issue by idelfonsog2** [AzureAD/microsoft-authentication-library-for-objc#891]
I'm trying to find a workaround to integrate MSAL and AD FS. From the docs it mentions that AD FS is supported through Federation, will I be able to use MSAL-for-objc in conjunction after that configuration happens?

**Comment by oldalton** [comment]
Thanks for the question. Yes, that is fully supported today. In that flow, MSAL calls AAD that calls ADFS to complete authentication, and AAD issues the token to the MSAL library. Let me know if you see any concerns with that flow.

**Comment by alberto093** [comment]
@oldalton I don't know I can I do that. Do I need an app registration on AD?
