### ISSUE TITLE
SSO policy displaying differently between iOS 13 and iOS 10

### ISSUE THREAD

**Issue by Halfpint-Code** [AzureAD/microsoft-authentication-library-for-objc#896]
We have an SSO policy we have named AlmostDone. It displays a form collecting user info for new users. We are seeing a difference in the screen displayed between iOS13 and older versions. Using the exact same code we are getting our old, default login screen instead of the expected user info form in lower versions. All other screens appear correctly in all iOS versions.

**Comment by jasoncoolmax** [comment]
Hi @Halfpint-Code , could you please share a screenshot such that we could understand the issue better? thanks!

**Comment by Halfpint-Code** [comment]
![Lead-in_TryItFreeScreen](https://user-images.githubusercontent.com/59026045/78596741-ea5d9480-7811-11ea-8696-b2333a86f8eb.png)
![iOS10_AlmostDone](https://user-images.githubusercontent.com/59026045/78596763-f21d3900-7811-11ea-82e8-e23127fb6697.png)
![iOS13_AlmostDone](https://user-images.githubusercontent.com/59026045/78596773-f5182980-7811-11ea-9f8f-35527490d019.png)

The first screen shot is seen in both iOS10 and 13 and is expected.

The second is the expected user info collection screen we should see.

The third is the iOS 13 screen that is displaying an old default version of our login screen. It should be showing the second shot from what we are seeing on iOS10.

We are calling https://login.microsoftonline.com/tfp/<tenantName>/AlmostDone in both instances

**Comment by Halfpint-Code** [comment]
@jasoncoolmax Hey, just following up. Do you need more information?

**Comment by antrix1989** [comment]
@Halfpint-Code, thanks for the screenshots. Are you using `MSALWebviewTypeDefault`? We are using different default browsers on iOS 10 and 13 and the difference in UI might be related to different User-Agent strings. Could you try using `MSALWebviewTypeSafariViewController` on both iOS 10 and 13 and see if there is a difference in the UI?

**Comment by Halfpint-Code** [comment]
@antrix1989  I just tried that now. I noticed a small UI difference in display. It's not a popup anymore. But it is still displaying the unintended login like the third screenshot. Also, it is now calling the policy twice with that change which is causing an error popup and then the screen loads. That could just be the way we have the call setup but this still didn't resolve the original issue.

**Comment by Halfpint-Code** [comment]
@antrix1989 Update, I just tried MSALWebviewTypeWKWebView and that is actually displaying the correct screen on iOS13 now. I'm going to continue the dev on this and hopefully that is the fix I need!

**Comment by Halfpint-Code** [comment]
I am going to close this as I am no longer blocked by this. I am having other issues but I believe them to be unrelated. Thanks for the help.
