### ISSUE TITLE
Passwordless login

### ISSUE THREAD

**Issue by jagrutiJ** [AzureAD/microsoft-authentication-library-for-objc#898]
@vladzaharia 
I have funtionality of passwordless login in my app
it is working fine first time.
second time username is not persisting in browser. I have to enter user name every-time
i am using promptType = .login
please suggest the way by which my only username will persist not password

**Comment by oldalton** [comment]
You can pass login_hint parameter on second login: https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALInteractiveTokenParameters.html#/c:objc(cs)MSALInteractiveTokenParameters(py)loginHint

**Comment by rohitnarula7176** [comment]
@jagrutiJ Closing this issue for now. Please reopen if you still face any issues.

**Comment by jagrutiJ** [comment]
I am using password less authentication functionality.
at first place it is working properly.
in second time either I have to enter username every-time in Prompttype.Login or in Prompttype.selectedAccount it doest throw any notification on my MFA application.
can you please suggest best approach to achieve this
