### ISSUE TITLE
iOS 13 present UIModalPresentationStyle

### ISSUE THREAD

**Issue by allan304** [AzureAD/microsoft-authentication-library-for-objc#901]
i set like that

MSALWebviewParameters *webParameters = [[MSALWebviewParameters alloc] initWithParentViewController:controller];
webParameters.presentationStyle = UIModalPresentationFullScreen;
MSALInteractiveTokenParameters *parameters = [[MSALInteractiveTokenParameters alloc] initWithScopes:@[@"User.Read", @"Files.ReadWrite"] webviewParameters:webParameters];

but when i click continue button, there is no full screen. Please help.

**Comment by oldalton** [comment]
I think presentationStyle would only apply to WKWebView. If you're using default MSAL webview (ASWebAuthenticationSession), then presentationStyle is decided by iOS and we have no way to change it.

**Comment by allan304** [comment]
oo, Thanks a lot!
