### ISSUE TITLE
Unable to login user interactively. if the iOS device has Authenticator App installed.

### ISSUE THREAD

**Issue by cuddle-sujeet** [AzureAD/microsoft-authentication-library-for-objc#903]
I have configured my app to allow the user to login with Microsoft. It works well but there is one issue.
If the device has the Microsoft Authenticator app, then that user is not able to login with Microsoft from my app.

iOS 13 and above.
Used Swift language.

Debug result gave this error:
Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=Could not write broker key -34018, MSALInternalErrorCodeKey=-42708}

Tried to look at the documentation to understand the "MSALInternalErrorCodeKey=-42708"
but could get much help.

Can you guys help me out?

**Comment by oldalton** [comment]
Can you make sure that you completed step nr 3 (setting up keychain access groups) for your project? See additional instructions here: https://github.com/AzureAD/microsoft-authentication-library-for-objc#adding-msal-to-your-project

Let us know if that doesn't solve the issue.

**Comment by cuddle-sujeet** [comment]
Thanks for your quick response. I was putting the wrong keychain access group. The issue is resolved now.
