### ISSUE TITLE
Web auth fails while brokered auth works fine

### ISSUE THREAD

**Issue by dbanik** [AzureAD/microsoft-authentication-library-for-objc#905]
We recently updated our app from ADAL to MSAL. With ADAL, we had the web auth and brokered auth working as expected. After updating to MSAL and removing the ADAL linking, the web auth fails with the following error:
`AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application`

We have tried by setting `redirect Uri` in `IntuneMAMSettings` but it did not help. We are logging in by calling `IntuneMAMEnrollmentManager.instance().loginAndEnrollAccount(nil)`. This is the same code that works fine with ADAL linked to the target.

We have the redirect URI set in the AAD. We have tried in both simulator and devices and we are seeing the same behavior. 

We have followed all the steps detailed in git info as well as referred to the following doc:
https://docs.microsoft.com/en-us/azure/active-directory/develop/migrate-objc-adal-msal#adal-and-msal-app-capability-differences

Is this a known issue? If so, do we know the solution?

**Comment by oldalton** [comment]
Thanks for the question.
Are you using a custom Redirect URI for your application? (are you passing Redirect URI in MSALPublicClientApplicationConfig: https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALPublicClientApplicationConfig.html#/c:objc(cs)MSALPublicClientApplicationConfig(py)redirectUri)

Could you provide a sample code on how you invoke MSAL as well as Redirect URI you're passing? 
Additionally, could you also provide a correlationID and/or MSAL log for the error you're getting. See more about MSAL logging here: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging?tabs=objc

**Comment by dbanik** [comment]
We are not using any custom redirect URI. Our app calls the following code on launch in order to receive app protection policy from the Intune MAM service:
`IntuneMAMEnrollmentManager.instance().loginAndEnrollAccount(nil)`

This works fine when we are using another app as a broker. If we delete the broker app and try to run the app, it shows Microsoft Sign In page but then it fails with the error mentioned above. Attaching screenshot below.

P.S. Both brokered auth and Microsoft sign-in page based auth works fine when we have ADAL linked to the target.

<img width="533" alt="Screen Shot 2020-04-13 at 2 56 45 PM" src="https://user-images.githubusercontent.com/20192384/79620637-5919d800-80c5-11ea-9dc8-5efa41e9927a.png">

**Comment by oldalton** [comment]
Hi. It appears that your app doesn't have MSAL reply URL registered. Please follow steps in the readme and register a reply url in the format of `msauth.[BUNDLE_ID]://auth` as described here: https://github.com/AzureAD/microsoft-authentication-library-for-objc#adding-msal-to-your-project

**Comment by ShruthiAchutha** [comment]
Once you have the MSAL reply URL registered as per above, please follow the steps in https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#configure-adalmsal-settings-for-the-intune-app-sdk to specify ADALClientId and ADALRedirectUri in IntuneMAMSettings.

**Comment by dbanik** [comment]
Yup adding `ADALClientId` and `ADALRedirectUri` fixed it for me. It's a bit odd that I had to add these keys after moving to MSAL while I never needed these keys when I was using ADAL :-)
