### ISSUE TITLE
WebView cache doesn't appear to retain account

### ISSUE THREAD

**Issue by Halfpint-Code** [AzureAD/microsoft-authentication-library-for-objc#907]
I recently had to resolve an issue by defaulting webViewType to MSALWebviewTypeWKWebView. I've found some comments about WKWebView not caching the token. 

When we would force close the app and restart it, previously the ADALiOS framework we had would skip the login screen and jump into our app. The MSAL framework we upgraded to, appears to require new login every time. We are using MSALPromptTypePromptIfNecessary, but I have tried all the others and the reaction is always the same. It seems like it loses the token or account.

**Comment by oldalton** [comment]
I think what you're seeing is the difference between UIWebView (used by ADAL 2.x) and WKWebView (used by ADAL 4.x as well as MSAL). When you call acquireToken API, the cookies that get set inside the webview are session only cookies. WKWebView will generally only store those cookies in memory, and after you restart the app or create a new instance of WKWebView, cookie jar will be reset. This should explain the behavior you're seeing.

Additionally, ADAL acquireToken API would internally first do "acquireTokenSilent" and only show webview if silent fails. In MSAL, we made those two operations very explicit, and developer needs to adopt the pattern of calling "acquireTokenSilent" first, and calling "acquireToken" only when silent acquisition failed. 

Regarding webview cookies, we don't recommend developers to rely on webview cookies to achieve SSO. Instead, we recommend app developers to utilize MSAL token cache and call acquireTokenSilent API as the very first thing. acquireTokenSilent API will look up token silently from the keychain cache. If interaction is needed, it will return "MSALErrorInteractionRequired" error and only then you would need to show webview. That way, user would need to sign in very infrequently only when refresh token is invalid. Alternatively, you can use default MSAL webview (ASWebAuthenticationSession), which also persists cookies across apps and across sessions. 

I'd recommend to take a look at few articles we have:
- Tutorial which shows some of the practices I described: https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-ios
- Differences between ADAL and MSAL that I described: https://docs.microsoft.com/en-us/azure/active-directory/develop/migrate-objc-adal-msal#token-acquisition-changes
- MSAL error handling: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-handling-exceptions?tabs=iosmacos

**Comment by Halfpint-Code** [comment]
Thank you very much for the details. I have not been using acquireTokenSilent first. I will take a look at this. I will close this as I believe this answers the question I had.
