### ISSUE TITLE
Odd behaviour in conjunction with Microsoft Authenticator

### ISSUE THREAD

**Issue by DarkAnGth** [AzureAD/microsoft-authentication-library-for-objc#909]
When authentication is going through Microsoft Authenticator, MSALPublicClientApplication class doesn't always get account after successful acquireToken operation (allAccounts() gives empty list).
Specifically in my application I do following steps:
1. authenticate to Microsoft account - calling acquireToken, app is redirected to Microsoft Authenticator, then back to app - everything is fine, I get account, and can see it in allAccounts() results
2. do the sign out for this account
3. repeat step 1 with same account, but now, after successful result of acquireToken, where I do get the account in callback (with same identifier as before), but this account seems not to be stored to MSALPublicClientApplication, and allAccounts() function gives empty list.  Each time I try to authenticate with this account I get the same situation, BUT
4. once I restart application, or create new instance of MSALPublicClientApplication, I do see account in allAccounts() without additional attempts to authenticate.

I've checked how it works in provided example here "https://github.com/Azure-Samples/ms-identity-mobile-apple-swift-objc.git" without any changes to provided code:
1. **Without** Microsoft Authenticator installed - I press "Call Microsoft Graph API", authenticate to account, "Sign Out" button becomes active, all works as expected. I can do Sign out, then authenticate again, and it works always the same.
2. With Microsoft Authenticator installed - after authentication the "Sign Out" button remains disabled. But "Sign Out" button becomes active after restarting this application. Seems to be similar behaviour like I see in my application.

**Comment by oldalton** [comment]
Thanks for filing the issue. Do you mind sharing Microsoft Authenticator logs with the repro such as we could investigate? 

In Microsoft Authenticator app,

1) Click the hamburger menu

![](https://www.dropbox.com/s/k2h08em940uua87/IMG_0009.PNG?raw=1)

2) Click Help

![](https://www.dropbox.com/s/672l872qx41v240/IMG_1593.jpg?raw=1)

3) Click Send Logs

![](https://www.dropbox.com/s/3wutzq0ia8uwga3/IMG_1594.jpg?raw=1)

4) Type in what is wrong and click Next

![](https://www.dropbox.com/s/ps792i5j5uoqyt5/IMG_1595.jpg?raw=1)

5) Provide us the Incident ID

![](https://www.dropbox.com/s/b0n8t6jiud1yr8h/IMG_1596.jpg?raw=1)

**Comment by DarkAnGth** [comment]
Got it: UP2CGSNW
![IMG_1781](https://user-images.githubusercontent.com/3061333/79639591-76b67280-8195-11ea-9d6a-bfcc10e84d41.PNG)

**Comment by antrix1989** [comment]
@DarkAnGth , thanks for the logs. I don't see any errors on the Authenticator side. Could you please collect MSAL logs and send them to my email? My email: sedemche@microsoft.com
See [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging?tabs=swift#logging-in-msal-for-ios-and-macos) how to configure MSAL logs.

**Comment by DarkAnGth** [comment]
@antrix1989, sent logs yesterday, forgot to reply here

**Comment by antrix1989** [comment]
Thanks @DarkAnGth. I was able to reproduce it.

**Comment by oldalton** [comment]
Linking a fix: https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/736#pullrequestreview-408545376

**Comment by oldalton** [comment]
@DarkAnGth, this should be fixed in MSAL 1.1.3. Can you give it another try?
Closing the issue for now but please reopen if it still remains.

**Comment by DarkAnGth** [comment]
@oldalton  We cannot reproduce this issue with 1.1.3 update. Thank you!
