### ISSUE TITLE
macCatalyst build error

### ISSUE THREAD

**Issue by tfsjohan** [AzureAD/microsoft-authentication-library-for-objc#910]
Any fix for the build errors for macCatalyst, like

`No visible @interface for 'UIViewController' declares the selector 'initWithURL:parentController:presentationType:context:'`

and 

`Unknown receiver 'MSIDSafariViewController'; did you mean 'MSIDViewController'?`

in MSIDSystemWebViewControllerFactory.m?

**Comment by oldalton** [comment]
We don't support Mac catalyst right now, but we have full macOS support. Are you looking to have MSAL with Mac catalyst support, or you're just trying to avoid build failures? Thanks.

**Comment by tfsjohan** [comment]
Looking for macCatalyst support. Noticed a lot of conditional #if’s that mentions macCatalyst, so I got som hope it was supposed to work. 

Would be a great addition!

**Comment by jasoncoolmax** [comment]
Thank you for bringing this up. Currently there is [another issue](https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/649) tracking the macOS Catalyst support. So I close this one as a duplicate.
