### ISSUE TITLE
Passwordless Authentication notification

### ISSUE THREAD

**Issue by jagrutiJ** [AzureAD/microsoft-authentication-library-for-objc#911]
@rohitnarula7176 I am using password less authentication functionality.
at first place it is working properly as expected.
However,
1. If I make  Prompttype.Login in MSAL it is asking me to enter username every-time
2.If I make Prompttype.selectedAccount in this case it does not give any notification on Authenticator application for approval

I want user name to be pre populated and when I process with selected username it should throw approval notification to my Authenticator app for approval

Pease guide me to achieve above functionality

**Comment by jasoncoolmax** [comment]
@jagrutiJ Thank you for reporting this.

It will help us to investigate if you could provide us the MSAL logs as well as a screenshot of what you saw. For collecting logs, see here for [details](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging?tabs=objc#logging-in-msal-for-ios-and-macos).

Besides, 
- Did you pass the login hint when you call MSAL?
- Did you finally land in the passwordless authentication page for both number 1 and number 2 cases? Or you just land in the page to prompt you for password?

Thank you very much!

**Comment by oldalton** [comment]
@jagrutiJ, are you still experiencing this issue? Were you able to take a look at questions from @jasoncoolmax?

**Comment by jagrutiJ** [comment]
@oldalton  Yes still facing same issue.
@jasoncoolmax Did you pass the login hint when you call MSAL? - Yes, However if I pass login hint it always ask me my username to enter.

 Did you finally land in the passwordless authentication page for both number 1 and number 2 cases? Or you just land in the page to prompt you for password? - Passowrdleass is working properly as expected (on very first login)

from second time onwords it show my account is signned and when I ckicked on account I am able to proceed without any aproval notification on authentication app.

**My requirement is - on second time on-words user do not need to type username and on selecting account the notification should come to users authentication app for approval**

**Comment by jasoncoolmax** [comment]
Hi @jagrutiJ, may I know why do you have such requirement? When you pass prompt=select_account, I think user is automatically signed in because of SSO, which is by design.

**Comment by jagrutiJ** [comment]
@jasoncoolmax correct,
This application is designed for bank agents.
Every agent have one iPad and one personal mobile.
so authenticator app is on agents mobile from which he can authenticate.
if any unauthorise user tries to login to my iPad I should get approval notification on my authenticator app which is there in phone so I will get to know the someone trying to login from my iPad.

**Comment by oldalton** [comment]
Thanks for the update. I've just learned that there's a known issue where passwordless is bypassed when you provide login_hint. It sounds like that was what you were seeing. This is getting fixed by server side, so give it a try in a couple of weeks. 

To summarize, recommendation is:
1. Pass login_hint to MSAL when calling acquireToken (after server side issue is fixed, it should also trigger passwordless)
2. We don't recommend forcing user to do passwordless every time. If you still need to do it, you can pass login_hint AND prompt=login.
