### ISSUE TITLE
Getting same popup before displaying the Microsoft Login page

### ISSUE THREAD

**Issue by kbabulrao** [AzureAD/microsoft-authentication-library-for-objc#912]
The PopUp appears when the user clicks on "Sign In" button. Here, we are calling the callGraphAPI()  in the button action. 

How do we restrict the below Popup to show once per user?
![Simulator Screen Shot - iPhone 8 Plus - 2020-04-08 at 14 51 33](https://user-images.githubusercontent.com/5792888/79850483-a5c12400-83e1-11ea-8574-69c32c758fbd.png)

How do we present the Login page if we don't see the popup? (If we user didn't click on the "Continue" button).

**Comment by rohitnarula7176** [comment]
@kbabulrao This pop up is presented by the OS and is out of the library control. In iOS 13, Apple introduced a flag that allows you the option of using a private mode or share cookies among various sessions. The default value for this flag in our library is false which enables sso and cookie sharing. You can set it to true to make the dialog go away but it is not recommended. Please see the documentation below for the exact property.:
[https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALWebviewParameters.html#/c:objc(cs)MSALWebviewParameters(py)prefersEphemeralWebBrowserSession](url)

**Comment by oldalton** [comment]
Closing this issue. Feel free to reopen if you have additional questions.
