### ISSUE TITLE
Web view on iOS 13 is not closed automatically after getting token

### ISSUE THREAD

**Issue by odarynakorolevych** [AzureAD/microsoft-authentication-library-for-objc#916]
Hello, I'm using for SSO ASWebAuthenticationSession on iOS 13. If the user clicks RELOAD (button in right top corner of web view), after successful login the web view is not closed automatically, and the user sees the logged in page of his SSO provider. 

Is that expected behavior? Can we disable the RELOAD button if it's expected?

**Comment by mipetriu** [comment]
@odarynakorolevych The UI behavior of ASWebAuthenticationSession is out of the library's control. You may want to contact Apple regarding this issue.

**Comment by oldalton** [comment]
Closing this issue. Feel free to reopen if you have additional questions.
