### ISSUE TITLE
Configuration problems

### ISSUE THREAD

**Issue by dusanjovanov** [AzureAD/microsoft-authentication-library-for-objc#921]
I'm trying to configure the AppDelegate callback as per your docs.
I'm not sure where to put this code: 
```
- (BOOL)application:(UIApplication *)app
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
    return [MSALPublicClientApplication handleMSALResponse:url 
                                         sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]];
}
```
This is my AppDelegate.m file:
![image](https://user-images.githubusercontent.com/20474783/80944754-929f5280-8dea-11ea-950c-b2c4e3e430d6.png)

If I replace the `return YES` line with the code you provided I get variable not found errors.

**Comment by oldalton** [comment]
Hi. You would need to add a new AppDelegate method in addition to 2 methods that you already implement as shown in the sample you referenced.

**Comment by rohitnarula7176** [comment]
@dusanjovanov Were you able to resolve the issue you were facing with configuration?

**Comment by dusanjovanov** [comment]
Yes, sorry for not responding, closing it now.
