### ISSUE TITLE
Trying to Aquire access tokens interactively for multiple scopes

### ISSUE THREAD

**Issue by vinod-singh1** [AzureAD/microsoft-authentication-library-for-objc#924]
Hi,
I am using MSAL Objective C lib in my project and trying to acquire access tokens interactively for multiple scopes: Policy token and RMS token. I am making two calls of "[application acquireTokenWithParameters:interactiveParameters
completionBlock:CompletionBlock];" from my function but it is failing with error as below:

MSALTestApp1[20226:1859401] Failed with error Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=Only one interactive session is allowed at a time., MSALInternalErrorCodeKey=-42402, MSALCorrelationIDKey=E5D8EB72-A38A-4206-B78F-57D0C4191A60}

Can someone please help me out how to fix that or the better approach to achieve that.

Thanks,
Vinod Singh

**Comment by jasoncoolmax** [comment]
Hi @vinod-singh1, I think you can call acquireTokenWithParameters:interactiveParameters for the first resource, like for Policy token. 
After the call finishes, you can call acquireTokenSilentWithParameters for the second resource, like RMS token mentioned in your post. 
If the silent call fails with interaction required, you can do acquireTokenWithParameters:interactiveParameters for the second resource.

Hopefully the above helps.

**Comment by oldalton** [comment]
Closing the issue. Please reopen if you have additional question.
