### ISSUE TITLE
User cannot login if browser cookies are blocked.

### ISSUE THREAD

**Issue by jayeshcode** [AzureAD/microsoft-authentication-library-for-objc#928]
User is getting error "Your browser is currently set to block cookies you need to allow cookies to use this service"  when the cookies are blocked for his browser. 

Even if he disable blocking cookies  he still gets error and is never able to log in.

![Image from iOS](https://user-images.githubusercontent.com/17971004/81998558-d0894b80-9620-11ea-9aa0-7321643ba963.png)

**Comment by oldalton** [comment]
Can you share MSAL correlationID? It is available in MSAL logs.
Additionally, do you have any custom configuration on your tenant?
Thanks!

**Comment by jayeshcode** [comment]
I Nslog "correlationID" in MSIDLogger  method->logWithLevel it is always coming's null. I don't think we have custom configuration in our App registration. How can I verify it.

**Comment by oldalton** [comment]
@jayeshcode, see instructions to configure MSAL logging here: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging?tabs=objc

**Comment by jayeshcode** [comment]
Thanks [2020-05-15 19:30:47 - C69E3B10-7EEC-42DE-AF98-C67E7BE0C463]  here is the correlationID = C69E3B10-7EEC-42DE-AF98-C67E7BE0C463 

The corelaltion ID was to captured when we see the above error.

**Comment by jayeshcode** [comment]
@oldalton 

 here are logs : -
correlationID :- 21C3D64E-2F99-45E0-915D-2A24B6B6EDF5

MSAL log: TID=423889 MSAL 1.1.1 iOS 13.4.1 [2020-05-19 16:05:29] Requiring default broker type due to app being built with iOS 13 SDK
MSAL log: TID=423889 MSAL 1.1.1 iOS 13.4.1 [2020-05-19 16:05:29 - 21C3D64E-2F99-45E0-915D-2A24B6B6EDF5] [MSAL] -[MSALPublicClientApplication acquireTokenWithParameters:(
    "https://graph.microsoft.com/user.read"
)
                                     extraScopesToConsent:(null)
                                                  account:Masked(null)
                                                loginHint:Masked(null)
                                               promptType:MSALPromptTypeSelectAccount
                                     extraQueryParameters:(null)
                                                authority:(null)
                                              webviewType:MSALWebviewTypeDefault
                                            customWebview:No
                                            correlationId:(null)
                                             capabilities:(null)
                                            claimsRequest:(null)]
MSAL log: TID=423889 MSAL 1.1.1 iOS 13.4.1 [2020-05-19 16:05:29 - 21C3D64E-2F99-45E0-915D-2A24B6B6EDF5] [MSAL] Checking broker install state for version V2-broker-nonce
2020-05-19 12:05:29.077327-0400 Connect[1135:423889] -canOpenURL: failed for URL: "msauthv2://broker" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
MSAL log: TID=423889 MSAL 1.1.1 iOS 13.4.1 [2020-05-19 16:05:29] Scheme msauthv2 for broker not present
MSAL log: TID=423889 MSAL 1.1.1 iOS 13.4.1 [2020-05-19 16:05:29 - 21C3D64E-2F99-45E0-915D-2A24B6B6EDF5] [MSAL] Beginning interactive flow.
MSAL log: TID=423889 MSAL 1.1.1 iOS 13.4.1 [2020-05-19 16:05:29 - 21C3D64E-2F99-45E0-915D-2A24B6B6EDF5] [MSAL] Resolving authority: Masked(not-null), upn: Masked(null)
MSAL log: TID=424063 MSAL 1.1.1 iOS 13.4.1 [2020-05-19 16:05:29 - 21C3D64E-2F99-45E0-915D-2A24B6B6EDF5] [MSAL] No cached preferred_network for authority
MSAL log: TID=424063 MSAL 1.1.1 iOS 13.4.1 [2020-05-19 16:05:29 - 21C3D64E-2F99-45E0-915D-2A24B6B6EDF5] [MSAL] Waiting on Authority Validation Queue
MSAL log: TID=424053 MSAL 1.1.1 iOS 13.4.1 [2020-05-19 16:05:29 - 21C3D64E-2F99-45E0-915D-2A24B6B6EDF5] [MSAL] Caching AAD Environements
MSAL log: TID=424053 MSAL 1.1.1 iOS 13.4.1 [2020-05-19 16:05:29 - 21C3D64E-2F99-45E0-915D-2A24B6B6EDF5] [MSAL] networkHost: login.microsoftonline.com, cacheHost: login.windows.net, aliases: login.microsoftonline.com, login.windows.net, login.microsoft.com, sts.windows.net
MSAL log: TID=424053 MSAL 1.1.1 iOS 13.4.1 [2020-05-19 16:05:29 - 21C3D64E-2F99-45E0-915D-2A24B6B6EDF5] [MSAL] networkHost: login.partner.microsoftonline.cn, cacheHost: login.partner.microsoftonline.cn, aliases: login.partner.microsoftonline.cn, login.chinacloudapi.cn
MSAL log: TID=424053 MSAL 1.1.1 iOS 13.4.1 [2020-05-19 16:05:29 - 21C3D64E-2F99-45E0-915D-2A24B6B6EDF5] [MSAL] networkHost: login.microsoftonline.de, cacheHost: login.microsoftonline.de, aliases: login.microsoftonline.de
MSAL log: TID=424053 MSAL 1.1.1 iOS 13.4.1 [2020-05-19 16:05:29 - 21C3D64E-2F99-45E0-915D-2A24B6B6EDF5] [MSAL] networkHost: login.microsoftonline.us, cacheHost: login.microsoftonline.us, aliases: login.microsoftonline.us, login.usgovcloudapi.net
MSAL log: TID=424053 MSAL 1.1.1 iOS 13.4.1 [2020-05-19 16:05:29 - 21C3D64E-2F99-45E0-915D-2A24B6B6EDF5] [MSAL] networkHost: login-us.microsoftonline.com, cacheHost: login-us.microsoftonline.com, aliases: login-us.microsoftonline.com
MSAL log: TID=424053 MSAL 1.1.1 iOS 13.4.1 [2020-05-19 16:05:29 - 21C3D64E-2F99-45E0-915D-2A24B6B6EDF5] [MSAL] Resolved authority, validated: YES, error: 0
MSAL log: TID=424063 MSAL 1.1.1 iOS 13.4.1 [2020-05-19 16:05:29 - 21C3D64E-2F99-45E0-915D-2A24B6B6EDF5] [MSAL] Returned from Authority Validation Queue
MSAL log: TID=423889 MSAL 1.1.1 iOS 13.4.1 [2020-05-19 16:05:29] Start background app task with type 0
2020-05-19 12:06:04.651890-0400 Connect[1135:423889] [BackgroundTask] Background Task 11 ("Interactive login"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.

**Comment by jayeshcode** [comment]
@oldalton any updates ?

**Comment by oldalton** [comment]
@jayeshcode, we are not seeing specific issues in our telemetry. Would it be possible to collect a network trace for additional investigation and send it to sedemche@microsoft.com? Thanks.

**Comment by jasoncoolmax** [comment]
@jayeshcode Have you had a chance to collect the network trace? :)

**Comment by jayeshcode** [comment]
@jasoncoolmax  with network trace you mean CFNetwork diagnostics logging from my XCODE ?

**Comment by mipetriu** [comment]
@jayeshcode You can refer to these instructions to get the network trace: [https://github.com/AzureAD/azure-activedirectory-library-for-objc/blob/dev/README.md#network-traces](https://github.com/AzureAD/azure-activedirectory-library-for-objc/blob/dev/README.md#network-traces)

**Comment by antrix1989** [comment]
Hey @jayeshcode, did you have a chance to collect the network trace?

**Comment by guidedways** [comment]
A user we have is having the same issue. They've tried everything but nothing seems to help.
