### ISSUE TITLE
Rationalize 'nil' behavior of authority parameter

### ISSUE THREAD

**Issue by RPangrle** [AzureAD/microsoft-authentication-library-for-objc#93]
In the silent code path we store 'nil' in parameters, interactive and application we don't. We should probably make that behavior consistent internally across code paths.

**Comment by unpluggedk** [comment]
Now with ATS logic in place as is, this is by design. 
AT will use default if authority is passed in nil, and ATS will keep nil as there is a separate logic for this.

There is a potential of a flaw here in some undiscovered corner case, in which all platforms will need to fix if it happens.
