### ISSUE TITLE
Implicit declaration of function 'MSID_LOG_WITH_CTX' is invalid in C99

### ISSUE THREAD

**Issue by neildas21** [AzureAD/microsoft-authentication-library-for-objc#935]
Hi, When I build my project on XCode. I get the following error from the MSAL import. 

"Implicit declaration of function 'MSID_LOG_WITH_CTX' is invalid in C99"
<img width="1047" alt="Screenshot 2020-05-20 at 9 59 16 AM" src="https://user-images.githubusercontent.com/42718622/82410276-98e72d00-9a80-11ea-90fa-f55eddc0c8e6.png">

**Comment by oldalton** [comment]
Make sure you run `git submodule update` command after checking out MSAL repository.

**Comment by oldalton** [comment]
Closing this issue. Please reopen if still active. Thanks!

**Comment by wvezey** [comment]
Getting the same issue when using MSAL as a pod. Are you saying that we have to git this, and embed it as a framework?

**Comment by sahil-75** [comment]
Hi @oldalton , we're facing the same issue. We tried `git submodule update`, but it doesn't seem to do anything. Could you help us understand how to resolve this?

**Comment by wvezey** [comment]
We are in a similar boat. I removed the MDAL pod from the podfile, and am no longer getting this build error, but i have not attempted to publish to the Intune company portal. We shall see.

**Comment by oldalton** [comment]
We have instructions depending on your way of installing MSAL here: https://github.com/AzureAD/microsoft-authentication-library-for-objc/wiki/Installation

If you're still experiencing the issue after following the steps in the Wiki page, please post your Podfile here.

**Comment by pranayubs** [comment]
Hello, I'm facing same issue. Any idea, How to resolve this issue?

Here is the pod file
```
target 'MyApp' do
  pod 'MSAL'
end
```
pod installation
```
Analyzing dependencies
Downloading dependencies
Installing MSAL (1.1.13)
Generating Pods project
Integrating client project
```
Compilation error
`Implicit declaration of function 'MSID_LOG_WITH_CTX' is invalid in C99`

**Comment by wvezey** [comment]
@pranayubs We fixed the issue by formatting our podfile MSAL call like this:

`pod 'MSAL', :git => 'https://github.com/AzureAD/microsoft-authentication-library-for-objc.git', :submodules => true`

**Comment by stutivaidya** [comment]
Hello, running into the same problem. "Implicit declaration of function 'MSID_LOG_WITH_CTX' is invalid in C99"

Tried out above suggestions but still running into the same error.

**Comment by dmitry-mikheev** [comment]
Same problem for me. I add it like this (copied from documentation):

`pod 'MSAL', :git => 'https://github.com/AzureAD/microsoft-authentication-library-for-objc', :branch => 'master', :submodules => true`

Tried to run 'pod update' and also made a clean install. Nothing helps. Does anyone managed to install it?
