### ISSUE TITLE
setting MSALWebviewParameters.presentationStyle = .fullscreen has no effect

### ISSUE THREAD

**Issue by svendr** [AzureAD/microsoft-authentication-library-for-objc#938]
I've recently updated my local MSAL-dependency to 1.1.2 and adapted the suggested changes. I've also noticed, that the presented SFSafariViewCoontroller now doesn't fully cover the screen (default behaviour when compiling with iOS 13 SDK):

![NoFullscreenPresentation_Small](https://user-images.githubusercontent.com/29842223/82647343-5b1c0d00-9c16-11ea-8f0f-a60c28315810.png)

I've tried to fix this by setting `presentationStyle = .fullscreen` on `MSALWebviewParameters`, but it didn't have any effect. Here's the full code:

```
...
let webviewParameters = MSALWebviewParameters.init(authPresentationViewController: presentationViewController)
webviewParameters.presentationStyle = .fullScreen
let tokenParameters = MSALInteractiveTokenParameters.init(scopes: configuration.authorizationScopes, webviewParameters: webviewParameters)
		msalApplicationContext.acquireToken(with: tokenParameters, logger: logger) { ... }
```

Environment: Xcode 11.4.1, iOS SDK 13.4, Swift 5.3, MSAL 1.1.2

**Comment by oldalton** [comment]
Thanks for the question. Can you clarify what kind of webview type you're using? `presentationStyle` property might not work reliably for all webview types. 

See more details about different webview types that MSAL supports here: https://docs.microsoft.com/en-us/azure/active-directory/develop/customize-webviews

**Comment by svendr** [comment]
Hi @oldalton, thanks for your feedback. I haven't explicitly configured a webViewType, so the default value of `MSALWebviewTypeDefault` should be applied, which itself should use `ASWebAuthenticationSession` as per my understanding. 

If the presentationStyle property has no effect for this webViewStyle, it should either be fixed or at least clearly documented. The current doc just states: "Modal presentation style for displaying authentication web content."

**Comment by oldalton** [comment]
Yes, I think ASWebAuthenticationSession would ignore any presentationStyle that we set. Agree that documentation needs to be updated. Thanks!

**Comment by oldalton** [comment]
Updated API documentation. Please let us know if you have additional suggestions for the documentation. Thanks.

**Comment by jatinmishra** [comment]
Is there any way possible to display the default webview `MSALWebviewTypeDefault` in fullscreen as the WKWebview.
I need SSO so cant use WKWebview and I need the webview in fullscreen.

Thanks.

**Comment by tushar-iosd** [comment]
Hi @jatinmishra  were you able to achieve that ?

**Comment by svgupta97** [comment]
Hi! How were you able to create a custom login with MSAL? Thank you!
