### ISSUE TITLE
macOS: Intermittent redirect failure from Safari after successful auth

### ISSUE THREAD

**Issue by mattvlas** [AzureAD/microsoft-authentication-library-for-objc#949]
This seems to happen about 5-10% of the time with our users, but we are seeing a problem where the Catalina 10.5.x Safari web view is reporting that the redirect back to our application after a successful authentication "can't open the specified address".  

<img width="1015" alt="screenshot_2020-06-09_at_17_49_31-1" src="https://user-images.githubusercontent.com/57152570/84199402-f526e680-aa59-11ea-9aca-10f6dcda25b7.png">

The weird thing is that some users are reporting that the authentication is actually succeeding to our application, even though they are seeing this screen.  I can't say for sure whether this is actually true or not given the rapid nature of user testing...

A reboot fixes the problem universally if it doesn't start working after a later attempt.

Has this been seen before?  It is weird because it works flawlessly on many machines and appears to occur intermittently on random devices.

**Comment by oldalton** [comment]
Thanks for reporting this. We haven't seen this before, so would appreciate some additional logs to diagnose. In order to collect MSAL logs, follow these instructions: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging?tabs=objc#logging-in-msal-for-ios-and-macos

Additionally, if it's impacting your users, I'd recommend you to switch to WKWebView in the meantime as your webview type: https://docs.microsoft.com/en-us/azure/active-directory/develop/customize-webviews#change-the-default-browser-for-the-request

**Comment by mattvlas** [comment]
@oldalton Great, we'll increase the log level to verbose (there is nothing indicating there was any problem at normal logging levels) and report back.

**Comment by mattvlas** [comment]
The issue occurred on another machine and I have attached the MSAL logs in debug mode when this occurred.  Hopefully this helps!

[service.log](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/4790302/service.log)

**Comment by mattvlas** [comment]
After investigation, unfortunately the WKWebView option is not viable for our application due to lack of integrated SSO on macOS.

We are going to try to add a `URL Type` of `msauth.$(PRODUCT_BUNDLE_IDENTIFIER)` to our applications Info.plist instead of relying on the MSAL library to register this scheme at run time.  In my testing, there doesn't seem to be any negative impact of doing this, and I will report back if we see any unintended consequences or if this resolves the issue.

**Comment by NerevarineRule** [comment]
Hi @mattvlas,

We've tried to reproduce the issue on a Mac with ver 10.15.5 using the log you provided a basis.

Below is the list of test cases we've tried out. 
1) Looking at a successful acquire token operation within your log using its timestamp & correlation ID, it indicated that the backslash was missing between auth and ? (://auth? instad of ://auth/?), while the URL in the screenshot you provided had an extra backslash. However, this wasn't the issue, as we were able to acquire token successfully with URLs that had an extra backslash.
2) We added a very long request state string as part of the acquireToken operation in our MSAL MacOS Test app, but we were still able to acquire token successfully.

Could you please help to provide additional information?
1) Any commonalities across the devices that have shown above issue.
2) Network trace of above redirect url issue. 

Thanks,
Peter

**Comment by mattvlas** [comment]
Hi Peter,

Thanks for trying to reproduce this.  We have found it very inconsistent, and is one of those issues that seems to be fixed with a device reboot with all other things being equal (so unlikely an issue with the request)

All devices experiencing this problem are macOS devices running Catalina.  On like models and OS versions, this won't be a problem, whereas on about 10% of devices it will be.

I believe the problem has to do with how the MSAL library is registering the URL schema to the OS because the OS is unable to handle it when called within Safari.  It acts as if our app isn't even installed.  As I mentioned we are trying to test this assumption by statically defining the `URL Type` for our binary, instead of relying on MSAL to register it at runtime (similar to what is required to do on iOS). 

We are between deployments but will be doing another phase soon, at which point I will report back.

**Comment by NerevarineRule** [comment]
Hi Matt,

Thank you for your reply.

We are not actually registering any url schemes. We are simply calling those ASWebAuthenticationSession APIs (https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession/2990952-init). It appears to be an OS-related issue based on the information provided so far. 
We would suggest that you consider filing a RADAR with Apple.
