### ISSUE TITLE
Signing of MSAL.Framework for Objective-C

### ISSUE THREAD

**Issue by vinod-singh1** [AzureAD/microsoft-authentication-library-for-objc#952]
I am building Objective-C library for Authentication and fetching tokens so I have downloaded the MSAL.Framework using Cocoa Pod install command.

When packaging this Framework along with dylib into the package, I found that MSAL.Framework binaries are not signed. Verified this using "codesign -dvvv MSAL" the result says that "MSAL: code object is not signed at all".
Ideally this should be signed by Microsoft as Microsoft is the provider of this Framework.
Has anyone else face the similar issue? or there is any other repository to download the signed version of MSAL.Framework?

Please help, suggests the correct usage of MSAL.Framework.

Thanks,
Vinod Singh

**Comment by oldalton** [comment]
When you install MSAL with CocoaPods, you're building MSAL from code. You'll need to have your own signing for all embedded frameworks at that point. I believe Xcode allows you to configure signing settings for any framework dependencies that you have in your app.

**Comment by vinod-singh1** [comment]
> When you install MSAL with CocoaPods, you're building MSAL from code. You'll need to have your own signing for all embedded frameworks at that point. I believe Xcode allows you to configure signing settings for any framework dependencies that you have in your app.

We have used Cocoa Pod just to download the MSAL.Framework. We have not configured Pod setting within project consuming MSAL.Framework.
So I would like to know the correct way or repository to download MSAL.Framework as we don't want to build it.

**Comment by jasoncoolmax** [comment]
@vinod-singh1 We don't provide binaries for Objective-C MSAL. You may need to build it yourself to get MSAL.Framework. If you are using CocoaPods, it will automatically download MSAL source files and configure your project. So at the moment, I think you need to config the signing of the framework in your project.

**Comment by vinod-singh1** [comment]
> @vinod-singh1 We don't provide binaries for Objective-C MSAL. You may need to build it yourself to get MSAL.Framework. If you are using CocoaPods, it will automatically download MSAL source files and configure your project. So at the moment, I think you need to config the signing of the framework in your project.

Thanks Jason!!! will do the needful.
