### ISSUE TITLE
Can MSALWebviewParameters be used with SwiftUI to fetch a token interactively?

### ISSUE THREAD

**Issue by jyotimathur** [AzureAD/microsoft-authentication-library-for-objc#953]
I have an app that uses SwiftUI instead of UIKit. I want to use MSAL library to acquire a token interactively. I see that MSALWebviewParameters support display using UIViewController. Is there a way to use swift ui based views here?

**Comment by oldalton** [comment]
SwiftUI should be compatible with existing UIKit frameworks. Apple has some guidance here: https://developer.apple.com/tutorials/swiftui/interfacing-with-uikit. Let us know if that still doesn't address your issue. Thanks.
