### ISSUE TITLE
Error -42700 when returning from the Microsoft Authenticator

### ISSUE THREAD

**Issue by niklassaers** [AzureAD/microsoft-authentication-library-for-objc#955]
Hi,  
I've implemented MSAL in my iOS 13 Swift app, and logging in via the web view works fine. However, when I have the authenticator app installed, it asks to open that, I authenticate with that and am returned to my app, at that point I get the error -42700. Any suggestions as to what could be causing it?

I have added com.microsoft.adalcache to the Keychain Groups in Keychain Sharing.

Cheers

   Niklas

**Comment by oldalton** [comment]
Can you double check if you implemented MSAL callback in your AppDelegate: https://github.com/AzureAD/microsoft-authentication-library-for-objc#swift-1. You need to propagate broker response back to MSAL when your app is opened.

**Comment by niklassaers** [comment]
Thank you so much for your answer. I had missed the detail where the AppDelegate code isn't executed, but the SceneDelegate is for my iOS 13 app. Having put in place the required code into SceneDelegate, it now authenticates fine :-) Thanks a lot :-)
