### ISSUE TITLE
MSAL 1.1.3 iOS 13.5.5 Error: One or more request parameter is missing from clientId, redirectUri, or target

### ISSUE THREAD

**Issue by smudireddy** [AzureAD/microsoft-authentication-library-for-objc#957]
Request Type: WorkplaceJoin registration
Platform : iOS
App: Request to "register" the3 device using Authenticator from MSAL iOS Sample App
MSAL Version : MSAL 1.1.3
ClientID = "7e3e8b0c-eeff-4506-b61a-ab33df7815d5"

For more Details: https://ibm.box.com/s/p76ytt9rwp6j8ihtwnc24pjo3hp25kfu

***********************************************************************************************
MSAL 1.1.3 iOS 13.5.5 [2020-06-14 02:14:57] Received broker request with URL: msauth://wpj/?username=(not-null)&client_info=(not-null)
MSAL 1.1.3 iOS 13.5.5 [2020-06-14 02:14:57] Creating V1 broker request
MSAL 1.1.3 iOS 13.5.5 [2020-06-14 02:14:57] Creating Error with description: One or more request parameter is missing from clientId, redirectUri, or target
MSAL 1.1.3 iOS 13.5.5 [2020-06-14 02:14:57] Failed to create broker request from request URL with error Error Domain=MSIDErrorDomain Code=-51112 "(null)" UserInfo={MSIDErrorDescriptionKey=One or more request parameter is missing from clientId, redirectUri, or target}
MSAL 1.1.3 iOS 13.5.5 [2020-06-14 02:14:57] Received broker request with URL: msauth://wpj/?username=(not-null)&client_info=(not-null)

MSAL 1.1.3 iOS 13.5.5 [2020-06-14 02:14:57] ADB 3.1.6 -[ADBrokerURLSchemeRequest shouldShowAccountPicker]

MSAL 1.1.3 iOS 13.5.5 [2020-06-14 02:14:57] Broker invoked from com.apple.SafariViewService

MSAL 1.1.3 iOS 13.5.5 [2020-06-14 02:14:57] Creating V1 broker request

MSAL 1.1.3 iOS 13.5.5 [2020-06-14 02:14:57] Creating Error with description: One or more request parameter is missing from clientId, redirectUri, or target

MSAL 1.1.3 iOS 13.5.5 [2020-06-14 02:14:57] Error Domain=MSIDErrorDomain Code=-51112 "(null)" UserInfo={MSIDErrorDescriptionKey=One or more request parameter is missing from clientId, redirectUri, or target}

**Comment by smudireddy** [comment]
2020-06-14 02:14:58.019    VERB        WorkplaceJoin    0    TID=1         0 () INFO: -[WorkPlaceJoinUtil getRegistrationInformation:error:] [Line 269][2020-06-14 02:14:58 +0000]getRegistrationInformation: Failed to retrieve certificate and identify

2020-06-14 02:14:58.019    VERB        WorkplaceJoin    0    TID=1         0 () INFO: [2020-06-14 02:14:58 +0000]Error Domain=com.microsoft.workplacejoin.errordomain Code=-400 "getCertificateForAccessGroup: Unable to read from shared access group: SGGM6D27TK.com.microsoft.workplacejoin for identifier: WPJCertificate with error code: -25300" UserInfo={NSLocalizedDescription=getCertificateForAccessGroup: Unable to read from shared access group: SGGM6D27TK.com.microsoft.workplacejoin for identifier: WPJCertificate with error code: -25300, NSUnderlyingError=0x2809d1410 {Error Domain=com.microsoft.workplacejoin.keychainerror Code=-25300 "(null)"}}

**Comment by smudireddy** [comment]
For more Details:  https://ibm.box.com/s/p76ytt9rwp6j8ihtwnc24pjo3hp25kfu 
password: msal

**Comment by jasoncoolmax** [comment]
Hi @smudireddy, thank you very much for reporting this. According to the logs, I guess certificated based authentication (CBA) is involved for your sign in. Currently, due to system limitation, we don't support CBA together device-based conditional access. 

We have heard from customers that, registering your device in Authenticator before hand could help solve this issue. Please do let me know if the workaround works for you.

**Comment by smudireddy** [comment]
> Hi @smudireddy, thank you very much for reporting this. According to the logs, I guess certificated based authentication (CBA) is involved for your sign in. Currently, due to system limitation, we don't support CBA together device-based conditional access.
> 
> We have heard from customers that, registering your device in Authenticator before hand could help solve this issue. Please do let me know if the workaround works for you.

@jasoncoolmax ,

Thanks for the confirmation.

- This is a case of ADFS with CBA where User Identity cert pushed to iOS system key-chain using MDM client.

- User able to register manually from the "Menu -> Settings -> Device registration" of Microsoft Authenticator but no Device object created in Azure AD portal under "Devices" so which will not help the CA policies to consider that and not providing the "deviceid" claim back to the calling app which initiated the "MSAL" interactive request.

**Use Case:** - 

1. App will initiate an interactive token request for scope "user.read" with "deviceid" claim to push the Authenticator app to register the device post authentication and provides the deviceid claim in Auth result back to the calling application. 

2. App will use the deviceid to update the device object manage and compliance attributes for CA policies to be satisfied

This flow working for AAD user with password but when it comes to ADFS + CBA  case Authenticator App authenticating the user and provided an option "Register" to user on webview control  (despite device already registered manually) but on selection of the "Register" option it is going into an infinite loop of keychain checks. Logs of Authenticator app showing Key-chain failures and missing "**One or more request parameter is missing from clientid, redirectUri ..."**

If failed to do "AAD device registration" option programmatically with "interactive request", at least Authenticator App should provide the deviceid claim when user already completed the Device registration manually from Authenticator App "settings -> Device registration"

Let me know if you need further details of the issue. Thanks in advance for  your help.

**Comment by smudireddy** [comment]
@jasoncoolmax ,

Is Azure AD users with CBA supported  or it is only ADFS with CBA not supported ?

**Comment by zounasL** [comment]
I am facing similar kind of issue. I have setup Azure conditional access policy which require mobile devices to be enrolled through company portal before they can access to office 365 resources.

If i add "site" permission to my Azure application the login flow always complains that the device need to be enrolled even it is already done and i believe this is happening because the iOS MSAL can't handle this certification based authentication? If MS Authenticator app is installed the login will work without any issue.

I would like to know what is the system limitation in this case? Don't get it when MS Authenticator app is installed why the login flow will succeed? I believe the Authenticator app is using same login methods as MSAL lib?

@antrix1989 @jasoncoolmax

**Comment by jasoncoolmax** [comment]
Hi @zounasL , in iOS, the user-installed certificate is stored in system keychain, while the certificate used to meet conditional access policy is stored in app keychain. System keychain is accessible by system webview while app keychain is accessible by embedded webview. Currently iOS doesn't provide a webview that can access them all. The above limitation creates the trouble for the scenario for Cert based auth + Device-based Conditional Access policy.

The reason Authenticator app can work is, we have some "special" work flow (which is not OAuth2) and special SSO artifacts in the Authenticator app that help get around this issue.
