### ISSUE TITLE
Add XCode 11.4 recommended project settings

### ISSUE THREAD

**Issue by arangato** [AzureAD/microsoft-authentication-library-for-objc#961]
XCode complains in issue navigator about MSAL project an suggests updating it to recommended settings.
Those recomended settings seem to add the following build configuration:

`ENABLE_HARDENED_RUNTIME = YES;`

and compiler flags:
`
CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED = YES;
CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS = YES;
CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF = YES;
`

**Comment by jasoncoolmax** [comment]
Hi @arangato, thank you bringing this up. we are going to address it. Thank you!

**Comment by NerevarineRule** [comment]
Hi @arangato,

Thank you for sharing this with us.

The next MSAL release will have the following options enabled by default:  
CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED,  
CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS, 
CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF.

However, enabling "ENABLE_HARDENED_RUNTIME" breaks MSAL iOS app, and, for that reason, we will keep it disabled for the time being.

Do you have specific reasons for wanting to enable hardened runtime? If so, could you please share them with us?


Thanks,
Peter

**Comment by barakwei** [comment]
@NerevarineRule thanks! Will the IdentityCore library get the same fixes?

**Comment by mipetriu** [comment]
Yes, we will make the same changes in IdentityCore.
