### ISSUE TITLE
This app could not be installed at this time Xcode 11.4

### ISSUE THREAD

**Issue by amaheshit** [AzureAD/microsoft-authentication-library-for-objc#962]
Unable to install the application on the simulator -

Domain: IXUserPresentableErrorDomain
Code: 1
Failure Reason: Could not install at this time.
Recovery Suggestion: Failed to load Info.plist from bundle at path /Users/username/Library/Developer/CoreSimulator/Devices/BD40F7-0819-4B06-817E-82C09ECA521D/data/Library/Caches/com.apple.mobile.installd.staging/temp.i7PH0O/extracted/Tracker_iOS.app/Frameworks/MSAL.framework; Extra info about plist: ACL=<not found> 
--
Failed to load Info.plist from bundle at path /Users/username/Library/Developer/CoreSimulator/Devices/BD4140F7-0819-4B06-817E-82C09ECA521D/data/Library/Caches/com.apple.mobile.installd.staging/temp.i7PH0O/extracted/Tracker_iOS.app/Frameworks/MSAL.framework; Extra info about plist: ACL=<not found> 
Domain: MIInstallerErrorDomain
Code: 35
User Info: {
    FunctionName = "-[MIBundle _validateWithError:]";
    LegacyErrorString = PackageInspectionFailed;
    SourceFileLine = 128;
}
--

System Information

macOS Version 10.15.3 (Build 19D76)
Xcode 11.4 (16134)

**Comment by jasoncoolmax** [comment]
@amaheshit Are you trying to build from MSAL source code? which target are you trying to build? MSAL Test App (iOS) or MSAL Test App (mac)? 
Once I get the above info, i will see if i could repro. Thank you!
