### ISSUE TITLE
Not smooth

### ISSUE THREAD

**Issue by ws752958369** [AzureAD/microsoft-authentication-library-for-objc#964]
When we integrate the MSAL SDK and Intune SDK after we found the app CPU and memory footprint is very high, cause equipment heating validation, further lead to app is not smooth, even the caton.

**Comment by ws752958369** [comment]
And this happened on the app signed by AppSote

**Comment by oldalton** [comment]
Seems similar to this issue inside Intune SDK: https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/922

@Kyle-Reis, @ShruthiAchutha - can you take a look?

**Comment by ShruthiAchutha** [comment]
@ws752958369 we have a fix pending for a similar issue that should be ready by early next week. 
Have you integrated the app with Intune diagnostic console as described at https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#how-can-i-troubleshoot-my-app? If so, can you share the MAM log file from the app?

**Comment by ws752958369** [comment]
yes,i have removed i386,x86_64  before subimt to AppStore

**Comment by ShruthiAchutha** [comment]
@ws752958369 my question was about integrating with diagnostic console that's at the top of the section (copying below for clarity),

How can I troubleshoot my app?
The Intune SDK for iOS 9.0.3+ supports the ability to add a diagnostics console within the mobile app for testing policies and logging errors. IntuneMAMDiagnosticConsole.h defines the IntuneMAMDiagnosticConsole class interface, which developers can use to display the Intune diagnostic console. This allows end users or developers during test to collect and share Intune logs to help diagnose any issue they may have. This API is optional for integrators.

**Comment by ws752958369** [comment]
[IntuneMAM.zip](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/4802296/IntuneMAM.zip)
Here is the sandbox log of IntuneMAN，Please help check the problem。Thank you so much.

**Comment by ws752958369** [comment]
![图片](https://user-images.githubusercontent.com/15607355/85093687-86971500-b21f-11ea-839b-6cb52d6841ee.png)
When we first install, the Welcome Page of the App will appear.When we want to swipe left and right, the app is very stagnant at this time, and the mobile phone device begins to heat up seriously

**Comment by ws752958369** [comment]
We found that when the Intune SDK was removed, it was smooth

**Comment by ShruthiAchutha** [comment]
@ws752958369 This is a bug in Intune SDK. We will be releasing a new version that has the fix later this week.

**Comment by ws752958369** [comment]
@ShruthiAchutha ok,If you have completed the upgrade, please let us know.Thanks!

**Comment by Kyle-Reis** [comment]
Hi @ws752958369, could you try out the [latest version](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest) of the Intune SDK? I think that should address this issue. Thanks!

**Comment by oldalton** [comment]
@ws752958369, was the issue resolved for you with the Intune SDK update? Thanks.

**Comment by oldalton** [comment]
Closing as this should be now fixed with the latest Intune SDK update.
