### ISSUE TITLE
Endless loop if you have Microsoft Authenticator on user device.

### ISSUE THREAD

**Issue by jaywadhwani** [AzureAD/microsoft-authentication-library-for-objc#968]
We are having issue only when we have our App & Microsoft Authenticator both app on users device.

Steps to reproduce : -

Precondition - Download Microsoft authenticator from App Store.

1. Click on  sign in.
   applicationContext.acquireToken is triggered

2. Now observe deeplinks to Microsoft Authenticator.

applicationContext.acquireToken returns error : -
result	MSALResult?	nil	none
error	Error?	domain: "MSALErrorDomain" - code: 18446744073709501616	0x0000000283004090

 Actual:
Deeplinks to Microsoft Authenticator.

Expected :
User should navigated to sign in.

MSALresult should return to make sequence to getContentWithToken()

**Comment by jaywadhwani** [comment]
@oldalton any updates ?

**Comment by antrix1989** [comment]
This is not a valid error code: 18446744073709501616, could you provide us MSALError code which you are getting back from the Authenticator? Also would be great if you could provide us Authenticator logs as well. See [here](https://github.com/AzureAD/azure-activedirectory-library-for-objc/wiki/Instructions-on-Collecting-Microsoft-Authenticator-Logs) how to collect them.

**Comment by jaywadhwani** [comment]
So here is Incident Id from Authenticator "JD3MANUB"

error object from   applicationContext.acquireToken(with: parameters)

Optional<Error>
  - some : Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=application did not receive response from broker., MSALInternalErrorCodeKey=-42700}

**Comment by oldalton** [comment]
@jaywadhwani, you might be missing an AppDelegate callback. Can you double check this: https://github.com/AzureAD/microsoft-authentication-library-for-objc#swift-1

**Comment by jaywadhwani** [comment]
Thanks @oldalton the endless loop issue is resolved. Is there a way we can avoid our app to stop deep linking to MS authenticator ?

**Comment by antrix1989** [comment]
If you support personal and org accounts you need to auth through broker. If you just have personal accounts you can disable broker if you set brokerAvailability = MSALBrokeredAvailabilityNone in global config.

**Comment by jaywadhwani** [comment]
Thanks @antrix1989 & @oldalton Issue resolved closing issue.
