### ISSUE TITLE
Failed to acquire authentication token for Teams

### ISSUE THREAD

**Issue by jasminppiri** [AzureAD/microsoft-authentication-library-for-objc#969]
Unable to get authentication token for "Team.ReadBasic.All" scope.

Always get below error.
**Error Domain=MSALErrorDomain Code=-50003 "(null)" UserInfo={MSALDeclinedScopesKey=(
    "Team.ReadBasic.All"
), MSALGrantedScopesKey=(
    "User.Read",
    "Calendars.Read"
), MSALErrorDescriptionKey=Server returned less scopes than requested, MSALCorrelationIDKey=0021DD1E-DFFB-49C2-949C-85DC2C465FE2, MSALInvalidResultKey=<MSALResult: 0x600003321020>}**

Code i am using for call authentication api.

```
private let publicClient: MSALPublicClientApplication?

public func getTokenInteractively(parentView: UIViewController, completion: @escaping(_ accessToken: String?, Error?) -> Void) {
        let webParameters = MSALWebviewParameters(parentViewController: parentView)
        let interactiveParameters = MSALInteractiveTokenParameters(scopes: ["User.Read", "Team.ReadBasic.All", "Calendars.Read"],
                                                                   webviewParameters: webParameters)
        interactiveParameters.promptType = MSALPromptType.selectAccount

        // Call acquireToken to open a browser so the user can sign in
        publicClient?.acquireToken(with: interactiveParameters, completionBlock: {
            (result: MSALResult?, error: Error?) in
            guard let tokenResult = result, error == nil else {
                print("Error getting token interactively: \(String(describing: error))")
                completion(nil, error)
                return
            }

            print("Got token interactively: \(tokenResult.accessToken)")
            completion(tokenResult.accessToken, nil)
        })
}

```

Screenshot of configured permissions in azure console.

![API_Permission](https://user-images.githubusercontent.com/66630825/85613608-ae4f0880-b677-11ea-8f9c-3f6a18ff0501.png)

System Information: 

macOS Version 10.15.5 (19F101)
Xcode Version 11.5 (11E608c)

Let me know if i am doing anything wrong or i need to do additional things to call Teams API.

**Comment by jasminppiri** [comment]
@oldalton can you please help?

**Comment by oldalton** [comment]
@jasminppiri, I believe Team.ReadBasic.All is only applicable to AAD (organizational, work or school) accounts.
You're trying to sign in with a personal account, so the scope is ignored.

**Comment by oldalton** [comment]
Also the scope you're trying to acquire a token for is related to team management and not Teams API. Just double checking to avoid confusion:


Team.ReadBasic.All | Read the names and descriptions of teams | Read the names and descriptions of teams, on behalf of the signed-in user. | Yes | No
-- | -- | -- | -- | --

**Comment by jasminppiri** [comment]
Okay Thanks @oldalton

**Comment by jasminppiri** [comment]
Hello @oldalton ,

As per your instruction, now i am using organizational account and trying to acquire access token for "Channel.ReadBasic.All", "ChannelMessage.Send", "Team.ReadBasic.All", "User.Read" scopes but i got error like you need admin approval.

![adminApproval](https://user-images.githubusercontent.com/66630825/86048105-93acd300-ba6d-11ea-97bc-907c3f6d632e.png)

On azure portal these scopes don't required admin consent.

![azurePortal](https://user-images.githubusercontent.com/66630825/86047643-d02bff00-ba6c-11ea-8cdc-5be6e15ae706.png)

I am using same code for call authentication api which i added on above message.

**Note: I am able to get token with same account for these scopes with Graph Explorer.**

Please check and let me know if i miss anything.

**Comment by jasminppiri** [comment]
@oldalton  @antrix1989  can you guys help?
