### ISSUE TITLE
Issue on Mac 10.15 while fetching token Interactively. Getting error "ASWebAuthenticationSession without providing presentation context"

### ISSUE THREAD

**Issue by vinod-singh1** [AzureAD/microsoft-authentication-library-for-objc#970]
I am using MSAL.framework version 1.1.2 and built a dynamic library in Objective-C to fetch the tokens Interactively & Silently for different scopes.
This dynamic lib is loaded in a CommandLine application to perform Interactive & Silent authentication for fetching tokens. Inside the CommandLine application, I have used NSApplication* pApplication = [NSApplication sharedApplication]; mechanism to call Objective-C dylib and launching Microsoft Authentication UI popup for authentication from CommandLine app.
This is working fine in 10.13 & 10.14 and launching Authentication popup successfully whereas it is failing on 10.15.
I am getting below error while launching the Microsoft Authentication UI popup during Interactive authentication.
********************************************
"Cannot start ASWebAuthenticationSession without providing presentation context. Set presentationContextProvider before calling -start." UserInfo={NSDebugDescription=Cannot start ASWebAuthenticationSession without providing presentation context. Set presentationContextProvider before calling -start.}
********************************************
I have gone through below links as well and it seems that this issue was fixed for iOS13 version. But I didn't find any link/document for the fix on Mac OSX 10.15 version.
[https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/603](url)
[https://github.com/AzureAD/microsoft-authentication-library-for-objc/wiki/iOS-13-and-macOS-10.15-support-in-MSAL](url)

Need your help to suggest the appropriate way to solve this issue or the correct MSAL version having this fix.

Thanks in advance!!!

**Comment by vinod-singh1** [comment]
Further I have investigated and found the below comment in MSAL lib. Since in my CommandLine app there is no parentViewController which I can pass. So it should use the application's keyWindow presentation but this is not working in my case.
Can you please help me out to resolve this issue?
/**
   Creates an instance of MSALWebviewParameters with a provided parentViewController.
   @param parentViewController The view controller to present authorization UI from.
   @note parentViewController is mandatory on iOS 13+. It is strongly recommended on macOS 10.15+ to allow correct presentation of ASWebAuthenticationSession. If parentViewController is not provided on macOS 10.15+, MSAL will use application's keyWindow for presentation
*/
- (nonnull instancetype)initWithAuthPresentationViewController:(MSALViewController *)parentViewController;

**Comment by vinod-singh1** [comment]
I did more investigation and found a way to set WebviewType(as below) as "MSALWebviewTypeWKWebView" and doing this change I am able to launch the Authentication popup UI on Mac OS 10.15.
****************************************************
MSALWebviewParameters *webParameters = [[MSALWebviewParameters alloc] init];
    [webParameters setWebviewType:MSALWebviewTypeWKWebView];
****************************************************

Can you please validate that using this view type is the right approach or not?

**Comment by oldalton** [comment]
Thanks for confirming. WKWebView should work. However, you'll not benefit from SSO with Safari using WKWebView, but you should be able to get a token for the user. Another idea is if you don't have any windows for your app, you could try creating a new window for MSAL authentication prior to calling acquireToken and passing that window's controller to MSAL.

**Comment by vinod-singh1** [comment]
Thanks for updating that we should use the recommended "ASWebAuthenticationSession" view type to take full advantage of MSAL lib. Since 

Command Line app doesn't have the Window itself, so Can you please suggests the way to create a Window in Command Line and pass it to the MSAL lib for Authentication?

Just wanted to confirm that this view type is specific to Mac 10.15 onwards, in prior version like 10.14, SSO benefit is available in supported view type itself?

**Comment by vinod-singh1** [comment]
@oldalton @antrix1989 any update on this please?

**Comment by antrix1989** [comment]
You will need to create app delegate and start NSApplication. See an example [here](https://stackoverflow.com/questions/15957819/objective-c-how-to-make-gui-window-from-terminal-app/15958586).
