### ISSUE TITLE
Failed acquired authentication token

### ISSUE THREAD

**Issue by jasminppiri** [AzureAD/microsoft-authentication-library-for-objc#979]
Hello @oldalton ,

I am trying to acquire access token for "Channel.ReadBasic.All", "ChannelMessage.Send", "Team.ReadBasic.All", "User.Read" scopes but i got error like you need admin approval.

![adminApproval](https://user-images.githubusercontent.com/66630825/86161525-00d26e00-bb2b-11ea-999f-8373d8cab4ff.png)

As per azure portal, these four scopes don't required admin consent.

![azurePortal](https://user-images.githubusercontent.com/66630825/86161550-0760e580-bb2b-11ea-89a8-c51b7ef09432.png)

So can you please help to solve this issue?

**Note: I am able to get token with same account on Graph Explorer and also able to send message without admin consent.**

**Comment by oldalton** [comment]
MSAL also requests "openid profile offline_access" scopes which might be triggering admin consent for you.
Can you try requesting https://graph.microsoft.com/.default as a scope instead and seeing if it changes the result?

**Comment by jasminppiri** [comment]
So you want me to request this on graph explorer?

**Comment by jasminppiri** [comment]
@oldalton 
If you mean that try with default scope(User.Read) then i have already tried and with that i can able to get token but when i adding teams scopes(Channel.ReadBasic.All, ChannelMessage.Send, Team.ReadBasic.All) then i am getting error that admin approval required.

**Comment by jasminppiri** [comment]
@oldalton 
I have added "https://graph.microsoft.com/.default" this as scope and able to get token.

**Comment by oldalton** [comment]
I meant using https://graph.microsoft.com/.default as the scope that you pass to MSAL.

**Comment by jasminppiri** [comment]
@oldalton Yes i have added and got the token. It doesn't ask for admin approval.

**Comment by oldalton** [comment]
Thanks for confirming. I believe you have a workaround in that case.
Regarding seeing admin consent in another case, it is probably because MSAL requests OIDC scopes "openid profile offline_access" that might require admin consent for your tenant.

**Comment by jasminppiri** [comment]
@oldalton  Actually I don't have any workaround.

Yes MSAL request OIDC scopes and these scopes added by default in MSAL but i don't think those scopes trigger admin consent because when i have added only once scope(User.Read) then i can able to get token without admin approval so in this case i have added only one scope(User.Read) and other OIDC scopes "openid profile offline_access" added by default but still i can able to get token.

If OIDC scopes required admin consent then only one scope(User.Read) should also ask admin consent but it didn't.

**Comment by jasminppiri** [comment]
@oldalton  I also removed OIDC scopes and tried with only "Channel.ReadBasic.All", "ChannelMessage.Send", "Team.ReadBasic.All", "User.Read" these scopes and still it ask for admin approval.

**Comment by jasminppiri** [comment]
@oldalton  I want to get token for "Channel.ReadBasic.All", "ChannelMessage.Send", "Team.ReadBasic.All", "User.Read" these scopes without admin consent.

Please let me know if i can do this or not?

**Comment by jasminppiri** [comment]
@oldalton I have also created login url like this way and open in chrome and safari browser directly on my pc but still it's ask for admin approval.

![BrowserLogin](https://user-images.githubusercontent.com/66630825/86270400-ce874600-bbe8-11ea-8f15-1eaac6877252.png)

**Comment by psignoret** [comment]
@jasminppiri Each organization can change whether users are allowed to consent, and can set a policy to limit/control which permissions and which apps users can consent to.  In your case, the user you are testing with is not allowed to consent to one or more of the permissions your app requires. probably because the user's organization has disabled user consent entirely, or has limited user consent to only certain permissions: https://docs.microsoft.com/azure/active-directory/manage-apps/configure-user-consent

**Comment by ashishLanghe-iOS** [comment]
Hi @oldalton 

I'm not able to execute MSAL SDK. I'm getting below mentioned issue while redirecting to SignIn.

My System Configuration :*

Mac OS : macOS High Sierra
XCode Ver : Version 10.1 (10B61)

**Issue :**

```
2020-07-20 19:16:48.965067+0530 qwerty[66144:4049892] -canOpenURL: failed for URL: "msauthv2://broker" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
2020-07-20 19:16:49.311753+0530 qwerty[66144:4052462] Failed to query AuthBrokerAgent Task <49DC4AA3-FAC7-4268-94DA-41FE68FD584F>.<1>
2020-07-20 19:16:49.313138+0530 qwerty[66144:4052462] CredStore - performQuery - Error copying matching creds.  Error=-25300, query={
    class = inet;
    "m_Limit" = "m_LimitAll";
    ptcl = htsx;
    "r_Attributes" = 1;
    srvr = "intpxy1.hk.hsbc";
    sync = syna;
}
2020-07-20 19:16:49.319596+0530 qwerty[66144:4052462] Failed to get applicable proxy auth Task <49DC4AA3-FAC7-4268-94DA-41FE68FD584F>.<1>
2020-07-20 19:16:49.455326+0530 qwerty[66144:4050095] Task <49DC4AA3-FAC7-4268-94DA-41FE68FD584F>.<1> HTTP load failed (error code: 311 [4:-2097])
2020-07-20 19:16:49.455602+0530 qwerty[66144:4052461] Task <49DC4AA3-FAC7-4268-94DA-41FE68FD584F>.<1> finished with error - code: 311
App error: Error Domain=kCFErrorDomainCFNetwork Code=311 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2097, _kCFStreamErrorDomainKey=4}
2020-07-20 19:18:49.052179+0530 qwerty[66144:4052475] Received XPC error Connection interrupted for message type 3 kCFNetworkAgentXPCMessageTypePACQuery
2020-07-20 19:18:49.052957+0530 qwerty[66144:4052475] Received XPC error Connection invalid for message type 3 kCFNetworkAgentXPCMessageTypePACQuery
```
Please help me to resolve this issue.
