### ISSUE TITLE
Is it possible to use this library with the SwiftUI App Lifecycle?

### ISSUE THREAD

**Issue by steveplatz** [AzureAD/microsoft-authentication-library-for-objc#983]
In Xcode 12, Apple introduced the SwiftUI App Lifecycle that uses an App protocol, instead of Scene or App delegates, when launching apps. Is it possible to use this library with the new way of creating SwiftUI-based apps?

**Comment by rohitnarula7176** [comment]
@steveplatz The library should work regardless as along on receiving the callback from native app, you invoke MSAL's api as follows:
`- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options
{
    (void)app;
    (void)url;
    (void)options;
    NSLog(@"OpenURL Method! - MSALWebviewTypeSafariViewController");
    
    return [MSALPublicClientApplication handleMSALResponse:url sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]];
}
`

**Comment by steveplatz** [comment]
@rohitnarula7176 That part makes sense. Where I was having trouble is with the web view parameters

    auth.webViewParameters = MSALWebviewParameters(authPresentationViewController: ???)

No `UIHostingController` or other view controller is being created as part of the SwiftUI App lifecycle, so I'm sure what to pass to this constructor. I've tried specifying `MSALWebviewParameters(authPresentationViewController: UIHostingController(rootView: self))`, mimicking what's done in the `SceneDelegate` for the current view, but something seems to be lost and the MSAL UI never shows.

**Comment by kaisong1990** [comment]
Hi @steveplatz:

Instead of using MSAL directly in View, I would suggest creating a new viewController and add the UIHostingController which hosts your SwiftUI view as a child of the viewController you created. In that way you can still use the SwiftUI to render all UI while the new viewController may handle MSAL related code

**Comment by steveplatz** [comment]
That makes sense. So, there’s no way to keep everything 100% SwiftUI when using this library right now?

**Comment by kaisong1990** [comment]
@steveplatz Not at this moment, but we may support it naturally in the future. Please keep MSAL up-to-date :)

**Comment by steveplatz** [comment]
Thanks for the clarification! I appreciate your help on this.
