### ISSUE TITLE
Is there a way of caching tokens other than keychain in Mac OSX

### ISSUE THREAD

**Issue by vinod-singh1** [AzureAD/microsoft-authentication-library-for-objc#991]
I am using MSAL Objective C framework to build an application for authentication and fetching tokens. This MSAL is doing Interactive and silent authentication based on authentication info is cached or not.
It is caching the authentication info in keychain on OSX. 
Instead of storing it in keychain, Is there any API or some other way we can cache this authentication info either in file system or DB?
I have verified in Windows .Net implementation of MSAL lib, there is a way we can override this default caching location. Can similar be done for Mac also?
Thanks in advance!!!

**Comment by mipetriu** [comment]
Hi @vinod-singh1, we do not provide any other cache implementations besides the login and iCloud keychain.

**Comment by vinod-singh1** [comment]
> Hi @vinod-singh1, we do not provide any other cache implementations besides the login and iCloud keychain.

On Mac 10.15 the keychain entries are created under "Local Items" not under login and their access control is non editable. Since we want to add ACL's for keychain and we can't due to this.

How we can create keychain entries under login/iCloud?

Thanks!!!

**Comment by mipetriu** [comment]
Starting in 10.15, Apple introducted iCloud keychain saving on Mac. With this change, our library does not fall back to login keychain for 10.15 and above. You can read more about this [here.](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-v2-keychain-objc?tabs=objc#macos)
