### ISSUE TITLE
macOS: Acquire token opens multiple session windows

### ISSUE THREAD

**Issue by eRDe33** [AzureAD/microsoft-authentication-library-for-objc#992]
Hello,

I am using the latest version of the MSAL library 1.1.5 on macOS Catalina 10.15.5. 

I came across strange behavior when I am trying to acquire token. Calling function `acquireToken(with:, completionBlock:)` sometimes will cause the interactive session window to appear multiple times.

After investigation I discovered that this issue is affected by the current state of the Safari app. If the Safari app is already running, everything works fine. But if the Safari app isn't running at the time my app call `acquireToken`, the login window is shown twice.

I've successfully replicated that issue in example app (https://github.com/Azure-Samples/ms-identity-macOS-swift-objc) without any changes in source code.

How to replicate:
1. Quit the Safari app.
2. Run the example app.
3. Click "Call Microsoft Graph API" button (which calls `acquireToken`).
4. Interactive session window is shown twice.

Have you seen this behavior before? Or is there any way how to fix that?

Thanks.

**Comment by kaisong1990** [comment]
@eRDe33 

Thanks for your posting. We were trying to reproduce the issue and it did happen occasionally. We have filed a bug to Apple.

If this blocks your current task, there is a workaround and  to use WKWebView instead:

   ``` webviewParameters.webviewType = MSALWebviewTypeWKWebView;```

We will post update here once we hear from Apple

**Comment by vinod-singh1** [comment]
@kaisong1990 
I have also observed the similar issue with latest version 1.1.5 of MSAL Objective C library. Is it Ok to use the other view type "WKWebView" as suggested by you. 
I mean does all the functionality will be supported with this view type as well?

**Comment by jasoncoolmax** [comment]
Hi @vinod-singh1, system webview and embedded webview both have pros and cons. There are many discussions going on regarding that. That's the reason why we provides both options to developers. For embedded webview, it won't share cookies with any other browser/webview in the device. So you may loose some SSO opportunities comparing to system webview. However, it has better support for some advanced features, like MAM condition policies, etc.

**Comment by mattvlas** [comment]
@kaisong1990 any updates from Apple on this issue?

**Comment by kaisong1990** [comment]
@mattvlas Thanks for following up. Apple requested for more information, and we provided early this week. Will update in this thread once we get more from Apple side.

**Comment by mattvlas** [comment]
@kaisong1990 reopening as this is still happening and causing intermittent UX issues. 

Any word on your end?

**Comment by kaisong1990** [comment]
@MAaronYeh We are not getting anything back from Apple since Aug last year. We will try with latest Big Sur this week and follow up again

**Comment by kaisong1990** [comment]
@mattvlas We tested on latest version of BigSure (11.2.3) with the old MSAL (1.1.5) where it can reproduce the issue earlier. Multi session windows cannot be reproduced anymore. Please do let us know if you still have issue with later version

**Comment by alexpenzWND** [comment]
@kaisong1990 I confirm the issue is still present on my BigSure (11.2.3) with latest MSAL v1.1.16.
Steps to reproduce are the same:
1. Quit safari
2. Press "Call Microsoft Graph API" button in example app
3. Press "Continue" in "“MSALMacOS” wants to use “microsoftonline.com” to sign in." window
4. See two login prompt with login.microsoftonline.com page open

**Comment by alexkozlowski** [comment]
Hello, I have been able to reproduce this issue on my Mac fairly consistently. I am running Big Sur 11.2.3 using MSAL 1.1.5
Every-time the MS prompt is shown there are two windows opened when we would only expect one. 

<img width="1222" alt="Screenshot 2021-04-16 at 10 35 01" src="https://user-images.githubusercontent.com/82642637/115005392-b9418680-9e9f-11eb-8596-1808c8004978.png">

**Comment by kaisong1990** [comment]
@alexpenzWND @alexkozlowski 

Thanks for reporting! Would you create a radar/feedback to Apple and attach the diagnose?

**Comment by shree1497** [comment]
I could reproduce this issue fairly consistently on macOS 10.15 Safari 14.1.2 and MacOS Bigsur 11.6 Safari 14.1.2 .
However after upgrading to safari 15.1, I was unable to reproduce this issue.

Upon further analysis, it seems that there is a bug in Apple's implementation of ASWebAuthenticationSession. I tried it with a sample application (No connection of MSAL anywhere) which used ASWebSessionAuthentication. And Lo, was able to reproduce this issue on Safari 14.1.2. Seems like apple fixed it in some release after that.
