### ISSUE TITLE
Authorization cycling for webviewType == .wkWebView/.safariViewController

### ISSUE THREAD

**Issue by pavelreva1998** [AzureAD/microsoft-authentication-library-for-objc#994]
Hello, 

I have authorization with MSAL within my project. The problem is the following, that it works fine with webviewType == .default, but it uses ASWebAuthenticationSession, which asks user permission for SSO, I don't have SSO and I just want to get rid of this prompt, the way I found is to set webviewType as wkWebView or safariViewController. But it seems, that, potentially, it requires some additional config, cause when I click even "Cancel" on the webview screen, it closes and opens again automatically.

So my question is how to avoid cycling for  .wkWebView/.safariViewController or how to get rid of prompt for ASWebAuthenticationSession

Thanks for your answer

**Comment by mipetriu** [comment]
If you set the `prefersEphemeralWebBrowserSession` to true when using ASWebAuthenticationSession, you should be able to skip the prompt. You can read more about the flag [here](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession/3237231-prefersephemeralwebbrowsersessio?language=objc).

**Comment by pavelreva1998** [comment]
Thanks a lot, it works flowless, but we can use this property only from iOS 13, what about lower iOS versions?

**Comment by pavelreva1998** [comment]
And what if we really want to use wkWebView, I know that it's not recommended, but we have this opportunity, so why does it cycle the authorization process?

**Comment by pavelreva1998** [comment]
wkWebView works for iOS 12, so, it can be closed, please, correct me if I'm wrong somewhere in my thoughts

**Comment by mipetriu** [comment]
I'm glad it works! Let us know if you have any further questions.
