### ISSUE TITLE
B2C token validation by msal libraby

### ISSUE THREAD

**Issue by rajesh-naik-by** [AzureAD/microsoft-authentication-library-for-objc#998]
I have a generic question about token validation from msal library for objc, does msal library takes care of validating below attributes from the token? or is it a responsibility of consumer to validate the token?

- Signature
- exp
- nbf
- iss
- aud

**Comment by mipetriu** [comment]
It is the responsibility of the resource to validate the token, not the client. More information about this is linked [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/tokens-overview#validation).
